### PR TITLE
[O11y][Oracle] Migrate `System Statistics` dashboard visualizations to kibana 8.6.0

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

- Migrate visualizations to lens for Oracle integration package

- Statistics for **Oracle** Lens migration:

<html>
<body>
<google-sheets-html-origin>

Oracle Dashboards | Before Migration |   | After Migration |   |
-- | -- | -- | -- | -- |
  | Lens | Visualization | Lens | Visualization
[Metrics Oracle] System Statistics | 0 | 8 | 8 | 0

</body>
</html>

## Checklist

- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that panels are populated with data.
- [x] I have verified that panels are not distorted after being migrated to lens.
- [x] I have updated screenshots of dashboard.
- [x] I have verified that data count are matching and panel aggregations are same as before.

## Author's checklist

- [x] Migrated panels should be removed from visualization folder.
- [x] Migrated visualizations are populating in Kibana version `8.6.0`. 

## Related issues

- Relates 
  - #5221 
  - #5753

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Review by agithomas — COMMENTED** [review]
I am seeing lot many negative values in the screenshot. Please review and correct. Encourage to use oracle docker or oracle instance to generate the values

**Comment by harnish-elastic** [comment]
> I am seeing lot many negative values in the screenshot. Please review and correct. Encourage to use oracle docker or oracle instance to generate the values

@agithomas, We have tried pulling the docker image which is mentioned in the integration package, but we don't have an access to pull the image. Could you please provide us an access so that we can setup the oracle and move forward. Please refer screenshot.

image

**Comment by agithomas** [comment]
> > I am seeing lot many negative values in the screenshot. Please review and correct. Encourage to use oracle docker or oracle instance to generate the values
> 
> @agithomas, We have tried pulling the docker image which is mentioned in the integration package, but we don't have an access to pull the image. Could you please provide us an access so that we can setup the oracle and move forward. Please refer screenshot.
> 
> image

Please login to docker.elastic.co before the pull.

**Review by agithomas — COMMENTED** [review]
Parse time is negative. Please check.

**Comment by harnish-elastic** [comment]
> Parse time is negative. Please check.

We have used the live instance. Now what happening is the parse time chart is using the differences aggregation. So what difference exactly do is, if the value is getting lesser than the previous value, the difference would be shown as negative in chart. Also this is the same behavior in the TSVB chart.

**Comment by agithomas** [comment]
> > Parse time is negative. Please check.
> 
> We have used the live instance. Now what happening is the parse time chart is using the differences aggregation. So what difference exactly do is, if the value is getting lesser than the previous value, the difference would be shown as negative in chart. Also this is the same behavior in the TSVB chart.

Got it. The current one looks good.

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
