### PR TITLE
[Cloud Security] Deprecate vulnerability data views

### PR DESCRIPTION
**Pull request by CohenIdo**
solves: 
- https://github.com/elastic/kibana/issues/190387

Associated Kibana PR:
- https://github.com/elastic/kibana/pull/191581

## Summary:
Beginning with version 8.16, the Cloud Security Posture integration's data view will be deprecated. Instead, CDR data views will be used, which will be installed independently rather than as an integration asset.

### CODE REVIEW

**Comment by maxcold** [comment]
@CohenIdo should we also add it to the changelog?
Btw , I realized that I don't really understand the following - am I correct that fixing a bug in an older version of the integration is not possible, as in released say 1.8.1 now

**Review by JordanSh — APPROVED** [review]

**Comment by CohenIdo** [comment]
> @CohenIdo should we also add it to the changelog? 
I added it to the changelog, probably you commented before I pushed it.

> am I correct that fixing a bug in an older version of the integration is not possible, as in released say 1.8.1 now

AFAIK it depends on the stack version:
```
# 1.8.x - 8.13.x
# 1.7.x - 8.12.x
# 1.6.x - 8.11.x
# 1.5.x - 8.10.x
# 1.4.x - 8.9.x
# 1.3.x - 8.8.x
# 1.2.x - 8.7.x
```
So for example if we want to push fix for a bug in 8.11 we can release (I guess) a patch for 1.6.x).
@maxcold Is it answer your question?

**Comment by maxcold** [comment]
@CohenIdo but in this new 1.6.x version the index pattern that you deleted will be missing, and it won't work for 8.11. Am I missing smth?

**Comment by CohenIdo** [comment]
> @CohenIdo but in this new 1.6.x version the index pattern that you deleted will be missing, and it won't work for 8.11. Am I missing smth?

The change we introduce here will not be available for stack 8.11 since this integration version [requires](https://github.com/elastic/integrations/pull/10913/files#diff-72fc27a4cf2fb28244c8fa9ed27c00e43935777a4875c5d61d91372f0d483425R14) stack 8.16^.

**Comment by maxcold** [comment]
@CohenIdo the thing I was missing is the process of backporting a change into an older package version https://www.elastic.co/guide/en/integrations-developer/current/developer-workflow-support-old-package.html

**Review by maxcold — APPROVED** [review]

**Pull request merged**
