### PR TITLE
[etcd] Add metric_type mapping for leader dataset

### PR DESCRIPTION
**Pull request by agithomas**
- Enhancement

## Proposed commit message

- Added metric_type mapping to leader datastream.
- To benefit from the TSDB enablement of the package.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- elastic-package build
- elastic-package stack up -v -d --services package-registry

## Related issues
- https://github.com/elastic/integrations/issues/8327

### CODE REVIEW

**Comment by agithomas** [comment]
**Validations**

<details>
<summary> time series - t0 </summary>

```json
{
  "leader": "91bc3c398fb3c146",
  "followers": {
    "8211f1d0f64f3269": {
      "latency": {
        "current": 0.002853,
        "average": 0.0060225,
        "standardDeviation": 0.004737272685839397,
        "minimum": 0.001533,
        "maximum": 0.015097
      },
      "counts": {
        "fail": 0,
        "success": 8
      }
    },
    "fd422379fda50e48": {
      "latency": {
        "current": 0.001762,
        "average": 0.004122999999999999,
        "standardDeviation": 0.0031665696344782956,
        "minimum": 0.001762,
        "maximum": 0.011871
      },
      "counts": {
        "fail": 0,
        "success": 8
      }
    }
  }
}
```

</details>

<details>
<summary>Timeseries - t1</summary>

```json

{
  "leader": "91bc3c398fb3c146",
  "followers": {
    "8211f1d0f64f3269": {
      "latency": {
        "current": 0.001362,
        "average": 0.004465928571428571,
        "standardDeviation": 0.004039304120837184,
        "minimum": 0.001362,
        "maximum": 0.015097
      },
      "counts": {
        "fail": 0,
        "success": 14
      }
    },
    "fd422379fda50e48": {
      "latency": {
        "current": 0.001726,
        "average": 0.003569214285714284,
        "standardDeviation": 0.0025458471275665367,
        "minimum": 0.001646,
        "maximum": 0.011871
      },
      "counts": {
        "fail": 0,
        "success": 14
      }
    }
  }
}


```
</details>

**Comment by agithomas** [comment]
<details>
<summary> Mappings validation </summary>

```json

  "leader": {
    "properties": {
      "follower": {
        "properties": {
          "failed_operations": {
            "type": "long"
          },
          "id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "latency": {
            "properties": {
              "ms": {
                "type": "float"
              }
            }
          },
          "leader": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "success_operations": {
            "type": "long"
          }
        }
      },
      "followers": {
        "properties": {
          "counts": {
            "properties": {
              "followers": {
                "properties": {
                  "counts": {
                    "properties": {
                      "fail": {
                        "type": "long",
                        "time_series_metric": "counter"
                      },
                      "success": {
                        "type": "long",
                        "time_series_metric": "counter"
                      }
                    }
                  }
                }
              }
            }
          },
          "latency": {
            "properties": {
              "followers": {
                "properties": {
                  "latency": {
                    "properties": {
                      "average": {
                        "type": "scaled_float",
                        "scaling_factor": 1000,
                        "time_series_metric": "gauge"
                      },
                      "current": {
                        "type": "scaled_float",
                        "scaling_factor": 1000,
                        "time_series_metric": "gauge"
                      },
                      "maximum": {
                        "type": "scaled_float",
                        "scaling_factor": 1000,
                        "time_series_metric": "gauge"
                      },
                      "minimum": {
                        "type": "long",
                        "time_series_metric": "gauge"
                      },
                      "standardDeviation": {
                        "type": "scaled_float",
                        "scaling_factor": 1000,
                        "time_series_metric": "gauge"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "leader": {
        "type": "keyword",
        "ignore_above": 1024
      }
    }
  }

```
</details>

**Review by ritalwar — APPROVED** [review]
LGTM!

**Comment by gpop63** [comment]
@agithomas I created an issue (#8373) for the wrong field definitions. Did you encounter the same thing?

**Comment by agithomas** [comment]
> @agithomas I created an issue (#8373) for the wrong field definitions. Did you encounter the same thing?

Yes, I have. In fact, i was trying my best to generate the data but couldn't. But, as the wrongly mapped fields are of type average, it was assigned to metric_type value `gauge`.

This is the extract that i got 

image

**Comment by mrodm** [comment]
Hi @agithomas, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

**Pull request closed without merging**
