### PR TITLE
[Kubernetes] Add support to kubernetes 1.30 version

### PR DESCRIPTION
**Pull request by MichaelKatsoulis**
## What does this PR do?

Add support for Kubernetes latest version 1.29.

## Related issues

Relates to https://github.com/elastic/observability-dev/issues/3068

### CODE REVIEW

**Review by jsoriano — APPROVED** [review]

**Review by constanca-m — APPROVED** [review]
Maybe add this PR link to the issue description to make it easier to find for the next person that needs to update to the 1.31 version

**Review by gizas — APPROVED** [review]

**Comment by MichaelKatsoulis** [comment]
> Maybe add this PR link to the issue description to make it easier to find for the next person that needs to update to the 1.31 version

Yes I will add all the Pre inks to the issue

**Comment by MichaelKatsoulis** [comment]
@elastic/ecosystem  team, tests are failing due to Terraform deployer container which remains unhealthy. There are no useful logs so to understand why. Do you have any idea ?
```
Error: error running package system tests: could not complete test run: could not setup service: Terraform deployer is unhealthy: container (ID: a326f556b46705bc18fe288e8c1b68472c3c0dee60fe5ccd1e2ac71166ea294f) exited with code 1
```

**Comment by mrodm** [comment]
> @elastic/ecosystem team, tests are failing due to Terraform deployer container which remains unhealthy. There are no useful logs so to understand why. Do you have any idea ?
> 
> ```
> Error: error running package system tests: could not complete test run: could not setup service: Terraform deployer is unhealthy: container (ID: a326f556b46705bc18fe288e8c1b68472c3c0dee60fe5ccd1e2ac71166ea294f) exited with code 1
> ```

Those packages are failing due to terraform cannot create the required resources. Those logs are in a private bucket. An example of this error is:
```
api error TooManyBuckets: You have attempted to create more buckets than allowed
```

Looking at your build, as the `kubernetes` and `cloud_security_posture` (it looks like this package has no system tests) packages finished successfully their tests, I guess it could be merged this PR. Let's wait until the build finishes at least.

**Pull request merged**
