### PR TITLE
Workaround: dump agent policy if line 47 error appears

### PR DESCRIPTION
**Pull request by mtojek**
This PR modifies the Jenkinsfile to safely store the agent policy if the `line 47` error appears.

Related: elastic/elastic-agent#98

### CODE REVIEW

**Comment by jlind23** [comment]
@elastic/elastic-agent-control-plane do you know what .fleet stands for?

**Comment by mtojek** [comment]
We suspect that it might be caused by a bug in yaml parser. The line should look like this:

```yaml
#   exponential: false
#     # Reporting threshold indicates how many events should be kept in-memory before reporting them to fleet.
#     #reporting_threshold: 10000
#     # Frequency used to check the queue of events to be sent out to fleet.
#     #reporting_check_frequency_sec: 30
``` 

The line `#     # Reporting threshold indicates how many events should be kept in-memory before reporting them to fleet.` is the longest one in the whole file. Maybe temporarily shorten it :)?

**Pull request closed without merging**
