### PR TITLE
Updating dependency on elastic-package

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

This PR updates the dependency on `elastic-package` for changing the location of where test reports are stored (https://github.com/elastic/elastic-package/pull/158).

### CODE REVIEW

**Comment by mtojek** [comment]
Hm... it looks like a non standard error:

```
[2020-11-09T09:57:55.269Z] Error: building package failed: building package failed (root: /var/lib/jenkins/workspace/gest-manager_integrations_PR-395/src/github.com/elastic/integrations/packages/apache): locating build directory failed: stat /var/lib/jenkins/workspace/gest-manager_integrations_PR-395/src/github.com/elastic/integrations/build/integrations: no such file or directory
[2020-11-09T09:57:55.269Z] Error: running elastic-package failed: running "/var/lib/jenkins/workspace/gest-manager_integrations_PR-395/src/github.com/elastic/integrations/build/elastic-package build" failed with exit code 1
```

**Comment by ycombinator** [comment]
Thanks @mtojek, I'm going to try and repro that error locally and update this PR as necessary.

**Comment by ycombinator** [comment]
run tests

**Comment by ycombinator** [comment]
I'm unable to reproduce this locally. If I run `mage build` the packages are built as expected.

@mtojek would you mind trying on your end please? If it works for you locally as well, I'll start adding some debugging statements to see what's going on in CI.

**Comment by mtojek** [comment]
I replicated the problem:

```
➜  integrations git:(test-report-folder) mage clean
➜  integrations git:(test-report-folder) mage build
packages/apache:
go: downloading github.com/elastic/elastic-package v0.0.0-20201109090234-263248735c28
elastic-package build
elastic-package has been installed.
Build the package
Error: building package failed: building package failed (root: /Users/marcin.tojek/go/src/github.com/elastic/integrations/packages/apache): locating build directory failed: stat /Users/marcin.tojek/go/src/github.com/elastic/integrations/build/integrations: no such file or directory
Error: running elastic-package failed: running "/Users/marcin.tojek/go/src/github.com/elastic/integrations/build/elastic-package build" failed with exit code 1
```

**Review by mtojek — CHANGES_REQUESTED** [review]
I suppose that the elastic-package needs a fix in code.

**Comment by ycombinator** [comment]
After running `mage clean`, I'm able to reproduce the issue locally as well. Thanks @mtojek. I'll work on a fix PR to `elastic-package`.

**Comment by ycombinator** [comment]
PR to fix `elastic-package`: https://github.com/elastic/elastic-package/pull/172

**Comment by mtojek** [comment]
I'm afraid that sth is still wrong here.

**Comment by ycombinator** [comment]
> I'm afraid that sth is still wrong here.

Yup, I've been working on the fix: https://github.com/elastic/elastic-package/pull/173.

**Comment by mtojek** [comment]
Would you mind to bump the dependency one more revision up to include changes in https://github.com/elastic/elastic-package/pull/171 ?

**Review by mtojek — COMMENTED** [review]
Looks like an update in `go.mod` is required.

**Review by mtojek — APPROVED** [review]

**Pull request merged**
