### PR TITLE
[O11y][InfluxDB] Lens migration for visualizations to Kibana version 8.3.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for InfluxDB integration package

- Statistics for InfluxDB Lens migration:

<html>
<body>
<google-sheets-html-origin>

  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[InfluxDB Metrics] Advanced Status Metrics | 0 | 9 | 9 | 0
[InfluxDB Metrics] Status Metrics | 0 | 18 | 18 | 0
  | 0 | 27 | 27 | 0

</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.3.0 itself.

## Related issues

- Relates #5221 

## Issues Identified
- https://github.com/elastic/integrations/issues/5506

**Note:** The size of panels has not been changed in `[InfluxDB Metrics] Advanced Status Metrics` dashboard. The screenshot of  `[InfluxDB Metrics] Advanced Status Metrics` dashboard and Kibana files are not synced. Please consider below screenshots to compare the migration changes.

`[InfluxDB Metrics] Advanced Status Metrics` dashboard before migration:
screencapture-storage-0-kb-us-central1-gcp-cloud-es-io-9243-app-dashboards-2023-03-21-13_07_56

`[InfluxDB Metrics] Advanced Status Metrics` dashboard after migration:
image

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Review by ritalwar — COMMENTED** [review]
Image size for advstatus.png and status.png is way too reduced compared to earlier ones.
There is no data for shard disk size in status.png, can we replace it with the one having some data in it?

Also, can you please resolve conflicts on this branch?

**Comment by rajvi-elastic** [comment]
> Image size for advstatus.png and status.png is way too reduced compared to earlier ones. There is no data for shard disk size in status.png, can we replace it with the one having some data in it?
> 
> Also, can you please resolve conflicts on this branch?

@ritalwar Can you please check the description, I have uploaded the screenshot of dashboard before migration as we haven't changed the size of panels. It seems like screenshots were not synced with Kibana files.

**Comment by agithomas** [comment]
Please address the conflicts.

**Comment by rajvi-elastic** [comment]
@agithomas, Merge conflicts has been resolved. 

As per the changes done in this [TSDB PR](https://github.com/elastic/integrations/pull/5312), the Kibana version was updated from `8.3.0` to `8.6.0`. Previously, we manually migrated the visualizations to 8.3.0 itself. Now we exported dashboards from `8.6.0`. So, there will be version changes in the json files from `8.3.0` -> `8.6.0`.

**Comment by agithomas** [comment]
LGTM!

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
