### PR TITLE
Spring boot package [Dashboards for all data streams]

### PR DESCRIPTION
**Pull request by sunny-elastic**
## What does this PR do?

- Generated the skeleton of Spring Boot integration package.
- Added dashboards for all data streams

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified visualisations considering all data streams 
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^8.0.0`).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/spring_boot directory.
- Run the following command to run tests. 
> elastic-package test 

## Screenshots

Spring Boot Dashboard

Note: We have covered dashboards and the visualisations for all data streams in this PR. Also Kibana version is updated in manifest.yml and tested with 8.1.0

### CODE REVIEW

**Review by mtojek — COMMENTED** [review]
I will take a look at dashboards once we agree on data streams and their fields.

**Review by yug-elastic — APPROVED** [review]
LGTM!
Let’s wait for other’s reviews over the dashboard.

**Review by mtojek — CHANGES_REQUESTED** [review]
As there are few data streams I think that you can go with a few dashboards. It's hard to deduce from the overview what's going on in the system, except reading current values.

My recommendation:
1. "Audit events" dashboard - show a table with latest events, IP address, session ID, principals, auth type. You can add 2 pie charts to show the percentage of failures (event type).
2.  Memory - include GC, heap, non-heap, manager. Please show using standard line-graphs that GC works as intended. It will be useful to look for memory leaks
3. Threading - (maybe combine them together with Memory) - show thread statistics using line-graphs. You can add "big values" to show the current state.
4. "Access logs" - that's the HTTP thread. Please take a look at Apache and model something 

.. and finally the "Overview"
5. Again, please take a look at the Apache integration and check if you can provide a similar experience, combining Apache's logs and metrics dashboards.

**Comment by sunny-elastic** [comment]
> As there are few data streams I think that you can go with a few dashboards. It's hard to deduce from the overview what's going on in the system, except reading current values.
> 
> My recommendation:
> 
> 1. "Audit events" dashboard - show a table with latest events, IP address, session ID, principals, auth type. You can add 2 pie charts to show the percentage of failures (event type).
> 2. Memory - include GC, heap, non-heap, manager. Please show using standard line-graphs that GC works as intended. It will be useful to look for memory leaks
> 3. Threading - (maybe combine them together with Memory) - show thread statistics using line-graphs. You can add "big values" to show the current state.
> 4. "Access logs" - that's the HTTP thread. Please take a look at Apache and model something
> 
> .. and finally the "Overview" 5. Again, please take a look at the Apache integration and check if you can provide a similar experience, combining Apache's logs and metrics dashboards.

Covered almost all points. Updated dashboards with respect to these changes

**Review by mtojek — APPROVED** [review]
LGTM!

**Pull request merged**
