### PR TITLE
fleet_server: changes for unified integration UI

### PR DESCRIPTION
**Pull request by endorama**
## What does this PR do?

Align package title and description for improved Unified Integration UI display.

## Checklist

- [ ] ~~I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.~~
- [ ] ~~I have verified that all data streams collect metrics or logs.~~
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] ~~If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).~~

## Author's Checklist

- [ ] promote package to staging
- [ ] promote package to production

## Related issues

- Part of https://github.com/elastic/integrations/issues/1901

### CODE REVIEW

**Review by ruflin — APPROVED** [review]
LGTM. I wonder if we could do some linting in the future to keep it consistent? Like checking if there is a `.` at the end of the description?

**Comment by endorama** [comment]
@ruflin [Looking at the document](https://docs.google.com/spreadsheets/d/1MbI69al5y9xCDmyu0SP63gOw9RuKPsgeoiB8vZa95IY/edit#gid=1803487246) that collects all titles and description the linting would be minimal, but it would surely helps with consistency.

What kind of linting where you thinking? On top of my mind:
- check title; should end with `Logs` (when package contains log types only), or `Metrics` (when package contains metric types only), or nothing (when it contains both).
- description ends with `.`

Should this be considered warning maybe, instead of errors?

**Comment by ruflin** [comment]
@mtojek What is your take on the above linting?

**Comment by mtojek** [comment]
I'm always for improving the wording/phrasing/UX consistency. We can introduce a pattern for package/data stream descriptions, but I'm wondering if it can be applied to all packages. The rule would be: description is a sentence (starts with a capital letter, ends with a period).

**Pull request merged**
