### PR TITLE
[O11y][Redis] Update value format of `Top Slowest command`  visualization

### LINKED ISSUE #7114: [O11y][Redis] Update human readable format in `Logs Overview` dashboard
### Workaround implemented during lens migration
Converted values to specific time format and migrated visualization to lens.
### Task
Update value format of  `Top Slowest command` visualization from `Logs Overview dashboard` once human readable format ( Seconds / Minutes / Hours ) is available in lens.
[[Reference](https://github.com/elastic/integrations/pull/5661#pullrequestreview-1371245897)]
image
## Related issues
- https://github.com/elastic/integrations/issues/5583
- https://github.com/elastic/kibana/issues/153378

## Screenshots
image

### PR DESCRIPTION
**Pull request by rajvi-elastic**
### Urgency
- High

### Activity Type
- Enhancement

## What does this PR do?

Update value format of  `Top Slowest command` visualization from `Logs Overview dashboard` once human readable format ( Seconds / Minutes / Hours ) is available in lens.
[[Reference](https://github.com/elastic/integrations/pull/5661#pullrequestreview-1371245897)]

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #7114

### Before
image
### After
image

### CODE REVIEW

**Review by milan-elastic — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
@rajvi-elastic , Isn't it possible that in the horizontal axis it is mentioned as Duration (ms) , as in the past and value is shown as 20, 30, 40... ?

its not very user-friendly to display 'millisecond' repeated in the horizontal axis.

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic , Is it possible that in the horizontal axis it is mentioned as Duration (ms) , as in the past and value is shown as 20, 30, 40... ?
> 
> its not very user-friendly to display 'millisecond' repeated in the horizontal axis.

Yes @agithomas, I have just checked and there is one parameter using which we can compact unit. I'll update PR with the changes.
image

**Comment by rajvi-elastic** [comment]
> Yes @agithomas, I have just checked and there is one parameter using which we can compact unit. I'll update PR with the changes. image

@agithomas, I have updated PR.

**Comment by agithomas** [comment]
What is the reason for the change in kibana version ? is this fix available only from 8.10?

**Comment by rajvi-elastic** [comment]
> What is the reason for the change in kibana version ? is this fix available only from 8.10?

Yes, that's right. ([reference](https://github.com/elastic/kibana/pull/162246))

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
