### PR TITLE
gcp: add keep_json option for audit, dns, firewall and vpcflow datastreams

### LINKED ISSUE #8184: proposal: gcp: add a `gcp.<datastream>.flattened` field for each of the datastreams
We have had customer requests to retain additonal fields in the GCP integration so that fields that we are currently removing from documents are available for them to use in detection rules. In particular this is in the audit datastream, but could be relevant to others.

I propose that we `rename` the `json` temporary field to `gcp.<datastream>.flattened` (or similar) which would be mapped either as a `type: flattened` or `index: false`. We would also add a configuration option to the datastream UI that sets a default `false` flag, `keep_json`. In the ingest pipeline this flag would be used to conditionally `remove` the `gcp.<datastream>.flattened` field if not `true`.

For current users, this would have no impact as the field would by default no be in their ingested documents, but for users wishing to use fields that we have otherwise dropped, they can set the option to `true` and in their `@custom` pipeline (and associated mapping definition) they can extract and process the fields that they are interested in and then optionally `remove` the `gcp.<datastream>.flattened` field if they do not need it further.

Note that this functionality can be achieved currently with additional work by adding an `@custom` pipeline that would `{"json":{"field":"event.original","target_field":"_tmp_json","if":"ctx.event?.original != null"}}`, doing the additional processing and then deleting `_tmp_json` (or giving it a more durable name and adding it appropriately to the mappings).

### PR DESCRIPTION
**Pull request by efd6**
## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## Related issues

- Closes #8184

### CODE REVIEW

**Comment by P1llus** [comment]
I think the change itself is great! I like these approaches and fully support it, however I would have liked the renames to stay as renames, rather than using set, as the user is usually after fields we are deleting and not the ones we have already renamed, this also makes the flattened object much smaller and we do not need to duplicate data.

This opens up one of the discussions we have had on the team a few times further in the past, and something I was always a bit against.
When we created integrations in the past from JSON payloads, what I liked to do was that I used the JSON processor from source field directly into the correct destination field (like gcp.audit), this has some pros and cons:
Pros:
1. We do not need to constantly cherry-pick which fields goes from the original JSON to the destination, but rather remove the few we do not want.
2. If new fields are introduced, they will not be automatically removed.
Cons:
1. New or missed fields will not have a field type mapped, which can cause issues down the line.

I like the flattened approach here! I believe we should discuss it further at a separate time, and change how we do our unpacking of JSON in general (default to flattened destination and cherry-pick renames out of the flattened field? Leaving any missed or newly added fields in flattened?

Still, I would really like to push for using renames rather than sets on as many as possible!

**Comment by efd6** [comment]
I am torn about the rename v copy; as you can see from the original issue I was using renames. The code changes are much simpler with renames since we don't need to spend so much care on making sure that everything remains in the final flattened field. We also have fewer (~0) futile allocations. The reason I went with the copies here (I did intend to note all this here, but forgot) is the simplicity in documenting behaviour in the copies case compared to the renames case; documenting the copies case is simple and clear, while the renames case has a bunch of understanding required by the user (including reading and understanding the ingest pipeline). I'd like to fully understand the perf implications of copy v rename here, but memory behaviour in Java is a dark art that I know little about.

**Comment by P1llus** [comment]
After some further discussion I think its fine to keep it this way, I just felt it was a bit too close to event.original, and the only reason we have this is so we do not have to use the JSON processor on event.original again. and it felt like a waste, it also puts the pressure on the end-user to remove this large duplicate object at the end to not incur storage cost.

**Comment by P1llus** [comment]
I would like to wait for @andrewkroh opinion on this as well.

We could also just not implement it, and ask users to run the JSON processor on event.original. If the performance is a concern, I would have liked to know a bit more about the statistics used to determine that the JSON processor is actually more heavy than having to pass this large duplicate object through the pipeline.

**Comment by andrewkroh** [comment]
If we copy, then downstream consumers of the field are less affected by changes when we map a new field (i.e. the flattened field's value is more stable). The downside is increased storage costs for keep_json. You would probably even want disable `preserve_original_event` if you used `keep_json` since those are close to duplicative.

If we rename, then the value in the flat field is less stable and less reflective of the original data which probably makes maintaining any follow-on custom pipelines more difficult.

As a custom pipeline author I would probably ask for "copy" because it gives me the greatest control.

**Comment by efd6** [comment]
I'd be reluctant to automatically disable `preserve_original_event`, but I do think it's worth documenting in the `keep_json` option that this is recommended. I agree that the copy is least surprising, and will add docs to note the potential costs of retaining the data.

**Review by andrewkroh — APPROVED** [review]

**Pull request merged**
