### PR TITLE
[O11y][ActiveMQ] Lens migration for visualizations to Kibana version 8.2.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for ActiveMQ integration package

- Statistics for ActiveMQ Lens migration:

<html>
<body>
<google-sheets-html-origin>

  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Logs ActiveMQ] Audit | 0 | 3 | 3 | 0
[Logs ActiveMQ] Broker | 0 | 6 | 6 | 0
[Logs ActiveMQ] Log | 0 | 2 | 2 | 0
[Logs ActiveMQ] Queues | 0 | 8 | 8 | 0
[Logs ActiveMQ] Topics | 0 | 8 | 8 | 0
  | 0 | 27 | 27 | 0

</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.2.0 itself.

## Related issues

- Relates #5221 

## Issues Identified
- The TagCloud visualizations are not supported in the lens. Hence, the TagCloud visualization is converted to the horizontal bar chart as per [this comment](https://github.com/elastic/integrations/pull/4915#issuecomment-1414368282).
https://github.com/elastic/kibana/issues/95542
- Splitting a chart into multiple smaller charts by a breakdown dimension is not supported in lens. However, the split chart layer used in **Audit Event Results [Logs ActiveMQ]** panel from **[Logs ActiveMQ] Audit** dashboard was redundant and removing that layer does not impact the functionality of panel. As a result, the split chart layer is removed in order to migrate visualization to lens.
https://github.com/elastic/kibana/issues/72063
- TSVB visualization doesn’t show negative values in UI. But the lens shows both negative and positive values. (This will be fixed in 8.8)
 https://github.com/elastic/elastic-charts/issues/135

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Review by muthu-mps — COMMENTED** [review]
Can we rename the image names by removing the filebeat and metricbeat prefix ?

**Comment by rajvi-elastic** [comment]
> Can we rename the image names by removing the filebeat and metricbeat prefix ?

These names are already there in the current codebase. This is just the lens migration PR so we won't be changing any behavior/files as a part of this PR otherwise it will mess it up. However, If you strongly feel that this change needs to be done then we can raise a separate issue for that and track them separately.

**Review by muthu-mps — APPROVED** [review]
looks good !

**Comment by rajvi-elastic** [comment]
@agithomas, @muthu-mps has approved the PR. Can you please review it so that we can proceed further?

**Comment by agithomas** [comment]
> @agithomas, @muthu-mps has approved the PR. Can you please review it so that we can proceed further?

One approver is enough. You may please proceed with the merge.

**Pull request merged**
