### PR TITLE
[kibana] add documentation for alert metricsets

### PR DESCRIPTION
**Pull request by klacabane**
### Summary

Closes https://github.com/elastic/integrations/issues/3977

Adds the standard documentation for the new metricsets introduced in https://github.com/elastic/beats/pull/29899, the data streams were created in https://github.com/elastic/integrations/pull/3965

### CODE REVIEW

**Comment by klacabane** [comment]
@elastic/response-ops I've added a placeholder[1] description for each metricset, could you please provide a short summary of what these metricsets are ? This documentation is publicly accessible and will show up in the Kibana Integrations UI when looking at the kibana package.

These are the new metricset that need a summary: `cluster_actions` `cluster_rules` `node_actions` `node_rules`

[1] {metricset} metrics documentation

**Review by miltonhultgren — APPROVED** [review]
I'm a bit confused by how some of the docs are written, for the ECS fields we seem to be documenting what the ECS field means but also how it should be populated when implementing the spec, but doesn't isn't the integration the implementation already?

**Comment by klacabane** [comment]
@miltonhultgren so this is what the `type: external` is for, to pull the documentation from the ecs repo (see service fields https://github.com/elastic/ecs/blob/main/schemas/service.yml#L176)

**Comment by klacabane** [comment]
No updates from @elastic/response-ops, I've also notified the team in slack. Let's merge as-is and follow up with a separate PR

**Pull request merged**
