### PR TITLE
[GCP] Convert GCP Compute metricset from lightweight

### LINKED ISSUE #3721: [GCP] Remove lightweight module in `gcp.compute` data stream
Part of #3188

- [ ] For the migrated data streams (from Bests): we should move the configuration part from Beats into integrations.
- [ ] For all data streams: use ingest pipeline instead of rename processor.

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Convert GCP Compute metricset from lightweight

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Closes #3721

### CODE REVIEW

**Review by r00tu53r — APPROVED** [review]

**Comment by legoguy1000** [comment]
@endorama can we merge this?

**Comment by legoguy1000** [comment]
@endorama Is this able to be merged?

**Comment by legoguy1000** [comment]
@kaiyan-sheng Can u review?

**Review by kaiyan-sheng — APPROVED** [review]

**Pull request merged**
