### PR TITLE
[Oracle] Add system testing files

### PR DESCRIPTION
**Pull request by agithomas**
## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by agithomas** [comment]
```
--- Test results for package: oracle - START ---
╭─────────┬───────────────────┬───────────┬───────────┬────────┬─────────────────╮
│ PACKAGE │ DATA STREAM       │ TEST TYPE │ TEST NAME │ RESULT │    TIME ELAPSED │
├─────────┼───────────────────┼───────────┼───────────┼────────┼─────────────────┤
│ oracle  │ database_audit    │ system    │ logfile   │ PASS   │   25.639576677s │
│ oracle  │ memory            │ system    │ memory    │ PASS   │ 3m16.987115667s │
│ oracle  │ performance       │ system    │ memory    │ PASS   │ 3m17.470738462s │
│ oracle  │ sysmetric         │ system    │ memory    │ PASS   │ 3m14.525228005s │
│ oracle  │ system_statistics │ system    │ memory    │ PASS   │ 3m13.227487928s │
│ oracle  │ tablespace        │ system    │ memory    │ PASS   │ 3m16.599954264s │
╰─────────┴───────────────────┴───────────┴───────────┴────────┴─────────────────╯
```

**Review by efd6 — COMMENTED** [review]
Can you regenerate the sample events with these tests.

**Review by efd6 — APPROVED** [review]
Thanks

**Comment by agithomas** [comment]
```
--- Test results for package: oracle - START ---
╭─────────┬───────────────────┬───────────┬──────────────────┬────────┬─────────────────╮
│ PACKAGE │ DATA STREAM       │ TEST TYPE │ TEST NAME        │ RESULT │    TIME ELAPSED │
├─────────┼───────────────────┼───────────┼──────────────────┼────────┼─────────────────┤
│ oracle  │ database_audit    │ system    │ logfile          │ PASS   │   29.049378469s │
│ oracle  │ memory            │ system    │ memory           │ PASS   │ 2m53.914758731s │
│ oracle  │ performance       │ system    │ performance      │ PASS   │  3m2.378931615s │
│ oracle  │ sysmetric         │ system    │ sysmetric        │ PASS   │ 2m59.861538164s │
│ oracle  │ system_statistics │ system    │ systemstatistics │ PASS   │  3m6.285862443s │
│ oracle  │ tablespace        │ system    │ tablespace       │ PASS   │ 3m13.524900296s │
╰─────────┴───────────────────┴───────────┴──────────────────┴────────┴─────────────────╯
--- Test results for package: oracle - END   ---
Done

```

**Review by ManojS-shetty — APPROVED** [review]
LGTM

**Pull request merged**
