### PR TITLE
[Stack Monitoring] Remove release field, add preview1 identifier

### PR DESCRIPTION
**Pull request by matschaffer**
## What does this PR do?

Remove release field, add preview1 identifier

This is based on recommendations in https://github.com/elastic/kibana/issues/122973 and https://github.com/elastic/package-spec/issues/225

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

```
#!/usr/bin/env bash

set -euxo pipefail

(cd packages/elasticsearch && elastic-package build)
(cd packages/kibana && elastic-package build)
(cd packages/logstash && elastic-package build)

elastic-package stack up -v -d --version 8.6.0-SNAPSHOT
```

- Verify that elasticsearch, kibana & logstash packages are not immediately visible in integrations search
- Click the "available as an Elastic Agent integration" from a logs/metrics package to see the latest version

Note that the label will show "Beta" until https://github.com/elastic/kibana/issues/122973 is addressed.

## Related issues

Closes https://github.com/elastic/integrations/issues/4107

## Screenshots

Filebeat/metricbeat tutorials on integration search

Screen Shot 2022-10-06 at 16 21 31

Link on metrics page to agent package

Screen_Shot_2022-10-06_at_16_21_52

Package with new version

Screen_Shot_2022-10-06_at_16_22_20

### CODE REVIEW

**Comment by matschaffer** [comment]
Initial attempt is still showing me the 1.0.0 technical preview. Could be that it's sorting higher than 1.0.0-preview1

Screen Shot 2022-10-06 at 15 27 32

**Comment by matschaffer** [comment]
2.0.0-preview1 worked. Trying again after wiping my build directory. We might have to increment the version to get the version with the identifier to appear by default since in semver `1.0.0` would be greater than `1.0.0-(x)`.

Screen Shot 2022-10-06 at 16 10 49

**Comment by miltonhultgren** [comment]
I think once you bump the version a release is made, I think that's why we held off with bumping the version until we were ready with all changes.

**Comment by matschaffer** [comment]
Thanks @miltonhultgren ! Maybe we can save this PR for last, then. I think if we just remove the `release` label now it'll make it harder to test updates since the old 1.0.0 sorts ahead of 1.0.0-preview1.

**Comment by klacabane** [comment]
There are currently 3 stages, a commit to the repo will publish to the snapshot stage while staging and production stages needs manual operation (documentation here https://github.com/elastic/package-storage/). Now this model will be deprecated in favor of a [v2 approach](https://github.com/elastic/elastic-package/blob/main/docs/howto/use_package_storage_v2.md) that only exposes a single stage but I don't have the specifics on when this is supposed to happen

**Comment by matschaffer** [comment]
> can we bump minor or is 1.0.0 taking precedence over 1.1.0-preview1 ?

I suspect 1.1.0-preview1 will work. I'll go with that 👍🏻

**Comment by matschaffer** [comment]
Updated. Given what @klacabane said I'm guessing this is okay to merge now and we'll do the manual release process once we've confirmed all the functionality is working as expected.

**Review by klacabane — APPROVED** [review]

**Comment by matschaffer** [comment]
Interesting. Looks like merging this caused the following PRs to get opened:

- https://github.com/elastic/package-storage/pull/5913
- https://github.com/elastic/package-storage/pull/5914
- https://github.com/elastic/package-storage/pull/5915

I'm inclined to go ahead with merge and "release" since the packages have been working in our tests so far, though it may be odd to have it launch ahead of 8.5.0.

Either way it's probably unlikely someone would install them by accident since you have to search or click via the metricbeat "integration" card.

What say you folks? Merge away or hold?

**Comment by matschaffer** [comment]
Nevermind, looks like automerge is a thing. I'm pretty sure this is fine given the above.

**Pull request merged**
