### PR TITLE
[Airflow] Remove metric_type mapping for 'airflow.scheduler.heartbeat' field and adjust the dashboard to visualize this 

### LINKED ISSUE #7504: Choosing the right metric_type mapping and aggregator function for the Airflow dashboard's `scheduler.heartbeat` field in the context of TSDB.
Previously, the sum aggregator function was used to display `scheduler.heartbeat` in the Airflow dashboard before TSDB integration. Although the sum aggregator isn't ideal for representing this field, it was switched to max to address visualization issues. This was done as sum, avg aggregators, etc., do not align well with counter fields. 
It's required to update an appropriate aggregator to accurately represent this field in TSDB-enabled mode too.

### PR DESCRIPTION
**Pull request by ritalwar**
- Bug

## What does this PR do?

This PR modifies the metric_type of `airflow.scheduler.heartbeat` from counter to gauge. Despite the field being labeled as a counter in the airflow [documentation](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/metrics.html#counters), the behavior of the values—consistently 1 or 2—suggests it aligns better with the characteristics of a gauge metric. 
Additionally,  dashboard is modified to accurately represent this data, with the aggregator function updated to use last_value.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates #7504 

## Screenshots

Screenshot 2023-08-28 at 11 40 39 AM
Screenshot 2023-08-28 at 11 36 26 AM

### CODE REVIEW

**Comment by agithomas** [comment]
@lalit-satapathy /  @ritalwar , I want to propose a third option - not to mention either gauge / counter following the conflicted behaviour we noticed and what is documented. Yes, this would lead to not able to benefit TSDB advantages. We can create a backlog item for metric_type mapping of this field. As we get more clarity, the change to map either to `gauge` or `counter` can be made. Thoughts?

**Comment by agithomas** [comment]
The advantage with the above approach is that the change (and thus the readme) don't contradict the official documentation of couchdb.

**Comment by ritalwar** [comment]
> @lalit-satapathy / @ritalwar , I want to propose a third option - not to mention either gauge / counter following the conflicted behaviour we noticed and what is documented. Yes, this would lead to not able to benefit TSDB advantages. We can create a backlog item for metric_type mapping of this field. As we get more clarity, the change to map either to `gauge` or `counter` can be made. Thoughts?

I think we can go with this to avoid any conflicts and keep this issue open. However, let's keep this PR to stick with the 'last_value' as the aggregator function for this visualisation, as discussed. We'll put the metric_type mapping on hold for now. @lalit-satapathy , WDYT?

**Comment by ritalwar** [comment]
Following our discussion, I've removed the metric_type mapping for the 'scheduler.heartbeat' field and made the necessary updates to the dashboard, utilizing 'last_value' for visualizing this field's data. We can maintain the related issue as open to determine the appropriate metric_type mapping without conflicting with the documentation.

Screenshot 2023-09-06 at 4 40 24 PM
Screenshot 2023-09-06 at 4 40 08 PM
Screenshot 2023-09-06 at 4 39 10 PM

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
