### PR TITLE
[O11y][Microsoft SQL Server] Lens migration for `Transaction log` dashboard visualizations to Kibana version 8.4.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for Microsoft SQL Server integration package

- Statistics for Microsoft SQL Server Lens migration:

<html>
<body>

Microsoft SQL Server dashboard | Before Migration |   | After Migration | |  
-- | -- | -- | -- | -- | -- 
  | Lens | Visualization | Lens | Visualization | New control Panel
[Metrics Microsoft SQL Server] Transaction log | 0 | 8 | 7 | 0 | 1
  | 0 | 8 | 7 | 0 | 1

</body>
</html>

Note: 1 visualization is migrated to new control panels.

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.4.0 itself.

## Related issues

- Relates #5221

### CODE REVIEW

**Comment by milan-elastic** [comment]
Thanks @rajvi-elastic ! Approved!

**Comment by muthu-mps** [comment]
@rajvi-elastic - Before and after migration doesn't include the control panel filter and you please add that to the table.

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic - Before and after migration doesn't include the control panel filter and you please add that to the table.

@muthu-mps Update the description in PR and issue as well.

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Review by muthu-mps — APPROVED** [review]
Looks good!

**Pull request merged**
