### PR TITLE
[O11y][Redis Enterprise] Add description for panels 

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Bug

## What does this PR do?
-  Add panel description in Redis Enterprise migrated panels.
- The description tooltip doesn't support for lens in Kibana older versions. However, It will be added in Kibana `8.7`.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [x] Panel descriptions can be viewed and modified in Kibana `8.7.0`

## Related issues

- Relates https://github.com/elastic/integrations/issues/5723

## Screenshots

image (13)

Note: We identified that adding description at `embeddableConfig.attributes.description` rather than adding at `embeddableConfig.description` will show tooltip in `8.3.0`.

### CODE REVIEW

**Comment by agithomas** [comment]
@rajvi-elastic , In the [comment](https://github.com/elastic/integrations/issues/5674#issuecomment-1486575643), it was mentioned the option to add description is not available in version until 8.6. In the PR, i do not see a kibana version change. Can you re-check on this point and clarify?

**Comment by agithomas** [comment]
@rajvi-elastic , please link the PR to the redis enterprise migration issue for purpose of ease of tracking

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic , In the [comment](https://github.com/elastic/integrations/issues/5674#issuecomment-1486575643), it was mentioned the option to add description is not available in version until 8.6. In the PR, i do not see a kibana version change. Can you re-check on this point and clarify?

@agithomas, Do we really want to upgrade Kibana version for this change? Because this change will not cause any issue in older Kibana Version (For eg., `8.3.0` or later versions). Just the tooltip won't appear in the panel. All the other functionalities will work fine.

**Comment by agithomas** [comment]
> @agithomas, Do we really want to upgrade Kibana version for this change? Because this change will not cause any issue in older Kibana Version (For eg., `8.3.0` or later versions). Just the tooltip won't appear in the panel. All the other functionalities will work fine.

I now see that there is no change in the kibana version and hence I am good.

**Comment by agithomas** [comment]
@SubhrataK , can you please help by discussing with @rajvi-elastic on the missing tool-tip issue , she highlighted and is it an important one and if it is Ok to loose the feature?

**Comment by SubhrataK** [comment]
@rajvi-elastic As discussed, as long as the panel names are meaningful and self explanatory, we can live without the tool tips . Anyhow, this feature is available in later versions of Kibana, so should not be a blocker.

Also, please update the dashboards, with suggestions provided for changing the Titles of each of the panels, so that tool tips are not required.

**Comment by milan-elastic** [comment]
Approved!

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
