### PR TITLE
Add missing rule templates

### PR DESCRIPTION
**Pull request by orestisfl**
## What does this PR do?

Generate missing rule templates for new rules.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes https://github.com/elastic/csp-security-policies/issues/192
- Closes https://github.com/elastic/csp-security-policies/issues/194
- Closes https://github.com/elastic/csp-security-policies/issues/220
- Closes https://github.com/elastic/csp-security-policies/issues/221
- Closes https://github.com/elastic/csp-security-policies/issues/222
- Closes https://github.com/elastic/csp-security-policies/issues/223

# Screenshots

screenshot-2023-05-04T16:48:05 IDT

### CODE REVIEW

**Review by oren-zohar — APPROVED** [review]

**Review by oren-zohar — CHANGES_REQUESTED** [review]
ping me when the manifest and change-log are updated, I'm supprised it didn't fail the CI here

**Comment by orestisfl** [comment]
Hey @kfirpeled, a bit confused about how the backporting is going to work since we have two preview versions right now. Do we have to follow the instructions in https://github.com/elastic/integrations/blob/main/docs/developer_workflow_bug_fix_older_package_version.md?

**Comment by kfirpeled** [comment]
@orestisfl great question, we have a guideline - I'll send it to you

Also, you didn't mention https://github.com/elastic/csp-security-policies/issues/192 which is also missing

**Comment by kfirpeled** [comment]
> ping me when the manifest and change-log are updated, I'm supprised it didn't fail the CI here

There's no check for adding anything to the manifest or the changelog

**Comment by orestisfl** [comment]
Updated, cherry-picked the commit from the backport branch

**Pull request merged**
