### PR TITLE
[O11y][WebSphere Application Server] Lens migration for visualizations to Kibana version 8.3.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for WebSphere Application Server integration package

- Statistics for WebSphere Application Server Lens migration:

<html>
<body>

WebSphere Application Server dashboard | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics WebSphere Application Server] Session Manager | 4 | 1 | 4 | 0
[Metrics WebSphere Application Server] Servlet | 3 | 0 | 3 | 0
[Metrics WebSphere Application Server] ThreadPool | 6 | 1 | 6 | 0
[Metrics WebSphere Application Server] JDBC | 4 | 1 | 4 | 0
  | 17 | 3 | 17 | 0

</div></div>
</body>
</html>
Note: Migrate 3 visualizations to new control panels.

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.3.0 itself.

## Related issues

- Relates #5221

### CODE REVIEW

**Comment by agithomas** [comment]
@rajvi-elastic , Sharing a recommendation :  to use colour theme as here
https://github.com/elastic/integrations/blob/db608ccfb0b13eb2c2ab94ceea297ade9648ad81/packages/oracle_weblogic/img/oracle_weblogic-logs-overview.png

The usage of themes / colours in a specific theme improve the UI consistency and also improve the dashboard readability

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic , Sharing a recommendation : to use colour theme as here https://github.com/elastic/integrations/blob/db608ccfb0b13eb2c2ab94ceea297ade9648ad81/packages/oracle_weblogic/img/oracle_weblogic-logs-overview.png
> 
> The usage of themes / colours in a specific theme improve the UI consistency and also improve the dashboard readability

Agreed @agithomas. The right color theme improves the dashboard readability and helps to highlight important data. But this PR only contains lens migration task and only three visualizations are migrated to new input controls. All the other panels are as it is. However, If you strongly feel that this change needs to be done then we can raise a separate issue for that and track them separately.

**Comment by agithomas** [comment]
> However, If you strongly feel that this change needs to be done then we can raise a separate issue for that and track them separately.

Understood. Please stick to the current scope.

**Comment by agithomas** [comment]
Please create separate PRs for each dashboard / datastream.

**Comment by milan-elastic** [comment]
> Please create separate PRs for each dashboard / datastream.

@agithomas I understand there are 29 file changes showing, but If you see there are only **179 lines** that are changed and most of them are because we exported in 8.3.0 and hence some necessary default properties are added. 

FYI: Only 3 control panels are migrated to lens control panels, other visualizations are untouched as they were already in the lens. Let me know if you still want to raise the separate PR for each dashboard that contains 1 control panel change.

image

**Comment by agithomas** [comment]
> @agithomas I understand there are 29 file changes showing, but If you see there are only **179 lines** that are changed and most of them are because we exported in 8.3.0 and hence some necessary default properties are added.

It is difficult to review the PR in current form and hence i request you to split PR - one per dashboard.

**Comment by rajvi-elastic** [comment]
@agithomas, As per the recommendation, created 3 other PRs  data-stream wise for WebSphere Application Server. For that reason we are declining this PR. Let me know if you have any issues.

JDBC: https://github.com/elastic/integrations/pull/5631
Threadpool: https://github.com/elastic/integrations/pull/5632
Session Manager and Servlet: https://github.com/elastic/integrations/pull/5633

**Comment by rajvi-elastic** [comment]
Closing this PR as we have raised separate PR for all the data-streams:
JDBC: https://github.com/elastic/integrations/pull/5631
Threadpool: https://github.com/elastic/integrations/pull/5632
Session Manager and Servlet: https://github.com/elastic/integrations/pull/5633

**Pull request closed without merging**
