### PR TITLE
enhancement - modify incident handling to match defender for endpoint

### PR DESCRIPTION
**Pull request by agmic**
Enhancement

## Proposed commit message

Modify incident handling to match Defender for Endpoint. 
- Change fingerprint to use creation_time and modification_time to generate a unique id
- Add event.created set to original incident creation time
- Set timestamp to modification_time
- Change search cursor to use modification_time instead of creation_time in order to only fetch newest incidents.
- Add severity:critical=5 to allow for events marked as 5 in Cortex XDR

This change will align the integration with the defender for endpoint integration, enable correct fetching of the latest incidents and incident changes, and allow for ingestion of modified incidents.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by agmic** [comment]
I've signed the CLA for this, but it doesn't seem to be passing the check. Anything I can do to help this along?

**Comment by jkomara** [comment]
buildkite test this

**Comment by agmic** [comment]
I see the build is failing, but don't have access to buildkite to see why. Is there anything I can help with to facilitate this?

**Comment by kcreddy** [comment]
@agmic CI is failing on this line inside changelog: `link: https://github.com/elastic/integrations/pull/` with following error: 
`Error: checking package failed: linting package failed: found 1 validation error:
  | 1. https://github.com/elastic/integrations/pull/: issue number in changelog link should be a positive number`

Can you update the line to `link: https://github.com/elastic/integrations/pull/9246`?

**Comment by agmic** [comment]
thx @kcreddy . I've made the update - any last things needed to trigger the buildcheck?

**Comment by kcreddy** [comment]
Hey @agmic, 
IIUC you are trying add support for ingesting modified incidents.
But the problem I see is that it gets difficult to analyse documents with dashboards/aggregations. For example, when an incident has changed its severity from `critical` to `high`, you will have 2 documents now inside the datastream with 2 states. 
When you try to find `how many incidents have `severity: critical` -> this leads to 1.
Also, `how many incidents have `severity: high` -> this also leads to 1.

The better way to handle this is using [Elasticsearch Latest Transform](https://www.elastic.co/guide/en/elasticsearch/reference/current/transform-overview.html#latest-transform-overview) where you can store latest copy in separate index. But, transforms are usually computationally expensive as every time it has to query all the data in the source datastream to find and store latest copies.

@jamiehynds Do you think adding this support (modified incidents) using transforms is worth it. Currently based on the [fingerprint processor](https://github.com/elastic/integrations/blob/main/packages/panw_cortex_xdr/data_stream/incidents/elasticsearch/ingest_pipeline/default.yml#L26-L31), modifications to incidents are not ingested.

**Comment by agmic** [comment]
👍

**Comment by andrewkroh** [comment]
The update to include mod time in the fingerprint seem good, because otherwise the integration mostly won't index any updates. I suggest adding a small blurb in the _Alerts_ section of the package's readme to state that a new document is indexed when alerts are modified.

**Review by kcreddy — COMMENTED** [review]
Hey @agmic , if you are okay with the suggestion [here](https://github.com/elastic/integrations/pull/9246#issuecomment-2139659242), could you please add to this PR?

As for the other approach, if you would like to add latest transform, you can take an example from [here](https://github.com/elastic/integrations/tree/main/packages/ti_threatconnect/elasticsearch/transform/latest).

**Comment by agmic** [comment]
@kcreddy I'll update the readme and add it to the PR. Just to  be clear, I'll add it to the _Incidents_ section, as this is what is changed.
Since there have been changes to the cortex integration since my initial PR (we are now on version 1.27.0) Do I need to resolve the conflicts and resubmit all changes - or can I just change the readme file?

**Comment by kcreddy** [comment]
> Just to be clear, I'll add it to the Incidents section, as this is what is changed.

Yes, that sounds good.

>  Do I need to resolve the conflicts and resubmit all changes - or can I just change the readme file?

Yes, the merge conflicts need to be resolved as well.

**Review by kcreddy — COMMENTED** [review]
@agmic The CI is failing on outdated README. 
Can you regenerate the README file and commit it. 

`elastic-package build && elastic-package format && elastic-package lint && elastic-package check && elastic-package build`

**Comment by agmic** [comment]
@kcreddy - I'd forgotten that the README.md was generated from a template. I've modified the template in _dev/build/docs and run the elastic-package commands above. The regenerated README.md appears to be unchanged.

**Comment by agmic** [comment]
@kcreddy Failing on expected outcome of incident parsing due to change of timestamp handling - I'll get that remedied.

**Comment by kcreddy** [comment]
@agmic You may have to re-run the pipeline tests:
`eval "$(elastic-package stack shellinit)" && elastic-package test pipeline --generate -v`

There is a missing comma `,` in [one of the lines](https://github.com/elastic/integrations/pull/9246/commits/439827275634188dcac94f7259b09881fc4194cc#diff-a1e67d494c888e6cfc9bafdb527e0dc3a37fa3c81cd36639d50bd5ce2d07c906R276), causing an invalid JSON.

**Review by kcreddy — APPROVED** [review]
LGTM

**Pull request merged**
