### PR TITLE
[O11y][Vsphere] Migrate `VMs Overview` dashboard visualizations to lens in kibana 8.7.0 

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for Vsphere integration package

- Statistics for Vsphere `VMs Overview` Lens migration:

<html>
<body>

VSphere dashboard | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics VSphere] VMs overview | 0 | 5 | 5 | 0
  |  0 | 5 | 5 | 0

</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.7.0 itself.

## Related issues

- Relates #5221 

Note: Screenshot of before migration dashboard is not synced with Kibana files. Please find below screenshot to compare the migrated visualizations.

Metrics VSphere  VMs overview (1)

### CODE REVIEW

**Comment by rajvi-elastic** [comment]
> 1. The Memory value is represented in Human readable format in Old vis but not in New Vis.
>    Can this be addressed. If not, i would recommend keeping the old vis
> 2. What is the default sort order followed in the table?

@agithomas ,

1. I have mentioned in the PR description that Kibana files and dashboards are not synced and also uploaded the before migration screenshot. In that the Memory value is not represented in Human readable format.
2.  Sorting orders are as below:
 - Name:  Descending order by count
image
-  Used CPU:  Descending order by Maximum of `vsphere.virtualmachine.cpu.used.mhz`
image
- Total RAM: Descending order by Maximum of `vsphere.virtualmachine.memory.total.guest.bytes`
image
- Networks:  Descending order by count
image

**Comment by agithomas** [comment]
Is it possible to make the changes in the new layout, so that it appears more human readable (representing in MB/ GB) ?

**Review by milan-elastic — APPROVED** [review]

**Comment by rajvi-elastic** [comment]
> Is it possible to make the changes in the new layout, so that it appears more human readable (representing in MB/ GB) ?

Yes @agithomas, It is possible. I'll update the PR.

**Comment by rajvi-elastic** [comment]
> Is it possible to make the changes in the new layout, so that it appears more human readable (representing in MB/ GB) ?

@agithomas, I have updated the PR with mentioned changes.

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
