### PR TITLE
change sum to max, use entire_time_range

### PR DESCRIPTION
**Pull request by aspacca**
Bug
## What does this PR do?
Fix AWS billing dashboard

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by tommyers-elastic** [comment]
thanks andrea! the diff is really hard to read - could we see a before and after screenshot?

**Comment by aspacca** [comment]
> thanks andrea! the diff is really hard to read - could we see a before and after screenshot?

after:
Screenshot 2023-02-28 alle 19 32 40

before:
Screenshot 2023-02-28 alle 19 31 05


differences in the pie chart and top10 visualisation are less evident since I've only a single day of data so avg/sum/max are the same

**Comment by dmathieu** [comment]
How come total estimated charges comes from $0 to $10k?
Similarly, how come the top10 visualization only has one value in the after chart?

**Comment by aspacca** [comment]
> How come total estimated charges comes from $0 to $10k?
> Similarly, how come the top10 visualization only has one value in the after chart?

the solutions/changes to implement were raised by the SA when facing the issues with a customer. I've tested them, and saw that they reflect the expected behaviour.
```
Issue:

a. Total estimated charges panel always showed $0.

Solution, we put in place:

a. In Data panel, Metrics, use Max aggregation

In panel options, under Data timerange mode - change to "Entire time range"

b. Estimated billing chart. does not reflect the amount that we see in AWS console billing dashborad. It also shows the sum of all the events(estimated charges rather than max of estimated charges)

c. Estimated billing per service name - the Panle shows the sum of the estimated charges based on the time period you select.

Solution, we have used max aggregation to solve.
```


specifically for the first question:
> under Data timerange mode - change to "Entire time range"

before it was last value: if you have "now" as end time range, and you are not checking the dashboard at the exact moment of @timestamp value of the latest event in the data stream you see 0. that's my assumption, I can validate it.
you can try as well to fetch once from current aws.billing integration and set the end date to the exact @timestamp of the latest document with `aws.billing.EstimatedCharges` and no `aws.billing.ServiceName`: I'd expect that in this case the value is not zero. 



second question:
> Similarly, how come the top10 visualization only has one value in the after chart?

top10, in my screenshots have one value in the chart before and after: the difference is that the metrics was changed from avg to sum. my assumption is that with avg a lines moving to zero is rendered to reach the end of the time range, while with max only the point of when the metric is present is rendered. still I can validate.

anyway your question and my explanation brought me some doubts about how the dashboard will behave when billing data are collected from multiple accounts. I'm getting in touch with support about those details

**Comment by aspacca** [comment]
please. do not merge yet

**Comment by aspacca** [comment]
> If this is what was happening, the [advice](https://github.com/elastic/integrations/issues/1437#issuecomment-1409454132) I gave there is equally applicable here.

thanks for chiming in @drewdaemon 

I'm not sure I can apply your advice here: it seems to me that the dashboard was already using that settings and it showed empty data (0 $)

The original data are something like the following:
@timestamp, account name, service name, estimated charges
2023/03/09, accountA, "", 400 $
2023/03/09, accountA, service 1, 200 $
2023/03/09, accountA, service 2, 200 $
2023/03/09, accountB, "", 500 $
2023/03/09, accountB, service 1, 400 $
2023/03/09, accountB, service 2, 100 $
2023/03/10, accountA, "", 100 $
2023/03/10, accountA, service 1, 70 $
2023/03/10, accountA, service 2, 30 $

I used daily time resolution for the timestamp since that's the default period of the events collection, but the users could change that up to 1m

An entry with an empty service is the cumulative value for the given period for a single account. It is the equivalent of the sum of the values with a non empty service for the same period for a single account.

For "Total estimated charges", we must sum the most recent single event for each separated account name with empty service (to be precise the most recent single event in the selected time range):  beware that two different accounts could have different timestamp for their own most recent single event.

If my selected range ends on 2023/03/09 23:59:59, the value shown should be 900 $ when not filtered by any account value. and 400 $ and 500 $ when filtered by accountA and accountB respectively

If my selected range ends after 2023/03/10 23:59:59, the value shown should be 600 $ when not filtered by any account value. and 100 $ and 500 $ when filtered by accountA and accountB respectively

We might decide that this is a case were it makes sense to constrain the time range independently of the time picker: and we will show the 600 $/100 $/500 $ scenario. I was not able to get it anyway.

For "Estimated billing per service name" we could use sum and set the interval to 1d: by default billing metrics are fetched every day, so that's the correct interval to be sure that the data shown are correct.
The problem is that if the time range selected is big enough, 1d of interval would be too short and the widget will fail to render. changing the interval to any value that will prevent the widget failure will show incorrect data.
This does not account for the case the users changed the period to something different than 1d.

For the "Estimated billing chart" I could not find any solution that will show the correct values in the tooltip, the percentages in the pie chart vary as well according to the aggregation we use.

We have a separated issue to migrate the dashboards to Lens, do you know if in this specific case it will help solving the problems above?

Thanks

**Comment by drewdaemon** [comment]
@aspacca apologies for the late response. I don't know how I missed your thoughtful reply.

Reading your description of the data and what you're trying to accomplish, it makes sense that you're using a constrained time range (i.e. TSVB "last value mode" or Lens "reduced time range").

I would recommend you set the interval to match your expected sample rate (so 1 day in this case). 

It is true that if the time range is too large "the widget will fail to render" but I think that is okay. No data visualization works well for every single case. The goal is to create visualizations that work well for the cases they're intended. I believe the message TSVB shows explains the problem and users can always fine-tune the max-buckets setting.

I do think that we handle this case more intelligently in Lens so you run into errors much less frequently. I would be interested to hear if you notice less erroring with large timespans after converting that metric to Lens (there should be an "Open in Lens" button you can use for testing).

Another avenue to try is a custom time range added to the dashboard panel.

But basically, I think the approach is right. Enforcing an interval that matches the sample rate is my main feedback. Otherwise users are confused as to why sometimes they have a metric and sometimes they don't.

**Comment by DK-Elastician** [comment]
> 
👍🏾

**Pull request closed without merging**
