### PR TITLE
Package spring boot [audit events, gc, memory]

### PR DESCRIPTION
**Pull request by sunny-elastic**
## What does this PR do?

- Generated the skeleton of Spring Boot integration package.
- Added 3 data stream ( Audit events, GC, Memory )
- Added data collection logic.
- Added the ingest pipelines.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yml files.
- Added dashboards and visualizations.
- Added system test cases.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/spring_boot directory.
- Run the following command to run tests. 
> elastic-package test 

Note: We have added all the visualizations for Spring boot in the same PR as splitting them would be tedious and create more conflicts for the other data stream PRs.

### CODE REVIEW

**Comment by sunny-elastic** [comment]
Test /

**Review by mtojek — COMMENTED** [review]
is it the main PR? It isn't rebased correctly and contains few data streams.

**Comment by miltonhultgren** [comment]
I don't think my team needs to review this so I'll unmark us, let me know otherwise :)

**Comment by sunny-elastic** [comment]
> is it the main PR? It isn't rebased correctly and contains few data streams.

Sure Its done. Thanks. Also this PR is targeting 3 data streams [Audit events, GC and Memory] as there are total 9 data streams for spring boot we have accommodated 3 data streams into 1 PR atleast for now just to reduce the # of PR's

**Review by mtojek — COMMENTED** [review]
@sunny-elastic 

This isn't what we agreed on. The scheme should be as follows:
1. Open a PR with skeleton and 1 data stream.
2. Iterate and open next PR with next data stream
3. ....
4. Open a PR with Kibana objects.

Don't need to feel concerned about number of PRs to be reviewed, it's fine, we will handle it. With larger PRs, it's easier to miss things

**Pull request closed without merging**
