### PR TITLE
[GCP] Billing dashboard fixes

### PR DESCRIPTION
**Pull request by endorama**
## What does this PR do?

- update GCP Billing Overview dashboard to 8.6.0 format
- use `last_value` for total billing cost instead of sum, as GCP data is already an aggregation
- add filter for `event.dataset: gcp.billing`
- replace filters with controls

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Closes https://github.com/elastic/integrations/issues/5008

## Screenshots

image

### CODE REVIEW

**Comment by Danouchka** [comment]
Can we have someone review the code and release the fix please ? 
Thank you

**Comment by Danouchka** [comment]
👍

**Comment by Danouchka** [comment]
Hello @tommyers-elastic 

What's the status on this issue please ? 

Thank you

**Comment by Danouchka** [comment]
Hi I see it as not fixed in 8.10.2 , latest GCP integration

**Comment by Danouchka** [comment]
:+1

**Comment by mrodm** [comment]
Hi @endorama, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

**Pull request closed without merging**
