### PR TITLE
[Cloudflare] Replace original integration with Logpush

### LINKED ISSUE #4217: [Cloudflare] Deprecate Logpull and rename Log Push
We recently shipped our Cloudflare Log Push integration, which is intended to replace the current Cloudflare Logpull based integration. Based on guidance from Cloudflare they recommend that we deprecate our Logpull integration, as Logpull is a legacy product and they are pushing their customers to switch over to using Logpush as well.

Can the current Logpull integration be deprecated and removed from future releases, while ensuring existing users of the integration can continue to use it for a period of time? A deprecation notice should be added to the integration for those users, with a recommendation to switch to Logpush. 

In parallel, can the new 'Cloudflare Log Push' integration be renamed to 'Cloudflare' as no other integration includes the method of ingestion in the name. This may involve having to rename the current 'Cloudflare' integration to 'Cloudflare Logpull' before we deprecate.

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

- Rename original Cloudfare Integration to Cloudflare LogPull
- Rename Cloudflare Logpush integration to just Cloudflare
- Copy HTTP JSON input for Audit logs to Cloudflare integation to support non-Enterprise tier customers and update ingest pipeline.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Closes #4217

### CODE REVIEW

**Comment by legoguy1000** [comment]
I could also replace the original Cloudflare integration with cloudflare_legacy?

**Comment by P1llus** [comment]
Hi @legoguy1000 .
Did some internal discussions here, would it be possible that you add "logpush" as a datastream to the existing package, and change the description of the logpull datastream to mention that it has been deprecated by Cloudflare and that logpush is recommended?

Renaming the packages will simply create issues for people upgrading, and making the upgrade path much harder for them, and while logpull is deprecated, its still running.

**Comment by legoguy1000** [comment]
So there are like 5 datastream in the current logpush integration. Just want to make sure our thinking is the same. Ur suggesting just combine the integrations under the `cloudflare` name and add a note to just not use the logpull datastream and use the new ones that's use logpull?

**Comment by P1llus** [comment]
> So there are like 5 datastream in the current logpush integration. Just want to make sure our thinking is the same. Ur suggesting just combine the integrations under the `cloudflare` name and add a note to just not use the logpull datastream and use the new ones that's use logpull?

From my understanding there is a `cloudflare_logpush` and a `cloudflare` package. I am almost thinking since we already have this structure we could always have a `cloudflare_logpull` or we would need to have some convenient naming under the cloudflare package to not cause any confusion.

WDYT @jamiehynds ?

**Comment by jamiehynds** [comment]
> Is there a reason why we need this rename at all?

Apologies @legoguy1000 & @P1llus - I didn't realise the proposed rename would have knock on effects. The main motivation was to avoid having 'how' we ingest in the package name (i.e. Logpush) and sticking with 'Cloudflare' as we do for all other integrations. However, if it's easier to just keep 'Cloudflare' (current Logpull integration) and 'Cloudflare Logpush', we can certainly live with that. Once Logpull is deprecated we'll be just left with 'Cloudflare Logpush' which isn't a big deal.

**Comment by P1llus** [comment]
> > Is there a reason why we need this rename at all?
> 
> Apologies @legoguy1000 & @P1llus - I didn't realise the proposed rename would have knock on effects. The main motivation was to avoid having 'how' we ingest in the package name (i.e. Logpush) and sticking with 'Cloudflare' as we do for all other integrations. However, if it's easier to just keep 'Cloudflare' (current Logpull integration) and 'Cloudflare Logpush', we can certainly live with that. Once Logpull is deprecated we'll be just left with 'Cloudflare Logpush' which isn't a big deal.

I think as long as we focus on the title and description (in the manifest.yml), it might be better, we just need to come up with something that isn't confusing, and keeping the current package names.

**Comment by jamiehynds** [comment]
Let's just stick with 'Cloudflare Logpush' as the title for our new integration. I'm sure most Cloudflare enterprise customers will know what Logpush is, so it shouldn't create any confusion.

However, we need to consider the Audit logs datastream which @legoguy1000 is copying from the Logpull integration. If we proceed, we'll have two Audit datastreams which is confusing. One for Enterprise plan customers and one for non-Enterprise plan customers (which doesn't actually use logpush). 

Should we consider keeping the Logpull audit data stream within the log pull package and change the integration title to 'Cloudflare Audit Events' with a description to indicate the integrations supports audit events for Free/Pro/Business plan customers?

**Comment by legoguy1000** [comment]
@jamiehynds so there wouldn't be 2 audit datastreams. I just added both inputs to the same audit datastream so there was an option for httpjson or s3/http_endpoint and I updated the ingest pipelines to support both data structures.

**Comment by jamiehynds** [comment]
> @jamiehynds so there wouldn't be 2 audit datastreams. I just added both inputs to the same audit datastream so there was an option for httpjson or s3/http_endpoint and I updated the ingest pipelines to support both data structures.

Ah, perfect. Thanks @legoguy1000!

**Comment by legoguy1000** [comment]
@jamiehynds I have been super busy lately but I need to go back and clean all this up.  I think i am tracking that we came to the decision to leave everything as is but copy the httpjson input from the original integration to the new logpush integration so non enterprise customers can still use it and then deprecate the original cloudflare integration??

**Comment by jamiehynds** [comment]
> @jamiehynds I have been super busy lately but I need to go back and clean all this up. I think i am tracking that we came to the decision to leave everything as is but copy the httpjson input from the original integration to the new logpush integration so non enterprise customers can still use it and then deprecate the original cloudflare integration??

Thanks for perceiving @legoguy1000! After some internal discussion, we felt its best to leave the current Logpull integration as-is, given that Logpull is still supported by Cloudflare. We'll make it clearer in the integration description/docs that Logpush is recommended. We'll keep a close eye on where Cloudfare goes with Logpull and will adjust the integration if/when they decide to deprecate Logpull on their side.

**Pull request closed without merging**
