### PR TITLE
[microsoft_dhcp] Fix incorrect log parsing for DHCP host.domain -> host.name (redo)

### PR DESCRIPTION
**Pull request by nicpenning**
These are the tests and doc updates manually added.

Replaces the original PR that was botched due to CLA/credential mishap.
(https://github.com/elastic/integrations/pull/4280)

Closes https://github.com/elastic/integrations/issues/4279

### CODE REVIEW

**Review by efd6 — APPROVED** [review]
LGTM. Thanks for your patience with this.

**Comment by efd6** [comment]
It should be promoted probably next week.

**Comment by nicpenning** [comment]
Thank you.

**Comment by nicpenning** [comment]
Thank you.

**Comment by nicpenning** [comment]
I noticed that this is available for upgrade in the platform, however, the docs here (https://docs.elastic.co/en/integrations/microsoft_dhcp#changelog) are still not update to date. Will those come at a later time or did I miss something in the PR?

**Pull request merged**
