### PR TITLE
[O11y][Redis Enterprise] Migrate visualizations to lens in Kibana 8.3.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for Redis Enterprise integration package

- Statistics for Redis Enterprise Lens migration:

<html>
<body>

Redis Enterprise dashboard | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metricbeat Redis Enterprise] Overview | 0 | 12 | 11 | 0
  | 0 | 12 | 11 | 0
</body>
</html>
Note: Migrate 1 visualization to new control panel.

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.3.0 itself.

## Related issues

- Relates #5221

### CODE REVIEW

**Review by agithomas — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
Please complete the peer review

**Review by kush-elastic — COMMENTED** [review]
Can you upload the screenshot before migration which populates all the panels to confirm that type of chart has not been changed? As I can see 3 of the panels are not populated!

**Comment by rajvi-elastic** [comment]
> Can you upload the screenshot before migration which populates all the panels to confirm that type of chart has not been changed? As I can see 3 of the panels are not populated!

Sure! Please find the below screenshot before migration.
redis-enterprise

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Pull request merged**
