### PR TITLE
[httpjson] Fix response.split indentation

### LINKED ISSUE #2686: Malformed agent template for `response.split` in Custom HTTPJSON integration
Here is the current handlebars template for `response.split`:
https://github.com/elastic/integrations/blob/25e236321abf992e75252275873829f3b7c1b998/packages/httpjson/data_stream/generic/agent/stream/httpjson.yml.hbs#L55-L58

This makes it impossible to set top-level properties such as:
```yml
target: body.data
keep_parent: true
```

because the template will compile to:
```yml
response.split: null
target: body.data
keep_parent: true
```

There should probably be some whitespace on L56 (just a guess - not sure how this will affect nested splits).

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Fix indentation for `response.split` config

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Closes #2686

### CODE REVIEW

**Comment by marc-gr** [comment]
Can we do the same for `request_custom` and `oauth_custom`? I think they will have the same problem.

**Comment by legoguy1000** [comment]
any idea on teh error? 
```
{"statusCode":500,"error":"Internal Server Error","message":"can not read an implicit mapping pair; a colon is missed at line 17, column 23:\n      \"##request_custom##\"\n                          ^"}
```

**Comment by P1llus** [comment]
@legoguy1000 Sorry for the late reply, I am wondering if this is due to the system test under `test-transforms-config.yml` which uses `request_custom`

It might be that the way we handle `request_custom` here is the cause:
```
    request_custom: |-
      encode_as: application/json
      timeout: 25s
```

Looking into it

**Comment by P1llus** [comment]
There is no real workaround for this, as the issue is on the Kibana side, so adding configuration items like request_custom and oauth_custom does it wont work.

We are discussing what to do as a workaround for now, in the end I might close this PR and open up a similar one with additional changes, or we might need to push some other changes first.

**Comment by marc-gr** [comment]
> There is no real workaround for this, as the issue is on the Kibana side, so adding configuration items like request_custom and oauth_custom does it wont work.
> 
> We are discussing what to do as a workaround for now, in the end I might close this PR and open up a similar one with additional changes, or we might need to push some other changes first.

For reference https://github.com/elastic/package-spec/issues/280

**Comment by P1llus** [comment]
I will be closing this in favour of another, to resolve some bigger issues with the custom fields: https://github.com/elastic/integrations/pull/2815

**Pull request closed without merging**
