### PR TITLE
Osquery_manager: Upgrade osquery_manager for serverless, pick up ECS 8.10.0

### PR DESCRIPTION
**Pull request by aleksmaus**
## What does this PR do?

Upgrades osquery_manager for serverless specs
Picks up ECS 8.10.0

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Screenshots

Tested following the serverless opt-in packages guide.

Screenshot 2023-09-20 at 12 11 22 PM

Screenshot 2023-09-20 at 12 12 37 PM

### CODE REVIEW

**Comment by aleksmaus** [comment]
hmmm, the error in CI
```
[2023-09-20T16:32:46.066Z] Error response from daemon: manifest for docker.elastic.co/kibana/kibana:8.10.0 not found: manifest unknown: manifest unknown

[2023-09-20T16:32:46.066Z] Error: failed updating the stack images: updating docker images failed: running command failed: running Docker Compose pull command failed: exit status 18
```

**Comment by mrodm** [comment]
Please wait to merge this PR @aleksmaus , merging this branch would publish this package as GA with spec v3 but this spec is not GA yet.

We are checking how this validation is performed in elastic-package to try avoid this situation.

Thanks!!

cc @jsoriano @andrewkroh

**Comment by mrodm** [comment]
> Please wait to merge this PR @aleksmaus , merging this branch would publish this package as GA with spec v3 but this spec is not GA yet.
> 
> We are checking how this validation is performed in elastic-package to try avoid this situation.
> 
> Thanks!!
> 
> cc @jsoriano @andrewkroh

@aleksmaus you could proceed with this PR, just be aware that the spec v3 is not GA yet and there could be still changes in that version (e.g. more validation rules to be applied).

Just as a note, remember to add the capabilities if this package has some special requirement.

Sorry for the inconveniences!

**Comment by mrodm** [comment]
> > @aleksmaus you could proceed with this PR, just be aware that the spec v3 is not GA yet and there could be still changes in that version (e.g. more validation rules to be applied).
> 
> Thanks! Any advice what to do about this error in CI?
> 
> ```
> [2023-09-20T16:32:46.066Z] Error response from daemon: manifest for docker.elastic.co/kibana/kibana:8.10.0 not found: manifest unknown: manifest unknown
> ```
> 
> I tried to re-kick the PR build, didn't help

mmm that kibana image was deleted, that's why the testing fails.
I think one option would be to update the kibana version condition to be `^8.10.1` @aleksmaus . The disadvantage in this case is that this version would not be available for the current 8.10.0 clusters, but I guess they would need to update to 8.10.1 due to the security issue too.

This has already been applied in at least 3 packages:
```shell
 $ git grep "\^8.10.1" | grep manifest
awsfirehose/manifest.yml:  kibana.version: "^8.10.1"
okta/manifest.yml:  kibana.version: ^8.10.1
security_detection_engine/manifest.yml:  kibana.version: ^8.10.1
```

**Review by andrewkroh — APPROVED** [review]
This looks good.

I saw a few more fields that could be changed over to use `external: ecs` if you wanted.

```
packages/osquery_manager/data_stream/result/fields/base-fields.yml:1:3 data_stream.type
packages/osquery_manager/data_stream/result/fields/base-fields.yml:4:3 data_stream.dataset
packages/osquery_manager/data_stream/result/fields/base-fields.yml:7:3 data_stream.namespace
packages/osquery_manager/data_stream/result/fields/base-fields.yml:10:3 @timestamp
```

**Comment by andrewkroh** [comment]
https://github.com/elastic/integrations/blob/5b4416170c7a87c9d8014c76d52179c151b1773d/packages/osquery_manager/data_stream/result/fields/osquery.yml#L2-L3

These two fields, title and description on a "group", can be removed. That are not used for anything in packages or Fleet.

**Review by andrewkroh — APPROVED** [review]

**Comment by aleksmaus** [comment]
> This has already been applied in at least 3 packages:
> 
> ```shell
>  $ git grep "\^8.10.1" | grep manifest
> awsfirehose/manifest.yml:  kibana.version: "^8.10.1"
> okta/manifest.yml:  kibana.version: ^8.10.1
> security_detection_engine/manifest.yml:  kibana.version: ^8.10.1
> ```

I tried to update to ^8.10.1 the build still fails in CI
```
[2023-09-28T20:03:45.058Z] 2023/09/28 20:03:44 DEBUG running command: /var/lib/jenkins/workspace/est-manager_integrations_PR-7894/bin/docker-compose -f /var/lib/jenkins/workspace/est-manager_integrations_PR-7894/.elastic-package/profiles/default/stack/snapshot.yml --ansi never -p elastic-package-stack pull --quiet

[2023-09-28T20:03:50.180Z] Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF

[2023-09-28T20:03:50.180Z] Error: failed updating the stack images: updating docker images failed: running command failed: running Docker Compose pull command failed: exit status 18

script returned exit code 1
```

**Comment by andrewkroh** [comment]
That last failure was 18 hours ago which was during a docker hub [outage](https://www.dockerstatus.com/pages/history/533c6539221ae15e3f000031). That might have been the cause. Retrying.

**Review by kevinlog — APPROVED** [review]

**Comment by aleksmaus** [comment]
Can't merge, the button is disabled, weird.
```
Merging is blocked
Merging can be performed automatically with 1 approving review.
```

**Review by patrykkopycinski — APPROVED** [review]

**Pull request merged**
