### PR TITLE
Change format_spec in the kubernetes_otel package to 3.3.0

### PR DESCRIPTION
**Pull request by gbamparop**
Change `format_spec` in the `kubernetes_otel` package to 3.3.0 as support for content packages is added to `3.3.0`. 

Related to https://github.com/elastic/package-spec/pull/818

### CODE REVIEW

**Review by gizas — APPROVED** [review]

**Review by tetianakravchenko — APPROVED** [review]

**Review by jsoriano — APPROVED** [review]

**Comment by jsoriano** [comment]
CI will keep failing till we merge https://github.com/elastic/elastic-package/pull/2166 and release a new version of elastic-package. Working on this now.

**Comment by gizas** [comment]
Thank you @jsoriano !

I was ready to say that the exclude_check in validation file was not working for 3.3.0 version

<details>
<summary>See bash logs</summary>

```bash

elastic-package build
Build the package
2024/10/16 17:20:08  INFO License text found in "/Users/andreasgkizas/elastic/integrations/LICENSE.txt" will be included in package
2024/10/16 17:20:08  INFO Skipped errors: found 1 validation error:
   1. package with non-stable semantic version and active beta features (enabled in [/Users/andreasgkizas/elastic/integrations/build/packages/kubernetes_otel-0.0.4.zip]) can't be released as stable version. (PSR00002)
Error: building package failed: invalid content found in built zip package: found 7 validation errors:
   1. item [LICENSE.txt] is not allowed in folder [/Users/andreasgkizas/elastic/integrations/build/packages/kubernetes_otel-0.0.4.zip]
   2. item [changelog.yml] is not allowed in folder [/Users/andreasgkizas/elastic/integrations/build/packages/kubernetes_otel-0.0.4.zip]
   3. item [docs] is not allowed in folder [/Users/andreasgkizas/elastic/integrations/build/packages/kubernetes_otel-0.0.4.zip]
   4. item [img] is not allowed in folder [/Users/andreasgkizas/elastic/integrations/build/packages/kubernetes_otel-0.0.4.zip]
   5. item [kibana] is not allowed in folder [/Users/andreasgkizas/elastic/integrations/build/packages/kubernetes_otel-0.0.4.zip]
   6. item [manifest.yml] is not allowed in folder [/Users/andreasgkizas/elastic/integrations/build/packages/kubernetes_otel-0.0.4.zip]
   7. item [validation.yml] is not allowed in folder [/Users/andreasgkizas/elastic/integrations/build/packages/kubernetes_otel-0.0.4.zip]

Reverting version to 3.4.0

elastic-package build
Build the package
2024/10/16 17:21:44  INFO License text found in "/Users/andreasgkizas/elastic/integrations/LICENSE.txt" will be included in package
2024/10/16 17:21:44  INFO Skipped errors: found 1 validation error:
   1. package with non-stable semantic version and active beta features (enabled in [/Users/andreasgkizas/elastic/integrations/build/packages/kubernetes_otel-0.0.4.zip]) can't be released as stable version. (PSR00002)
Package built: /Users/andreasgkizas/elastic/integrations/build/packages/kubernetes_otel-0.0.4.zip
Done

````
</details>

**Comment by jsoriano** [comment]
@gbamparop you may need to update the branch to get the latest changes from main.

**Pull request merged**
