### PR TITLE
[tenable_sc] Add drop to pipeline if event is empty

### PR DESCRIPTION
**Pull request by LaZyDK**
Drop event in Vulnerability pipeline if there is no returned results.

## What does this PR do?

Drops empty events. 

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by LaZyDK** [comment]
@P1llus Test :)

**Comment by P1llus** [comment]
@LaZyDK any idea why we would want to ignore this? If its missing then there is no data.

**Comment by LaZyDK** [comment]
@P1llus I see that you are right! So we should actually drop the events instead.

**Comment by vinit-elastic** [comment]
Hey @LaZyDK @P1llus - These are the extra external references for the Vulnerability. I don't see a point in dropping the entire event as the field is expected to be empty for many vulnerabilities. With that being said, this is a new behavior for the API though previously the response would have an empty string in cases where there were no external references for the vulnerability.

By the way, thanks for the PR @LaZyDK, Really appreciate it. :)

**Comment by LaZyDK** [comment]
After testing with the ignore_missing set we get a new error, which should also be fixed if not everything should be dropped. 
I will look into this on Monday.

**Comment by LaZyDK** [comment]
I don't find any data in the events that are not having the `seeAlso` field. 
Here is `event.original` of one:
```
{"error_code":0,"error_msg":"","response":{"endOffset":"118000","matchingDataElementCount":"-1","results":[],"returnedRecords":0,"startOffset":"117000","totalRecords":"116095"},"timestamp":1677232486,"type":"regular","warnings":[]}
```

Data is all neat after implementing a Drop action as a failure event handler for that particular split.

**Comment by LaZyDK** [comment]
I removed the failure processor and included a conditional drop processor instead, to be inline with other integrations like the one for MISP.

Also included the empty original event in the test document.

**Comment by P1llus** [comment]
It needs to generate pipeline tests, adding it now

**Review by P1llus — APPROVED** [review]

**Pull request merged**
