### PR TITLE
[GCP] Move dashboard visualizations to by value

### LINKED ISSUE #3719: GCP

### PR DESCRIPTION
**Pull request by endorama**
## What does this PR do?

As per https://github.com/elastic/integrations/issues/3448 (and it's GCP dedicated issue https://github.com/elastic/integrations/issues/3719) we want to migrate Dashboards to use by value visualization instead of by reference.

This PR does it for GCP dashboard available in GCP package as of today.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Closes #3719

### CODE REVIEW

**Comment by endorama** [comment]
Changelog missing, will update once this is ready to be merged

**Review by kaiyan-sheng — COMMENTED** [review]
Besides changelog, I think we are missing the kibana version change in manifest.yml

**Comment by mbondyra** [comment]
I haven't checked all the dashboards yet, but would it be possible to convert the legacy visualizations to Lens when it's possible? For example, for [Logs GCP] Audit dashboard all the selected visualizations are using Visualize and they could be already using Lens. 

Screenshot 2022-09-22 at 22 33 51

**Review by mbondyra — COMMENTED** [review]
I haven't checked all the dashboards yet, but would it be possible to convert the legacy visualizations to Lens when it's possible? For example, for [Logs GCP] Audit dashboard all the selected visualizations are using Visualize and they could be already using Lens. 

Screenshot 2022-09-22 at 22 33 51

**Review by efd6 — APPROVED** [review]
I've checked the dashboards briefly (all appear to be OK, but I have only checked that audit, firewall and vpc flow render events correctly).

**Review by mbondyra — APPROVED** [review]
Approved as probably moving to lens will be a part of a different PR 👌🏼

**Review by kaiyan-sheng — APPROVED** [review]

**Pull request merged**
