### PR TITLE
Upgrade the k8s version when using kind

### PR DESCRIPTION
**Pull request by tetianakravchenko**
## What does this PR do?

During our upgrade procedure, we are updating `K8S_VERSION` value - https://github.com/elastic/integrations/blob/main/.ci/Jenkinsfile#L17

Before this change the only thing affected by it was kubectl binary version - https://github.com/elastic/integrations/blob/main/.ci/Jenkinsfile#L323

but the actual version of kubernetes was defined by the version of kind:
```
kind version
kind v0.14.0 go1.18.2 darwin/amd64

kind create cluster --name test1
Creating cluster "test1" ...
 ✓ Ensuring node image (kindest/node:v1.24.0) 🖼
 ✓ Preparing nodes 📦
```

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by constanca-m — APPROVED** [review]

**Review by gsantoro — APPROVED** [review]

**Review by gizas — APPROVED** [review]

**Comment by ChrsMark** [comment]
@tetianakravchenko the CI failure looks relevant to me: `[2023-01-19T17:51:40.730Z] 2023/01/19 17:51:40 DEBUG found 0 hits in metrics-kubernetes.state_cronjob-ep data stream: index_not_found_exception: no such index [metrics-kubernetes.state_cronjob-ep] Status=404`. Le;ts make sure we check this before merging.

**Comment by constanca-m** [comment]
> @tetianakravchenko the CI failure looks relevant to me: `[2023-01-19T17:51:40.730Z] 2023/01/19 17:51:40 DEBUG found 0 hits in metrics-kubernetes.state_cronjob-ep data stream: index_not_found_exception: no such index [metrics-kubernetes.state_cronjob-ep] Status=404`. Let's make sure we check this before merging.

That happens because the kube state metrics version is not updated right now @ChrsMark. [This PR](https://github.com/elastic/obs-infraobs-team/pull/896) will solve this problem or the one that [this issue](https://github.com/elastic/elastic-package/issues/1102) opens.

**Comment by ChrsMark** [comment]
> > @tetianakravchenko the CI failure looks relevant to me: `[2023-01-19T17:51:40.730Z] 2023/01/19 17:51:40 DEBUG found 0 hits in metrics-kubernetes.state_cronjob-ep data stream: index_not_found_exception: no such index [metrics-kubernetes.state_cronjob-ep] Status=404`. Let's make sure we check this before merging.
> 
> That happens because the kube state metrics version is not updated right now @ChrsMark. [This PR](https://github.com/elastic/obs-infraobs-team/pull/896) will solve this problem or the one that [this issue](https://github.com/elastic/elastic-package/issues/1102) opens.

Thanks for the background info! So is this current PR blocked until the kube-state-metrics installation is automated? Shall we just update the kube-state-metrics for now manually so as to have the CI passing?

**Comment by constanca-m** [comment]
> Thanks for the background info! So is this current PR blocked until the kube-state-metrics installation is automated? Shall we just update the kube-state-metrics for now manually so as to have the CI passing?

I don't think that is necessary, at least for this PR. There are other integrations failing, so we could not merge it even if we updated kube state metrics version @ChrsMark

**Comment by ChrsMark** [comment]
> > Thanks for the background info! So is this current PR blocked until the kube-state-metrics installation is automated? Shall we just update the kube-state-metrics for now manually so as to have the CI passing?
> 
> I don't think that is necessary, at least for this PR. There are other integrations failing, so we could not merge it even if we updated kube state metrics version @ChrsMark

However at least k8s integration test should be successful to merge this PR. Other failures are apparently unrelated to this PR. So before merging the k8s integration test should be successful :).

**Comment by constanca-m** [comment]
> However at least k8s integration test should be successful to merge this PR. Other failures are apparently unrelated to this PR. So before merging the k8s integration test should be successful :).

Unfortunately, I don't think that will work. Since the change is on the Jenkins file, all the integrations tests will run @ChrsMark (and some fail)

**Comment by ChrsMark** [comment]
> > However at least k8s integration test should be successful to merge this PR. Other failures are apparently unrelated to this PR. So before merging the k8s integration test should be successful :).
> 
> Unfortunately, I don't think that will work. Since the change is on the Jenkins file, all the integrations tests will run @ChrsMark (and some fail)

I agree, but it's up to the reviewer to decide to ignore them consider them as unrelated. BTW, do we know why other integrations are failing?

**Comment by constanca-m** [comment]
> I agree, but it's up to the reviewer to decide to ignore them considering them as unrelated (all other except of the k8s one). BTW, do we know why other integrations are failing?

I though the only way to merge a PR was if it passed all the required tests. I'm not aware of why the other integrations are failing.

**Comment by ChrsMark** [comment]
> > I agree, but it's up to the reviewer to decide to ignore them considering them as unrelated (all other except of the k8s one). BTW, do we know why other integrations are failing?
> 
> I thought the only way to merge a PR was if it passed all the required tests. I'm not aware of why the other integrations are failing.

I see, in general if one PR is urgent and it is known that some unrelated tests are failing the PR can be merged if reviewers and contributors agree on this (ignoring the failing but unrelated tests). Otherwise one can just disable any flaky tests (opening also issues for them to be fixed back) and have the CI happy before merging their PR.

To this one PR specifically I would be just fine to approve/merge if k8s tests were successful, even if some others that are unrelated to the changes are failing.

**Comment by tetianakravchenko** [comment]
> I agree, but it's up to the reviewer to decide to ignore them considering them as unrelated (all other except of the k8s one). BTW, do we know why other integrations are failing?

I agree with @ChrsMark on this, that this PR shouldn't be blocked by other integrations packages, I would upgrade kube-state-metrics, make sure kubernetes package does not fails, inform owners of other packages about the failing tests and ask codeowner to merge this PR in

**Comment by tetianakravchenko** [comment]
regarding failing tests - seems it is a known issue - https://github.com/elastic/integrations/pull/5082#issuecomment-1401608397, at least for `beat`, `hadoop` and `haproxy` packages

`aws` error: `ERROR: for elastic-agent_is_ready  Container "6d1c6f9e0e28" is unhealthy.`
`osquery_manager`: `Error: booting up the stack failed: running docker-compose failed: running command failed: running Docker Compose up command failed: exit status 1`

both might be some CI issue, I would try to retriger build

**Comment by tetianakravchenko** [comment]
Failing packages 1 run ([CI run](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-5065/2/pipeline)):
`beat` - known issue
`cloud_security_posture` - fails with the `Error: booting up the stack failed: running docker-compose failed: running command failed: running Docker Compose up command failed: exit status 1`
`hadoop` - known issue
`haproxy` - known issue
`osquery_manager` - `Error: booting up the stack failed: running docker-compose failed: running command failed: running Docker Compose up command failed: exit status 1`

After retriggering (without any change), failing tests (see the[ CI run](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-5065/3/pipeline/1042)):
`beat`
`hadoop`
`haproxy`
`logstash`

@elastic/ecosystem could you please merge this PR, as "merge" button is not active for me, because some tests, unrelated to this PR, are failing.
Also please have a look on randomly failing tests with error like: `ERROR: for elastic-agent_is_ready  Container "6d1c6f9e0e28" is unhealthy.`

**Pull request merged**
