### PR TITLE
[O11y][PostgreSQL] Lens migration for `Database Overview` visualizations to Kibana version 8.4.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for PostgreSQL integration package

- Statistics for PostgreSQL Lens migration:

<html>
<body>

PostgreSQL Dashboards  | Before Migration |   | After Migration |      |  
-- | -- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization | New control panel
[Metrics PostgreSQL] Database Overview | 0 | 10 | 9 | 0 | 1
 | 0 | 10 | 9 | 0 | 1

</body>
</html>

Note: One visualization is migrated to new input controls.

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.4.0 itself.

## Related issues

- Relates #5221

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Comment by rajvi-elastic** [comment]
> Can you please update the Y-axis unit for these two panels ? it is not clear - if the Y axis shows count or a percentage?

@agithomas, Please find below aggregation which is applied to the `Shared block cache stats` panel. We are not sure which unit should we put here. Can you please help us with this? Same functions are also used in the `Local block cache stat` panel.

image

**Comment by agithomas** [comment]
> > Can you please update the Y-axis unit for these two panels ? it is not clear - if the Y axis shows count or a percentage?
> 
> @agithomas, Please find below aggregation which is applied to the `Shared block cache stats` panel. We are not sure which unit should we put here. Can you please help us with this? Same functions are also used in the `Local block cache stat` panel.
> 
> image

Count can be considered here.

**Comment by rajvi-elastic** [comment]
> Can you please update the Y-axis unit for these two panels ? it is not clear - if the Y axis shows count or a percentage?

@agithomas, I have updated the PR as per your suggestion and added Y-axis label to the Local and shared block cache stats panels.

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
