### PR TITLE
[threat_map] Fix Invalid SVG path error

### PR DESCRIPTION
**Pull request by navnit-crest**
Type of change
- Bug

## Proposed commit message

Fixes for the Threat Map:

- **Fix invalid SVG path**:  Modified `geopoint` transform fields from `lat` and `lon` to `coordinates` array to fix the Invalid SVG path error caused by the `geo_point` type for source and destination geolocation fields.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [x] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## How to test this PR locally

1. Clone integrations repo.
2. Install elastic package locally.
3. Start elastic stack using elastic-package.
4. Move to integrations/packages/threat_map directory.
5. Run the following command to run tests. 
> elastic-package test

```
--- Test results for package: threat_map - START ---
╭────────────┬─────────────┬───────────┬─────────────────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME                                                           │ RESULT │ TIME ELAPSED │
├────────────┼─────────────┼───────────┼─────────────────────────────────────────────────────────────────────┼────────┼──────────────┤
│ threat_map │             │ asset     │ dashboard threat_map-fecb4669-516d-4de9-aa98-713aca39fa6c is loaded │ PASS   │      1.467µs │
╰────────────┴─────────────┴───────────┴─────────────────────────────────────────────────────────────────────┴────────┴──────────────╯
--- Test results for package: threat_map - END   ---
Done
```

### Before
before

### After
after

### CODE REVIEW

**Comment by navnit-crest** [comment]
Changes in the Vega spec:
```diff
--- spec1.json	2024-12-27 16:18:45.881939835 +0530
+++ spec2.json	2024-12-27 16:18:56.026109444 +0530
@@ -1,594 +1,600 @@
 {
     "$schema": "https://vega.github.io/schema/vega/v5.json",
     "config": {
         "kibana": {
             "type": "map",
             "latitude": 10,
             "longitude": 10,
             "zoom": 1.3,
             "mapStyle": true,
             "zoomControl": true,
             "scrollWheelZoom": false,
             "delayRepaint": true,
             "tooltips": {
                 "position": "top",
                 "padding": 15,
                 "textTruncate": true
             }
         }
     },
     "signals": [
         {
             "name": "zoom",
             "value": 1
         },
         {
             "name": "latitude",
             "value": 0
         },
         {
             "name": "longitude",
             "value": 0
         },
         {
             "name": "width",
             "value": 900
         },
         {
             "name": "height",
             "value": 560
         },
         {
             "name": "timer",
             "value": 0,
             "on": [
                 {
                     "events": {
                         "type": "timer",
                         "throttle": 10
                     },
                     "update": "if(timer >= 1e4, 0, timer + 10)"
                 }
             ]
         },
         {
             "name": "fraction2",
             "value": 0,
             "on": [
                 {
                     "events": {
                         "signal": "timer"
                     },
                     "update": "(timer % 500) / 500"
                 }
             ]
         },
         {
             "name": "showLables",
             "value": true,
             "bind": {
                 "input": "checkbox"
             }
         }
     ],
     "data": [
         {
             "name": "routes",
             "url": {
                 "index": "_all,*:_all",
                 "body": {
                     "size": 10000,
                     "_source": false,
                     "fields": [
-                        "source.geo.location.lat",
-                        "source.geo.location.lon",
-                        "destination.geo.location.lat",
-                        "destination.geo.location.lon",
+                        "source.geo.location",
+                        "destination.geo.location",
                         "source.ip",
                         "destination.ip",
                         "source.geo.country_name",
                         "destination.geo.country_name",
                         "color",
                         "weight",
                         "animate",
                         "source_label",
                         "destination_label",
                         "pulse_at_source"
                     ],
                     "query": {
                         "bool": {
                             "must": [
                                 "%dashboard_context-must_clause%",
                                 {
                                     "range": {
                                         "@timestamp": {
                                             "%timefilter%": true
                                         }
                                     }
                                 },
                                 {
                                     "exists": {
                                         "field": "source.geo.location"
                                     }
                                 },
                                 {
                                     "exists": {
                                         "field": "destination.geo.location"
                                     }
                                 }
                             ],
                             "must_not": [
                                 "%dashboard_context-must_not_clause%"
                             ],
                             "filter": [
                                 "%dashboard_context-filter_clause%"
                             ]
                         }
                     }
                 }
             },
             "format": {
                 "property": "hits.hits"
             },
             "transform": [
                 {
                     "type": "formula",
                     "expr": "isDefined(datum.fields) && isArray(datum.fields['color']) && datum.fields['color'][0] != null ? datum.fields['color'][0] : '#54B399'",
                     "as": "color"
                 },
                 {
                     "type": "formula",
                     "expr": "isDefined(datum.fields) && isArray(datum.fields['animate']) && datum.fields['animate'][0] != null && datum.fields['animate'][0] == false? 0 : 1",
                     "as": "animateOpacity"
                 },
                 {
                     "type": "formula",
                     "expr": "isDefined(datum.fields) && isArray(datum.fields['weight']) && datum.fields['weight'][0] != null? datum.fields['weight'][0] : 1",
                     "as": "weight"
                 },
                 {
                     "type": "formula",
                     "expr": "isDefined(datum.fields) && isArray(datum.fields['source_label']) && datum.fields['source_label'][0] != null? datum.fields['source_label'][0] : ''",
                     "as": "source_label"
                 },
                 {
                     "type": "formula",
                     "expr": "isDefined(datum.fields) && isArray(datum.fields['destination_label']) && datum.fields['destination_label'][0] != null? datum.fields['destination_label'][0] : ''",
                     "as": "destination_label"
                 },
                 {
                     "type": "formula",
                     "expr": "isDefined(datum.fields) && isArray(datum.fields['pulse_at_source']) && datum.fields['pulse_at_source'][0] != null? datum.fields['pulse_at_source'][0] : false",
                     "as": "pulse_at_source"
                 },
                 {
                     "type": "formula",
                     "expr": "isDefined(datum.fields) && isArray(datum.fields['source.geo.country_name']) && datum.fields['source.geo.country_name'][0] != null? datum.fields['source.geo.country_name'][0] : ''",
                     "as": "source_country"
                 },
                 {
                     "type": "formula",
                     "expr": "isDefined(datum.fields) && isArray(datum.fields['destination.geo.country_name']) && datum.fields['destination.geo.country_name'][0] != null? datum.fields['destination.geo.country_name'][0] : ''",
                     "as": "destination_country"
                 },
                 {
                     "type": "formula",
                     "expr": "isDefined(datum.fields) && isArray(datum.fields['source.ip']) && datum.fields['source.ip'][0] != null? datum.fields['source.ip'][0] : ''",
                     "as": "source_ip"
                 },
                 {
                     "type": "formula",
                     "expr": "isDefined(datum.fields) && isArray(datum.fields['destination.ip']) && datum.fields['destination.ip'][0] != null? datum.fields['destination.ip'][0] : ''",
                     "as": "destination_ip"
                 },
                 {
+                    "type": "filter",
+                    "expr": "!isArray(datum.fields['destination.geo.location']) || !isArray(datum.fields['destination.geo.location'][0]['coordinates']) ? false : true"
+                },
+                {
+                    "type": "filter",
+                    "expr": "!isArray(datum.fields['source.geo.location']) || !isArray(datum.fields['source.geo.location'][0]['coordinates']) ? false : true"
+                },
+                {
                     "type": "geopoint",
                     "projection": "projection",
                     "fields": [
-                        "fields['source.geo.location.lon']",
-                        "fields['source.geo.location.lat']"
+                        "fields['source.geo.location'][0]['coordinates'][0]",
+                        "fields['source.geo.location'][0]['coordinates'][1]"
                     ],
                     "as": [
                         "sourceX",
                         "sourceY"
                     ]
                 },
                 {
                     "type": "geopoint",
                     "projection": "projection",
                     "fields": [
-                        "fields['destination.geo.location.lon']",
-                        "fields['destination.geo.location.lat']"
+                        "fields['destination.geo.location'][0]['coordinates'][0]",
+                        "fields['destination.geo.location'][0]['coordinates'][1]"
                     ],
                     "as": [
                         "targetX",
                         "targetY"
                     ]
                 },
                 {
                     "type": "filter",
                     "expr": "datum.sourceX !== datum.targetX || datum.sourceY !== datum.targetY"
                 },
                 {
                     "type": "linkpath",
                     "shape": "curve",
                     "sourceX": {
                         "field": "sourceX"
                     },
                     "sourceY": {
                         "field": "sourceY"
                     },
                     "targetX": {
                         "field": "targetX"
                     },
                     "targetY": {
                         "field": "targetY"
                     }
                 },
                 {
                     "type": "formula",
                     "as": "control1X",
                     "expr": "datum.sourceX + 0.2 * ((datum.targetX - datum.sourceX) + (datum.targetY - datum.sourceY))"
                 },
                 {
                     "type": "formula",
                     "as": "control1Y",
                     "expr": "datum.sourceY + 0.2 * ((datum.targetY - datum.sourceY) - (datum.targetX - datum.sourceX))"
                 },
                 {
                     "type": "formula",
                     "as": "control2X",
                     "expr": "datum.targetX + 0.2 * ((datum.targetY - datum.sourceY) - (datum.targetX - datum.sourceX))"
                 },
                 {
                     "type": "formula",
                     "as": "control2Y",
                     "expr": "datum.targetY - 0.2 * ((datum.targetX - datum.sourceX) + (datum.targetY - datum.sourceY))"
                 },
                 {
                     "type": "formula",
                     "as": "tooltip_data",
                     "expr": "{source_country: datum.source_country, destination_country: datum.destination_country, source_IP: datum.source_ip, destination_IP: datum.destination_ip}"
                 },
                 {
                     "type": "formula",
                     "as": "pathLength",
                     "expr": "sqrt(pow(datum.control1X - datum.sourceX, 2) + pow(datum.control1Y - datum.sourceY, 2)) + sqrt(pow(datum.control2X - datum.control1X, 2) + pow(datum.control2Y - datum.control1Y, 2)) + sqrt(pow(datum.targetX - datum.control2X, 2) + pow(datum.targetY - datum.control2Y, 2))"
                 },
                 {
                     "type": "formula",
                     "as": "duration",
                     "expr": "datum.pathLength * 5"
                 }
             ]
         },
         {
             "name": "animatedRoutes",
             "source": "routes",
             "transform": [
                 {
                     "type": "formula",
                     "as": "fraction",
                     "expr": "(timer % datum.duration) / datum.duration"
                 }
             ]
         }
     ],
     "marks": [
         {
             "name": "linkpath-curve",
             "type": "path",
             "from": {
                 "data": "routes"
             },
             "encode": {
                 "enter": {
                     "strokeWidth": {
                         "field": "weight"
                     },
                     "stroke": {
                         "field": "color"
                     }
                 },
                 "update": {
                     "path": {
                         "field": "path"
                     }
                 }
             }
         },
         {
             "name": "moving-path",
             "type": "path",
             "from": {
                 "data": "animatedRoutes"
             },
             "encode": {
                 "enter": {
                     "strokeWidth": {
                         "value": 2
                     },
                     "stroke": {
                         "field": "color"
                     }
                 },
                 "update": {
                     "path": {
                         "signal": "'M' + (pow(1 - (datum.fraction - 0.05), 3) * datum.sourceX + 3 * pow(1 - (datum.fraction - 0.05), 2) * (datum.fraction - 0.05) * datum.control1X + 3 * (1 - (datum.fraction - 0.05)) * pow((datum.fraction - 0.05), 2) * datum.control2X + pow((datum.fraction - 0.05), 3) * datum.targetX) + ',' + (pow(1 - (datum.fraction - 0.05), 3) * datum.sourceY + 3 * pow(1 - (datum.fraction - 0.05), 2) * (datum.fraction - 0.05) * datum.control1Y + 3 * (1 - (datum.fraction - 0.05)) * pow((datum.fraction - 0.05), 2) * datum.control2Y + pow((datum.fraction - 0.05), 3) * datum.targetY) + 'L' + (pow(1 - datum.fraction, 3) * datum.sourceX + 3 * pow(1 - datum.fraction, 2) * datum.fraction * datum.control1X + 3 * (1 - datum.fraction) * pow(datum.fraction, 2) * datum.control2X + pow(datum.fraction, 3) * datum.targetX) + ',' + (pow(1 - datum.fraction, 3) * datum.sourceY + 3 * pow(1 - datum.fraction, 2) * datum.fraction * datum.control1Y + 3 * (1 - datum.fraction) * pow(datum.fraction, 2) * datum.control2Y + pow(datum.fraction, 3) * datum.targetY)"
                     },
                     "opacity": {
                         "field": "animateOpacity"
                     }
                 }
             }
         },
         {
             "name": "shadow-path",
             "type": "path",
             "from": {
                 "data": "routes"
             },
             "encode": {
                 "enter": {
                     "tooltip": {
                         "field": "tooltip_data"
                     },
                     "strokeWidth": {
                         "value": 10
                     },
                     "strokeOpacity": {
                         "value": 0.1
                     }
                 },
                 "update": {
                     "path": {
                         "field": "path"
                     },
                     "stroke": {
                         "field": "color"
                     },
                     "opacity": {
                         "field": "animateOpacity"
                     }
                 }
             }
         },
         {
             "name": "moving-arrow",
             "type": "text",
             "from": {
                 "data": "animatedRoutes"
             },
             "encode": {
                 "enter": {
                     "text": {
                         "value": "➤"
                     },
                     "align": {
                         "value": "center"
                     },
                     "baseline": {
                         "value": "middle"
                     },
                     "fontWeight": {
                         "value": "bold"
                     },
                     "fontSize": {
                         "value": 11
                     },
                     "dy": {
                         "value": 1
                     },
                     "fill": {
                         "field": "color"
                     }
                 },
                 "update": {
                     "x": {
                         "signal": "pow(1 - datum.fraction, 3) * datum.sourceX + 3 * pow(1 - datum.fraction, 2) * datum.fraction * datum.control1X + 3 * (1 - datum.fraction) * pow(datum.fraction, 2) * datum.control2X + pow(datum.fraction, 3) * datum.targetX"
                     },
                     "y": {
                         "signal": "pow(1 - datum.fraction, 3) * datum.sourceY + 3 * pow(1 - datum.fraction, 2) * datum.fraction * datum.control1Y + 3 * (1 - datum.fraction) * pow(datum.fraction, 2) * datum.control2Y + pow(datum.fraction, 3) * datum.targetY"
                     },
                     "angle": {
                         "signal": "atan2(3 * pow(1 - datum.fraction, 2) * (datum.control1Y - datum.sourceY) + 6 * (1 - datum.fraction) * datum.fraction * (datum.control2Y - datum.control1Y) + 3 * pow(datum.fraction, 2) * (datum.targetY - datum.control2Y), 3 * pow(1 - datum.fraction, 2) * (datum.control1X - datum.sourceX) + 6 * (1 - datum.fraction) * datum.fraction * (datum.control2X - datum.control1X) + 3 * pow(datum.fraction, 2) * (datum.targetX - datum.control2X)) * 180 / PI"
                     },
                     "opacity": {
                         "field": "animateOpacity"
                     }
                 }
             }
         },
         {
             "name": "fixed-arrow",
             "type": "text",
             "from": {
                 "data": "routes"
             },
             "encode": {
                 "enter": {
                     "fontWeight": {
                         "value": "bold"
                     },
                     "fontSize": {
                         "value": 11
                     },
                     "text": {
                         "value": "➤"
                     },
                     "align": {
                         "value": "center"
                     },
                     "baseline": {
                         "value": "middle"
                     },
                     "fill": {
                         "field": "color"
                     },
                     "dy": {
                         "value": 1
                     }
                 },
                 "update": {
                     "x": {
                         "field": "targetX"
                     },
                     "y": {
                         "field": "targetY"
                     },
                     "angle": {
                         "signal": "atan2(datum.targetY - datum.control2Y, datum.targetX - datum.control2X) * 180 / PI"
                     }
                 }
             }
         },
         {
             "name": "source-labels",
             "type": "text",
             "from": {
                 "data": "routes"
             },
             "encode": {
                 "enter": {
                     "text": {
                         "field": "source_label"
                     },
                     "fill": {
                         "value": "#54B399"
                     },
                     "align": {
                         "value": "center"
                     },
                     "baseline": {
                         "value": "middle"
                     },
                     "fontWeight": {
                         "value": "bold"
                     },
                     "fontSize": {
                         "value": 11
                     }
                 },
                 "update": {
                     "x": {
                         "field": "sourceX"
                     },
                     "y": {
                         "field": "sourceY"
                     },
                     "opacity": [
                         {
                             "test": "showLables == true",
                             "value": 1
                         },
                         {
                             "value": 0
                         }
                     ]
                 }
             }
         },
         {
             "name": "destination-labels",
             "description": "The lables to show at the end of the path",
             "type": "text",
             "from": {
                 "data": "routes"
             },
             "encode": {
                 "enter": {
                     "text": {
                         "field": "destination_label"
                     },
                     "fill": {
                         "value": "#54B399"
                     },
                     "fontSize": {
                         "value": 11
                     },
                     "align": {
                         "value": "center"
                     },
                     "baseline": {
                         "value": "middle"
                     },
                     "fontWeight": {
                         "value": "bold"
                     }
                 },
                 "update": {
                     "x": {
                         "field": "targetX"
                     },
                     "y": {
                         "field": "targetY"
                     },
                     "opacity": [
                         {
                             "test": "showLables == true",
                             "value": 1
                         },
                         {
                             "value": 0
                         }
                     ]
                 }
             }
         },
         {
             "name": "pulsing-circle",
             "type": "arc",
             "from": {
                 "data": "animatedRoutes"
             },
             "encode": {
                 "enter": {
                     "startAngle": {
                         "value": 0
                     },
                     "endAngle": {
                         "value": 6.29
                     },
                     "innerRadius": {
                         "value": 0
                     },
                     "stroke": {
                         "field": "color"
                     },
                     "strokeWidth": {
                         "value": 2
                     }
                 },
                 "update": {
                     "x": [
                         {
                             "test": "datum.fields['pulse_at_source'] && datum.fields['pulse_at_source'] == true",
                             "field": "sourceX"
                         },
                         {
                             "field": "targetX"
                         }
                     ],
                     "y": [
                         {
                             "test": "datum.fields['pulse_at_source'] && datum.fields['pulse_at_source'] == true",
                             "field": "sourceY"
                         },
                         {
                             "field": "targetY"
                         }
                     ],
                     "outerRadius": {
                         "signal": "20 * fraction2"
                     },
                     "strokeOpacity": {
                         "signal": "1 - fraction2"
                     },
                     "opacity": {
                         "field": "animateOpacity"
                     }
                 }
             }
         }
     ]
 }
 ```

**Review by kcreddy — APPROVED** [review]
LGTM

**Comment by iamhowardtheduck** [comment]
Great work and thank you for you!  I noticed if the time window is beyond 1 minute OR if you do not select a single dataset, the animations are very slow.  If you select a single dataset (e.g. netflow) and keep the 1 minute time window, it's super smooth.

**Pull request merged**
