### PR TITLE
ti_crowdstrike: Fix max() calculation on empty resources leading to error

### PR DESCRIPTION
**Pull request by kcreddy**
## Proposed commit message
Fix `max()` calculation on empty resources leading to error.

Due to change made in [`mito`](https://github.com/elastic/mito/pull/65), the 
`max()`function now returns an error message `no extremum of empty list` 
when it is applied on empty `[]` list. This `mito` change is applied to `8.15.0` 
Stack. While this error message is extremely useful, the current CEL program in 
`ti_crowdstrike` doesn't check for empty list. This leads to an error while otherwise 
could have been a `null` value in Stack version `< 8.15.0`.

The PR fixes this by adding a conditional check on empty list, before applying `max()`.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates https://github.com/elastic/integrations/issues/10850

### CODE REVIEW

**Review by andrewkroh — APPROVED** [review]
LGTM

> This leads to an error while otherwise could have been a null value in Stack version < 8.15.0

I believe that prior elastic/mito#65 the behavior was a panic instead of error (which the cel input probably recovered and logged).

**Comment by kcreddy** [comment]
> I believe that prior https://github.com/elastic/mito/pull/65 the behavior was a panic instead of error (which the cel input probably recovered and logged).

Correct. I observed 2 scenarios with earlier `mito` version (1.12.0).

1. When `max` is not wrapped: `{"resources": []}.as(body, body.resources.map(e, e.modified_on)).map(t, timestamp(t)).max()`. This returns panic `panic: runtime error: invalid memory address or nil pointer dereference`
2. When `max` is wrapped: `{"resources": []}.as(body, body.resources.map(e, e.modified_on).map(t, timestamp(t)).max())`. This returns `null`, which is the case with current CEL program.

**Comment by andrewkroh** [comment]
Interesting.  I'm surprised wrapping in an `as` changes the behavior

`[].max() -> panic`

`{}.as(x, [].max()) -> null`

**Comment by efd6** [comment]
With the `as` macro, you will still see the error. With a `map` macro in the same place (`{}.map(x, [].max())`) you will not, since the max is never evaluated because there is no iteration over an empty set of fields.
```
! mito -use collections src.cel
cmp stderr want.txt

-- src.cel --
{}.as(x, [].max())
-- want.txt --
failed eval: ERROR: <input>:1:16: no extremum of empty list
 | {}.as(x, [].max())
 | ...............^
```
versus
```
mito -use collections src.cel
cmp stdout want.txt

-- src.cel --
{}.map(x, [].max())
-- want.txt --
[]
```

**Pull request merged**
