### PR TITLE
[O11y][Apache] Migrate `Metrics overview` dashboard visualizations to lens in kibana 8.3.0

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

- Migrate visualizations to lens for Apache integration package
- As per discussion with @SubhrataK,
  - For `Total accesses`, Kept the original value (not the `k`) in this case, as the number of accesses has to be the exact value and not a rounded off version.

- Statistics for **Apache** Lens migration:

<html>
<body>
<google-sheets-html-origin>

Apache Dashboards | Before Migration |   |   | After Migration |   |  
-- | -- | -- | -- | -- | -- | --
  | Maps | Lens | Visualization | Maps | Lens | Visualization
[Metrics Apache] Overview | 0 | 0 | 12 | 0 | 11 | 1

</body>
</html>

## Checklist

- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that panels are populated with data.
- [x] I have verified that panels are not distorted after being migrated to lens.
- [x] I have updated screenshots of dashboard.
- [x] I have verified that data count are matching and panel aggregations are same as before.

## Author's checklist

- [x] Migrated panels should be removed from visualization folder.
- [x] Migrated visualizations are populating in current Kibana version 8.3.0 itself. 

## Related issues

- Relates #5221

## Issues Identified
- Not able to convert value into human readable format ( Seconds / Minutes / Hours )
  - https://github.com/elastic/kibana/issues/153378

Note: 
- Please refer the following before migrated screenshot for `[Metrics Apache] Overview` dashboard, because the current screenshot is not updated.

image

### CODE REVIEW

**Comment by harnish-elastic** [comment]
As discussed with @SubhrataK, 

1. For the `Not able to convert value into human readable format ( Seconds / Minutes / Hours )`, we keep the old visualization as it is due to not having functionality to user to convert into human-readable and also create the separate issue for the same to track in down. 

2. For the issue `Not having feature to set last bucket value`, we are good with the metrics chart. For the line/area chart we need `auto` functionality in `reduced timerange`. So for the time series visualization we still need to discuss with the kibana team.

3. For the `Splitting a chart into multiple smaller charts by a breakdown dimension is not supported in the lens`, we are going to migrate into table chart. Also need to re-arrange the dashboard like first metrics, then line/area/bar charts, and the table charts be at last.

**Comment by harnish-elastic** [comment]
@agithomas Updated the PR based on this [comment](https://github.com/elastic/integrations/pull/5636#issuecomment-1491731261). Thanks!

**Review by kush-elastic — APPROVED** [review]

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
@SubhrataK , can you please confirm if the new way of representation is good ? Please refer the [screenshot](https://raw.githubusercontent.com/elastic/integrations/8777ad0c1d795b1d7bb6f2a9338acd46f83f6b15/packages/apache/img/apache-metrics-overview.png)

**Comment by harnish-elastic** [comment]
@agithomas The line split charts are basically splitting charts into 5 or 10 line charts as per provided field. We don't have any functionality to migrate this kind of chart in lens. Also as discuss with @SubhrataK, the splitting chart has poor readability. Hence we have converted to table chart in which user can see their actual values based on time interval. Please refer the screenshot for more information.

apache-image

**Comment by harnish-elastic** [comment]
As discuss with @SubhrataK, we are going to rename `Load1/5/15` to `Average server load`. Also will change the position of column and rename it like `load per 1 min`, `load per 5 min`, `load per 15 min`.


image

**Comment by agithomas** [comment]
> As discuss with @SubhrataK, we are going to rename `Load1/5/15` to `Average server load`. Also will change the position of column and rename it like `load per 1 min`, `load per 5 min`, `load per 15 min`.
> 
> image
> 
> @agithomas If you feel like there are many fields in the table feel free to suggest any fields that we can remove.
> 
> image
> 
> Field names that have used
> 
> image

My concern is mainly around representing the CPU usage in tabular manner, when a line graph could explain the trends much better.

**Comment by harnish-elastic** [comment]
@SubhrataK / @agithomas We have converted the line split chart to lens line chart. Let me know if it looks good to you so that we can update the PR accordingly. Please refer this screenshot.

image
image

**Comment by agithomas** [comment]
> @SubhrataK / @agithomas We have converted the line split chart to lens line chart. Let me know if it looks good to you so that we can update the PR accordingly. Please refer this screenshot.
> 
> image image

This looks much better and user friendly. Hope you can update the screenshot.

**Comment by harnish-elastic** [comment]
@agithomas Updated the PR with suggested changes. Thanks!

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
