### PR TITLE
[azure_frontdoor] Fix Azure frontdoor preserve original event

### PR DESCRIPTION
**Pull request by nicpenning**
- Bug

## What does this PR do?
Fixes the "Preserve Original Event" feature for both Frontdoor Access and WAF data streams which has been stated here:
https://github.com/elastic/integrations/issues/6847
https://github.com/elastic/integrations/issues/6848

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by nicpenning** [comment]
This should be good for review and testing. Hopefully a simple but powerful fix!

**Review by efd6 — APPROVED** [review]

**Comment by efd6** [comment]
The test expectations need to be rebuilt for the pipeline tests.

**Comment by nicpenning** [comment]
Updated test expectations

**Comment by nicpenning** [comment]
What a mess. Looks like the Windows Integration tests got merged into here some how?

**Comment by efd6** [comment]
Can you reset hard to fecb8da310563cf1f60e4dd33b3656213c3514db and then push forced after regenerating the test expectationt. There is too much going on here.

By way of advice, don't keep remerging main into branches. Only do this if there is a conflict. IMHO remerging main into a working branch should ~never happen but is an unfortunate consequence of GH's PR design, rebasing to ensure a linear history is preferable unless there are reasons to ensure continuity of review (this is where GH's approach falls into a screaming heap).

**Comment by nicpenning** [comment]
I will rebuild this PR to only include Azure fixes.

**Comment by nicpenning** [comment]
> Can you reset hard to [fecb8da](https://github.com/elastic/integrations/commit/fecb8da310563cf1f60e4dd33b3656213c3514db) and then push forced after regenerating the test expectations. There is too much going on here.
> 
> By way of advice, don't keep remerging main into branches. Only do this if there is a conflict. IMHO remerging main into a working branch should ~never happen but is an unfortunate consequence of GH's PR design, rebasing to ensure a linear history is preferable unless there are reasons to ensure continuity of review (this is where GH's approach falls into a screaming heap).

Sorry I missed this!

I see what I did and I figured I could just start it over. Thanks for the help!

https://github.com/elastic/integrations/pull/7464

**Pull request closed without merging**
