### PR TITLE
Replacing .json pipeline test config files with .yml ones

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

This PR replaces all `.json` pipeline test configuration files with equivalent `*.yml` ones. This ensures that all package-related configuration files are consistently in YAML format.

## Related issues
- https://github.com/elastic/package-spec/issues/106

### CODE REVIEW

**Comment by ycombinator** [comment]
CI is failing on pipeline tests for the `zoom` integration. These failures are legitimate and will be resolved once https://github.com/elastic/elastic-package/pull/264 is merged and the `elastic-package` dependency in this PR is updated.

**Comment by ycombinator** [comment]
@mtojek looks like the new static tests are failing in CI. Is this to be expected?

**Comment by ycombinator** [comment]
@mtojek Re: my previous comment, I guess we will need https://github.com/elastic/integrations/pull/754 to be merged first and then this PR here will need to be rebased on `master` again.

**Comment by ycombinator** [comment]
@mtojek Actually I just updated the `elastic-package` dependency in this PR's `go.mod` again to point to a slightly older release (https://github.com/elastic/elastic-package/commit/adf93024cc499e8ba7da93f27c590ca14bb0a6f7). That release does not include the static test runner changes, which are not needed for this PR anyway.

**Comment by ycombinator** [comment]
jenkins, run the tests please

**Comment by mtojek** [comment]
> @mtojek Actually I just updated the elastic-package dependency in this PR's go.mod again to point to a slightly older release (elastic/elastic-package@adf9302). That release does not include the static test runner changes, which are not needed for this PR anyway.

Yes, that's why I pushed the static test runner, it's not really blocking :) Sorry for the confusion.

**Review by mtojek — APPROVED** [review]

**Pull request merged**
