### PR TITLE
[Thycotic Secret Server] New integration

### LINKED ISSUE #4834: Add Thycotic Secret Server integration
# Integration release checklist

[Thycotic Secret Server](https://thycotic.com/products/secret-server/) is a Privileged Access Management (PAM) solution used by many medium and large organisations as it provides both a GUI as well as an API to facilitate software access, provides automation capabilities, and logs regarding secret access and modification by humans and software.

This is an important data source for a SOC.

Thycotic SS principally logs via syslog in CEF format, refer to: https://thycotic.force.com/support/s/article/SS-Secure-Syslog-CEF-Logging

filebeat within the Elastic Agent will need to perform the following:
1. Storage of message to event.original if configured to do so
2. Syslog parsing
3. Fix unescaped escapes if they exist
4. CEF parsing

Additionally we've found that special characters in the the CEF message string are not escaped by SS prior to sending to the syslog destination, which breaks the default filebeat CEF parser, hence some character substitution prior to CEF KV parsing is needed using a custom filebeat javascript snippet.

We have already developed a working custom log ingest configuration, ingest pipeline and a dashboard for Thycotic SS logs. A pull request will be created referencing this issue shortly.

### All changes

- [X] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [X] Supported versions of the monitoring target are documented
- [X] Supported operating systems are documented
- [X] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [X] Documentation exists
- [X] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [X] At least a manual test with ES / Kibana / Agent has been performed.
- [X] Required Kibana version set to: 8.4.1

### New Package

- [ X] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes

- [X] Dashboards exists
- [X] Screenshots added or updated
- [X] Datastream filters added to visualizations

### Log dataset changes

- [X] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist
- [X] Generated output for at least 1 log file exists

### Filebeat module changes

- [X] Test log files exist for the grok patterns
- [X] Generated output for at least 1 log file exists

### PR DESCRIPTION
**Pull request by colin-stubbs**
Add initial thycotic_ss release

Refer to Add Thycotic Secret Server integration #4834

## What does this PR do?

PR addressing Add Thycotic Secret Server integration #4834

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] Linting/Testing/etc

## How to test this PR locally

A larger sample of logs is available at: thycotic_ss/_dev/deploy/docker/sample_logs/full-sample.log

That can be ingested as a log file by the integration.

## Related issues

- Closes #4834

## Screenshots

Configuration

Dashboard

### CODE REVIEW

**Comment by efd6** [comment]
Follows from #4835

**Comment by efd6** [comment]
Build error from logs:
```
[2023-01-16T21:10:24.614Z] Error: error running package system tests: could not complete test run: could not add data stream config to policy: could not add package to policy; API status code = 422; response body = {"statusCode":422,"error":"Unprocessable Entity","message":"Document \"thycotic_ss-0cb71ae0-5bdd-11ed-b6ae-6bb0097dca82\" has property \"dashboard\" which belongs to a more recent version of Kibana [8.5.0]. The last known version is [8.4.0]"}
```

**Comment by colin-stubbs** [comment]
> Build error from logs:
> 
> ```
> [2023-01-16T21:10:24.614Z] Error: error running package system tests: could not complete test run: could not add data stream config to policy: could not add package to policy; API status code = 422; response body = {"statusCode":422,"error":"Unprocessable Entity","message":"Document \"thycotic_ss-0cb71ae0-5bdd-11ed-b6ae-6bb0097dca82\" has property \"dashboard\" which belongs to a more recent version of Kibana [8.5.0]. The last known version is [8.4.0]"}
> ```

Err... does that mean what I think it means? e.g. the automated testing going on behind this repo is still using an older version of `elastic-package` rather than the most recent release?

**Comment by efd6** [comment]
The version of elastic package that is being used is v0.70.1 from the go.mod. This error is complaining about the stack version. Please bump the kibana version in the manifest.yml.

**Comment by colin-stubbs** [comment]
Additional commit made to bump to 8.5.0 after re-run of elastic-package test

**Review by efd6 — APPROVED** [review]
Thanks

**Pull request merged**
