### PR TITLE
[system] Fix broken visualization for User Renamed Metric in User Management Events Dashboard

### PR DESCRIPTION
**Pull request by nicpenning**
Please label this PR with one of the following labels, depending on the scope of your change:
- Bug

## Proposed commit message
See title 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

Related: https://github.com/elastic/integrations/issues/10431 -> All visualizations implemented here work, except this one. A missed ")" is causing this to break.

## Screenshots
image

### CODE REVIEW

**Comment by nicpenning** [comment]
Ready for tests. Missed a closing parenthesis.

**Review by marc-gr — APPROVED** [review]

**Comment by nicpenning** [comment]
Pinging here again.

**Review by nfritts — APPROVED** [review]

**Comment by nicpenning** [comment]
So close, just need another review here.

**Review by ishleenk17 — APPROVED** [review]
Looks good!

**Comment by nicpenning** [comment]
Thank you very much!

**Pull request merged**
