### PR TITLE
[Couchbase]Add dimensions mapping to miscellaneous datastream

### PR DESCRIPTION
**Pull request by agithomas**
- Enhancement

## What does this PR do?

Add dimensions to `miscellaneous` datastream

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

 - [x] 1. Build verification
`elastic-package build`
`elastic-package stack up -v -d --services package-registry`

- [x] 2. Document count verification after enablement
- [x] 3. Dashboard verification after enablement
- [x] 4. Index template verification
- [x] 5. Index mapping verification
- [x] 6. Index settings verification.
- [x] 7. Index rollover after TSDB disablement verification 

## Related issues
- Relates #7378

### CODE REVIEW

**Comment by agithomas** [comment]
Dashboard verification

image
image

**Comment by agithomas** [comment]
image

**Comment by agithomas** [comment]
Index rollover verification

```{
  "acknowledged": true,
  "shards_acknowledged": true,
  "old_index": ".ds-metrics-couchbase.miscellaneous-default-2023.08.30-000002",
  "new_index": ".ds-metrics-couchbase.miscellaneous-default-2023.08.30-000003",
  "rolled_over": true,
  "dry_run": false,
  "conditions": {}
}```

**Review by ritalwar — APPROVED** [review]
LGTM!

**Pull request merged**
