### PR TITLE
Make etcd integration package GA

### PR DESCRIPTION
**Pull request by agithomas**
- Enhancement

## Proposed commit message

Make ETCD Integration package GA.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [x] Automated Tests / Manual Tests guidelines
- [x] Timeduration guidelines 
- [x] Field mapping guidelines
- [x] Document quality check
- [x] Kibana dashboard guidelines
- [x] TSDB enablementt
- [x] SDHs check
- [x] Enhacement Requests check
- [x] Publish GA checklist summary

## Related issues

- Relates https://github.com/elastic/integrations/issues/8441

## Screenshots

image

### CODE REVIEW

**Review by muthu-mps — COMMENTED** [review]
Here is my observations on the documentation,
1) Can we have all `etcd` reference in lowercase?
2) As we have the metrics dataset which supports V3. Just a thought is it okay to change the title to metrics `(v3)` in the document?
Screenshot 2024-01-24 at 3 16 43 PM

**Comment by agithomas** [comment]
> 1. Can we have all `etcd` reference in lowercase?

Sure , will do that.

**Comment by agithomas** [comment]
> 2\. As we have the metrics dataset which supports V3. Just a thought is it okay to change the title to metrics `(v3)` in the document?

I think, this would lead to more confusions that use. `metrics` is the name of the dataset. If we make it `metrics v3`, it would  be more confusing as there won't be any reference towards what `metrics v3` means.

**Review by muthu-mps — APPROVED** [review]
LGTM!

**Pull request merged**
