### PR TITLE
Add panel to dashboard, add percent field

### PR DESCRIPTION
**Pull request by fearful-symmetry**
closes: https://github.com/elastic/beats/issues/38708
For more context: https://github.com/elastic/beats/pull/39205

This PR adds support in integrations for the new queue percentage full metric. As part of this, we:

- Add a `Queue Usage` panel to the agent metrics dashboard
- Add a `queue.filled.pct.events` field to the integrations

I haven't tinkered with integrations in ages, so...I hopefully haven't broken anything.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

Screenshot 2024-05-01 at 1 49 16 PM

### CODE REVIEW

**Comment by ycombinator** [comment]
@fearful-symmetry Would you mind adding a screenshot of the new panel in the dashboard to this PR's description?

**Comment by leehinman** [comment]
@fearful-symmetry the code changes look fine, but holding off approval till we get a screen shot.  I'm not very good at rendering those kibana json files into dashboards in my head :-)

**Comment by fearful-symmetry** [comment]
Alright, uploaded a screenshot. Also made me realize that I didn't set the percentage correctly. I think it's right now?

**Comment by fearful-symmetry** [comment]
@leehinman / @ycombinator

**Review by leehinman — APPROVED** [review]
LGTM

**Pull request merged**
