### PR TITLE
Osquery Manager: Update schema fields description

### PR DESCRIPTION
**Pull request by aleksmaus**
Provides better description for the schema fields.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Related issues

- Closes https://github.com/elastic/security-team/issues/1226

### CODE REVIEW

**Comment by melissaburpo** [comment]
@aleksmaus - this looks good, but one question: it looks like the `Type` column now has 2 entries for most fields. For example, `keyword, text.text`. Is that intentional? Previously, almost all of them were just `keyword`.

Ex:
image

**Comment by aleksmaus** [comment]
> @aleksmaus - this looks good, but one question: it looks like the `Type` column now has 2 entries for most fields. For example, `keyword, text.text`. Is that intentional? Previously, almost all of them were just `keyword`.
> 
> Ex:
> image

The previous README.MD didn't capture that the fields were multi-fields as defined os osquery.yml for the actual Elasticsearch mapping.

**Review by melissaburpo — APPROVED** [review]

**Review by james-elastic — APPROVED** [review]

**Comment by aleksmaus** [comment]
While testing with kibana stumbled upon issue, the line breaks are sanitized and not rendered correctly.
Screen Shot 2021-05-25 at 1 08 26 PM

Screen Shot 2021-05-25 at 1 10 03 PM

None of the other approaches with markdown worked, it's either didn't render README.md in github correctly or was not rendering with kibana.

Updated to the multi-line cells that looks like this with kibana
Screen Shot 2021-05-25 at 2 25 11 PM

And markdown README.md renders sufficiently ok
Screen Shot 2021-05-25 at 2 29 24 PM

**Comment by melissaburpo** [comment]
That looks great @aleksmaus - it's very readable.

**Pull request merged**
