### PR TITLE
Set default endpoint for AWS to empty string

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
## What does this PR do?

This PR is a follow up for https://github.com/elastic/integrations/pull/4103 to fix the same bug in `cloudflare_logpush` package.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by aspacca** [comment]
@kaiyan-sheng thanks for taking care of this

I would add exposing `default_region` like in https://github.com/elastic/integrations/pull/4158

**Review by aspacca — COMMENTED** [review]
let's remove `endpoint` and add `default_region`, what do you think?

**Comment by kaiyan-sheng** [comment]
@aspacca I was originally thinking to add `default_region` in #4158 :) I can definitely add it here.

**Comment by aspacca** [comment]
hi @kaiyan-sheng we can remove `endpoint` at all, since as far as I can see the integrations does not support fetching from a non aws s3 compatible bucket

@elastic/security-external-integrations could you confirm?

**Review by efd6 — APPROVED** [review]

**Comment by aspacca** [comment]
sorry @kaiyan-sheng I've realised after merging https://github.com/elastic/integrations/pull/4158 that the changes were made there.

I guess this PR can be closed now. 

still there is the topic for this integration about:
> but this probably means that in case of non default logs collection via s3 direct access is working only on effective aws cloud bucket: for compatible non-aws s3 buckets the variable to set is `non_aws_bucket` along with a proper `endpoint`

**Comment by kaiyan-sheng** [comment]
@aspacca No worries! Thanks for checking!! 

I think we still need to set `endpoint` default value to empty string instead.

**Review by aspacca — APPROVED** [review]

**Pull request merged**
