### PR TITLE
[O11y][Hadoop] Remove `(s)` from `Application` dashboard visualization

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Bug

## What does this PR do?

- Remove `(s)` from below `Application` dashboard visualizations:
  - The number of virtual cores the application has allocated [Metrics Hadoop]
  - The amount of memory the application has allocated [Metrics Hadoop] 

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have added an entry to my package's changelog.yml file.

## Related issues

- Relates #5628

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
Please add the unit of memory for "Available Memory" panel

**Comment by agithomas** [comment]
Average elapsed time is shown in ms. Can you convert this to a more human readable state - sec / min / hour?

**Comment by harnish-elastic** [comment]
> Average elapsed time is shown in ms. Can you convert this to a more human readable state - sec / min / hour?

Kibana hasn't any functionality to convert `ms` to sec / min / hour or any human readable state. Also we have already raised an issue for the same. https://github.com/elastic/kibana/issues/153378

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
