### PR TITLE
[Azure Logs] Rebrand azure spring cloud logs to azure spring apps logs

### LINKED ISSUE #4111: [Azure] [Logs] Rebrand Azure Spring Cloud to Azure Spring Apps
In May, Azure and Spring [announced](https://spring.io/blog/2022/05/24/azure-spring-apps-enterprise-is-now-generally-available) a new enterprise tier and renamed the service Azure Spring Cloud as Azure Spring Apps.

We need to update the naming in the Azure Logs integration to match the current Azure naming.

### PR DESCRIPTION
**Pull request by muthu-mps**
- Enhancement

## Proposed commit message
This PR updates the Azure Spring Cloud Logs to Azure Spring Apps Logs as per the change mentioned [here](https://spring.io/blog/2022/05/24/azure-spring-apps-enterprise-is-now-generally-available)

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Install the Azure Spring Cloud Logs integrations and upgrade the integrations and verify the data is getting loaded in the dashboards.
- Check the older name gets replaced with the newer name in all the places.
- ### Verify the changes in the following places
  - Documentation 
  - Add Integrations page
  - Dashboard title, description, Visualisation title

## Related issues
- Closes #4111 

## Screenshots
Screenshot 2023-10-13 at 6 19 03 PM

### CODE REVIEW

**Comment by muthu-mps** [comment]
> I see we are changing the labels and the description with the new "Spring Apps" name, which is good.
> 
> The data stream name, the dataset, and the fields keep the old `azure.springcloudlogs` name?

When we change the `datastream` name this will add a new service in the UI. The existing users might not be able to update the service from the older version to newer version.

If we try to change the field name then this will become a breaking change. When making this change we have to consider the Kibana dashboards updated with the new field names. Can we have `aliases` for the fields this would help maintain consistency while searching for data from older fields and from the newer fields?

Also the `event.dataset` filter should be applied with older and newer names to render the data ingested from older version and with the newer version.

@zmoog - If we change the `datastream` name to a new name, Will the policy template work for updating the existing integration ? Can we consider changing the `field name` and the `datastream` names?

**Comment by zmoog** [comment]
Hey @muthu-mps, the same questions stopped me from completing the [previous PR](https://github.com/elastic/integrations/pull/4112) on this topic. 

Changing the data stream name from `azure.springcloudlogs` to `azure.springappslogs` would probably result in a breaking change.

We can approach this at the branding level only or go deeper:

1. Branding only: update the externally visible names to "Spring Apps" and keep internal names (fields, data stream, etc) to the old name — what this PR is doing.
2. Go deeper: replace "spring cloud" with "spring app" internally and externally. 

What's your take from the product perspective, @SubhrataK ?

@muthu-mps, one option I contemplated back in the day was to add a new integration named "Spring Apps" and mark "Spring Cloud" as deprecated; this may be a compelling option, especially if we can add an alias for the older `azure.springcloudlogs.` fields in the new integration: do you know if aliasing works across different data streams?

**Comment by muthu-mps** [comment]
@zmoog - As per the recent discussions with @SubhrataK , We can go-ahead with renaming the application externally. Hope this helps!

**Review by zmoog — APPROVED** [review]
@muthu-mps, if @SubhrataK wants to focus on external rebranding, this PR is spot-on.

Nit: we may consider updating the inner pipeline description at https://github.com/elastic/integrations/blob/6f9073c4a448710bec48aa9186c76eaae7ce7205/packages/azure/data_stream/platformlogs/elasticsearch/ingest_pipeline/springcloudlogs-inner-pipeline.yml#L2. 

For a reason I don't know, we have a copy of the Spring Apps logs embedded in the platform logs integration. My wild guess is that this is to support better the Native Azure Integration that has limited routing capabilities, but I am unsure. Maybe @hemantmalik knows more about this backstory. 

We can drop the Spring Apps logs pipeline embedded in the platform logs as we add routing rules capabilities to the Azure Logs integration. More on this topic soon.

**Comment by muthu-mps** [comment]
> For a reason I don't know, we have a copy of the Spring Apps logs embedded in the platform logs integration. My wild guess is that this is to support better the Native Azure Integration that has limited routing capabilities, but I am unsure. Maybe @hemantmalik knows more about this backstory.
> 
> We can drop the Spring Apps logs pipeline embedded in the platform logs as we add routing rules capabilities to the Azure Logs integration. More on this topic soon.

Thanks @zmoog! Let me verify the reason for embedding in platform logs.

**Comment by zmoog** [comment]
> Thanks @zmoog! Let me verify the reason for embedding in platform logs.

I guess we added it back in the day to process spring cloud logs coming from the Native Azure Integration.

We can't remove it until we add routing rules.

**Pull request merged**
