### PR TITLE
Update Synthetics package fields to create appropriate mapping

### PR DESCRIPTION
**Pull request by justinkambic**
## What does this PR do?

In the initial version of the synthetics package we specified incorrect fields for our agent. This PR should fix that issue, although there may be additional fields we want to add in the future.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [ ] I have verified that all datasets collect metrics or logs.
  - leaving this unchecked because we are waiting on some changes to Agent. If necessary we can leave this PR unmerged until Agent is unblocked.

## Author's Checklist

- [x] Load package assets in Kibana
- [x] (For Synthetics team member) Make sure the fields we're loading look good
- [x] Create a configuration without error

## How to test this PR locally

- Run a package registry with this package version loaded
- Configure Kibana/ES to use your registry
- Ensure the package shows up in IM
- Create a configuration

## Related issues

N/A

### Load assets

For anyone unfamiliar, you can use the IM UI to load a package's assets before creating any configuration. You can then view them under stack management's index page (see below).

synthpackage

### Fields viewed in Index Management

image

### Adding configuration

image

### CODE REVIEW

**Comment by mtojek** [comment]
The CI job failed. It looks that there are unformatted files. Try to run `mage check` locally.

**Comment by justinkambic** [comment]
I'm unsure how to diagnose the CI failure. The log has these lines:

```
[2020-08-24T23:55:35.637Z] 2020/08/24 23:55:35 Notice: the template file "dev/import-beats-resources/synthetics/docs/README.md" does not exist. The README.md file will not be rendered.

...

[2020-08-24T23:55:42.485Z] packages/synthetics/dataset/monitor/fields/fields.yml: needs update
[2020-08-24T23:55:42.485Z] packages/synthetics/manifest.yml: needs update
```

Running `mage-check` locally yields output like:

```
packages/apache: elastic-package lint
packages/aws: elastic-package lint
packages/checkpoint: elastic-package lint
packages/cisco: elastic-package lint
packages/crowdstrike: elastic-package lint
packages/fortinet: elastic-package lint
packages/haproxy: elastic-package lint
packages/iis: elastic-package lint
packages/kafka: elastic-package lint
packages/kubernetes: elastic-package lint
packages/log: elastic-package lint
packages/microsoft: elastic-package lint
packages/mongodb: elastic-package lint
packages/mysql: elastic-package lint
packages/netflow: elastic-package lint
packages/nginx: elastic-package lint
packages/o365: elastic-package lint
packages/okta: elastic-package lint
packages/panw: elastic-package lint
packages/postgresql: elastic-package lint
packages/prometheus: elastic-package lint
packages/rabbitmq: elastic-package lint
packages/redis: elastic-package lint
packages/suricata: elastic-package lint
packages/synthetics: elastic-package lint
packages/system: elastic-package lint
packages/windows: elastic-package lint
packages/zookeeper: elastic-package lint
>> fmt - go-licenser: Adding missing headers
Error: failed to run "go-licenser -license Elastic: exec: "go-licenser": executable file not found in $PATH"
```

**Comment by ruflin** [comment]
I think you need to install go-licenser: https://github.com/elastic/go-licenser

Also if the README.md is actually missing, best add one. There also seems to be something off with the yaml file linting. @mtojek can help you with that.

**Comment by justinkambic** [comment]
> if the README.md is actually missing, best add one.

There's a README.md under `~/docs/README.md`.

> I think you need to install go-licenser

I think I was running this project from the wrong place, I moved it alongside my other golang repos and path-specific problems seemed to be resolved. `mage format` runs without errors now on my local system. It looks like CI problems resolved as well.

**Comment by justinkambic** [comment]
@andrewvc when you have time please leave feedback on the actual fields themselves, I think that's all that is holding us back at this point.

**Comment by andrewvc** [comment]
Almost there, the only fields I see missing are the `tls.*` fields from https://github.com/elastic/beats/blob/master/heartbeat/monitors/active/dialchain/_meta/fields.yml Let's be sure to add all those

**Comment by justinkambic** [comment]
@andrewvc check https://github.com/elastic/integrations/pull/252/commits/60515ebfdcd269c700d8671ef886f6587d260623

**Review by mtojek — CHANGES_REQUESTED** [review]
Please adjust the PR accordingly to changes introduced in https://github.com/elastic/integrations/pull/280 .

Main changes:

0. Rebase against master.
1. Rename "dataset" folder to "data_stream".
2. Rename "config_templates" to "policy_templates" in package manifest file.

**Comment by justinkambic** [comment]
Closing this for now as we aren't actively working on this.

**Pull request closed without merging**
