### PR TITLE
[pfSense] Add OPNsense support and multiple other log types

### LINKED ISSUE #2401: OPNsense/pfSense Integration
Thanks for adding the pfSesne Integration! It is obvious the work from from @pfelk was copied without credit...would you like the @pfelk repo transferred too - you can certainly maintain that project until you've replicated within the pfSense integration.

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Adds support for OPNsense and adds other logs types to be parsed. Also bumps the version to 1.0.0 and GA release.

- [X] OPNsense support
- [X] PHP-FPM Logs
- ~~Captive Portal Logs~~
- ~~Suricata~~
- [x] Squid

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Closes #2401

### CODE REVIEW

**Comment by legoguy1000** [comment]
I removed Captive Portal logs as I didn't have access to samples.

**Comment by legoguy1000** [comment]
@fabiogermann Here is the PR, I already added the OPNsense support thanks to @a3ilson.  If there is anything else u want added, just let me know.  I may need sample logs from you.

**Comment by a3ilson** [comment]
> @fabiogermann Here is the PR, I already added the OPNsense support thanks to @a3ilson. If there is anything else u want added, just let me know. I may need sample logs from you.

Awesome! Adding support for the following OPNsense logs, in addition to the firewall logs, would be greatly appreciated:
- unbound
- Suricata
- Captive
- Nginx
- Haproxy
- squid 
- dhcp

The grok patterns, templates and dashboards  for the above work for both pfSense and OPNsense and may be found at the @pfelk repo.

**Comment by legoguy1000** [comment]
Unbound, HAProxy, DHCP are already in the module. I can copy the Suricata module like I did with the Haproxy logs. I don't have a captive portal or Squid on my pfsense install so if u can provide the sample logs I can use to validate the grok patterns, I can add them.

**Comment by a3ilson** [comment]
## squid 
```
<166>Aug 21 22:08:13 myfirewall.my-domain.tld (squid-1)[6802]: [1598040493.253 325](tel:1598040493.253 325) 172.16.17.119 TCP_MISS/304 2912 GET https://github.com/3ilson/pfelk/file-list/master - HIER_DIRECT/140.82.121.4 -
```

## captive 
```
<165>Jan 17 13:45:14 firewall.domain.dev captiveportal[68837]: starting captiveportal background process
```

```
<166>Jan 17 14:01:29 firewall.domain.dev captiveportal[6155]: AUTH username (192.168.1.102) zone 0
```

**Comment by legoguy1000** [comment]
Thanks if there are other samples/examples u can provide, the more the merrier but I can start with those.

**Comment by andrewkroh** [comment]
@Mergifyio update

**Comment by legoguy1000** [comment]
I removed Suricata and Captive portal for now. The OPNsense, PHP-FPM, Squid logs should be good to go.

**Comment by legoguy1000** [comment]
@andrewkroh could u rerun tests?

**Comment by legoguy1000** [comment]
I found the issues with the TLS system test, had an incorrect port.  rerunning locally and will push

**Comment by legoguy1000** [comment]
@andrewkroh random question, what are u guys looking at to generate the coverage reportv since packages are all just different configs of the agent?

**Comment by andrewkroh** [comment]
See https://github.com/elastic/integrations/blob/master/docs/testing_and_validation.md#cobertura-format-vs-package-domain-language to understand the mappings. I think the annotated source report is still in progress, like https://github.com/elastic/elastic-package/pull/704.

**Comment by legoguy1000** [comment]
This is ready to merge.

**Pull request merged**
