### PR TITLE
[O11y][Nginx]  Migrate `[Metrics Nginx] Overview` dashboard visualizations to lens in kibana 8.5.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate `[Metrics Nginx] Overview` dashboard visualizations to lens for Nginx integration package

- Statistics for Nginx Lens migration:
<html>
<body>

Nginx Dashboards | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics Nginx] Overview | 0 | 9 | 9 | 0
  | 0 | 9 | 9 | 0
</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.5.0 itself.

## Related issues

- Relates #5221

### CODE REVIEW

**Review by milan-elastic — APPROVED** [review]

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Review by agithomas — COMMENTED** [review]
Y -axis is missing for some of the panels. Please add the Y-axis and the appropriate labels to Y-axis

**Comment by rajvi-elastic** [comment]
> Y -axis is missing for some of the panels. Please add the Y-axis and the appropriate labels to Y-axis

@agithomas, Below are the suggested Y-axis labels:

<html>
<body>

Panel | Y-axis label 
-- | -- 
 Active connections [Metrics Nginx] | Active
Reading / Writing / Waiting Rates [Metrics Nginx] <br> Request Rate [Metrics Nginx] <br>Accepts and Handled Rate [Metrics Nginx]<br>Drops Rate [Metrics Nginx] | Rate
</body>
</html>

Should we update PR with above Y-axis labels?

**Comment by agithomas** [comment]
> > Y -axis is missing for some of the panels. Please add the Y-axis and the appropriate labels to Y-axis
> 
> @agithomas, Below are the suggested Y-axis labels:
> 
> Panel	Y-axis label
>  Active connections [Metrics Nginx]	Active
> Reading / Writing / Waiting Rates [Metrics Nginx]
> Request Rate [Metrics Nginx]
> Accepts and Handled Rate [Metrics Nginx]
> Drops Rate [Metrics Nginx]	Rate
> Should we update PR with above Y-axis labels?

looks good to me. Yes, please.

**Comment by rajvi-elastic** [comment]
> Y -axis is missing for some of the panels. Please add the Y-axis and the appropriate labels to Y-axis

@agithomas, I have updated the PR with suggested Y-axis labels. Can you please review it?

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
