### PR TITLE
[MongoDb] Tsdb enabled release

### PR DESCRIPTION
**Pull request by ritalwar**
- Enhancement

## What does this PR do?

This PR enables TSDB for MongoDB module.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates #6152

### CODE REVIEW

**Comment by jsoriano** [comment]
> Blocked on: [elastic/elastic-package#1334](https://github.com/elastic/elastic-package/issues/1334)

A new version of elastic-package including a fix for this blocker (https://github.com/elastic/elastic-package/pull/1335) has been released and is used in integrations repo. Please try to update the branch.

**Comment by lalit-satapathy** [comment]
@ritalwar, Can we close this PR if no longer applicable?

**Pull request closed without merging**
