### PR TITLE
Add GitHub audit integration

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Adds integration to fetch GitHub audit logs

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [X] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Author's Checklist

- [ ]

## How to test this PR locally
```
cd integrations/packages/github
elastic-package build && elastic-package stack down && elastic-package stack up  --version 7.16.0-SNAPSHOT  -d -v && eval "$(elastic-package stack shellinit)" && elastic-package test -v
```

## Related issues

-

## Screenshots
github-user
github-audit

### CODE REVIEW

**Comment by P1llus** [comment]
Just going to see if we can test this against our own Github Account, but the rest looks good!

**Comment by legoguy1000** [comment]
> Just going to see if we can test this against our own Github Account, but the rest looks good!

Sweet. You'll need someone with `org:admin` role.

**Review by P1llus — APPROVED** [review]
Works great! tested on our API as well, LGTM!

**Pull request merged**
