### PR TITLE
Add "security" category to featured security integrations

### PR DESCRIPTION
**Pull request by hop-dev**
## What does this PR do?

As part of https://github.com/elastic/kibana/issues/141823, we want to have featured integrations for certain categories. The network_traffic and cloud_security_posture integrations will be featured in the security category so they need the security category in the manifest.

### CODE REVIEW

**Review by oren-zohar — APPROVED** [review]
LGTM

**Review by andrewkroh — APPROVED** [review]
LGTM. But if you want these changes to ship then you need to bump the version and add a changelog entry to each package. This tool can do the work for you https://github.com/elastic/elastic-package#elastic-package-changelog.

**Comment by hop-dev** [comment]
> LGTM. But if you want these changes to ship then you need to bump the version and add a changelog entry to each package. This tool can do the work for you https://github.com/elastic/elastic-package#elastic-package-changelog.

Hi @andrewkroh thanks for this! Does it seem like overkill to bump the package versions for a category addition? I guess cloud security may be under active dev so a new version will be released soon-ish, network traffic may not have a new release coming out soon so I may do it for that one?

**Comment by hop-dev** [comment]
@oren-zohar I have re-requested your review, would you be happy for me to bump the cloud_securoty_posture version to get this change released?

**Review by amitkanfer — APPROVED** [review]

**Comment by oren-zohar** [comment]
> Thanks so much for your help Andrew.
> 
> @oren-zohar I have re-requested your review, would you be happy for me to bump the cloud_securoty_posture version to get this change released?

yes if you could it would be great thanks Mark 🙏

**Pull request merged**
