### PR TITLE
[proofpoint_tap] Add Proofpoint TAP package

### PR DESCRIPTION
**Pull request by darshan-elastic**
## What does this PR do?

- Generated the skeleton of the Proofpoint TAP integration package.
- Added a data stream.
- Added data collection logic to the data stream.
- Added the ingest pipeline for the data stream.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yml files
- Added dashboards and visualizations.
- Added test for pipeline for the data stream.
- Added system test cases for the data stream.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally
- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/proofpoint_tap directory.
- Run the following command to run tests.
 `elastic-package test`

## Related issues
- https://github.com/elastic/integrations/issues/2464

## Screenshots

image
image
image
image

### CODE REVIEW

**Comment by darshan-elastic** [comment]
@jamiehynds  @andrewkroh  This integration has been tested using a mock server.

**Comment by andrewkroh** [comment]
There are some duplicate field definitions that should be cleaned up (in preparation for https://github.com/elastic/package-spec/pull/309).

```
packages/proofpoint/data_stream/emailsecurity
packages/proofpoint/data_stream/emailsecurity/fields/ecs.yml:1 - @timestamp : [Duplicate field (2 times).]
packages/proofpoint/data_stream/emailsecurity/fields/base-fields.yml:18 - @timestamp : [Duplicate field (2 times).]
packages/proofpoint/data_stream/emailsecurity/fields/base-fields.yml:42 - tags : [Duplicate field (2 times).]
packages/proofpoint/data_stream/emailsecurity/fields/ecs.yml:209 - tags : [Duplicate field (2 times).]
```

**Review by andrewkroh — APPROVED** [review]

**Pull request merged**
