### PR TITLE
[System] GA release for time_series index.mode

### PR DESCRIPTION
**Pull request by tetianakravchenko**
## What does this PR do?

Add a changelog record to the system package regarding the enablement of TSDB, add the doc regarding the time series index mode.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by lalit-satapathy — APPROVED** [review]
Approving since GA was already enabled. This does it cleanly now.

**Comment by tetianakravchenko** [comment]
FYI: tests are failing with the error:
```
Error: error running package system tests: could not complete test run: failed to tear down runner: failed to uninstall package: can't remove the package: could not remove package; API status code = 400; response body = {"statusCode":400,"error":"Bad Request","message":"unable to remove package with existing package policy(s) in use by agent(s)"}
```

fix - https://github.com/elastic/elastic-package/pull/1315, waiting for the next elastic-package release

**Comment by mrodm** [comment]
Merging this PR.

This failure is related to an issue solved by this elastic-package PR https://github.com/elastic/elastic-package/pull/1315 . It was also checked that tests for this package are run successfully with a previous version of elastic-package

cc @tetianakravchenko

**Pull request merged**
