### PR TITLE
Revert: prisma_cloud: fix login endpoint path (#11885)

### PR DESCRIPTION
**Pull request by efd6**
## Proposed commit message

Change was incorrect[1]. Also improve documentation in the config UI.

[1]https://pan.dev/prisma-cloud/api/cwpp/post-authenticate/

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## Author's Checklist

- [ ] 

## Related issues

- Ref #11885

### CODE REVIEW

**Review by chrisberkhout — APPROVED** [review]
Does revert as it says, so I assume it's good to go.

Looking at the documentation, I see a URL format like this:
```
https://<CONSOLE>/api/v<VERSION>/authenticate
```
So it looks like the `url` variable should be set to `https://<CONSOLE>/api/v<VERSION>`. In the manifest files, `url` is described as:

> Base URL of the Prisma Cloud Server API.

Maybe an example value should be added there to avoid setting `https://<CONSOLE>` by mistake.

**Comment by efd6** [comment]
Waiting for input from @mohitjha-elastic

**Comment by mohitjha-elastic** [comment]
The changes look good to me, and including an example format in the base URL makes it clearer for the user.

**Pull request merged**
