### PR TITLE
Fix k8s overview dashboard

### PR DESCRIPTION
**Pull request by ChrsMark**
## What does this PR do?

Fixes k8s dashboard as part of https://github.com/elastic/integrations/issues/2159. Porting PR for https://github.com/elastic/beats/pull/30913 (+https://github.com/elastic/beats/pull/30986):

Screenshot 2022-03-23 at 10 24 20 AM
Screenshot 2022-03-23 at 10 24 02 AM
Screenshot 2022-03-23 at 10 23 48 AM

Closes https://github.com/elastic/integrations/issues/2906 too.

### CODE REVIEW

**Comment by ChrsMark** [comment]
@mtojek any ideas for the failure on https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-2876/3/pipeline#step-793-log-311?

**Comment by mtojek** [comment]
Did you check Kibana version in the dashboard/visualizations JSON files?

**Comment by ChrsMark** [comment]
> Did you check Kibana version in the dashboard/visualizations JSON files?
> 
> EDIT:
> 
> I suspect that you used/dumped using newer Kibana and now testing with 7.16.0.

Yes this is intentional. The dashboards I build are leveraging 8.2 Kibana's features. Is this supported in testing or I have to wait?

**Comment by mtojek** [comment]
> Yes this is intentional. The dashboards I build are leveraging 8.2 Kibana's features. Is this supported in testing or I have to wait?

I guess that it means that the package won't be supported by older Kibanas and you need to update the Kibana version constaint.

**Comment by ChrsMark** [comment]
Isn't https://github.com/elastic/integrations/pull/2876/files#diff-d20d8086b58468701d8a944fc3ead31ddcc098054affdcc335b69464b4c16c54R13 enough? Or I should completely remove the `7.16.0` part, this would lead to making the package backwards incompatible with 7.x from now on?

**Comment by mtojek** [comment]
Yes, it's a breaking change for dashboards anyway.

**Comment by ChrsMark** [comment]
@mtojek is there any reference about such changes sanity? I'm wondering how safe it is to just remove the `7.16` compatibility at this point but on the other hand we cannot just stick not doing the new changes. Do we have a specific plan for such cases so as to be covered in case we need a fix for 7.x?

**Comment by mtojek** [comment]
There are teams which already decided to support only the 8.x packages and, in case there is a necessity to release a bugfix, they push modified packages directly to Package Storage. Fortunately, these are really rare cases. The idea is to prevent overusing backporting and just design features to be backward compatible.

There are open discussions around those issues and due to low priority, we don't look into them actively. I can give you references to those if you want to take a look and comment.

**Comment by ChrsMark** [comment]
> There are teams which already decided to support only the 8.x packages and, in case there is a necessity to release a bugfix, they push modified packages directly to Package Storage. Fortunately, these are really rare cases. The idea is to prevent overusing backporting and just design features to be backward compatible.
> 
> There are open discussions around those issues and due to low priority, we don't look into them actively. I can give you references to those if you want to take a look and comment.

I see thanks for the extra info.

**Comment by mtojek** [comment]
Zrzut ekranu 2022-03-29 o 16 21 18

**Comment by ChrsMark** [comment]
@tetianakravchenko @MichaelKatsoulis  this PR is ready for review :).

**Review by tetianakravchenko — APPROVED** [review]
LGTM!

**Comment by ChrsMark** [comment]
CI is failing because of https://github.com/elastic/integrations/issues/2906. I added the missing field here so this PR close https://github.com/elastic/integrations/issues/2906 too.

**Review by MichaelKatsoulis — APPROVED** [review]

**Pull request merged**
