### PR TITLE
[Salesforce] Add pagination support for login_rest and logout_rest data streams

### PR DESCRIPTION
**Pull request by kush-elastic**
## What does this PR do?
In the current Salesforce Integration, we don’t have pagination support for login-rest and logout-rest data streams. So if in any case, we have a response body with more than 2000 records, the next page is never called and the data will not be fetched.

Solution:
You can request the next batch of records using the provided URL with your instance and session information, and repeat until all records have been retrieved. These requests use `nextRecordsUrl` and don’t include any parameters. The final batch of records doesn’t have a `nextRecordsUrl` field and return `true` value for field `done`

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates #3940 
- Relates #4261
- Relates #4323

### CODE REVIEW

**Comment by agithomas** [comment]
Please complete the internal review. Send me a note once it is done

**Comment by harnish-elastic** [comment]
> Please complete the internal review. Send me a note once it is done

We are not able to provide approval from the Elastic account. It seems like still, some access is missing for the Elastic GitHub integration repo. Hence we are not able to approve. We have raised an IT ticket for the same.

**Comment by agithomas** [comment]
> > Please complete the internal review. Send me a note once it is done
> 
> We are not able to provide approval from the Elastic account. It seems like still, some access is missing for the Elastic GitHub integration repo. Hence we are not able to approve. We have raised an IT ticket for the same.

You would not be able to approve the PR. The general practice followed is, the other team member does the review and comment the change looks good to him / her . Then, it comes for the review of Elastic team. Please comment the PR once peer review is complete

**Comment by agithomas** [comment]
> > Please complete the internal review. Send me a note once it is done
> 
> We are not able to provide approval from the Elastic account. It seems like still, some access is missing for the Elastic GitHub integration repo. Hence we are not able to approve. We have raised an IT ticket for the same.

You may consider cancelling the IT ticket created for this purpose as it is not needed at the moment . If you decide to proceed, kindly ensure atleast one of the Elastic team member performs the code review. 

cc @rameshelastic

**Comment by harnish-elastic** [comment]
> > > Please complete the internal review. Send me a note once it is done
> > 
> > 
> > We are not able to provide approval from the Elastic account. It seems like still, some access is missing for the Elastic GitHub integration repo. Hence we are not able to approve. We have raised an IT ticket for the same.
> 
> You may consider cancelling the IT ticket created for this purpose as it is not needed at the moment . If you decide to proceed, kindly ensure atleast one of the Elastic team member performs the code review.
> 
> cc @rameshelastic

Currently, only Kush has access, But when he raises the PR, others are not able to review it. So we need at least one more person who has the access to reviewers and approval.

**Comment by agithomas** [comment]
> Currently, only Kush has access, But when he raises the PR, others are not able to review it. So we need at least one more person who has the access to reviewers and approval.

For now, as with the case of other PRs, kindly do a PR review and let the reviewer comment if the change looks to him / her

**Comment by harnish-elastic** [comment]
LGTM! Approved. ✅

**Review by agithomas — APPROVED** [review]
Approved

**Pull request merged**
