### PR TITLE
[hadoop][visualizations] Add visualizations for Hadoop

### PR DESCRIPTION
**Pull request by yug-elastic**
## What does this PR do?

- Added dashboard and visualizations.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^8.0.0`).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/hadoop directory.
- Run the following command to run tests. 
> elastic-package test 

## Screenshots
Applications
hadoop-cluster-overview-dashboard-screenshot
hadoop-data-node-dashboard-screenshot
Node Manager

### CODE REVIEW

**Review by mtojek — COMMENTED** [review]
Thanks for submitting the dashboards. I have a few ideas on how to improve them. My recommendation is to do something similar as @sunny-elastic for Spring Boot, so provide multiple dashboards.

1. Cluster overview:
* node managers active, decommissioned, etc.
* nodes active, decomission, etc.
* apps completed, failed, killed, pending, running, etc.
* containers allocated, pending, reserved, etc.

2. Applications:
+ _Filter to select application_
+ _Filter to select node_
* running containers
* average finished time
* memory allocated
* main launch time, delay
* app memory

3. Nodes
* (value) live nodes
* (value) unhealthy nodes
* (value) lost nodes
* Data nodes section:
  + Filter to select a node
  * (value) disk space
  * (gauge) cache total/used capacity
  * bytes read/written
  * failed volumes
  * blocks
* Node manager section:
  * containers:
    * running, allocated, completed, etc.
    * avg launch time

**Comment by yug-elastic** [comment]
Thanks for your feedback, @mtojek!

We have implemented the changes in the dashboards as per your suggestions. We had to separate the `Nodes` and the `Node Manager` dashboard as the documents belonged to different data streams and created issues in some of the visualizations when we filter out based on the nodes.

Please re-review the visualizations and let us know what you think of them.

**Review by mtojek — COMMENTED** [review]
A bunch of suggestions based on screenshots:

* nit: number of cores (countable), amount of memory (uncountable)
* Does amount of virtual cores changes over time? If so, would replace it with line graph.
* Same with memory. BTW why is it in seconds? What does it mean :)?
* Not sure about this: is there an option to adjust the unit of "Average Elapsed Time"? When it's small it's `ms`, if larger then `s`.
* Container Launch Duration also line graphs (to see the historical trend and catch if something bad happens).

I don't know what to do with elapsed time of different apps. If the counter always go app, I would replace it with a value?

**Comment by yug-elastic** [comment]
Thanks for the suggestions, please find the point-wise responses below:

- The naming convention that we have used is according to [this](https://github.com/elastic/integrations/issues/1543#:~:text=memorySeconds,resources%20the%20application%20has%20allocated) description. Please let us know if you think we should update it to something which sounds more intuitive to you.

- The amount of virtual cores does not change once the application finishes its execution.
- The amount of memory and virtual cores are in seconds denoting the amount of time they were kept allocated.
- Good idea, but AFAIK, we can not dynamically change from `ms` to `s`, we can only stick to either one of them.
- That makes sense, we have updated `Container launch duration average time` to a line graph.

The elapsed time of different apps is used to compare different applications' elapsed time. For instance, if only one application is selected in the filter it would show a single value.

**Review by mtojek — COMMENTED** [review]
Thanks for all adjustments, LGTM.

Regarding naming, "amount of cores" is a grammar mistake. I think that it should be "number of cores". Could you please adjust the dashboard label?

**Comment by lalit-satapathy** [comment]
- hadoop-data-node-dashboard-screenshot.png

Says “Decommissioning Data Nodes”  should it be “Decommissioned Data Nodes”?

- hadoop-cluster-overview-dashboard-screenshot.png

Can you point to a dashboard with active/lost/unhealthy/* nodes > 0 in the Number of node managers over time?

**Comment by yug-elastic** [comment]
> * hadoop-data-node-dashboard-screenshot.png
> 
> Says “Decommissioning Data Nodes” should it be “Decommissioned Data Nodes”?

We have followed the naming convention as given [here](https://github.com/elastic/integrations/issues/1543#:~:text=NumDecommissioningDataNodes) where it's mentioned as `decomissioning`, changing it to `decomissioned` might change it's meaning.

> * hadoop-cluster-overview-dashboard-screenshot.png
> 
> Can you point to a dashboard with active/lost/unhealthy/* nodes > 0 in the Number of node managers over time?

In the visualization `Number of node managers over time` in the screenshot, there is a flat line representing a `single` active node for the Hadoop cluster that we are observing. It indicates that we don't have any `lost`/`unhealthy`/`decommissioned` nodes in our cluster in the given time frame. We already have `active > 0` in the visualization.

@lalit-satapathy, I hope this clarifies your doubts. Let us know if you have any more questions.

**Comment by lalit-satapathy** [comment]
> > * hadoop-data-node-dashboard-screenshot.png
> > 
> > Says “Decommissioning Data Nodes” should it be “Decommissioned Data Nodes”?
> 
> We have followed the naming convention as given [here](https://github.com/elastic/integrations/issues/1543#:~:text=NumDecommissioningDataNodes) where it's mentioned as `decomissioning`, changing it to `decomissioned` might change it's meaning.

Sounds good.
> 
> > * hadoop-cluster-overview-dashboard-screenshot.png
> > 
> > Can you point to a dashboard with active/lost/unhealthy/* nodes > 0 in the Number of node managers over time?
> 
> In the visualization `Number of node managers over time` in the screenshot, there is a flat line representing a `single` active node for the Hadoop cluster that we are observing. It indicates that we don't have any `lost`/`unhealthy`/`decommissioned` nodes in our cluster in the given time frame. We already have `active > 0` in the visualization.
> 

I hope the test has happened the scenarios where there are `lost`/`unhealthy`/`decommissioned` nodes in the cluster ? Just want to make sure, it is covered in the testing and it will be great if we can cover the same in the dashboard?

> @lalit-satapathy, I hope this clarifies your doubts. Let us know if you have any more questions.

**Comment by yug-elastic** [comment]
> > > * hadoop-cluster-overview-dashboard-screenshot.png
> > > 
> > > Can you point to a dashboard with active/lost/unhealthy/* nodes > 0 in the Number of node managers over time?
> > 
> > 
> > In the visualization `Number of node managers over time` in the screenshot, there is a flat line representing a `single` active node for the Hadoop cluster that we are observing. It indicates that we don't have any `lost`/`unhealthy`/`decommissioned` nodes in our cluster in the given time frame. We already have `active > 0` in the visualization.
> 
> I hope the test has happened the scenarios where there are `lost`/`unhealthy`/`decommissioned` nodes in the cluster ? Just want to make sure, it is covered in the testing and it will be great if we can cover the same in the dashboard?

Yes, it has been covered as a part of testing. We have also updated the dashboard screenshot to reflect the same, please check it out.

**Review by lalit-satapathy — APPROVED** [review]

**Pull request merged**
