### PR TITLE
Add multi_fields to postgresql.log.query

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
## What does this PR do?

This PR is to change `postgresql.log.query` to multi fields: keep original `keyword` field type and add `match_only_text` field type as well for indexing log messages and better search experience.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes https://github.com/elastic/integrations/issues/4022

### CODE REVIEW

**Review by sayden — APPROVED** [review]
LGTM

**Comment by kaiyan-sheng** [comment]
Closing this PR for now because this should be solved with enabling event.original field.

**Comment by ishleenk17** [comment]
Is there a different approach we are planning to take here ? @kaiyan-sheng

**Comment by kaiyan-sheng** [comment]
@ishleenk17 Yes, we will add a tag called `preserve_original_event` into the document so ingest pipeline knows to keep the `event.original` field.

**Pull request closed without merging**
