### PR TITLE
[O11y][IIS] Migrate `Application Pool Overview` dashboard visualizations to lens in kibana 8.5.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for IIS integration package

- Statistics for IIS Lens migration:

<html>
<body>

IIS dashboard | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
Application Pool Overview | 0 | 9 | 8 | 1
  | 0 | 9 | 8 | 1

</body>
</html>

Note: 1 markdown panel has not been migrated because we don't have any alternatives in lens for markdown.
1-metricbeat-iis-application-pool-overview

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.5.0 itself.

## Related issues

- Relates #5221

### CODE REVIEW

**Comment by rajvi-elastic** [comment]
> Is it possible to remove the decimal places in the percentage representation of the `CPU Usage` chart ?

@muthu-mps, Yes it is possible. But it won't show you the precise value even when you hover over the chart. 
In the previous TSVB visualization (before migration), when you hover over the chart it shows precise values. Hence we have kept the precision of 2 decimal places. 

Please find the below screenshot of before migration.
image (14)

**Comment by muthu-mps** [comment]
> > Is it possible to remove the decimal places in the percentage representation of the `CPU Usage` chart ?
> 
> @muthu-mps, Yes it is possible. But it won't show you the precise value even when you hover over the chart. In the previous TSVB visualization (before migration), when you hover over the chart it shows precise values. Hence we have kept the precision of 2 decimal places.
> 
> Please find the below screenshot of before migration. image (14)

@rajvi-elastic - Do we really need three decimal places ? As the `CPU Usage` chart in `Webserver Processes` doesn't show decimal places. Is there any difference ?

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic - Do we really need three decimal places ? As the `CPU Usage` chart in `Webserver Processes` doesn't show decimal places. Is there any difference ?

@muthu-mps , Please find below image for before migrated  `CPU Usage` chart. 
image

Both the panels are showing different formatted values. If it is required to show precise percentage value then we can add decimals point otherwise we can remove it. Please let us know whether or not it is required?

**Comment by muthu-mps** [comment]
> > @rajvi-elastic - Do we really need three decimal places ? As the `CPU Usage` chart in `Webserver Processes` doesn't show decimal places. Is there any difference ?
> 
> @muthu-mps , Please find below image for before migrated `CPU Usage` chart. image
> 
> Both the panels are showing different formatted values. If it is required to show precise percentage value then we can add decimals point otherwise we can remove it. Please let us know whether or not it is required?

As the lens shows the values in the Y axis with decimal values. It would be good to have single decimal value.

**Comment by rajvi-elastic** [comment]
> As the lens shows the values in the Y axis with decimal values. It would be good to have single decimal value.

@muthu-mps, Should we also change decimal values in other IIS panels as well? 

For example, in [Website Overview dashboard](https://raw.githubusercontent.com/elastic/integrations/0809a4a2d656958d3f19564795a77dc6bb7dbc30/packages/iis/img/metricbeat-iis-website-overview.png) there are few panels in which 3 decimal points are configured.

**Comment by muthu-mps** [comment]
> > As the lens shows the values in the Y axis with decimal values. It would be good to have single decimal value.
> 
> @muthu-mps, Should we also change decimal values in other IIS panels as well?
> 
> For example, in [Website Overview dashboard](https://raw.githubusercontent.com/elastic/integrations/0809a4a2d656958d3f19564795a77dc6bb7dbc30/packages/iis/img/metricbeat-iis-website-overview.png) there are few panels in which 3 decimal points are configured.

Yes, Please make the change for other dashboards as well.

**Comment by rajvi-elastic** [comment]
> Yes, Please make the change for other dashboards as well.

@muthu-mps, we have updated the decimal points in panels and updated the PRs. Can you please review it?

**Review by milan-elastic — APPROVED** [review]

**Review by muthu-mps — APPROVED** [review]
Looks good!

**Review by muthu-mps — APPROVED** [review]
Looks good!

**Pull request merged**
