### PR TITLE
[O11y][Oracle] Migrate `Sysmetrics` dashboard visualizations to lens in kibana 8.6.0

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

- Migrate visualizations to lens for Oracle integration package

- Statistics for **Oracle** Lens migration:

<html>
<body>
<google-sheets-html-origin>

Oracle Dashboards | Before Migration |   | After Migration |   |
-- | -- | -- | -- | -- |
  | Lens | Visualization | Lens | Visualization
[Metrics Oracle] Sysmetrics | 0 | 15 | 15 | 0

</body>
</html>

## Checklist

- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that panels are populated with data.
- [x] I have verified that panels are not distorted after being migrated to lens.
- [x] I have updated screenshots of dashboard.
- [x] I have verified that data count are matching and panel aggregations are same as before.

## Author's checklist

- [x] Migrated panels should be removed from visualization folder.
- [x] Migrated visualizations are populating in Kibana version `8.6.0`. 

## Related issues

- Relates 
  - #5221 
  - #5753

**Note**: - Previously the sysmetric dashboard divided into two screenshot. We have provided whole dashboard in one screenshot. Hence we have removed entry for second sysmetric dashboard screenshot from manifest.yml file

### CODE REVIEW

**Comment by milan-elastic** [comment]
Thanks, @harnish-elastic! Looks good, Approved!

**Comment by agithomas** [comment]
Please explain the reason for kibana version change.

**Comment by kush-elastic** [comment]
> Please explain the reason for kibana version change.

We have already provided the reason behind why we are migrating to Kibana version `8.6.0` in the [issue](https://github.com/elastic/integrations/issues/5753#:~:text=kibana%20version%20(8.6.0)-,Note,-The%20reason%20behind) itself. The reason behind why we have mentioned there is that the dashboard (`System Statistics`) which lets us use kibana 8.6.0 is different from this PR.

**Review by kush-elastic — APPROVED** [review]

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
