### PR TITLE
[Osquery] Add default saved queries

### PR DESCRIPTION
**Pull request by tomsonpl**
Added default Saved Object (Saved Query) to Osquery Manager integration.

## Screenshots
Zrzut ekranu 2022-04-5 o 14 53 53

### CODE REVIEW

**Review by james-elastic — APPROVED** [review]
If we were to update this with the ECS fields all we'd have to do is put in another PR right?

**Comment by patrykkopycinski** [comment]
@james-elastic I think it would be better to do it in this PR

**Review by patrykkopycinski — CHANGES_REQUESTED** [review]
Let's wait with merging for ECS mapping

**Comment by tomsonpl** [comment]
I think there is no rush - 8.3 is still quite away. Who should we contact to get the mappings? Because the previous list didn't mention them.

**Comment by patrykkopycinski** [comment]
@james-elastic and @melissaburpo

**Comment by jsoriano** [comment]
> @jsoriano it looks like we need to release a new revision of elastic-package with updated package-spec. Do you know if there are any blockers or if we can proceed with a release?

Yes, we have to merge https://github.com/elastic/integrations/pull/3316 or similar first. We will also have to check some other new validations as the ones for the changelog links.

**Comment by mtojek** [comment]
@mergifyio rebase

**Comment by tomsonpl** [comment]
@mtojek yes, I will try rebasing manually. Thank you :)

**Review by patrykkopycinski — APPROVED** [review]
LGTM

**Review by P1llus — APPROVED** [review]

**Comment by tomsonpl** [comment]
@P1llus thank you :)

**Pull request merged**
