### PR TITLE
Schedule daily: test packages against 8.1

### PR DESCRIPTION
**Pull request by mtojek**
This PR modifies `schedule-daily.groovy` to run daily system tests against 8.1-SNAPSHOT.

Motivation:

The `containerd` integration requires [8.1 stack](https://github.com/elastic/integrations/blob/main/packages/containerd/manifest.yml#L12) to be present and it isn't ignored by 8.0 stacks, failing the system test with 404 error. We can refactor [the logic](https://github.com/elastic/integrations/blob/main/.ci/Jenkinsfile#L149) to skip packages targeting 8.1 or we can use a newer snapshot.

I'm not in favor of adding an extra column to the testing matrix (now: 7.16 and 8.0), as this job is sequential and developers do not pay much attention to its status.

Let me know what you think.

### CODE REVIEW

**Comment by mtojek** [comment]
I'm also wondering if we should bump 7.16 to 7.17 to catch any issues earlier.

**Comment by jsoriano** [comment]
> I'm not in favor of adding an additional column to the testing matrix (now: 7.16 and 8.0), as this job is sequential and developers do not pay much attention to its status.

> I'm also wondering if we should bump 7.16 to 7.17 to catch any issues earlier.

Yep, the purpose of these jobs was to test with the latest versions of these majors, so +1 to let it only with 7.17 and 8.1.

**Comment by mtojek** [comment]
Thanks, I bumped the other job to 7.17.

**Review by jsoriano — APPROVED** [review]
Thanks for updating this!

**Comment by mtojek** [comment]
Errors are unrelated to this change. Merging.

**Comment by jsoriano** [comment]
Maybe we can implement something similar to [`findOldestSupportedVersion`](https://github.com/elastic/apm-pipeline-library/blob/861c9ed3aa3ca692cbced11f6457cf38f1f9659c/vars/findOldestSupportedVersion.groovy), but to find the newest minor, so we don't need to update these files every time a new minor is released.

**Comment by mtojek** [comment]
That's a fair point. We could make it useful also in the `isPrAffected` function.

**Comment by jsoriano** [comment]
Issue created for this: https://github.com/elastic/integrations/issues/2604

**Pull request merged**
