### PR TITLE
[Citrix ADC] Update code-owner for logs and metrics data stream

### PR DESCRIPTION
**Pull request by muthu-mps**
Update code owner for Citrix ADC logs and metrics data streams.

### CODE REVIEW

**Review by qcorporation — APPROVED** [review]
LGTM

**Review by mjwolf — DISMISSED** [review]

**Review by qcorporation — COMMENTED** [review]
@muthu-mps Please hold up on this merge until we talk offline

**Comment by muthu-mps** [comment]
Based on the comments from @taylor-swanson, updating the ownership of logs data stream with security-service-integrations team.

**Review by ishleenk17 — APPROVED** [review]
Looks good!.
@lalit-satapathy : Please check

**Comment by narph** [comment]
> Based on the comments from @taylor-swanson, updating the ownership of logs data stream with security-service-integrations team.



Please reach out to the respective team if ownership changes are involved and provide clarification on why @elastic/security-service-integrations should be involved here

**Comment by andrewkroh** [comment]
> but that would mean you need a review from us for any change to the integration.

@taylor-swanson Are you sure? When reviews from code owners are required, an approval from *any* of the owners is sufficient to meet this requirement[^1]. So a joint owner should be able to modify their data stream and the changelog+manifest and be able to merge.

[^1]: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-and-branch-protection

**Pull request merged**
