### PR TITLE
Add support for custom processors

### PR DESCRIPTION
**Pull request by rsdrakh**
## Checklist

- [x ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ x] I have verified that all data streams collect metrics or logs.
- [x ] I have added an entry to my package's `changelog.yml` file.
- [x ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by rsdrakh** [comment]
Do I need to resubmit after signing the CLA?

**Comment by gsantoro** [comment]
@rsdrakh you might want to fix the conflicts and commit them. If you have signed the CLA before that, it should clear the error check

**Comment by gizas** [comment]
@rsdrakh Can you give us some more details for the user scenarios that you want to use the processors?

Reason I am asking is that in collector scenarios we have filters (to include/ exclude metrics), in remote write (the  write_relabel_configs see doc [here](https://docs.elastic.co/integrations/prometheus#prometheus-server-remote-write)) can offload the extra processing on prometheus server side and promql also includes the import/export mentality in its queries. So I am a little sceptical that if we allow this functionality here we might expose agent to extra processing and finally to bigger memory/ cpu consumption

**Comment by rsdrakh** [comment]
Hi, 

from the customers side, they need to add labels to each document produced by an elastic agent, that contains the application that the server being polled belongs to.

Nothing specific for prometheus, I still need to open PRs for Oracle IOntegration, mysql integration, basically every single one they use that has no processors available.

After I signed the CLA and did another commit, it still says I did not sign the CLA, though...

Cheers!

**Comment by gizas** [comment]
Thank you for clarifications @rsdrakh . Makes sense.

For the CLA, I have checked with an internal tool that we have and still your PR is not verified. I think that the 2 commits are the problem:
- https://github.com/elastic/integrations/commit/e3bb0fe42b379abf7dbb5423c82657366703f032,
- https://github.com/elastic/integrations/commit/e2aa0ccfeaf254257bb3869a4a73ffd2e9685a21

Can you squash them and leave only last one ?

**Review by gizas — APPROVED** [review]

**Review by gizas — APPROVED** [review]

**Comment by gizas** [comment]
Yes this was done in previous PR!

(@P1llus  fyi https://github.com/elastic/integrations/issues/5285)

**Comment by rsdrakh** [comment]
Sorry guys, I will close this one and recreate it, because that is somehow effed up here. :-) See you in the next one

**Pull request closed without merging**
