### PR TITLE
Update Prometheus package to leverage types in remote write

### PR DESCRIPTION
**Pull request by ChrsMark**
## What does this PR do?
Updates Prometheus package to leverage types in remote write.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [x] I have verified that all datasets collect metrics or logs.

## Related issues

- Relates elastic/beats#19944, elastic/beats#17675

## Screenshots
Screenshot 2020-08-11 at 15 12 03

### CODE REVIEW

**Comment by ChrsMark** [comment]
Wondering about versioning on this https://github.com/elastic/integrations/pull/243/files#diff-7fc71a4e1d864fb27e0913069d72da8dR4. Should it be a patch upgrade or a minor number update since it introduces new functionality?

**Comment by ChrsMark** [comment]
cc: @exekias

**Comment by mtojek** [comment]
@ChrsMark I think you need to rebase this PR against the master branch.

**Review by exekias — APPROVED** [review]

**Comment by ChrsMark** [comment]
@mtojek the feature is implemented in Beats in `7.10` version. In this, is it ok to merge this package update now, or shall we wait? What is the process in such cases?

**Comment by mtojek** [comment]
I assume that the package-storage distribution for 7.9 has been freezed and we're safe to commit changes for 7.10. @ruflin, right?

**Comment by ruflin** [comment]
The 7.9 branch has not been created yet. But that should not hold back this PR. If the package is only compatible with 7.10, please ensure it contains the correct conditions.

**Comment by ChrsMark** [comment]
@exekias could you please have a final look on this since I applied some changes 🙂  ?

**Review by exekias — APPROVED** [review]

**Pull request merged**
