### PR TITLE
Fix adding processors in cloudfront logs

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
## What does this PR do?

This PR is to fix adding processors for `cloudfront` logs in AWS package. With the change, we can see `processors` in agent policy is in the right format now:
```
inputs:
  - id: aws-s3-cloudfront-096288f1-4c9d-4f1b-a6b1-7e73ecc7a849
    name: aws-1
    revision: 1
    type: aws-s3
    use_output: default
    meta:
      package:
        name: aws
        version: 1.24.3
    data_stream:
      namespace: default
    streams:
      - id: aws-s3-aws.cloudfront_logs-096288f1-4c9d-4f1b-a6b1-7e73ecc7a849
        data_stream:
          dataset: aws.cloudfront_logs
          type: logs
        queue_url: 'https://sqs.us-east-1.amazonaws.com/123/test'
        max_number_of_messages: 5
        access_key_id: a
        secret_access_key: b
        session_token: c
        tags:
          - forwarded
          - aws-cloudfront
        publisher_pipeline.disable_host: true
        processors:
          - drop_event:
              when:
                regexp:
                  message: ^#.*
          - drop_event:
              when:
                not:
                  regexp:
                    message: .*text/html.*
```

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes https://github.com/elastic/integrations/issues/4394

### CODE REVIEW

**Review by tommyers-elastic — APPROVED** [review]
thanks!

it's not ideal that indentation errors can affect behavior so severely! i guess the same is true of this type of YAML config in general. 😬

**Comment by kaiyan-sheng** [comment]
@tommyers-elastic I think the main issue is missing `-` in front of `{{processors}}` :) Thanks for the review!!

**Comment by elasticsatch** [comment]
Thanks for the fix. So this change requires input NOT to have dash in front of each processor? Could you show me some examples (or maybe a test case?)

**Comment by kaiyan-sheng** [comment]
@elasticsatch You mean requires/or not to have a dash in front of each processor on the kibana UI?

**Comment by elasticsatch** [comment]
Oh thanks, I overlooked the screenshot. So if I want multiple processors we should put something like this, right?

```
dissect:
  ...

drop_event:
  ..
```

And we can put blank lines in between, correct?

**Comment by kaiyan-sheng** [comment]
@elasticsatch OMG good call...... Nope right now it only support adding one processor! I will look into it tomorrow and fix it for multiple processors. Thanks!

**Comment by elasticsatch** [comment]
Good to hear and no pressure. Please take your time. 

I also suggest to put the instruction somewhere in a document so users can see how to write the processors correctly. There is no good ones as of this moment so it took a little bit of time to figure it out on my own.

**Pull request merged**
