### PR TITLE
Mimecast | Changing dashboards, adding logo, renaming integration and release

### PR DESCRIPTION
**Pull request by djordje-adzemovic-devtech**
## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by djordje-adzemovic-devtech** [comment]
Here is the integration logo:
mimecast
Dashboards:
Screenshot_3
Screenshot_4
Screenshot_5
Screenshot_6
Screenshot_7
Screenshot_8
Screenshot_9
Screenshot_10
Screenshot_11
Screenshot_12
Screenshot_13
Screenshot_14
Screenshot_15
Screenshot_16
Screenshot_17
Screenshot_18
Screenshot_19
Screenshot_20
Screenshot_21
Screenshot_22
Screenshot_23
Screenshot_24
Screenshot_25
Screenshot_26
Screenshot_27
Screenshot_28
Screenshot_29
Screenshot_30
Screenshot_31
Screenshot_32

**Review by marc-gr — APPROVED** [review]

**Pull request merged**
