### PR TITLE
Enhance AWS S3 integration dashboard

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
## What does this PR do?

This PR is to improve AWS S3 overview dashboard. Some metrics are added to be collected in order to show in the visualizations as well.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Screenshots

Screen Shot 2022-11-16 at 4 01 13 PM

### CODE REVIEW

**Comment by ravikesarwani** [comment]
Wow! this is great. Exceptional work and thank you for helping it drive forward.

Just a few minor comments:
What is this graph showing? Is it # of objects? Would be good to make it clear and add the appropriate text.
Screen Shot 2022-11-16 at 5 09 12 PM


On the Downloads and uploads row, what does the “download bytes **per request**” really mean?

**Comment by kaiyan-sheng** [comment]
> Just a few minor comments: What is this graph showing? Is it # of objects? Would be good to make it clear and add the appropriate text. Screen Shot 2022-11-16 at 5 09 12 PM

Ah good catch! I missed the title there! Will add it. This visualization is for number of objects per bucket.

> On the Downloads and uploads row, what does the “download bytes **per request**” really mean?

So this one is to show the `BytesDownloaded` metric from S3. `BytesDownloaded` metric shows the number of bytes downloaded for requests made to an Amazon S3 bucket, where the response includes a body. With the `average` statistic method, this metric represents the average number of bytes downloaded per request.

**Comment by kaiyan-sheng** [comment]
CI failure should be fixed by https://github.com/elastic/integrations/pull/4657

**Review by andrewctate — COMMENTED** [review]
Looking great!

I noticed a couple of things that might point to overuse of horizontal space:

1. On my screen (still quite large), the row labels get clipped
Screen Shot 2022-11-17 at 9 46 58 AM

2. I see that we are putting the legends inside the charts, which overlaps with the data. 
Screen Shot 2022-11-17 at 9 48 12 AM

I am wondering if it would make sense to limit the rows to max two visualizations each. This would allow you more space to place the legends outside the charts and increase the width of the row labels

In this spirit

- the "Average 4xx errors" and "Average 5xx errors" visualizations could be replaced with one stacked bar chart.
- do we need separate visualizations for the GET and PUT requests? After all, the user can always add a dashboard filter if they only want to see one request type

These would result in more horizontal space and actually better dashboard performance when the data gets large. WDYT?

**Comment by kaiyan-sheng** [comment]
> Looking great!
> 
> I noticed a couple of things that might point to overuse of horizontal space:
> 
> 1. On my screen (still quite large), the row labels get clipped

Fixed! I changed it to font size 12 and they all should be visible in smaller screens now.

> 2. I see that we are putting the legends inside the charts, which overlaps with the data.
> I am wondering if it would make sense to limit the rows to max two visualizations each. This would allow you more space to place the legends outside the charts and increase the width of the row labels

I adjusted the visualizations to only have 2 in one row instead of 3. This way we have more space to show the legends and data points. Thanks for the suggestion!

> In this spirit
> 
> * the "Average 4xx errors" and "Average 5xx errors" visualizations could be replaced with one stacked bar chart.
> * do we need separate visualizations for the GET and PUT requests? After all, the user can always add a dashboard filter if they only want to see one request type
> 
> These would result in more horizontal space and actually better dashboard performance when the data gets large. WDYT?

I'd like to still keep the 4xx and 5xx separate in two visualizations, same with GET and PUT just because they are basic metrics to show for S3 requests and depends on the specific bucket or use case, user might want to see these charts separately 🤔

**Comment by kaiyan-sheng** [comment]
Note: I'm keeping the screenshot as it is (instead of showing 2 visualizations per row) so all the visualizations can fit in one page of screenshot 😂

**Review by girodav — APPROVED** [review]
LGTM! Great work :)

**Pull request merged**
