### PR TITLE
[Citrix ADC] Fix native syslog parsing failures

### LINKED ISSUE #10153: [Citrix ADC] Syslog messages are not according to documentation
As @eriroley mentioned in #9592 , the Citrix ADC messages received over syslog are missing the fields

* syslog timestamp
* level 
* client ip

even though the [documentation of citrix adc ](https://docs.netscaler.com/en-us/citrix-adc/current-release/application-firewall/logs.html) clearly states, that the logs are to be expected in this format. Therefore the grok pattern fails. We double checked all the settings, but the log message format is not configurable for adc logs. 

As of our understanding, the logfile format with the timestamp, level and client ip is only valid for logs saved to the `/var/log` folder.

https://github.com/elastic/integrations/blob/7cdf5800aed7b680040eaba311f997d54407726b/packages/citrix_adc/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L26-L37

Here are some example messages:

```
<134> 06/14/2024:18:29:23 GMT host1 0-PPE-1 : default REWRITE Message 209051714 0 :  "Source: 1.1.1.1 Destination: 192.168.0.1 Request URL: site.example.com/webcam/1.jpg HTTP Status: 200"
<134> 06/14/2024:16:02:01 GMT host1 0-PPE-0 : default TCP CONN_TERMINATE 225601598 0 :  Source 192.168.0.1:443 - Destination 192.168.0.2:15567 - Start Time 06/14/2024:16:02:01 GMT - End Time 06/14/2024:16:02:01 GMT - Total_bytes_send 0 - Total_bytes_recv 1
<134> 06/14/2024:16:01:40 GMT host1 0-PPE-0 : default TCP CONN_DELINK 220659229 0 :  Source 1.1.1.1:48277 - Vserver 10.0.0.1:443 - NatIP 192.168.0.1:12248 - Destination 192.168.0.100:443 - Delink Time 06/14/2024:16:01:40 GMT - Total_bytes_send 0 - Total_bytes_recv 619
<135> 06/14/2024:16:01:39 GMT host1 0-PPE-0 : default SSLLOG SSL_HANDSHAKE_SUCCESS 220659228 0 :  SPCBId 27719517 - ClientIP 1.1.1.1 - ClientPort 38797 - VserverServiceIP 192.168.0.1 - VserverServicePort 443 - ClientVersion TLSv1.2 - CipherSuite "TLS1.2-ECDHE-RSA-AES256-GCM-SHA384" - Session New  - HandshakeTime 120 ms
```

### PR DESCRIPTION
**Pull request by jvalente-salemstate**
This PR introduces the following changes to improve parsing of Citrix Native syslog format

* Grok Patterns capturing usernames have been updated to capture usernames entered as an email address.
* Avoids duplication of `client.ip`
* SSLVPN events generated through Citrix Storefront are captured with with the associated `icauuid`
* Grok and Date processors for `start_time` and `end_time` correctly handle any presence of a trailing space and/or timezone
* Adjust patterns to account for blank values resulting in a double space (e.g. no timezone), or a trailing space. 
* Parsing of `MONITORUP` and `MONITORDOWN` events.
* Corrected cases where Login Failure and HTTPREQUEST events were not capturing application or browsers due to spacing. 

## Proposed commit message

Fix native syslog parsing failures

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [x] Identify additional failures in pattern matches 
- [x] Add sample "native syslog" logs for tests

## Related issues

- Closes #10153

### CODE REVIEW

**Comment by jvalente-salemstate** [comment]
I’ve submitted this as a draft since there are additional failures to be captured. 

I’m also unsure if this PR would be appropriate for fixing dashboards or if that should be in a separate one specific to those changes. There’s panels in there that are counting the number of documents containing a field for bytes tx/rx rather than doing a sum on the field.  I can fix that in this PR if acceptable.

**Comment by jvalente-salemstate** [comment]
I think I’ve captured all failures in the existing samples, the ones in the related issue, and sampling from events we’ve got in our environment. 

For the dashboard, I can either add it to this PR or open a new one later for the dashboard and mapping some of the ECS security fields that aren’t present.

**Comment by jvalente-salemstate** [comment]
@andrewkroh should I close this and open a new PR ? There's been a few other PRs merged or pending relating to time zones so I'd need to fix any merge conflicts.

**Comment by andrewkroh** [comment]
> should I close this and open a new PR ? There's been a few other PRs merged or pending relating to time zones so I'd need to fix any merge conflicts.

fwiw: I'm not part of the team that owns this particular code, but my personal recommendation would be to submit a few small PRs. The description of the PR sounds like those changes could be made in distinct PRs. The smaller focused PRs will probably be easier to review.

**Pull request closed without merging**
