### PR TITLE
Refactor cisco_ise integration

### PR DESCRIPTION
**Pull request by Bernhard-Fluehmann**
Changes:
- No kv parsing to root level anymore (user log_details_object flattened field instead
- More sophisticated parsing of av-pairs
- Enhanced error handling
- Bug-fixes

## What does this PR do?
This is a major rework of the cisco_ise integration. The main reason was that the corrent implementation contains lots of errors, resulting in non-ecs compliant fields which are not removed in all conditions after parsing. The new approach is to do the kv parsing in a specific field (cisco_ise.log.log_details_object) of type flattened and rename, convert, etc. from there. Thus, non standard fields can be completely avoided. As a side effect, additional, unknown fields which are not renamed are still visible in the flattened field, without the risk of field exhaustion. 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by Bernhard-Fluehmann** [comment]
Please check what's wrong with my CLA

**Comment by efd6** [comment]
@Bernhard-Fluehmann Can you check that the email address that you are using in the commit matches your CLA-registered email addresses (I can see two, one which looks correct and the other which looks like a typo variant).

**Comment by Bernhard-Fluehmann** [comment]
@efd6 The confusion may come from a company renaming from RealStuff to Securix. What company name do you see in the CLA? BTW, I have switched the main email address of my contact to the realstuff one and confirmed that it still works.

**Comment by efd6** [comment]
The emails that are registered are for the user @realstuff.ch.

**Comment by Bernhard-Fluehmann** [comment]
@efd6 bernhard.fluehmann@realstuff.ch is the main address of my account again. Problem solved. PM me if not.

**Comment by efd6** [comment]
Yes, that is the email that is noted as having signed the CLA. The commits in this PR will need to be rewritten so that the author matches that. Alternatively you could resign with the new email address; the CLA checker looks at the email addresses of the commits rather than the email address of the user that sent the change (which I'm not sure it can know).

**Comment by Bernhard-Fluehmann** [comment]
I'll open a new one

**Pull request closed without merging**
