### PR TITLE
[OSQuery] Add root fields to get proper mappings

### LINKED ISSUE #5134: [OSQuery] file.elf.sections does not conform to ECS
I found a field conflict in our data and it seems that file.elf.sections is set as an `object `type instead of a `nested `type as ECS shows here: https://www.elastic.co/guide/en/ecs/current/ecs-elf.html#field-elf-sections

Looking at the ecs fields, it doesn't denote the file.elf.sections as nested but I am not sure if it needs to or not since I don't know where this needs to be implemented.

https://github.com/elastic/integrations/blob/main/packages/osquery_manager/data_stream/result/fields/ecs.yml#L105-L114

Does file.elf.sections need to be an `object` type or must it be updated to the `nested` type to conform with ECS and not give me conflict issues with my other data. Please advise!

### PR DESCRIPTION
**Pull request by nicpenning**
## Type
- Bug

## What does this PR do?
Adds appropriate ECS fields for mappings to prevent field conflicts and better align to ECS.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #5134

### CODE REVIEW

**Comment by nicpenning** [comment]
@jamiehynds  Can someone please review this?

**Comment by jamiehynds** [comment]
@caitlinbetz could someone from your team review please, as it related to OSQuery Manager? Thanks!

**Review by tomsonpl — APPROVED** [review]
LGTM, sorry for the delay with review

**Review by aleksmaus — APPROVED** [review]
Thank you!

**Comment by nicpenning** [comment]
Corrected typo in change docs. Should be good to go now.  Anything else we are waiting on?

**Comment by nicpenning** [comment]
Please get this merged as it is still an issue. Is there anything needed from me?

**Comment by patrykkopycinski** [comment]
Hey @nicpenning, Sorry to hear that, we're working on the solution to get it merged and make it available to `<8.7.0` stack version, because in this PR we have added constrain for `8.7.0` version https://github.com/elastic/integrations/pull/5175/files#diff-1a77d5360c51dd72560ba5a0b18395ea8f133948182feb61eeb82bab2e709d97R14

**Comment by nicpenning** [comment]
Okay, excellent! I was just making sure you were not waiting on me :)

**Comment by nicpenning** [comment]
This should still be relevant, but I will patiently await the 8.7.0 release.

**Pull request merged**
