### PR TITLE
[O11y][K8s] Migrate `Cronjobs` dashboard visualizations to lens

### PR DESCRIPTION
**Pull request by rajvi-elastic**
### Urgency
- High

### Activity Type
- Enhancement

## What does this PR do?
- Manually migrate `K8s CronJobs` visualizations to the lens in the current Kibana version `8.10.2` itself. 

- Statistics for `K8s CronJobs` Lens migration:
## Migration stats
  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Vizualization | Lens | Vizualization
[Metrics Kubernetes] Cronjobs | 1 | 1 | 2 | 0

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to the lens.
- [x] I have updated screenshots of the dashboard.
- [X] I have verified that the data counts are matching and panel aggregations are the same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.10.2 itself.

## Related issues

- Relates #7774

Before Migration:
image
After Migration:
kubernetes-state_cronjob-dashboard

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Comment by drewdaemon** [comment]
Thanks for doing this. Could we decrease the height of the metric panel by about half? That way the numbers will be much closer to the labels. Here is an example from System integration

**Comment by rajvi-elastic** [comment]
> Thanks for doing this. Could we decrease the height of the metric panel by about half? That way the number will be much closer to the label.

Hi Drew, according to your comment I have raised a separate [issue](https://github.com/elastic/integrations/issues/8308) for tracking the changes related to size of metric visualizations. As already 3 dashboard PRs are merged for Kubernetes, they also require this change.

**Comment by drewdaemon** [comment]
Thanks @rajvi-elastic !

**Review by constanca-m — APPROVED** [review]

**Pull request merged**
