### PR TITLE
Migrate "[Logs Azure] Cloud Overview" dashboard to  Lens 

### PR DESCRIPTION
**Pull request by tdancheva**
## What does this PR do?

This PR migrates the  "[Logs Azure] Cloud Overview" dashboard to  Lens, changes the style of the metrics, and makes changes to the filters in accordance with the new dashboard design guidelines. 

Fixed the alerts and service health visualizations that were not getting populated due to the event_category field not showing the proper category, instead the category field is populated. See this [PR](https://github.com/elastic/integrations/pull/6504) for more info. 

NOTE: The after screenshot is taken with stack version 8.6.2. Panel titles of Lens Metrics type do not show in version 8.6.x, from 8.7.0 they show correctly. I will bump up the minimum Kibana version in the whole package in a separate [PR](https://github.com/elastic/integrations/pull/6515) that I will link here as well. 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

## Screenshots

Before:

ClOUD_OVERVIEW_BEFORE_3

After:
AFTER

After fixing N/A:

Screenshot 2023-06-08 at 10 21 16

### CODE REVIEW

**Comment by drewdaemon** [comment]
Thanks for doing this! A couple initial recommendations:

I see that we are currently using dynamic coloring with the "status" palette for the activity stats and top users:

Screenshot 2023-06-08 at 4 34 38 PM

I'm not sure this coloring is a good fit since these are valence-free numbers (it isn't necessarily a bad or a good thing to have a higher or lower resource count, for example). 

- [ ] For the activity stats, I would recommend changing the background color of those metrics to a static white.

- [ ] For the top users, I would recommend we use a horizontal bar chart as we do with the "top resource groups." We could also wait for the release of Kibana 8.9 when Tag cloud will be available in Lens.

Let me know if this makes sense

**Comment by drewdaemon** [comment]
@tdancheva 

Thanks for making those changes.

> I also changed resource groups to Pie plot since it seems more readable to me that way, but let me know If you think otherwise.

I'll start by asking you: which of the following would be most helpful to the user?

1. Seeing how the set of all their resource groups breaks down into subcategories
2. Seeing the top N most-used resource types

These are related but different.

If 1., then I think a partition chart such as a donut makes sense, but I would advise you to increase the number of terms to a large-enough number to be relatively sure that _all_ the group types will be shown (100 or so?). Otherwise, the partition chart will imply that all the group types are shown but they won't be. (Side-note: you might try a treemap chart here for better use of the space).

I would also rename the panel to something like "Resource group breakdown," or simply "Resource groups" since it should no longer be just the top ones.

If 2., I think the original bar chart is a better fit and we could look into why you didn't find it readable.

**Comment by drewdaemon** [comment]
Ah, one other point

Can we switch the color palettes for the visualizations to the system default?

Old palette:
Screenshot 2023-03-30 at 4 37 09 PM

Default palette
Screenshot 2023-03-30 at 4 37 24 PM

**Comment by tdancheva** [comment]
> @tdancheva
> 
> Thanks for making those changes.
> 
> > I also changed resource groups to Pie plot since it seems more readable to me that way, but let me know If you think otherwise.
> 
> I'll start by asking you: which of the following would be most helpful to the user?
> 
> 1. Seeing how the set of all their resource groups breaks down into subcategories
> 2. Seeing the top N most-used resource types
> 
> These are related but different.
> 
> If 1., then I think a partition chart such as a donut makes sense, but I would advise you to increase the number of terms to a large-enough number to be relatively sure that _all_ the group types will be shown (100 or so?). Otherwise, the partition chart will imply that all the group types are shown but they won't be. (Side-note: you might try a treemap chart here for better use of the space).
> 
> I would also rename the panel to something like "Resource group breakdown," or simply "Resource groups" since it should no longer be just the top ones.
> 
> If 2., I think something like the original bar chart is a better fit and we could look into why you didn't find it readable.

Thank you so much for the insight. You are right, it is case 2) I believe. I changed it back and I also addressed your other comment about the color palette, and changed them to default.

**Review by drewdaemon — APPROVED** [review]
Great work!

**Review by zmoog — APPROVED** [review]

**Pull request merged**
