### PR TITLE
Security detection engine.fix changelog

### PR DESCRIPTION
**Pull request by djptek**
## What does this PR do?

The changelog for the `security_detection_engine` integration had a distinct format to the sibling integrations. This PR aligns the format with the other integrations. I have NOT updated the changelog by choice.

## Checklist

- [X ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
~- [ ] I have verified that all data streams collect metrics or logs.~
~- [ ] I have added an entry to my package's `changelog.yml` file.~
~- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).~

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by djptek** [comment]
By the way, why this matters: I was checking [another PR](https://github.com/elastic/integrations/pull/4227#pullrequestreview-1111865602) and did some scripting to validate that changes to `changelog.yml` matched changes to `manifest.yml`. This exposed the inconsistency

**Comment by terrancedejesus** [comment]
@djptek - Hello. TRADE has a custom [CLI command](https://github.com/elastic/detection-rules/blob/9861958833f90243309ea3189432b26452e27e27/detection_rules/devtools.py#L443) that adds the updates to our local integrations repo and then creates the PR. This command automatically adjusts the changelog.yml file, so we will need to adjust this on our side. I will open a PR to adjust this.

Reviewing your changes, I noticed that `8.3.2` was removed, is there any particular reason why or questions I can clear up as well?

**Comment by djptek** [comment]
Hi @terrancedejesus I think `8.3.2` may have happened after I started the PR, this was not removed intentionally. The one which I had doubts about was `version 0.13.1` since this appeared twice, see [first commit]( https://github.com/elastic/integrations/pull/4231/commits/e0a9132a0d0c66d5fecfe163ff81dbc543fe5b64)

**Comment by djptek** [comment]
Re the other questions:

>>- Are there any implications upstream from these changes, such as package-storage formatting with manifests?
>>- Outside of adjusting the changelog.yml file here, does anything else need adjusted that references this file?

Not sure, but my changes are failing CI so I suspect something may be amiss

**Comment by terrancedejesus** [comment]
> Hi @terrancedejesus I think 8.3.2 may have happened after I started the PR, this was not removed intentionally. The one which I had doubts about was version 0.13.1 since this appeared twice, see [first commit](https://github.com/elastic/integrations/pull/4231/commits/e0a9132a0d0c66d5fecfe163ff81dbc543fe5b64)

I see what you are describing, however I am not sure if this was intentional or not. I would keep it as is, but adjust the formatting of course based on the original issue explained in this PR.

**Comment by terrancedejesus** [comment]
> Not sure, but my changes are failing CI (silently) so I suspect something may be amiss
If this PR is noise then I'm fine to close

Checking the Jenkins job, all checks are passing, so I am surprised to see it failed as well, potentially because the changelog file is not recognized as a change during the tests? If this is the case, the next release we do (`v8.4.1`) I can adjust this file and see if it will pass.

**Comment by terrancedejesus** [comment]
I will look to get this [fixed](https://github.com/elastic/detection-rules/issues/2351) by the next release cycle on the TRADE side regarding the output of the changelog entries.

**Comment by djptek** [comment]
Thanks @terrancedejesus

**Review by szeitlin — APPROVED** [review]

**Pull request closed without merging**
