### PR TITLE
[O11y][Hadoop] Fix system tests

### PR DESCRIPTION
**Pull request by aliabbas-elastic**
## Proposed commit message
- Fixes system tests for Hadoop package
- There we some updates in the CentOS 7 mirrors which are now changed to `http://vault.centos.org` and this change we need to do manually as the docker image of hadoop comes with older mirrors. Prior to this fix the tests were failing due to the yum repo not able to identify the expired mirrors.

```
#10 24.23 http://mirror.ash.fastserv.com/centos/7.6.1810/os/x86_64/Packages/tcp_wrappers-libs-7.6-77.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
#10 24.23 Trying other mirror.
#10 24.31 http://mirror.ash.fastserv.com/centos/7.6.1810/os/x86_64/Packages/fipscheck-1.4.1-6.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
#10 24.31 Trying other mirror.
#10 24.38 http://mirrors.advancedhosters.com/centos/7.6.1810/os/x86_64/Packages/fipscheck-lib-1.4.1-6.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
#10 24.38 Trying other mirror.
#10 24.39 http://mirror.ash.fastserv.com/centos/7.6.1810/os/x86_64/Packages/libedit-3.0-12.20121213cvs.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
#10 24.39 Trying other mirror.
#10 24.46 http://mirrors.advancedhosters.com/centos/7.6.1810/os/x86_64/Packages/openssh-7.4p1-16.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
#10 24.46 Trying other mirror.
#10 24.47 http://mirror.ash.fastserv.com/centos/7.6.1810/os/x86_64/Packages/openssh-clients-7.4p1-16.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
#10 24.47 Trying other mirror.
#10 24.55 http://mirrors.advancedhosters.com/centos/7.6.1810/os/x86_64/Packages/tcp_wrappers-libs-7.6-77.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
#10 24.55 Trying other mirror.
#10 24.56 http://mirror.ash.fastserv.com/centos/7.6.1810/os/x86_64/Packages/openssh-server-7.4p1-16.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
#10 24.56 Trying other mirror.
#10 24.60 http://mirror.cogentco.com/pub/linux/centos/7.6.1810/os/x86_64/Packages/fipscheck-lib-1.4.1-6.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
#10 24.60 Trying other mirror.
#10 24.62 http://mirror.vcu.edu/pub/gnu_linux/centos/7.6.1810/os/x86_64/Packages/libedit-3.0-12.20121213cvs.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
#10 24.62 Trying other mirror.
```

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

- elastic-package test system -v

## Related issues

- Relates #10407 

## Screenshots

```
--- Test results for package: hadoop - START ---
╭─────────┬──────────────┬───────────┬───────────────────────────────────┬────────┬───────────────╮
│ PACKAGE │ DATA STREAM  │ TEST TYPE │ TEST NAME                         │ RESULT │  TIME ELAPSED │
├─────────┼──────────────┼───────────┼───────────────────────────────────┼────────┼───────────────┤
│ hadoop  │ application  │ system    │ application-metrics (variant: v3) │ PASS   │ 49.426520965s │
│ hadoop  │ cluster      │ system    │ cluster-metrics (variant: v3)     │ PASS   │ 48.524036589s │
│ hadoop  │ datanode     │ system    │ datanode (variant: v3)            │ PASS   │ 48.477215753s │
│ hadoop  │ namenode     │ system    │ namenode (variant: v3)            │ PASS   │ 47.485092041s │
│ hadoop  │ node_manager │ system    │ nodemanager (variant: v3)         │ PASS   │  47.49537262s │
╰─────────┴──────────────┴───────────┴───────────────────────────────────┴────────┴───────────────╯
--- Test results for package: hadoop - END   ---
Done
```

### CODE REVIEW

**Review by harnish-elastic — APPROVED** [review]
LGTM!

**Comment by ishleenk17** [comment]
Why did the older Hadoop image start giving errors?
The requirement for new Centos mirror came through running system test on which environment?

**Comment by aliabbas-elastic** [comment]
> Why did the older Hadoop image start giving errors?
The requirement for new Centos mirror came through running system test on which environment?

@ishleenk17 I would say nothing wrong with the image but the error is here in the [Dockerfile](https://github.com/elastic/integrations/blob/main/packages/hadoop/_dev/deploy/docker/Dockerfile#L8)

```
RUN sudo yum install openssh-server openssh-clients -y;\
```

This command started getting failed due to the 404 [error](https://github.com/elastic/integrations/pull/10422#:~:text=There%20we%20some%20updates%20in%20the%20CentOS%207%20mirrors%20which%20are%20now%20changed%20to%20http%3A//vault.centos.org%20and%20this%20change%20we%20need%20to%20do%20manually%20as%20the%20docker%20image%20of%20hadoop%20comes%20with%20older%20mirrors.%20Prior%20to%20this%20fix%20the%20tests%20were%20failing%20due%20to%20the%20yum%20repo%20not%20able%20to%20identify%20the%20expired%20mirrors.) in mirrors. 

Instead I have used a different mirror for the packages to be installed. As the current Hadoop image uses CentOS distribution, using the new mirror works on it instead.

**Review by ishleenk17 — APPROVED** [review]

**Pull request merged**
