### PR TITLE
[aws][cloudwatch_metrics] Fix the issue with the fingerprint field

### PR DESCRIPTION
**Pull request by tetianakravchenko**
## Proposed commit message

- WHAT: Dimension field shouldn't be a subfield of the flattened field `aws.dimensions`
- WHY:  currently the mapping does not include `aws.dimensions.fingerprint` field that is defined as a dimension, so after the tsdb enablement some documents are dropped.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## Related issues

- 

## Screenshots
mapping does not include fingerprint field:
Screenshot 2023-12-12 at 18 46 15
data:
Screenshot 2023-12-12 at 18 30 35

### CODE REVIEW

**Review by gizas — APPROVED** [review]

**Comment by tetianakravchenko** [comment]
Hey @elastic/security-external-integrations I am getting this error:
```
Error: error running package system tests: could not complete test run: could not find hits in logs-aws.guardduty-ep data stream
```
that is not related to the change I made, could you please have a look this this?

**Comment by kcreddy** [comment]
The problem is coming from the expired certificate in guardduty datastream's system test configuration. Created https://github.com/elastic/integrations/pull/8736 for adding new cert.

**Review by zmoog — APPROVED** [review]
LGTM

**Pull request merged**
