### PR TITLE
[O11y][Apache] Migrate `Access and error logs` dashboard visualizations to lens in kibana 8.3.0

### PR DESCRIPTION
**Pull request by harnish-crest-data**
- Enhancement

## What does this PR do?

- Migrate visualizations to lens for Apache integration package

- Statistics for **Apache** Lens migration:

<html>
<body>
<google-sheets-html-origin>

Apache Dashboards | Before Migration |   |   | After Migration |   |  
-- | -- | -- | -- | -- | -- | --
  | Maps | Lens | Visualization | Maps | Lens | Visualization
[Logs Apache] Access and error logs | 1 | 0 | 6 | 1 | 6 | 0

</body>
</html>

## Checklist

- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that panels are populated with data.
- [x] I have verified that panels are not distorted after being migrated to lens.
- [x] I have updated screenshots of dashboard.
- [x] I have verified that data count are matching and panel aggregations are same as before.

## Author's checklist

- [x] Migrated panels should be removed from visualization folder.
- [x] Migrated visualizations are populating in current Kibana version 8.3.0 itself. 

## Related issues

- Relates #5221

### CODE REVIEW

**Comment by agithomas** [comment]
@SubhrataK , please assess the significance of the issue reported as "Not having feature to set last bucket value" . If it is relevant enough, we may need to wait until Lens resolves the issue.

**Comment by SubhrataK** [comment]
> @SubhrataK , please assess the significance of the issue reported as "Not having feature to set last bucket value" . If it is relevant enough, we may need to wait until Lens resolves the issue.

@agithomas As already discussed, with @harnish-elastic the value displayed in lens (without the selection of "Drop last bucket") is correct representation of data and hence we do not need that option. The same has been communicated in the issue you have mentioned above.

**Comment by agithomas** [comment]
@harnish-elastic , once you made the changes, resolved the merge conflicts, please ask for re-review

**Comment by harnish-elastic** [comment]
@agithomas Updated the PR with converting split chart to table chart. Thanks!

**Review by kush-elastic — APPROVED** [review]

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
