### PR TITLE
Add package data

### PR DESCRIPTION
**Pull request by mtojek**
Issue: https://github.com/elastic/package-registry/issues/414

This PR only adds package data. No side changes.

### CODE REVIEW

**Comment by mtojek** [comment]
Also @ruflin,  would you like to move alpha packages in this PR as well?

**Comment by ruflin** [comment]
@mtojek I prefer to keep the alpha packages in package registry for a few more days until all PR's are merged.

**Comment by ruflin** [comment]
Is the current PR reimported from Beats (through the script) or copied or from package-registry?

As soon as this is merged, lets remove it from the package-registry.

**Comment by mtojek** [comment]
Reimported.

**Comment by ruflin** [comment]
Great, so the script works 👍

**Pull request merged**
