### PR TITLE
Add global level data_stream.dataset dashboard filter

### PR DESCRIPTION
**Pull request by milan-elastic**
## Proposed commit message
Add a global filter to the dashboard and remove the subfilters on the dataset and a global filter on the dataset is introduced. Filters on data_stream.dataset are applied with a phrase type filter on the dataset that is being used in that particular dashboard.

Expect the above mentioned changes done in following selected packages to ease the review
- Stan
- Nats
- Golang
- Couchbase
- Couchdb
- IIS
- Memcached
- Zookeeper
- InfluxDB
- Coredns

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates https://github.com/elastic/integrations/issues/9323

## Screenshot

<details>
<summary>Stan</summary>

|Logs Before|Logs After|
|:-:|:-:|
|stan  logs overview - before|stan  logs overview - after|

|Channel Before| Channel|
|:-:|:-:|
|stan  channel overview - before|stan  channel overview - after|

</details>
<details>
<summary>Nats</summary>

|Metrics Before|Metrics After|
|:-:|:-:|
|before_nats_metrics_dashboard|after_nats_metrics_overview|

|Logs Before|Logs After|
|:-:|:-:|
|before_nats_logs_dashboard|after_nats_logs|

</details>

<details>
<summary>Golang</summary>

|Heap Before|Heap After|
|:-:|:-:|
|golang  heap - before|golang  heap - after|

|expvar Before|expvar After|
|:-:|:-:|
|golang  expvar - before|golang  expvar - after|

</details>

<details>
<summary>Couchbase</summary>

|xcdr Before|xcdr  After|
|:-:|:-:|
|couchbase  xdcr overview - before|couchbase  xdcr overview - after|

| sync gateway before| sync gateway after|
|:-:|:-:|
|couchbase  sync gateway overview - before|couchbase  sync gateway overview - after|

|node overview before|node overview after|
|:-:|:-:|
|couchbase  node overview - before|couchbase  node overview - after|

|Before|After|
|:-:|:-:|
|couchbase  metrics overview - before|couchbase  metrics overview - after|

</details>

<details>
<summary>Couchdb</summary>

|Before|After|
|:-:|:-:|
|couchdb  server-before|couchdb  server-after|

</details>

<details>
<summary>IIS</summary>

|Website Overview Before|Website Overview After|
|:-:|:-:|
|iis  website overview-before|iis  website overview-after|

|Webserver Process Before|Webserver Process After|
|:-:|:-:|
|iis  webserver process overview-before|iis  webserver process overview-after|

|Webserver Overview Before|Webserver Overview After|
|:-:|:-:|
|iis  webserver overview-before|iis  webserver overview-after|

|Application pool overview Before| Application pool overview  After|
|:-:|:-:|
|iis  application pool overview-before|iis  application pool overview-after|

|Access abd Error logs Before|Access abd Error logs After|
|:-:|:-:|
|iis  access and error logs-before|iis  access and error logs-after|
</details>

<details>
<summary>Memcached</summary>

|Stats Before|Stats After|
|:-:|:-:|
|before_memcached_stats|after_memcached_stats|
</details>

<details>
<summary>Zookeeper</summary>

|Before|After|
|:-:|:-:|
|before_zookeeper_mntr|after_zookeeper_mntr|
</details>

<details>
<summary>InfluxDB</summary>

|Status Before|Status After|
|:-:|:-:|
|before_influxdb_status|after_influxdb_status|

|Advstatus Before|Advstatus After|
|:-:|:-:|
|before_influxdb_advstatus|after_influxdb_advstatus|

</details>

<details>
<summary>Coredns</summary>

|Overview Before|Overview After|
|:-:|:-:|
|coredns  overview-before|coredns  overview-after|

</details>

### CODE REVIEW

**Review by harnish-elastic — APPROVED** [review]
LGTM! 🚀

**Review by agithomas — DISMISSED** [review]
LGTM!

**Comment by agithomas** [comment]
@harnish-elastic , can you verify - if entries in `validation.yml` (`exclude_checks`)  be updated as part of this change?

**Comment by harnish-elastic** [comment]
> @harnish-elastic , can you verify - if entries in `validation.yml` (`exclude_checks`) be updated as part of this change?

Okay, let me take a look at this with @milan-elastic and update if needed.

**Comment by milan-elastic** [comment]
> > @harnish-elastic , can you verify - if entries in `validation.yml` (`exclude_checks`) be updated as part of this change?
> 
> Okay, let me take a look at this with @milan-elastic and update if needed.

Done!

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
