### PR TITLE
Add build check for import-beats script

### PR DESCRIPTION
**Pull request by ruflin**
I am currently making a few changes to the import-beats script and I want to have assurance in CI that I did not break it. So this makes sure, that the script at least still builds after changes.

### CODE REVIEW

**Comment by mtojek** [comment]
As a quick win, this could be as simple as running "-help" to list flags. It should fail if the source code is not consistent.

**Comment by ruflin** [comment]
Happy to adjust, but not sure how it is different from what is in the PR?

**Comment by mtojek** [comment]
I reviewed your changes (really thought it's an issue hence suggestion). I like the idea you proposed. I think it would be valid to transform it into `BuildScripts` target and rebuild all scripts, which may also use the registry.

"Build" can be a combination of "BuildIntegrations" and "BuildScripts"

**Comment by ruflin** [comment]
@mtojek Not sure I follow. Is that a 👍  to get this in and iterate or changes to the PR needed?

**Pull request merged**
