### PR TITLE
[Enhancement] Adding ESXi log extraction to vsphere

### LINKED ISSUE #4566: vSphere integration drops EXSi logs that dont match grok pattern
The vSphere integration silently drops EXSi logs that do not match a grok pattern in the default ingestion pipeline.

This means that if the default ingest pipeline drops the log the user loses the opportunity to apply the custom integration pipeline.

This drop processor in the default ingest pipeline also overrides saving the _original event_ option despite being selected by the user on the integrations page.

**Suggestion:**
Do not drop the log file if the grok pattern does not match, just store it in the _message_ field.

**Example logs being dropped:**
<166>2022-11-04T15:01:58.230Z ESXI Hostd: info hostd[1053970] [Originator@6876 sub=Vimsvc.ha-eventmgr opID=esxui-b370-037c user=root] Event 406 : Guest OS reboot for Kali Linux - Foobar on ESXI in ha-datacenter

<166>2022-11-04T18:44:33.373Z ESXI Hostd: info hostd[1050909] [Originator@6876 sub=Default] IpmiIfcEntityInstantiateAll: stripping out phantom power supply IPMI SDRs

<110>2022-11-04T15:25:46.186Z ESXI shell[1231448]: [shell.cmd@6876 subject="root" object="shell" command="grep -i kali  hostd.log  | grep reboot" result="success" status="0"]

**Screenshot from Kibana discover app:**
After manually deleting the DROP processes error handler from the grok pattern, the logs are getting ingested with the following error
image

### PR DESCRIPTION
**Pull request by WildDogOne**
## What does this PR do?

It has been mentioned in Issue #4566 that ESXi logs sent via vsphere are silently dropped.
This has to do with the fact that the first Grok just drops if it fails, instead of letting the engineer decide.
This PR is here to resolve this issue, and to extract the data supplied in the samples

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues
- Closes #4566

### CODE REVIEW

**Comment by WildDogOne** [comment]
I removed 2 log lines from "test-format-common.log" because they seem useless
```
 (2021-09-06T14:40:29.190Z cpu3:2097472)]
 (2021-09-06T14:40:29.190Z cpu3:2097472)']
```

**Comment by WildDogOne** [comment]
Removed default drop on first Grok because this will silently drop events instead of letting the engineer decide

```
      on_failure:
        - drop:
            ignore_failure: true
```

**Comment by WildDogOne** [comment]
:+1

**Comment by jamiehynds** [comment]
Adding @SubhrataK for visibility.

**Pull request closed without merging**
