### PR TITLE
[O11Y] [AWS Billing] Convert "Total Estimated Charges" visualization to new metric

### PR DESCRIPTION
**Pull request by niraj-elastic**
## What does this PR do?

If we use the new metric chart and if the value is 5004 then the new metric visualization will show us 5k. It won't show us the actual value that is 5004. Also there isn't any option available to change this behavior. Hence legacy metric was used for Total Estimated Charges panel while migrating to lens.

Kibana 8.10.2 supports custom formatting for new metric visualization. Hence Converting Total Estimated Charges panel to new metric visualization is needed.

## Checklist

- [x] I have added an entry to my package's changelog.yml file.
- [x] I have verified that panels is populated with data.
- [x] I have updated screenshots of the dashboard.
- [x] I have verified that the panel aggregations are the same as before.

## Related issues

- Relates #6835

## Screenshots
Before 
metricbeat-aws-billing-overview (1)

After
metricbeat-aws-billing-overview

### CODE REVIEW

**Review by harnish-elastic — APPROVED** [review]
LGTM!

**Comment by niraj-elastic** [comment]
> @niraj-elastic thanks for doing this! The new metric is quite different from the legacy in that the label and the text can be too far apart in large panels. What do you think about updating the layout of the dashboard to look like this?
> 
> Screenshot 2023-11-16 at 7 37 43 AM

@drewdaemon Updated, thanks!

**Review by drewdaemon — APPROVED** [review]
LGTM!

**Review by zmoog — APPROVED** [review]
nit:

> Convert Total Estimated Charges panel to new metric visualization.

It would be great to have an 'executive summary' style recap of the changes in the PR description, for example:

- How it was before and how it is now
- Why we are making this change

**Comment by niraj-elastic** [comment]
> Updated, thanks!

@zmoog Made the changes, thanks!

**Comment by niraj-elastic** [comment]
> nit:
> 
> > Convert Total Estimated Charges panel to new metric visualization.
> 
> It would be great to have an 'executive summary' style recap of the changes in the PR description, for example:
> 
> * How it was before and how it is now
> * Why we are making this change

@zmoog Made the changes, thanks!

**Pull request merged**
