### PR TITLE
[System][core] Enable tsdb

### PR DESCRIPTION
**Pull request by tetianakravchenko**
## Proposed commit message

Enable TSDB by default for core datastream.
To enable tsdh on core datastream it is required to change the stack restriction to 8.11.0 - related to this issue https://github.com/elastic/elasticsearch/issues/96552.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## Related issues

- Closes https://github.com/elastic/integrations/issues/5848

## Screenshots
`system.core.id` is a dimension now, there is no errors like `Routing values must be strings but found` ([issue](https://github.com/elastic/elasticsearch/issues/96552))
Screenshot 2023-12-04 at 10 57 13

### CODE REVIEW

**Comment by mrodm** [comment]
Hi @tetianakravchenko, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

**Comment by tetianakravchenko** [comment]
CI is failing due to missing field in system.process datastream - here is a PR to add it https://github.com/elastic/integrations/pull/8783
@lalit-satapathy please help to review both PR and proceed with it

**Review by lalit-satapathy — APPROVED** [review]
LGTM

**Pull request merged**
