### PR TITLE
[Barracuda_WAF] Change the package name

### LINKED ISSUE #7724: [Barracuda] Rename to Barracuda WAF
Our [Barracuda package ](https://github.com/elastic/integrations/tree/main/packages/barracuda)used to include several datastreams for several products, but is now limited to Barracuda Web Application Firewall. Can we update the title and description of the package:

Title: Barracuda Web Application Firewall
Description: Collect logs from Barracuda Web Application Firewall with Elastic Agent.

### PR DESCRIPTION
**Pull request by vinit-chauhan**
## What does this PR do?

As mentioned in issue, #7724 the package name of `Barracuda` needed to be changed. This PR, therefore changes the name of the package and all of its associated assets (package name, data_stream name, dashboard IDs, field names, etc. )

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Closes #7724

## Screenshots
image
image

### CODE REVIEW

**Comment by vinit-chauhan** [comment]
Hey @efd6 - I've added CODEOWNER entry. Would you mind running the tests again? 😄

**Comment by vinit-chauhan** [comment]
Most of the changes are done for this PR, I'll be waiting for @jamiehynds' input on the issue. Once done, I'll mark it to "Ready to review".

**Comment by jamiehynds** [comment]
> Most of the changes are done for this PR. However, I'll waiting for @jamiehynds' input on the issue. Once done, I'll mark it to "Ready to review".

Thanks @vinit-chauhan - looking at the package version, the manifest.yml mentions 0.1.0 but the UI is showing 1.5.0. Any ideas as to why there's a discrepancy? 

Screenshot 2023-09-11 at 11 30 09

**Comment by vinit-chauhan** [comment]
Hey @jamiehynds - looks like the one you are referring to is the old integration. I've attached the screenshot along with the PR, which has updated Title and Readme. I'll have to update the integration version and titles of Visualizations if required to be aligned with the new name.

**Comment by vinit-chauhan** [comment]
Hey @jamiehynds - Updated the PR to match the version per your suggestion on the issue. And marking the PR ready for review. 😄

**Comment by jamiehynds** [comment]
> Hey @jamiehynds - looks like the one you are referring to is the old integration. I've attached the screenshot along with the PR, which has updated Title and Readme. I'll have to update the integration version and titles of Visualizations if required to be aligned with the new name.

Thanks @vinit-chauhan - I don't think you attached the screenshot, would you mind attaching? I'm looking at the latest version of the integration, which is appearing as 1.5.0. 

@bharath-elastic worked on the WAF integration. Can you remember if you just replaced the existing datastream within the Barracuda integration?

**Comment by vinit-chauhan** [comment]
Hey @jamiehynds - Here's the Screenshot. 

image

In the older integration of `barracuda v1.5.0`, there was only one data stream named `waf`. In this PR, the package has been renamed to `barracuda_waf` and data-stream to `logs`. Moreover, the older `barracuda` integration is not removed in this PR. Therefore, there are 2 integrations. 

If you want I can remove the older integrations and add this one or we can add an update to the old integration with a message that "we are moving to a new integration, and users would have to switch to the new integration." and later deprecate/remove it. 

If we want users to allow seamless updates, We will have to keep the package name the same. which is "barracuda". If we update the package name, to `barracuda_waf` it will create a new entry in the package registry. 

So there are two possible approaches to tackle this,
**Approach 1**: Rename the integration package to `barracuda_waf`: This would help us maintain the integration uniformity in the code base and in data ( field name for the custom field would follow `package_name.data-stream_name`: `barracuda_waf.logs` )  as the naming convention would be the same as other integrations. However, it would result in a somewhat bad UX, as existing users would have move to new integration and reindex old data, instead of simply clicking on the Update button for this particular update. 
**Approach 2**: Use the existing package name,  It would allow the users to update the package with ease. However, on the other hand, it would break the conversion in the code base and field mappings ( `barracuda.waf` )  

**Note:** In this PR, I've used Approach 1. 

Let me know your thoughts, and the changes necessary.

**Comment by bhapas** [comment]
@jamiehynds @vinit-chauhan 

Looks like there is a confusion here? I think issue #7724 meant to change the `title` and `description` in the `manifest.yml` - @jamiehynds correct me if I am wrong

https://github.com/elastic/integrations/blob/720540a54f47795a58acfa72508e995dbf028e3e/packages/barracuda/manifest.yml#L3-L5

**Comment by jamiehynds** [comment]
Thanks @bhapas - correct, just wanted to adjust the title to ensure it's clear the integration only covers WAF events. The title was originally 'Barracuda Logs' due to multiple datastreams for different products within that integration, it's now just limited to WAF so hoping to adjust the title accordingly.

**Comment by bhapas** [comment]
@vinit-chauhan 

So this is just down to

```diff
integrations/packages/barracuda/manifest.yml
- title: "Barracuda Logs"
- description: Ingest Events from Barracuda Web Application Firewall
+ title: "Barracuda Web Application Firewall"
+ description: Collect logs from Barracuda Web Application Firewall with Elastic Agent.

```

**Comment by vinit-chauhan** [comment]
Ah, I see. I thought we were going to update the whole package. So it's just the Manifest file then. 

Thanks for the update, I'll do the changes later today. 😄

**Review by efd6 — APPROVED** [review]

**Pull request merged**
