### PR TITLE
[AWS] Add Kinesis Metrics datastream

### LINKED ISSUE #3822: [AWS] migrate AWS Kinesis module from beats to integrations

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Add AWS Kinesis Metrics Datastream

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Requires #3799 
- Closes #3822

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
@legoguy1000 Thank you for migrating this data stream!! One quick question: I think we have a dashboard for kinesis metrics in Metricbeat. Can we also move the dashboard over? Thank you!

**Comment by legoguy1000** [comment]
@kaiyan-sheng I'll resolve the conflicts here when #3799 is merged.

**Review by kaiyan-sheng — COMMENTED** [review]
I think the `sample_event.json` file needs to be updated. But I can help regenerate that in a separate PR.

**Comment by legoguy1000** [comment]
Sounds good.

**Review by kaiyan-sheng — APPROVED** [review]

**Review by andrewctate — COMMENTED** [review]
I'm sorry that I wasn't able to review this sooner. Thank you for using Lens in your dashboard! A couple points about dashboard best practices:

- "Library visualizations" (aka "by-reference" visualizations) should generally be avoided. These are added to the user's "Visualize library" in Kibana instead of being limited to just the dashboard. You can tell that a visualization is "by-reference" because a little file icon will show up at the top right of the panel. It's easy to change these to _by-value_ by clicking the unlink button. This issue should be resolved this particular dashboard by https://github.com/elastic/integrations/pull/3688
Screen Shot 2022-07-28 at 12 11 32 PM

- Dashboard-native controls should be used instead of the deprecated "input controls" visualization type. Here is the [documentation](https://www.elastic.co/guide/en/kibana/master/add-controls.html) for dashboard-native controls.

This is what the old stuff looks like:

Screen Shot 2022-07-28 at 12 21 23 PM

This is what the new stuff looks like:
Screen Shot 2022-07-28 at 12 26 31 PM

This information is all available in the [best practices document](https://docs.google.com/document/d/1uyyFGx6xA5Kvl8c-ZdvXdvBGrHTylxU9F69TGqfzdmw/edit#).

**Comment by legoguy1000** [comment]
Good to know for the future.  These visualizations/dashboards were just the
Metricbeat items copied straight from the beats repo.

**Comment by andrewctate** [comment]
@legoguy1000 I totally get it. It's what I would do, too. It's sort of like the power of defaults.

We're pushing best practices in the integration dashboards because our customers often follow exactly the same workflow of copy-modify-publish. It's leverage to get customers using the best possible tools.

**Comment by legoguy1000** [comment]
Absolutely, totally agree!

**Comment by legoguy1000** [comment]
Will do.  I completely spaced on teh Visualizations.

**Comment by ruflin** [comment]
@jsoriano See above conversation and also in https://github.com/elastic/integrations/pull/4064 around by value / by reference. It would be great if there is an automated way to make our community contributors aware of these things to make their life easier. I remember we had a discussion around potentially bringing this in as a CI check or similar but couldn't find it anymore.

**Comment by jsoriano** [comment]
> @jsoriano See above conversation and also in #4064 around by value / by reference. It would be great if there is an automated way to make our community contributors aware of these things to make their life easier. I remember we had a discussion around potentially bringing this in as a CI check or similar but couldn't find it anymore.

@ruflin a warning was added for this in https://github.com/elastic/package-spec/pull/389. If warnings are not enough we may need to think in other strategies, or make this an error in CI.

**Comment by jsoriano** [comment]
> @jsoriano To see this warning, someone needs to open the CI logs? @legoguy1000 Did you ever stumble over these?

These warnings also appear when running `elastic-package` locally. This check was recently implemented, after this PR was merged, so I guess it didn't appear in this case.

> @jsoriano The more intrusive way would be with a comment as part of the coverage report or one of the other automatic comments from CI.

Yeah, it'd be good if we had more easily consumable warnings, I have added a mention to this in https://github.com/elastic/package-spec/issues/342.

**Comment by legoguy1000** [comment]
> @jsoriano To see this warning, someone needs to open the CI logs? @legoguy1000 Did you ever stumble over these?
> 
> @jsoriano The more intrusive way would be with a comment as part of the coverage report or one of the other automatic comments from CI.

You're talking about having visualizations embedded in the dashboards instead of separate files that are referenced? If so I can't remember that for this PR but I've definitely seen it lately and I'll be honest for the dashboards that I've copied from existing beats modules I haven't really done anything with them besides copy and update the fields.

**Pull request merged**
