### PR TITLE
Dashboard guidelines: use by value

### PR DESCRIPTION
**Pull request by endorama**
## What does this PR do?

- move dashboard guidelines to separate file
- add guideline around visualisation by value

Updating guidelines to reflect the guideline to use visualisations by value is part of https://github.com/elastic/integrations/issues/3448.  
I went a step forward and also moved dashboard guidelines to a new file, to help discovery and clarity of content.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by jlind23 — APPROVED** [review]
Thanks for the work.

**Comment by endorama** [comment]
@jlind23 I can't merge with failing CI. I don't think is related with my changes, maybe you have the right to merge this? Otherwise let me know how to proceed.

**Comment by jlind23** [comment]
@endorama Let me by pass checks for once.

**Comment by endorama** [comment]
Thanks!

**Pull request merged**
