### PR TITLE
initial commit for storage dashboard in ES integration

### PR DESCRIPTION
**Pull request by jsvd**

### CODE REVIEW

**Review by miltonhultgren — APPROVED** [review]
I've tested the dashboards and they work. My only feedback would be to consider aligning the naming of the dashboards with those added for Ingest Pipeline monitoring.

Screenshot 2023-12-14 at 12 46 33

**Comment by jsvd** [comment]
Done: https://github.com/elastic/integrations/pull/8689/commits/ba40c1024aaea576123b43d0dd786c4668c9edc2
@miltonhultgren thanks for the feedback

**Comment by jsvd** [comment]
@jsoriano taking up your offer to look at this PR, I set you up as a reviewer. thanks!

**Review by jsoriano — APPROVED** [review]
Nice. Consider adding screenshots of the dashboards. They can be added to the `img` directory and referenced in the manifest.

**Comment by mrodm** [comment]
Hi @jsvd, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

**Comment by jsvd** [comment]
@mrodm rebase done!
@jsoriano neat! I'll work on getting some screenshots when I'm back from PTO next year.

**Comment by jsvd** [comment]
@jsoriano screenshots added, looking for final LGTM. thanks!

**Review by jsoriano — APPROVED** [review]
> @jsoriano screenshots added, looking for final LGTM. thanks!

Nice, thanks!

**Comment by IanLee1521** [comment]
@jsvd / whomever  - I've been using these dashboards recently and am having some issues with them in our environment, what's the best way to provide feedback? Open a new issue?

**Comment by jsvd** [comment]
Hi @IanLee1521 yes a new issue on this repo would be the right approach! /cc @flexitrev

**Pull request merged**
