### PR TITLE
[O11y][PostgreSQL] Lens migration for `Query Duration Overview` visualizations to Kibana version 8.4.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for PostgreSQL integration package

- Statistics for PostgreSQL Lens migration:

<html>
<body>

PostgreSQL Dashboards  | Before Migration |   | After Migration |      |  
-- | -- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization | New control panel
[Logs PostgreSQL] Query Duration Overview | 0 | 1 | 1 | 0 | 0
 | 0 | 1 | 1 | 0 | 0

</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.4.0 itself.

## Related issues

- Relates #5221

### CODE REVIEW

**Comment by agithomas** [comment]
@rajvi-elastic , there exist three panels in the dashboard. But, in the summary chart, only 1 is marked. Can you please look?

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic , there exist three panels in the dashboard. But, in the summary chart, only 1 is marked. Can you please look?

@agithomas, the other two panels are saved search. The search panels doesn't belong to either visualizations or lens category and also they are not migrated.

**Review by agithomas — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
Please complete the peer review

**Comment by milan-elastic** [comment]
Thanks @rajvi-elastic ! Approved!

**Comment by milan-elastic** [comment]
Thanks @rajvi-elastic ! Approved!

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Pull request merged**
