### PR TITLE
[D4C] cloud_defend. Removed kubernetesPodId. Update docs.

### PR DESCRIPTION
**Pull request by mitodrummer**
## What does this PR do?

Removes documentation for an unimplemented selector condition.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Review by norrietaylor — APPROVED** [review]
LGTM

**Comment by learhy** [comment]
Karl, I think the readme should also act as the source of truth for our feature compatibility matrix:

<google-sheets-html-origin><style type="text/css"></style>

  | EKS 1.24-1.26 (AL2022) | GKE 1.24-1.26 (COS)
-- | -- | --
Process event exports | ✅ | ✅
Network event exports | ✅ | ✅
File event exports | ✅ | ✅
File blocking | ✅ | ✅
Process blocking | Coming Soon | Coming Soon
Network blocking | ❌ | ❌
Drift prevention | ✅ | ✅
Mount point awareness | ✅ | ✅


I also think we could replace the overview section with this text which I think does a better job of really describing the integration:

**How Container Workload Protection Works**
CWP is powered by a lightweight integration (Defend for Containers) that is bundled and configured by the Elastic Agent. The agent is installed as a daemonset on supported Kubernetes clusters and the integration uses eBPF LSM and tracepoint probes to produce system events. Events are evaluated against eBPF LSM hook points, enabling a configured policy to be evaluated before system activity is allowed to proceed. 

The policy determines which system behaviors (for example, process executions, file creations or deletions, etc) will result in an action. Actions are simple: logging the behavior to Elasticsearch, creating an alert in Elasticsearch, or blocking the behavior. 

**Threat Detection**
The system ships with a default policy configured featuring two selectors and responses. The first selector is designed to stream process telemetry events to the user’s Elasticsearch cluster. The policy uses the selector allProcesses which specifies fork and exec operations. This selector is mapped to the allProcesses response, which specifies a log action. 

The resulting telemetry data is transformed into an ECS document and streamed back to the user’s Elasticsearch cluster, where the Elastic Security SIEM evaluates the data to detect malicious behavior. 

**Drift Detection & Prevention**
The second selector is written to detect the modification of existing executables or the creation of new executables within a container (This is how Elastic detects “container drift”). The policy selector is named executableChanges and is mapped to a response section called executableChanges which specifies an alert action. 

This policy is configured with an alert response, meaning that when drift conditions are detected, the matching event(s) are collected and written as an alert to the user’s Elasticsearch cluster. A prebuilt rule “escalation rule” in the SIEM watches for these alert documents and raises an alert in the SIEM when drift is detected. This policy can also be modified to block drift operations by changing the response action to block. 

**Policies**
Users that want to use the full strength of CWP will benefit to understand the system’s policy syntax, which enables fine-grained policies to be constructed. Policies can be built to precisely match expected container behaviors– disallowing any unexpected behaviors– and thereby substantially hardening the security posture of container workloads. 

Policies are composed of selectors and responses. A given policy must contain at least one selector and one response. Currently, the system supports two types of selectors and responses, file and process. Selectors tell the service what system operations to match and have a number of conditions that can be grouped together (using a logical AND operation) to provide precise control. Responses instruct the system on what actions to take when system operations match selectors.

**Comment by norrietaylor** [comment]
@learhy I think your suggestions here are great, but they are outside the scope of the PR. I will transpose them into a new issue and we get them in the queue.

**Comment by learhy** [comment]
OK-- Karl asked me to comment on the PR

Dan Rohan

**Comment by norrietaylor** [comment]
My bad, I've created the new issue linked above for my own clerical reason :)

**Comment by norrietaylor** [comment]
I would love to see that. @learhy can you provide the text?On May 10, 2023, at 9:15 AM, Karl Godard ***@***.***> wrote:﻿
@norrietaylor @learhy Did we want to add anything about having to uncomment "capabilities" in the yaml?

**Pull request merged**
