### PR TITLE
[O11y][AWS] Migrate AWS Metric Overview dashboard visualizations to lens

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
Manually migrate AWS `Metrics (EC2, SQS, ELB, Lambda)` visualizations to the lens in the current Kibana version `8.7.1` itself. 

## Migration stats
<html>
<body>

AWS Metrics Dashboard  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
Dashboards | 0 | 15 | 15 |0 

</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to the lens.
- [X] I have updated screenshots of the dashboard.
- [X] I have verified that the data counts are matching and panel aggregations are the same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.7.1 itself.

## Related issues

- Relates #6141
- Closes https://github.com/elastic/integrations/issues/6222

Note: 

As per the discussion with team, aggregations for the below panels have been modified:

<html>
<body>

Visualization | Field | Aggregation [Before] | Aggregation [After]
-- | -- | -- | --
Total # of HTTP 4xx Errors | aws.s3_request.errors.4xx | Sum | Average
Total # of HTTP 5xx Errors | aws.s3_request.errors.5xx | Sum | Average
SQS Empty Receives Top5 | aws.sqs.empty_receives | Average | Last Value
SQS Messages Delayed Top5 | aws.sqs.messages.delayed | Average | Last Value
Cloudwatch ELB Request Count Top5 | aws.elb.metrics.RequestCount.sum | Sum | Sum
Cloudwatch ELB Unhealthy Host Count | aws.elb.metrics.UnHealthyHostCount.max | Sum | Last Value
Cloudwatch Lambda Errors Top5 | aws.lambda.metrics.Errors.avg | Average | Average
Cloudwatch Lambda Invocations Top5 | aws.lambda.metrics.Invocations.avg | Average | Average
Cloudwatch Lambda Throttles Top5 | aws.lambda.metrics.Throttles.avg | Average | Average

</body>
</html>

Please refer the below `Before Migrated screenshot` to compare!
image

### CODE REVIEW

**Comment by drewdaemon** [comment]
Awesome to see this.

A couple of requests:
- Can we change those metrics to be the new Lens metric (as opposed to the legacy metric)?
- Can we remove the legacy dashboard controls and replace them with the [new stuff](https://www.elastic.co/guide/en/kibana/master/add-controls.html)? Once you do this, you can 
  - convert the pie chart to a treemap visualization (equivalent, but better use of the space)
  - keep the pie chart the same size and just expand the "EC2 CPU Utilization" visualization to make up for the extra space in the first row

**Comment by rajvi-elastic** [comment]
> A couple of requests:

@drewdaemon, The screenshot in description is before migrated dashboard. I have updated the screenshot in [package](https://github.com/elastic/integrations/pull/6543/files#diff-d7c25220c73c623dded1899182980cd2cf61e3f7ca819b97e66e8650aa71211e) itself where I have converted the legacy metrics to new metric and also migrated to new control panels.

Please let me know if anything needs to be changed.

Sorry for the confusion!

**Review by drewdaemon — APPROVED** [review]
Sorry @rajvi-elastic. I should have read more carefully!

Looks good from my end, though you might try changing the color of the horizontal bar graphs to the Lens default so they match the new pie chart (this can be done by deleting the custom color that came over from TSVB).

Approved so as not to hold you up.

**Review by milan-elastic — APPROVED** [review]
LGTM!

**Pull request merged**
