### PR TITLE
[Suricata] Missing ECS Field Mappings

### LINKED ISSUE #7270: [Netflow] Missing ECS Field Mappings
## Describe the Issue

The Netflow integration does not currently have mappings for several `destination.*` and `source.*` fields and is causing conflicts in the `logs-*` Data View. 

## Screenshots
netflow_conflict

### LINKED ISSUE #7274: [Suricata] Missing ECS Field Mappings
## Describe the Issue

The Suricata integration does not currently have mappings for several `destination.*` and `source.*` fields and is causing conflicts in the `logs-*` Data View. 

## Screenshots
suricata_conflict

### PR DESCRIPTION
**Pull request by MakoWish**
Type of change

- Bug

## What does this PR do?

This PR adds missing mappings `source.*` and `destination.*` fields to prevent field mapping conflicts in the `logs-*` Data View. 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have incremented the version in my package's `manifest.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #7274

## Screenshots

suricata_conflict

### CODE REVIEW

**Review by kcreddy — APPROVED** [review]
LGTM

**Comment by MakoWish** [comment]
I don't have permissions to merge. Could someone do it, please?

**Comment by efd6** [comment]
Please hold off on merging this subject to internal discussion.

**Review by efd6 — CHANGES_REQUESTED** [review]
The approach that we should be using here is to turn on `import_mappings`. This is ~detailed [here](https://github.com/elastic/package-spec/blob/037631bddaffe6519b61eb41c186fb929675d6e1/spec/integration/_dev/build/build.spec.yml#L23-L26) in the package spec, but there is an issue to improve the documentation for the option [here](https://github.com/elastic/elastic-package/issues/1421). There are examples of its use in the wild, for example [here](https://github.com/elastic/integrations/blob/1c48a895f3a2e88dddad43316352febba9034bfb/packages/cisco_nexus/_dev/build/build.yml#L4).

**Pull request closed without merging**
