### PR TITLE
[ZScaler ZPA] Fix PosturesHit and PosturesMiss parsing

### LINKED ISSUE #5537: [ZScaler ZPA] UserStatus -  Processing errors for PostureHits and PostureMiss fields
Hello,

We noticed the `PosturesHit` and  `PosturesMiss` fields from our ZScaler ZPA User status logs were not parsed and didn't appeared into our data streams. Zscaler ZPA is configured to send us its logs the way described into the [integration documentation](https://docs.elastic.co/integrations/zscaler_zpa#user-status-logs). Version of the integration is the current one (1.5.0)

After some quick tests, I was able to reproduce the issue by simulating the pipeline execution on a raw log in verbose mode. The two `split` processors dealing with those fields were failing with the following output:

```json
{
  "processor_type": "split",
  "status": "error_ignored",
  "ignored_error": {
    "error": {
      "root_cause": [
        {
          "type": "illegal_argument_exception",
          "reason": "field [json.PosturesHit] of type [java.util.ArrayList] cannot be cast to [java.lang.String]"
        }
      ],
      "type": "illegal_argument_exception",
      "reason": "field [json.PosturesHit] of type [java.util.ArrayList] cannot be cast to [java.lang.String]"
    }
  },
  "doc": {...}
}
```

I changed the two `split` processors into `rename` processors and documents started to show with `zscaler_zpa.user_status.postures.hit` and `zscaler_zpa.user_status.postures.miss` stored as arrays.

I think the `split` processors should remain but with a condition checking if the original fields are `String` and they should be doubled with their `rename` counterparts if the original fields are of type `ArrayList`. That way, compatibility with the current logic will remain and the pipeline would support data that are already into a JSON array. If needed, I can try to submit a PR to fix this issue.

Thank you

### PR DESCRIPTION
**Pull request by srilumpa**
## What does this PR do?

As described in #5537, ZScaler Private Access Postures fields are not properly parsed and the related processors fail silently. This PR fixes this by checking if the field is a string or a list and apply the adequate processor.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [x] Pipeline properly proceeds log with `PosturesHit` and `PosturesMiss` as Strings (current behaviour)
- [x] Pipeline properly proceeds log with `PosturesHit` and `PosturesMiss` as Lists (expected behaviour)

## How to test this PR locally

1. Start the Elastic stack: `elastic-package.exe stack up -v -d`
2. Setup environment: `\elastic-package stack shellinit`
3. Run unit tests: `elastic-package.exe test pipeline -v`

## Related issues

- Closes #5537

### CODE REVIEW

**Comment by ShourieG** [comment]
@srilumpa can you update the **version** under manifest.yml to "1.5.3". Otherwise its failing our CI checks

**Comment by srilumpa** [comment]
My bad, I forgot to update this field too.

**Review by andrewkroh — APPROVED** [review]
LGTM. What version of ZPA are you running where you observed the `Postures{Hit,Miss}` that were lists? Did the format of these fields change between versions?

**Comment by srilumpa** [comment]
Unfortunately, I can't tell you as I don't have those informations. We transmitted the configuration requested by the Elastic's integration documentation to the ones in charge of the appliance configuration and they configured the log forwarding accordingly. I don't think there were any version changes since then.

**Comment by srilumpa** [comment]
Hello, I have just updated the branch with the last main version and fix the conflicts. Are there some additional steps or missing informations that I could provide to proceed with this PR?

**Comment by jamiehynds** [comment]
Thanks @srilumpa. @ShourieG @bhapas are we ok to merge this PR?

**Review by bhapas — APPROVED** [review]
LGTM

**Pull request merged**
