### PR TITLE
Fix for issue #8425 ti_opencti integration causes field conflict

### LINKED ISSUE #8425: ti_opencti integration causes field conflict
Field `event.original` is an object within the `ti_opencti.indicator` datastream, when it should be a keyword to conform to [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-original).

This is due to enabling retention of event.original while debugging the integration configuration and connectivity from elastic agent to OpenCTI.

I will not be the last to need to do this.

Field conflicts result in search related issues and likely missed security detections that should occur.

The `ti_opencti.indicator` ingest pipeline should convert the original OpenCTI object which is being stored in event.original to an escaped JSON text string instead, in order to avoid conflicts with other `logs-*` indices, and in particular other `logs-ti_*` indices.

The original object should be stored in an alternative structure instead, for example as `opencti.original` or similar.

Conflicts with other `logs-ti_` indices,

Screenshot 2023-11-08 at 9 44 37 am

Screenshot 2023-11-08 at 9 44 45 am

Example document,

```
{
  "_index": ".ds-logs-ti_opencti.indicator-default-2023.11.01-000001",
  "_id": "v0GviYsB7yFddSXSKrvB",
  "_version": 1,
  "_score": 0,
  "_source": {
    "agent": {
      "name": "elastic-agent",
      "id": "7d3d7879-7cd6-4352-9c2b-186499853bc2",
      "type": "filebeat",
      "ephemeral_id": "4fbed899-b644-4a48-960c-8aa303063f4e",
      "version": "8.10.4"
    },
    "elastic_agent": {
      "id": "7d3d7879-7cd6-4352-9c2b-186499853bc2",
      "version": "8.10.4",
      "snapshot": false
    },
    "cloud": {
      "availability_zone": "",
      "instance": {
        "name": "",
        "id": ""
      },
      "provider": "hetzner",
      "service": {
        "name": "Cloud"
      },
      "region": ""
    },
    "ecs": {
      "version": "8.10.0"
    },
    "related": {
      "ip": [
        "77.97.164.31"
      ]
    },
    "event": {
      "agent_id_status": "verified",
      "ingested": "2023-11-01T07:00:40Z",
      "original": {
        "standard_id": "indicator--44117981-d1dc-58a4-95fc-dd3944b2594b",
        "externalReferences": {
          "edges": []
        },
        "killChainPhases": {
          "edges": []
        },
        "pattern_type": "stix",
        "created": "2023-11-01T05:33:54.025Z",
        "confidence": 70,
        "pattern_version": "2.1",
        "pattern": "[ipv4-addr:value = '77.97.164.31']",
        "valid_from": "2023-11-01T05:33:54.025Z",
        "description": "Malicious SSL connections",
        "revoked": false,
        "objectMarking": {
          "edges": []
        },
        "x_opencti_main_observable_type": "IPv4-Addr",
        "observables": {
          "pageInfo": {
            "globalCount": 1
          },
          "edges": [
            {
              "node": {
                "standard_id": "ipv4-addr--7ade4706-945d-5641-9061-95a8471f8d6f",
                "entity_type": "IPv4-Addr",
                "id": "3096eea9-148f-4419-a407-8d937ea3656b",
                "value": "77.97.164.31",
                "observable_value": "77.97.164.31"
              }
            }
          ]
        },
        "valid_until": "2023-12-31T05:33:54.025Z",
        "is_inferred": false,
        "createdBy": {
          "identity_class": "organization",
          "name": "Abuse.ch ssl blacklist"
        },
        "name": "77.97.164.31",
        "modified": "2023-11-01T05:36:22.028Z",
        "x_opencti_detection": false,
        "id": "8e0ea4c6-3943-4c60-8413-b983217689ad",
        "x_opencti_score": 50,
        "lang": "en",
        "objectLabel": {
          "edges": [
            {
              "node": {
                "value": "osint"
              }
            },
            {
              "node": {
                "value": "ssl-blacklist"
              }
            }
          ]
        }
      },
      "kind": "enrichment",
      "created": "2023-11-01T05:33:54.025Z",
      "id": "8e0ea4c6-3943-4c60-8413-b983217689ad",
      "category": [
        "threat"
      ],
      "type": [
        "indicator"
      ],
      "dataset": "ti_opencti.indicator"
    },
    "tags": [
      "preserve_original_event",
      "forwarded",
      "opencti-indicator",
      "osint",
      "ssl-blacklist",
      "ecs-indicator-detail"
    ],
    "input": {
      "type": "cel"
    },
    "@timestamp": "2023-11-01T07:00:38.018Z",
    "data_stream": {
      "namespace": "default",
      "type": "logs",
      "dataset": "ti_opencti.indicator"
    },
    "threat": {
      "indicator": {
        "reference": "https://opencti/dashboard/observations/indicators/8e0ea4c6-3943-4c60-8413-b983217689ad",
        "provider": "Abuse.ch ssl blacklist",
        "confidence": "High",
        "ip": [
          "77.97.164.31"
        ],
        "name": "77.97.164.31",
        "description": "Malicious SSL connections",
        "modified_at": "2023-11-01T05:36:22.028Z",
        "type": "ipv4-addr"
      },
      "feed": {
        "reference": "https://docs.opencti.io/latest/usage/overview/",
        "name": "OpenCTI",
        "description": "Indicator data from OpenCTI",
        "dashboard_id": "ti_opencti-83b2bef0-591c-11ee-ba5f-49a63bb985cd"
      }
    },
    "opencti": {
      "indicator": {
        "standard_id": "indicator--44117981-d1dc-58a4-95fc-dd3944b2594b",
        "detection": false,
        "pattern_type": "stix",
        "pattern_version": "2.1",
        "pattern": "[ipv4-addr:value = '77.97.164.31']",
        "valid_from": "2023-11-01T05:33:54.025Z",
        "revoked": false,
        "score": 50,
        "valid_until": "2023-12-31T05:33:54.025Z",
        "is_inferred": false,
        "observables_count": 1,
        "lang": "en",
        "creator_identity_class": "organization"
      },
      "observable": {
        "ipv4_addr": {
          "standard_id": "ipv4-addr--7ade4706-945d-5641-9061-95a8471f8d6f",
          "entity_type": "IPv4-Addr",
          "id": "3096eea9-148f-4419-a407-8d937ea3656b",
          "value": "77.97.164.31"
        }
      }
    }
  }
  }
}
```

### PR DESCRIPTION
**Pull request by colin-stubbs**
- Bug

## Proposed commit message

Added primary ingest pipeline processor to ensure `event.original` is removed if the `preserve_original_event` tag is NOT present.

Added primary ingest pipeline processor to ensure `event.original` is converted to a text field if it exists, to support storage as a text keyword field as per ECS definition.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [X] `elastic-package build` completed without errors
- [X] `elastic-package check` completed without errors
- [X] `elastic-package test --generate` completed without errors 

## How to test this PR locally

Deploy and test locally using `elastic-package` based stack.

## Related issues

- Closes #8425

## Screenshots

Not applicable.

### CODE REVIEW

**Comment by chrisberkhout** [comment]
Hi Colin,

Thanks for the PR!

Turning on `preserve_original_event` for the system tests and having that show in the sample event and documentation is good.

Currently, `event.original` should only be [added if `preserve_original_event` is set](https://github.com/elastic/integrations/blob/5ccced5d589d610d52da64179ddf3c4f120522e3/packages/ti_opencti/data_stream/indicator/agent/stream/cel.yml.hbs#L55-L57), so I think removing it otherwise is redundant. Note that it's the `preserve_original_event` *setting* that determines adding the field and the tag, rather the field addition/retention being based on a tag added in another way.

I notice that the string conversion step is generating a stringified object that isn't in JSON format:
`{standard_id=indicator--cde0a6e1-c622-52c4-b857-e9aeac56131b, ...}` vs 
`{"standard_id":"indicator--cde0a6e1-c622-52c4-b857-e9aeac56131b", ...}`.
I'm inclined to stringify where the field is inserted, in the CEL expression, like this:
```diff
diff --git a/packages/ti_opencti/data_stream/indicator/agent/stream/cel.yml.hbs b/packages/ti_opencti/data_stream/indicator/agent/stream/cel.yml.hbs
index 3f6d08388..f07a0025c 100644
--- a/packages/ti_opencti/data_stream/indicator/agent/stream/cel.yml.hbs
+++ b/packages/ti_opencti/data_stream/indicator/agent/stream/cel.yml.hbs
@@ -53,7 +53,7 @@ program: |
     bytes(resp.Body).decode_json().as(body, state.with({
       "events": body.data.indicators.edges.map(e, e.node.with(
         has(state.preserve_original_event) && state.preserve_original_event ?
-          { "event": { "original": e.node } } :
+          { "event": { "original": e.node.encode_json() } } :
           {}
       )),
       "want_more": body.data.indicators.pageInfo.hasNextPage,
```

What do you think?

**Comment by colin-stubbs** [comment]
Ah yes! I didn't actually double check the result in event.original :-(

Yeap, doing it there insteadmakes sense, zero issues.

I'll adjust the PR.

**Comment by chrisberkhout** [comment]
To make the tests pass, run `elastic-package build` and commit the updated `packages/ti_opencti/docs/README.md`.  
(`docs/README.md` is generated from `_dev/build/docs/README.md` using Handlebars templating).

**Comment by colin-stubbs** [comment]
rebuild done

**Review by chrisberkhout — APPROVED** [review]

**Comment by chrisberkhout** [comment]
@colin-stubbs One more thing: there are conflicts to resolve, since a couple of other changes went in since the PR was opened.

**Pull request merged**
