### PR TITLE
[AWS] [EMR] Add metrics dashboard

### LINKED ISSUE #6438: [AWS] [EMR Metrics] Dashboard
## Summary

The current monitoring capabilities for AWS EMR metrics lack a dedicated dashboard to visualize EMR metrics data stream. Create a concise and user-friendly EMR metrics dashboard for Kibana. This will provide customers with valuable insights to optimize their EMR clusters.

## Tasks/Steps

- Identify Relevant Metrics
  - Determine the most meaningful and valuable metrics for customers. This will involve understanding the specific needs and pain points of EMR users.
- Dashboard Creation
  - Develop a concise and intuitive dashboard using Kibana to display the identified metrics. The dashboard should be visually appealing and easy to navigate, allowing customers to quickly gain insights into the performance of their EMR clusters.

## Docs
- https://docs.aws.amazon.com/emr/latest/ManagementGuide/UsingEMR_ViewingMetrics.html

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?

Adds metrics dashboard for EMR metrics data stream.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Closes #6438 

## Screenshots
emr_dashb

### CODE REVIEW

**Comment by stratoula** [comment]
@gpop63 have you checked how it looks on dark mode? I am mostly concerned about the metrics.

**Comment by gpop63** [comment]
This is how it looks in dark mode:
emr_dark_mode

**Comment by gpop63** [comment]
I used the default color for metric charts and now it adjusts itself! Thanks @stratoula 

Black:
emr_updated

White:
emr_updated_white

**Review by stratoula — APPROVED** [review]
Much better now I think. We will work on this and then the transparent will be pure whit but until then this approach is better! LGTM

**Review by zmoog — APPROVED** [review]
The values are a little weird, but I know you partially used fake data.

LGTM, but we should add an item in the BETA to GA issue.

**Pull request merged**
