### PR TITLE
[Azure] [App Service Logs] Dashboard for logs datastream

### LINKED ISSUE #7173: [Azure] [App Service Logs] Dashboard for logs datastream
Figure out which logs are suitable for visualization and provide an OOTB dashboard.

### PR DESCRIPTION
**Pull request by lucian-ioan**
### Urgency
- Normal

### Activity Type
- Enhancement

## What does this PR do?

Adds an overview dashboard for App Service Logs and 6 dashboards corresponding to each data stream.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] Move HTTP Logs first in the navigation panel as those logs have the most information available.

Initial Completed dashboards:

- [ ] Overview
- [ ] App Logs
- [ ] HTTP Logs
- [ ] Platform Logs
- [x] Console Logs
- [ ] Audit Logs
- [x] IpSecAudit Logs

## How to test this PR locally

Document providing details on how to fetch data for each individual log category:
https://docs.google.com/document/d/1AJREQvAE2mc1QU19YKgZ4QJB6OHsyw8fy_WlLRYJV74

## Related issues

Closes #7173

## Screenshots

Console Logs:
ConsoleLogs

IpSecAudit Logs:
IpSecAuditLogs

Unsure whether a line plot based on denied/allowed is too much here given that there's enough information already based on Results.

### CODE REVIEW

**Comment by lucian-ioan** [comment]
Ongoing work. 4/6 dashboards so far.

**Comment by lucian-ioan** [comment]
6/7 dashboards done, only AppLogs left. Will push the work and provide updated screenshots.

**Comment by lucian-ioan** [comment]
👍 Still relevant, had other priorities at the time but will return here ASAP.

**Comment by mrodm** [comment]
Hi @lucian-ioan, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

**Pull request closed without merging**
