### PR TITLE
[MongoDB] Enable TSDB

### PR DESCRIPTION
**Pull request by ritalwar**
- Enhancement

## What does this PR do?

This PR enables TSDB for MongoDB module.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates #6152

### CODE REVIEW

**Comment by lalit-satapathy** [comment]
Lets add this to MongoDB Meta issue. I see many counters used in MongoDB, did we change any visualisations? Are all the aggregations up-to-date.

**Comment by ritalwar** [comment]
> Lets add this to MongoDB Meta issue. I see many counters used in MongoDB, did we change any visualisations? Are all the aggregations up-to-date.

Done.
No changes in visualisations were needed as all the fields used in existing visualisations were of type gauge.

**Review by lalit-satapathy — APPROVED** [review]
LGTM

**Pull request merged**
