### PR TITLE
[O11y][Oracle WebLogic] Fix Logs Overview dashboard

### LINKED ISSUE #8779: [Oracle Weblogic] Failure in dashboards after change in message datatype
In oracle weblogic Integration, there was a [change](https://github.com/elastic/integrations/pull/7971) of datatype of message field to comply with the ECS. Following this change, failure of dashboards was observed  `match_only_text fields do not support sorting and aggregations`. 

The failure happens since there are panels where aggregation (last_value) is being performed on the message field which now is match_only_text instead of keyword. 

Failure Screenshot: 
image

image (1)

image (2)

cc: @andrewkroh, fyi

### PR DESCRIPTION
**Pull request by harnish-elastic**
## Proposed commit message

-  Dashboard table visualizations that have message field, converted to saved search visualization. https://github.com/elastic/integrations/issues/8779

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that the fixed dashboard is working as expected.

## Related issues

- Closes #8779 

### Before
oracle_weblogic-logs-overview-before

### After
oracle_weblogic-logs-overview-after

### CODE REVIEW

**Review by milan-elastic — APPROVED** [review]
LGTM!

**Comment by ishleenk17** [comment]
@harnish-elastic : I hope you have tried the upgrade scenario and are seeing no issue there. 
If that works, changes are good to go

**Comment by harnish-elastic** [comment]
> @harnish-elastic : I hope you have tried the upgrade scenario and are seeing no issue there. If that works, changes are good to go

Yes, I have performed the upgrade scenario and the dashboard working as expected!

**Review by ishleenk17 — APPROVED** [review]
Looks good!

**Pull request merged**
