### PR TITLE
New integration - ESET Threat Intelligence

### PR DESCRIPTION
**Pull request by polakovicp**
## What does this PR do?
PR adds integration package for ESET Threat Intelligence data feeds.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

### CODE REVIEW

**Comment by polakovicp** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [dc893ed](https://github.com/elastic/integrations/commit/dc893edd414fa6c295c612ca7d570323d9990e34), [ef80c42](https://github.com/elastic/integrations/commit/ef80c4241934b39409b898ba1ddbbad15940c464)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

CLA should be signed now

**Comment by jamiehynds** [comment]
@ShourieG would you mind kicking off the tests for this PR as CLA has now been signed?

**Comment by ShourieG** [comment]
@jamiehynds CLA issue is still there.

**Pull request closed without merging**
