### PR TITLE
citrix_waf: relax header format constraints

### LINKED ISSUE #9266: Citrix Web App Firewall - v 1.13.2 - Grok Errirs
all events being ingested from the citrix waf log are erroring with a "Provided Grok expressions do not match field value: " error

[<134> 2024/03/04:17:59:39 GMT <name snip> 0-PPE-1 : default API CMD_EXECUTED 149531 0 :  User <username snip> - ADM_User NONE - Remote_ip <ip snip> - Command \"logout\" - Status \"Success\"\n]

If I filter for error,message does not exist, I get no documents

### PR DESCRIPTION
**Pull request by efd6**
## Proposed commit message

- allow missing citrix header
- allow syslog priority field
- allow year-first date format in timestamp

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## Related issues

- Closes #9266

### CODE REVIEW

**Comment by efd6** [comment]
@jamiehynds The owner label here disagrees with the label on the issue. Which is correct?

**Comment by jamiehynds** [comment]
> @jamiehynds The owner label here disagrees with the label on the issue. Which is correct?

Given that Citrix WAF is an appliance that syslogs I _think_ it lives with deployment and devices, but will let @norrietaylor or @narph confirm.

**Comment by narph** [comment]
the team owner was probably wrongly assigned in https://github.com/elastic/integrations/issues/9266 but indeed Citrix WAF is currently owned by deployment and devices team.

**Comment by norrietaylor** [comment]
Agreed @narph! Thanks for getting here first.

**Comment by eriroley** [comment]
Pinging @elastic/sec-deployment-and-devices (Team:Security-Deployment and Devices)

**Review by taylor-swanson — APPROVED** [review]
LGTM

**Pull request merged**
