### PR TITLE
[awsfirehose] remove redudant `.logs` suffix from dataset name

### PR DESCRIPTION
**Pull request by tommyers-elastic**
## What does this PR do?

The dataset name is `awsfirehose.logs`, but the datastream `type` is `logs`. so the datastream name is `logs-awsfirehose.logs-*`. This PR removes this redundancy. 

The package is in very early tech preview - we are not worries about this being a major breaking change.

### CODE REVIEW

**Comment by tommyers-elastic** [comment]
closing this due to technical limitation and uncertainty around whether or not this is the right thing to do. the `logs` suffix is likely here to stay.

**Comment by ruflin** [comment]
I have a fix for this opened here: https://github.com/elastic/elastic-package/pull/1437

**Review by zmoog — APPROVED** [review]

**Comment by ruflin** [comment]
@tommyers-elastic https://github.com/elastic/elastic-package/pull/1437 has landed. To get this PR green, a new elastic-package release is needed. Can you and team help to get this over the line?

**Comment by ruflin** [comment]
The newest version of elastic-package was just realised with the fix in places. Lets rerun CI on this PR.

**Review by kaiyan-sheng — APPROVED** [review]
Thanks for making the change!

**Review by kaiyan-sheng — COMMENTED** [review]
https://github.com/elastic/integrations/blob/main/packages/awsfirehose/manifest.yml#L4 needs to be updated to 0.3.0

**Comment by kaiyan-sheng** [comment]
```
[2023-09-20T15:43:05.650Z] Error response from daemon: manifest for docker.elastic.co/kibana/kibana:8.10.0 not found: manifest unknown: manifest unknown
```
This is caused by kibana 8.10.0 image was removed.

**Pull request merged**
