### PR TITLE
[Cloudflare] Cloudflare audit logs

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Add a datastream for Cloudflare Audit logs

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

### CODE REVIEW

**Comment by legoguy1000** [comment]
Fixed version typo

**Review by P1llus — APPROVED** [review]

**Pull request merged**
