### PR TITLE
[nagios_xi] 3046: ECS Schema adherence for Nagios-XI fields

### PR DESCRIPTION
**Pull request by ishleenk17**
## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

elastic-package test system -v -g
elastic-package test static -v -g

## Related issues

- Closes https://github.com/elastic/integrations/issues/3046
- Relates https://github.com/elastic/integrations/issues/3016

### CODE REVIEW

**Review by kush-elastic — COMMENTED** [review]
Can you update the PR Heading: `[nagios_xi] 3046: ECS Schema adherence for Nagios-XI fields`
Else LGTM!

**Comment by jsoriano** [comment]
The problem with CLA seems to be caused by the use of local emails in the commits. @ishleenk17 could you please replace these emails in these commits? With an email for what the CLA is valid.

**Review by jsoriano — APPROVED** [review]
Codewise LGTM, there is some issue with CLA.

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Review by lalit-satapathy — APPROVED** [review]

**Pull request merged**
