### PR TITLE
[cisco_asa] Added new grok pattern for message ID 113039

### PR DESCRIPTION
**Pull request by WildDogOne**
For my open [issue ](https://github.com/elastic/integrations/issues/3992) I have built a pull requests to adjust the grok to deal with message ID 113039 properly

### CODE REVIEW

**Comment by efd6** [comment]
@WildDogOne Please sign the CLA so that we can take a look at this.

**Comment by efd6** [comment]
@WildDogOne This will need to have test cases added. These should be put in [this file](https://github.com/elastic/integrations/blob/main/packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-non-canonical.log) and then make sure you run `elastic-package test pipeline -g`.

**Comment by WildDogOne** [comment]
Should already be fixed in the newest snapshot, will stop this pull request.
Hope I can more successfully send the next ones

**Pull request closed without merging**
