### PR TITLE
[AWS] Migrate EBS dashboard visualizations to lenses

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?

Migrates EBS visualizations to lenses.

Before:

ebs_before

After:

ebs_after

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by tommyers-elastic** [comment]
looks good! are the region and volume id drop down filters using the deprecated input control panels though?

thanks

**Review by drewdaemon — COMMENTED** [review]
Thanks for doing this. As has been mentioned, we should take this opportunity to migrate the deprecated "controls visualizations" to the native dashboard controls ([doc](https://www.elastic.co/guide/en/kibana/current/add-controls.html)).

**Comment by gpop63** [comment]
I added the control groups and fixed first 2 panels width and position:

updated_ebs

**Review by drewdaemon — APPROVED** [review]
Looks great!

**Review by tommyers-elastic — APPROVED** [review]
thanks gabriel!

**Pull request merged**
