### PR TITLE
Apache: replace total_kbytes with total_bytes

### PR DESCRIPTION
**Pull request by mtojek**
## What does this PR do?

This PR adjusts the `apache.status` data stream to recent changes in filebeat (use field `total_bytes`). Opening as draft as I'm waiting for the changes in filebeat to get released first.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [ ] I have verified that all datasets collect metrics or logs.

## Related issues

- https://github.com/elastic/integrations/issues/370

Filebeat changes:
- https://github.com/elastic/beats/pull/23022
- https://github.com/elastic/beats/pull/23055 (cherry-pick)

### CODE REVIEW

**Comment by ycombinator** [comment]
> Opening as draft as I'm waiting for the changes in filebeat to get released first.

Could you link to the corresponding PR for the Filebeat changes?

**Comment by mtojek** [comment]
> Could you link to the corresponding PR for the Filebeat changes?

Linked in the issue desciption.

**Comment by ycombinator** [comment]
I think a couple places still need updating?

```
$  git grep total_kbytes
packages/apache/data_stream/status/sample_event.json:            "total_kbytes": 0,
packages/apache/docs/README.md:            "total_kbytes": 0,
```

**Review by ycombinator — COMMENTED** [review]
I think a couple places still need updating?

```
$  git grep total_kbytes
packages/apache/data_stream/status/sample_event.json:            "total_kbytes": 0,
packages/apache/docs/README.md:            "total_kbytes": 0,
```

**Comment by mtojek** [comment]
Nice catch, @ycombinator ! I adjusted the sample event (totally forgot about this one) and bumped up the version as it's the last change I want to push to the Apache integration.

**Review by ycombinator — APPROVED** [review]
LGTM. WFG.

**Comment by mtojek** [comment]
jenkins run the tests please

**Pull request merged**
