### PR TITLE
[Network Traffic] Add Dashboards

### LINKED ISSUE #2169: Network Packet Capture Dashboards
Our experimental NPC integration currently lacks dashboards. Existing Packetbeat dashboards needs to be migrated to Lens and included with the NPC integration. The Packbeat dashboards also use old maps, which need to be updated also - https://github.com/elastic/beats/issues/26015

- [ ] [Network Packet Capture - DNS Tunneling](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/DNS-Unique-Domains-ecs.json)
- [ ] [Network Packet Capture - DNS Overview](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/65120940-1454-11e9-9de0-f98d1808db8e-ecs.json)
- [ ] [Network Packet Capture - Cassandra](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-Cassandra-ecs.json)
- [ ] [Network Packet Capture - Overview](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-Dashboard-ecs.json)
- [ ] [Network Packet Capture - Flows](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-Flows-ecs.json)
- [ ] [Network Packet Capture - HTTP](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-HTTP-ecs.json)
- [ ] [Network Packet Capture - MongoDB](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-MongoDB-performance-ecs.json)
- [ ] [Network Packet Capture - MySQL Performance](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-MySQL-performance-ecs.json)
- [ ] [Network Packet Capture - Network File System](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-NFS-ecs.json) | [Bug](https://github.com/elastic/beats/issues/19547#event-5635140638) to consider fixing. 
- [ ] [Network Packet Capture - PostgreSQL Performance ](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-PgSQL-performance-ecs.json)
- [ ] [Network Packet Capture - Thrift Performance](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-Thrift-performance-ecs.json) 
- [ ] [Network Packet Capture - DHCP Overview](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/a7b35890-8baa-11e8-9676-ef67484126fb-ecs.json)
- [ ] [Network Packet Capture - TLS Sessions ](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/tls-sessions-ecs.json)

### PR DESCRIPTION
**Pull request by leehinman**
## What does this PR do?

Adds Packetbeat dashboards to network traffic integration

Changes made to Packetbeat dashboards:

- change index from packetbeat-* to log-*
- rename files to match package-spec
- remove ECS string from all titles
- change "packetbeat" to "Newtwork Packet Capture" in titles
- add data_stream.dataset query to limit data searched
- use query of "agent.type:packetbeat" to get data across data_streams
- convert tile_map objects to map
- exported from a 7.17.0 ES instance

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #2169

## Screenshots
Screen Shot 2022-03-02 at 14 06 02
Screen Shot 2022-03-02 at 14 07 09
Screen Shot 2022-03-02 at 14 07 19
Screen Shot 2022-03-02 at 14 07 27
Screen Shot 2022-03-02 at 14 07 38
Screen Shot 2022-03-02 at 14 07 48
Screen Shot 2022-03-02 at 14 07 57
Screen Shot 2022-03-02 at 14 08 06
Screen Shot 2022-03-02 at 14 08 13
Screen Shot 2022-03-02 at 14 08 23
Screen Shot 2022-03-02 at 14 08 47

### CODE REVIEW

**Review by andrewkroh — COMMENTED** [review]
LGTM. Can you put into the PR description what changes were made since bringing in the dashboards from Packetbeat.

**Comment by efd6** [comment]
Is it possible to express the network durations in millis rather than nanos? For example DNS query times and handshake latency.

**Comment by leehinman** [comment]
> Is it possible to express the network durations in millis rather than nanos? For example DNS query times and handshake latency.

For this I think we should convert the visualizations to lens, and I'd like to do that in a second PR.  Also any other changes.

**Review by andrewkroh — APPROVED** [review]

**Comment by leehinman** [comment]
> any chance of dropping agent.type:packetbeat from the query to provide visualizations that work with any packet level information that complies with ECS? On a similar note, would we expect other solutions / integrations to be using the network_traffic dataset for equivalent ifnormation?

I like the idea of visualizations that use ECS to span multiple data sources.  There is the possibility of counting connections multiple times though.  For example, network traffic integration might capture a tls connection and apache integration might also have a log for the same connection.  Maybe it would be a good idea to have this be something we can toggle on or off?

**Comment by dainperkins** [comment]
Grouping sure would be handy... even if it's not apache, multiple observers could very well do the same.  adding a drop down to select specific (thinking out loud, so to speak...) modules, or datasets, or potentially even agents / observers would probably do the trick...  (thinking the agents / observers would be the most irritating, as the members of the 2 groups will be distinct)

**Pull request merged**
