### PR TITLE
Fix EventID's for "Users Added to Group" panel

### LINKED ISSUE #6275: [System][Windows] "Users Added to Group" panel has incorrect filter
Kibana > Dashboard > `[System Windows Security] Group Management Events` > `Users Added to Group` has the following filter:

https://github.com/elastic/integrations/blob/41f59833ebc81d1c5a83902f1a3cd3683d335b3f/packages/system/kibana/dashboard/system-bb858830-f412-11e9-8405-516218e3d268.json#L3951

**Issue**: The listed event IDs are for group creations as per the MS doc below.

> https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/appendix-l--events-to-monitor
> 4731 635 Low A security-enabled local group was created.
> 4727 631 Medium A security-enabled global group was created.
> 4754 658 Medium A security-enabled universal group was created.
> 4749 653 Low A security-disabled global group was created.
> 4759 663 Low A security-disabled universal group was created.
> 4744 648 Low A security-disabled local group was created.
> 4783 667 Low A basic application group was created.
> 4790 694 Low An LDAP query group was created.

**Proposal**: The filter should consists of the following event IDs to show user additions.

> https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/appendix-l--events-to-monitor
> 4732 636 Low A member was added to a security-enabled local group.
> 4728 632 Low A member was added to a security-enabled global group.
> 4756 660 Low A member was added to a security-enabled universal group.
> 4751 655 Low A member was added to a security-disabled global group.
> 4761 665 Low A member was added to a security-disabled universal group.
> 4746 650 Low A member was added to a security-disabled local group.
> 4785 689 Low A member was added to a basic application group.
> 4787 691 Low A nonmember was added to a basic application group.

**Note**: These proposed event IDs are identical with the ones used in `Users Added - Table [Windows System Security]` following this panel.

https://github.com/elastic/integrations/blob/25a4f35a4ea15cb18cbad06f8741055a15102306/packages/system/kibana/dashboard/system-bb858830-f412-11e9-8405-516218e3d268.json#L1181

### PR DESCRIPTION
**Pull request by sakurai-youhei**
Fixes #6275

https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/appendix-l--events-to-monitor
4732 636 Low A member was added to a security-enabled local group.
4728 632 Low A member was added to a security-enabled global group.
4756 660 Low A member was added to a security-enabled universal group.
4751 655 Low A member was added to a security-disabled global group.
4761 665 Low A member was added to a security-disabled universal group.
4746 650 Low A member was added to a security-disabled local group.
4785 689 Low A member was added to a basic application group.
4787 691 Low A nonmember was added to a basic application group.

## What does this PR do?

Change Event ID's set to the filter in "Users Added to Group" panel.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

Rewrite the numbers manually in the Lens.

## Related issues

- Fixes #6275

## Screenshots

Kibana > Dashboard > `[System Windows Security] Group Management Events` > `Users Added to Group`

**Before change**
image

**After change**
image

### CODE REVIEW

**Comment by efd6** [comment]
There is currently a beta version in play for the promotion of TSDB to GA, so this PR should wait for that to have gone in before it's updated and merged.

/cc @tetianakravchenko

**Comment by ebeahan** [comment]
Are these changes able to move forward with `1.34.0` released in https://github.com/elastic/integrations/pull/6607?

**Comment by sakurai-youhei** [comment]
@ebeahan Is that change bumping up to `1.34.1` ok?

/test

**Review by efd6 — APPROVED** [review]

**Comment by sakurai-youhei** [comment]
The same issue here. https://github.com/elastic/integrations/pull/6607#issuecomment-1600691907 Because elastic-package v0.83.2 was released with the fix - https://github.com/elastic/elastic-package/pull/1315 20 hours ago, I'm attempting the test again.

**Comment by efd6** [comment]
@sakurai-youhei Are you able to merge?

**Comment by sakurai-youhei** [comment]
@efd6 No, The merge button is still diactive and it says:

> Waiting on code owner review from elastic/elastic-agent-data-plane, elastic/kibana-visualizations, and/or elastic/obs-infraobs-integrations.

Could you give another approval from either? Thanks.

**Comment by efd6** [comment]
Sorry, I missed that there are different owners across multiple files.

**Comment by efd6** [comment]
@elastic/elastic-agent-data-plane, @elastic/kibana-visualizations and @elastic/obs-infraobs-integrations would you be able to take a look please.

**Review by cmacknz — APPROVED** [review]

**Review by ishleenk17 — APPROVED** [review]
Loks good!

**Pull request merged**
