### PR TITLE
[eset_protect][imperva_cloud_waf][sentinal_one_cloud_funnel][ti_crowdstrike] Use modern ecs@mappings

### PR DESCRIPTION
**Pull request by chrisberkhout**
## Proposed commit message

```
[eset_protect][imperva_cloud_waf][sentinal_one_cloud_funnel][ti_crowdstrike] Use modern ecs@mappings (#)

- Remove `dependencies.ecs.import_mappings: true`.
- Set `8.13` as the minimum stack version.
```

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates #9192

### CODE REVIEW

**Review by ShourieG — APPROVED** [review]
LGTM

**Comment by andrewkroh** [comment]
@chrisberkhout For future reference, you probably want a shorter git commit summary line. The summary of this [commit](https://github.com/elastic/integrations/commit/ae85e390cdf325be483789f522acc81e40d791e8) was truncated. 

https://kortschak.io/courses/git_workshop/communication/#commit-messages

**Comment by joshFive** [comment]
Should this release also have the kibana 8.13.0 requirement added on the download page?

**Comment by chrisberkhout** [comment]
Hi @joshFive,

The updated metadata will show up, for example [here](https://www.elastic.co/docs/current/integrations/eset_protect) you'll see "Compatible Kibana version(s): 8.13.0 or higher".

However, I noticed that all of these integrations had a hard-coded Kibana version number mentioned in the README. I've opened a PR to remove those so that the version constraints are in one place only, as we have it for many other integrations: https://github.com/elastic/integrations/pull/10182

**Pull request merged**
