### PR TITLE
Seagate's Lyve Cloud plugin to elastic

### PR DESCRIPTION
**Pull request by leon-seagate**
- Enhancement

## What does this PR do?

- Added new directory under packages for new cloud provider - a.k.a Seagate's Lyve Cloud.
- Added data collection logic for the data streams.
- Added the ingest pipeline for the data streams.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yaml files.
- Added dashboards and visualizations.
- Added system test cases for the data stream.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Screenshots
image

### CODE REVIEW

**Comment by jamiehynds** [comment]
@marc-gr Seagate have now signed the CLA, which I assume should now allow @leon-seagate to proceed. Could you run the CLA Checker again and see if we're now unblocked?

**Comment by marc-gr** [comment]
It still appears as not signed, @leon-seagate can you confirm the email used to sign the commits and the email used to sign the CLA is the same?

**Comment by leon-seagate** [comment]
the mail of which I've signed the commits is the same as the mail mentioned in the CORPORATE CLA under "Contributing Employee email" column in "Schedule A" table.

**Comment by gtback** [comment]
cla/check

**Pull request closed without merging**
