### PR TITLE
[Logstash] Fix node cel script type checking issue

### PR DESCRIPTION
**Pull request by robbavey**
An update to the cel-go library added stricter type checking, and made certain overload operations invalid in CEL scripts. This is a work-around to "hide" the type in an array, until a better fix is available.

Closes: #9546,#9319

### CODE REVIEW

**Comment by robbavey** [comment]
Test failure looks like an instance of #9366, which is a known bug for Logstash - I believe it is an instance of https://github.com/elastic/logstash/issues/14335

**Review by efd6 — APPROVED** [review]
CEL code LGTM

**Review by miltonhultgren — APPROVED** [review]

**Comment by IanLee1521** [comment]
FYI -- I can confirm this fixed the metrics not coming in issue I reported to support: https://support.elastic.co/cases/500Vv000002ryV2IAI

**Comment by efd6** [comment]
@IanLee1521 Thank you for the report, it has spurred additional work that is resolving the issue at a deeper level as well.

**Comment by IanLee1521** [comment]
Glad to hear! Feel free to ping me if you need any additional testing. Cheers.

**Comment by robbavey** [comment]
@IanLee1521 Thanks for the report, and the testing. Please feel free to reach out to me with any feedback you have with this issue, or the integration in general

**Comment by IanLee1521** [comment]
@robbavey -- happy to! I pinged you on the community Slack, but just let me know if there is a better way to connect up.

**Pull request merged**
