### PR TITLE
[RedisEnterprise] Enable TSDB

### LINKED ISSUE #6268: [Redis Enterprise] TSDB Enablement
## Test Environment Setup
- [x] Creation of Redis Enterprise Test Environment

## Datastream : node 
  - [x] Add dimension fields
         https://github.com/elastic/integrations/pull/8091
  - [x] Adding metric_type mapping
          https://github.com/elastic/integrations/pull/8133
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if dimension field mapping is correct in the data stream template.

## Datastream : proxy
  - [x] Add dimension fields 
         https://github.com/elastic/integrations/pull/8148
  - [x] Adding metric_type mapping
         https://github.com/elastic/integrations/pull/8539
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.

Tsdb Enablement PR: https://github.com/elastic/integrations/pull/8584

### PR DESCRIPTION
**Pull request by ritalwar**
## Proposed commit message

This PR enables TSDB for RedisEnterprise.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #6268 

## Screenshots

Screenshot 2023-11-28 at 2 37 09 PM

### CODE REVIEW

**Review by harnish-elastic — COMMENTED** [review]
Observation:

The dashboard visualizations have static intervals as `1m` rather than `Auto`. Is this intentional? 

image

**Comment by harnish-elastic** [comment]
The visualization `Total client connections` has an `average` operation type which seems inappropriate. Can you check if we can use `last_value` instead of `average`!

**Comment by ritalwar** [comment]
> The dashboard visualizations have static intervals as `1m` rather than `Auto`. Is this intentional?

This was implemented within this [PR](https://github.com/elastic/integrations/pull/5678). For TSDB migration tests, I only verified if visualizations display data correctly or appear distorted. Perhaps @rajvi-patel-22  can provide insights into why "1m" was chosen over "Auto."

**Comment by ritalwar** [comment]
> The visualization `Total client connections` has an `average` operation type which seems inappropriate. Can you check if we can use `last_value` instead of `average`!

Could you please create a separate issue and add it to the backlog for implementing the right aggregator functions in visualizations? 
Let's keep the TSDB enablement separate.

**Comment by harnish-elastic** [comment]
> > The visualization `Total client connections` has an `average` operation type which seems inappropriate. Can you check if we can use `last_value` instead of `average`!
> 
> Could you please create a separate issue and add it to the backlog for implementing the right aggregator functions in visualizations? Let's keep the TSDB enablement separate.

Created a separate issue as per observation: https://github.com/elastic/integrations/issues/8603!

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
