### PR TITLE
[WIP] Introduce syslog package with different dataset types

### PR DESCRIPTION
**Pull request by urso**
This WIP PR introduces the syslog package, that supports the logs and the syslog input. Available datasets are:
- local: use logs input to collect syslog files from disk (duplicates the syslog dataset from the system package)
- tcp: start tcp server
- udp: start udp server
- unix: start unix (stream based) socket server

I also started an alternative implementation for the syslog package as a dataset only within the logs package: #112 

There is quite some overlap with the system's package syslog input, as we share the ingest pipeline. Can packages have a dependency on other packages?

### CODE REVIEW

**Comment by ruflin** [comment]
Packages can't have dependencies on others at the moment (by design) to remove this complexity.

My thinking around the different input types was having one package per type. You combined them here, could you share a bit more on they way you see users using this?

**Comment by urso** [comment]
In Filebeat we have input-source and inputs. An input can have different input sources. Especially syslog can be transmitted via: TCP, UDP, unix streaming socket, unix datagram socket. If a syslog server is in place we also have the option to collect the same logs from disk. In this sense the `syslog` input in Beats is no traditional input type. This is reflected in this package by creating a source per input type, allowing the user to select which kind of syslog server they want to start by using the correct dataset. I originally started with one dataset, but decided to split them, because different input sources support a different set of settings (not all are exposed yet). e.g. unix sockets require a path to be configured only (but also allow for permissions). TCP sockets have settings for splitting the input stream and TLS.

**Comment by ruflin** [comment]
I'm torn about the `local` collection fo syslog files where it should go. It uses the `logfile` (currently log) input and not the syslog one so it only fits half in here.

There is an alternative way here (not supported yet in Kibana). We could specify 3-4 datasources, one for each entry you have above. Now when the user selects the syslog package, first thing he needs to do is pick one of the above options in a dropdown and then will only have the config options available to the specific input.

**Comment by urso** [comment]
> I'm torn about the local collection fo syslog files where it should go. It uses the logfile (currently log) input and not the syslog one so it only fits half in here.

Still, syslog is the service. It just allows for multiple transport. Does syslog even make sense in the system package, where journald/winlogevents would actually make more sense?

> There is an alternative way here (not supported yet in Kibana). We could specify 3-4 datasources, one for each entry you have above. Now when the user selects the syslog package, first thing he needs to do is pick one of the above options in a dropdown and then will only have the config options available to the specific input.

Syslog is more or less independent of the transport being used. Personally I'd prefer to be able to configure TCP, UDP and Unix datagram sockets once (in order to replace the local syslog server), instead of being required to configure the package multiple times with different datasources. Doesn't the package also act as some kind of grouping mechanism?

**Comment by ruflin** [comment]
If I look at `local`, it uses the `logs` input and not syslog: https://github.com/elastic/integrations/pull/111/files#diff-89c2859d32f11eeb9e58850f97e581bbR6

It is possible to configure them all together if we want. In the end, it means the Agent would start 3 inputs, correct?

**Comment by urso** [comment]
> If I look at local, it uses the logs input and not syslog

Correct. But the package is named `syslog`, and the ingest node pipeline is configured to parse `syslog`. I don't expect the package to reflect available inputs in filebeat 1 by one. To me it just feels natural to group generic syslog based collection into a single package, no matter where the logs come from (custom server or logs). Or do you plan to introduce a `logs` package with syslog dataset (we already got one in system module)?

> It is possible to configure them all together if we want. In the end, it means the Agent would start 3 inputs, correct?

correct.

**Comment by ruflin** [comment]
The nice things about the package is that we can provide more then 1 way / package to run the same input. So perhaps it is not either / or?

**Comment by mtojek** [comment]
I'm afraid this PR is not compliant with latest changes in the Integrations. I'll close it.

**Pull request closed without merging**
