### PR TITLE
[cisco_umbrella] Update to v8 format proxy logs

### PR DESCRIPTION
**Pull request by LaZyDK**
## What does this PR do?

Added `Isolate Action`, `File Action`, `Warn Status` fields required to consume v8 Proxy logs:
[Link to documentation.](https://docs.umbrella.com/deployment-umbrella/docs/log-formats-and-versioning#section-order-of-fields-in-proxy-log-record)

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by LaZyDK** [comment]
My mistake.

**Review by andrewkroh — APPROVED** [review]
LGTM. The new pattern appears backward compatible.

**Pull request merged**
