### PR TITLE
Nginx Integration Controller: Add "error" data stream

### PR DESCRIPTION
**Pull request by mtojek**
## What does this PR do?

This PR introduces a new data stream for Nginx Integration Controller which can process application/error logs.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [x] I have verified that all datasets collect metrics or logs.

## How to test this PR locally

The CI will verify if it works correctly.

## Related issues

- Closes https://github.com/elastic/integrations/issues/467

## Screenshots

nginx-ingress-controller-access-error-logs
nginx-ingress-controller-overview

### CODE REVIEW

**Comment by mtojek** [comment]
jenkins run the tests please

**Comment by mtojek** [comment]
jenkins run the tests please

**Comment by mtojek** [comment]
jenkins run the tests please

**Review by ChrsMark — COMMENTED** [review]
Really happy to see this package getting completed! Thanks!

It looks good already, some minor suggestions:
1. Visualisations tittles can possibly omit `[Logs Nginx Ingress Controller]` suffix. Usually we just edit the viewable title to omit this, and preserve the original tittle as is. You can see `nats` package as an example. This makes the view more clear.
2. One visualisation I would add would be a distribution of warnings/errors per source file.
3. Maybe a distribution of warning/errors over time could be helpful here.

The last two suggestions can be implemented/evaluated in a different issue/PR. Let me know what you think.

**Comment by mtojek** [comment]
These are good suggestions and don't look though. I will adjust dashboards then.

**Comment by mtojek** [comment]
@ChrsMark I've just addressed your comments:

screencapture-localhost-5601-app-dashboards-2020-12-17-15_00_57
screencapture-localhost-5601-app-dashboards-2020-12-17-15_02_04

Please re-review the PR whenever you're free.

**Review by ChrsMark — APPROVED** [review]
lgtm, thanks!

**Comment by mtojek** [comment]
Thank you too!

**Pull request merged**
