### PR TITLE
Update terraform lock files in aws package

### PR DESCRIPTION
**Pull request by mrodm**
## Proposed commit message

~Remove Terraform lock files so tests are executed with the latest versions of the providers.~

~If it is required to set specific versions, probably it could be used https://developer.hashicorp.com/terraform/language/providers/requirements#requiring-providers~

According to this issue https://github.com/elastic/integrations/issues/2661 , these lock files were added to ensure reproducible installations. This PR updates these lock files so CI uses the latest version at this moment. 

All the other data streams in `aws` package do not have this file committed.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## Related issues

-

### CODE REVIEW

**Comment by mrodm** [comment]
@elastic/obs-ds-hosted-services @elastic/obs-infraobs-integrations WDYT about removing these lock files (`*.lock.hcl`) to allow using latest version of the provider (currently the latest version is `5.37.0`) ? 

These data streams were using old versions 4.18.0 and 4.0.0 of the provider because of those lock files.

**Review by kaiyan-sheng — APPROVED** [review]
I don't think we lock the version for a specific reason... approving this PR.

**Comment by mrodm** [comment]
Thanks @kaiyan-sheng !

@elastic/obs-infraobs-integrations any inconvenient to remove the lock file (`*.lock.hcl`) in the `redshift` data stream ?

**Comment by mrodm** [comment]
Found this issue where these lock files were added https://github.com/elastic/integrations/issues/2661 (thanks @jsoriano)

I've updated this PR to include those lock files again , but with the latest versions. Run `terraform init` in those `_dev/deploy/tf` folder to create those files again. cc @kaiyan-sheng


Updated PR description

**Review by jsoriano — APPROVED** [review]
:+1:

**Review by kaiyan-sheng — APPROVED** [review]
Good to know! Thanks!

**Pull request merged**
