### PR TITLE
azure metrics: add list of supported databases and namespaces

### PR DESCRIPTION
**Pull request by zmoog**
## Proposed commit message

Add the list of databases and namespaces supported by the Azure Database Account integration.

Set the right expectations about the namespaces and supported databases. Without this list, users may expect this integration to support all database types available in Azure.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] ~~I have verified that all data streams collect metrics or logs.~~
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] ~~I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).~~

### CODE REVIEW

**Review by Kavindu-Dodan — APPROVED** [review]

**Comment by muthu-mps** [comment]
@zmoog  - Just a question around the integration name, Can we rename this integration to `Azure Cosmos DB` if it is appropriate. Because this is the right name I can find in the Azure services. WDYT?

**Review by alaudazzi — APPROVED** [review]
LGTM

**Review by muthu-mps — APPROVED** [review]
LGTM!

**Comment by muthu-mps** [comment]
> @zmoog - Just a question around the integration name, Can we rename this integration to `Azure Cosmos DB` if it is appropriate. Because this is the right name I can find in the Azure services. WDYT?

We can take this separately.

**Comment by zmoog** [comment]
> > @zmoog - Just a question around the integration name, Can we rename this integration to `Azure Cosmos DB` if it is appropriate. Because this is the right name I can find in the Azure services. WDYT?
> 
> We can take this separately.

Good point. 

I'm opening a dedicated issue to discuss this topic! I need to do some research.

**Pull request merged**
