### PR TITLE
elastic_agent: changes for unified integration UI

### PR DESCRIPTION
**Pull request by endorama**
## What does this PR do?

Align package title and description for improved Unified Integration UI display.

## Checklist

- [ ] ~~I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.~~
- [ ] ~~I have verified that all data streams collect metrics or logs.~~
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] ~~If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).~~

## Author's Checklist

- [ ] promote package to staging
- [ ] promote package to production

## Related issues

- Part of https://github.com/elastic/integrations/issues/1901

### CODE REVIEW

**Comment by ruflin** [comment]
The elastic_agent packages collects logs and metrics from the Elastic Agent, see https://github.com/elastic/integrations/tree/master/packages/elastic_agent/data_stream I assume this should be mentioned in the title?

**Comment by ruflin** [comment]
@endorama @akshay-saraswat ^

**Comment by endorama** [comment]
@akshay-saraswat I'm going to change this to: `Elastic Agent - Collect logs and metrics from Elastic Agents.` similar to other integrations that behave in the same way.

**Comment by ruflin** [comment]
@endorama I have currently a PR open for Elastic Agent and can take care of it directly. Ok for you? https://github.com/elastic/integrations/pull/2125

**Comment by endorama** [comment]
Yes please! Thank you

**Pull request merged**
