### PR TITLE
Add missing internal packagees

### PR DESCRIPTION
**Pull request by mtojek**
This PR adds missing but mandatory internal packages.

### CODE REVIEW

**Comment by ruflin** [comment]
I'm ok to add these here for now at the same time I don't think they belong here. In the future they should be pulled in from a remote source during build time to only have a single point of truth.

**Comment by mtojek** [comment]
> I'm ok to add these here for now at the same time I don't think they belong here. In the future they should be pulled in from a remote source during build time to only have a single point of truth.

I can adjust it in the follow-ups. Could you please link me to the right location (source of truth)?

**Comment by ruflin** [comment]
Today, EPR is the source of truth. In the near future it should be package-storage.

**Comment by mtojek** [comment]
@ruflin 

1. Would you prefer to approve this as is and let me adjust in next follow-ups  or it's better to do now?
2. Which way do you think is better? git clone the package-registory (package-store in the future), fetch data from https://epr.elastic.co/, extract from docker image.

I need to simply mount a volume with custom package. If I need to update the package, I don't need to rebuild/restart docker containers.

**Comment by ruflin** [comment]
For the future, I think the best path is to get it out of the package-storage. Like this you have what is currently deployed + your packages on top of it.

**Comment by mtojek** [comment]
> For the future, I think the best path is to get it out of the package-storage. Like this you have what is currently deployed + your packages on top of it.

Sounds good.

**Pull request merged**
