### PR TITLE
[System] Add custom configuration option to winlog inputs

### PR DESCRIPTION
**Pull request by user-987654321**
## Proposed commit message

Adding the ability for users to set custom yaml config for windows datastream (System, Application, Security) winlog inputs.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## Related issues

- 

## Screenshots

custom-system

### CODE REVIEW

**Review by andrewkroh — APPROVED** [review]
LGTM. Appears to be consistent with #8877.

**Comment by ishleenk17** [comment]
@andrewkroh : Please see if we would like to proceed with this change. I had one concern as mentioned [here](https://github.com/elastic/integrations/pull/9045#issuecomment-2036488600).

**Comment by andrewkroh** [comment]
> Hence, increasing the likelihood of integration breakages. Would it be better to give a specific yaml box for the requirement like we do for say SSL.

This is true given that there is no validation of the YAML. But I don't think scoping the YAML to one setting (like `ssl: {{ssl}}`) is any better because no matter where the invalid YAML is placed it will break the configuration. It's the same problem that exists for `processors`. So I don't think this drastically increases the risk of invalid configurations.

I would like to see us build a UI component that encapsulates all of the winlog input settings. It would encode all of the validation rules like mutual exclusivity between options, provide type-ahead for the most common channel names, and do validiton of the processors YAML based on json-schema. This would be a better UX and reduce this risk of saving an invalid config.

**Review by ishleenk17 — APPROVED** [review]

**Pull request merged**
