### PR TITLE
[mimecast] audit events - add additional email fields

### PR DESCRIPTION
**Pull request by djordje-adzemovic-devtech**
## What does this PR do?

Add new use case in pipeline for audit events, set email.direction as lowercase, set geo.ip for siem logs and for ttp-url logs email.to.adress and remove user data

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by andrewkroh** [comment]
This will need to be updated after https://github.com/elastic/integrations/pull/2841 is merged as it includes some of the same commits.

**Comment by andrewkroh** [comment]
@djordje-adzemovic-devtech You can rebase this on `main` now that the other PR is merged.

**Comment by djordje-adzemovic-devtech** [comment]
I will close this PR I made a new one since rebase cause a lot of conflicts which are hard to resolve.

**Comment by djordje-adzemovic-devtech** [comment]
I will close this PR since rebase cause a lot of conflicts which are hard to resolve.

**Comment by djordje-adzemovic-devtech** [comment]
This is new PR:
https://github.com/elastic/integrations/pull/3116

**Pull request closed without merging**
