### PR TITLE
[citrix_adc] Handle time zone parsing in sslvpn_and_aaatm_feature pipeline

### PR DESCRIPTION
**Pull request by mjwolf**
## Proposed commit message

This has a few pipeline improvements

* Fail if sslvpn_and_aaatm_feature message data cannot be parsed. If this data is not parsed, most data provided by this pipeline is silently not populated. So I think overall its better to fail, so that users and developers are more aware that there is an error.
* Improve parsing of the message to handle optional space between username and Group key. Both formats have been observed.
* Handle the presence of time zone in the message timestamp.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Review by pkoutsovasilis — COMMENTED** [review]
manifest needs to get updated as well? also this isn't a sec-deployment-and-devices integration?! or at least the .github/CODEOWNERS does not say so

**Comment by mjwolf** [comment]
> manifest needs to get updated as well? also this isn't a sec-deployment-and-devices integration?! or at least the .github/CODEOWNERS does not say so

I've updated the manifest. And yeah, I guess we don't own this. It seems like an integration we'd own, and I didn't check before working on it

**Comment by pkoutsovasilis** [comment]
> > manifest needs to get updated as well? also this isn't a sec-deployment-and-devices integration?! or at least the .github/CODEOWNERS does not say so
> 
> I've updated the manifest. And yeah, I guess we don't own this. It seems like an integration we'd own, and I didn't check before working on it

definitely no worries, I see no issue with that! just checking if my eyes were deceiving me

**Review by pkoutsovasilis — APPROVED** [review]
LGTM

**Comment by shmsr** [comment]
Changes look good, but I noticed a spelling error: "received" is misspelled as "recieved" in some places while reviewing. But it is unrelated to the change made here.

**Review by shmsr — APPROVED** [review]

**Comment by muthu-mps** [comment]
@mjwolf - The citrix_waf integration also does processing the logs for citrix_adc. Do you consider validating the scenario with the WAF integration as well?

**Pull request merged**
