### PR TITLE
Fixes to Readme files

### PR DESCRIPTION
**Pull request by cherryleaf**
## What does this PR do?

Amendments as per https://docs.google.com/document/d/1moVUo7eRqfgic-fgqYKKT7Fo4iQlI5w5W4CYiNSodk4/edit

- Added Overview headings
- Added hyperlink to and hyperlink to the documentation for the product that's being integrated
 
## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by mtojek — COMMENTED** [review]
Could you please open a PR per integration instead? We're trying to prevent big bulk pull requests.

**Review by bmorelli25 — COMMENTED** [review]
Congrats on your first PR, Ellis! A few thoughts:

* Let's remove the newly added `## Overview` headings from the readme files. These files are built both in Kibana and in our documentation. It adds clutter in the former, and we can programmatically add them in the latter.
* It looks like only the `/_dev/build/docs/README.md` files were edited in this PR. Don't forget to run the `elastic-package build` command to build the readme file prior to opening a PR.
* For the changelog files, you can edit the PR number in after opening the PR directly in GitHub if you'd like.

**Comment by cherryleaf** [comment]
I tried to build one of the packages. I got this error: 
```
cex@Ellis-13-MacBook-Air carbonblack_edr % elastic-package build
2022/03/25 15:05:22 INFO New version is available - v0.42.0. Download from: https://github.com/elastic/elastic-package/releases/tag/v0.42.0
Build the package
README.md file rendered: /Users/cex/Documents/GitHub/integrations/packages/carbonblack_edr/docs/README.md
Error: building package failed: invalid content found in built package: found 1 validation error:
  1. current manifest version doesn't have changelog entry 
```
I had updated the changelog.yml file in the carbonblack directory.






[3:10](https://elastic.slack.com/archives/C036AQU4ENP/p1648221047172999)
Any suggestions on how to fix this error?

**Comment by cherryleaf** [comment]
I amended the manifest.yml files and successfully ran `elastic-package build `

**Comment by cherryleaf** [comment]
I'll resubmit the changes as separate Pull Requests.

**Pull request closed without merging**
