### PR TITLE
Cleanup: Remove unused minimum_should_match parameter in bool query

### PR DESCRIPTION
**Pull request by nc-sec**
Type of change
Enhancement.

Proposed commit message
This PR removes the minimum_should_match which isn't an attribute of a should. Reference to the minimum_should_match parameter from the [Bool Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html#bool-min-should-match) documentation page. The parameter is not applicable in the context provided and could lead to confusion.

WHAT: The change involves removing the snippet that incorrectly suggests minimum_should_match is directly usable within the bool query context. This parameter does not have an effect in this context and its presence is misleading.

WHY: The rationale behind this change is to clarify the qry and avoid potential confusion among Elasticsearch users. By cleaning up the qry, we ensure that users are not misled into using parameters in contexts where they have no effect. This contributes to a clearer understanding of how to properly construct queries in Elasticsearch.

Checklist
 I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
 I have verified that all data streams collect metrics or logs.
 I have added an entry to my package's changelog.yml file.
 I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
Author's Checklist
 Ensure that the removal of minimum_should_match does not contradict any other parts of the documentation.
 Verify that the documentation structure remains consistent post-removal.
How to test this PR locally
To test this documentation change locally, you can build the docs using the Elastic documentation build process, ensuring that the removal of the minimum_should_match parameter does not introduce formatting or structural issues.

Related issues
None
Screenshots
N/A

### CODE REVIEW

**Review by qn895 — APPROVED** [review]

**Comment by qn895** [comment]
ML changes LGTM 🎉

**Comment by sodhikirti07** [comment]
@nc-sec The positioning of the `minimum_should_match` parameter is accurate, and it was included to enhance the performance of the `terms` filters. That being said, I don't see any reason to eliminate this parameter.

**Comment by pantea-elastic** [comment]
Based on https://github.com/elastic/integrations/pull/9534#issuecomment-2061487705 the parameter is in use so I will close the PR.

**Comment by nc-sec** [comment]
> @nc-sec The positioning of the `minimum_should_match` parameter is accurate, and it was included to enhance the performance of the `terms` filters. That being said, I don't see any reason to eliminate this parameter.

Yup, you are 100% correct. I normally place it after the 'should' block. Guess it's more of a style thing that threw me off.

**Pull request closed without merging**
