### PR TITLE
system: convert dashboard visualisations to store by value

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

This updates visualisations to store by value.

The operations used are shown in the `git-generate` script in the commit message and can be confirmed (slowly) by running [`git generate`](https://pkg.go.dev/rsc.io/rf/git-generate).

Output of script from point of cloning the conversion tool.
<details>
<pre>
Cloning into 'legacy_vis_analyzer'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 12 (delta 0), reused 5 (delta 0), pack-reused 0
Receiving objects: 100% (12/12), 11.94 KiB | 643.00 KiB/s, done.
Submodule 'beats' (https://github.com/elastic/beats) registered for path 'beats'
Submodule 'integrations' (https://github.com/elastic/integrations) registered for path 'integrations'
Submodule 'kibana' (https://github.com/elastic/kibana) registered for path 'kibana'
Cloning into '/Users/daniel/go/src/github.com/elastic/integrations/packages/system/legacy_vis_analyzer/beats'...
Cloning into '/Users/daniel/go/src/github.com/elastic/integrations/packages/system/legacy_vis_analyzer/integrations'...
Cloning into '/Users/daniel/go/src/github.com/elastic/integrations/packages/system/legacy_vis_analyzer/kibana'...
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: Enumerating objects: 2269, done.
remote: Counting objects: 100% (2269/2269), done.
remote: Compressing objects: 100% (1100/1100), done.
remote: Total 1366 (delta 893), reused 494 (delta 210), pack-reused 0
Receiving objects: 100% (1366/1366), 2.09 MiB | 2.80 MiB/s, done.
Resolving deltas: 100% (893/893), completed with 614 local objects.
From https://github.com/elastic/beats
 * branch              b83248684299976dd4630064d6c1f7413e945f3b -> FETCH_HEAD
Submodule path 'beats': checked out 'b83248684299976dd4630064d6c1f7413e945f3b'
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: Enumerating objects: 11640, done.
remote: Counting objects: 100% (11640/11640), done.
remote: Compressing objects: 100% (4507/4507), done.
remote: Total 9089 (delta 4407), reused 6437 (delta 2905), pack-reused 0
Receiving objects: 100% (9089/9089), 11.91 MiB | 3.00 MiB/s, done.
Resolving deltas: 100% (4407/4407), completed with 724 local objects.
From https://github.com/elastic/integrations
 * branch              a3639be8de8b6f564644c6a9afc93170a2b915ef -> FETCH_HEAD
Submodule path 'integrations': checked out 'a3639be8de8b6f564644c6a9afc93170a2b915ef'
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: Enumerating objects: 33054, done.
remote: Counting objects: 100% (33054/33054), done.
remote: Compressing objects: 100% (18606/18606), done.
remote: Total 22258 (delta 12214), reused 9539 (delta 3140), pack-reused 0
Receiving objects: 100% (22258/22258), 28.54 MiB | 2.20 MiB/s, done.
Resolving deltas: 100% (12214/12214), completed with 7951 local objects.
From https://github.com/elastic/kibana
 * branch                7a3243b79fbc309875490e1477a3d97b80854676 -> FETCH_HEAD
Submodule path 'kibana': checked out '7a3243b79fbc309875490e1477a3d97b80854676'
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 0.64s.
(node:37532) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Prepared 45 visualizations to be inlined
Processing dashboard [System Windows Security] Group Management Events - Simple Metrics
Inlined a vis, pushed 0 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Leaving panel of type search
Leaving panel of type search
Inlined a vis, pushed 0 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Processing dashboard [System Windows Security] User Logons - Simple Metrics
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 0 inner references
Leaving panel of type search
Inlined a vis, pushed 0 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 1 inner references
Leaving panel of type search
Inlined a vis, pushed 2 inner references
Leaving panel of type search
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Processing dashboard [Logs System] New users and groups
Inlined a vis, pushed 0 inner references
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Processing dashboard [Logs System] Sudo commands
Inlined a vis, pushed 0 inner references
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Processing dashboard [Logs System] SSH login attempts
Leaving panel of type search
Inlined a vis, pushed 0 inner references
Leaving panel of type map, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Processing dashboard [System Windows Security] User Management Events
Inlined a vis, pushed 0 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Leaving panel of type search
Leaving panel of type search
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 0 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Processing dashboard [Metrics System] Host overview
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type lens, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type lens, seems to be inlined already
Leaving panel of type lens, seems to be inlined already
Leaving panel of type lens, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type lens, seems to be inlined already
Leaving panel of type lens, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type lens, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type lens, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Processing dashboard [System Windows Security] User Management Events - Simple Metric
Inlined a vis, pushed 0 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Leaving panel of type search
Leaving panel of type search
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 0 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Processing dashboard [Logs System] Syslog dashboard
Leaving panel of type search
Inlined a vis, pushed 0 inner references
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Processing dashboard [Metrics System] Overview
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type lens, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type lens, seems to be inlined already
Leaving panel of type lens, seems to be inlined already
Processing dashboard [System] Windows Overview
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Processing dashboard [System Windows Security] User Logons
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 0 inner references
Leaving panel of type search
Inlined a vis, pushed 0 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 1 inner references
Leaving panel of type search
Inlined a vis, pushed 2 inner references
Leaving panel of type search
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Processing dashboard [System Windows Security] Group Management Events
Inlined a vis, pushed 0 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Leaving panel of type search
Leaving panel of type search
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 1 inner references
Inlined a vis, pushed 0 inner references
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Processing dashboard [System Windows Security] Failed and Blocked Accounts
Inlined a vis, pushed 0 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 3 inner references
Leaving panel of type search
Inlined a vis, pushed 3 inner references
Inlined a vis, pushed 3 inner references
Inlined a vis, pushed 0 inner references
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Processing dashboard [System Windows Security] Failed and Blocked Accounts - Simple Metrics
Inlined a vis, pushed 0 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 2 inner references
Inlined a vis, pushed 3 inner references
Leaving panel of type search
Inlined a vis, pushed 3 inner references
Inlined a vis, pushed 3 inner references
Inlined a vis, pushed 0 inner references
Leaving panel of type visualization, seems to be inlined already
Leaving panel of type visualization, seems to be inlined already
Inlined 44 visualizations
Inlined 0 maps
Inlined 0 lenses
Some visualizations did not get inlined! 44/45
Did not inline system-f42f3b20-fee6-11e9-8405-516218e3d268 anywhere
Removing visualization folder
Writing back dashboards
</pre>
</details>

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

Install integrations and examine dashboards.

## Related issues

- Updates #5022

### CODE REVIEW

**Review by drewdaemon — APPROVED** [review]
Great work. Just for visibility, there is [automated tooling](https://github.com/elastic/visualizations_integrations_tools#inliner-usage) to accomplish this.

**Review by andrewkroh — APPROVED** [review]

**Comment by efd6** [comment]
@drewdaemon That package is the same as the one that I used here, correct?

**Review by fearful-symmetry — APPROVED** [review]

**Comment by drewdaemon** [comment]
@efd6 great! There's no way for me to know if you used the tool or did it in the dashboard UI, so I wanted to make sure you knew.

**Comment by efd6** [comment]
@drewdaemon The commit message has a git-generate script which re-runs thew process and shows what was done (excellent [tool](https://pkg.go.dev/rsc.io/rf/git-generate)).

**Pull request merged**
