### PR TITLE
Run "check" and "test" only for affected packages in PRs

### PR DESCRIPTION
**Pull request by mtojek**
## What does this PR do?

This PR runs "check" and  "test" only for affected packages in the PR.

Checklist:

- [x] Spawn new nodes if package should be checked or tested
- [x] Implement logic to check if package tests should be executed

## Related issues

- Issue: https://github.com/elastic/integrations/issues/296

### CODE REVIEW

**Comment by mtojek** [comment]
Test passed:

I modified the Jenkinsfile for testing purposes to skip changes in the Jenkinsfile and consider artificial changes in the Apache package. The CI job affecting onły Apache: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-474/11/pipeline

**Comment by mtojek** [comment]
The Jenkinsfile seems to be working now. @ycombinator Please take a look whenever you've a chance.

**Comment by mtojek** [comment]
Pipeline tests are failing due to https://github.com/elastic/integrations/issues/491 .

**Review by ycombinator — APPROVED** [review]
LGTM.

**Pull request merged**
