### PR TITLE
[AWS] Fix field names for rds remove processor

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
## What does this PR do?

This pr is to drop the remove processor because it's not doing any actual work since the rename processor already changes the fields name.

### CODE REVIEW

**Review by zmoog — COMMENTED** [review]
@kaiyan-sheng Why do we need to remove the same field we're renaming? In which case the rename is not enough?

**Comment by kaiyan-sheng** [comment]
> @kaiyan-sheng Why do we need to remove the same field we're renaming? In which case the rename is not enough?

We rename it and then remove the original field name. So we don't report the same data point twice :)

**Comment by zmoog** [comment]
> We rename it and then remove the original field name. So we don't report the same data point twice :)

Yeah, I get it.

What I meant was, for example, why do we need to remove the field `aws.rds.metrics.AuroraVolumeBytesLeftTotal.avg` when renaming it makes it go away?

```
POST _ingest/pipeline/metrics-aws.rds-1.42.0/_simulate
{
  "docs": [
    {
      "_source": {
        "@timestamp": "2022-10-04T13:05:22.643+1300",
        "aws": {
          "rds": {
            "metrics": {
              "AuroraVolumeBytesLeftTotal": {
                "avg": 0
              }
            }
          }
        }
      }
    }
  ]
}
```

```
{
  "docs": [
    {
      "doc": {
        "_index": "_index",
        "_id": "_id",
        "_version": "-3",
        "_source": {
          "aws": {
            "rds": {
              "aurora_volume_left_total": {
                "bytes": 0
              },
              "metrics": {}
            }
          },
          "@timestamp": "2022-10-04T13:05:22.643+1300"
        },
        "_ingest": {
          "timestamp": "2023-08-16T21:28:27.25249272Z"
        }
      }
    }
  ]
}
```

**Comment by kaiyan-sheng** [comment]
@zmoog Ahh sorry I completely misunderstood you! Thanks for the comment!! This is interesting! I didnt know rename processor also removes the old field! Let me double check tomorrow then :)

**Comment by kaiyan-sheng** [comment]
@zmoog you are right! The renamed processors deleted the old fields after done renaming. So I will change this PR to actually remove the remove processor then 😂 THANK YOU!!

**Review by zmoog — APPROVED** [review]
So we are dropping the remove processor because it's not doing any actual work since the rename processor already changes the fields name. 

LGTM.

**Review by bhapas — APPROVED** [review]
LGTM

**Pull request merged**
