### PR TITLE
Add var.storage_account_container in Azure Logs

### PR DESCRIPTION
**Pull request by aspacca**
Enhancement
## What does this PR do?
Add var.storage_account_container in Azure Logs

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

## Screenshots

The new "Storage Account Container" option is positioned in the advanced section of each data stream:

CleanShot 2022-07-29 at 13 15 55@2x

### CODE REVIEW

**Comment by zmoog** [comment]
We need to make some changes: defining the `storage_account_container` at the top level in the integration settings makes it available to all azureeventhub inputs, but storage account containers must not be shared across multiple azureeventhub inputs.

Each azureeventhub input uses a storage account container to store checkpoint information about its consumer group, for example:

```json
{
    "partitionID": "0",
    "epoch": 1,
    "owner": "b5454f29-881f-48ae-bd34-5711932f378e",
    "checkpoint": {
        "offset": "47244772552",
        "sequenceNumber": 986,
        "enqueueTime": "2022-07-20T08:17:37.523Z"
    },
    "state": "available",
    "token": "923168d8-bc7a-4e75-8f70-4afb83637c12"
}
```

**Comment by aspacca** [comment]
> but integrations must not share the same storage account container across multiple azureeventhub inputs

good catch! thanks for taking care of this

**Comment by zmoog** [comment]
From the technical perspective, to keep things working as expected, we must place the `storage_account_container` option in the data stream scope (1).

From the UI perspective, we have the choice: can make it always visible and put it in the "standard" section (2) or put it in the "advanced" section (3) of the data stream.

Since this is a vital option and can mess things up if used by multiple integrations, I am inclined to pick the "advanced" option.

I'd love to hear what you think.

cc @ravikesarwani @kaiyan-sheng 

CleanShot 2022-07-28 at 16 53 09@2x

The description is also a critical aspect of this change. I started with this description (this is a draft, do not consider it final):

> This is the container in the storage account where the integration stores the checkpoint data for the consumer group. The integration generates a default container name if not specified. Each integration MUST have a dedicated container; do not reuse the same container for multiple integrations.

The goal is to convey the following information:
- what this is
- what value should you expect
- it is crucial not to reuse the same value in multiple integrations

**Comment by kaiyan-sheng** [comment]
@zmoog I also vote for putting it under the advanced options. But instead of having it all the way to the bottom of the list, I would put it before tags and processors since tags and processors are common across all data streams basically.

btw this can be considered separately. We can also add the `Optional` tag for each config parameter so that users know which ones are required and which ones are not. For example
Screen Shot 2022-07-28 at 9 55 47 AM
:

**Comment by ravikesarwani** [comment]
Yes, let's put it in the Advanced option please since this will be used only in some use cases.

**Comment by zmoog** [comment]
Sounds good; let's go for the "advanced" option. I expect this option to be used in rare cases, but it needs to be there for a few.

Positioning it before the tags looks like a better alternative; thanks @kaiyan-sheng! I will double-check the use of the `Optional` tag here.

**Comment by zmoog** [comment]
Updated the PR description with the a screenshot of the up-to-date version of integration settings.

**Review by tommyers-elastic — APPROVED** [review]
nice work - the description of the new field is super clear.

**Review by endorama — APPROVED** [review]

**Pull request merged**
