### PR TITLE
[ Cisco Secure Email Gateway ] Fix grok pattern in AMP ingest pipeline

### LINKED ISSUE #6442: [ Cisco Secure Email Gateway ] Broken parse for some messages in the AMP pipeline.
One of the `grok`  patterns in the AMP ingest pipeline of the Cisco Secure Email Gateway is the following one:

```
"^Response received for file reputation query from Cloud. %{GREEDYDATA:_tmp.new_message}$"
```

This will parse messages like this:

> Response received for file reputation query from Cloud. File Name = fileName.pdf, MID = 64687353, Disposition = LOWRISK, Malware = None, Analysis Score = 0, sha256 = redactedSha256, upload_action = Recommended to send the file for analysis, verdict_source = CLAMAV, suspected_categories = None

But sometimes the message starts with _Response received for file reputation query from **Cache**_, which will not be parsed.

This can be solved changing the grok pattern to the following:

```
"^Response received for file reputation query from (Cloud|Cache). %{GREEDYDATA:_tmp.new_message}$"
```
I will try to make a PR to fix this parse.

### PR DESCRIPTION
**Pull request by leandrojmp**
## What does this PR do?

FIx a grok pattern in the AMP ingest pipeline for the Cisco Secure Email Gateway integration.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #6442

### CODE REVIEW

**Review by efd6 — COMMENTED** [review]
Can we have a test case for this?

**Comment by leandrojmp** [comment]
> Can we have a test case for this?

Hello @efd6 I can add one tomorrow!

**Comment by leandrojmp** [comment]
Hello @efd6,

I added the test case and bumped the version on changelog and manifest because another PR was merged in between, but not sure what should I do on my side to solve the conflicts.

**Review by efd6 — APPROVED** [review]
Thanks

**Pull request merged**
