### PR TITLE
[O11y][MongoDB] Update filters and remove `mongodb.log.timestamp` from mongodb logs dashboard

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Bug

## What does this PR do?

- [x] Remove mongodb.log.timestamp field from dashboard and visualizations
- [x] Add data_stream.dataset:'mongodb.log' filter to panels
- [x] Add update log level filter in Error Logs panel [[Reference](https://github.com/elastic/integrations/pull/5831#issuecomment-1502067842)]
## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes https://github.com/elastic/integrations/issues/5846

## Screenshots

Below is the screenshot of dashboard before updating filters and fields:
image

After fix:
image

### CODE REVIEW

**Comment by muthu-mps** [comment]
@rajvi-elastic - Can you please update the dashboard screenshot after the fix ?

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic - Can you please update the dashboard screenshot after the fix ?

 @muthu-mps I have updated it in the [package](https://github.com/elastic/integrations/pull/6533/files#diff-a8b3538f67a6d2a776caca1184b69b838c8027f17c349b822051ca03a12a95bf) itself and also updated the description with screenshot.

**Review by muthu-mps — APPROVED** [review]
LGTM !

**Review by milan-elastic — APPROVED** [review]
LGTM!

**Pull request merged**
