### PR TITLE
[Enhancement] Nginx Improve Log Coverage

### PR DESCRIPTION
**Pull request by WildDogOne**
## What does this PR do?

This PR aims to improve the log coverage for nginx

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist
Adding ECS compliant fields for
- [x] Client
- [x] Server
- [x] Referrals

### CODE REVIEW

**Comment by WildDogOne** [comment]
need a bit of input on this
I am adding logs with reverse proxy functionality, how can I make this ECS conforming?
Right now I have this:

client.ip/domain: The requester
server.ip/domain: The nginx reverse proxy
destination.ip/domain: The actual Server, which can be the nginx or someone upstream

Does this make sense?
or would a custom field like nginx.target.server.ip be better?

**Comment by WildDogOne** [comment]
👍

**Comment by jamiehynds** [comment]
Adding @SubhrataK for visibility.

**Pull request closed without merging**
