### PR TITLE
Add microsoft package

### PR DESCRIPTION
**Pull request by adriansr**
## What does this PR do?

This adds the microsoft package with dhcp dataset.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [x] I have verified that all datasets collect metrics or logs.

## Screenshots

Screenshot 2020-08-05 at 18 46 10

Screenshot 2020-08-05 at 18 46 36

### CODE REVIEW

**Comment by adriansr** [comment]
Timezone is definitely necessary as most/none of these parsers contain timezone information, so it'll be necessary to adjust it when ingesting logs from a tz other than the one elastic-agent/filebeat uses.

All in all, probably makes sense to hide those under Advanced options.

**Comment by urso** [comment]
Seeing a package named Microsoft makes me wonder how it relates to the Windows package. Do we plan to add more non-DHCP related inputs to this package?

**Comment by andrewstucki** [comment]
> Do we plan to add more non-DHCP related inputs to this package?

To be honest, I had the same thought when I saw this, seeing as I just ported the Office 365 module. Seeing as this is such an all-encompassing namespace, does it make sense to put things like the Office 365 module + whatever winlogbeat stuff gets ported under here?

**Comment by adriansr** [comment]
We also have microsoft/defender_atp (not ported to packages yet) in Filebeat.

I had the same realization recently, we should merge o365 in here or in the Windows package (didn't see that one).

However, note that I plan to release this integration in 7.9. So maybe we can wait until that's done and then create a new version of this package or talk about moving it to a different one.

**Pull request merged**
