### PR TITLE
[O11y][Hadoop] Lens migration for visualizations to kibana version 8.3.0

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

- Migrate visualizations to lens for Hadoop integration package

- Statistics for **Hadoop** Lens migration:

<html>
<body>
<google-sheets-html-origin>

Hadoop dashboards | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics Hadoop] Applications | 0 | 7 | 7 | 0
[Metrics Hadoop] Cluster overview | 0 | 8 | 8 | 0
[Metrics Hadoop] Data nodes | 6 | 3 | 9 | 0
[Metrics Hadoop] Node Manager | 0 | 3 | 3 | 0
  | 6 | 21 | 27 | 0

</body>
</html>

## Checklist

- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that panels are populated with data.
- [x] I have verified that panels are not distorted after being migrated to lens.
- [x] I have updated screenshots of dashboard.
- [x] I have verified that data count are matching and panel aggregations are same as before.

## Author's checklist

- [x] Migrated panels should be removed from visualization folder.
- [x] Migrated visualizations are populating in current Kibana version 8.3.0 itself. 

## Related issues

- Relates #5221

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
Can you consider breaking down the PR to smaller one ?

**Comment by harnish-elastic** [comment]
> Can you consider breaking down the PR to smaller one ?

Sure @agithomas, breaking down the PR into the following PRs:

- Application
- Cluster
- Data Node and Node Manager

**Comment by agithomas** [comment]
> Let me know if it looks good to you! Also do we need to bump up the version for every PR?

looks good. Version change is optional, no harm in making an increment also.

**Comment by harnish-elastic** [comment]
@agithomas As breakdown this PR is getting difficult, created 3 other PRs dashboard wise. For that reason we are declining this PR. Let me know if you have any issues.

https://github.com/elastic/integrations/pull/5605
https://github.com/elastic/integrations/pull/5606
https://github.com/elastic/integrations/pull/5607

**Pull request closed without merging**
