### PR TITLE
[Azure][Storage_account] Enable TSDB

### LINKED ISSUE #7215: Azure TSDB Enablement: storage_account datastream
## Test Environment Setup
- [x] Creation of Azure Test Environment

## Datastream : storage_account 
  - [x] Add dimension fields
           https://github.com/elastic/integrations/pull/7356/
  - [x] Adding metric_type mapping
          https://github.com/elastic/integrations/pull/7488
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface
  - [x] Verify if dimension field mapping is correct in the data stream template.

Enable TSDB by default -  https://github.com/elastic/integrations/pull/8064

## Screenshots

Screenshot 2023-10-03 at 11 37 10 AM
Screenshot 2023-10-03 at 11 37 38 AM
Screenshot 2023-10-03 at 11 37 46 AM
Screenshot 2023-10-03 at 11 38 19 AM
Screenshot 2023-10-03 at 11 38 38 AM
Screenshot 2023-10-03 at 11 38 45 AM
Screenshot 2023-10-03 at 11 39 00 AM

### PR DESCRIPTION
**Pull request by ritalwar**
- Enhancement

## Proposed commit message

Enable time series data streams for the storage_account metrics dataset. This dramatically reduces storage for metrics and is expected to progressively improve query [performance](https://www.elastic.co/blog/70-percent-storage-savings-for-metrics-with-elastic-observability). For more details, see https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html.

The changes have been validated using the `TSDB migration test kit`.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

- Closes #7215 

## Screenshots

Refer #7215

### CODE REVIEW

**Review by constanca-m — APPROVED** [review]

**Comment by lalit-satapathy** [comment]
Hi @zmoog, @ritalwar, 

 Do you see the **storage_account** data stream any impact from the Azure metrics grouping issues (example [this](https://github.com/elastic/integrations/issues/7621)) currently being worked on. or this one is not impacted by those changes?

**Comment by zmoog** [comment]
@lalit-satapathy, I guess the grouping / time grain problems can happen or not, depending on the metricset configuration. 

If the migration kit didn't report any data loss, this probably means the storage account metrics config is not triggering the problem.

However, it's worth double-checking this metricset more in the context of the changes happening with https://github.com/elastic/integrations/issues/7621.

Thanks for bringing this up!

**Comment by ritalwar** [comment]
I conducted testing with the TSDB migration kit and confirmed that there was no data loss. Furthermore, I reviewed the metricbeat [code](https://github.com/elastic/beats/blob/4c34c41039be5f24d9c7f2b6f3305a6b1522c969/x-pack/metricbeat/module/azure/storage/client_helper.go#L140) and found that grouping for the storage account is already occurring using allowed dimensions, so there should be no impact.

**Review by lalit-satapathy — APPROVED** [review]
LGTM as this is not impacted by Azure metric grouping [issue](https://github.com/elastic/integrations/pull/8064#issuecomment-1765957464).

**Pull request merged**
