### PR TITLE
Rename config to policy and dataset to datastream

### PR DESCRIPTION
**Pull request by mtojek**
## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [x] I have verified that all datasets collect metrics or logs.

## Author's Checklist

- [x] Rename config template to policy template
- [x] Rename dataset to data_stream
- [x] Bump up release versions of integrations
- [x] Make sure there are no "hacked" dependencies.

## How to test this PR locally

```
mage clean
mage build
cd testing/environments
docker-compose -f snapshot.yml build package-registry
docker-compose -f snapshot.yml up --force-recreate package-registry
```
package-registry should be exposed under http://localhost:8080 .

## Related issues

-

### CODE REVIEW

**Comment by jen-huang** [comment]
Hi @mtojek, thanks for helping me get my registry running with this branch. I found that the package info endpoint doesn't contain `policy_templates` or `data_streams` properties for any of the packages I checked (doesn't contain `config_templates` or `datasets` either). Example: http://localhost:8080/package/system/0.7.0/

Are you seeing the same?

**Comment by ycombinator** [comment]
@jen-huang I might be off here but is the registry you are running built with this PR's changes in it: https://github.com/elastic/package-registry/pull/641?

**Comment by mtojek** [comment]
@jen-huang , confirmed (I see the same results).

It looks that you need to checkout the PR @ycombinator posted above (https://github.com/elastic/package-registry/pull/641), then:

```
docker build . -t docker.elastic.co/package-registry/package-registry:wip
```

In testing/environments, you need to update the reference to the Docker image:

```
FROM docker.elastic.co/package-registry/package-registry:wip

COPY testing/environments/package-registry.config.yml /package-registry/config.yml
COPY build/integrations /packages/integrations
```

and finally:

```
docker-compose -f snapshot.yml build package-registry
docker-compose -f snapshot.yml up --force-recreate package-registry
```

**Comment by jen-huang** [comment]
Thanks both!! I am seeing the correct package info now. Will continue with my testing.

**Comment by jen-huang** [comment]
Another issue found: I think elastic/package-registry#641 is missing `datasets.name`->`data_streams.datasets` property renaming from the [package spec changes](https://github.com/elastic/package-spec/pull/24/files#diff-13d2900dcce8e312a06c834b665816a1R71).

Example from system package info:

```diff
  "data_streams": [
    {
      "type": "logs",
-      "name": "system.auth",
+      "dataset": "system.auth",
      "title": "System auth logs",
      "release": "experimental",
      "ingest_pipeline": "default",
      ...
    },
    ...
  ]
```

**Comment by jen-huang** [comment]
I was able to monkey patch my local `package-registry` to return `data_stream.dataset` property. Things are looking promising.

**Review by jen-huang — APPROVED** [review]
Didn't review actual code but tested this with https://github.com/elastic/kibana/pull/78699 and it works well 👍

**Review by jonathan-buttner — APPROVED** [review]
I looked over the changes and they look good 👍

**Pull request merged**
