### PR TITLE
Remove unfinished synthetics package

### PR DESCRIPTION
**Pull request by justinkambic**
## What does this PR do?

We were working on a partially-ready package for synthetics, but had to delay because of external factors. We're looking to remove the package for now and we will re-add when we are prepared to move forward in the future.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [ ] I have verified that all datasets collect metrics or logs.

## Author's Checklist

- [ ] Ensure all synthetics-related assets are removed from the master branch.

## Related issues

- Relates https://github.com/elastic/uptime/issues/260

### CODE REVIEW

**Comment by andresrc** [comment]
@mtojek @ruflin do we have a way to remove packages from `package-storage`

**Review by mtojek — APPROVED** [review]
Because of the design of package-storage, there is no easy way to delete packages. The package-storage can accept packages from multiple sources, also committed directly.

@justinkambic Please prepare also a similar PR to the package-storage snapshot branch. Thank you for the cleanup!

**Comment by ruflin** [comment]
@andresrc The synthetics package only went into snapshot builds, so there is no issue in removing it from there.

**Comment by justinkambic** [comment]
> The synthetics package only went into snapshot builds, so there is no issue in removing it from there.

@ruflin does this mean no further action is needed?

**Comment by ruflin** [comment]
@justinkambic You should still remove it from the snapshot branch if you do not want to have it there.

**Comment by justinkambic** [comment]
@ruflin +1, PR is here: https://github.com/elastic/package-storage/pull/461

**Pull request merged**
