### PR TITLE
[Fleet] Update Elastic Agent dashboard, package icon, and data stream mappings

### LINKED ISSUE #951: Update the agent integration dashboard with additional filebeat and metricbeat metrics
**Describe the enhancement:**
We added the awesome elastic agent integration in 7.11 that shows agent metrics and filebeat and metricbeat system metrics. There are other meaningful filebeat and metricbeat metrics that we gather but are not showing it on dashboard today. These metrics are displayed in stack monitoring UI and are described in our [documentation](https://www.elastic.co/guide/en/kibana/master/beats-page.html)

Acceptance criteria:
After this issue is resolved, users will be able to see all the filebeat and metricbeat metrics that we display in stack monitoring UI. 

@ravikesarwani I do not specific metric names other than the ones in documentation. If there are additional metrics not shown but we need to show in dashboard, can you please add them in this issue?

### LINKED ISSUE #1453: [Elastic Agent] Incorrect visualization of CPU usage
See [discuss](https://discuss.elastic.co/t/negative-cpu-usage-on-default-dashboard-elastic-agent-agent-metrics/279762)

It seems that the visualization is using some derivative and missing some additional function to ensure the values are positive.

### PR DESCRIPTION
**Pull request by nchaulet**
## Description

Resolve #951
Resolve https://github.com/elastic/beats/issues/27405
Resolve #1453

Update the elastic agent dashboard with more metrics:
* CGroup CPU usage
* filebeat and metricbeat events rate, throughput and errors

Data streams changes:

* Add the missing `beat*` fields to the metrics data_stream 
* Add back the `log.level` field  to fix a bug with the log level selection in the agent logs page in Fleet 

## UI Change
elastic_agent_metrics

Screen Shot 2021-08-16 at 10 38 28 AM

cc @ravikesarwani

### CODE REVIEW

**Comment by ravikesarwani** [comment]
@nchaulet I don't see cgroup memory information. Can you please add that as well. Both CPU and memory limits are critical in the container (Docker)environment and showing cgroup information would be very useful there.

**Comment by ravikesarwani** [comment]
@matschaffer I know you have some great field experience and love to hear any feedback from your side on this Elastic Agent dashboard.

**Comment by nchaulet** [comment]
Updated with the memory Cgroup limit 

localhost_5601_app_dashboards (5)

**Comment by ruflin** [comment]
We add a lot of fields to each template. Do we really need all of them? In general we should only map the ones we need in the queries for the dashboards. For all the other ones runtime fields could be used if needed.

@nimarezainia Would be great if you could spin this up and have a look if all works as expected.
@nchaulet Thx for taking it on.

**Comment by nchaulet** [comment]
> We add a lot of fields to each template. Do we really need all of them? In general we should only map the ones we need in the queries for the dashboards. For all the other ones runtime fields could be used if needed.

We probably do not need any of them, I am going to use runtime fields instead

**Comment by nchaulet** [comment]
@ruflin Actually looks like we do not support runtime fields in a package for now (https://github.com/elastic/package-spec/issues/39) just going to cleanup the fields to only add the one needed in the dashboard

**Comment by ravikesarwani** [comment]
@nchaulet We haven't added all the fields in the dashboard that the current beats shows. the idea was to make enough things available but users can easily extend the dashboard where needed.Can we make sure some of the missing fields in Events rate, Throughput (Bytes received), System load are available to user for easily extending the dashboard?

**Comment by ruflin** [comment]
I did not mean runtime fields on the packages / templates but on query time.

**Comment by nchaulet** [comment]
> I did not mean runtime fields on the packages / templates but on query time.

Maybe I am saying a mistake here, but I think the only way to use runtime fields in a dashboard or a visualization is to add the runtime field to the index pattern

**Comment by nchaulet** [comment]
> @nchaulet We haven't added all the fields in the dashboard that the current beats shows. the idea was to make enough things available but users can easily extend the dashboard where needed.Can we make sure some of the missing fields in Events rate, Throughput (Bytes received), System load are available to user for easily extending the dashboard? 

I added the mappings for all the events, and throughput  even the one we do not use in the dashboard.

**Comment by jen-huang** [comment]
@hop-dev was looking at #27404 and found that `event.dataset` is missing mappings too. @nchaulet do your mapping changes here add that back? It looks like most other packages have this field defined in `base-fields.yml` files:

https://github.com/elastic/integrations/blob/0732c7811279339870d6960abd7ffe2a6d8d2233/packages/nats/data_stream/connection/fields/base-fields.yml#L17

**Comment by nchaulet** [comment]
> @hop-dev was looking at #27404 and found that event.dataset is missing mappings too. @nchaulet do your mapping changes here add that back? It looks like most other packages have this field defined in base-fields.yml files:

It does not but I can try to add it back and see if it solve the Fleet issue.

**Comment by matschaffer** [comment]
@nchaulet is there a doc that'll teach me how to get this running live so I can see what's available?

A couple of thoughts just based on the screenshot:

- cgroup info will be important for people running containers with limits, but might just take up screen space for people who don't. Not sure if we have options for toggling visibility, but it might be good to consider for future work.

- it'd be good to get info about restarts (for example cgroup OOMs) or start up errors, not just output errors. Typically I'd read cgroup ooms from the OS system log, so not sure how easy that will be. But without it we could have a case where there's not enough cgroup memory and we just can't start. Would be good to make the failure obvious to the user.

- The titles are good, but it'd be even better to have descriptions on each viz as well so you can know exactly what metric is being shown without having to edit the viz (especially rough for TSVB since filters will drop away when you edit the viz).

**Comment by ruflin** [comment]
@matschaffer Here some docs on how to get this setup for testing: https://github.com/elastic/integrations/blob/master/docs/developer_workflow_design_build_test_integration.md

**Comment by ruflin** [comment]
@nchaulet You are right about the Kibana index pattern and runtime fields. I was thinking the user would update these to use it. But these are global and not per dashboard and I think there is also a chance to we will overwrite it? I'm hoping in the future each Dashboard will have its own "data view / kibana index pattern" stored locally so it does not impact each other and we do not overwrite it. I know there is some work ongoing in this direction on the Kibana side. Maybe @joshdover has some more specifics.

**Comment by nchaulet** [comment]
Just updated with the description 
localhost_5601_app_dashboards (7)

**Comment by jen-huang** [comment]
@nchaulet Do you think the dashboard changes here also fixes https://github.com/elastic/integrations/issues/1453?

**Comment by nchaulet** [comment]
@jen-huang yes I just tested and adding event.dataset mapping fix the issue

**Comment by jen-huang** [comment]
@nchaulet Nice thanks for adding `event.dataset`. #1453 is a different issue about CPU usage calculation being incorrect.

**Comment by nchaulet** [comment]
@jen-huang  My bad I misread your comment, I just pushed a fix for #1453

**Review by nimarezainia — APPROVED** [review]
Hi, I can't comment on the individual fields but based on the dashboard this looks good. thanks.

**Review by kpollich — APPROVED** [review]
LGTM in Fleet/Integrations UI's. 🚀

**Comment by dikshachauhan-qasource** [comment]
Hi @nchaulet 

We have attempted to validate above ticket on 7.15 BC2 Kibana QA build and could not find required changes on elastic agent metrics dashboard for default docker-fleet-agent. Though we have enabled logs collection settings for default fleet server agent.

Screenshot:
image


@nchaulet  Could you Please let us know how to validate above changes on dashboard.

**Working fine:**
- On Integration tab, elastic agent package icon and sub-headings were correctly updated as per mock screenshot.
 
image

cc @EricDavisX 

Thanks
QAS

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this issue on 7.15.0 BC-2 Kibana Cloud environment and found it **fixed** now.
- Log level dropdown is showing user options to select log level say- error, info, debug, warn etc.

**Build details:**
```
Build: 43742
Commit: 113d5f2a745ab9be7d567d13ff906dfd0f5b7a9a
```

**Screenshot:**


Thanks
QAS

**Comment by dikshachauhan-qasource** [comment]
Hi @nchaulet 

We have validated above PR again on 7.15BC4 cloud-qa build and came up with following observations shared above on Elastic-agent package version 1.2.0. Please let us know if we are missing anything in validating above.

Observations:
1. Icons is now visible on Integration detail page and data stream page.
image

2. Data streams are now available for filebeat and metricbeat.
image

3.  On Dashboard no data is available for Host selected by default in filter value.
image

4. However, on removing pre-selected host value on dashboard data shows up on graphs for elastic-agent.
image

Query: No data is available on graphs Cgroup CPUusage and [Elastic Agent] Errors in writing the response from the output. Is it expected.

Thanks
QAS

**Comment by nchaulet** [comment]
@dikshachauhan-qasource  thanks for the testing 

The default filter issue will be fixed by https://github.com/elastic/integrations/pull/1569

For the no data for cgroup and errors it's expected, you will have data in cgroup if you run the agent in a container with memory and cpu limit. and errors if there are output errors.

**Comment by dikshachauhan-qasource** [comment]
Hi @nchaulet 

Thanks for the feedback. 

Further, we revalidated fixes for https://github.com/elastic/integrations/pull/1569 under latest snapshot build from cloud-qa. However, as merges were not found under same, so we will validate same on next BC.

Build details:
BUILD 43910
COMMIT 3a43cf52fb7fb41403239132e78fd43ab9a0e118

Thanks
QAS

**Pull request merged**
