### PR TITLE
[O11y][CouchDB] Resolve the conflicts in host.ip field

### PR DESCRIPTION
**Pull request by milan-elastic**
- Bug

## What does this PR do?

- Added host.ip field in ecs.yml to avoid field conflicts for users.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.

## Related issues

- Closes https://github.com/elastic/integrations/issues/7283
- Relates https://github.com/elastic/integrations/issues/7253

### CODE REVIEW

**Review by aliabbas-elastic — APPROVED** [review]
LGTM

**Comment by muthu-mps** [comment]
Do we have plans to update the troubleshooting guide similar to other PR's ?

**Comment by milan-elastic** [comment]
> Do we have plans to update the troubleshooting guide similar to other PR's ?

@muthu-mps For the couchbase TSDB is already enabled, we don't have the exact reindexing steps while TSDB is enabled, So for now it is not updated. When we'll have clarity on the steps then we can plan to include it. For more information, Please have a look at this [issue](https://github.com/elastic/elasticsearch/issues/98157).

**Review by muthu-mps — APPROVED** [review]
Looks good!

**Pull request merged**
