### PR TITLE
[Winlog] Can't modify Dataset Name / event.dataset not conforming to ECS

### PR DESCRIPTION
**Pull request by nicpenning**
- Bug

## What does this PR do?
Integration Impacted: `Custom Windows Event Logs integration`

image
_Screenshot of default Dataset name_

Currently, the event.dataset is set to a constant_keyword which prevents anyone from changing the dataset in the custom windows integration. This should be a keyword to conform to ECS and allow anyone to modify the dataset in the integration as it is provided today.

If you change winlog.winlog to anything this will likely error.
```
Preview of field's value: 'windows.applocker'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"[constant_keyword] field [event.dataset] only accepts values that are equal to the value defined in the mappings [winlog.winlog], but got [windows.applocker]"}}}}}
```

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Screenshots

image

### CODE REVIEW

**Review by andrewkroh — APPROVED** [review]
LGTM. The fact that Elastic Agent is [always setting](https://github.com/elastic/elastic-agent/blob/725b75093ca40a48ff31e60685c52ca1ea9c590b/internal/pkg/agent/application/monitoring/v1_monitor.go#L403-L4130 `event.dataset` seems risky (and wasteful of storage) given that almost all integrations use a constant_keyword with static value.

**Comment by nicpenning** [comment]
Awesome 👌🏻

**Comment by andrewkroh** [comment]
> [2023-02-15T23:26:09.700Z] Error: checking package failed: checking readme files are up-to-date failed: files do not match

CI says the readme needs rebuilt. Can you please run `elastic-package build` and commit the updated file.

**Comment by nicpenning** [comment]
Thanks for running that for me and reviewing this!

**Pull request merged**
