### PR TITLE
Apache: refactor integration (part II)

### PR DESCRIPTION
**Pull request by mtojek**
## What does this PR do?

This PR refactors the Apache integration according to action items defined in https://github.com/elastic/integrations/issues/370 . 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [x] I have verified that all datasets collect metrics or logs.

## Author's Checklist

- [x] Update dashboards with latest changes in Metricbeat
- [x] Adjust field defintions after changes in Metricbeat
- [x] Update the sample event for `status` data stream
- [x] Save sample events for other data streams
- [x] Write pipeline tests for Apache

## How to test this PR locally

CI tests will verify the ingest pipeline. Service metrics data should visible on dashboards.

## Related issues

- https://github.com/elastic/integrations/issues/370

### CODE REVIEW

**Comment by mtojek** [comment]
Now I have to wait now until changes in Metricbeat are propagated to the Elastic Agent docker image and these tests will start passing.

**Comment by mtojek** [comment]
jenkins run the tests please

**Comment by mtojek** [comment]
jenkins run the tests please

**Comment by mtojek** [comment]
jenkins run the tests please

**Comment by exekias** [comment]
Nice to see this moving forward! It would be good to update `fields.yml` to include `unit` and `metric_type`, WDYT?

**Comment by mtojek** [comment]
> Nice to see this moving forward! It would be good to update fields.yml to include unit and metric_type, WDYT?

Let me try to update these. Is there any one-pager with available units/metric_types?

**Comment by mtojek** [comment]
jenkins run the tests please

**Comment by mtojek** [comment]
I need to wait a bit longer with this draft. The last builtin commit is `b8a4a20a37daea7e78763da4e6f07238080cdfba`.

**Comment by mtojek** [comment]
jenkins run the tests please

**Review by ycombinator — APPROVED** [review]
LGTM.

**Pull request merged**
