### PR TITLE
[ess_billing] Addition of an ESS billing integration

### PR DESCRIPTION
**Pull request by 3kt**
## Proposed commit message

This adds the `ess_billing` integration package, that consumes the ESS billing API at https://api.elastic-cloud.com. This in turns gives a richer view than what is directly exposed through the cloud organization page, and allows customers to gather clearer insights in their spending patterns.

Currently, a single `billing` dataset is implemented, performing daily CEL API calls against the API. Lookbehind is supported, with 1 year configured as default (meaning initial run of the input will fetch the last year of billing data).

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

I don't have access to https://docs.elastic.dev - not quite sure how to check the last bullet point.

## Author's Checklist

- [ ] 

## How to test this PR locally

You will need an active cloud organization, for which you want to grab:
* The organization ID, visible on the organization page.
* An API key with billing permissions.

Simply install the integration without changing the defaults, and you should see the included dashboard getting populated with data. Make sure you change your time range, as the default will initially populate data from 1 year in the past.

## Related issues

N/A

## Screenshots

image

ess_billing-dashboard

The cloud locations will need fine tuning, but I can figure this out while we keep the integration in beta.
I've also taken some liberties with regards to ECS, as we don't really have good handling for such information AFAICT.

### CODE REVIEW

**Comment by 3kt** [comment]
Not quite sure how to fix these:

```
test case failed: one or more errors found in document: [0] field "input.type" is undefined
[1] field "tags" is undefined
[2] field "ecs.version" is undefined
```

Checking with other integrations, it's unclear how they pass themselves

**Comment by kpollich** [comment]
@elastic/stack-monitoring - Do you think you could help out with coming up with an ownership model for this new integration? Since your team already owns the `elasticsearch` integration I thought maybe you'd be able to help out here. 



> Not quite sure how to fix these:
> 
> ```
> test case failed: one or more errors found in document: [0] field "input.type" is undefined
> [1] field "tags" is undefined
> [2] field "ecs.version" is undefined
> ```
> 
> Checking with other integrations, it's unclear how they pass themselves

@jsoriano @mrodm could you help with this particular test failure?

**Comment by kcreddy** [comment]
> test case failed: one or more errors found in document: [0] field "input.type" is undefined
[1] field "tags" is undefined
[2] field "ecs.version" is undefined

The [1] and [2] should be resolved by adding [`build.yml`](https://github.com/elastic/integrations/blob/main/packages/tychon/_dev/build/build.yml).

[0] field `input.type` is not an ECS field. The error could be resolved by manually defining a field. [Example1](https://github.com/elastic/integrations/blob/main/packages/tychon/data_stream/arp/fields/filestream.yml#L1-L6), [Example2](https://github.com/elastic/integrations/blob/main/packages/zscaler_zia/data_stream/alerts/fields/beats.yml#L1-L3).

**Comment by consulthys** [comment]
> @elastic/stack-monitoring - Do you think you could help out with coming up with an ownership model for this new integration? Since your team already owns the elasticsearch integration I thought maybe you'd be able to help out here.

@kpollich we would certainly help, though I see in [CODEOWNERS](https://github.com/elastic/integrations/pull/11533/files#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R182) that @elastic/obs-infraobs-integrations would be responsible for this new integration.

**Comment by 3kt** [comment]
> @kpollich we would certainly help, though I see in CODEOWNERS that @elastic/obs-infraobs-integrations would be responsible for this new integration.

@consulthys I've put this by mimicry with other integrations, to prevent build failures 😅 - very happy to alter it to what makes the most sense.

cc @mrjoechin

**Comment by lalit-satapathy** [comment]
> > I think either @elastic/platform-billing or @elastic/platform-billing-bm should take responsibility
> 
> I concur here. This should be platform billing or ESS team ownership. obs-infraobs-services might not be the right fit for this code ownership. Let me know if this helps @3kt

CC: @daniela-elastic for any pointers.

**Comment by brentnewton** [comment]
Regarding finding appropriate ownership in CODEOWNERS, would this not be a case for the authors and current vendor of this tooling (Customer Engineering in this case) to be listed?

**Comment by 3kt** [comment]
> Regarding finding appropriate ownership in CODEOWNERS, would this not be a case for the authors and current vendor of this tooling (Customer Engineering in this case) to be listed?

The CE team isn't part of engineering so I'm not quite sure what this entails from a support perspective. If this is just an acknowledgement of whom developed a certain module, it's fine for me to modify ownership.

**Comment by brentnewton** [comment]
> The CE team isn't part of engineering so I'm not quite sure what this entails from a support perspective. If this is just an acknowledgement of whom developed a certain module, it's fine for me to modify ownership.

@3kt - from my perspective CE maintaining codeowner on this integration aligns with the authorship and with being the most likely to be able to resolve issues or otherwise support this integration.

**Comment by lucabelluccini** [comment]
Integrations have a level of support https://www.elastic.co/docs/current/integrations/support. At the moment they're not enforced and we allow support tickets for all of them, but we set expectations.

From Support level of Integrations @111andre111 is following this subject internally.

Regardless of the support level, at the moment we must have the ability to reach out engineering and we need a path, which is driven by the codeowners and requires some work to be done on Support side.

**Comment by 3kt** [comment]
@lucabelluccini I'd find it hard to put such integration in any category but the `Elastic Developed` one, given the circumstances and the fact that we own the data source.

> we must have the ability to reach out engineering

That's the crux of the issue: what if the `codeowners` references someone or a team __outside__ of engineering?

> Non-GA integrations are still allowed support cases, but not as high urgency.

Another option would be never to leave GA, but we still don't address the underlying issue of non-engineering ownership, and it feels like shoving the issue under the rug.

**Review by pathoge — APPROVED** [review]
LGTM

**Pull request merged**
