### PR TITLE
[Enhancement] Cisco FTD differentiating between inbound and outbound

### PR DESCRIPTION
**Pull request by WildDogOne**
## What does this PR do?

I noticed some very odd Logs in FTD
```
Nov 01 16:42:22 UTC: %FTD-session-6-302013: Built inbound TCP connection 1488052803 for intranet:192.168.22.10/59864 (192.168.22.10/59864) to internet:216.160.83.56/1433 (216.160.83.56/1433)
```

The current extraction is:
network.direction: inbound (makes sense as it's extracted from log)
source.ip: 192.168.22.10
destination.ip: 216.160.83.56

In my opinion the source and destination IPs are flipped.
So this PR is to check if flipping them makes sense in the view of the community.
The main problem that I see, this change could potentially affect a lot of users who have already adapted to this way of life.

[Cisco Documentation on this issue:](https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/syslogs3.html#con_4770603)
`If inbound is specified, the original control connection was initiated from the outside. For example, for FTP, all data transfer channels are inbound if the original control channel is inbound. If outbound is specified, the original control connection was initiated from the inside. `

Event Codes with this issue:
- 302013
- 302015
- 302017

This change covers 302013 and 302015. I have sadly no sample logs for 302017

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by efd6** [comment]
Do we have a good idea about what Cisco mean when they include "to" in the connection description? Does it really mean "between"?

**Comment by WildDogOne** [comment]
honestly I think cisco themselves already have no actual idea what to means.
What I have noticed with Cisco FTD logs, everything seems quite unified until you come to the 300k eventcodes, which are part of the more modern modules of the FTD appliance and they have a totally different way of logging,

My interpretation so far is: if no direction is specified, X to Y means, X is source and Y is destination. If a direction is specified, which luckily is only in 3 event codes, X to Y is dependant on the direction

**Comment by P1llus** [comment]
I can confirm this is indeed the correct assumption, at least based on their documentation of these specific event codes, a bit of a weird way to log this.

From my perspective this change is 👍

**Review by efd6 — APPROVED** [review]

**Pull request merged**
