### PR TITLE
Statsd Input Package

### PR DESCRIPTION
**Pull request by ishleenk17**
- Enhancement

## What does this PR do?

Statsd Input Package.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

Install the Statsd Input Package and run a service that sends metrics in Statsd format

## Related issues

- Closes https://github.com/elastic/integrations/issues/4809

## Screenshots
Screenshot 2023-01-04 at 5 44 56 PM

### CODE REVIEW

**Comment by ishleenk17** [comment]
As part of the next development cycle for statsd, 
1. Support other input options for users: stats.mappings, TTL.
2. Check how we can make statsd more generic.

**Comment by lalit-satapathy** [comment]
Any plans to add to the [statsd.mapping](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-statsd.html) as an input config?

**Comment by ishleenk17** [comment]
> Any plans to add the [statsd.mapping](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-statsd.html) as an input config?

Yes, this will be taken as part of further enhancements. Its captured in https://github.com/elastic/integrations/issues/4958

**Comment by lalit-satapathy** [comment]
LGTM for 0.0.1 release

**Review by lalit-satapathy — APPROVED** [review]

**Pull request merged**
