### PR TITLE
Add search reference that was removed from Elastic-Agent dashboard

### PR DESCRIPTION
**Pull request by belimawr**
## Proposed commit message

This commit re-adds a search that was removed by accident from the
[Elastic Agent] Agent Info dashboard and add an exception to the lint
so the package can be compiled.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

~~## Author's Checklist~~
## How to test this PR locally

1. Build the elastic-agent package
2. go to the dashboard: https://127.0.0.1:5601/app/dashboards#/view/elastic_agent-0600ffa0-6b5e-11ed-98de-67bdecd21824

## Related issues
- https://github.com/elastic/integrations/pull/10217

~~## Screenshots~~

### CODE REVIEW

**Review by pierrehilbert — APPROVED** [review]

**Comment by belimawr** [comment]
@jlind23 you had notices this search got deleted, could you double check it is working as expected?

**Comment by pierrehilbert** [comment]
@jlind23 is out for one more week

**Comment by agmic** [comment]
@belimawr jlind23 may have commented based on a support ticket I raised. 

After updating to 2.0.2 I still can't see the [Elastic Agent] Agent Errors saved query on the [Elastic Agent] Agent Info dashboard. Under saved objects, there is a relationship between the dashboard and the query (parent-child) but the saved query isn't displaying. I can open it in Discover with the expected data being returned.

**Comment by belimawr** [comment]
Thanks @agmic I believe I managed to fix it now, see my new PR: https://github.com/elastic/integrations/pull/10773

**Comment by agmic** [comment]
@belimawr The screenshot with Agent Errors at the bottom looks correct.

**Pull request merged**
