### PR TITLE
[O11y][Azure Metrics] Migrate Queue Storage Overview dashboard to lens

### LINKED ISSUE #7434: [O11y][Azure Metrics] Azure Storage Account Lens migration
Manually migrate `Azure Storage Account` visualizations to the lens in the Kibana version `8.4.0` itself. 

## Preparation of data for testing
- [x] Use sample_event.json / setup live instance using docker / mock data using a mock server to populate dashboards 

## Migration stats
<html>
<body>

  | Before Migration |   |   | After Migration |   |  
-- | -- | -- | -- | -- | -- | --
  | Lens | Visualization | Old Input Controls | Lens | Visualization | New control panels
[Azure Metrics] Queue Storage Overview | 0 | 9 | 1 | 9 | 0 | 1
[Azure Metrics] Table Storage Overview | 0 | 9 | 1 | 9 | 0 | 1
[Azure Metrics] Storage Overview | 0 | 10 | 1 | 10 | 0 | 1
[Azure Metrics] File Storage Overview | 0 | 11 | 1 | 11 | 0 | 1
  | 0 | 39 | 4 | 39 | 0 | 4

</body>
</html>

## Dashboard : [Azure Metrics]  Queue Storage Overview
  - [x] Migrate  visualization to the lens.
    - https://github.com/elastic/integrations/pull/7662/
## Dashboard : [Azure Metrics]  Table Storage Overview
  - [x] Migrate  visualization to the lens.
    - https://github.com/elastic/integrations/pull/7690/
 ## Dashboard : [Azure Metrics] Storage Overview
  - [x] Migrate  visualization to the lens.
    - https://github.com/elastic/integrations/pull/7691
## Dashboard : [Azure Metrics] File Storage Overview
  - [ ] Migrate  visualization to the lens.
    - https://github.com/elastic/integrations/pull/7692
## Verification and Validation
  - [x] Verification of functionality remains the same after migration in Kibana
  - [x] Verification of data count of after-migrated visualization with before-migrated visualization in Kibana
  - [x] Verification of Dashboards is not distorted in the supported Kibana version ^8.4.0

### PR DESCRIPTION
**Pull request by kush-elastic**
### Urgency
- High

### Activity Type
- Enhancement

## What does this PR do?
- Manually migrate `Azure Queue Storage` visualizations to the lens in the current Kibana version `8.9.0` itself. 

- Statistics for `Azure Queue Storage` Lens migration:
## Migration stats
  | Before Migration |   |   | After Migration |   |  
-- | -- | -- | -- | -- | -- | --
  | Lens | Visualization | Old Input Controls | Lens | Visualization | New control panels
[Azure Metrics] Queue Storage Overview | 0 | 9 | 1 | 9 | 0 | 1

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to the lens.
- [x] I have updated screenshots of the dashboard.
- [X] I have verified that the data counts are matching and panel aggregations are the same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.4.0 itself.

## Related issues

- Relates #7434 

Before Migration
image

After Migration
image

### CODE REVIEW

**Review by zmoog — APPROVED** [review]

**Review by zmoog — COMMENTED** [review]
The queue and message count values have decimals:

CleanShot 2023-09-08 at 12 32 30@2x

Isn't this the latest value for this metric?

**Review by zmoog — CHANGES_REQUESTED** [review]
Shouldn't these be integer values?

**Comment by kush-elastic** [comment]
@zmoog
Both the visualizations were already using Average aggregation before migration, we will need to create new tickets to address this issue. As part of this PR scope, our focus will be only on migration.

Screenshot 2023-09-08 at 4 34 15 PM

Screenshot 2023-09-08 at 4 36 30 PM

**Comment by zmoog** [comment]
The old dashboard version displays the count values as integers; how does it work?

**Comment by kush-elastic** [comment]
> The old dashboard version displays the count values as integers; how does it work?

it's working there because there is a way we can specify the custom format in TSDB.

Screenshot 2023-09-08 at 5 07 48 PM

**Comment by zmoog** [comment]
> it's working there because there is a way we can specify the custom format in TSDB.

So, the old version displays the average value but uses a custom format to show it as an integer, right?

**Comment by zmoog** [comment]
Displaying single count values with decimals doesn't feel right, but I'm not an expert. 

@drewdaemon, can you or someone in your team help us understand the best way to represent this kind of data? It could be just me.

**Comment by drewdaemon** [comment]
Custom formatter was [added to Lens](https://github.com/elastic/kibana/pull/158468) in 8.9. Does that cover this?


https://github.com/elastic/integrations/assets/315764/a81679ba-be9a-4e0e-93be-19b75893cd9f

**Comment by kush-elastic** [comment]
> Custom formatter was [added to Lens](https://github.com/elastic/kibana/pull/158468) in 8.9. Does that cover this?

Hey @zmoog @drewdaemon,
We are not able to export dashboards from `8.9.0` using the latest elastic-pacakge.
Error

**Comment by drewdaemon** [comment]
@kush-elastic good point. I had forgotten about https://github.com/elastic/kibana/pull/161969. 

The public release for 8.10 is tomorrow, so you could always wait a day or two. Up to @zmoog of course.

**Comment by kush-elastic** [comment]
> The public release for 8.10 is tomorrow, so you could always wait a day or two. Up to @zmoog of course.

@zmoog, what do you think? how should we proceed with this?
what I think is the issue itself is with the aggregation used in the current visualization. if we use the last value it should work just fine without any formatting. I don't see any reason to move dashboards to 8.10 just because of export issues.

We can merge this and create a new issue to track and resolve the wrong aggregation issue. that way we can stay on the current version and target more users at the same time.

**Comment by zmoog** [comment]
> We can merge this and create a new issue to track and resolve the wrong aggregation issue. that way we can stay on the current version and target more users at the same time.

Okay, sounds good.

**Review by zmoog — APPROVED** [review]

**Review by rajvi-elastic — APPROVED** [review]
LGTM!

**Pull request merged**
