### PR TITLE
[O11y][Mongodb Atlas] Alert Logs Datastream

### PR DESCRIPTION
**Pull request by milan-elastic**
Create the package for Mongodb Atlas Integration and Provide the support of **Alert logs**.

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists, [useful guidelines](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md) to follow
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to: 8.12.0
- [ ] TSDB enablement for the data stream

### Data dataset changes

_This entry is currently only recommended. It will be mandatory once we provide better support for it._

- [x] Sample event (`sample_event.json`) exists

### Related Issue
- Relates https://github.com/elastic/obs-infraobs-team/issues/1401

### Screenshots
mongodb_atlas-alert-logs-dashboard

### Known Issues:
Currently Following challenges are still open to solve for this PR:
- https://github.com/elastic/obs-infraobs-team/issues/1350
- https://github.com/elastic/obs-infraobs-team/issues/1351
- https://github.com/elastic/obs-infraobs-team/issues/1372

### CODE REVIEW

**Review by harnish-elastic — APPROVED** [review]
LGTM

**Comment by shmsr** [comment]
Here are some recommended changes:

```diff
diff --git a/packages/mongodb_atlas/data_stream/alert/agent/stream/input.yml.hbs b/packages/mongodb_atlas/data_stream/alert/agent/stream/input.yml.hbs
index 6dac5fe66..41bdf744c 100644
--- a/packages/mongodb_atlas/data_stream/alert/agent/stream/input.yml.hbs
+++ b/packages/mongodb_atlas/data_stream/alert/agent/stream/input.yml.hbs
@@ -36,7 +36,7 @@ redact:
 program: |
       (
         request(
-          "GET", 
+          "GET",
           state.url + "/api/atlas/v2/groups/" + state.group_id + "/alerts?" + {
             "pageNum": [string(state.page_num)],
             "itemsPerPage": ["100"]
@@ -44,7 +44,7 @@ program: |
           "Header": {
             "Accept": ["application/vnd.atlas." + string(now.getFullYear()) + "-01-01+json"]
           }
-        }).do_request().as(resp, 
+        }).do_request().as(resp,
           resp.StatusCode == 200 ?
             bytes(resp.Body).decode_json().as(body, {
               "events": body.results.map(event, { "response": event }),
@@ -54,7 +54,7 @@ program: |
             })
             :
             {
-              "events": [{"response":"The application encountered an error while retrieving the current page"}],
+              "events": [{"response":"Error: HTTP " + string(resp.StatusCode) + " — The application encountered an error while retrieving the current page"}],
               "want_more": false,
               "page_num": 1,
               "group_id": state.group_id
diff --git a/packages/mongodb_atlas/data_stream/alert/elasticsearch/ingest_pipeline/default.yml b/packages/mongodb_atlas/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
index f74fcd059..d5175a77e 100644
--- a/packages/mongodb_atlas/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
+++ b/packages/mongodb_atlas/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
@@ -114,6 +114,10 @@ processors:
       patterns:
         - '%{HOSTNAME:source.address}:%{POSINT:source.port}'
       ignore_missing: true
+      on_failure:
+        - append:
+            field: error.message
+            value: 'Failed to parse host_name_and_port: {{ _ingest.on_failure_message }}'
   - convert:
       field: source.port
       type: long
@@ -216,4 +220,4 @@ on_failure:
   - append:
       field: event.kind
       value: pipeline_error
-      allow_duplicates: false
\ No newline at end of file
+      allow_duplicates: false
diff --git a/packages/mongodb_atlas/data_stream/alert/fields/fields.yml b/packages/mongodb_atlas/data_stream/alert/fields/fields.yml
index 5f4899322..6d4a32619 100644
--- a/packages/mongodb_atlas/data_stream/alert/fields/fields.yml
+++ b/packages/mongodb_atlas/data_stream/alert/fields/fields.yml
@@ -9,24 +9,24 @@
           fields:
             - name: comment
               type: keyword
-              description: Comment left by the user who acknowledged the alert. Cloud Manager returns this value if the alert has been acknowledged.
+              description: Comment left by the user who acknowledged the alert. MongoDB Atlas returns this value if the alert has been acknowledged.
             - name: time
               type: date
-              description: Timestamp in ISO 8601 date and time format in UTC until which the alert has been acknowledged. Cloud Manager returns this value if the alert has been acknowledged.
+              description: Timestamp in ISO 8601 date and time format in UTC until which the alert has been acknowledged. MongoDB Atlas returns this value if the alert has been acknowledged.
             - name: user.name
               type: keyword
-              description: Username of the user who acknowledged the alert. Cloud Manager returns this value if the alert has been acknowledged.
+              description: Username of the user who acknowledged the alert. MongoDB Atlas returns this value if the alert has been acknowledged.
         - name: cluster
           type: group
           fields:
             - name: id
               type: keyword
               description: |-
-                Unique identifier for the cluster to which this alert applies. Cloud Manager returns this value if "eventTypeName" : "SHARDED_CLUSTER"
+                Unique identifier for the cluster to which this alert applies. MongoDB Atlas returns this value if "eventTypeName" : "SHARDED_CLUSTER"
             - name: name
               type: keyword
               description: |-
-                Name of the cluster to which this alert applies. Cloud Manager returns this value if "eventTypeName" : "SHARDED_CLUSTER"
+                Name of the cluster to which this alert applies. MongoDB Atlas returns this value if "eventTypeName" : "SHARDED_CLUSTER"
             - name: parent.id
               type: keyword
               description: Unique 24-hexadecimal character string that identifies the parent cluster to which this alert applies. The parent cluster contains the sharded nodes. MongoDB Cloud returns this parameter only for alerts of events impacting sharded clusters.
@@ -42,23 +42,23 @@
             - name: id
               type: keyword
               description: |-
-                unique identifier for the host to which the metric pertains. Cloud Manager returns this value if "eventTypeName" was set to one of the following : HOST_DOWN, OUTSIDE_METRIC_THRESHOLD, REPLICA_SET.
+                Unique identifier for the host to which the metric pertains. MongoDB Atlas returns this value if "eventTypeName" was set to one of the following : HOST_DOWN, OUTSIDE_METRIC_THRESHOLD, REPLICA_SET.
             - name: non_running.ids
               type: keyword
               description: List of unique 24-hexadecimal character strings that identify the replica set members that are not in PRIMARY nor SECONDARY state.
         - name: host_name_and_port
           type: keyword
           description: |-
-            Hostname and port of each host to which the alert applies. This can be a hostname, an FQDN, an IPv4 address, or an IPv6 address. Cloud Manager returns this value if "eventTypeName" was set to one of the following : HOST_DOWN, OUTSIDE_METRIC_THRESHOLD, REPLICA_SET.
+            Hostname and port of each host to which the alert applies. This can be a hostname, an FQDN, an IPv4 address, or an IPv6 address. MongoDB Atlas returns this value if "eventTypeName" was set to one of the following : HOST_DOWN, OUTSIDE_METRIC_THRESHOLD, REPLICA_SET.
         - name: last_notified.time
           type: date
-          description: Timestamp in ISO 8601 date and time format in UTC when the last notification was sent for this alert. Cloud Manager returns this value if notifications have been sent.
+          description: Timestamp in ISO 8601 date and time format in UTC when the last notification was sent for this alert. MongoDB Atlas returns this value if notifications have been sent.
         - name: metric
           type: group
           fields:
             - name: name
               type: keyword
-              description: Name of the measurement whose value went outside the threshold. Cloud Manager returns this value if "eventTypeName" was set to OUTSIDE_METRIC_THRESHOLD.
+              description: Name of the measurement whose value went outside the threshold. MongoDB Atlas returns this value if "eventTypeName" was set to OUTSIDE_METRIC_THRESHOLD.
             - name: unit
               type: keyword
               description: Relevant units for value.
@@ -83,18 +83,18 @@
         - name: replicaset.name
           type: keyword
           description: |-
-            Name of the replica set. Cloud Manager returns this value if "eventTypeName" was set to one of the following : BACKUPHOST_DOWN, OUTSIDE_METRIC_THRESHOLD, REPLICA_SET.
+            Name of the replica set. MongoDB Atlas returns this value if "eventTypeName" was set to one of the following : BACKUPHOST_DOWN, OUTSIDE_METRIC_THRESHOLD, REPLICA_SET.
         - name: resolved.time
           type: date
-          description: Timestamp in ISO 8601 date and time format in UTC when the alert was closed. Cloud Manager returns this value if "status":"CLOSED"
+          description: Timestamp in ISO 8601 date and time format in UTC when the alert was closed. MongoDB Atlas returns this value if "status":"CLOSED"
         - name: source_type.name
           type: keyword
           description: |-
-            Type of host being backed up when "eventTypeName" : "BACKUP". Cloud Manager can return one of the following : REPLICA_SET, SHARDED_CLUSTER, CONFIG_SERVER.
+            Type of host being backed up when "eventTypeName" : "BACKUP". MongoDB Atlas can return one of the following : REPLICA_SET, SHARDED_CLUSTER, CONFIG_SERVER.
         - name: status
           type: keyword
           description: |-
-            Current state of the alert. Cloud Manager can return one of the following : TRACKING.
+            Current state of the alert. MongoDB Atlas can return one of the following : TRACKING.
             The alert condition exists but has not persisted beyond the defined notification delay. For details, see Request Query Parameters. OPEN, CLOSED, CANCELLED.
         - name: tags
           type: keyword

```


s/Cloud Manager/ MongoDB Atlas? Looks good?

**Review by shmsr — COMMENTED** [review]
Please find my review in the comment where I have linked the diff patch.

**Pull request merged**
