### PR TITLE
[Logstash] Add Node Dashboards to Logstash integration package

### PR DESCRIPTION
**Pull request by robbavey**
## What does this PR do?

This PR adds dashboards to the Logstash integration.

These dashboards are intended as the first phase in a long term replacement of the
dedicated stack monitoring UI with standard Kibana visualizations, and are intended to
allow serverless users to continue to monitor Logstash.

This PR includes a Logstash overview dashboard, an overview of all the Logstash nodes, allowing
drill downs to individual nodes, with dashboards for general information on a single node, and a more
advanced view of a single node.

The intention of this commit is to mirror the existing stack monitoring UI as much as possible, using the
current `node.stats` data available.

Limitations:
 * Dashboards related to pipelines will be addressed in follow-up PRs - the current data in the integration does
   not fit well with standard Kibana visualizations, and will be addressed separately
 * The Advanced node view differs from the Stack Monitoring UI:
   * The size of the persistent queue is not presented here. PQ size statistics are only presented in the `node.state`
     document, which we do not want to use going forward. Additionally, the existing UI has significant limitations, in that
     only the total size across all PQs is shown, which is misleading when multiple PQs are available.
   * Additional graphs showing OS and Process CPU usage, and file descriptor usage are added

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

-

#### This PR:
Screen Shot 2023-09-07 at 11 57 32 AM

#### Existing Stack Monitoring UI:
Screen Shot 2023-09-07 at 11 59 01 AM

#### This PR:
Screen Shot 2023-09-07 at 11 57 46 AM

#### Existing Stack Monitoring UI:
Screen Shot 2023-09-07 at 11 59 08 AM

#### This PR: 
Screen Shot 2023-09-07 at 11 58 29 AM

#### Existing Stack Monitoring UI:
Screen Shot 2023-09-07 at 11 59 17 AM

#### This PR:
Screen Shot 2023-09-07 at 11 58 48 AM

#### Existing Stack Monitoring UI
Screen Shot 2023-09-07 at 11 59 28 AM

### CODE REVIEW

**Comment by miltonhultgren** [comment]
I'll review this now, have you considered linking these new dashboards into the SM UI, similar to what was done recently for Ingest Pipeline monitoring? 
https://github.com/elastic/kibana/pull/149721

**Review by miltonhultgren — APPROVED** [review]
Not much to review given the generated dashboard JSON!

**Comment by robbavey** [comment]
@miltonhultgren Thank you for the fast turnaround!

> I'll review this now, have you considered linking these new dashboards into the SM UI, similar to what was done recently for Ingest Pipeline monitoring?

This commit is the starting phase of a project to replace the stack monitoring UI for Logstash with standard Kibana visualizations, rather than rely on the custom UI. 
In particular, we are doing this now to allow Logstash to be monitored with the serverless solution, which does not include any stack monitoring UI at all.
Eventually, when we port over the missing functionality from the stack monitoring UI, I would anticipate that we would replace that with a link to the Overview dashboard here.

> The only thing to note is that it should be possible to make the dashboards also read from the .monitoring-* data streams to make it work with Beats collection as well, which would make it available to use also for ESS users.

Done - I've added an index pattern along the same lines as that done in the `elasticsearch` package.

**Comment by miltonhultgren** [comment]
> Eventually, when we port over the missing functionality from the stack monitoring UI, I would anticipate that we would replace that with a link to the Overview dashboard here.

Sounds good to me!

**Comment by miltonhultgren** [comment]
Yes, this LGTM!

**Pull request merged**
