### PR TITLE
[O11y][AWS CloudTrail] Migrate AWS `CloudTrail` dashboard visualizations to lenses in Kibana 8.7.1

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?
- Manually migrate AWS `CloudTrail` visualizations to the lens in the current Kibana version `8.7.1` itself. 

- Statistics for Usage Overview Lens migration:

<html>
<body>

AWS Cloudtrail Dashboards | Before Migration |   |   |   | After Migration |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
  | Maps | Search | Lens | Visualization | Maps | Search | Lens | Visualization
[Logs AWS] CloudTrail | 1 | 1 | 0 | 6 | 1 | 1 | 6 | 0

</body>
</html>

Notes: 
- Increase the `Donut charts` size across the dashboard and added the legend as well as show values inside and outside for better visualize and readability.
- For the `CloudTrail Event Outcome over time [Logs AWS]`, in the before migrated visualization, we have `Show missing values` toggle on! Hence if the field (`event.outcome`) defined for that visualization is not present, then it will show the `count of records` and also put the labels with (`unknown`). Please refer the below screenshot for more information.
`Before migration`:
image
Now while migrating the visualization to lens, found that if we need to implement the same functionality, we need to do `Group remaining values as "Other"` toggle on and then we can able to do `include documents without the selected field`.  Please refer the below screenshot for more information.
`After migration`:
image
Now for the `Show missing values`  toggle, in lens we have alternative for this functionality as `include documents without the selected field` toggle. To enable this toggle in lens I must need to enable the `Group remaining values as "Other"` toggle. Hence I should proceed with enable the Group remaining values as "Other" toggle.
Q. What happens when I enable Group remaining values as "Other" toggle?
Ans. If I enable Group remaining values as "Other" toggle, user can have the additional information in `Other` named bucket other than defined size. For example, if I have the 7 unique values for one field and I have defined my size of the breakdown as 5, I will get 2 unique value informations as `Other` named bucket in the visualization.
- For `CloudTrail Event Outcome over time [Logs AWS]` chart, before migrated screenshot has hardcoded the colors over color palette to visualize the `success` and `failure` . However while migrating this visualization into lens, we are not able to hardcode the colors over `color palette`. 
- Screenshot for dashboard is outdated currently, please refer this `before` migrated screenshot.
image

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.7.1 itself.

## Related issues

- Relates #6141
- Relates #6206

### CODE REVIEW

**Comment by drewdaemon** [comment]
Thanks, @harnish-elastic !

Can we change the palettes for the visualizations to "default"?


Old palette:
Screenshot 2023-03-30 at 4 37 09 PM

Default palette
Screenshot 2023-03-30 at 4 37 24 PM

**Comment by harnish-elastic** [comment]
> Thanks, @harnish-elastic !
> 
> Can we change the palettes for the visualizations to "default"?
> 
> Old palette: Screenshot 2023-03-30 at 4 37 09 PM
> 
> Default palette Screenshot 2023-03-30 at 4 37 24 PM

Thanks, @drewdaemon for the review!

I think the `before migrated` visualization uses the `compatibility` color palette.

`Before migrated` visualization color palette (inside the visualization): 
Before migrated

Also, please refer the below visualization taken from the dashboard! It is showing the different hardcoded colors, that lens doesn't support!
From the dashboard side

Let me know if you still strongly feel to change the color palette to `default`!

**Comment by rajvi-elastic** [comment]
> But, for the visualizations using the `compatibility` palette, let's use the `default` palette.

@drewdaemon, Regarding color palette, What if TSVB visualization have configured gradient color palette? Should we configure positive, negative, warm etc. color palette or keep the default one in lens?

Below is the screenshot of ELB Access Log dashboard before and after migration. In area charts, gradient color palettes have been used. When we migrated to the lens, we tried to set the closest color palette from the options. 

### ELB Access Log dashboard **before** Migration
screencapture-localhost-5601-app-dashboards-2023-05-31-11_34_38


### ELB Access Log dashboard **after** Migration
screencapture-localhost-5601-app-dashboards-2023-05-31-13_05_12

Let me know what are your thoughts on this?

**Review by drewdaemon — APPROVED** [review]

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic I think you did well there. If it seems like the colors were intentionally chosen in the TSVB visualization, it probably makes sense to keep them.

@drewdaemon Understood, Thank you for the explanation!

**Review by rajvi-elastic — APPROVED** [review]

**Review by zmoog — APPROVED** [review]

**Pull request merged**
