### PR TITLE
[AWS] Support Cloudtrail tlsDetails field

### LINKED ISSUE #6300: Cloudtrail Ingest Pipeline: Does not parse tlsDetails structure
With AWS TLS 1.0 and 1.1 depreciation coming in June, please add to the ingest pipeline parsing of tlsDetails structure. 

```
{
    ...
    "tlsDetails": {
        "tlsVersion": "TLSv1.2",
        "cipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "clientProvidedHostHeader": "ssm.us-west-2.amazonaws.com"
    }
  ...
}
```

Reference:
https://aws.amazon.com/blogs/mt/using-aws-cloudtrail-lake-to-identify-older-tls-connections-to-aws-service-endpoints/

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Parses tlsDetails field

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- closes #6300

### CODE REVIEW

**Comment by legoguy1000** [comment]
bump

**Comment by legoguy1000** [comment]
I haven't had the time to follow up on this or push it along. It should be
GTG, might need a rebase.

**Review by efd6 — APPROVED** [review]
LGTM after the builder can be made to run and pass.

**Review by kaiyan-sheng — APPROVED** [review]
Thank you for making the change!

**Review by efd6 — APPROVED** [review]
Still LGTM

**Pull request merged**
