### PR TITLE
#1439-sample_event-tomcat

### PR DESCRIPTION
**Pull request by kush-crest**
## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Author's Checklist

- [x] sample_event.json should be present at integrations/packages/tomcat/data_stream/log

## How to test this PR locally

- Clone Branch and move to tomcat package directory.
- Run following command to verify sample_event.json file. `elastic-package test static -v`

## Related issues

- Related #1439

### CODE REVIEW

**Comment by kush-crest** [comment]
Yeah
I have question.
Do i need to add entry in changelog.yml?
I am not sure so please help me understand that.
Maybe this error is also because of that.

**Comment by jsoriano** [comment]
>  Do i need to add entry in changelog.yml?

No, you don't need to add an entry in the changelog for this change.

**Comment by jsoriano** [comment]
Ok, I think this was being affected by https://github.com/elastic/beats/issues/27299, good to go now, thanks!

**Review by jsoriano — APPROVED** [review]

**Pull request merged**
