### PR TITLE
[ti_rapid7_threat_command] Ensure event.kind is correctly set for pipeline errors

### PR DESCRIPTION
**Pull request by MakoWish**
## What does this PR do?

Modify ti_rapid7_threat_command integration to correctly set `event.kind` for pipeline errors and ensure `error.message` is an array.

## Checklist

- [X] I have reviewed tips for building integrations and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's changelog.yml file.
- [ ] I have verified that Kibana version constraints are current according to guidelines.
 
## Author's Checklist

- [ ]  

## Related issues

* For #6582

## Screenshots

### CODE REVIEW

**Review by efd6 — COMMENTED** [review]
You've found some that my automation missed, but missed the ones that I found. Can you also add changes for the default.yml files under data_stream/{alert,ioc,vulnerability}/elasticsearch/ingest_pipeline?

**Comment by MakoWish** [comment]
Oops! Forgot to change my commit message, but that last one was for the three `default.yml` files you pointed out.

**Review by efd6 — APPROVED** [review]

**Pull request merged**
