### PR TITLE
[TrendMicro VisionOne] Fix Detection API TMV1-Query header

### PR DESCRIPTION
**Pull request by kcreddy**
## Proposed commit message
The Detection API for [TrendMicro Vision One](https://automation.trendmicro.com/xdr/api-v3#tag/Search/paths/~1v3.0~1search~1detections/get) takes a required header `TMV1-Query` which needs to contain an [operator](https://automation.trendmicro.com/xdr/api-v3#tag/Search/paths/~1v3.0~1search~1detections/get:~:text=uuid%27%20%2D%20Match%20type%20support%3A%20Partial%20match-,Supported%20operators%3A,-%27%3A%27%20%2D%20Abbreviation%20of%20the%20operator%20%22equal%20to) to perform the query. Currently there is no operator which is causing the API to return zero results. This PR fixes the header and adds `:*` to the existing operator to query all events containing `uuid`.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates https://github.com/elastic/sdh-beats/issues/3899

### CODE REVIEW

**Review by bhapas — COMMENTED** [review]
Possible to test this in system test?

**Comment by kcreddy** [comment]
@bhapas Added system test for the same.

**Review by bhapas — APPROVED** [review]
LGTM

**Comment by hussein759** [comment]
@kcreddy and @bhapas,

Regarding the TrendMicro integration for detection with the API path /v3.0/search/detections: When the header {'Authorization': 'Bearer ' + token, 'TMV1-Query': '(uuid:*)'} is added to the query, the result contains a significant amount of data — over 10,000 hits in the last hour. However, after updating to version 1.12.1, the output seems to be limited to roughly 10 events or fewer per hour from vision_one_detection.

Is it accurate that when uuid is set as a wildcard, it should fetch all events? It seems that this expected behavior is not being observed in the recent update. Has this been thoroughly tested?

**Comment by bhapas** [comment]
> @kcreddy and @bhapas,
> 
> Regarding the TrendMicro integration for detection with the API path /v3.0/search/detections: When the header {'Authorization': 'Bearer ' + token, 'TMV1-Query': '(uuid:*)'} is added to the query, the result contains a significant amount of data — over 10,000 hits in the last hour. However, after updating to version 1.12.1, the output seems to be limited to roughly 10 events or fewer per hour from vision_one_detection.
> 
> Is it accurate that when uuid is set as a wildcard, it should fetch all events? It seems that this expected behavior is not being observed in the recent update. Has this been thoroughly tested?

@hussein759 Any notable logs in the agent logs? Like `Dropped Event` or `log.error` etc?

**Comment by hussein759** [comment]
Thanks bapas, i think the request field is again causing issue after this update which was bug of earlier version for request field and it was fixed earlier,uploading the image where error.message shows field [request] not present as part of path which again i m assuming is an array expected but its not mapped correctly.. image attached for your reference
image

**Comment by hussein759** [comment]
Thanks @kcreddy, request field issue is similar to #7871, this was bug and it was fixed, if u refer this issue for request field you will know exactly whats going on, as per trendmicro document it is not mention that request field will contain array however the elastic developer managed to fix it to include the array and @bhapas had raised this issue earlier for this!

**Comment by hussein759** [comment]
@Bhapas, sure here is the event.original field

{"act":["not blocked"],"aggregatedCount":"1","app":"SMB2","appGroup":"CIFS","aptRelated":"0","clientFlag":"src","cnt":"8","compressedFileSize":"0","dceHash1":"0","dceHash2":"0","detectionType":"1","deviceDirection":"outbound","deviceGUID":"73497B359ABF-4189A916-9CD9-23B1-C465","deviceMacAddress":"4c:d9:8f:aa:0a:12","devicePayloadId":"99:10786206:::","deviceRiskConfidenceLevel":3,"dhost":"aeadvsa044.internal.adsic.abudhabi.ae","dmac":"00:00:0c:07:ac:96","dpt":445,"dst":["192.168.15.25"],"dstGroup":"Default","dstZone":"1","dvc":["192.168.5.221"],"dvchost":"EUADVSATM05","eventId":"100119","eventName":"SECURITY_RISK_DETECTION","eventSourceType":3,"eventTime":1696921180000,"eventTimeDT":"2023-10-10T06:59:40+00:00","filePath":"\\","filePathName":"\\","fileSize":"0","hasdtasres":"No","interestedGroup":"Default","interestedHost":"sam-b-df-09.internal.samuel.eu","interestedIp":["192.168.20.233"],"isHidden":"Yes","logKey":"23497B359ABF-4189A916-9CD9-23B1-C465_DDI-3.8-CAV-JSONv1-en_10786206","malType":"OTHERS","malTypeGroup":"Others","overSsl":"Not over SSL/TLS","pComp":"NCIE","peerGroup":"Default","peerHost":"df-08.internal.samuel.eu","peerIp":["192.168.20.233"],"pname":"Deep Discovery Inspector","potentialRisk":"1","productCode":"pdi","pver":"6.5.1129","remarks":"[\"IP address: 192.168.20.233\"]","rt":"2023-10-10T06:59:40.0000000Z","rtDate":"2023-10-10T00:00:00.0000000Z","rtHour":10,"rtWeekDay":"Tuesday","rt_utc":"2023-10-10T06:59:40.0000000Z","ruleId":3498,"ruleName":"DOWNLOAD FILE - SMB2(REQUEST) - BETA","searchDL":"DDL","senderGUID":"73497B359ABF-4189A916-9CD9-23B1-C465","senderIp":["192.168.5.221"],"severity":2,"shost":"pamm-l-df-09.internal.samuel.eu","smac":"98:72:5d:2d:13:06","spt":52066,"src":["192.168.20.233"],"srcGroup":"Default","srcZone":"1","threatType":"99","uuid":"f4b08e7d-716e-4bc9-9569-2645b7cdb958","vLANId":4095}

**Comment by kcreddy** [comment]
In your sample above the field `request` doesn't exist unlike the other logs. Hence you have the `error.message` populated. https://github.com/elastic/integrations/pull/8160 should fix it.

Going back to earlier issue with your reduced data, were you seeing higher data ingestion with earlier integration version and when upgraded to `1.12.1` you saw it reduced?

**Comment by hussein759** [comment]
@kcreddy Observations on Vision One Detection Event Categories:

Categories with request Data in the "trend_micro_vision_one.detection.request" field:

    Web_Threat_Detection, Web_Policy_Violation, Message_Suspicious_Detection, Security_Risk_Detection.

For above categories, the "trend_micro_vision_one.detection.request" field displays data.

Categories Lacking Data in the "trend_micro_vision_one.detection.request" field mentioned below
For these categories, there is no data present in the "trend_micro_vision_one.detection.request" field, leading to the appearance of an error message.
field [request] not present as part of path [trend_micro_vision_one.detection.request]


    BEHAVIORAL_VIOLATION, INTEGRITY_MONITORING_EVENT, APPLICATION_CONTROL_VIOLATION, FIREWALL_POLICY_VIOLATION.
    
    I can see u have made upgrade request to 1.12.2 to exclude error message from field request if it doesnt contain any data
    so one it is pushed to epr this might also solve the request field issue

For the uuid changes you have made with * the logs count are fine and that is no longer any issue

Thanks for all the work!, if u need any more info pls let me know.

**Comment by kcreddy** [comment]
Awesome, thanks for the explanation. That helps great deal!

**Pull request merged**
