### PR TITLE
[Windows] Enable TSDB for service metrics dataset.

### LINKED ISSUE #6993: Windows TSDB Enablement
## Test Environment Setup
- [x] Creation of Windows Test Environment

## Datastream : perfmon 

Note: According to Andres, when examining the expected usage of the metrics dataset "perfmon," it appears more suitable to treat it as an input package, where users can query specific metrics. Based on this observation, he recommends postponing its migration for the time being. As a result, we will only migrate the service dataset as part of this migration task.

~- [ ]Add dimension fields~
  ~- [ ] Adding metric_type mapping~
#### Verification and validation
  ~- [ ] Verification of data in visualisation after enabling TSDB flag in kibana~
  ~- [ ] Verification of the count of documents (before & after TSDB enablement) in Discover Interface~
  ~- [ ] Verify if dimension field mapping is correct in the data stream template.~

## Datastream : service
  - [x] Add dimension fields 
          https://github.com/elastic/integrations/pull/7172
  - [x] Adding metric_type mapping
         https://github.com/elastic/integrations/pull/7200
#### Verification and validation
  - [x] Verification of data in visualisation after enabling TSDB flag in kibana
  - [x] Verification of the count of documents (before & after TSDB enablement) in Discover Interface.
  - [x] Verify if dimension field mapping is correct in the data stream template.

Enable TSDB by default - https://github.com/elastic/integrations/pull/7206

## Screenshots

image
image
image
image
image

### PR DESCRIPTION
**Pull request by ritalwar**
- Enhancement

## What does this PR do?

This PR enables TSDB by default for Windows `service` datastream.
Reference to a [blog post](https://www.elastic.co/blog/70-percent-storage-savings-for-metrics-with-elastic-observability) that elaborates on the performance enhancements achieved with TSDB.

## How to test this PR locally
 - [x] 1. Setup Windows VM
 - [x] 2. Build verification
`elastic-package build`
`elastic-package stack up -v -d --services package-registry`

- [x] 3. Document count verification after TSDB enablement
- [x] 4. Dashboard verification after enablement.
- [x] 5. Index template verification
- [x] 6. Index mapping verification
- [x] 7. Index settings verification.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #6993 

## Screenshots

Refer https://github.com/elastic/integrations/issues/6993

### CODE REVIEW

**Review by rdner — COMMENTED** [review]
Could you please list the testing steps you've taken to validate it working? Would be nice to have it in the description.

**Comment by ritalwar** [comment]
> Could you please list the testing steps you've taken to validate it working? Would be nice to have it in the description.

Please check this [reference] (https://github.com/elastic/integrations/issues/6993#issuecomment-1660113474). 
I've also made updates to the description of this ticket.

**Review by rdner — APPROVED** [review]
The change LGTM, however I'd like to see a link that supports this claim in the changelog:

> This dramatically reduces storage for metrics and is expected to progressively improve query performance.

**Comment by mlunadia** [comment]
> The change LGTM, however I'd like to see a link that supports this claim in the changelog:
> 
> > This dramatically reduces storage for metrics and is expected to progressively improve query performance.

@ritalwar if links can be added to the changelog please use this one https://www.elastic.co/blog/70-percent-storage-savings-for-metrics-with-elastic-observability

**Review by leehinman — APPROVED** [review]
LGTM

I was able to install on Windows Server 2022, ingest worked fine and Dashboards worked fine.

**Review by lalit-satapathy — COMMENTED** [review]
LGTM

**Review by lalit-satapathy — APPROVED** [review]

**Pull request merged**
