### PR TITLE
[O11y][MySQL] Migrate `[Logs MySQL] Overview` dashboard visualizations to lens in kibana 8.8.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for MySQL integration package

- Statistics for MySQL Lens migration:

<html>
<body>

MySQL dashboard | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Logs MySQL] Overview | 0 | 5 | 5 | 0
  | 0 | 5 | 5 | 0

</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.6.0 itself.

## Related issues

- Relates #5221 

Note:

The Kibana files and before migration dashboard image is not synced. Please find below screenshot to compare before and after migrated panels.
Logs Mysql  Overview

### CODE REVIEW

**Review by agithomas — COMMENTED** [review]
Can u update the query time duration unit and convert to sec /min/ hour unit?

**Comment by agithomas** [comment]
@lalit-satapathy , the version change is a steep jump to 8.6.0 for MySQL. Are there concerns?

@rajvi-elastic , can you please share the details what led to this steep jump?

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic , can you please share the details what led to this steep jump?

@agithomas, Below are the 3 panels which uses conditional operations (`ifelse`)  which is supported in 8.6 and later versions.
<html>
<body>


[Metrics MySQL] Database Overview |  Minimum Kibana Version
-- | --
Buffer Pool Utilization | 8.6.0 | Adds conditional operations in the Lens formula
Buffer Pool Efficiency | 8.6.0 | Adds conditional operations in the Lens formula
Network Traffic | 8.6.0 | Adds conditional operations in the Lens formula


</body>
</html>

**Comment by rajvi-elastic** [comment]
> Can u update the query time duration unit and convert to sec /min/ hour unit?

@agithomas, According to the [field description](https://github.com/elastic/integrations/tree/main/packages/mysql#:~:text=event.duration,long), the values are in nanoseconds. Should we convert it to milliseconds or seconds?

**Comment by agithomas** [comment]
> @agithomas, According to the [field description](https://github.com/elastic/integrations/tree/main/packages/mysql#:~:text=event.duration,long), the values are in nanoseconds. Should we convert it to milliseconds or seconds?

Yes, please proceed with representing time in human readable format.

**Comment by agithomas** [comment]
> > @rajvi-elastic , can you please share the details what led to this steep jump?
> 
> @agithomas, Below are the 3 panels which uses conditional operations (`ifelse`) which is supported in 8.6 and later versions.
> 
> [Metrics MySQL] Database Overview	 Minimum Kibana Version	Functionality
> Buffer Pool Utilization	8.6.0	Adds conditional operations in the Lens formula
> Buffer Pool Efficiency	8.6.0	Adds conditional operations in the Lens formula
> Network Traffic	8.6.0	Adds conditional operations in the Lens formula

@lalit-satapathy , Please note this dependency. Please let us know if there exist any concerns.

**Comment by agithomas** [comment]
> @agithomas, lens doesn't support human readable format for duration. However, we can normalize the value to millisecond/second using division function.

Please consider milli-seconds, consider the usecase here of query time. 
Also, please see if you can add decimals of 2 numbers to handle when duration is less than 0ms
Please add the unit (milli second) or (ms) in the column title.

**Comment by rajvi-elastic** [comment]
> > @agithomas, lens doesn't support human readable format for duration. However, we can normalize the value to millisecond/second using division function.
> 
> Please consider milli-seconds, consider the usecase here of query time. Also, please see if you can add decimals of 2 numbers to handle when duration is less than 0ms Please add the unit (milli second) or (ms) in the column title.

@agithomas, PR has been updated with suggested changes.

**Comment by lalit-satapathy** [comment]
> @lalit-satapathy , the version change is a steep jump to 8.6.0 for MySQL. Are there concerns?

Need to wait for large version changes like this below, as we are discussing with others:

```
 - kibana.version: "^7.14.0 || ^8.0.0"
 + kibana.version: "^8.6.0"

```

**Comment by lalit-satapathy** [comment]
> > @lalit-satapathy , the version change is a steep jump to 8.6.0 for MySQL. Are there concerns?
> 
> Need to wait for large version changes like this below, as we are discussing with others:
> 
> ```
>  - kibana.version: "^7.14.0 || ^8.0.0"
>  + kibana.version: "^8.6.0"
> ```

We should go ahead with version change for Lens and TSDB will soon migrate this package to 8.8

**Comment by lalit-satapathy** [comment]
FYI mysql package is already at 8.8.0 kibana version, so this can be un-gated.

**Comment by rajvi-elastic** [comment]
> FYI mysql package is already at 8.8.0 kibana version, so this can be un-gated.

Yes @lalit-satapathy, I have updated the PR.

**Review by agithomas — APPROVED** [review]
LGTM!

**Review by harnish-elastic — APPROVED** [review]
LGTM!

**Pull request merged**
