### PR TITLE
[New Integration] GitLab

### PR DESCRIPTION
**Pull request by tehbooom**
- Enhancement

## Proposed commit message

New integration for GitLab

Some examples logs were pulled from the [documentation](https://docs.gitlab.com/ee/administration/logs/)

The other logs were pulled from a test GitLab instance using the free tier.

Not all logs from GitLab are collected since we need a dev license and more example logs.

The following logs will need to be ingested from another integration:

- nginx
- postgresql
- redis
- prometheus
- mattermost

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## Related issues

- Relates #9122 
- Relates #1741

### CODE REVIEW

**Comment by Alphayeeeet** [comment]
@tehbooom Thanks for looking into this topic. Is it possible to use use the mentioned other integrations inside the Gitlab integration as a one for all solution?

I hope it's understandable what I mean. So that I don't need an integration policy for each of the components as the GitLab integration should manage all that (preferably configurable in the policy settings).

**Comment by tehbooom** [comment]
> The following logs will need to be ingested from another integration:
> 
> * nginx
> * postgresql
> * redis
> * prometheus
> * mattermost

Hey @Alphayeeeet , there have been discussions around using one ingest pipeline for two integrations however at this time it is not supported. Ive decided to not recreate the pipelines in this integration incase we do in the future move towards utilizing more than one integration pipeline for a single integration. As of now, you will need to add more integrations to the policy to fully monitor all of GitLab.

**Comment by efd6** [comment]
Two comments on this.
1. There is a GitLab CE [PR](https://github.com/elastic/integrations/pull/9747) open at the moment. It may be good to think about whether it's possible to simplify the surface for integration users in some way.
2. The size of this PR is to large to reasonably review with any real quality control. It would be good to reduce the chunk size of review objects. I suggest prioritising the data streams and making a series of PR that add them in priority order.

**Comment by tehbooom** [comment]
Closing since it is a duplicate of https://github.com/elastic/integrations/pull/9747. After it is merge will start to add more datastreams for this PR.

**Pull request closed without merging**
