### PR TITLE
[azure logs] use one input + routing for all data streams (WIP)

### PR DESCRIPTION
**Pull request by zmoog**
## Proposed commit message

Switch the integration package from the one-input-per-data-stream model to the one-input model.

One input per data stream model:

image

One input model:

image

In the one-input model, there is only one azure-eventhub input running and sending events to the `events` data stream. In the `events` data stream, the ingest pipeline performs these tasks:

- discover and set the `event.dataset` field using the `category` field in the event.
- use the `event.dataset` field to reroute the event to the target data stream.

The discover process uses the following logic:

- if the event doesn't have a category, it sets `event.dataset` to `azure.eventhub` (the generic integration)
- if the event does have a category, it sets `event.dataset` to `azure.platformlogs` (it's probably an Azure log)
- if the event category is supported, it sets `event.dataset` to specific one like `azure.activitylogs` or `azure.signinlogs`.

After the discovery step, the routing rules use the `event.dataset` value to forward the events to the best available target data stream.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## Author's Checklist

- [ ] 

## Related issues

- Closes https://github.com/elastic/integrations/issues/11251

### CODE REVIEW

**Comment by zmoog** [comment]
Here's the latest iteration for the integration settings to evidence the recommended single data stream (v2) vs. the legacy multiple data stream (v1) solutions:

image

**Comment by defutek-tj** [comment]
@zmoog - do you have any updates as to the timeframe when this will be ready / released?

**Comment by zmoog** [comment]
> @zmoog - do you have any updates as to the timeframe when this will be ready / released?

Hey @defutek-tj, my apologies for the delay.

We clarified the Event Hub SDK behavior with the Event Hub team, and now we can move forward with the first update.

In the following integration update, we will ship a new data stream v2 (preview) to handle all the log categories. ETA is next week.

**Comment by zmoog** [comment]
I'm replacing this PR with the simpler and backwards compatible https://github.com/elastic/integrations/pull/11984

**Pull request closed without merging**
