### PR TITLE
Change s3 input name to aws-s3

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
## What does this PR do?

NOTE: This PR should wait till 7.12.0 release before merging.

This PR is to change `s3` input name to `aws-s3` in order to match the renaming we did in Filebeat. 
Since the PR in Beats merged for 7.12, this only works when testing with:
```
elastic-package stack up --version 7.12.0-SNAPSHOT -v -d
```

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
@mtojek This only works with filebeat 7.12 so should I wait till after 7.12 get released before merging this? TIA!

**Review by mtojek — COMMENTED** [review]
The 7.12 stack has been merged, feel free to rebase this branch against master.

BTW you can think also about system tests for the AWS integration as it's also available (not necessary as part of this PR).

**Comment by kaiyan-sheng** [comment]
@mtojek Yeah I will create a separate PR (hopefully soon) for system tests!! Thanks!

**Comment by mtojek** [comment]
The build is failing due to this: https://github.com/elastic/beats/issues/24198 . If it's not an urgent issue I would wait for the correct Docker images.

**Review by mtojek — APPROVED** [review]
If the CI is happy, I'm happy too :)

**Pull request merged**
