### PR TITLE
[AWS docs] Add required permissions for Custom AWS Logs

### PR DESCRIPTION
**Pull request by alaudazzi**
This PR adds the specific permissions required to use the [Custom AWS Logs](https://www.elastic.co/docs/current/integrations/aws_logs) integration, both for `aws-s3` input and `aws-cloudwatch` input.

Closes https://github.com/elastic/integrations/issues/11603.

### CODE REVIEW

**Review by lucabelluccini — COMMENTED** [review]
Hello @alaudazzi 
I would involve the owners / developer of the `aws_logs` integration for a double check.

To me, the pointers to the Filebeat `aws-s3` doc and `cloudwatch` doc make sense,  but I would have expected that the whole `Requirement` section of https://www.elastic.co/docs/current/integrations/aws#requirements would have been ported to https://www.elastic.co/docs/current/integrations/aws_logs.
IIUC, the permissions should be similar (just the AWS integration Requirement section mixes up both the permissions required for S3 and Cloudwatch).
Obviously the "cost" of this is we're duplicating the content.

If instead we want to tackle this problem properly in the follow up issue https://github.com/elastic/integrations/issues/11793, then this PR should be ok to allow users to understand which permissions are required.

I would ask @octavioranieri to review.

**Comment by octavioranieri** [comment]
+1 to @lucabelluccini suggestions above. 

It's better to have it within the page (and product) instead of referencing to an external page.
we already do that under the parent page for https://www.elastic.co/docs/current/integrations/aws#aws-permissions

**Comment by alaudazzi** [comment]
Duplicating content often leads to maintenance issues that are difficult to track.

**Review by kaiyan-sheng — APPROVED** [review]

**Comment by kaiyan-sheng** [comment]
@alaudazzi I agree with Luca on `the whole Requirement section` should be included as well. This is not necessarily permissions but should be mentioned as required for using the integration.

**Comment by alaudazzi** [comment]
@kaiyan-sheng @octavioranieri 
Thank you for your feedback.

@lucabelluccini 

> If instead we want to tackle this problem properly in the follow up issue https://github.com/elastic/integrations/issues/11793, then this PR should be ok to allow users to understand which permissions are required.

Yes, let's do that. 

Please note that one of the points highlighted in the follow-up issue is `locate the permissions set in one place to facilitate content standardization and maintenance`.

**Pull request merged**
