### PR TITLE
Oracle Dashboard fix for showing Parse count total

### PR DESCRIPTION
**Pull request by agithomas**
Type of change
- Bug

## What does this PR do?

Oracle Dashboard for showing Parse count total is not correct. The PR indent to resolve this problem

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

### CODE REVIEW

**Review by muthu-mps — COMMENTED** [review]
While looking into the dashboard file for this change found couple of issues which needs to be addressed,
+ `oracle.pga_sga.sga_total_memory`, `oracle.pga_sga.sga_free_memory` These fields also doesn't exist in fields.yml. Can we point to the appropriate fields to get metrics in the visualisation.
+ version: `8.4.0-SNAPSHOT` - The snapshot version should be excluded from this dashboard.
+ `"InActive Session Count [Metrics Oracle] (copy)" `- Please remove copy from visualisation name.

**Comment by agithomas** [comment]
> While looking into the dashboard file for this change found couple of issues which needs to be addressed,
> 
> * `oracle.pga_sga.sga_total_memory`, `oracle.pga_sga.sga_free_memory` These fields also doesn't exist in fields.yml. Can we point to the appropriate fields to get metrics in the visualisation.
> * version: `8.4.0-SNAPSHOT` - The snapshot version should be excluded from this dashboard.
> * `"InActive Session Count [Metrics Oracle] (copy)" `- Please remove copy from visualisation name.

Issues resolved.

**Comment by muthu-mps** [comment]
> > While looking into the dashboard file for this change found couple of issues which needs to be addressed,
> > 
> > * `oracle.pga_sga.sga_total_memory`, `oracle.pga_sga.sga_free_memory` These fields also doesn't exist in fields.yml. Can we point to the appropriate fields to get metrics in the visualisation.
> > * version: `8.4.0-SNAPSHOT` - The snapshot version should be excluded from this dashboard.
> > * `"InActive Session Count [Metrics Oracle] (copy)" `- Please remove copy from visualisation name.
> 
> Issues resolved.

`Snapshot` version is not completely removed from both the dashboards. Can you please check once ?

While looking at the other Dashboards which doesn't have any change is exported with `8.3 version` of Kibana. The Dashboards that are updated is exported with `8.4 version`. Is it okay to have different Dashboard's of a same integration with different Kibana versions ?

**Comment by agithomas** [comment]
> While looking at the other Dashboards which doesn't have any change is exported with `8.3 version` of Kibana. The Dashboards that are updated is exported with `8.4 version`. Is it okay to have different Dashboard's of a same integration with different Kibana versions ?

It won't create a problem. The same dashboard is tested against 8.3.0 as well. No change in JSON output. It works ok

**Review by muthu-mps — APPROVED** [review]
looks good.

**Pull request merged**
