### PR TITLE
Add missing field definitions for the SQLServer integration

### LINKED ISSUE #6070: [microsoft_sqlserver.audit] Conflicting host.ip and message field definition
Microsoft SQL Server integration version: 1.19.0

Component template "logs-microsoft_sqlserver.audit@package" should match "logs-microsoft_sqlserver.log@package"
The audit @package contains fewer field definitions for host and message is missing.
Causing fields to be mapped as keyword by the .fleet_globals-1
In the logs-* data view **host.ip** is conflicting on **ip,keyword** and **message** has **text,keyword**
The latter also causes an error when trying to setup the ML job in Observability -> Logs -> Categories

> At least one index matching logs-* has a field called message without the correct type.

> Your index configuration is not valid. Select at least one index name.

Proposal:
Add the following to logs-microsoft_sqlserver.audit@package instead of only host.name
```
"host": {
                "properties": {
                  "hostname": {
                    "ignore_above": 1024,
                    "type": "keyword"
                  },
                  "os": {
                    "properties": {
                      "build": {
                        "ignore_above": 1024,
                        "type": "keyword"
                      },
                      "kernel": {
                        "ignore_above": 1024,
                        "type": "keyword"
                      },
                      "codename": {
                        "ignore_above": 1024,
                        "type": "keyword"
                      },
                      "name": {
                        "ignore_above": 1024,
                        "type": "keyword",
                        "fields": {
                          "text": {
                            "type": "text"
                          }
                        }
                      },
                      "family": {
                        "ignore_above": 1024,
                        "type": "keyword"
                      },
                      "version": {
                        "ignore_above": 1024,
                        "type": "keyword"
                      },
                      "platform": {
                        "ignore_above": 1024,
                        "type": "keyword"
                      }
                    }
                  },
                  "domain": {
                    "ignore_above": 1024,
                    "type": "keyword"
                  },
                  "ip": {
                    "type": "ip"
                  },
                  "containerized": {
                    "type": "boolean"
                  },
                  "name": {
                    "ignore_above": 1024,
                    "type": "keyword"
                  },
                  "id": {
                    "ignore_above": 1024,
                    "type": "keyword"
                  },
                  "type": {
                    "ignore_above": 1024,
                    "type": "keyword"
                  },
                  "mac": {
                    "ignore_above": 1024,
                    "type": "keyword"
                  },
                  "architecture": {
                    "ignore_above": 1024,
                    "type": "keyword"
                  }
                }
              }
```
and 
```
"message": {
                "type": "match_only_text"
              },
```

### PR DESCRIPTION
**Pull request by chemamartinez**
## What does this PR do?

It adds the following changes:

**Audit data stream**
- Add the requested field definitions. The ones that match ECS are included in `ecs.yml`. Otherwise, they have been added at `agent.yml` along with missing fields for `cloud` and `container`.
- Although `host.os.name` is defined in ECS, it has been included in `agent.yml` to avoid a conflict in the type of the `text` multi_field (`text` vs `match_only_text`) with the Log data stream.

**Log data stream**
- `host` ECS fields defined at `agent.yml` have been moved to `ecs.yml` for consistency.

**Performance data stream**
- Added missing `cloud` and `container` fields in agent.yml.
- Added `host` fields in ecs.yml for consistency.

**Transaction logs data stream**
- Added missing `cloud` and `container` fields in agent.yml.
- Added `host` fields in ecs.yml for consistency.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #6070 

## Screenshots

image
image

### CODE REVIEW

**Comment by P1llus** [comment]
Lets add in some other common agent.yml fields as well, we have some covering add_*_metadata like container and cloud in most of our integrations, compare this with for example checkpoint.

Rest LGTM!

**Comment by chemamartinez** [comment]
> Lets add in some other common agent.yml fields as well, we have some covering add_*_metadata like container and cloud in most of our integrations, compare this with for example checkpoint.
> 
> Rest LGTM!

Thanks for the review. I also realized that the host and message fields were missing in the remaining data streams and the events could contain those fields so I added them as well.

**Comment by chemamartinez** [comment]
Found a bug when processing the `host.mac` field in the log, performance, and transaction_log data streams:

image

so I have added the necessary processors in the ingest pipeline to meet the ECS format in case the field appears: https://github.com/elastic/integrations/pull/6264/commits/601683c84cdc0e7920b7b1515f0a09ffb25bf5c8

**Review by P1llus — APPROVED** [review]

**Review by ritalwar — APPROVED** [review]

**Pull request merged**
