### PR TITLE
[system][process] Add missing num_threads field

### PR DESCRIPTION
**Pull request by tetianakravchenko**
## Proposed commit message
Please explain:

- WHAT: Add missing `num_threads` field in process datastream, that was introduced recently in beats - https://github.com/elastic/beats/pull/36578
- WHY: to fix failing ci

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## Related issues

-

### CODE REVIEW

**Comment by lalit-satapathy** [comment]
Assuming the es stack version of the fix https://github.com/elastic/beats/pull/36578 is aligned. Otherwise LGTM.

**Comment by tetianakravchenko** [comment]
@ishleenk17 @elastic/security-external-integrations could you please have a look to this PR?

**Comment by tetianakravchenko** [comment]
@ishleenk17 I've sety stack restriction to 8.11.0 - https://github.com/elastic/integrations/pull/8783/commits/0450f23dc380726e779405abbf2779f432f05370 (checked that this field is available in v8.11.0 tag - https://github.com/elastic/beats/blob/v8.11.0/metricbeat/module/system/process/_meta/fields.yml )

**Comment by tetianakravchenko** [comment]
@ishleenk17 can you please review it?

@elastic/security-external-integrations tests are failing because of the sytem.auth datastream due to the timestamp change:
```
-            "@timestamp": "2023-10-11T09:10:48.000Z",
+            "@timestamp": "2024-10-11T09:10:48.000Z",
```
could you please have a look to it?

**Comment by ishleenk17** [comment]
The changes look good. Please resolve the build issue. Then we should be GTG

**Review by ishleenk17 — APPROVED** [review]
Looks good!

**Review by bhapas — APPROVED** [review]

**Pull request merged**
