### PR TITLE
Allow system package to be installed on 9.0.0+ as well

### PR DESCRIPTION
**Pull request by ycombinator**
## Proposed commit message

This change allows the `system` package to be installed on 9.0.0+ as well.

See also https://github.com/elastic/elastic-package/blob/main/docs/howto/stack_version_support.md#support-for-multiple-majors.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Review by jlind23 — APPROVED** [review]

**Comment by jlind23** [comment]
@lalit-satapathy @andrewkroh can we please get your eyes on this as codeowners?

**Comment by muthu-mps** [comment]
Can you help understand why we do the change for the system package and not for the other packages?

**Comment by jlind23** [comment]
@muthu-mps because we (ingest) own the system package and need it for our automated tests on 9.0. 
@jsoriano are we soon going to remove the kibana.version constraint in Kibana api calls to unblock other integrations?

**Review by muthu-mps — APPROVED** [review]
Code owner approval.

**Comment by jsoriano** [comment]
During 9.x development we have removed the kibana version constraint from most deployments, so it should be possible to install any package in 9.x. Is there any place where you are having problems to install this package in 9.x?

There are some issues with packages in 9.x in scenarios managed by `elastic-package`. We are fixing this in 0.105.0, that we are releasing today.

We will be more specific about the plans for 9.0 in the following weeks, but by now package developers should not need to do anything.

**Comment by ycombinator** [comment]
Thanks @jsoriano.  Closing this PR as unmerged.

**Pull request closed without merging**
