### PR TITLE
[Kibana] Set dimension fields for TSDB migration

### PR DESCRIPTION
**Pull request by constanca-m**
## What does this PR do?

Set dimension fields for all metrics data streams.

All of them only have 2 dimensions set:
1. `agent.id`
2. `service.address`, since the same agent can report metrics for two different addresses at the same time.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

Relates to https://github.com/elastic/integrations/issues/7024.

### CODE REVIEW

**Comment by klacabane** [comment]
Tests break because dimension fields should hold single value but some metricsets (cluster_actions, cluster_rules, node_actions, node_rules) report multiple values[1] for `service.address`. This is because both the [metricset](https://github.com/elastic/beats/blob/main/metricbeat/module/kibana/cluster_actions/data.go#L93) and the [metricbeat](https://github.com/elastic/beats/blob/main/metricbeat/mb/event.go#L148-L150) layer add a value there. Notice that one of these value is wrong and is reporting the api endpoint not the host, and that erroneous value is set on `event.Host`. I think we should remove the metricset `service.address` assignment and fix the `event.Host` value, either by assigning the address we get from the API response or extracting the host from the current Host value.

This fix will only be available in a future release since it's tied to metricbeat, if we want to ship the integrations before that we could use another field - @constanca-m is there another field you would recommend ? We could also fix the `service.address` with a pipeline processor

[1] `service.address | [https://localhost:5601/api/monitoring_collection/cluster_rules, 0.0.0.0:5601]`

**Comment by constanca-m** [comment]
Thanks @klacabane for such a detailed answer.

>  @constanca-m is there another field you would recommend ?

I had a look at the fields again and tested it locally (used the code from [this repository](https://github.com/elastic/TSDB-migration-test-kit)). I only had one instance where files got overwritten if `service.address` is deleted as dimension. Unfortunately, the only `keyword` field that differentiated the two documents was the `service.address`, so I don't think there is a work around for it.

**Comment by klacabane** [comment]
So we could add an ingest pipeline for the impacted data streams. The following should ensure a unique value is stored in `service.address`:

```
processors:
  - dot_expander:
      field: service.address
  - set:
      if: ctx.service.address != null && ctx.service.address instanceof List
      field: service.address
      value: "{{service.address.0}}"
```

**Pull request closed without merging**
