### PR TITLE
[etcd] Enable TSDB for metrics datastream

### PR DESCRIPTION
**Pull request by agithomas**
- Enhancement

## Proposed commit message

- Enable time series data streams for the metrics datasets.
- This improves storage usage and query performance.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist
- [x] Package testing
- [x] Disablement & Rollover testing

## How to test this PR locally

- elastic-package build
- elastic-package stack up -v -d --services package-registry

## Related issues

- Relates https://github.com/elastic/integrations/issues/8327

## Screenshots

https://github.com/elastic/integrations/pull/8438#issue-1984441530

## TSDB Testkit output

https://github.com/elastic/integrations/pull/8438#issue-1984441530

### CODE REVIEW

**Comment by gpop63** [comment]
@agithomas I created a PR (#8663) to test if CI passes with a single variant, and it does after I removed these 2 variants.

```diff
diff --git a/packages/etcd/_dev/deploy/variants.yml b/packages/etcd/_dev/deploy/variants.yml
index d4bb730c31..f9af2ac973 100644
--- a/packages/etcd/_dev/deploy/variants.yml
+++ b/packages/etcd/_dev/deploy/variants.yml
@@ -1,8 +1,4 @@
 variants:
   etcd_3_5_1:
     SERVICE_VERSION: 3.5.1
-  etcd_3_3_8:
-    SERVICE_VERSION: 3.3.8
-  etcd_3:
-    SERVICE_VERSION: 3
 default: etcd_3_5_1
```

**Comment by agithomas** [comment]
Yes, thanks for testing it. 

While this is an issue which must be reported to the `elastic-package` team, I do not think, there exists a merit in testing variants having minor number differences (all versions are 3.x.y) . Please correct me if I am wrong.

**Review by gpop63 — APPROVED** [review]

**Comment by agithomas** [comment]
@ritalwar , can you please review the PR?

**Comment by agithomas** [comment]
I have created an [issue](https://github.com/elastic/integrations/issues/8741)  to assess the impact of multiple variants in system testing with TSDB enablement. 

Note: MySQL integration, having multiple variants did not have similar issues.

**Review by ritalwar — APPROVED** [review]
LGTM!

**Pull request merged**
