### PR TITLE
[Beats] Remove datastreams and add monitoring dashboards

### LINKED ISSUE #6944: [Beats] Create integration dashboards similar to Stack Monitoring UI
To accomplish this we will build new Kibana dashboards and ship them in integration packages so that users have an option to visualize monitoring data out of the box.

Later, these dashboards will be linked to or embedded into a new Ingest UI to give users a global overview of data ingestion metrics and management.

These new dashboards should strive to follow the [best practices](https://github.com/elastic/integrations/blob/main/docs/dashboard_guidelines.md) for integration dashboards. In the first iteration, we're aiming to simply replace the clone Stack Monitoring UI as much as we can 1-1.

## Testing instructions

First deploy a local stack on your machine using elastic-package:
`elastic-package stack up -v -d --version 8.9.0`

As soon as the stack is up you should see the following console output:
```
/Users/julienlind/Downloads/elastic-package_0.84.0_darwin_amd64/elastic-package stack status
Status of Elastic stack services:
╭──────────────────┬────────────────┬───────────────────╮
│ SERVICE          │ VERSION        │ STATUS            │
├──────────────────┼────────────────┼───────────────────┤
│ elastic-agent    │ 8.9.0-SNAPSHOT │ running (healthy) │
│ elasticsearch    │ 8.9.0-SNAPSHOT │ running (healthy) │
│ fleet-server     │ 8.9.0-SNAPSHOT │ running (healthy) │
│ kibana           │ 8.9.0-SNAPSHOT │ running (healthy) │
│ package-registry │ latest         │ running (healthy) │
╰──────────────────┴────────────────┴───────────────────╯
```

Then you need to generate some monitoring metrics, so you can start by installing metricbeat and enabling the system metric:
```
> curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.8.2-darwin-x86_64.tar.gz
> tar xzvf metricbeat-8.8.2-darwin-x86_64.tar.gz
> cd metricbeat-8.8.2-darwin-x86_64
> sudo chown root metricbeat.yml
> sudo chown root modules.d/system.yml
> sudo ./metricbeat -e
```

In the `metricbeat.yml` config file you should set up your ES output and turn on monitoring.

You should now see data flowing in your Stack monitoring menu under the Beats section:
Screenshot 2023-07-13 at 14 34 04

Here is a screenshot that contains both new dashboard (on the left) and Stack Monitoring UI (on the right).
Screenshot 2023-07-19 at 19 03 28

The main differences here is on the CPU Utilization viz as the Stack Monitoring UI has a data point every 10 seconds whereas in dashboard there is one every 30 seconds.

The screenshot below represents the overview dashboard.
Screenshot 2023-07-19 at 19 10 55

### PR DESCRIPTION
**Pull request by jlind23**
Clean up Beat package and make it an asset only package.
It will contains only Beats monitoring dashboards

Closes #6944

### CODE REVIEW

**Comment by jlind23** [comment]
@joshdover I moved this PR to ready for review. Happy to pull in anyone you think will be helpful here. I also updated the [issue description](https://github.com/elastic/integrations/issues/6944) with snapshots and testing instructions.

**Comment by klacabane** [comment]
Getting this error when trying to install the beat package on both 8.9.0 and 8.10.0. What version was used to extract the dashboards ?

```
[plugins.fleet] Failure to install package [beat]: [Error: Migration function for version 7.13.1 threw an error]
[2023-07-24T16:10:54.101+00:00][ERROR][plugins.fleet] uninstalling beat-1.0.0-beta after error installing: [Error: Migration function for version 7.13.1 threw an error]
[2023-07-24T16:10:54.916+00:00][ERROR][plugins.fleet] Error: Migration function for version 7.13.1 threw an error
    at Object.tryTransformDoc [as transform] (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/document_migrator/utils.js:53:13)

...

Caused by:
TypeError: Cannot read properties of undefined (reading 'layers')
```

**Comment by jlind23** [comment]
@klacabane are you using elastic-package to install these? I used the latest 8.10.0-SNAPSHOT.

**Comment by klacabane** [comment]
Happens both with `elastic-package install` and kibana UI (on `8.10.0-f963b2d8-SNAPSHOT`), it also appear in the CI failure. Can we try to re extract the dashboard ?

```
elastic-package-stack-kibana-1  | [2023-07-24T07:57:10.311+00:00][WARN ][plugins.fleet] Failure to install package [beat]: [Error: Migration function for version 7.13.1 threw an error]
elastic-package-stack-kibana-1  | [2023-07-24T07:57:10.312+00:00][ERROR][plugins.fleet] uninstalling beat-1.0.0-beta after error installing: [Error: Migration function for version 7.13.1 threw an error]
elastic-package-stack-kibana-1  | [2023-07-24T07:57:11.193+00:00][ERROR][plugins.fleet] Error: Migration function for version 7.13.1 threw an error
```

**Comment by jlind23** [comment]
@klacabane just pushed the dashboards one more time on this branch.

**Comment by jlind23** [comment]
@jsoriano @mrodm do you know how I can fix this problem: https://github.com/elastic/integrations/pull/6945#issuecomment-1649549212 ?

**Comment by jsoriano** [comment]
> @jsoriano @mrodm do you know how I can fix this problem: [#6945 (comment)](https://github.com/elastic/integrations/pull/6945#issuecomment-1649549212) ?

This seems to be the issue with dashboards created in 8.8/8.9. Were these dashboards exported using a 8.10 that includes the fix? https://github.com/elastic/elastic-package/issues/1354

**Comment by jsoriano** [comment]
> > @jsoriano @mrodm do you know how I can fix this problem: [#6945 (comment)](https://github.com/elastic/integrations/pull/6945#issuecomment-1649549212) ?
> 
> This seems to be the issue with dashboards created in 8.8/8.9. Were these dashboards exported using a 8.10 that includes the fix? [elastic/elastic-package#1354](https://github.com/elastic/elastic-package/issues/1354)

Well, to be more precise, if these dashboards are intended to be used on versions before 8.10, it should be exported from 8.7.
If it is intended to be used in 8.10, it should work there on latest builds including the fix.

**Comment by jlind23** [comment]
These dashboards will be used from 8.10 onwards. I'll update my elastic-package instance and re-export them then.

**Comment by jlind23** [comment]
@klacabane you should be good to test by now :)

**Comment by klacabane** [comment]
@jlind23 I updated graphed properties to align with what Stack Monitoring currently uses in https://github.com/elastic/integrations/pull/6945/commits/1e58b46fbc82233625967df10ec8d769087dcc57

When testing I started two local metricbeat processes and they had the same name which ended up being aggregated[1] in a single row in the dashboard because we collapse on `beat.name`. We should collapse on `beat.uuid` to surface individual process

Screenshot 2023-07-26 at 16 04 31

**Comment by jlind23** [comment]
@klacabane did you change the collapse property too or shall I do it?

**Comment by klacabane** [comment]
Fixed the collapse and added a control to filter on `cluster_uuid` on the overview dashboard to replicate stack monitoring behavior. The control requires a dedicated index pattern to be imported in the package next to the dashboards. Also updated all the lenses to query from this pattern

Screenshot 2023-07-26 at 18 52 06

**Comment by jlind23** [comment]
Up @joshdover

**Comment by joshdover** [comment]
On my list for this week, promise 👍

**Review by joshdover — APPROVED** [review]
LGTM.

I pushed some fixes to the overview dashboard to show metrics for multiple beats:

image

**Pull request merged**
