### PR TITLE
[Fleet] Add Elastic agent integration

### PR DESCRIPTION
**Pull request by nchaulet**
Add a new integration for Elastic Agent

Still in progress

## What does this PR do?

Create a new Elastic Agent integration that add a dashboard for agent metrics

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [x] I have verified that all datasets collect metrics or logs.

## How to test this PR locally

This PR depends on this PR of the elastic Agent https://github.com/elastic/beats/pull/22793

## Screenshots

Screen Shot 2020-12-14 at 9 22 47 PM

Screen Shot 2020-12-14 at 9 09 37 AM

### CODE REVIEW

**Comment by ph** [comment]
@ravikesarwani Can you take a look?

@nchaulet I am curious, the values looks weirds to me, the graph looks too perfect for me?  Are the values aggregated?

**Comment by nchaulet** [comment]
@ph The graph are stacked per process, what does seems weird to you in the graph?

**Comment by ph** [comment]
what is the left axis for the graph?

**Comment by nchaulet** [comment]
The left axis is a percentage for CPU, memory size for Memory and the number of open handle 

Maybe this screenshot makes more sense

Screen Shot 2020-12-15 at 9 45 34 AM

**Review by ruflin — APPROVED** [review]
@nchaulet The part that makes me suspicious is that memory usage of all process is identical. My guess is, that it takes memory usage from the parent process, so maybe the reporting is off not the graph. @blakerouse might know more.

I did run and install the package on my end and it works. I suggest we get it in an then iterate on it.

**Comment by ravikesarwani** [comment]
**Some initial comments from my side:**
- I found this issue that Dimitri created and may help here https://github.com/elastic/integrations/issues/269
- Can we label the Y axis?
- Can we add a filter for easy selection by user to select one or more Agent sub processes. 
- For CPU usage and open handles I was thinking if the stacked graph is the best default representation. Line chart maybe more appropriate here. Thoughts?
- For memory usage stacked maybe good if we can show whole part relationship. Total available memory (8 GB) and Agent, filebeat & metricbeat is taking x, y and z from the total and F is free.
- We can change the CPU Usage to CPU Usage %
@nchaulet Feel free to ping me any time for us to chat on Zoom and brainstorm any of the above points.
Is there some place I can play with this?

**Comment by nchaulet** [comment]
@ravi-elastic  the dashboard as updated in our Zoom conversation

Screen Shot 2020-12-15 at 4 34 53 PM

**Comment by nchaulet** [comment]
I will merge it as it is and will update in new PRs if we have things to change.

**Comment by ph** [comment]
@nchaulet I've been trying to find a followup issue, did you create one to install this package by default?

**Comment by nchaulet** [comment]
I just created the follow up issue to install the package by default https://github.com/elastic/kibana/issues/86112

**Pull request merged**
