### PR TITLE
[System] Adding condition to 0.9.2 package => 0.9.3

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

This PR effectively performs two steps:
1. Reverts all changes in the `system` package back to the `0.9.2` version of the package (commit SHA: 1f5013cef1a441e3d76adcfe687b035c1390617c
2. Then adds a `condition` to the `load` data stream and bumps up the package version to `0.9.3`

However, due to step 1, the diff in this PR is very large. To get a true-r sense of the changes (i.e. just step 2), check out this PR and run `git diff 1f5013cef1a441e3d76adcfe687b035c1390617c -- packages/system/`.

Immediately following up this PR will be a PR that undoes step 1, therefore bringing the `system` package back to it's current state in this repo, i.e. as of commit SHA 293d243f6e00ebc772ee39b65c14d58a24a4bcbb.

## Why is this change important?

The latest released `0.9.x` version of the `system` package is `0.9.2`. We need to fix an issue in this series (by adding the `condition` field). For this, we need to release `0.9.3` of the package with this change.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
@ycombinator so is the plan to let the automation put in the `SNAPSHOT` PR for this change, _then_ revert?

**Comment by ycombinator** [comment]
> @ycombinator so is the plan to let the automation put in the `SNAPSHOT` PR for this change, _then_ revert?

@fearful-symmetry yep, exactly!

**Review by fearful-symmetry — APPROVED** [review]
Assuming this is good. In the future we might want to find a less multi-step way to do this, since we're definitely going to see more cases where a stack release is constrained to certain integration releases.

**Comment by ycombinator** [comment]
Welp, we have a problem! CI is failing with this error:

```
[2021-02-08T19:30:32.915Z] Error: error running package asset tests: could not complete test run: could not install package: could not install package; API status code = 400; response body = {"statusCode":400,"error":"Bad Request","message":"system-0.9.3 is out-of-date and cannot be installed or updated"}
```

This is because the package registry distribution used for tests by CI contains a newer version of the `system` package. 

Even if we merged this PR with the failing CI, I don't think that's going to help us because I suspect we'll see the same error on the `master` build that follows. And once it errors out, the `master` build won't automatically publish the `0.9.3` version of the `system` package to https://github.com/elastic/package-storage/tree/snapshot. 😞 

I'm wondering now if we should instead make a PR directly to https://github.com/elastic/package-storage/tree/snapshot with a new folder for `0.9.3` (copied from `0.9.2`) with the necessary `condition` change. The down side of this approach is that we won't have a copy of the `0.9.3` `system` package in the `integrations` repo. 🤔 

@mtojek do you have any opinions or other ideas? Please see the PR description to understand what we are trying to accomplish with this PR.

**Comment by ycombinator** [comment]
I chatted with @jen-huang off-PR about the error we're seeing in CI:

```
[2021-02-08T19:30:32.915Z] Error: error running package asset tests: could not complete test run: could not install package: could not install package; API status code = 400; response body = {"statusCode":400,"error":"Bad Request","message":"system-0.9.3 is out-of-date and cannot be installed or updated"}
```

Since we are trying to install the package for system testing purposes, I think it's okay to ignore the package version check. IOW, the system test runner  _needs_ to be able to install the package version being tested so it can run the test, regardless of what other versions of the package are present in the registry.

@jen-huang informed me that this is, in fact, possible with the Fleet API by passing `{force: true}` in the API's request payload. I'm going to implement this change in `elastic-package` now.

**Review by mtojek — APPROVED** [review]
> I'm wondering now if we should instead make a PR directly to https://github.com/elastic/package-storage/tree/snapshot with a new folder for 0.9.3 (copied from 0.9.2) with the necessary condition change. The down side of this approach is that we won't have a copy of the 0.9.3 system package in the integrations repo and we'd bypass any checks that normally happen on integrations repo PRs. 🤔

I met a case in the past where there was condition on Kibana version in the package. As no user could install that package I simply modified the broken source in the package-storage. I understand that in this case it's possible to install the package, so your idea is correct, hence LGTM for this PR and the fix in the elastic-package.

I would also re-consider fixing broken packages directly in the package-storage in such emergency cases. It's much easier to handle it operationally.

**Comment by ycombinator** [comment]
Thanks for weighing in, @mtojek .

I understand your point about broken package versions: because such versions cannot be installed anyway by the user, we can assume no one has installed them and, therefore, a fix to them will not require a re-install. So we can safely fix them directly in `package-storage`. 

When you did this in the past, did you also fix the source package version in the `integrations` repo afterwards? Otherwise there is no record of that fix for that version in the `integrations` repo, right? If you did fix it in the `integrations` repo afterwards, how did you do it, considering that the package in the repo @ `master` would've probably been far ahead in terms of it's changes from the broken version — did you end up with a "messy" PR like the one here?

**Comment by ycombinator** [comment]
Just to be clear, the above discussion with @mtojek is not blocking this PR. I'm waiting to rebase this PR on `master` once https://github.com/elastic/integrations/pull/679 is merged.

**Comment by mtojek** [comment]
> When you did this in the past, did you also fix the source package version in the integrations repo afterwards? Otherwise there is no record of that fix for that version in the integrations repo, right? If you did fix it in the integrations repo afterwards, how did you do it, considering that the package in the repo @ master could've probably been far ahead in terms of it's changes from the broken version 

In my case it was an issue with incompatible import of Kibana dashboards: https://github.com/elastic/package-storage/commit/0767f7a0db327acdb578f50d61807731c944457d . I fixed it only in the package-storage (must be compatible with Kibana 7.10), because the Apache package's version has been bumped up in Integrations together with bumped up Kibana's constraint (7.11.0 - https://github.com/elastic/integrations/blob/master/packages/apache/manifest.yml#L12). As we're working with latest master in Integrations, I couldn't alter the Git history there.

**Comment by ycombinator** [comment]
> As we're working with latest master in Integrations, I couldn't alter the Git history there.

Right, this is what I'm facing with this PR here as well. It's why this PR is so messy (so many changes!) and why we will need a follow up PR to restore the `system` package as it stands prior to this PR back in `master`.

I think, in general, we need to have a policy that covers how to fix older versions of packages so we are fixing them consistently and all package authors are aware of it.  I'll file a separate issue to take this discussion off this PR.

**Comment by ycombinator** [comment]
So just to recap, the next steps with this PR are as follows:

1. Now that the PR is approved and CI is green, merge the PR. This will cause the `master` branch of the `integrations` repo to temporarily contain `0.9.3` of the `system` package. CI will build `master`, which will result in `0.9.3` of the `system` package being released (i.e. CI will make a PR to the `snapshot` branch of `package-storage` with `0.9.3` of the `system` package.

2. Once the PR to `package-storage` resulting from step 1. looks good, I will put up another PR to the `master` branch of the `integrations` repo to restore the `system` package as it stands just prior to this PR here, effectively undoing this PR.

@fearful-symmetry @ChrsMark Please take note of the above, as you two come up as recent editors of the `system` package. You might want to hold off on further PRs for the `system` package to the `integrations` repo until the above two steps are completed. I will post a comment here once both steps are completed and the resulting PRs merged.

**Comment by ycombinator** [comment]
> I think, in general, we need to have a policy that covers how to fix older versions of packages so we are fixing them consistently and all package authors are aware of it. I'll file a separate issue to take this discussion off this PR.

Created issue for discussion: https://github.com/elastic/integrations/issues/682.

**Comment by ycombinator** [comment]
> So just to recap, the next steps with this PR are as follows:

> 1. Now that this PR here is approved and CI is green, I will merge the PR. This will cause the `master` branch of the `integrations` repo to temporarily contain `0.9.3` of the `system` package. CI will build `master`, which will result in `0.9.3` of the `system` package being released (i.e. CI will make a PR to the `snapshot` branch of `package-storage` with `0.9.3` of the `system` package).

This is done now. The PR to `package-storage` is up: https://github.com/elastic/package-storage/pull/869.

> 2. Once the PR to `package-storage` resulting from step 1. looks good, I will put up another PR to the `master` branch of the `integrations` repo to restore the `system` package as it stands just prior to this PR here, effectively undoing this PR.

This is also done now. The PR to revert this PR here is up: https://github.com/elastic/integrations/pull/681.

@mtojek @fearful-symmetry I've requested your reviews on both PRs above.

**Pull request merged**
