### PR TITLE
windows: add file hash fields for the new Sysmon EID 29

### PR DESCRIPTION
**Pull request by fopson**
The current pipeline does not create the "file.hash" field for the new sysmon Event ID 29. As a result, that information is lost and does not end up on the event.

- Enhancement

## What does this PR do?

It makes sure the file hash information from the new sysmon EID 29 is not lost when the "_temp" field is deleted.

## Checklist

- [x ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x ] I have verified that all data streams collect metrics or logs.
- [x ] I have added an entry to my package's `changelog.yml` file.
- [x ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] Update the Sysmon ingest pipeline
- [ ] Generate Sysmon EID 29
- [ ] Verify that the appropriate hashes are being store under file.hash.*

## How to test this PR locally

- Update the Sysmon ingest pipeline, Generate a Sysmon EID 29 and

## Sample Event
```

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Events>
  <Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'>
    <System>
      <Provider Name='Microsoft-Windows-Sysmon' Guid='{5770385f-c22a-43e0-bf4c-06f5698ffbd9}' />
      <EventID>29</EventID>
      <Version>5</Version>
      <Level>4</Level>
      <Task>29</Task>
      <Opcode>0</Opcode>
      <Keywords>0x8000000000000000</Keywords>
      <TimeCreated SystemTime='2023-07-19T17:01:17.8516659Z' />
      <EventRecordID>71035898</EventRecordID>
      <Correlation />
      <Execution ProcessID='6164' ThreadID='6268' />
      <Channel>Microsoft-Windows-Sysmon/Operational</Channel>
      <Computer>REDACTED</Computer>
      <Security UserID='S-1-5-18' />
    </System>
    <EventData>
      <Data Name='RuleName'>-</Data>
      <Data Name='UtcTime'>2023-07-19 17:01:17.843</Data>
      <Data Name='ProcessGuid'>{56a10975-16dd-64b8-0407-000000005d00}</Data>
      <Data Name='ProcessId'>6900</Data>
      <Data Name='User'>NT AUTHORITY\SYSTEM</Data>
      <Data Name='Image'>C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsvw.exe</Data>
      <Data Name='TargetFilename'>
        C:\Windows\assembly\NativeImages_v4.0.30319_32\XsdBuildTask\b25cbabe3057c96a57c7361a596cc89a\XsdBuildTask.ni.dll</Data>
      <Data Name='Hashes'>
        SHA1=2D263CA9EDE0B59CA3105B3261730000441EF4D9,MD5=AC0E7A24551EB981D5DCF6EDAE582A58,SHA256=AD7DD6CD1117A6CD50A8EDC3D4594264D60CD11BAA3747C3CBCCEF17CE706A7C,IMPHASH=00000000000000000000000000000000</Data>
    </EventData>
  </Event>
</Events>


```
## Screenshots

image

### CODE REVIEW

**Comment by efd6** [comment]
@fopson, please sign the CLA so that we can take a look at this. If you believe you have signed it, please check that the email address that you used agrees with the email address in the commits.

**Comment by fopson** [comment]
> 

Hi @efd6, I have signed the agreement twice now but it is still showing up as unsigned. Not sure why.

**Comment by efd6** [comment]
@fopson Looks good now.

**Review by efd6 — COMMENTED** [review]
@fopson Please add an entry to the changelog and update the manifest for the package. I expect that this change will require that the test expectations will need to be updated. Are you able to do this?

**Comment by fopson** [comment]
> @fopson Please add an entry to the changelog and update the manifest for the package. I expect that this change will require that the test expectations will need to be updated. Are you able to do this?

Done.

**Comment by efd6** [comment]
@fopson This also needs a change to the manifest [here](https://github.com/elastic/integrations/blob/67f64f15a8f0bdf487f8170b6ba6fce62c10c56f/packages/windows/manifest.yml#L3).

**Comment by fopson** [comment]
> @fopson This also needs a change to the manifest [here](https://github.com/elastic/integrations/blob/67f64f15a8f0bdf487f8170b6ba6fce62c10c56f/packages/windows/manifest.yml#L3).

Done

**Pull request merged**
