### PR TITLE
[O11y][IBM MQ] Lens migration for visualizations to Kibana version 8.5.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for IBM MQ integration package

- Statistics for IBM MQ Lens migration:

<html>
<body>
<google-sheets-html-origin>

IBM MQ dashboard | Before Migration |   | After Migration |   |  
-- | -- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization | New Control Panel
[Metrics IBM MQ] Subscriptions Overview | 0 | 7 | 7 | 0 | 0
[Logs IBM MQ] Overview of error log | 0 | 7 | 5 | 1 | 1
[Metrics IBM MQ] Calls Overview | 0 | 11 | 11 | 0 | 0
[Metrics IBM MQ] Messages Overview | 0 | 12 | 12 | 0 | 0
  | 0 | 37 | 35 | 1 | 1

</body>
</html>

Note: One visualization is migrated to new input controls.

Below visualization is not migrated to the lens

<html>
<body>

Dashboard  | Visualisation Name | Link to the issue
-- | -- | --
[Logs IBM MQ] Overview of error log | Top 5 Errors [Logs IBM MQ]|  https://github.com/elastic/integrations/issues/5662

</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.5.0 itself.

## Related issues

- Relates #5221 

## Issues Identified
- Gradient and rainbow color palettes are not available in lens and won't be available in the future versions as well. Hence, the closest color palettes (positive and negative) have been used.
https://github.com/elastic/kibana/issues/152699
- The text type field is not supported in table type visualizations of Lens. ~Hence, we have removed Description field from the table.~ Created the [issue](https://github.com/elastic/integrations/issues/5662) to migrate the `Top 5 Errors [Logs IBM MQ]` panel in future.
https://github.com/elastic/kibana/issues/96576
- Added custom label for multilayer visualizations to identify the individual graphs (for eg., Succeeded and Failed in **MQCB calls succeeded/failed [Metrics IBM MQ]** panel)

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Comment by rajvi-elastic** [comment]
> Removing a field may not be the best option. We may then retain the old viz panel that supports text data. Please create a backlog issue to migrate this panel in future.

@agithomas, We have reverted the changes to the old visualization and created the [issue](https://github.com/elastic/integrations/issues/5662) to migrate the `Top 5 Errors [Logs IBM MQ]` panel in future.

**Comment by agithomas** [comment]
> @agithomas, We have reverted the changes to the old visualization and created the [issue](https://github.com/elastic/integrations/issues/5662) to migrate the `Top 5 Errors [Logs IBM MQ]` panel in future.

Please update the summary chart on how many vis are not migrated.

**Comment by agithomas** [comment]
Last bucket empty is a common problem seen across multiple dashboards. @SubhrataK , kindly confirm if this problem is a blocker for vis migration to Lens.  Hope you can clarify this today. This clarification is a blocker for multiple integration tasks.

@rajvi-elastic , if this is a blocker, kindly revert the migration for these panels to Lens and update the summary chart.

**Comment by rajvi-elastic** [comment]
> Please update the summary chart on how many vis are not migrated.

@agithomas, I have updated the summary below migration stat table. Please let me know if anything else needs to be added.

**Comment by agithomas** [comment]
> > Please update the summary chart on how many vis are not migrated.
> 
> @agithomas, I have updated the summary below migration stat table. Please let me know if anything else needs to be added.

Please update in the PR description as well : https://github.com/elastic/integrations/pull/5495#issue-1617377286

**Comment by SubhrataK** [comment]
> Last bucket empty is a common problem seen across multiple dashboards. @SubhrataK , kindly confirm if this problem is a blocker for vis migration to Lens. Hope you can clarify this today. This clarification is a blocker for multiple integration tasks.

@agithomas and @rajvi-elastic IMO, this should not be a blocker. As a user, it shows a legend for me and I can hover and see the values. Also, this is only in the case where the last bucket values are zero in area and line charts (bar charts are fine). 
Infact, the point that it shows the values in the last bucket would have been slightly confusing, as I would have expected it to show an aggregate of the values over the selected time range. There is another discussion thread on what data should be displayed, here: https://github.com/elastic/kibana/pull/101353. 
However, there has to be a consistency in the values displayed in the different charts, and that has been raised as a bug. 

I suggest we go ahead and migrate the visualizations.

**Comment by rajvi-elastic** [comment]
> Please update in the PR description as well : [#5495 (comment)](https://github.com/elastic/integrations/pull/5495#issue-1617377286)

@agithomas I have added the table for panels that are not migrated to the lens. Can you please check? [#5495 (comment)](https://github.com/elastic/integrations/pull/5495#issue-1617377286)

**Comment by agithomas** [comment]
> > Please update in the PR description as well : [#5495 (comment)](https://github.com/elastic/integrations/pull/5495#issue-1617377286)
> 
> @agithomas I have added the table for panels that are not migrated to the lens. Can you please check? [#5495 (comment)](https://github.com/elastic/integrations/pull/5495#issue-1617377286)

@rajvi-elastic , please check below. I was referring to this table. If certain visualisation is not migrated to Lens, i expect certain count under Visualisation not equal to 0, after migration. Or, is my understanding incorrect?

With Subrata's clarification, i believe, the last bucket issue is not longer a concern. So, please unlink to referrences to Lens original issue from all the applicable Lens migration issues

image

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic , please check below. I was referring to this table. If certain visualisation is not migrated to Lens, i expect certain count under Visualisation not equal to 0, after migration. Or, is my understanding incorrect?

My bad! Updated the table and removed the last bucket issue link from the PR and meta issue as well.

**Comment by agithomas** [comment]
@rajvi-elastic ,i see that there is a steep jump in the kibana version from 8.2.0 to 8.5.0. With some of the changes made , does the change to  8.5.0 still needed. If yes, why?

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic ,i see that there is a steep jump in the kibana version from 8.2.0 to 8.5.0. With some of the changes made , does the change to 8.5.0 still needed. If yes, why?

Yes @agithomas. Please find the below analysis for `[Metrics IBM MQ] Calls Overview` dashboard which shows the minimum version and the functionality that has been used for the panels.

<html>
<body>


Visualization Name | Minimum kibana version | Functionality used
-- | -- | --
MQCB calls succeeded/failed [Metrics IBM MQ] | 8.5.0 | Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens
MQCLOSE calls succeeded/failed [Metrics IBM MQ] | 8.5.0 | Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens
MQCONN/MQCONNX calls succeeded/failed [Metrics IBM MQ] | 8.5.0 | Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens
MQDISC calls succeeded [Metrics IBM MQ]MQDISC calls succeeded [Metrics IBM MQ] | 8.2.0 | include empty rows
MQCTL calls succeeded [Metrics IBM MQ] | 8.2.0 | include empty rows
MQSTAT calls succeeded [Metrics IBM MQ] | 8.2.0 | include empty rows
MQCTL calls succeeded [Metrics IBM MQ] | 8.2.0 | include empty rows
MQOPEN calls succeeded/failed [Metrics IBM MQ] | 8.5.0 | Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens
MQINQ calls succeeded/failed [Metrics IBM MQ] | 8.5.0 | Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens
MQSET calls succeeded/failed [Metrics IBM MQ] | 8.5.0 | Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens
MQSUBRQ calls succeeded/failed [Metrics IBM MQ] | 8.5.0 | Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens


</body>
</html>

**Comment by agithomas** [comment]
> > @rajvi-elastic ,i see that there is a steep jump in the kibana version from 8.2.0 to 8.5.0. With some of the changes made , does the change to 8.5.0 still needed. If yes, why?
> 
> Yes @agithomas. Please find the below analysis for `[Metrics IBM MQ] Calls Overview` dashboard which shows the minimum version and the functionality that has been used for the panels.
> 
> Visualization Name	Minimum kibana version	Functionality used
> MQCB calls succeeded/failed [Metrics IBM MQ]	8.5.0	Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens
> MQCLOSE calls succeeded/failed [Metrics IBM MQ]	8.5.0	Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens
> MQCONN/MQCONNX calls succeeded/failed [Metrics IBM MQ]	8.5.0	Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens
> MQDISC calls succeeded [Metrics IBM MQ]MQDISC calls succeeded [Metrics IBM MQ]	8.2.0	include empty rows
> MQCTL calls succeeded [Metrics IBM MQ]	8.2.0	include empty rows
> MQSTAT calls succeeded [Metrics IBM MQ]	8.2.0	include empty rows
> MQCTL calls succeeded [Metrics IBM MQ]	8.2.0	include empty rows
> MQOPEN calls succeeded/failed [Metrics IBM MQ]	8.5.0	Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens
> MQINQ calls succeeded/failed [Metrics IBM MQ]	8.5.0	Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens
> MQSET calls succeeded/failed [Metrics IBM MQ]	8.5.0	Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens
> MQSUBRQ calls succeeded/failed [Metrics IBM MQ]	8.5.0	Adds the ability to show the metric name if there are multiple layers with breakdowns in Lens

@lalit-satapathy / @rameshelastic  please advice  here. Is it Ok to migrate to 8.5.0 .

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
