### PR TITLE
feat: add aws additional auth options

### PR DESCRIPTION
**Pull request by olegsu**
## What does this PR do?

Add additional AWS auth options (https://github.com/elastic/security-team/issues/4495)

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues
Related https://github.com/elastic/security-team/issues/4495

## Screenshots

image

### CODE REVIEW

**Review by ofiriro3 — APPROVED** [review]
LGTM 🚀

**Comment by ofiriro3** [comment]
I am not sure that the integration CI error is related to your work - please double check me

**Comment by orouz** [comment]
LGTM 

just to be sure, can you please verify that after creating an integration, the agent policy still includes our runtime config? 


Screen Shot 2022-09-08 at 17 56 58

**Comment by olegsu** [comment]
> LGTM
> 
> just to be sure, can you please verify that after creating an integration, the agent policy still includes our runtime config?
> 
> Screen Shot 2022-09-08 at 17 56 58

I will verify this case

**Comment by olegsu** [comment]
@orouz 
Seems ok
image

**Pull request merged**
