### PR TITLE
[Fortinet Fortigate] Ensure MAC addresses conform to ECS

### LINKED ISSUE #4386: [fortinet_fortigate] fortinet.firewall.mac does not respect ECS via RFC 7042
Hello Elastics,

it seems that the fortinet_fortigate integration does not respect ECS for fortinet.firewall.mac fields

Can someone please correct this? Thank you

Also an side note:
There is no related.mac in ECS
https://www.elastic.co/guide/en/ecs/current/ecs-related.html

Perhaps there should be one added?

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

- Ensure MAC addresses conform to ECS format
- Update to ECS 8.4.0

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Closes #4386

### CODE REVIEW

**Comment by andrewkroh** [comment]
@legoguy1000 Is there anything else that needs added or can we take this out of "Draft" mode? I think it's going to go green on this CI run 🤞 .

**Comment by legoguy1000** [comment]
> @legoguy1000 Is there anything else that needs added or can we take this out of "Draft" mode? I think it's going to go green on this CI run 🤞 .

I think the only thing was that none of the sample data has any Mac addresses verify. But besides that, should be all good.

**Comment by andrewkroh** [comment]
We have a sample for this now in https://github.com/elastic/integrations/issues/4386#issuecomment-1361057289 so this could be revived.

**Pull request closed without merging**
