### PR TITLE
Add global level data_stream.dataset dashboard filter

### PR DESCRIPTION
**Pull request by milan-elastic**
## Proposed commit message
Add a global filter to the dashboard and remove the subfilters on the dataset and a global filter on the dataset is introduced. Filters on data_stream.dataset are applied with a phrase type filter on the dataset that is being used in that particular dashboard.

Expect the above mentioned changes done in following selected packages to ease the review

- prometheus
- oracle_weblogic
- containerd
- azure_application_insights
- mysql
- springboot
- nginx ingress controller
- nginx
- istio
- traefik

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates https://github.com/elastic/integrations/issues/9323

## Screenshot

<details>
  <summary>Prometheus</summary>

| Before| After|
|:-:|:-:|
|prometheus  server overview - before |prometheus  server overview - after|

</details>

<details>
  <summary>Oracle Weblogic</summary>

|Deployed application Before|Deployed application After|
|:-:|:-:|
|oracle weblogic  deployed application - before|oracle weblogic  deployed application - after|

| log overview Before| log overview After|
|:-:|:-:|
|oracle weblogic  logs overview - before|oracle weblogic  logs overview - after|

|Threadpool Before|Threadpool After|
|:-:|:-:|
|oracle weblogic  threadpool - before|oracle weblogic  threadpool - after|

</details>

<details>
  <summary> Containerd</summary>

|Server Before|Server  After|
|:-:|:-:|
| Before| After|
|containerd  overview - before|containerd  overview - after|
</details>

<details>
<summary>Azure Application insights</summary>

| Before|  After|
|:-:|:-:|
|App state overview Before|App state overview After|
|Azure Application Insights -  Azure Metrics  App State Overview - Before|Azure Application Insights -  Azure Metrics  App State Overview - After|
</details>

<details>
<summary>Mysql</summary>

|Logs overview Before|Logs overview After|
|:-:|:-:|
|mysql  logs overview - before|mysql  Logs overview - after|

|Database Before|Database  After|
|:-:|:-:|
|mysql  database overview - before|mysql  database overview - after|
</details>

<details>
<summary>SpringBoot</summary>

|Access  Before|Access After|
|:-:|:-:|
|spring boot  access logs - before|spring boot  access logs - after|

|Audit events Before|Audit events After|
|:-:|:-:|
|spring boot  audit events - before|spring boot  audit events - after|

|Memory and Threads Before|Memory and Threads  After|
|:-:|:-:|
|spring boot  memory and threads - before|spring boot  memory and threads - after|

|Overview Before|Overview  After|
|:-:|:-:|
|spring boot  overview - before|spring boot  overview - after|

</details>

<details>
<summary>Nginx ingress controller</summary>

|Access  Before|Access After|
|:-:|:-:|
|nginx ingress controller  access and error logs - before|nginx ingress controller  access and error logs - after|

|Access  Before|Access After|
|:-:|:-:|
|nginx ingress controller  overview - before|nginx ingress controller  overview - after|

</details>

<details>
<summary>Nginx </summary>

|Log Overview  Before|Log Overview After|
|:-:|:-:|
|nginx  logs overview - before|nginx  logs overview - after|

|Access and Error  Before|Access and Error After|
|:-:|:-:|
|nginx  access and error logs - before|nginx  access and error logs - after|

|Metrics Overview  Before|Metrics Overview After|
|:-:|:-:|
|nginx  metrics overview - before|nginx  metrics overview - after|

</details>

<details>
<summary>Istio </summary>

|Overview  Before|Overview After|
|:-:|:-:|
|metrics istio  overview -before|metrics istio  overview -after|

|Traffic  Before|Traffic After|
|:-:|:-:|
|metrics istio  traffic -before|metrics istio  traffic -after|

</details>

<details>
<summary>Traefik </summary>

|Access Overview  Before|Access After|
|:-:|:-:|
|traefik  access - before|traefik  access - after|

</details>

### CODE REVIEW

**Review by harnish-elastic — APPROVED** [review]
LGTM! 🚀

**Comment by agithomas** [comment]
@milan-elastic ,there are a few panels under istio without data. Can this be verified  - if there are no datasets missing? I understand that the data is not present in the "before" scenario. However, in such cases, it is best to double-check. Please confirm

**Comment by agithomas** [comment]
Kindly check if `validations.yml` entry needs to be removed for some of the datastreams / packages?

**Comment by milan-elastic** [comment]
> @milan-elastic ,there are a few panels under istio without data. Can this be verified - if there are no datasets missing? I understand that the data is not present in the "before" scenario. However, in such cases, it is best to double-check. Please confirm

Updated the screenshot and verified the dashboard for istio is working as expected.

**Comment by milan-elastic** [comment]
> Kindly check if `validations.yml` entry needs to be removed for some of the datastreams / packages? Example : nginx_ingresscontroller

I have re-checked all the validations.yml in the packages of this PR and found that azure_application_insights needs to remove the validations.yml file. So I have removed it. Thanks!

**Review by agithomas — APPROVED** [review]
LGTM!

**Comment by milan-elastic** [comment]
@gizas @constanca-m Can you please review and provide code owner approval for istio, containerd and nginx ingress controller packages?

**Review by constanca-m — APPROVED** [review]

**Review by gizas — APPROVED** [review]

**Pull request merged**
