### PR TITLE
[AlienVault OTC] Populate Related IP and Related Hash Fields

### LINKED ISSUE #8321: [AlienVault OTX] Related Fields Not Populated
I just noticed none of the `related.*` fields are being populated for the AlienVault OTX integration. This is affecting global, aggregated  searches for documents with `related.ip` and `related.hash` values.

### PR DESCRIPTION
**Pull request by MakoWish**
Please label this PR with one of the following labels, depending on the scope of your change:
- Enhancement

## Proposed commit message

The AlienVault OTX integration does not currently populate hash or IP values to `related.hash` and `related.ip`, respectively. This PR adds those values. 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have incremented the version in my package's `manifest.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #8321

### CODE REVIEW

**Review by bhapas — APPROVED** [review]
LGTM

**Comment by MakoWish** [comment]
I don't have permissions to merge, so if someone would be so kind. :-)

**Comment by MakoWish** [comment]
Would somebody please retest and merge this?

**Pull request merged**
