### PR TITLE
ti_crowdstrike: prevent eval failure when pagination is absent

### LINKED ISSUE #8916: [CrowdStrike Threat Intel] Technical Preview Error Messages
Our recently release CrowdStrike TI integration has been tested by some early adopters and some error messages are being reported.

Following message has been observed by two users, one with the data flowing through Logstash and the other with no Logstash instance in place. Doesn't make a different if `Preserve original event` is enabled or not. The same error is appearing for both intel and IoC datastreams. 

```
event.dataset:ti_crowdstrike.intel [failed eval: no such key: pagination, Processor json with tag json_event_original in pipeline logs-ti_crowdstrike.intel-0.1.0 failed with message: field [original] not present as part of path [event.original]]
```

### PR DESCRIPTION
**Pull request by efd6**
## Proposed commit message

The pagination logic currently accesses the meta.pagination field, which
apparently may not exist. So protect against access in that case.

Also clean up CEL code and make test input data clearer.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] Best reviewed commit-wise.
- [ ] Hide whitespace diffs on the first commit.
- [ ] JSON prettification was done by editor plugin.

## Related issues

- Fixes #8916

### CODE REVIEW

**Review by andrewkroh — APPROVED** [review]

**Comment by mbudge** [comment]
I updated to ti_crowdstrike - 0.1.1 yesterday which didn't fix it.

Still get these errors.

**ti_crowdstrike.intel** 
[failed eval: no such overload, Processor json with tag json_event_original in pipeline logs-ti_crowdstrike.intel-0.1.1 failed with message: field [original] not present as part of path [event.original]]

**ti_crowdstrike.ioc**
[failed eval: no such key: resources, Processor json with tag json_event_original in pipeline logs-ti_crowdstrike.ioc-0.1.1 failed with message: field [original] not present as part of path [event.original]]

ti_crowdstrike.intel only works when using the Elasticsearch output. We get an eval: no such overload error when using the Logstash output.

ti_crowdstrike.ioc doesn't work with Elasticsearch or Logstash output. We get the no such key: resources error with both.

Logstash plugins don't support meta fields yet.

Thanks

**Comment by kcreddy** [comment]
In the case of `ioc` issue, the error `no such key: resources` could be probably happening when the API doesn't respond with 200 status. We don't seem to check if the `body.resources` exist. Maybe we can even catch errors and propagate into the `error.message` with appropriate status code. 

https://github.com/elastic/integrations/blob/b4c28956a9ceee5cf463946ff7e685d6350e3453/packages/ti_crowdstrike/data_stream/ioc/agent/stream/cel.yml.hbs#L50-L51

I am not sure about the `intel` issue, and I am not convinced it could be output related.

We also need to document required API scopes/permissions that users must add.

**Comment by mbudge** [comment]
Here's the scopes for the CrowdStrike API Client 

Indicators (Falcon Intelligence)
Reports (Falcon Intelligence)

For IOCs I did this

```
if "body" in response and "resources" in response["body"]:
        indicators = response["body"]["resources"]
```

Attached my script to support ticket #01543410 which uses https://github.com/CrowdStrike/falconpy/blob/main/src/falconpy/intel.py

**Comment by mbudge** [comment]
Is this still been worked on?

Still not working for us.

**Pull request merged**
