### PR TITLE
[AWS] Change default value for dataset name on cloudwatch logs

### PR DESCRIPTION
**Pull request by P1llus**
## What does this PR do?

This PR is a reaction to https://github.com/elastic/integrations/issues/5467#issuecomment-1461798560.

When the default name of dataset is wrong, the related ingest pipelines and other assets are not working out of the box.

While we wait to convert to "input type" packages, the best course of action is to ensure the default name is correct.

This might be seen as a breaking change, and I will let it be up to the owner of the package to decide on this, any users with using the default value (since the option was hidden at the bottom of the page under advanced options, that is likely), will suddenly send data to a new datastream.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates #5467

### CODE REVIEW

**Comment by dmathieu** [comment]
This does indeed seems like a breaking change.

**Comment by aspacca** [comment]
@P1llus I'd take the occasion to remove the deprecate s3 input since we are introducing a breaking change. the major version should be bumped.

do we have any migration path?
is it possible to show some kind of changelog/breaking change notice to the users before they install the package, when notified about the new major version?

if so I'd add there the fact that if they are upgrading from a previous minor and they didn't customised already the dataset they must do that setting it to `generic` as it was before the new major

**Comment by P1llus** [comment]
> @P1llus I'd take the occasion to remove the deprecate s3 input since we are introducing a breaking change. the major version should be bumped.
> 
> do we have any migration path? is it possible to show some kind of changelog/breaking change notice to the users before they install the package, when notified about the new major version?
> 
> if so I'd add there the fact that if they are upgrading from a previous minor and they didn't customised already the dataset they must do that setting it to `generic` as it was before the new major

Yeah that is the biggest hurdle right now, since we can't inform the user of the breaking change.
Another option is to simply leave it like this for now @aspacca @dmathieu, and wait for the new input type package, which will have a better user experience when it comes to changing dataset names.

I can bump the major version, remove the S3 input and create a changelog entry for it, newer versions of the stack will have a better way of displaying the changelog when upgrading, so maybe that is sufficient? We can bump the minimum stack version to 8.6+ or so?

**Comment by leandrojmp** [comment]
Hello @P1llus is this issue going to be solved? I didn't seen this PR before and opened a similar PR https://github.com/elastic/integrations/pull/8632 changing the dataset name.

I opened it based on this issue https://github.com/elastic/integrations/issues/5155 I reported in January after speding a couple of hours trying to understand why an ingest pipeline wasn't working.

If this isn't goling to be solved, then the documentation should be changed to inform that the integration ingest pipeline will not be used, as this can lead to confusion for the users.

**Pull request closed without merging**
