### PR TITLE
[O11y][StatsD Input] Fix hit count in system tests

### PR DESCRIPTION
**Pull request by aliabbas-elastic**
- Bug

## Proposed commit message

- Fixes the `hit_count` parameter wrongly set in this [PR](https://github.com/elastic/integrations/pull/9596)

## How to test this PR locally

1. elastic-package check
2. elastic-package stack up -d -v
3. elastic-package test -v

## Related issues

- Relates #9584 

## Screenshots

- Verified that the expected hit count is exactly `9` this time by the following run

<details>
  <summary>System Test Run</summary>

  ```
2024/04/23 11:57:23 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:24 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:25 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:26 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:27 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:28 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:29 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:30 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:31 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:32 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:33 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:34 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:35 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:36 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:37 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:38 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:39 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:40 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:41 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:42 DEBUG found 0 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:43 DEBUG found 3 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:44 DEBUG found 3 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:45 DEBUG found 3 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:46 DEBUG found 3 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:47 DEBUG found 3 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:48 DEBUG found 3 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:49 DEBUG found 3 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:50 DEBUG found 3 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:51 DEBUG found 3 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:52 DEBUG found 3 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:53 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:54 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:55 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:56 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:57 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:58 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:57:59 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:00 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:01 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:02 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:03 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:04 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:05 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:06 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:07 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:08 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:09 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:10 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:11 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:12 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:13 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:14 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:15 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:16 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:17 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:18 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:19 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:20 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:21 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:22 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:23 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:24 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:25 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:26 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:27 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:28 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:29 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:30 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:31 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:32 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:33 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:34 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:35 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:36 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:37 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:38 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:39 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:40 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:41 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:42 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:43 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:44 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:45 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:46 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:47 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:48 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:49 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:50 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:51 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:52 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:53 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:54 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:55 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:56 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:57 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:58 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:58:59 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:00 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:01 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:02 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:03 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:04 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:05 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:06 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:07 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:08 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:09 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:10 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:11 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:12 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:13 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:14 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:15 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:16 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:17 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:18 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:19 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:20 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:21 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:22 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:23 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:24 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:25 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:26 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:27 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:28 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:29 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:30 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:31 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:32 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:33 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:34 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:35 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:36 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:37 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:38 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:39 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:40 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:41 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:42 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:43 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:44 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:45 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:46 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:47 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:48 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:49 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:50 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:51 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:52 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:53 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:54 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:55 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:56 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:57 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:58 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 11:59:59 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:00 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:01 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:02 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:03 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:04 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:05 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:06 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:07 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:08 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:09 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:10 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:11 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:12 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:13 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:14 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:15 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:16 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:17 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:18 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:19 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:20 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:21 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:22 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:23 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:24 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:25 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:26 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:27 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:28 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:29 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:30 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:31 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:32 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:33 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:34 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:35 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:36 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:37 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:38 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:39 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:40 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:41 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:42 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:43 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:44 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:45 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:46 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:47 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:48 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:49 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:50 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:51 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:52 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:53 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:54 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:55 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:56 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:57 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:58 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:00:59 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:00 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:01 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:02 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:03 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:04 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:05 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:06 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:07 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:08 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:09 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:10 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:11 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:12 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:13 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:14 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:15 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:16 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:17 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:18 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:19 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
2024/04/23 12:01:20 DEBUG found 9 hits in metrics-statsd_input.statsd-ep data stream
  ```
</details>

### CODE REVIEW

**Review by harnish-elastic — APPROVED** [review]
LGTM!

**Comment by ritalwar** [comment]
Shall we update changelog?

**Comment by aliabbas-elastic** [comment]
> Shall we update changelog?

I don't think that's needed because we are just updating the test files to make sure the CI runs and expects the correct `hit_count`.

**Review by ritalwar — APPROVED** [review]

**Pull request merged**
