### PR TITLE
[O11y][Salesforce] Lens migration for visualizations to Kibana version 8.5.0

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

- Migrate visualizations to lens for Salesforce integration package

- Statistics for **Salesforce** Lens migration:

<html>
<body>
<google-sheets-html-origin>

Salesforce Dashboards | Before Migration |   |   | After Migration |   |  
-- | -- | -- | -- | -- | -- | --
  | Maps | Lens | Visualization | Maps | Lens | Visualization
[Logs Salesforce] Login Dashboard | 1 | 9 | 1 | 1 | 10 | 0
[Logs Salesforce] Apex Dashboard | 0 | 11 | 2 | 0 | 13 | 0
[Logs Salesforce] Logout Dashboard | 1 | 4 | 1 | 1 | 5 | 0
[Logs Salesforce] Setup Audit Trail Dashboard | 0 | 4 | 0 | 0 | 4 | 0
  | 2 | 28 | 4 | 2 | 32 | 0

</body>
</html>

## Checklist

- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that panels are populated with data.
- [x] I have verified that panels are not distorted after being migrated to lens.
- [x] I have updated screenshots of dashboard.
- [x] I have verified that data count are matching and panel aggregations are same as before.

## Author's checklist

- [x] Migrated panels should be removed from visualization folder.
- [x] Migrated visualizations are populating in current Kibana version 8.5.0 itself. 

## Related issues

- Relates #5221

### CODE REVIEW

**Review by agithomas — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
Please complete the Peer review before the merge.

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Comment by harnish-elastic** [comment]
> Please complete the Peer review before the merge.

@agithomas Merging this PR since peer review is completed.

**Comment by kush-elastic** [comment]
@harnish-elastic Can you update the title for the PR? I think version should be 8.5.0 instead of 8.4.0.

**Pull request merged**
