### PR TITLE
[TrendMicro VisionOne] Fix missing request in pipeline

### PR DESCRIPTION
**Pull request by kcreddy**
## Proposed commit message

 
The pipeline's` uri_parts` processor throws an error when `trend_micro_vision_one.detection.request` field is missing in the response. We have seen sample logs where this might happen. Certain categories of data such as `BEHAVIORAL_VIOLATION, INTEGRITY_MONITORING_EVENT, APPLICATION_CONTROL_VIOLATION, FIREWALL_POLICY_VIOLATION` etc. doesn't contain this field. Fixing this by adding a conditional.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

`cd packages/trend_micro_vision_one`
`elastic-package build && elastic-package stack up --version=8.11.0-SNAPSHOT -d -v --services=elasticsearch && eval "$(elastic-package stack shellinit)" && elastic-package test pipeline --generate`

## Related issues

-

### CODE REVIEW

**Review by efd6 — APPROVED** [review]
Do we know why these documents without `request` exist?

**Comment by kcreddy** [comment]
> Do we know why these documents without request exist?

Hey @efd6, I'm checking with the user. https://github.com/elastic/integrations/pull/8083#issuecomment-1756838536

**Review by bhapas — APPROVED** [review]

**Comment by kcreddy** [comment]
@efd6 let me know if you are okay with this user's explanation - https://github.com/elastic/integrations/pull/8083#issuecomment-1758932289. I will proceed merging the PR. Thanks!

**Comment by efd6** [comment]
@kcreddy Thanks, that is fine with me.

**Pull request merged**
