### PR TITLE
[windows] Update event code in powershell_operational ingest pipeline processor description

### PR DESCRIPTION
**Pull request by Doserdog**
- Bug

## What does this PR do?
Updates ingest pipeline processor description with correct event code.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Screenshots
image

### CODE REVIEW

**Review by nicpenning — CHANGES_REQUESTED** [review]
You will likely need to bump this up to 1.18.1 due to a feature that was recently merged. https://github.com/elastic/integrations/pull/5384

**Review by nicpenning — CHANGES_REQUESTED** [review]
Make sure to update here as well.

**Comment by nicpenning** [comment]
You still need to update the changelog and manifest. :)

**Comment by Doserdog** [comment]
Thanks!

/test

**Comment by nicpenning** [comment]
Looks like another System integration was updated and commited to pass this again. You will probably need to update the version again :( Is there a better way to handle this?

https://github.com/elastic/integrations/pull/5511

**Review by efd6 — APPROVED** [review]

**Review by rdner — APPROVED** [review]

**Pull request merged**
