### PR TITLE
[keycloak] Correct spelling "UCT -> UTC"

### PR DESCRIPTION
**Pull request by fionera**
## What does this PR do?

Fix typo in 'Timezone Offset' description.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by adriansr** [comment]
Thanks for your contribution @fionera !

You'll have to [sign the CLA](https://www.elastic.co/contributor-agreement) before we can review.

I see we've made this mistake in a few places:
```
packages/hid_bravura_monitor/data_stream/log/manifest.yml
packages/keycloak/data_stream/log/manifest.yml
packages/microsoft_dhcp/data_stream/log/manifest.yml
packages/pfsense/data_stream/log/manifest.yml
packages/qnap_nas/data_stream/log/manifest.yml
packages/snort/data_stream/log/manifest.yml
```

**Comment by legoguy1000** [comment]
> Thanks for your contribution @fionera !
> 
> You'll have to [sign the CLA](https://www.elastic.co/contributor-agreement) before we can review.
> 
> I see we've made this mistake in a few places:
> 
> ```
> packages/hid_bravura_monitor/data_stream/log/manifest.yml
> packages/keycloak/data_stream/log/manifest.yml
> packages/microsoft_dhcp/data_stream/log/manifest.yml
> packages/pfsense/data_stream/log/manifest.yml
> packages/qnap_nas/data_stream/log/manifest.yml
> packages/snort/data_stream/log/manifest.yml
> ```

Thats awkward.  I created 4 of those. I must have done it on one and then as I created/copied the others it propogated.

**Comment by adriansr** [comment]
> Thats awkward. I created 4 of those. I must have done it on one and then as I created/copied the others it propogated.

That's to be expected when one creates so many useful integrations.

**Pull request merged**
