### PR TITLE
[Azure] [OpenAI] Enhance Metrics Dashboard

### PR DESCRIPTION
**Pull request by lucian-ioan**
## Proposed commit message
WIP, enhancing Azure OpenAI integration dashboard in preparation for GA.

Switched to filtering by model, similar to Logs Dashboard and redid/added other vizualisations.

`provisioned_managed_utilization_v2.avg` -> Unfortunately this metric is empty, it could've been used also in comparison to requests total.

TODO:

- Need to populate RAI data into the dashboards (data about content filtered - Harmful and Rejected Requests)
- Content Filtered Requests Ratio = % of requests that have been filtered.
- Perhaps a vizualisation by model and requests would still be good even if we have the filters.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## Related issues

- 

## Screenshots

Before:
screencapture-muthu-cloud-instance-8-13-4-kb-us-central1-gcp-cloud-es-io-9243-app-dashboards-2024-05-27-06_32_02

After:
screencapture-muthu-cloud-instance-8-13-4-kb-us-central1-gcp-cloud-es-io-9243-app-dashboards-2024-05-27-06_31_08

### CODE REVIEW

**Comment by muthu-mps** [comment]
The `provisioned_managed_utilization_v2` metrics, we will not be getting now because these values come from the provisioned deployments. Once we get access we should be able to test the metrics.

**Comment by muthu-mps** [comment]
Reviewing the dashboard screenshots. Looks good, Left few comments.
+ Content filtered Requests Ration. Are we displaying the percentage value?
+ Can we update the title of the Requests chart to `Requests over the time` or Total Requests.
+ The `Token Overview` chart Y axis title shows Generated Tokens. Can you please double check whether the title is appropriate here? The same applies for RAI Requests and Operations.

**Comment by lucian-ioan** [comment]
@muthu-mps  

1. Content filtered Requests Ratio will be percentage value.
2. Yes.
3. The Y axis is appropriate for all vizualisations, similar to the Logs Dashboard we can look multiple related metrics, and if by-model view is ever needed, we can just use the filters.

**Comment by ishleenk17** [comment]
> The `provisioned_managed_utilization_v2` metrics, we will not be getting now because these values come from the provisioned deployments. Once we get access we should be able to test the metrics.

If we have deployment specific metrics, is there a need to mention this in the documentation for clarity of the user ?

**Comment by muthu-mps** [comment]
> > The `provisioned_managed_utilization_v2` metrics, we will not be getting now because these values come from the provisioned deployments. Once we get access we should be able to test the metrics.
> 
> If we have deployment specific metrics, is there a need to mention this in the documentation for clarity of the user ?

Yes Ishleen, This is captured and we have an open PR to address the same.

**Review by muthu-mps — APPROVED** [review]
Suggested title changes also update the latest image to the /img. Otherwise looks good!

**Pull request merged**
