### PR TITLE
[Cloud Security Posture] Update CloudFormation template format

### PR DESCRIPTION
**Pull request by opauloh**
### Summary

This PR updates the CloudFormation template format for the Vuln Mgmt policy. The format was now updated to support the full CloudFormation create stack URL, plus these additional parameters to be replaced by Kibana:
- `FLEET_ENROLLMENT_TOKEN`
- `FLEET_URL`
- `KIBANA_VERSION`

### Screenshot

image

### CODE REVIEW

**Review by olegsu — APPROVED** [review]

**Comment by eyalkraft** [comment]
Make sure stack name doesn't result with a failure on the second attempt due to collision (users are supposed to be able to launch this stack multiple times to install on different regions).

It is probably unique only in a specific region but make sure just in case 👍

**Comment by amirbenun** [comment]
I think that having a single link as part of our source code is a bad practice as it's harder to maintain.
Instead, we can split it into more than one parameter:
```
vars:
    - name: cloud_formation_quick_create
      default: https://console.aws.amazon.com/cloudformation/home#/stacks/quickcreate
    - name: templateURL
      default: https://elastic-cspm-cft.s3.eu-central-1.amazonaws.com/vuln-mgmt/cloudformation-8.8.0-2023-04-02-12-11-35.yml
    - name: stack_name
      default: Elastic-Vulnerability-Management
    - name: param_EnrollmentToken
      default: {{FLEET_ENROLLMENT_TOKEN}}
```

And so on...
On Kibana we will have to compose the link from all of the parameters and change the placeholders in runtime.
What do you think @opauloh?

**Comment by opauloh** [comment]
> I think that having a single link as part of our source code is a bad practice as it's harder to maintain. Instead, we can split it into more than one parameter:
> 
> ```
> vars:
>     - name: cloud_formation_quick_create
>       default: https://console.aws.amazon.com/cloudformation/home#/stacks/quickcreate
>     - name: templateURL
>       default: https://elastic-cspm-cft.s3.eu-central-1.amazonaws.com/vuln-mgmt/cloudformation-8.8.0-2023-04-02-12-11-35.yml
>     - name: stack_name
>       default: Elastic-Vulnerability-Management
>     - name: param_EnrollmentToken
>       default: {{FLEET_ENROLLMENT_TOKEN}}
> ```
> 
> And so on... On Kibana we will have to compose the link from all of the parameters and change the placeholders in runtime. What do you think @opauloh?

I don't like all that extra work and composition just for the template URL, as it will be harder to maintain and reuse in other integrations in the future (whenever needed to add an extra parameter for CloudFormation, it would be required to update the URL parser in Kibana, which sounds fragile).

But for improving maintainability, we can split stack_name and template_url as you suggested:

```yml
vars:
    - name: cloud_formation_stack_name
      default: Elastic-Vulnerability-Management
    - name: cloud_formation_template_url
      default: https://elastic-cspm-cft.s3.eu-central-1.amazonaws.com/vuln-mgmt/cloudformation-8.8.0-2023-04-02-12-11-35.yml
    - name: cloud_formation_url
      default: https://console.aws.amazon.com/cloudformation/home#/stacks/quickcreate?templateURL={{cloud_formation_template_url}}&stackName={{cloud_formation_stack_name}}&param_EnrollmentToken={{FLEET_ENROLLMENT_TOKEN}}&param_FleetUrl={{FLEET_URL}}&param_ElasticAgentVersion=elastic-agent-{{KIBANA_VERSION}}-linux-arm64
```

Let me know what do you think @amirbenun, the above would only require one update in kibana to look for `cloud_formation_stack_name` and `cloud_formation_url` provided alongside the `cloud_formation_url`, but doesn't affect the logic that builds the URL, which only handles the replaces.

**Pull request merged**
