### PR TITLE
[cisa_kev] Update logo to align w/ Elastic Integrations page 2

### PR DESCRIPTION
**Pull request by nicpenning**
- Bug
Simply updating logo so that the integration matches the logo here: https://www.elastic.co/integrations/data-integrations?search=cisa

Also, this corrects the manifest description so that it reads well.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by efd6** [comment]
@nicpenning Can you provide a screenshot of the new page?

**Comment by nicpenning** [comment]
Yes, I can do that

**Comment by nicpenning** [comment]
image

image

**Comment by nicpenning** [comment]
Not sure why my manifest is not reflecting after the build. Text is wrong above on first screenshot.

**Comment by efd6** [comment]
Probably caching. I just wanted to check that the image is rendering as expected.

**Comment by nicpenning** [comment]
Excellent, thank you! Until next time 😀

**Pull request merged**
