### PR TITLE
Handle missing community_id attributes for Cisco and Sophos devices

### PR DESCRIPTION
**Pull request by gogochan**
## Proposed commit message

This PR fixes the pipeline failure by populating `community_id` attributes.

This change only works with 8.16.0. We can merge when it is ready.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## Related issues
- https://github.com/elastic/integrations/issues/10903
- https://github.com/elastic/integrations/issues/10904
- https://github.com/elastic/integrations/issues/10907
- https://github.com/elastic/integrations/issues/10908

### CODE REVIEW

**Comment by gogochan** [comment]
Confirmed that payload update makes the test pass with stack version `8.16.0-SNAPSHOT`

**Comment by andrewkroh** [comment]
@gogochan Could [dynamic_fields](https://github.com/elastic/elastic-package/blob/46d80b55f5bc445c5e087070b05d0ad32b3667e5/docs/howto/pipeline_testing.md?plain=1#L104) be used to ignore this field? Like this...

```yaml
dynamic_fields:
  network.community_id: "^.*$" # Match anything.
```

**Comment by andrewkroh** [comment]
@gogochan CI is passing now 😄 . Have you confirmed locally that this also checks out on ES 8.16?

**Comment by gogochan** [comment]
I applied the changes to the wrong place. Now it is passing 8.16 as well.

**Review by andrewkroh — APPROVED** [review]

**Pull request merged**
