### PR TITLE
[Elastic Agent] Adding new dashboards to monitor Agent Health

### PR DESCRIPTION
**Pull request by P1llus**
## What does this PR do?

Using this PR to gather some initial feedback from tomorrow, so some of the visualizations might change slightly. Don't merge it just yet.

As discussed with @nimarezainia and @joshdover 

This change adds a few different components:
1. New Agent Overview dashboard.
2. New Agent Information dashboard.
3. Updates Agent metrics dashboard to Lens (still missing Cgroup CPU usage).
4. New Agent Integration dashboard.
5. Bumps minimum version for newer dashboard features.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates https://github.com/elastic/integrations/issues/5245

## Screenshots

**Overview**
AgentHealthNew

**Integrations**
AgentIntegrationsNew

**Metrics**
AgentMetrics1New
AgentMetricsNew2

**Information**
AgentInfoNew

### CODE REVIEW

**Comment by joshdover** [comment]
This is looking great from the screenshots, haven't tested locally.

Can we rename "current active agents" to "agents ingested data" or something similar? I want it to be clear that this is based data ingested rather than agents connected.

@pierrehilbert @cmacknz PTAL as well

**Comment by P1llus** [comment]
The CPU Usage Lens metric I converted from TSVB has to be converted back for now. The Interval context we use to divide the metrics value is not available in Lens yet, this has been reported and an issue is being created to add this issue.

Except that, I will perform a few minor tweaks and changes, before the dashboard should be ready to go.

**Comment by jamiehynds** [comment]
**Integrations page:** Could we expose 'Integrations by last event received' so users can identify integrations that are no longer receiving events or experiencing long delays? Could we also expose 'Outdated integrations' whereby a new version for the integration is available, to encourage users to update?

**Comment by jamiehynds** [comment]
These dashboards are great, and provide a tonne of value to users but I fear a user will have to stumble upon them or do some digging to find them. In order to expose these dashboards (to our security users at least), can we add a 'Security' tag to ensure they appear under Security -> Dashboards. 

I know this isn't possible today, but would like to understand who we need to lean on in order to support that use case. The dashboards deserve as much exposure as possible.

**Comment by P1llus** [comment]
> **Integrations page:** Could we expose 'Integrations by last event received' so users can identify integrations that are no longer receiving events or experiencing long delays? Could we also expose 'Outdated integrations' whereby a new version for the integration is available, to encourage users to update?

The issue with the current implementation compared to a custom Kibana UI is that we can only query for data that is actually there. I totally agree that its some information we should add in, but it wont be available to us with the data we have today.
Same with the versions, we should communicate that with @nimarezainia, and maybe we can add it to the custom UI once that is available?

**Comment by P1llus** [comment]
> These dashboards are great, and provide a tonne of value to users but I fear a user will have to stumble upon them or do some digging to find them. In order to expose these dashboards (to our security users at least), can we add a 'Security' tag to ensure they appear under Security -> Dashboards.
> 
> I know this isn't possible today, but would like to understand who we need to lean on in order to support that use case. The dashboards deserve as much exposure as possible.

I am unsure the best way to go about it today. If we want ALL security related dashboards with that tag (meaning all packages that have the security category), we could have fleet add the tags based on the categories of the packages? That way all packages in the security category will have its dashboards available there.
I believe @kpollich would be one to reach out to for this.

**Comment by jamiehynds** [comment]
@kpollich in relation to the comment above, do you have any thoughts as to how we can ensure the ingest/agent health dashboards can appear under Custom Dashboards in Security? I believe if the dashboards are tagged with 'security' they will appear here, but there are some bugs associated. 

Screenshot 2023-02-23 at 15 44

**Comment by kpollich** [comment]
> we could have fleet add the tags based on the categories of the packages

This is indeed something Fleet can do, however there are a _lot_ of categories, and now we've got subcategory mappings to be concerned with as well. I worry about bloating the number of tags that ship with Kibana out of the box based on the full set of integrations. 

> in relation to the comment above, do you have any thoughts as to how we can ensure the ingest/agent health dashboards can appear under Custom Dashboards in Security? I believe if the dashboards are tagged with 'security' they will appear here, but there are some bugs associated.

I'm unfamiliar with the specifics of how this "custom dashboards" list is rendered in the Security app, but if it's based on asset tags it should be relatively straightforward to get a "Security" tag onto these assets. @P1llus - would it be possible to add the security tag to the `references` property of a given dashboard, e.g. https://github.com/elastic/integrations/pull/5335/files#diff-0b8d78edfcb1ec58ae5489b1bf5beea24089920f930af51f713655e27dad9517R683

Looking at this more, it seems Kibana ships with a `Security Solution` tag, e.g. 

image

Adding a dashboard with this tag does in fact cause it to show on the security solution dashboards page, e.g:

image

I'm not sure if we can reference this tag in asset definitions, though, as I don't think the ID is deterministic. 

```
GET .kibana/_search?q=type:tag

{
  "took": 7,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 7.103322,
    "hits": [
      {
        "_index": ".kibana_8.8.0_001",
        "_id": "tag:de131a10-b39b-11ed-b54b-15224cf62f23",
        "_score": 7.103322,
        "_source": {
          "tag": {
            "name": "Security Solution",
            "description": "Security Solution auto-generated tag",
            "color": "#1ecccd"
          },
          "type": "tag",
          "references": [],
          "namespaces": [
            "default"
          ],
          "migrationVersion": {
            "tag": "8.0.0"
          },
          "coreMigrationVersion": "8.0.0",
          "updated_at": "2023-02-23T17:02:34.545Z",
          "created_at": "2023-02-23T17:02:34.545Z"
        }
      }
    ]
  }
}
```

We could implement some logic in Fleet to detect whether a package is categorized with `Security`, look up this `Security Solution tag, and add the tag reference to all generated assets in that case, but that feels like quite a bit of hardcoding and I'd worry about it being a brittle solution.

**Comment by P1llus** [comment]
@kpollich I think we can try to manually add this reference, and test if it works, however it would still be a manual workaround. If I would add that existing tag to the dashboard, then export the dashboard again with elastic-package, it will create a new tag reference, using the name of the integration as part of the ID, which is why the tag is always unique :(

**Comment by P1llus** [comment]
@kpollich I could not find this "Security Solutions" tag when spinning up a new 8.6.1 cluster with elastic-package, so it does not seem to be default?

**Comment by P1llus** [comment]
I think the plan forward is to merge this dashboard without the tag, and in the meantime I will reach out to the relevant teams and find a solution.

The easiest is to make sure fleet installs the tag by default, and that the security solutions UI uses that instead.

**Comment by P1llus** [comment]
This is now ready for review 👍

**Comment by P1llus** [comment]
The discussion around tags above is resolved by: https://github.com/elastic/kibana/issues/152814 and can be ignored.

**Review by joshdover — APPROVED** [review]
I feel comfortable shipping this now. If we find issues in the field, we can revert it.

**Comment by cmacknz** [comment]
Haven't had a chance to do a detailed review but the screenshots look great, no concerns shipping this from me.

**Comment by michalpristas** [comment]
haven't tested locally, from screenshot it looks great. very good job.
this was not clear to me most Active Integrations - meaning most agents have this integration or this integration spikes resources the most or producing most events?

I like events per integrations overview 💙 

Metrics - resources, I hope we can replace this one with consumption per integration soon. User does not need to know how integration maps to processes.

**Comment by P1llus** [comment]
> haven't tested locally, from screenshot it looks great. very good job. this was not clear to me most Active Integrations - meaning most agents have this integration or this integration spikes resources the most or producing most events?
> 
> I like events per integrations overview 💙
> 
> Metrics - resources, I hope we can replace this one with consumption per integration soon. User does not need to know how integration maps to processes.
> 
> 🚢 🚢 🚢

I do plan on a updated version once the input metrics are out in 8.7 @michalpristas, my only conern was that some of the metrics we collect was a bit confusing. If I could get some basic help around that at some point, we could discuss a better approach to the metrics for sure!

**Comment by cmacknz** [comment]
>  my only conern was that some of the metrics we collect was a bit confusing. If I could get some basic help around that at some point, we could discuss a better approach to the metrics for sure!

@P1llus I'd be happy to help explain what the metrics mean so we can further improve this.

**Comment by P1llus** [comment]
@cmacknz I will reach our to pick this up then!

**Pull request merged**
