### PR TITLE
[Apache Spark] Migrate to GA

### LINKED ISSUE #7406: Make Apache Spark GA
- Make Apache Spark GA with the following data streams
   - Metrics:
       - application 
       - executor
       - driver
       - node

### Issue & Enhancements

- https://github.com/elastic/integrations/issues/7407
- https://github.com/elastic/integrations/issues/7409
- https://github.com/elastic/integrations/issues/7411
- https://github.com/elastic/integrations/issues/7410
- https://github.com/elastic/integrations/issues/7408
- https://github.com/elastic/integrations/issues/8116

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

Migrates the integration from BETA to GA.

## Related issues

- Closes #7406

### CODE REVIEW

**Review by milan-elastic — APPROVED** [review]

**Comment by muthu-mps** [comment]
@harnish-elastic,

- The compatibility check is done with 3.2.0 version of apache spark which is released on 2021. Can we do a test with recent major release. If done already can we update the document to have a mention of 3.2.0 and later versions ?

**Comment by harnish-elastic** [comment]
> @harnish-elastic,
> 
> * The compatibility check is done with 3.2.0 version of apache spark which is released on 2021. Can we do a test with recent major release. If done already can we update the document to have a mention of 3.2.0 and later versions ?

@muthu-mps I have tested Apache Spark with the latest [version](https://spark.apache.org/downloads.html) (3.5.0) and it's working properly. Hence I have updated the README with version `3.5.0`

**Review by muthu-mps — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
@muthu-mps , @harnish-elastic , as we are in the final stage of TSDB enablement for Apache Spark, it would be good to have this merged after TSDB enablement.

**Review by devamanv — APPROVED** [review]
LGTM!

**Pull request merged**
