### PR TITLE
Sonicwall Integration Enhancement

### PR DESCRIPTION
**Pull request by donasmello**
Type of Change: Enhancement

## What does this PR do?

I was having issues with the Sonicwall integration parsing logs for Sonicwall firewalls on firmware 6.5.x.  Was getting a dissect parse error for every log.  I referenced the Fortinet firewall integration to update the Sonicwall firewall integration to parse Sonicwall firewall logs.  Pointed a lab Sonicwall firewall to a host with the integration installed and validated log collection.

## Checklist

- [x ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x ] I have verified that all data streams collect metrics or logs.
- [ x] I have added an entry to my package's `changelog.yml` file.

## Author's Checklist

- [ ] Validate that the sonicwall integration works via elastic-package registry using the log file method.  Can use example logs in the test file.

## How to test this PR locally

Follow the contributing guide and use the sonicwall integration 

https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md

## Related issues

https://discuss.elastic.co/t/filebeat-sonicwall-module-not-parsing-correctly-many-messages/268232/5

### CODE REVIEW

**Review by donasmello — COMMENTED** [review]
changes made to bring up to date with elastic/integrations master branch

**Comment by donasmello** [comment]
Is there any additional review that I need to do on this?

**Comment by adriansr** [comment]
Hi @donasmello !

Thanks for your contribution. We are reviewing it, sorry for taking so long

**Comment by adriansr** [comment]
@donasmello do you mind sharing some sample logs from your device? The current pipeline (after fixing it, it broke during a merge) can't parse any of the sample logs under `packages/sonicwall/_dev/deploy/docker/sample_logs/`. You can commit a new sample file to that directory.

**Pull request closed without merging**
