### PR TITLE
[AWS] Add Firewall metrics dashboard input control groups

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?

Adds input control groups.

I'm not sure if the markdown visualization (first one from images) can be converted to a lens. Should it be left like that or removed?

Before:
firewall_before

After: 
firewall_after

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by drewdaemon — COMMENTED** [review]
Is there a reason you chose to use the Lens legacy metric visualization? In the future, this will likely be removed in favor of the metric visualization.

**Comment by gpop63** [comment]
Replaced legacy metric charts. This is how it looks now:

firewall_metric_chart

**Review by drewdaemon — APPROVED** [review]
@gpop63 sorry about this—let's take these back to the legacy metric for now. The way this dashboard is set up, especially after removing the legacy dashboard controls from the layout, just leaves too much vertical room for the new metric to make much sense.

Approving so as not to hold you up.

**Comment by drewdaemon** [comment]
From meeting
- put metrics in 3 columns of two
- increase size of markdown panel to half of page (check if these metrics get too small on smaller screen)
- make metrics white

**Comment by gpop63** [comment]
@drewdaemon what do you think about the new layout?

firewall_new_layout

**Review by drewdaemon — APPROVED** [review]
LGTM!

**Review by zmoog — APPROVED** [review]

**Pull request merged**
