### PR TITLE
[O11y][HAProxy] Migrate stat data-stream visualizations to lens in kibana 8.4.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate stat data-stream visualizations to lens for HAProxy integration package

- Statistics for HAProxy Lens migration:
<html>
<body>

HAProxy Dashboards  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics HAProxy] HTTP backend | 0 | 8 | 8 | 0
[Metrics HAProxy] Overview | 0 | 4 | 4 | 0
[Metrics HAProxy] Frontend | 0 | 2 | 2 | 0
[Metrics HAProxy] HTTP frontend | 0 | 3 | 3 | 0
[Metrics HAProxy] HTTP server | 0 | 6 | 6 | 0
[Metrics HAProxy] Backend | 0 | 6 | 6 | 0
  | 0 | 29 | 29 | 0

</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.4.0 itself.

## Related issues

- Relates #5221 

## Issues

~Below 10 panels are not migrated due to lens limitations:~
<html>
<body>

~Dashboard~ | ~Visualization~ | ~Reason~
-- | -- | --
~[Metrics HAProxy] HTTP backend~ | ~Downtime seconds [Metrics HAProxy]~ | ~https://github.com/elastic/kibana/issues/153326~
  | ~Connections per server [Metrics HAProxy]~ | ~https://github.com/elastic/kibana/issues/153326~
  | ~Active servers in backend [Metrics HAProxy]~ | ~https://github.com/elastic/kibana/issues/153326~
~[Metrics HAProxy] HTTP server~ | ~Healthcheck [Metrics HAProxy]~ | ~Complex painless script~
~[Metrics HAProxy] Backend~ | ~Downtime seconds [Metrics HAProxy]~ | ~https://github.com/elastic/kibana/issues/153326~
  | ~Connections per server [Metrics HAProxy]~ | ~https://github.com/elastic/kibana/issues/153326~
  | ~Active servers in backend [Metrics HAProxy]~ | ~https://github.com/elastic/kibana/issues/153326~
~[Metrics HAProxy] Overview~  | ~Frontends~ | ~https://github.com/elastic/kibana/issues/153326~
  | ~Backends~ | ~https://github.com/elastic/kibana/issues/153326~
  | ~Servers visualizations~ | ~https://github.com/elastic/kibana/issues/153326~

</body>
</html>

Note: Please find below screenshots of dashboards (before migration) to compare migrated panels:

**[Metrics HAProxy] Overview**:
image

**[Metrics HAProxy] HTTP backend**:
image

**[Metrics HAProxy] Backend**:
image

**[Metrics HAProxy] HTTP Frontend**:
image

**[Metrics HAProxy] HTTP server**:
image

**[Metrics HAProxy] Frontend**:
image

### CODE REVIEW

**Comment by rajvi-elastic** [comment]
@agithomas, As we have mentioned in the description, there are 10 panels which have not be migrated to the lens. We have found work around for  `Healthcheck [Metrics HAProxy]` panel from `[Metrics HAProxy] HTTP server` dashboard which was blocked. The functionality can be replicated using **conditional operations** which are added in Kibana `v8.6.0` ([Github Issue](https://github.com/elastic/kibana/pull/142325)). 

Currently, we have migrated everything to 8.4.0. In order to migrate this new panel, we will have to upgrade to the newer Kibana version (v8.6.0). 

Can you please let us know how should we proceed further?

**Comment by agithomas** [comment]
> Currently, we have migrated everything to 8.4.0. In order to migrate this new panel, we will have to upgrade to the newer Kibana version (v8.6.0).

@rajvi-elastic , are you saying with 8.6.0 migration, we would have 100% lens migration for HAProxy dashboards?

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic , are you saying with 8.6.0 migration, we would have 100% lens migration for HAProxy dashboards?

No @agithomas . Not all the 10 remaining panels could be migrated to the lens. Only one panel which is blocked due to **Complex painless script** could be migrated. All the other 9 panels are blocked due to https://github.com/elastic/kibana/issues/153326. 

With v8.6.0 we will be only able to migrate one panel from the list. Other 9 panels would be still visualizations.

**Comment by rajvi-elastic** [comment]
@agithomas, There is one [screenshot of the dashboard](https://github.com/elastic/integrations/blob/main/packages/haproxy/img/kibana-haproxy-overview.png) of the filebeat module. It seems redundant to me, we already have updated the latest screenshot [here](https://github.com/elastic/integrations/pull/5611/files#diff-ee90eba8ce5c09e3da272dd3da95c380bbf42ae8b965ac3e1250660c97be4f00). If it's not needed now then please remove this from the integration.

**Comment by agithomas** [comment]
> All the other 9 panels are blocked due to [elastic/kibana#153326](https://github.com/elastic/kibana/issues/153326)

@SubhrataK , is the last bucket issue highlighted here and referred in other integrations can now be considered is not an issue anymore ? 

@rajvi-elastic , please confirm if the issue is similar to other integrations and there are no edge cases here.

**Comment by agithomas** [comment]
> @agithomas, As we have mentioned in the description, there are 10 panels which have not be migrated to the lens. We have found work around for `Healthcheck [Metrics HAProxy]` panel from `[Metrics HAProxy] HTTP server` dashboard which was blocked. The functionality can be replicated using **conditional operations** which are added in Kibana `v8.6.0` ([Github Issue](https://github.com/elastic/kibana/pull/142325)).
> 
> Currently, we have migrated everything to 8.4.0. In order to migrate this new panel, we will have to upgrade to the newer Kibana version (v8.6.0).
> 
> Can you please let us know how should we proceed further?

@lalit-satapathy , what is your take on this? The benefit of migrating to 8.6.0 from 8.4.0 is only for just one panel. My personal preference is to retain this one panel in old vis style and migrate when there exist a proper solution instead of workaround.

**Comment by rajvi-elastic** [comment]
> @SubhrataK , is the last bucket issue highlighted here and referred in other integrations can now be considered is not an issue anymore ?
> 
> @rajvi-elastic , please confirm if the issue is similar to other integrations and there are no edge cases here.

No @agithomas, The issue that is mentioned here is not similar to what we discussed in [IBM MQ](https://github.com/rajvi-elastic/integrations). We are still discussing this last bucket issue with Kibana team and they have scheduled a call in next week.

**Comment by rajvi-elastic** [comment]
As discussed with @SubhrataK, 

1. For the issue `Not having feature to set last bucket value`, we are good with the metrics chart. For the line/area chart we need `auto` functionality in `reduced timerange`. So for the time series visualization we still need to discuss with the kibana team.

2. For the `Splitting a chart into multiple smaller charts by a breakdown dimension is not supported in the lens`, we are going to migrate into table chart. Also need to re-arrange the dashboard like first metrics, then line/area/bar charts, and the table charts be at last. 

3.  Split Active server in backend into 2 panels which represents Active server and Total server.

**Comment by rajvi-elastic** [comment]
@agithomas, Can you please help me understand the aggregation that has been used in `Connections per server` panel. The panel is using last value functionality along with drilldowns. In order to migrate this visualization in lens, it would be better to have an understanding of why average and derivatives are applied on `haproxy.stat.connection.total` rather than directly using the value of `haproxy.stat.connection.total` :
 
screencapture-storage-0-kb-us-central1-gcp-cloud-es-io-9243-app-visualize-2023-04-06-17_44_25

screencapture-storage-0-kb-us-central1-gcp-cloud-es-io-9243-app-visualize-2023-04-06-17_44_44

CC: @SubhrataK

**Comment by agithomas** [comment]
> @agithomas, Can you please help me understand the aggregation that has been used in `Connections per server` panel. The panel is using last value functionality along with drilldowns. In order to migrate this visualization in lens, it would be better to have an understanding of why average and derivatives are applied on `haproxy.stat.connection.total` rather than directly using the value of `haproxy.stat.connection.total` :
> 
> screencapture-storage-0-kb-us-central1-gcp-cloud-es-io-9243-app-visualize-2023-04-06-17_44_25
> 
> screencapture-storage-0-kb-us-central1-gcp-cloud-es-io-9243-app-visualize-2023-04-06-17_44_44
> 
> CC: @SubhrataK

It appears that the field is of metric_type counter. Avg() function may not be the agg function to use here. It is important to find out the rate of change on counter field and hence derivative() function is used. 

You may consider changing from avg() to max() while making the lens migration.

**Comment by rajvi-elastic** [comment]
> @lalit-satapathy , what is your take on this? The benefit of migrating to 8.6.0 from 8.4.0 is only for just one panel. My personal preference is to retain this one panel in old vis style and migrate when there exist a proper solution instead of workaround.

@agithomas, The solution that we have implemented is the same as auto lens migration implements (`Edit visualization in lens` option). In older TSVB visualization, the **ternary** operator was used which can be replicated in lens using **ifelse** condition `v8.6.0`. In both the cases the counts are accurate and If we migrate to 8.6.0 then we will achieve 100% migration. 

Please let us know whether we should migrate to the 8.6.0 or not?

**Comment by rajvi-elastic** [comment]
> > @agithomas, The solution that we have implemented is the same as auto lens migration implements (`Edit visualization in lens` option). In older TSVB visualization, the **ternary** operator was used which can be replicated in lens using **ifelse** condition `v8.6.0`. In both the cases the counts are accurate and If we migrate to 8.6.0 then we will achieve 100% migration.
> > Please let us know whether we should migrate to the 8.6.0 or not?
> 
> Please proceed.

@agithomas, All the panels have been migrated to lens (Kibana v8.6.0).

**Review by milan-elastic — APPROVED** [review]

**Review by agithomas — COMMENTED** [review]
`packages/haproxy/img/haproxy-metrics-http-frontend.png` have negative values for traffic volume. Please correct them.

**Comment by rajvi-elastic** [comment]
> `packages/haproxy/img/haproxy-metrics-http-frontend.png` have negative values for traffic volume. Please correct them.

@agithomas, this panel uses the differences. This has the similar aggregations as [oracle](https://github.com/elastic/integrations/pull/5815#issuecomment-1506444750) panel..

**Comment by agithomas** [comment]
> > `packages/haproxy/img/haproxy-metrics-http-frontend.png` have negative values for traffic volume. Please correct them.
> 
> @agithomas, this panel uses the differences. This has the similar aggregations as [oracle](https://github.com/elastic/integrations/pull/5815#issuecomment-1506444750) panel..

Well, it is understandable from Oracle Integration snapshot, it is not clear here that what is represented is a difference from previous value. In oracle, the actual value was shown and then the line showing the difference is an overlay. I understand that this is how things were in the past . 

@SubhrataK , can you please have a quick check on this and recommend a suitable title change or a better representation of panel data such as -  data + difference value

**Comment by agithomas** [comment]
> > > `packages/haproxy/img/haproxy-metrics-http-frontend.png` have negative values for traffic volume. Please correct them.
> > 
> > 
> > @agithomas, this panel uses the differences. This has the similar aggregations as [oracle](https://github.com/elastic/integrations/pull/5815#issuecomment-1506444750) panel..
> 
> Well, it is understandable from Oracle Integration snapshot, it is not clear here that what is represented is a difference from previous value. In oracle, the actual value was shown and then the line showing the difference is an overlay. I understand that this is how things were in the past .
> 
> @SubhrataK , can you please have a quick check on this and recommend a suitable title change or a better representation of panel data such as - data + difference value

@rajvi-elastic , please create a backlog issue for this. It may be best we take it up separately in the interest of time.

**Comment by agithomas** [comment]
Rest things are good. 

Version change from 8.0.0 to 8.6.0 needs approval, deferring the PR approval until then.

**Comment by agithomas** [comment]
@rajvi-elastic , 

please wait till https://github.com/elastic/integrations/pull/8204 is merged .

**Comment by rajvi-elastic** [comment]
Another [PR](https://github.com/elastic/integrations/pull/8375) has been raised for HAProxy lens migration.

**Pull request closed without merging**
