### PR TITLE
[zerofox_threatfeed] ZeroFOX Threatfeed Integration

### PR DESCRIPTION
**Pull request by zf-jedmunds**
Enhancement

## What does this PR do?

ZeroFOX ThreatFeed

@jamiehynds @marc-gr

### CODE REVIEW

**Comment by andrewkroh** [comment]
@Mergifyio rebase

**Comment by jamiehynds** [comment]
@andrewkroh this PR was submitted by Zerofox prior to our [ECS threat feeds](https://www.elastic.co/guide/en/ecs/current/ecs-threat.html) being available. Probably worth updating the mappings to ensure our IOC match rules will work, inline with our other Threat Intel integrations. 

@zf-jedmunds I presume the threat feed integration is still relevant on the Zerofox side?

**Comment by jamiehynds** [comment]
> @jamiehynds this feed is actually deprecated and would need to be replaced with our newly released Threat Intelligence endpoints / feeds...

@zf-jedmunds is a Threat Intelligence integration of interest to Zerofox? We're seeing strong demand for TI feed ingest and several vendors have built integrations including Anomali, Recorded Future, ThreatQuotient and others.

**Pull request closed without merging**
