### PR TITLE
cef: ensure timezones are strings

### PR DESCRIPTION
**Pull request by efd6**
## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by andrewkroh** [comment]
This is passing for me locally using stack 8.1.0 (same as CI). 🤷‍♂️

**Comment by efd6** [comment]
Yeah this was an xpt to see if it was interaction between packages.

**Comment by andrewkroh** [comment]
I am wondering if there is some interaction between the two different logfile system tests (like the second execution does read the files b/c it thinks it already read them once). I pushed a change to run only a single test.

**Comment by efd6** [comment]
This is the thought I had and why I asked if I was holding stream wrong. Looks like I am.

**Comment by andrewkroh** [comment]
The problem seems to be related to Filebeat state. The change in 0478623 made it pass by using unique files in each test. Looking at the registry contents after the tests finish I see:

`
{"k":"filebeat::logs::native::46739704-134","v":{"offset":3426,"ttl":-1,"type":"log","id":"native::46739704-134","prev_id":"","source":"/tmp/service_logs/arcsight.log","timestamp":[427954886,1674779470],"FileStateOS":{"inode":46739704,"device":134},"identifier_name":"native"}}
`

`
{"k":"filebeat::logs::native::46739800-134","v":{"offset":764,"timestamp":[93762627,1674779511],"FileStateOS":{"inode":46739800,"device":134},"identifier_name":"native","id":"native::46739800-134","prev_id":"","source":"/tmp/service_logs/cef.log","ttl":-1,"type":"log"}}
`

What's not present in those lines that I expected to see is the ID assigned to the `log` input by Fleet. I figured the some part of the stream ID would be part of the registry key.

```yaml
    streams:
      - id: logfile-cef.log-fb5db97d-a7e1-462f-a9ea-57915fd6db32
        data_stream:
          dataset: cef.log
          type: logs
        paths:
          - /tmp/service_logs/arcsight.log
```

I suspect that this is because the `log` input is not a Filebeat v2 input. So the input does not automatically utilize the `id`. I might try the original test config but with the `filestream` input to see what happens.

**Comment by andrewkroh** [comment]
With the filestream input you can see that the same file has an ID related to the respective stream instances. This allows it to be read by each unique test.

`{"k":"filestream::filestream-cef.log-3b9fce4f-94b8-472a-8e01-f146800f84f1::native::46741448-134","v":{"cursor":{"offset":1561},"meta":{"source":"/tmp/service_logs/netscaler.log","identifier_name":"native"},"ttl":1800000000000,"updated":[920015216,1674780754]}}`

`{"k":"filestream::filestream-cef.log-b32ab652-2b8c-4d73-9359-a73e12e95060::native::46741662-134","v":{"ttl":1800000000000,"updated":[619438219,1674780849],"cursor":{"offset":1561},"meta":{"source":"/tmp/service_logs/netscaler.log","identifier_name":"native"}}}`

**Comment by andrewkroh** [comment]
So I would say for this issue, let's tailor the test configuration to get the tests to pass (use unique log file paths in each test). There's ongoing work to make it possible to transition from `log` to `filestream` within integrations (and not lose state). 

- https://github.com/elastic/integrations/issues/2495
- https://github.com/elastic/beats/pull/34292

**Comment by efd6** [comment]
I'll do that in the change that includes the other affected packages.

**Pull request closed without merging**
