### PR TITLE
Update elastic-package to latest version (for fields type assertion)

### PR DESCRIPTION
**Pull request by mtojek**
## What does this PR do?

This PR updates elastic-package to the latest version to enable fields type assertion.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [ ] I have verified that all datasets collect metrics or logs.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by mtojek** [comment]
@ycombinator I tried to run it locally and actually there is an issue with test results presentation:

```
packages/zeek:
elastic-package test system --report-format xUnit --report-output file
Run system tests for the package
packages/zookeeper:
elastic-package test system --report-format xUnit --report-output file
Run system tests for the package
packages/zoom:
elastic-package test system --report-format xUnit --report-output file
Run system tests for the package
elastic-package stack down
Take down the Elastic stack
Done
```
(no error)

but when I modify the formatter to human:

```
packages/nginx:
elastic-package test pipeline --report-format xUnit --report-output stdout
Run pipeline tests for the package
--- Test results for package: nginx - START ---
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="pipeline" tests="4" failures="4">
    <!--test suite for pipeline tests-->
    <testcase name="[nginx/access] pipeline test: test-access-event.json" classname="" time="0.050823126">
      <failure>test case failed: one or more problems with fields found in documents: [0] field &#34;related.ip&#34; is undefined&#xA;[1] field &#34;source.address&#34; is undefined&#xA;[2] field &#34;source.ip&#34; is undefined&#xA;[3] field &#34;user_agent.os.full&#34; is undefined</failure>
    </testcase>
    <testcase name="[nginx/access] pipeline test: test-access-raw.log" classname="" time="0.249006348">
      <failure>test case failed: one or more problems with fields found in documents: [0] field &#34;ecs.version&#34; is undefined&#xA;[1] field &#34;related.ip&#34; is undefined&#xA;[2] field &#34;source.address&#34; is undefined&#xA;[3] field &#34;source.as.number&#34; is undefined&#xA;[4] field &#34;source.as.organization.name&#34; is undefined&#xA;[5] field &#34;source.geo.country_name&#34; is undefined&#xA;[6] field &#34;source.ip&#34; is undefined&#xA;[7] field &#34;user_agent.os.full&#34; is undefined</failure>
    </testcase>
    <testcase name="[nginx/error] pipeline test: test-error-raw.log" classname="" time="0.009410137">
      <failure>test case failed: one or more problems with fields found in documents: [0] field &#34;error.message&#34; is undefined&#xA;[1] field &#34;nginx.error.time&#34; is undefined</failure>
    </testcase>
    <testcase name="[nginx/ingress_controller] pipeline test: test-ingest-raw.log" classname="" time="0.038396974">
      <failure>test case failed: one or more problems with fields found in documents: [0] field &#34;error.message&#34; is undefined&#xA;[1] field &#34;nginx.ingress_controller.time&#34; is undefined&#xA;[2] field &#34;source.address&#34; is undefined&#xA;[3] parsing field value failed: field &#34;nginx.ingress_controller.upstream.port&#34; has invalid type, expected: long, actual Go type: string</failure>
    </testcase>
  </testsuite>
</testsuites>
--- Test results for package: nginx - END   ---
```

I think we need to modify `mage check` (and other steps?) to report/fail locally for people who would like to check their integrations locally. There is also a bug because the `mage check` ends up without any "bad" exit code.

**Comment by ycombinator** [comment]
> I tried to run it locally 

What command exactly did you run locally? `mage check`?

> but when I modify the formatter to human:
...
> `elastic-package test pipeline --report-format xUnit --report-output stdout`

That still looks like the `xUnit` formatter?

> I think we need to modify `mage check` (and other steps?) to report/fail locally for people who would like to check their integrations locally. 

++ I think you mean that when a human user runs `mage check` locally, it should use the `human` formatter and `stdout` output, right? We could default to these values and expose environment variables or something to override them, then we override them in the CI configuration. WDYT?

> There is also a bug because the `mage check` ends up without any "bad" exit code.

Hmmm, I wonder if this is similar to the problem we had in https://github.com/elastic/package-spec/issues/60 (fixed via https://github.com/elastic/package-spec/pull/62).

**Comment by mtojek** [comment]
> What command exactly did you run locally? mage check?

Yes

> That still looks like the xUnit formatter?

Sorry, I miscopied it. I meant the human format :)

> ++ I think you mean that when a human user runs mage check locally, it should use the human formatter and stdout output, right? We could default to these values and expose environment variables or something to override them, then we override them in the CI configuration. WDYT?

Good idea!

**Comment by mtojek** [comment]
@ycombinator here is the link to a failed CI job (fields): https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations/detail/PR-345/1/tests

**Comment by mtojek** [comment]
It looks rather like a bug in elastic-package:

```
➜  nginx git:(update-ep-1-type-assert) /Users/marcin.tojek/go/src/github.com/elastic/integrations/build/elastic-package test pipeline -v
2020/10/28 07:53:54 DEBUG Enable verbose logging
Run pipeline tests for the package
--- Test results for package: nginx - START ---
╭─────────┬────────────────────┬───────────┬────────────────────────┬─────────────────────────────────────────────────────────────────────────────┬──────────────╮
│ PACKAGE │ DATA STREAM        │ TEST TYPE │ TEST NAME              │ RESULT                                                                      │ TIME ELAPSED │
├─────────┼────────────────────┼───────────┼────────────────────────┼─────────────────────────────────────────────────────────────────────────────┼──────────────┤
│ nginx   │ access             │ pipeline  │ test-access-event.json │ FAIL: test case failed: one or more problems with fields found in documents │ 244.649677ms │
│ nginx   │ access             │ pipeline  │ test-access-raw.log    │ FAIL: test case failed: one or more problems with fields found in documents │ 129.313788ms │
│ nginx   │ error              │ pipeline  │ test-error-raw.log     │ FAIL: test case failed: one or more problems with fields found in documents │   9.832297ms │
│ nginx   │ ingress_controller │ pipeline  │ test-ingest-raw.log    │ FAIL: test case failed: one or more problems with fields found in documents │  29.730505ms │
╰─────────┴────────────────────┴───────────┴────────────────────────┴─────────────────────────────────────────────────────────────────────────────┴──────────────╯

FAILURE DETAILS:

nginx/access test-access-event.json:
[0] field "related.ip" is undefined
[1] field "source.address" is undefined
[2] field "source.ip" is undefined
[3] field "user_agent.os.full" is undefined
nginx/access test-access-raw.log:
[0] field "ecs.version" is undefined
[1] field "related.ip" is undefined
[2] field "source.address" is undefined
[3] field "source.as.number" is undefined
[4] field "source.as.organization.name" is undefined
[5] field "source.geo.country_name" is undefined
[6] field "source.ip" is undefined
[7] field "user_agent.os.full" is undefined
nginx/error test-error-raw.log:
[0] field "error.message" is undefined
[1] field "nginx.error.time" is undefined
nginx/ingress_controller test-ingest-raw.log:
[0] field "error.message" is undefined
[1] field "nginx.ingress_controller.time" is undefined
[2] field "source.address" is undefined
[3] parsing field value failed: field "nginx.ingress_controller.upstream.port" has invalid type, expected: long, actual Go type: string
--- Test results for package: nginx - END   ---
Done
➜  nginx git:(update-ep-1-type-assert) echo $?
0
```

**Comment by ycombinator** [comment]
> It looks rather like a bug in elastic-package:
> ...

Ah, good catch. Want to file a bug there and we can take it from there? Or if you want to just put up the bugfix PR directly, that's fine too.

**Comment by mtojek** [comment]
I will try to prepare a bugfix, shouldn't be complicated.

**Comment by mtojek** [comment]
Ok, I think I fixed the issue with test runners and the elastic-package, will adjust package content now.

**Review by ycombinator — APPROVED** [review]
LGTM. I like the ability to fail fast or not as well, depending on the `elastic-package` command being run. 👍

**Comment by mtojek** [comment]
> LGTM. I like the ability to fail fast or not as well, depending on the elastic-package command being run. 👍

Let me adjust necessary fields to make this PR green.

**Pull request merged**
