### PR TITLE
Fix JSON Typos on AWS API Gateway Documentation

### PR DESCRIPTION
**Pull request by max-ieremenko**
## Proposed commit message

Fix JSON typos on the documentation page [AWS API Gateway](https://github.com/elastic/integrations/blob/main/packages/aws/docs/apigateway.md)

## Related issues

- relates #9834

### CODE REVIEW

**Comment by max-ieremenko** [comment]
Hi, yes, the PR is still relevant.

**Review by gizas — APPROVED** [review]

**Review by andrewkroh — APPROVED** [review]
LGTM.

It needs a changelog entry and a patch version increment in order to be released.

**Comment by max-ieremenko** [comment]
Hello Elastic team,

I wonder if the normal process of correcting typos in documents takes months.
Or typos are there by design?

May 21 - September 22, ???

**Review by agithomas — APPROVED** [review]
LGTM!

**Comment by max-ieremenko** [comment]
> Hi! We just realized that we haven't looked into this PR in a while. We're sorry! We're labeling this issue as `Stale` to make it hit our filters and make sure we get back to it as soon as possible. In the meantime, it'd be extremely helpful if you could take a look at it as well and confirm its relevance. A simple comment with a nice emoji will be enough `:+1`. Thank you for your contribution!

> A simple comment with a nice emoji will be enough

👇 

>... we get back to it as soon as possible ...

The issue opened on May 21, today is Oct 25
 ~~as soon as possible~~ is redundant

> ... confirm its relevance ...

Yes, it is.

**Comment by efd6** [comment]
@max-ieremenko Please address the comment [here](https://github.com/elastic/integrations/pull/9932#pullrequestreview-2307949697).

**Comment by max-ieremenko** [comment]
thanks, @efd6 for the tip. The changelog entry and patch version are there.

**Comment by max-ieremenko** [comment]
Thx for the help, closed means closed. 

BR.

**Pull request closed without merging**
