### PR TITLE
[O11y][Nginx] Migrate `[Logs Nginx] Overview` dashboard visualizations to lens in kibana 8.5.0 

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate `[Logs Nginx] Overview` dashboard visualizations to lens for Nginx integration package

- Statistics for Nginx Lens migration:
<html>
<body>

Nginx Dashboards | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Logs Nginx] Overview | 0 | 8 | 7 | 1 (Markdown)
  | 0 | 8 | 7 | 1 (Markdown)
</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.5.0 itself.

## Related issues

- Relates #5221 

Note:
In the Response codes over time [Logs Nginx] we faced below two issues:

1. Lens doesn't have a gradient color palette. 
**Solution:** Set the color palette to status color palette because the values are defined by response status codes. 
2. We are unable to set http.response.status_code: [200 TO 299] filters due to number_format_exception.
**Solution:** To overcome this issue we have set the filter as http.response.status_code >= 200 and http.response.status_code<= 299.

### CODE REVIEW

**Review by milan-elastic — APPROVED** [review]

**Comment by milan-elastic** [comment]
Approved!

**Review by agithomas — COMMENTED** [review]
Please remove `[Logs Nginx]` phrase from the cangelog

**Comment by agithomas** [comment]
> > Please remove `[Logs Nginx]` phrase from the cangelog
> 
> @agithomas, I'll remove the `[Logs Nginx]` phrase but there are two overview dashboards in Nginx.
> 
> 1. [Logs Nginx] Overview
> 2. [Metrics Nginx] Overview
> 
> So, It would be good to keep `Logs Overview` and` Metrics Overview` in the description. What do you think?

Suggestions are just fine.

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
