### PR TITLE
iis: Add script processor to fix grok behaviour of ES 8.7.x+

### LINKED ISSUE #6016: MYSQL/IIS log file issue in Integrations
There have been some recent failures with IIS/MYSQL have gone unnoticed after 8.7.0. (Since CI/CD is broken). 
These issues came up in beats and same can be observed in Integrations as well. 

The issue is seen since ES has updated the grok processing(8.7.0 onwards) and it is generating different outputs (Expected json files). 

`Files now report duplicate values (list) in contrast to a string value before.
`

### For MYSQL:
 [Maria DB Log](https://github.com/elastic/beats/blob/ca13ce86cf08d3aae43789650819cac33632cf6e/filebeat/module/mysql/slowlog/test/mariadb-10.3.13.log)

**Issue**: {"root['mysql.slowlog.schema']": {'`old_type': <class 'str'>, 'new_type': <class 'list'>, 'old_value': 'employees-test', 'new_value': ['employees-test', 'employees-test']}}}`

[MYSQL Ubuntu Logs
](https://github.com/elastic/beats/blob/ca13ce86cf08d3aae43789650819cac33632cf6e/filebeat/module/mysql/slowlog/test/mysql-ubuntu-8.0.15.log)

**Issue**: {"root['mysql.thread_id']": {'`old_type': <class 'str'>, 'new_type': <class 'list'>, 'old_value': '16', 'new_value': [16, '16']`}}}

[Percona Ubuntu Logs
](https://github.com/elastic/beats/blob/ca13ce86cf08d3aae43789650819cac33632cf6e/filebeat/module/mysql/slowlog/test/percona-ubuntu-8.0.15.log)

**Issue**: {"root['mysql.slowlog.schema']": {`'old_type': <class 'str'>, 'new_type': <class 'list'>, 'old_value': 'employees', 'new_value': ['employees', 'employees'`]}}}

### For IIS:

[IIS Logs 7.5
](https://github.com/elastic/beats/blob/main/filebeat/module/iis/access/test/test-iis-7.5.log)

Issue:  {"root['destination.address']": `{'old_type': <class 'str'>, 'new_type': <class 'list'>, 'old_value': '10.100.220.70', 'new_value': ['10.100.220.70', '10.100.220.70']}
`

The issue has been fixed in beats. 
But since integrations don't follow a release cycle, we need to figure out a way to fix this in integrations. 

1. Are changes required in the pipeline?
2. Does ES need to backport the change?
3. Do we need to update the Kibana version of the integrations?

The issue raised in beats: https://github.com/elastic/beats/issues/35133

### PR DESCRIPTION
**Pull request by shmsr**
- Bug

## What does this PR do?

Changes deduplicate the list and only keep the unique elements. After this, if only 1 element remains, then it's added to the result as a single element (a string) and if not, the list is kept in the result with unique elements. This handling is done to manage the new behaviour of the grok processor in 8.7.x+. Read the related issue for more details.

Also, see: https://github.com/elastic/integrations/pull/6531

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #6016

### CODE REVIEW

**Comment by shmsr** [comment]
Other unrelated changes to grok are because they were failing even with the ES version lower than 8.7. I read the file and removing them did make sense. But I'd like someone to take another look.

**Comment by shmsr** [comment]
https://github.com/elastic/integrations/pull/6531#issuecomment-1596790040

cc: @HiDAl

**Comment by lalit-satapathy** [comment]
@shmsr,

What needs to be done here. I see this integration [PR](https://github.com/elastic/integrations/pull/6531) already merged. Also CI showing red.

**Comment by shmsr** [comment]
> @shmsr,
> 
> What needs to be done here. I see this integration [PR](https://github.com/elastic/integrations/pull/6531) already merged. Also CI showing red.

It just needs approval. The same fix is applied for mysql integration and @ishleenk17 and I decided let's have the fix merged for mysql first and monitor and if things are fine then also merge this. 

CI failure is transient from what I saw in the logs.

**Review by ishleenk17 — APPROVED** [review]
Looks good!

**Pull request merged**
