### PR TITLE
Elastic Agent: ensure syslog processor is not used with 7.17.X agents

### PR DESCRIPTION
**Pull request by pierrehilbert**
## Proposed commit message

Elastic Agent: ensure syslog processor is not used with 7.17.X agents by adding a condition.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

Tests:
- [x] 7.17.22 agent is now healthy
- [x] 8.15.0 agent is still healthy 
- [x] 7.17.22 agent is stuck in `configuring` if I reverse the condition check 

## Related issues

- Closes https://github.com/elastic/integrations/issues/10457

### CODE REVIEW

**Review by jlind23 — APPROVED** [review]

**Comment by jlind23** [comment]
@norrietaylor @lalit-satapathy @andrewkroh can we please get people from your time to review this?

**Review by andrewkroh — APPROVED** [review]
Do we expect all packages to work on Elastic Agent 7.17 even when their manifest says they require Kibana 8.x? Or is this a special case because it's the system package?

Are there CI tests for this package against 7.x?

**Comment by jlind23** [comment]
> Do we expect all packages to work on Elastic Agent 7.17 even when their manifest says they require Kibana 8.x? Or is this a special case because it's the system package?

As we never introduced any Agent version constraints in the package manifest then users would expect them to work. If you first upgrade your stack to 8.X and then upgrade all integrations before upgrading Agents you wouldn't expect them to be broken.

> Are there CI tests for this package against 7.x?

I do not think so.

**Comment by ishleenk17** [comment]
Is this a valid scenario to expect an integration with ^8.x to work on 7.x agent?
This type of compatibility issue is likely common in many integrations where a feature has been introduced in version 8.x but is not supported in agent version 7.x.

**Comment by jlind23** [comment]
@ishleenk17 That what would you recommend? It also means that 7.X users won't get fixes anymore or this will break their integrations?

**Comment by ishleenk17** [comment]
Approving this for now as it's a conditional check. 

> @ishleenk17 That what would you recommend? It also means that 7.X users won't get fixes anymore or this will break their integrations?

In general, the recommendation would be to not have a mix of versions in the stack. There can be other uncovered incompatibilities as well.

For fixing an integration in older stack version, this [approach](https://www.elastic.co/guide/en/integrations-developer/current/developer-workflow-support-old-package.html) can be followed.

**Review by ishleenk17 — APPROVED** [review]

**Comment by jlind23** [comment]
> In general, the recommendation would be to not have a mix of versions in the stack. There can be other uncovered incompatibilities as well.

I do agree but this is definitely not what users are doing and this can be easily proved by our telemetry.

**Pull request merged**
