### PR TITLE
[O11y][Azure Metrics] Migrate Table Storage Overview dashboard to lens

### PR DESCRIPTION
**Pull request by kush-elastic**
### Urgency
- High

### Activity Type
- Enhancement

## What does this PR do?
- Manually migrate `Azure Table Storage` visualizations to the lens in the current Kibana version `8.9.0` itself. 

- Statistics for `Azure Table Storage` Lens migration:
## Migration stats
  | Before Migration |   |   | After Migration |   |  
-- | -- | -- | -- | -- | -- | --
  | Lens | Visualization | Old Input Controls | Lens | Visualization | New control panels
[Azure Metrics] Table Storage Overview | 0 | 9 | 1 | 9 | 0 | 1

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to the lens.
- [x] I have updated screenshots of the dashboard.
- [X] I have verified that the data counts are matching and panel aggregations are the same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.4.0 itself.

## Related issues

- Relates #7434 

Before Migration
image

After Migration
image

### CODE REVIEW

**Comment by rajvi-elastic** [comment]
LGTM!

**Review by rajvi-elastic — APPROVED** [review]
LGTM!

**Review by zmoog — APPROVED** [review]
~~LGTM.~~

UPDATE: Revisiting the review to clarify the table and entity count values and format.

**Review by zmoog — CHANGES_REQUESTED** [review]
The table and entities count values have decimals:

CleanShot 2023-09-08 at 12 48 30@2x

Shouldn't these be integer values?

**Comment by kush-elastic** [comment]
@zmoog ,
Both the visualizations were already using Average aggregation before migration, we will need to create new tickets to address this issue. As part of this PR scope, our focus will be only on migration.

Screenshot 2023-09-08 at 4 44 01 PM

Screenshot 2023-09-08 at 4 45 02 PM

**Comment by kush-elastic** [comment]
@zmoog,
As discussed [here](https://github.com/elastic/integrations/pull/7662/#issuecomment-1715503247) I think we can unblock this PR as well.

**Review by zmoog — APPROVED** [review]
As discussed at https://github.com/elastic/integrations/pull/7662#issuecomment-1715672085, @kush-elastic will open a dedicated issue to address the decimals in the count.

**Pull request merged**
