### PR TITLE
[O11y][Redis] Migrate `Metrics Overview` dashboard visualizations to lens in kibana 8.3.0

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

- Migrate visualizations to lens for Redis integration package

- Statistics for **Redis** Lens migration:

<html>
<body>
<google-sheets-html-origin>

Redis dashboard | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics Redis] Overview | 0 | 7 | 7 | 0

</body>
</html>

## Checklist

- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that panels are populated with data.
- [x] I have verified that panels are not distorted after being migrated to lens.
- [x] I have updated screenshots of dashboard.
- [x] I have verified that data count are matching and panel aggregations are same as before.

## Author's checklist

- [x] Migrated panels should be removed from visualization folder.
- [x] Migrated visualizations are populating in Kibana version 8.3.0. 

## Related issues

- Relates #5221 

## Issues Identified
- Need to update label position in `Keyspaces [Metrics Redis]` visualization
  https://github.com/elastic/integrations/issues/5671

**Note** : - There is no screenshot previously present for `Metrics Overview` dashboard. Hence we have updated the screenshot and also updated entry in `manifest.yml` file. Please refer before migration for compare and review.
 
image

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM

**Comment by agithomas** [comment]
Please note the labels in the panel is getting truncated right after the second character. 

It may be best to either put the labels either at the bottom or have two panels per row. 

image

**Review by agithomas — COMMENTED** [review]
Please remove the phrase 'Metrics' from the string `Metrics Overview` in the changelog.

**Comment by harnish-elastic** [comment]
> Please note the labels in the panel is getting truncated right after the second character.
> 
> It may be best to either put the labels either at the bottom or have two panels per row.
> 
> image

We have kept the same behavior with the previous visualization. We totally agreed on your point and we have created separate [issue](https://github.com/elastic/integrations/issues/5671) for that as well. Once all `redis migration PRs` are approved and merged we will work on that issue.

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
