### PR TITLE
Adjust aws package to use input groups

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
## What does this PR do?

This PR is to modify current `aws` package to use input groups in order to add icons for each service to support granular search.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.

## Related issues

- Relates https://github.com/elastic/package-spec/issues/122

## Screenshots

Screen Shot 2021-05-27 at 11 47 12 AM

### CODE REVIEW

**Comment by sorantis** [comment]
In its current state the `manifest.yml` is missing the `categories` section both package wide and service specific. Are we planning to add these?

**Comment by kaiyan-sheng** [comment]
Update: waiting on https://github.com/elastic/elastic-package/pull/282 before working on this PR again

**Comment by mtojek** [comment]
@kaiyan-sheng I assume we can't merge this package yet, as other parties don't support it yet? I mean Kibana and Package Registry. I'm not sure what would be implications of merging it now :)

**Comment by kaiyan-sheng** [comment]
> @kaiyan-sheng I assume we can't merge this package yet, as other parties don't support it yet? I mean Kibana and Package Registry. I'm not sure what would be implications of merging it now :)

@mtojek Yeah I just tested the AWS integration with this PR and I definitely need to work on package registry first before this PR can get merged.

**Comment by mtojek** [comment]
Maybe mark this PR as draft to prevent from accidental merge :)

**Comment by kaiyan-sheng** [comment]
@mtojek Done, back in draft mode! Thanks!

**Comment by sorantis** [comment]
The Meta https://github.com/elastic/package-spec/issues/144 indicates that package registry changes have dependency on AWS package. Is it the other way around? Also, what should be done to unblock [changes in Kibana](https://github.com/elastic/kibana/issues/93315#issuecomment-793095903)?

**Comment by kaiyan-sheng** [comment]
@sorantis I'm currently working on changes in package-registry https://github.com/elastic/package-registry/pull/685 to unblock Kibana work. I also pointed this draft PR to @jen-huang and hopefully combining both draft PRs together will help.

**Comment by jen-huang** [comment]
Hi all, I'm starting to assess Kibana work using the in-flight changes to AWS package in this PR along with the package registry changes. I have a question regarding the new package-level `vars` field introduced here:
https://github.com/elastic/integrations/blob/e00cbd7ecfcfd9c6229697fc3dbd4f75222cdd0e/packages/aws/manifest.yml#L26-L27

I know we introduced support for package-level `vars` a little while ago in the [package spec PR](https://github.com/mtojek/package-spec/blob/1d17ee39856b3a7becd640d756f150d259d56754/test/packages/input_groups/manifest.yml#L26), but AFAIK supporting this on the Kibana side was not scoped for phase 1, so I was wondering if we can pull out that change from this PR and put those `vars` back at the (I think) input level?

@sorantis What do you think? If Kibana should support package-level vars as part of phase 1, can you provide some guidance on how they fit into the existing policy editor UI?

**Comment by kaiyan-sheng** [comment]
@jen-huang My understanding is, for package-level vars, I would expect to see them under current `Integration settings`. So basically moving `Credential Profile Name` and `Advanced options` from under `Settings` per logs/metrics up a level.
Screen Shot 2021-03-31 at 4 18 58 PM

**Comment by jen-huang** [comment]
Thanks @kaiyan-sheng, I think that makes sense. I've added supporting package-level vars to the Kibana scope for phase 1: https://github.com/elastic/kibana/issues/93315

**Comment by jen-huang** [comment]
Hi @kaiyan-sheng, please add `input_groups` as part of these changes too. Without this field, Kibana won't know what to display in the UI. For more context: https://github.com/elastic/package-registry/pull/685#issuecomment-814323270

**Comment by jen-huang** [comment]
Also, things are looking really promising on the Kibana side, but I'm not able to do a full test due to an error with installing the package. It seems that Kibana assets in `package-storage` are encoded to match Kibana saved object schema:

https://github.com/elastic/package-storage/blob/snapshot/packages/aws/0.5.1/kibana/map/aws-0edf0640-3e7e-11ea-bb0a-69c3ca1d410f.json#L31

image

but assets that are still in `integrations` (including from this PR branch) are not:

https://github.com/elastic/integrations/blob/master/packages/aws/kibana/map/aws-0edf0640-3e7e-11ea-bb0a-69c3ca1d410f.json#L31

image

I'm not sure where/when this processing occurs or how to manually apply it to this PR branch. If anyone has any suggestions, I'd appreciate it!

**Comment by ycombinator** [comment]
@jen-huang I just responded to your question about encoding off-PR but paraphrasing it here for everyone's benefit:

Indeed, there's a difference between "source" packages (the kind that are stored in the `integrations` repo) and "built" packages (the kind that are served by the package registry and, therefore, stored in the `package-storage` repo). Source packages get converted to built packages by running [`elastic-package build`](https://github.com/elastic/elastic-package#elastic-package-build) on them. As part of this conversion a few different things are done to the source package, including [encoding assets](https://github.com/elastic/elastic-package/blob/f171846c52f3301e35d8b771bd8aaaaeb889f57d/internal/builder/packages.go#L112-L113).

**Comment by kaiyan-sheng** [comment]
> Hi @kaiyan-sheng, please add `input_groups` as part of these changes too. Without this field, Kibana won't know what to display in the UI. For more context: [elastic/package-registry#685 (comment)](https://github.com/elastic/package-registry/pull/685#issuecomment-814323270)

@jen-huang Done, please let me know if it works for you! Thank you!!

**Comment by mtojek** [comment]
@kaiyan-sheng Do input groups need a newer stack (7.14.0-SNAPSHOT)? If so, we need to bump it out in elastic-package. It's not a problem at all, but just asking in advance ;)

**Comment by kaiyan-sheng** [comment]
> @kaiyan-sheng Do input groups need a newer stack (7.14.0-SNAPSHOT)? If so, we need to bump it out in elastic-package. It's not a problem at all, but just asking in advance ;)

Thanks for pointing this out @mtojek ! Yes we do need to limit the stack version. I'm thinking to change the `kibana.version` in manifest.yml to be `^7.14.0`. What do you mean by bumping it in elastic-pacakge?

**Comment by jen-huang** [comment]
FYI https://github.com/elastic/kibana/pull/99866 is just the first part of the Kibana work, there is a second part to come :)

**Review by ChrsMark — COMMENTED** [review]
lgtm, however conflicts should be resolved

**Review by ChrsMark — APPROVED** [review]
:shipit:

**Pull request merged**
