### PR TITLE
[AWS] Migrate RDS metrics dashboard visualizations to lenses

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?

Migrates visualizations to lenses and adds input control groups.

Before:
rds_before

After:
rds_after

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by drewdaemon — COMMENTED** [review]
Let's change those two legacy metrics to Lens metrics and arrange them horizontally instead of vertically.

**Comment by gpop63** [comment]
Fixed:

aws_rds_metric

**Comment by drewdaemon** [comment]
Thanks @gpop63 ! 

Sorry for the whiplash, but I think that in this case maybe the legacy metric makes more sense. 

I still like the horizontal configuration of the panels, but we're dealing with so much space that the number is very far away from the label which isn't really how the new metric is supposed to be.

**Review by drewdaemon — APPROVED** [review]
Approving so as not to hold you up

**Review by zmoog — APPROVED** [review]

**Pull request merged**
