### PR TITLE
[microsoft_sqlserver,system] Add ECS error.code mapping

### PR DESCRIPTION
**Pull request by ishleenk17**
- Bug

## What does this PR do?
This PR fixes the type conflicts for error.message and error.code for datastreams in system and mssql package

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes https://github.com/elastic/integrations/issues/6766

### CODE REVIEW

**Review by andrewkroh — APPROVED** [review]

**Comment by muthu-mps** [comment]
@ishleenk17 - What happens to the existing user who faces the field conflicts ?

**Comment by ishleenk17** [comment]
> @ishleenk17 - What happens to the existing user who faces the field conflicts ?

They will have to upgrade to this version if they think it's a deal breaker for them.

**Comment by muthu-mps** [comment]
> > @ishleenk17 - What happens to the existing user who faces the field conflicts ?
> 
> They will have to upgrade to this version if they think it's a deal breaker for them.

Does it requires removing the conflicting field and re-indexing the existing data ? Are we considering this as a breaking change ? Otherwise the changes looks good !

**Comment by ishleenk17** [comment]
> > > @ishleenk17 - What happens to the existing user who faces the field conflicts ?
> > 
> > 
> > They will have to upgrade to this version if they think it's a deal breaker for them.
> 
> Does it requires removing the conflicting field and re-indexing the existing data ? Are we considering this as a breaking change ? Otherwise the changes looks good !

Yes, I think this would be categorized as a breaking change since it's going to be a mapping change. 
@andrewkroh: How do we handle such a scenario?
do we document them?

**Comment by ishleenk17** [comment]
> I would categorize this as a bug. ECS was not adhered here and the default ES dynamic mappings prevailed.
> 
> When the new package version is installed Fleet will `_rollover` the backing data stream index so that the new mappings are applied. From a data indexing point of view there should be no issues.

Thanks for the clarity @andrewkroh

**Comment by muthu-mps** [comment]
@andrewkroh - I am trying to understand what happens when we try to search or perform aggregations against the data after the new change.

Will the type conflict still exists ?

### Observations :

- Applied an aggregation query against the datastream which has a type of long in older indices and with type of keyword in newer indices after _rollover.
- Getting two different type for same field error.

Screenshot 2023-07-12 at 10 09 05 AM

#### Correct me if am wrong,

  - This happens because we are searching for the data from older indices which has a different field type.
  -  This can be avoided either by searching for the data from the newer index only or by re-indexing the older index with newer mapping.

**Comment by andrewkroh** [comment]
That is correct. Any functions that require knowing the type can have issues. Queries without aggs (like Discover) should work. The options for resolution are [reindexing](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html), [deleting](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-index.html), [closing](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-close.html), or adding a [runtime field](https://www.elastic.co/guide/en/elasticsearch/reference/8.8/runtime.html) in the old indices to shadow the field with the correct type.

**Comment by ishleenk17** [comment]
If we go by this [document](https://github.com/elastic/dev/issues/2036), I think we should consider this as a bug fix and not a breaking change. 
There are lesser chances that the error.code field will be used in aggregation queries.

**Review by muthu-mps — APPROVED** [review]

**Pull request merged**
