### PR TITLE
Box Consolidate Shield Events (#4464) Rebased 

### PR DESCRIPTION
**Pull request by djptek**
This is a PR based on a rebase of #4464 squashing commits from previous PR #3677 

## Additional Tasks Post rebase

- [x] Rectify all unresolved merge conflicts post-squash
- [x] Check `elastic-package test` results for regressions
- [x] Sync to main
- [x] Rectify all unresolved merge conflicts post-sync
- [x] Check `elastic-package test` results for regressions
- [x] Apply fix from #4552
- [x] Check Integration still connects to live target
- [x] Check screenshots for Events live data for regressions
- [x] Check screenshots for Shield simulated data for regressions

The Description of #4464 is copied verbatim below:

## What does this PR do?

Release 0.2.0 Beta of Box Integration
- Restores and Corrects System Tests
- Improves documentation around Authorisation vs Target Box Service
- Consolidates Shield data streams into the Events data stream to avoid redundant API calls and reduce bandwidth consumption

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [x] Restore and Correct System Tests
- [x] Improve documentation around Authorisation vs Target Box Service, see screenshots below
- [x] Consolidate Shield data streams into the Events data stream
- [x] Add `related.*` fields to facilitate `aggs` on doubly-nested fields
- [x] Rebuild Box Shield events dashboard, see screenshots below
- [x] Check for regressions vs reviewer comments for https://github.com/elastic/integrations/pull/3677
  - [x] `event.kind` is ECS compatible
  - [x] date processors applied: Box Shield events are mapped to `shield_date` and the processor applied to this field
  - [x] module set to `box_events`
  - [x] check dashboards for regression after module change
  - [x] adjust the integration description to: `Collect logs from Box with Elastic Agent`
  - [x] check for rogue `.swp` files
  - [x] check ecs v 8.4
  - [x] add Box Shield events origin story
  - [x] check anomalous download `event.type[]` includes `access`
  - [x] check anomalous download `event.category[]` includes `file`
  - [x] check suspicious locations `event.type[]` includes `indicator`
  - [x] check suspicious sessions `event.type[]` includes `indicator`
  - [x] check `event.ingested` not in `test-common-config.yml`
  - [x] add AS lookups to Box Shield events: contingent on IP, see [`test-malicious-content.log-expected.json`](https://raw.githubusercontent.com/djptek/integrations/box_consolidate_shield_events/packages/box_events/data_stream/events/_dev/test/pipeline/test-malicious-content.log-expected.json) for example
  - [x] use a params map to map between the `box.event_type` and the ECS `event.type` and `event.category`
  - [x] ensure `event.kind` and `event.category` are arrays for all events
  - [x] ensure pipeline ECS version is `8.4`
 
## How to test this PR locally

Build the integration and start the elastic Stack with latest Box integration

`elastic-package build -v ; elastic-package stack up -v -d --version 7.17.0`

Load stack environment variables 

`eval "$(elastic-package stack shellinit)"`

Run the test suite

`elastic-package test`

Expected Results

```
Run test suite for the package
Run system tests for the package
2022/10/27 14:44:36  INFO Write container logs to file: /Users/djptek/github/integrations/build/container-logs/box-http-1666874676405788000.log
--- Test results for package: box_events - START ---
╭────────────┬─────────────┬───────────┬───────────┬────────┬───────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME │ RESULT │  TIME ELAPSED │
├────────────┼─────────────┼───────────┼───────────┼────────┼───────────────┤
│ box_events │ events      │ system    │ httpjson  │ PASS   │ 29.704100098s │
╰────────────┴─────────────┴───────────┴───────────┴────────┴───────────────╯
--- Test results for package: box_events - END   ---
Done
Run asset tests for the package
--- Test results for package: box_events - START ---
╭────────────┬─────────────┬───────────┬─────────────────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME                                                           │ RESULT │ TIME ELAPSED │
├────────────┼─────────────┼───────────┼─────────────────────────────────────────────────────────────────────┼────────┼──────────────┤
│ box_events │             │ asset     │ dashboard box_events-ce6fbf50-2df9-11ed-8003-6d5721603181 is loaded │ PASS   │        659ns │
│ box_events │             │ asset     │ dashboard box_events-ff3d9940-2e03-11ed-8003-6d5721603181 is loaded │ PASS   │        107ns │
│ box_events │ events      │ asset     │ index_template logs-box_events.events is loaded                     │ PASS   │        121ns │
│ box_events │ events      │ asset     │ ingest_pipeline logs-box_events.events-0.2.0 is loaded              │ PASS   │        117ns │
╰────────────┴─────────────┴───────────┴─────────────────────────────────────────────────────────────────────┴────────┴──────────────╯
--- Test results for package: box_events - END   ---
Done
Run pipeline tests for the package
--- Test results for package: box_events - START ---
╭────────────┬─────────────┬───────────┬───────────────────────────────┬────────┬──────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME                     │ RESULT │ TIME ELAPSED │
├────────────┼─────────────┼───────────┼───────────────────────────────┼────────┼──────────────┤
│ box_events │ events      │ pipeline  │ test-anomalous-download.log   │ PASS   │    3.98345ms │
│ box_events │ events      │ pipeline  │ test-copy.log                 │ PASS   │   4.798673ms │
│ box_events │ events      │ pipeline  │ test-create.log               │ PASS   │   5.535755ms │
│ box_events │ events      │ pipeline  │ test-download.log             │ PASS   │   4.408652ms │
│ box_events │ events      │ pipeline  │ test-event-types.log          │ PASS   │  42.536447ms │
│ box_events │ events      │ pipeline  │ test-malicious-content.log    │ PASS   │   5.064869ms │
│ box_events │ events      │ pipeline  │ test-preview.log              │ PASS   │   4.322739ms │
│ box_events │ events      │ pipeline  │ test-rename.log               │ PASS   │    4.52733ms │
│ box_events │ events      │ pipeline  │ test-suspicious-locations.log │ PASS   │   5.047095ms │
│ box_events │ events      │ pipeline  │ test-suspicious-sessions.log  │ PASS   │   3.980184ms │
│ box_events │ events      │ pipeline  │ test-trash.log                │ PASS   │   3.895217ms │
│ box_events │ events      │ pipeline  │ test-upload.log               │ PASS   │   4.962918ms │
╰────────────┴─────────────┴───────────┴───────────────────────────────┴────────┴──────────────╯
--- Test results for package: box_events - END   ---
Done
Run static tests for the package
--- Test results for package: box_events - START ---
╭────────────┬─────────────┬───────────┬──────────────────────────┬────────┬──────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME                │ RESULT │ TIME ELAPSED │
├────────────┼─────────────┼───────────┼──────────────────────────┼────────┼──────────────┤
│ box_events │ events      │ static    │ Verify sample_event.json │ PASS   │  50.203768ms │
╰────────────┴─────────────┴───────────┴──────────────────────────┴────────┴──────────────╯
--- Test results for package: box_events - END   ---
Done
```

Verify that all tests are passing

Note: The simulated shield events were created by extracting the events from the [Box Shield Alerts documentation](https://developer.box.com/guides/events/event-triggers/shield-alert-events/) and publishing these via a web proxy. They were then ingested using Filebeat and the resultant data routed to a temporary Elastic Stack. The resultant JSON was then merged with events generated by the ingest from the event data stream, to append the Elastic Agent related properties.

## Screenshots

Updated Integration Package Documentation 
Screenshot 2022-10-26 at 11 15 24
Screenshot 2022-10-26 at 11 09 40

Screenshot 2022-10-26 at 11 10 53
Screenshot 2022-10-26 at 11 12 16
Screenshot 2022-10-26 at 11 12 56

Updated Dashboard [Logs Box Events Integration] Events

box_screenshot

Updated Dashboard [Logs Box Events Integration] Box Shield Alerts

box_screenshot_shield_alerts
box_screenshot_shield_alerts_anomalous_downloads
box_screenshot_shield_alerts_malware
box_screenshot_shield_alerts_suspicious_locations
box_screenshot_shield_alerts_suspicious_sessions

### CODE REVIEW

**Comment by djptek** [comment]
Re-run tests:

```
% elastic-package test pipeline -v                                               (box_consolidate_shield_events_rebased)integrations
2022/11/04 15:12:46 DEBUG Enable verbose logging
2022/11/04 15:12:46 DEBUG Distribution built without a version tag, can't determine release chronology. Please consider using official releases at https://github.com/elastic/elastic-package/releases
Run pipeline tests for the package
--- Test results for package: box_events - START ---
╭────────────┬─────────────┬───────────┬───────────────────────────────┬────────┬──────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME                     │ RESULT │ TIME ELAPSED │
├────────────┼─────────────┼───────────┼───────────────────────────────┼────────┼──────────────┤
│ box_events │ events      │ pipeline  │ test-anomalous-download.log   │ PASS   │   3.128624ms │
│ box_events │ events      │ pipeline  │ test-copy.log                 │ PASS   │   3.070003ms │
│ box_events │ events      │ pipeline  │ test-create.log               │ PASS   │   3.021994ms │
│ box_events │ events      │ pipeline  │ test-download.log             │ PASS   │   3.077335ms │
│ box_events │ events      │ pipeline  │ test-event-types.log          │ PASS   │  33.927692ms │
│ box_events │ events      │ pipeline  │ test-malicious-content.log    │ PASS   │   4.991846ms │
│ box_events │ events      │ pipeline  │ test-preview.log              │ PASS   │   3.229628ms │
│ box_events │ events      │ pipeline  │ test-rename.log               │ PASS   │   3.152263ms │
│ box_events │ events      │ pipeline  │ test-suspicious-locations.log │ PASS   │   3.627952ms │
│ box_events │ events      │ pipeline  │ test-suspicious-sessions.log  │ PASS   │    3.11417ms │
│ box_events │ events      │ pipeline  │ test-trash.log                │ PASS   │   4.850903ms │
│ box_events │ events      │ pipeline  │ test-upload.log               │ PASS   │   3.863745ms │
╰────────────┴─────────────┴───────────┴───────────────────────────────┴────────┴──────────────╯
--- Test results for package: box_events - END   ---
Done
djptek@Dominics-MacBook-Pro box_events % elastic-package test                                                           (box_consolidate_shield_events_rebased)integrations
Run test suite for the package
Run asset tests for the package
--- Test results for package: box_events - START ---
╭────────────┬─────────────┬───────────┬─────────────────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME                                                           │ RESULT │ TIME ELAPSED │
├────────────┼─────────────┼───────────┼─────────────────────────────────────────────────────────────────────┼────────┼──────────────┤
│ box_events │             │ asset     │ dashboard box_events-ce6fbf50-2df9-11ed-8003-6d5721603181 is loaded │ PASS   │      3.912µs │
│ box_events │             │ asset     │ dashboard box_events-ff3d9940-2e03-11ed-8003-6d5721603181 is loaded │ PASS   │        128ns │
│ box_events │ events      │ asset     │ index_template logs-box_events.events is loaded                     │ PASS   │        159ns │
│ box_events │ events      │ asset     │ ingest_pipeline logs-box_events.events-0.2.0 is loaded              │ PASS   │        129ns │
╰────────────┴─────────────┴───────────┴─────────────────────────────────────────────────────────────────────┴────────┴──────────────╯
--- Test results for package: box_events - END   ---
Done
Run pipeline tests for the package
--- Test results for package: box_events - START ---
╭────────────┬─────────────┬───────────┬───────────────────────────────┬────────┬──────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME                     │ RESULT │ TIME ELAPSED │
├────────────┼─────────────┼───────────┼───────────────────────────────┼────────┼──────────────┤
│ box_events │ events      │ pipeline  │ test-anomalous-download.log   │ PASS   │   2.879639ms │
│ box_events │ events      │ pipeline  │ test-copy.log                 │ PASS   │   3.108485ms │
│ box_events │ events      │ pipeline  │ test-create.log               │ PASS   │   3.726011ms │
│ box_events │ events      │ pipeline  │ test-download.log             │ PASS   │   3.374954ms │
│ box_events │ events      │ pipeline  │ test-event-types.log          │ PASS   │  36.392981ms │
│ box_events │ events      │ pipeline  │ test-malicious-content.log    │ PASS   │   3.334071ms │
│ box_events │ events      │ pipeline  │ test-preview.log              │ PASS   │    3.72101ms │
│ box_events │ events      │ pipeline  │ test-rename.log               │ PASS   │   3.146481ms │
│ box_events │ events      │ pipeline  │ test-suspicious-locations.log │ PASS   │   3.283858ms │
│ box_events │ events      │ pipeline  │ test-suspicious-sessions.log  │ PASS   │    4.59337ms │
│ box_events │ events      │ pipeline  │ test-trash.log                │ PASS   │   2.999598ms │
│ box_events │ events      │ pipeline  │ test-upload.log               │ PASS   │    3.84989ms │
╰────────────┴─────────────┴───────────┴───────────────────────────────┴────────┴──────────────╯
--- Test results for package: box_events - END   ---
Done
Run static tests for the package
--- Test results for package: box_events - START ---
╭────────────┬─────────────┬───────────┬──────────────────────────┬────────┬──────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME                │ RESULT │ TIME ELAPSED │
├────────────┼─────────────┼───────────┼──────────────────────────┼────────┼──────────────┤
│ box_events │ events      │ static    │ Verify sample_event.json │ PASS   │   42.60185ms │
╰────────────┴─────────────┴───────────┴──────────────────────────┴────────┴──────────────╯
--- Test results for package: box_events - END   ---
Done
Run system tests for the package
2022/11/04 15:13:42  INFO Write container logs to file: /Users/djptek/github/integrations/build/container-logs/box-http-1667574822847359000.log
--- Test results for package: box_events - START ---
╭────────────┬─────────────┬───────────┬───────────┬────────┬──────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME │ RESULT │ TIME ELAPSED │
├────────────┼─────────────┼───────────┼───────────┼────────┼──────────────┤
│ box_events │ events      │ system    │ httpjson  │ PASS   │ 25.22240368s │
╰────────────┴─────────────┴───────────┴───────────┴────────┴──────────────╯
--- Test results for package: box_events - END   ---
Done

```

**Comment by djptek** [comment]
Check screenshots still match up with live (events) and simulated (shield) data:

image

image

image

image

**Review by efd6 — COMMENTED** [review]
There are still many commit that pre-date the changes required here. For example the [original commit](https://github.com/elastic/integrations/pull/4562/commits/655ee8e6a86f50bb7350c617202b870a474e2800) for the addition to the package is in this set of changes, but we shouldn't see except the changes that are required here.

I'm concerned about the go.mod changes. I don't understand why they are necessary and they really should be their own PR if they are.

Since the original PR has been abandoned I would be inclined to just squash this change here (minus the go.{mod,sum} changes into one commit (or a small number of conceptually related commits if there should be a story to the changes) and make a new PR (solely to remove the confusion in the testing for other packages that has been done here because the go.mod has been changed). Another alternative would be to reopen the old PR for this change and just live with the noise there, though it looks like that will no longer merge without conflict.

**Comment by djptek** [comment]
I'll do this as well:

>>just squash this change here (minus the go.{mod,sum} changes into one commit

**Comment by djptek** [comment]
Hi Dan, all done, see: https://github.com/elastic/integrations/pull/4578

**Pull request closed without merging**
