### PR TITLE
In the nginx ingress_controller datastream the source.address is never set

### PR DESCRIPTION
**Pull request by renekalff**
## What does this PR do?

Fixes a field naming error in the conditional for executing a script block which is supposed to set the source.address field.

Interestingly the pipeline did work in the past and we suspect that a change in Elasticsearch 7.10 is now resulting in different behavior though we we're able to exactly match the time of our cluster upgrade to the loss of the source.address information.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [ ] I have verified that all datasets collect metrics or logs.

## Author's Checklist

- [ ] Processing of events from K8S nginx controller using the Fleet NginX integration
- [ ] The source address geo ip information should be set

## How to test this PR locally

Deploy the pipeline and send a test event using the simulate api. The following event was used for testing the change:

```json
{
  "docs": [
    {
      "_index": ".ds-logs-nginx.ingress_controller-default-000001",
      "_id": "id",
      "_source": {
        "@timestamp": "2020-11-19T22:00:00.000Z",
        "message": "11..22.33.44 - test_ingress [25/Nov/2020:12:55:47 +0000] \"POST /test-*/_search?scroll=30s HTTP/1.1\" 200 300 \"-\" \"elasticsearch-js/7.10.0 (linux 4.19.112+-x64; Node.js v14.15.1)\" 610 0.005 [es-http-9200] [] 10.8.3.105:9200 300 0.004 200 83fbb9732a44e678f3f30a0647854661"
      }
    }
  ]
}
```

### CODE REVIEW

**Review by ChrsMark — APPROVED** [review]
lgtm. It looks like the migration missed that from https://github.com/elastic/beats/blob/113703276df1471ac05cf6ab487d01a40a0ce92f/filebeat/module/nginx/ingress_controller/ingest/pipeline.yml#L64

cc: @ruflin @mtojek

**Review by ChrsMark — COMMENTED** [review]
Thanks for catching this @renekalff! You will need to sign the CLA and also the version of the package needs to be updated at https://github.com/elastic/integrations/blob/9e4efb410dc4495a4805b69afc1bcbb79d9d8829/packages/nginx/manifest.yml#L4 since it is a bugfix.

**Review by mtojek — CHANGES_REQUESTED** [review]
@renekalff Could you please sign the CLA, so we can merge your changes?

Let's also test them.

**Comment by mtojek** [comment]
jenkins run the tests please

**Comment by renekalff** [comment]
> @renekalff Could you please sign the CLA, so we can merge your changes? We can test them then using the CI.

Sure, I did sign the CLA **after** making the PR. Should it automagically recognize that I signed the CLA or do I need to make a change in the PR in order for it to check again?

**Comment by mtojek** [comment]
> Sure, I did sign the CLA after making the PR. Should it automagically recognize that I signed the CLA or do I need to make a change in the PR in order for it to check again?

Hm.. it looks like the system didn't accept. Could you retry the signing procedure?

**Comment by mtojek** [comment]
It seems that you need to adjust `ingress_controller` tests: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-419/3/tests . 

You can use the [elastic-package](https://github.com/elastic/elastic-package) for that, which is the official builder tool. Here is a sample guide to run pipeline tests: https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md#running-a-pipeline-test

To regenerate expected results: `elastic-package test pipeline -v -g`

**Comment by renekalff** [comment]
What a great way to test the datastreams. Turned out more had to be done. GeoIP wasn't tested and some fields where missing in ECS.

**Review by ChrsMark — APPROVED** [review]
lgtm! Glad to see that `elastic-package` was handy for you.

@mtojek I don't think we miss anything else for this one.

**Review by mtojek — APPROVED** [review]
Thank you for your contribution! I'm glad the tool worked for you :) Feel free to ship it!

**Pull request merged**
