### PR TITLE
[Postgresql] [Bugfix] create new field query_id field to replace query field as dimension field

### PR DESCRIPTION
**Pull request by agithomas**
- Bug

## Proposed commit message

WHAT: The change helps to prevent the errors of storing data in ES when the query field in pg_stat_activity table exceeds 1024 byte length.  
WHY: The length of the values stored in the query field can extend beyond 1024 bytes, which is the limit of dimension field length after a limit override

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [x] elastic-package build
- [x] elastic-package stack up -v -d --services package-registry
- [x] Validation of relationship between query and query_id field
- [x] Record count validation
- [x] Index Field mapping validation
- [x] Index Settings validation

## How to test this PR locally

- [x] elastic-package build
- [x] elastic-package stack up -v -d --services package-registry
- [x] Upgrade the package

## Screenshots

image

## Priority
High.

### CODE REVIEW

**Comment by agithomas** [comment]
Index mappings after the change

```json
              "query": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "query_id": {
                "type": "keyword",
                "time

```

**Comment by lalit-satapathy** [comment]
@agithomas, @aliabbas-elastic, 

Can we reproduce and verify that the issue is getting resolved by the PR?

BTW, I am able to get a user query populated into: _postgresql.activity.query_
  
Screenshot 2023-10-23 at 11 11 03 AM

**Comment by aliabbas-elastic** [comment]
> Can we reproduce and verify that the issue is getting resolved by the PR?

Sure @lalit-satapathy Let me look into it

**Comment by aliabbas-elastic** [comment]
Performed TSDB testing over the changes and everything is working fine
```
All 234 documents taken from index .ds-metrics-postgresql.activity-default-2023.10.23-000001 were successfully placed to index tsdb-index-enabled.
```
image

**Review by lalit-satapathy — APPROVED** [review]
LGTM. 

The original below error was not reproduced during the testing. The fix should address the issue.

`Dimension fields must be less than [1024] bytes but was [1307]
`

**Pull request merged**
