### PR TITLE
[Enhancement] Cisco MERAKI urls user agent support

### PR DESCRIPTION
**Pull request by srilumpa**
## What does this PR do?

In some cases, Cisco MERAKI URLS logs contains an "agent" field right after the "mac" field. Since the detection of those fields is realized with a "dissect" processor, the extracted MAC address can then contains the user-agent as well.

This PR aims to extract the User-Agent, leave the MAC address (and only the MAC address) in the `cisco_meraki.urls.mac` field and parse the User-Agent using the "User Agent" processor.

Example before fix:

```json
{
  "_source": {
    "cisco_meraki": {
      "urls": {
        "mac": "AA-BB-CC-DD-EE-FF agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0'"
      },
      "event_type": "urls",
      "event_subtype": "http_access"
    },
    ...
  }
}
```

After fix:

```json
{
  "_source": {
    "cisco_meraki": {
      "urls": {
        "mac": "AA-BB-CC-DD-EE-FF agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0'"
      },
      "event_type": "urls",
      "event_subtype": "http_access"
    },
    "user_agent": {
      "original": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0",
      "version": "108.0",
      "name": "Firefox",
      "device": {
        "name": "Other"
      },
      "os": {
        "name": "Windows",
        "version": "10",
        "full": "Windows 10"
      }
    }
    ...
  }
}
```

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [x] I have updated the unitary tests

## How to test this PR locally

Execute `elastic-package check`

## Related issues

- None

### CODE REVIEW

**Comment by ShourieG** [comment]
@srilumpa The ci error is occurring because there is a mismatch in the readme fields. You need to update the file **"sample_event.json"** in the directory **cisco_meraki/data_stream/log** with the new fields introduced/changed by this PR and do run the command  **elastic-package build** . You need to install elastic-package first ofc. This will rebuild the README.md with the new fields and the error will go away.

**Comment by srilumpa** [comment]
@ShourieG thank you for the feedback. I have updated the README.md file as asked.

**Comment by ShourieG** [comment]
@srilumpa Hey there, actually if you manually update the README it's not gonna work. I pulled your branch code and checked a couple of things, and these are the following steps you need to do, so that it passes the ci checks :- 

1) install elastic-package tool from :  https://github.com/elastic/elastic-package
2) then after that run the command: elastic-package stack up -v -d
3) go to the integration folder **cisco_meraki/data_stream/log**  and look for the file **"sample_event.json"**
4) add the following block to the   to the existing log : 

```javascript
 "user_agent": {
      "original": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0",
      "version": "108.0",
      "name": "Firefox",
      "device": {
        "name": "Other"
      },
      "os": {
        "name": "Windows",
        "version": "10",
        "full": "Windows 10"
      }
    }
   ```
5)  then after this run command **elastic-package build**
6) run command : **elastic-package stack up -v -d  --services package-registry**
7) run command eval **"$(elastic-package stack shellinit)"** or **eval $(elastic-package stack shellinit --shell bash)** 
     which ever works on your system
8) Finally run command  **elastic-package test pipeline -v --generate**

These steps will regenerate the expected log files, and README files at the same time testing the changes that you have made and mostly make sure it passes our ci tests.

**Comment by srilumpa** [comment]
Hi @ShourieG and thank you for you guiding me for this.

I updated the README.md file simply running `elastic-package build`, not manually, and I am not confident in changing the `sample_event.json`by adding this block since the sample log in it is not an `urls` log type but one of the `security_event` log type.

Anyway, here is an updated version after the `elastic-package test pipeline -v --generate` command has been ran. Here is the output of the command.

```
2022/12/22 11:22:23 DEBUG Enable verbose logging
Run pipeline tests for the package
--- Test results for package: cisco_meraki - START ---
╭──────────────┬─────────────┬───────────┬────────────────────────────┬────────┬──────────────╮
│ PACKAGE      │ DATA STREAM │ TEST TYPE │ TEST NAME                  │ RESULT │ TIME ELAPSED │
├──────────────┼─────────────┼───────────┼────────────────────────────┼────────┼──────────────┤
│ cisco_meraki │ events      │ pipeline  │ test-mx-events.json        │ PASS   │    42.0565ms │
│ cisco_meraki │ log         │ pipeline  │ test-airmarshal-events.log │ PASS   │   227.7732ms │
│ cisco_meraki │ log         │ pipeline  │ test-events.log            │ PASS   │   102.4388ms │
│ cisco_meraki │ log         │ pipeline  │ test-flows.log             │ PASS   │    35.0057ms │
│ cisco_meraki │ log         │ pipeline  │ test-ip-flow.log           │ PASS   │    27.1247ms │
│ cisco_meraki │ log         │ pipeline  │ test-security-events.log   │ PASS   │    32.5743ms │
│ cisco_meraki │ log         │ pipeline  │ test-urls.log              │ PASS   │    22.0469ms │
╰──────────────┴─────────────┴───────────┴────────────────────────────┴────────┴──────────────╯
--- Test results for package: cisco_meraki - END   ---
Done
```

**Comment by joeafari** [comment]
hey @srilumpa @ShourieG 
There seems to be a conflict that is preventing the pull request to be finalized. Could you please review and correct it?
Thanks

**Comment by ShourieG** [comment]
@srilumpa, you need to merge latest upstream/main into your branch, it should resolve the merge conflicts

**Comment by srilumpa** [comment]
@joeafari and @ShourieG, I fixed the conflict and updated the tests accordingly

**Pull request merged**
