### PR TITLE
github: give greater instructions for commit messages

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

This brings the commit message section of the PULL_REQUEST_TEMPLATE.md into line with the text used in the beats repository.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by efd6** [comment]
Note that changing this file causes *all* packages to be tested. This should probably not happen.

**Review by zmoog — APPROVED** [review]
❤️

**Review by cmacknz — APPROVED** [review]

**Review by shmsr — APPROVED** [review]

**Review by jsoriano — APPROVED** [review]
:+1:

**Comment by efd6** [comment]
@jsoriano When this has been approved by all, would you mind force merging this? I don't see why it should be blocked by packages failing.

**Review by bhapas — APPROVED** [review]

**Review by crespocarlos — APPROVED** [review]

**Comment by efd6** [comment]
@jsoriano I think everyone has accepted this.

**Comment by mrodm** [comment]
> @jsoriano I think everyone has accepted this.

@efd6 I'll merge it, thanks for this PR!

**Pull request merged**
