### PR TITLE
[O11y][Oracle] Migrate `Performance` dashboard visualizations to lens in kibana 8.6.0

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

- Migrate visualizations to lens for Oracle integration package

- Statistics for **Oracle** Lens migration:

<html>
<body>
<google-sheets-html-origin>

Oracle Dashboards | Before Migration |   | After Migration |   |
-- | -- | -- | -- | -- |
  | Lens | Visualization | Lens | Visualization
[Metrics Oracle] Performance | 0 | 15 | 15 | 0

</body>
</html>

## Checklist

- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that panels are populated with data.
- [x] I have verified that panels are not distorted after being migrated to lens.
- [x] I have updated screenshots of dashboard.
- [x] I have verified that data count are matching and panel aggregations are same as before.

## Author's checklist

- [x] Migrated panels should be removed from visualization folder.
- [x] Migrated visualizations are populating in Kibana version `8.6.0`. 

## Related issues

- Relates 
  - #5221 
  - #5753

**Note**: - Previously the screenshot was not fully updated. Hence providing screenshot for compare and review process.

image

### CODE REVIEW

**Comment by milan-elastic** [comment]
Thanks, @harnish-elastic ! Looks good, Approved!

**Comment by agithomas** [comment]
Can you continue populating the data for some more time or change the time window so that the panel has data fully filled and does not look broken. Referring to the screenshot.

**Comment by agithomas** [comment]
Why the kibana version change to 8.6.0 ?

**Comment by kush-elastic** [comment]
> Why the kibana version change to 8.6.0 ?

We have already provided the reason behind why we are migrating to Kibana version `8.6.0` in the [issue](https://github.com/elastic/integrations/issues/5753#:~:text=kibana%20version%20(8.6.0)-,Note,-The%20reason%20behind) itself. The reason behind why we have mentioned there is that the dashboard (`System Statistics`) which lets us use kibana 8.6.0 is different from this PR.

**Review by kush-elastic — APPROVED** [review]

**Comment by harnish-elastic** [comment]
> Can you continue populating the data for some more time or change the time window so that the panel has data fully filled and does not look broken. Referring to the screenshot.

All the panels are populated with data and charts looks good. Are you suggesting to still update the screenshots with more data? https://raw.githubusercontent.com/elastic/integrations/f2f477af91fdc98439a67f630900ae46e21a6f2c/packages/oracle/img/Oracle-performance-dashboard.png

**Comment by agithomas** [comment]
> > Can you continue populating the data for some more time or change the time window so that the panel has data fully filled and does not look broken. Referring to the screenshot.
> 
> All the panels are populated with data and charts looks good. Are you suggesting to still update the screenshots with more data? https://raw.githubusercontent.com/elastic/integrations/f2f477af91fdc98439a67f630900ae46e21a6f2c/packages/oracle/img/Oracle-performance-dashboard.png

Please ignore this comment. I observed the panel looked broken and on recheck, it looked fine.

**Comment by agithomas** [comment]
@efd6 , are there concerns with the security team to set 8.6.0 as the min version for Oracle integration ?

**Comment by efd6** [comment]
@agithomas If the bump is required for the visualisation changes then it's OK. This is what we have been doing recently. See https://github.com/elastic/integrations/pull/5493#discussion_r1147273015.

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
