### PR TITLE
[AWS] Add metric type to VPN, Firewall and Transit Gateway data streams

### PR DESCRIPTION
**Pull request by constanca-m**
## What does this PR do?

Add metric type to VPN, Firewall and Transit Gateway data streams.

All metrics are gauge, since they go up and down and might not relate to the previous values. For example, some metrics may have a specific time window of 1 minute. For that minute, all values are summed to obtain the final value of a field, but as soon as that time window finishes, the value restarts again. There is no guarantee that the next value will be equal or higher than the previous value.

## Author's Checklist

 - [x] Verification of data in visualisation after enabling TSDB flag in kibana
 - [x] Verify if field mapping is correct in the data stream template.

## How to test this PR locally

Refer to https://github.com/elastic/integrations/issues/6293.

## Related issues

Relates to https://github.com/elastic/integrations/issues/6293.

### CODE REVIEW

**Review by tetianakravchenko — APPROVED** [review]

**Review by aspacca — APPROVED** [review]

**Comment by constanca-m** [comment]
\test

**Pull request merged**
