### PR TITLE
[NetSkope] add UNIX format to the date processor on Alerts and Events datasets.

### LINKED ISSUE #9430: [NetSkope] Date processor failing on both Alerts and Events ingest pipeline
Hello,

The `date` processor for both the Alerts and Events ingest pipelines in the NetSkope integration is failing because it expects the `@timestamp` from the source messager to be a `ISO8601` string, but this field can also have a `UNIX` as its value.

Since the format is wrong, the indexed event will use the ingest time, and will have the `error.message` field with the following value:

> Unable to parse the value of Timestamp field, therefore setting the value of Timestamp field to current time.

I've made a PR to fix this.

### PR DESCRIPTION
**Pull request by leandrojmp**
## Proposed commit message

The `date` processor on the ingest pipeline for both datasets in the netskope integration only has `ISO8601` as the format, but the value of the source `@timestamp` field can also appear as `UNIX`, which will make the processor fail and the event will use the current time instead of its original time.

This PR adds the `UNIX` format to the date processor to cover these cases

- Bug
## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #9430

### CODE REVIEW

**Review by efd6 — COMMENTED** [review]
@leandrojmp Are you able to provide a test case for each of the newly supported timestamp formats?

**Comment by leandrojmp** [comment]
> Please do. It guards against regression.

@efd6 

Just added the tests for UNIX and UNIX_MS timestamps!

**Comment by efd6** [comment]
pipeline test: test-alerts.log in netskope.alerts
```
test case failed: Expected results are different from actual ones: --- want
+++ got
@@ -4400,7 +4400,7 @@
             }
         },
         {
-            "@timestamp": "2022-04-10T06:00:05.000Z",
+            "@timestamp": "1970-01-20T02:12:50.405Z",
             "destination": {
                 "address": "81.2.69.142",
                 "geo": {
```
pipeline test: test-events.log in netskope.events
```
test case failed: Expected results are different from actual ones: --- want
+++ got
@@ -2180,7 +2180,7 @@
             }
         },
         {
-            "@timestamp": "2022-02-12T12:02:32.020Z",
+            "@timestamp": "1970-01-20T00:50:24.152Z",
             "destination": {
                 "address": "89.160.20.112",
                 "geo": {
@@ -2290,7 +2290,7 @@
             }
         },
         {
-            "@timestamp": "2022-02-12T12:02:32.020Z",
+            "@timestamp": "2022-02-12T00:02:32.020Z",
             "destination": {
                 "address": "89.160.20.112",
                 "geo": {
```

**Comment by leandrojmp** [comment]
> Please make sure the 1970 timestamps are sane.

Yeah, I think the issue here is in the `date` processor, I'm not able to have both `UNIX` and `UNIX_MS` as the formats, one of them will fail depending on the order of the formats.

Using the following epoch `1711599155639` which is `2024-03-28T04:12:35.639Z`, the epoch without millis would be `1711599155`.

If in the `date` processor I have the formats in the following order: `ISO8601`, `UNIX`, `UNIX_MS` the epoch with millis will fail, but if I use the order `ISO8601`, `UNIX_MS`, `UNIX`, then the epoch without millis will fail.

Maybe the `date` processor does not support both?

This pipeline can replicate this:

```
POST /_ingest/pipeline/_simulate?verbose=true
{
  "pipeline" :
  {
    "description": "date processor",
    "processors": [
      {
        "date" : {
          "field" : "@timestamp",
          "target_field": "processed_date", 
          "formats": ["ISO8601", "UNIX","UNIX_MS"]
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "id": "1",
        "@timestamp": "1711599155"
      }
    },
    {
      "_source": {
        "id": "2",
        "@timestamp": "1711599155639"
      }
    }
  ]
}
```

Not sure if this is expected behavior or a bug in the `date` processor.

I will remove the `UNIX_MS` format and tests and use only `UNIX`, current at my logs I'm only seeing the `@timestamp` as epoch without millis, I added the `UNIX_MS` as a future proof in the case that netskope changes the format.

**Comment by efd6** [comment]
This *can* be done heuristically by scaling unexpected dates into the expected range. This is reasonable when the constraints are known, and possibly reasonable here; we could say that if the unix time is less than 1e12 it should be multiplied by 1000, and then apply the unix milli interpretation. This is unlikely to be unsafe, but may be best to be guarded behind an option is it's used.

**Review by efd6 — APPROVED** [review]
Thanks

**Pull request merged**
