### PR TITLE
[O11y][Redis] Migrate `Key Metrics` dashboard visualizations to lens in kibana 8.3.0

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

- Migrate visualizations to lens for Redis integration package

- Statistics for **Redis** Lens migration:

<html>
<body>
<google-sheets-html-origin>

Redis dashboard | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics Redis] Keys | 0 | 5 | 5 | 0

</body>
</html>

## Checklist

- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that panels are populated with data.
- [x] I have verified that panels are not distorted after being migrated to lens.
- [x] I have updated screenshots of dashboard.
- [x] I have verified that data count are matching and panel aggregations are same as before.

## Author's checklist

- [x] Migrated panels should be removed from visualization folder.
- [x] Migrated visualizations are populating in Kibana version 8.3.0. 

## Related issues

- Relates #5221

## Issues Identified
- Splitting a chart into multiple smaller charts by a breakdown dimension is not supported in the lens.
  https://github.com/elastic/kibana/issues/72063
  - Impact : [ Severity : Critical, Workaround : Yes]

### CODE REVIEW

**Comment by harnish-elastic** [comment]
Since we have confirmation on work-around of split series charts by Subhrata, putting this PR into draft.

**Comment by rajvi-elastic** [comment]
@SubhrataK , The two panels that were blocked in the Redis integration can be migrated as per the discussion that we had on [split series functionality](https://github.com/elastic/integrations/issues/5531#issuecomment-1477512047). 

In **Lists length [Metrics Redis]** visualization, we found that the fields used in both split series functionality use different sizes (i.e. 16, 20 respectively) as highlighted in below screenshot. So it will show total `16*20=320` line charts (Top 16 values of `redis.keys.id` and Top 20 values of `redis.key.name` for each 16 `redis.keys.id`)! 

image

However this is not the case in Lens. We use breakdown functionality in Lens to tackle this issue but in that we can specify only one size for both fields. For example if we provide 20 then it will show top 20 line chart for combined field of `redis.keys.id` + `redis.keys.name`.  So while migrating this panel in lens, should we provide 320 (which will show 320 line charts and IMO it would become tough for the user to interpret the information) or should we provide the small number (for example 20 which will show user just top 20 charts)

image


And should we enable group other functionality in the lens visualization? it will group all the other values in separate bucket and provide one line chart for that.

**Comment by SubhrataK** [comment]
@rajvi-elastic As discussed, please change it to display Top 10 values only.

**Review by kush-elastic — APPROVED** [review]

**Comment by agithomas** [comment]
@SubhrataK , can we have your input on the [discussion](https://github.com/elastic/integrations/pull/5659#issuecomment-1485053509)?

**Comment by harnish-elastic** [comment]
> @SubhrataK , can we have your input on the [discussion](https://github.com/elastic/integrations/pull/5659#issuecomment-1485053509)?

@agithomas For this discussion, @SubhrataK has provided her [comments](https://github.com/elastic/integrations/pull/5659#issuecomment-1486702604) over here. But @SubhrataK can provide more information around it if it's needed.

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
