### PR TITLE
[Atlassian JIRA & Confluence] Add support for Atlassian Cloud

### LINKED ISSUE #2695: [Integrations] Atlassian Jira/Confluence Cloud Integration
**Describe the feature:**
Including in the Atlassian Jira/Confluence integration. At the moment is only works with Self Hosted Jira/Confluence. The API endpoints for both are different so at the moment the Atlassian Jira/Confluence integration does not work with Cloud Jira/Confluence accounts.

Would be great for the same integration configuration settings for both. But for the integration to be compatible with the Cloud API as well as the Self Hosed API.

**Describe a specific use case for the feature:**
To have a fluid Atlassian integration which includes performance for the Self Hosted and Cloud Jira/Confluence environments.

**Example of Jira Cloud API endpoint:**
Below is the Jira Cloud Endpoint API link:
> https://{{jira_domain}}/rest/api/3/auditing/record

**Example of Jira Cloud API endpoint RAW GET:**
Example of the RAW GET Request  to the Jira Cloud Audit API
> curl --location --request GET 'https://{{jira_domain}}/rest/api/3/auditing/record' \
--header 'Accept: application/json' \
--header 'Authorization: Basic {{basic_auth_token}}'

**Example of Jira Cloud API endpoint RESPONSE:**
Example of the response of the Jira Cloud API audit log, please see the link below.
[Response](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-audit-records/#api-rest-api-3-auditing-record-get-responses)

**Example of Confluence Cloud API endpoint:**
Below is the Confluence Cloud Endpoint API link:
> https://{{confluence_domain}}/wiki/rest/api/audit

**Example of Confluence Cloud API endpoint RAW GET:**
Example of the RAW GET Request  to the Confluence Cloud Audit API
> curl --location --request GET 'https://{{confluence _domain}}/rest/api/3/auditing/record' \
--header 'Accept: application/json' \
--header 'Authorization: Basic {{basic_auth_token}}'

**Example of Confluence Cloud API endpoint RESPONSE:**
Example of the response of the Confluence Cloud API audit log, please see the link below.
[Response](https://developer.atlassian.com/cloud/confluence/rest/api-group-audit/#api-wiki-rest-api-audit-get-responses)

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Adds support for the SaaS versions of Confluence and JIRA in the Atlassian Cloud for the audit datastream.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Closes #2695

### CODE REVIEW

**Comment by legoguy1000** [comment]
found some bugs, put back to draft

**Comment by legoguy1000** [comment]
I'm getting this issue `[elastic_agent.filebeat][debug] template execution failed: template: :1:18: executing "" at <.url.params.offset>: can't evaluate field params in type interface {}`.  Is this related to elastic/beats#30477 or elastic/beats#30476??

**Comment by legoguy1000** [comment]
I was able to get around the above issue but now with the current config whenever it paginates, instead of just updating the offset via the `response.pagination` config, it also updates the date params using the cursor setting so it never actually paginates.

**Comment by andrewkroh** [comment]
I rebased this in order to apply the formatting of the pipeline test files in separate commits. This way it will be easier to digest the non-formatting changes during review. The JSON is now normalized due to https://github.com/elastic/elastic-package/pull/644, but until all of the packages are normalized you'll get these large diffs the first time you make changes.

**Comment by legoguy1000** [comment]
even with the latest 8.0.0 docker image, I can't get past the error, https://github.com/elastic/integrations/pull/2715#issuecomment-1046291862. Any thoughts?

**Comment by andrewkroh** [comment]
Do the tests not expose this problem? The CI checks are passing for this. It's using 7.16.0 for the tests. The 8.0 branch was missing a backport, and that has [now been fixed](https://github.com/elastic/beats/pull/30574), but not released.

**Comment by legoguy1000** [comment]
> Do the tests not expose this problem? The CI checks are passing for this. It's using 7.16.0 for the tests. The 8.0 branch was missing a backport, and that has [now been fixed](https://github.com/elastic/beats/pull/30574), but not released.

I have to keep playing with it as I'm testing it against an actual Atlassian cloud instance and I keep getting the error so idk if I have a bad docker image or something but I've cleared all my local images and still having issues.

**Comment by andrewkroh** [comment]
Try testing with either 7.17.0 or 8.1.0 (e.g. `elastic-package stack up -d -v --version=7.17.0`).

**Comment by legoguy1000** [comment]
I'll try with 8.1. I didn't have any issues when I built filebeat from source on main branch using a basic input config to test. So it's definitely weird.

**Comment by legoguy1000** [comment]
@andrewkroh 8.1 appears to work and i'm no longer getting an error that the key doesn't exist but still having an issue with Pagination.  I currently have
```
response.pagination:
  - set:
      target: url.params.from
      value: '[[.last_response.url.params.Get "from"]]'
      fail_on_template_error: true
...
```
This should maintain the existing URL parameter so the pagination continues through the same time range.  However it's being overridden by the cursor and the original request Transforms.  Any thoughts on how to fix that?
```
cursor:
  last_timestamp:
    value: "[[.first_event.created]]"

request.transforms:
...
  - set:
      target: url.params.from
      value: "[[.cursor.last_timestamp]]"
      default: '[[formatDate (now (parseDuration "-{{initial_interval}}")) "2006-01-02T15:04:05.999-0700"]]'
...
```

**Comment by P1llus** [comment]
@legoguy1000 In the current situation the request transforms run for each pagination, so I believe we might have to take another approach on this.

If date is the only possible value here, we might have to drop the pagination and simply let it catch up with a smaller interval. Unless there is some sort of range query, or other values we can use from response headers or body to paginate.

Let's catch up when you got time to discuss this! :)

**Comment by legoguy1000** [comment]
@P1llus copy. I'm artificially inducing pagination in order to make sure there is a valid solution as idk how many events/time is normal for these services. Unfortunately this seems like the only way to paginate but I can check again to see if there is anything in the headers.

**Comment by legoguy1000** [comment]
@P1llus Looks like instead of trying to set individual params, setting `url.value` and build the entire query string seems to be a work around.  Only issue is it doesn't URL encode the values so the TZ offset in the JIRA date params `+0000` messes up the url.  It looks like just leaving off the TZ part will work since all the dates are in UTC anyways.  BUt the better solution would probably be to create a URL encode template function.  Thoughts??

**Comment by legoguy1000** [comment]
Just tested without the TZ offset and the `url.value`, worked great.  It paginated through 9 pages, 10 items each for 76 events total and the start/end dates stayed the same.  Just need an answer on the URL encode functionality and we can press to merge this.

**Comment by andrewkroh** [comment]
Does any of this depend on https://github.com/elastic/beats/pull/30962? If so the kibana constrained will need change to `^8.3.0`.

**Comment by legoguy1000** [comment]
Long term it should be updated to use that function, but I was able to get around it.  Instead of wrapping the datetime with `+000` for timezone, since its always UTC, i just left the TZ offset from the URL and it seemed to work fine.

**Review by andrewkroh — APPROVED** [review]

**Pull request merged**
