### PR TITLE
Add null checks and ignore_missing checks to the rename processor

### PR DESCRIPTION
**Pull request by ishleenk17**
- Bug

## What does this PR do?

This PR adds the if check for event.original and the ignore_missing check for the renaming of message to event.original

This PR does changes for below Packages:

- apache
- apache_tomcat
- cassandra
- ceph
- citrix_adc
- golang
- hadoop
- haproxy
- iis
- kafka
- microsoft_sqlserver
- nagios_xi
- nginx
- oracle
- oracle_weblogic
- php_fpm
- postgresql
- rabbitmq
- redis
- traefik

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates https://github.com/elastic/integrations/issues/7822

### CODE REVIEW

**Comment by muthu-mps** [comment]
@ishleenk17,
As this PR closes the #7822 , Are we consider addressing all the cloud native and cloud monitoring integration changes as well with this PR ?

### Observations

As the event.original is renamed and the grok processor is applied without validating the `preserve_original_event` flag. Will this be an extra overhead when we remove the `event.original` field at the end after performing rename and applying grok?

#### Remove processor Sample
```
- remove:
      field: event.original
      if: "ctx.tags == null || !(ctx.tags.contains('preserve_original_event'))"
      ignore_failure: true
      ignore_missing: true
```

**Comment by shmsr** [comment]
Can we also note down the names of the packages touched in this PR so that it is trackable? 

> Closes https://github.com/elastic/integrations/issues/7822

^ This issue will be closed once this PR gets merged and not all packages are taken care of, right? So can we do s/Closes/Relates

**Comment by shmsr** [comment]
Looks good to me.

**Review by shmsr — COMMENTED** [review]
Left a comment in PR comments.

**Comment by ishleenk17** [comment]
> Can we also note down the names of the packages touched in this PR (in the PR description itself) so that it is trackable?
> 
> Also, in the PR description:
> 
> > Closes #7822
> 
> ^ This issue will be closed once this PR gets merged and not all packages are taken care of, right? So can we do s/Closes/Relates

MAkes sense. Updated!

**Review by shmsr — APPROVED** [review]

**Comment by ishleenk17** [comment]
> As the event.original is renamed and the grok processor is applied without validating the `preserve_original_event` flag. Will this be an extra overhead when we remove the `event.original` field at the end after performing rename and applying grok?

@muthu-mps , the renaming of message to event.original was already happening. We are mainly adding if checks. 
Also since we are having check for preserve original in the end after all the groking has been done, so it should be ok.
For tracking preserve original issue I have raised this github [ticket](https://github.com/elastic/integrations/issues/7911)

**Comment by muthu-mps** [comment]
@ishleenk17 - As part of the new validation rules [here](https://github.com/elastic/package-spec/issues/583) we should also remove the message field. Can we consider removing message field as a part of this change ?

**Review by muthu-mps — APPROVED** [review]
LGTM!

**Pull request merged**
