### PR TITLE
[fortinet_fortigate] Fix test data

### PR DESCRIPTION
**Pull request by aleksmaus**
## Proposed commit message

Fix test data.
Looking at the original event data and the pipeline, it looks like the test output expectation was wrong. Fixed that.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes https://github.com/elastic/integrations/issues/10365

### CODE REVIEW

**Review by pkoutsovasilis — APPROVED** [review]
LGTM! full disclosure, I remember this issue where the extension part was not expected for newer versions of elastic stack but it was expected for older ones?! somebody updated the stack version in the CI of fortinet_fortigate?!

**Comment by aleksmaus** [comment]
> extension part was not expected for newer versions of elastic stack but it was expected for older ones

It seemed to me that deriving the extension as ```fortianalyzer/setting``` from ```url="/api/v2/cmdb/log.fortianalyzer/setting?vdom=root"``` is wrong, the url parser processor doesn't produce that extension value from that given url

**Comment by aleksmaus** [comment]
Hmm, and it failed in CI with
Screenshot 2024-08-23 at 12 04 57 PM

WTH?

**Comment by aleksmaus** [comment]
Looks like test was ran agains 8.3.0 version of the stack, rechecking if there was a bug in ```uri_parts``` processor in that early version.

**Comment by aleksmaus** [comment]
Looks like indeed a bug in 8.3.0 
Screenshot 2024-08-23 at 12 20 19 PM

Was fixed in 8.14.0 it looks like 
https://github.com/elastic/elasticsearch/pull/105689

Should we bump the constraint on that package to 8.14.0 then?

**Comment by aleksmaus** [comment]
Fixed the input data as a workaround the bug in uri_parts processor that was fixed in Elasticsearch 8.14. This will keep the constraint at 8.3.0 still since the bug is not in the integration.

**Pull request merged**
