### PR TITLE
[AWS] Migrate NATGateway metrics visualizations to lenses

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?

Migrates visualizations to lenses and adds input control groups.

Before:
natgateway_before

After:
natgateway_after

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by drewdaemon — COMMENTED** [review]
Looks great! One request: let's avoid using the Legacy Metric in favor of the Metric chart.

**Comment by gpop63** [comment]
I replaced legacy metrics charts with metrics charts.

Here's how it looks now:

natgateway_metrics

**Review by drewdaemon — APPROVED** [review]

**Comment by gpop63** [comment]
@drewdaemon what do you think about the width of the metric charts?

natgateway_new_layout

**Comment by gvnmagni** [comment]
Absolutely! 👍

**Review by zmoog — APPROVED** [review]

**Pull request merged**
