### PR TITLE
[security-external-integrations packages] Update to ECS 8.5

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

This updates the ECS version used in all non-deprecated packages owned by elastic/security-external-integrations.

See #4338 for a list of preparatory changes that were made before this PR.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to ~test~ recreate this PR locally

The changeset was fully produced by this command from the root of the repo at the parent of the first commit in the PR:

```
go run github.com/andrewkroh/go-examples/ecs-update@6efa1ecb3871 \
	-ecs-version=8.5.0 \
	-ecs-git-ref=v8.5.1 \
	-pr=4285 \
	-owner=elastic/security-external-integrations \
	packages/*
```

Note that the marked ECS version has a zero patch version as this appears to be the convention.

## Related issues

- Relates #4338

### CODE REVIEW

**Review by andrewkroh — APPROVED** [review]

**Review by muthu-mps — COMMENTED** [review]
How do we handing ECS version update for the data-streams that is developed by service integration team and the code owner is security team ? For Example we have `performance`, `transaction` datastreams in `microsoft_sqlserver` and similarly for `Oracle`.

**Comment by efd6** [comment]
@muthu-mps We are happy to do the work for the co-owned packages. They are done here.

**Review by andrewkroh — APPROVED** [review]

**Review by muthu-mps — APPROVED** [review]
LGTM!

**Review by endorama — APPROVED** [review]

**Pull request merged**
