### PR TITLE
Generate docs from existing package content

### PR DESCRIPTION
**Pull request by mtojek**
Issue: https://github.com/elastic/integrations/issues/107

This PR adds support for generating docs from the existing package content and `import-beats-resources`. It will help developers to update docs sources and keep in sync fields and README.

Also, I've added support for rendering sample events in READMEs. Sample events must be present in `packages/{packageName}/dataset/{datasetName}/sample_event.json`.

Preview tool's README: https://github.com/mtojek/integrations/tree/107-generate-docs/dev/generate-docs

Sample event in JSON for nginx/stubstatus: https://github.com/mtojek/integrations/blob/107-generate-docs/packages/nginx/dataset/stubstatus/sample_event.json

To verify if it works, I've adjusted the following integrations: nginx, cisco, netflow.

### CODE REVIEW

**Comment by mtojek** [comment]
self-approved

let me merge this one, to verify on the mongodb integration (thanks @kaiyan-sheng). Fixes won't be blocking and can be applied in followups.

**Comment by mtojek** [comment]
>One question, do we have to list all fields? Like dataset.name, event.created etc in fields doc?

The script will handle this. IMHO we should describe all fields in the README docs not to introduce any gaps or fields without proper description. If it's in fields.yml file, it should be consistently mentioned in the docs.

**Comment by kaiyan-sheng** [comment]
@mtojek Good point, it's just these fields will be repeating themself for all metric datasets. I wonder if we can find a central location to document them instead of duplicating them in each dataset. @exekias WDYT?

**Comment by exekias** [comment]
> @mtojek Good point, it's just these fields will be repeating for all metric datasets. I wonder if we can find a central location to document them instead of duplicating them in each dataset. @exekias WDYT?

That's a fair point, Beats docs for modules normally cover module specific fields (example: https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-nginx.html), leaving the common fields to other parts of the docs: https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-common.html and https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-event-structure.html.

I think this saves some space on screen and focuses on the integration fields.

This change looks great for now, I think it should be easy to reevaluate as we go

**Pull request merged**
