### PR TITLE
[windows] Preserve original event when toggled on

### PR DESCRIPTION
**Pull request by nicpenning**
- Bug

## Proposed commit message
See title.

This should resolve some of the issues here: https://github.com/elastic/integrations/issues/9425

I didn't have Sysmon or Forwarded events for testing, but they all use nearly the same template files so they should work.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues
- Closes https://github.com/elastic/integrations/issues/9425

## Screenshots

After fix:
image
image
image
image

### CODE REVIEW

**Comment by nicpenning** [comment]
Ready to test.

**Comment by AndersonQ** [comment]
I'll be off on PTO the whole next week, so I'm removing myself from the reviewers.
cc: @fearful-symmetry

**Review by fearful-symmetry — APPROVED** [review]
Can't comment on the windows-specific parts, but the integration seems fine.

**Review by belimawr — APPROVED** [review]

**Review by marc-gr — APPROVED** [review]
lgtm

**Comment by nicpenning** [comment]
Thank you!

**Pull request merged**
