### PR TITLE
[O11y][Apache Spark] Add metric type mapping for driver datastream

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

This PR adds metric_type mapping for the fields of the driver data stream.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

To verify the metric_type, please refer to the below mbeans type that is used for data collection

[driver_mbean.txt](https://github.com/elastic/integrations/files/12827172/driver_mbean.txt)

- Relates #7786
- Relates #7408

### CODE REVIEW

**Review by aliabbas-elastic — APPROVED** [review]
LGTM

**Comment by agithomas** [comment]
@harnish-elastic , similar to https://github.com/elastic/integrations/pull/7794, is there a source of metric_type you have for reference?

**Comment by harnish-elastic** [comment]
> @harnish-elastic , similar to #7794, is there a source of metric_type you have for reference?

@agithomas Since the MBean list is too large to mention in the PR description, I have already attached the link of the metric_type in the [description](https://github.com/elastic/integrations/pull/8110#:~:text=To%20verify%20the%20metric_type) itself.

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
