### PR TITLE
[Apache] Rename apache2.error.integration to apache.error.module

### PR DESCRIPTION
**Pull request by herrBez**
## Proposed commit message

Rename `apache2.error.integration` to `apache.error.module`

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## Related issues

- https://github.com/elastic/beats/pull/39481 
- https://github.com/elastic/beats/issues/39480

### CODE REVIEW

**Comment by shmsr** [comment]
Shouldn't this be `apache2.error.integration` to `apache.error.integration`

**Comment by herrBez** [comment]
Because the field in the apache.error dataset is module (is the module of the apache error, it has nothing to do with Ealastic integrations and should be the same of apache error module):

https://github.com/elastic/integrations/blob/main/packages/apache/data_stream/error/elasticsearch/ingest_pipeline/default.yml#L21

**Comment by shmsr** [comment]
@herrBez Makes sense. Thanks.

**Review by shmsr — APPROVED** [review]
Let's wait for someone else from my team as well to give a +1 on this.

**Comment by devamanv** [comment]
@herrBez LGTM. You will also have to make update the package version in `manifest.yml` before it can be approved and merged.

**Review by devamanv — APPROVED** [review]
LGTM

**Pull request merged**
