### PR TITLE
[apache_tomcat] Improve access pipeline performance by split grok and switch to dissect

### PR DESCRIPTION
**Pull request by SimonAtElastic**
Restructuring apache_tomcat.access ingest pipeline to use dissect as first step and split grok into multiple processors to improve perfomance.
On test-env the ingest performance was more den doubled, from ~0.899ms per Document (average) to ~0.253ms per Document (average)

image

### CODE REVIEW

**Comment by harnish-elastic** [comment]
@SimonAtElastic, Can you please confirm as per your latest [commit](https://github.com/elastic/integrations/pull/8723/commits/eb3f7ec6d3f01cb65ee436abd154b5ed8bdb8f4e), the ingest performance is still ~304ms (average)?

**Comment by SimonAtElastic** [comment]
> @SimonAtElastic, Can you please confirm as per your latest [commit](https://github.com/elastic/integrations/pull/8723/commits/eb3f7ec6d3f01cb65ee436abd154b5ed8bdb8f4e), the ingest performance is still ~304ms (average)?

Not exactly, i know average ~0.25ms, so even improved :) I did the seperation of the grok before the dissect and then i got a slight improvement but after the dissect its performing better when combined.

**Review by harnish-elastic — APPROVED** [review]
LGTM! 🚀

**Review by ishleenk17 — APPROVED** [review]
Looks good!

**Pull request merged**
