### PR TITLE
[windows] Add Windows AppLocker Data Stream (Packaged app-Execution)

### PR DESCRIPTION
**Pull request by nicpenning**
- Enhancement

## What does this PR do?

This PR adds the Windows AppLocker Packaged app-Execution data stream which allows the ingestion of those events from the Windows Event Log. This is the final AppLocker data stream to get added.

Resolves Part of - https://github.com/elastic/integrations/issues/6979

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by nicpenning** [comment]
Ready for review and testing!

**Comment by nicpenning** [comment]
Now ready to go. Had to update README.md with the new data stream.

**Comment by nicpenning** [comment]
Missing the HTTP JSON config updates. I will get that updated soon. Sorry about that.

**Review by efd6 — APPROVED** [review]

**Pull request merged**
