### PR TITLE
[AWS] Migrate ELB metrics dashboard visualizations to lenses

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?
Migrates visualizations to lenses and adds input control groups.

Before:
elb_before

After:
elb_after

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by drewdaemon — COMMENTED** [review]
Could we use the Lens metric instead of the legacy metric?

**Comment by gpop63** [comment]
Replaced legacy metric charts, here's how it looks:

elb_metric_charts

**Comment by drewdaemon** [comment]
Looking good! @gvnmagni any further layout suggestions here?

**Comment by drewdaemon** [comment]
From meeting
- collapse first two layout lines into one
  - stack metric charts

**Comment by gpop63** [comment]
This is how it looks now - do you think the metric charts are too wide? @drewdaemon 

aws_elb_new_layout

**Review by drewdaemon — APPROVED** [review]
@gpop63 I think they look good. You have a particularly wide screen, so if it looks okay on yours, it probably looks good on smaller screens as well 👍

**Review by zmoog — APPROVED** [review]

**Pull request merged**
