### PR TITLE
[cisco_ftd]: escape hyphen inside regex char list

### PR DESCRIPTION
**Pull request by pkoutsovasilis**
## Proposed commit message

After tackling [this issue](https://github.com/elastic/integrations/issues/9489), a respective [PR](https://github.com/elastic/elastic-package/pull/1755) was created to `elastic-package` to mainstream the detection of similar warnings. Thus this PR fixes the following similar to the former issue regex-related warning for `cisco_ftd`
```
character class has '-' without escape
```

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

N/A 

## Related issues

N/A

## Screenshots

N/A

### CODE REVIEW

**Review by jrmolin — APPROVED** [review]

**Comment by dwhyrock** [comment]
Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`log` | 800.64 | 165.02 | -635.62 (-79.39%) | :broken_heart:

Do we need to be concerned about the performance report?

**Comment by pkoutsovasilis** [comment]
> Data stream	Previous EPS	New EPS	Diff (%)	Result
> `log`	800.64	165.02	-635.62 (-79.39%)	💔
> Do we need to be concerned about the performance report?

hmmm not sure to be honest I just escaped a hyphen I didn't expect such a massive impact on perf 🤷‍♂️

**Pull request merged**
