### PR TITLE
Enable and update packages using agent service deployer - DO NOT MERGE

### PR DESCRIPTION
**Pull request by mrodm**
## Proposed commit message

Test to enable independent Elastic Agents for all packages using the latest changeset of elastic-package main branch.
Migrate auditd_manager and oracle packages that were using custom agents to use this new mode to run Elastic Agents.

- Configuration/Settings for Elastic Agents is now defined in the configuration files for each system test.
- `_dev/deploy/agent` folders removed, no longer needed.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] Requires a new `elastic-package` version

## How to test this PR locally

```shell
# Build/Install elastic-package from main
cd /path/elastic-package
make install

cd /path/integrations

# Start Elastic stack
elastic-package stack up -v -d

# Run system tests in any of the packages from integrations
cd /path/integrations/packages/<package>
ELASTIC_PACKAGE_TEST_ENABLE_INDEPENDENT_AGENT=true elastic-package test system -v

# Tear down Elastic stack
elastic-package stack down -v
```

## Related issues

- Relates https://github.com/elastic/elastic-package/issues/787

### CODE REVIEW

**Comment by mrodm** [comment]
@flash1293 this PR that tests with the latest changes of `elastic-package` reports a package (zeronetworks) failing due to ignored fields cc @jsoriano 

Here it is the link to the error: https://buildkite.com/elastic/integrations/builds/11433#018f778c-9382-496a-a782-af5796a25b70/679-1176

**Comment by mrodm** [comment]
> @mrodm Ideally, the mapping issue should be investigated and fixed - e.g. if it is a keyword field that's running into `ignore_above`, maybe we don't need to index it at all or should index it as text? However, you should be able to also mute the error like this: #9823

Ok! This PR is not intended to be merged (at least for now). However, this is something that needs to be taken into account when a new `elastic-package` version is released and updated in the integrations repository, because it would require changes in packages. cc @elastic/ecosystem

**Comment by flash1293** [comment]
Yeah, the linked PR was meant to take care of this problem, but maybe some additional integrations had changes that made the check fail in new places. Lets wait for the build to finish, then I can create a PR to mute these errors as well.

Shows that we should get this change out quickly so integration authors see the problem right away.

**Comment by flash1293** [comment]
Opened PR here: https://github.com/elastic/integrations/pull/9871

**Pull request closed without merging**
