### PR TITLE
Add daemonset datastream for k8s package & system tests

### PR DESCRIPTION
**Pull request by ChrsMark**
## What does this PR do?
This PR:
1. adds daemonset datastream introduced by https://github.com/elastic/beats/pull/20649 as part of elastic/integrations#511, based on [migration assessment](https://github.com/elastic/obs-dc-team/blob/master/migration/packages/kubernetes.md) 
2. Adds system tests for the datastreams using mock k8s APIs

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [x] I have verified that all datasets collect metrics or logs.

### CODE REVIEW

**Comment by ChrsMark** [comment]
@mtojek it could be merged as is but not sure if we should merge yet. However, I would like your eyes on this at this stage.

**Review by mtojek — APPROVED** [review]
LGTM. I think we can merge it and even push it to snapshot. We don't need to promote it further.

**Comment by ChrsMark** [comment]
OK merging this one for now, thanks for reviewing!

**Comment by ChrsMark** [comment]
Ah, CI failed. Checking...

**Comment by mtojek** [comment]
Hm.. it looks like it passed.

**Pull request merged**
