### PR TITLE
[Crowdstrike] Removing edge processing and fixing some missing field definitions

### LINKED ISSUE #658: Convert Crowdstrike's edge processing to Ingest Node pipeline
# Convert edge processing to Ingest Node pipeline

This package uses Beats processors for some of its data processing. We want to
move that processing into the ingest node pipeline that is part of the package
to make reuse easier (e.g. data from Kafka could be routed through the pipeline).

### Data Streams
- falcon (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added

### PR DESCRIPTION
**Pull request by P1llus**
## What does this PR do?

This removes edge processing from the Crowdstrike package, and adds some missing fields to the field definition. Certain timestamp fields was also known to be 0, so changed the pipeline a bit to remove unnecessary fields.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.

## Related issues

- Closes #658

### CODE REVIEW

**Comment by P1llus** [comment]
This PR only resolves the edge processing, however it is also seen that multiple fields are breaking the ECS convention, that custom fields uses `camelCase` naming compared to` snake_case`, this could be fixed in a separate PR.

**Review by marc-gr — APPROVED** [review]
LGTM

**Review by andrewkroh — APPROVED** [review]

**Comment by P1llus** [comment]
jenkins test this please

**Comment by P1llus** [comment]
jenkins run tests please

**Comment by P1llus** [comment]
jenkins run tests please

**Pull request merged**
