### PR TITLE
[WebSphere Application Server] Migrate to GA

### PR DESCRIPTION
**Pull request by aliabbas-elastic**
- Enhancement

## What does this PR do?

Migrates the integration from BETA to GA.

## Related issues

- Closes https://github.com/elastic/integrations/issues/7281

### CODE REVIEW

**Review by harnish-elastic — APPROVED** [review]

**Review by ishleenk17 — APPROVED** [review]
Looks good!

**Comment by muthu-mps** [comment]
@aliabbas-elastic, 

- The Threadpool dashboard has a table view which represents the total number of threads. The title is given as `ThreadPool size`. Can you check and update the title ?
- Below that we have Total Threads, Is it okay to remove the table from the dashboard if this is a redundant information which is already available ?
Screenshot 2023-09-21 at 8 56 11 AM

**Comment by aliabbas-elastic** [comment]
> The Threadpool dashboard has a table view which represents the total number of threads. The title is given as ThreadPool size. Can you check and update the title ?

As it displays the thread count per server, I can update it to `Total Threads in Thread Pool`. Let me know if that's seem good.

> Below that we have Total Threads, Is it okay to remove the table from the dashboard if this is a redundant information which is already available ?

The `Total Threads` visualization displays the thread count per threadpool over a period of time. So user can see the trend of total number of threads (increasing or decreasing). [Link](https://github.com/elastic/integrations/blob/main/packages/websphere_application_server/data_stream/threadpool/fields/fields.yml#L28)

**Comment by muthu-mps** [comment]
> > The Threadpool dashboard has a table view which represents the total number of threads. The title is given as ThreadPool size. Can you check and update the title ?
> 
> As it displays the thread count per server cum per threadpool, I can update it to `Total Threads in Thread Pool`. Let me know if that seems good.

Yes, The title looks good.

> > Below that we have Total Threads, Is it okay to remove the table from the dashboard if this is a redundant information which is already available ?
> 
> The `Total Threads` visualization displays the thread count per threadpool over a period of time. So user can see the trend of total number of threads (increasing or decreasing). [Link](https://github.com/elastic/integrations/blob/main/packages/websphere_application_server/data_stream/threadpool/fields/fields.yml#L28)

This is fine.

**Review by muthu-mps — APPROVED** [review]
LGTM!

**Pull request merged**
