### PR TITLE
[O11y][Azure Metrics] Migrate Compute VMs Overview dashboard to lens

### PR DESCRIPTION
**Pull request by rajvi-elastic**
### Urgency
- High

### Activity Type
- Enhancement

## What does this PR do?
- Manually migrate `Compute VMs Overview` visualizations to the lens in the current Kibana version `8.4.0` itself. 

- Statistics for `Compute VMs Overview` Lens migration:
## Migration stats
<html>
<body>

  | Before Migration |   |   | After Migration |   |  
-- | -- | -- | -- | -- | -- | --
  | Lens | Visualization | Old Input Controls | Lens | Visualization | New control panels
[Azure Metrics] Compute VMs Overview | 0 | 8 | 1 | 8 | 0 | 1

</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to the lens.
- [x] I have updated screenshots of the dashboard.
- [X] I have verified that the data counts are matching and panel aggregations are the same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.4.0 itself.

## Related issues

- Relates #7433

### CODE REVIEW

**Review by zmoog — APPROVED** [review]
nit: Is there a reason why the "VM Disk Reads [Azure Metrics]" is the only panel having the "[Azure Metrics]" suffix?

CleanShot 2023-08-25 at 06 07 04@2x

**Comment by rajvi-elastic** [comment]
> nit: Is there a reason why the "VM Disk Reads [Azure Metrics]" is the only panel having the "[Azure Metrics]" suffix?
> 

@zmoog I'm not sure why only one panel have the "[Azure Metrics]" suffix. We have just migrated the visualizations to the lens keeping titles as it is. But according to the best practices "[Azure Metrics]" suffix should be added to the all panel titles.

**Comment by agithomas** [comment]
> But according to the best practices "[Azure Metrics]" suffix should be added to the all panel titles.

Can you please help with the guidelines that highlight this as a best practice? I think, such a guideline must be revisited.

I agree with @zmoog  on removing the title.

**Comment by rajvi-elastic** [comment]
> Can you please help with the link to the guidelines that highlight this as a best practice? I think, such a guideline must be revisited.

Yes @agithomas. Here is the official elastic [doc](https://www.elastic.co/guide/en/integrations-developer/current/create-dashboards.html#_visualizations) for integration dashboard guidelines.

**Comment by zmoog** [comment]
Since this PR is ready, I would not hold it back more. 

I suggest merging this and opening a dedicated PR to track the need to align the integrations to the guidelines.

**Pull request merged**
