### PR TITLE
Run daily job with 8.8.

### PR DESCRIPTION
**Pull request by jsoriano**
Update the stack in the daily job from 8.7 to 8.8.

### CODE REVIEW

**Review by jen-huang — APPROVED** [review]

**Review by mrodm — COMMENTED** [review]
Trying to execute `elastic-package` with this version fails. Those images do not exist yet:
```
Error response from daemon: manifest for docker.elastic.co/kibana/kibana:8.8-SNAPSHOT not found: manifest unknown: manifest unknown
```

Command used: `elastic-package stack up -v -d --version 8.8-SNAPSHOT`

**Comment by jsoriano** [comment]
> Trying to execute `elastic-package` with this version fails. Those images do not exist yet:
> 
> ```
> Error response from daemon: manifest for docker.elastic.co/kibana/kibana:8.8-SNAPSHOT not found: manifest unknown: manifest unknown
> ```
> 
> Command used: `elastic-package stack up -v -d --version 8.8-SNAPSHOT`

Oops, you are right, I tried locally with `elastic-package stack update -v 8.8-SNAPSHOT`. It seems that with `8.8.0-SNAPSHOT` it works, I will change to this version.

**Review by mrodm — APPROVED** [review]
LGTM!

When is it created the docker images for 8.8-SNAPSHOT ? If we keep this `stackVersion` as 8.8.0-SNAPSHOT, it should be then updated for 8.8.1-SNAPSHOT and others, shouldn't it ?

**Review by mrodm — APPROVED** [review]

**Pull request merged**
