### PR TITLE
Upgrade k8s version to v1.23.0

### PR DESCRIPTION
**Pull request by ChrsMark**
## What does this PR do?

This PR upgrades k8s version for the CI to a latest one (v1.23.0)

### CODE REVIEW

**Review by mtojek — APPROVED** [review]
Please wait for the CI to finish.

**Comment by ChrsMark** [comment]
@mtojek any ides about the CI failure? It seems to be an issue in GCP integration.

**Comment by mtojek** [comment]
I checked internal logs for GCP in the special bucket:

```
[35mgcppubsub-vpcflow_1   |[0m {"level":"debug","ts":"2021-12-22T11:17:42.223Z","caller":"command/log.go:74","msg":"Sending log line.","address":"gcppubsub-emulator:8681","log":"/sample_logs/vpcflow.log","line_number":33}
[35mgcppubsub-vpcflow_1   |[0m {"level":"debug","ts":"2021-12-22T11:17:42.246Z","caller":"command/log.go:74","msg":"Sending log line.","address":"gcppubsub-emulator:8681","log":"/sample_logs/vpcflow.log","line_number":34}
[35mgcppubsub-vpcflow_1   |[0m {"level":"debug","ts":"2021-12-22T11:17:42.250Z","caller":"command/log.go:74","msg":"Sending log line.","address":"gcppubsub-emulator:8681","log":"/sample_logs/vpcflow.log","line_number":35}
[35mgcppubsub-vpcflow_1   |[0m {"level":"debug","ts":"2021-12-22T11:17:42.254Z","caller":"command/log.go:74","msg":"Sending log line.","address":"gcppubsub-emulator:8681","log":"/sample_logs/vpcflow.log","line_number":36}
[33mgcppubsub-emulator_1  |[0m [pubsub] Dec 22, 2021 11:17:41 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[33mgcppubsub-emulator_1  |[0m [pubsub] INFO: Detected HTTP/2 connection.
[33mgcppubsub-emulator_1  |[0m [pubsub] Dec 22, 2021 11:17:42 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[33mgcppubsub-emulator_1  |[0m [pubsub] INFO: Detected HTTP/2 connection.
[33mgcppubsub-emulator_1  |[0m [pubsub] Dec 22, 2021 11:17:42 AM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
[33mgcppubsub-emulator_1  |[0m [pubsub] WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
[33mgcppubsub-emulator_1  |[0m [pubsub] java.io.IOException: Connection reset by peer
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[33mgcppubsub-emulator_1  |[0m [pubsub] 	at java.base/java.lang.Thread.run(Thread.java:829)
[33mgcppubsub-emulator_1  |[0m [pubsub] 
[35mgcppubsub-vpcflow_1   |[0m {"level":"debug","ts":"2021-12-22T11:17:42.258Z","caller":"command/log.go:74","msg":"Sending log line.","address":"gcppubsub-emulator:8681","log":"/sample_logs/vpcflow.log","line_number":37}
[35mgcppubsub-vpcflow_1   |[0m {"level":"debug","ts":"2021-12-22T11:17:42.262Z","caller":"command/log.go:74","msg":"Sending log line.","address":"gcppubsub-emulator:8681","log":"/sample_logs/vpcflow.log","line_number":38}
```

It doesn't look like a related bug, so I would say we can safely merge this change. AFAIR `kind` is used by the Kubernetes integration only. Would you like me to merge this PR?

**Comment by ChrsMark** [comment]
Thanks for checking, I will proceed with the merge.

**Pull request merged**
