### PR TITLE
[hashicorp_vault] Test with Vault 1.11.2

### LINKED ISSUE #4035: [Hashicorp Vault] Support for Vault v1.11
Our integration currently supports up to Vault v1.8 (as that's what we test against). Vault is now up to v1.11 and after some discussions with Hashicorp and Vault users, we should aim to support up to v1.11

There are no significant changes to Vault logging between 1.8 and 1.11, so it will likely just require a smoke test. Assuming the test with our integration is successful, we'll need to ensure [our documentation](https://docs.elastic.co/integrations/hashicorp_vault) is updated to reflect support for versions up to 1.11.

### PR DESCRIPTION
**Pull request by andrewkroh**
## What does this PR do?

Update tests to use Hashicorp Vault 1.11.2.
Update mappings for Vault 1.11 audit data schema.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #4035

## Logs

1.11 event with new fields.

```
{
  "agent": {
    "name": "docker-fleet-agent",
    "id": "03109bfa-7015-46bd-9433-3879357210cd",
    "type": "filebeat",
    "ephemeral_id": "c6777a07-0ee5-4efc-b9d5-efe38e545ab5",
    "version": "8.3.2"
  },
  "hashicorp_vault": {
    "audit": {
      "request": {
        "client_token": "hmac-sha256:9670f60ae136c9fb5ec99472291977aa9c61ad4d49829cf4dffabc21d5a05483",
        "path": "auth/token/lookup-self",
        "namespace": {
          "id": "root"
        },
        "remote_port": 46026,
        "id": "6a2dae54-47cc-80ab-43d5-aaa60bc95745",
        "mount_type": "token",
        "remote_address": "172.30.0.4",
        "client_token_accessor": "hmac-sha256:dd2e0395c657ad5a10dfd832e841b0f1d91e0e95911fa58d6ee7fe7e622912c5",
        "operation": "read",
        "mount_accessor": "auth_token_df374312",
        "client_id": "0DHqvq2D77kL2/JTPSZkTMJbkFVmUu0TzMi0jiXcFy8="
      },
      "auth": {
        "token_policies": [
          "root"
        ],
        "client_token": "hmac-sha256:9670f60ae136c9fb5ec99472291977aa9c61ad4d49829cf4dffabc21d5a05483",
        "token_issue_time": "2022-08-18T17:01:47Z",
        "accessor": "hmac-sha256:dd2e0395c657ad5a10dfd832e841b0f1d91e0e95911fa58d6ee7fe7e622912c5",
        "policies": [
          "root"
        ],
        "policy_results": {
          "granting_policies": [
            {
              "namespace_id": "root",
              "name": "root",
              "type": "acl"
            }
          ],
          "allowed": true
        },
        "display_name": "token",
        "token_type": "service"
      },
      "response": {
        "data": {
          "creation_time": 1660842107,
          "creation_ttl": 0,
          "accessor": "hmac-sha256:dd2e0395c657ad5a10dfd832e841b0f1d91e0e95911fa58d6ee7fe7e622912c5",
          "policies": [
            "hmac-sha256:2d6e645cbe7182171f0dc8dafb5959ff1a9f28ffbebf505d98ede04f7360ba92"
          ],
          "expire_time": null,
          "num_uses": 0,
          "display_name": "hmac-sha256:976ba670270142f2507af8db8a08ab80e39fb8e59dd990cd97a94744597d7ae2",
          "entity_id": "hmac-sha256:508ac971ef30d807928dca23750b3dcf6b0b2e251a06b7ca636c4d111877d5c2",
          "orphan": false,
          "type": "hmac-sha256:f00410e9496c6521003b940705e6c8f076614212de1bbbe9867555871d65629e",
          "ttl": 0,
          "explicit_max_ttl": 0,
          "path": "hmac-sha256:80821fa705df690f161f9b5e041f7f5460c827cad881c50b6caafc5f54bbb2ea",
          "meta": null,
          "renewable": false,
          "id": "hmac-sha256:9670f60ae136c9fb5ec99472291977aa9c61ad4d49829cf4dffabc21d5a05483",
          "issue_time": "2022-08-18T17:01:47.694373174Z"
        },
        "mount_type": "token",
        "mount_accessor": "auth_token_df374312"
      },
      "type": "response"
    }
  },
  "log": {
    "file": {
      "path": "/tmp/service_logs/vault/audit.json"
    },
    "offset": 22102
  },
  "elastic_agent": {
    "id": "03109bfa-7015-46bd-9433-3879357210cd",
    "version": "8.3.2",
    "snapshot": false
  },
  "source": {
    "port": 46026,
    "ip": "172.30.0.4"
  },
  "tags": [
    "preserve_original_event",
    "hashicorp-vault-audit"
  ],
  "input": {
    "type": "log"
  },
  "@timestamp": "2022-08-18T17:01:47.754Z",
  "ecs": {
    "version": "8.4.0"
  },
  "related": {
    "ip": [
      "172.30.0.4"
    ]
  },
  "data_stream": {
    "namespace": "ep",
    "type": "logs",
    "dataset": "hashicorp_vault.audit"
  },
  "host": {
    "hostname": "docker-fleet-agent",
    "os": {
      "kernel": "5.10.76-linuxkit",
      "codename": "focal",
      "name": "Ubuntu",
      "family": "debian",
      "type": "linux",
      "version": "20.04.4 LTS (Focal Fossa)",
      "platform": "ubuntu"
    },
    "containerized": false,
    "ip": [
      "172.23.0.7"
    ],
    "name": "docker-fleet-agent",
    "mac": [
      "02:42:ac:17:00:07"
    ],
    "architecture": "x86_64"
  },
  "event": {
    "agent_id_status": "verified",
    "ingested": "2022-08-18T17:02:23Z",
    "original": "{\"time\":\"2022-08-18T17:01:47.754081924Z\",\"type\":\"response\",\"auth\":{\"client_token\":\"hmac-sha256:9670f60ae136c9fb5ec99472291977aa9c61ad4d49829cf4dffabc21d5a05483\",\"accessor\":\"hmac-sha256:dd2e0395c657ad5a10dfd832e841b0f1d91e0e95911fa58d6ee7fe7e622912c5\",\"display_name\":\"token\",\"policies\":[\"root\"],\"token_policies\":[\"root\"],\"policy_results\":{\"allowed\":true,\"granting_policies\":[{\"name\":\"root\",\"namespace_id\":\"root\",\"type\":\"acl\"}]},\"token_type\":\"service\",\"token_issue_time\":\"2022-08-18T17:01:47Z\"},\"request\":{\"id\":\"6a2dae54-47cc-80ab-43d5-aaa60bc95745\",\"client_id\":\"0DHqvq2D77kL2/JTPSZkTMJbkFVmUu0TzMi0jiXcFy8=\",\"operation\":\"read\",\"mount_type\":\"token\",\"mount_accessor\":\"auth_token_df374312\",\"client_token\":\"hmac-sha256:9670f60ae136c9fb5ec99472291977aa9c61ad4d49829cf4dffabc21d5a05483\",\"client_token_accessor\":\"hmac-sha256:dd2e0395c657ad5a10dfd832e841b0f1d91e0e95911fa58d6ee7fe7e622912c5\",\"namespace\":{\"id\":\"root\"},\"path\":\"auth/token/lookup-self\",\"remote_address\":\"172.30.0.4\",\"remote_port\":46026},\"response\":{\"mount_type\":\"token\",\"mount_accessor\":\"auth_token_df374312\",\"data\":{\"accessor\":\"hmac-sha256:dd2e0395c657ad5a10dfd832e841b0f1d91e0e95911fa58d6ee7fe7e622912c5\",\"creation_time\":1660842107,\"creation_ttl\":0,\"display_name\":\"hmac-sha256:976ba670270142f2507af8db8a08ab80e39fb8e59dd990cd97a94744597d7ae2\",\"entity_id\":\"hmac-sha256:508ac971ef30d807928dca23750b3dcf6b0b2e251a06b7ca636c4d111877d5c2\",\"expire_time\":null,\"explicit_max_ttl\":0,\"id\":\"hmac-sha256:9670f60ae136c9fb5ec99472291977aa9c61ad4d49829cf4dffabc21d5a05483\",\"issue_time\":\"2022-08-18T17:01:47.694373174Z\",\"meta\":null,\"num_uses\":0,\"orphan\":false,\"path\":\"hmac-sha256:80821fa705df690f161f9b5e041f7f5460c827cad881c50b6caafc5f54bbb2ea\",\"policies\":[\"hmac-sha256:2d6e645cbe7182171f0dc8dafb5959ff1a9f28ffbebf505d98ede04f7360ba92\"],\"renewable\":false,\"ttl\":0,\"type\":\"hmac-sha256:f00410e9496c6521003b940705e6c8f076614212de1bbbe9867555871d65629e\"}}}",
    "kind": "event",
    "action": "read",
    "id": "6a2dae54-47cc-80ab-43d5-aaa60bc95745",
    "category": [
      "authentication"
    ],
    "type": [
      "access"
    ],
    "dataset": "hashicorp_vault.audit",
    "outcome": "success"
  }
}
```

### CODE REVIEW

**Review by efd6 — COMMENTED** [review]
From looking in the Go definitions for the [types that serialise these fields](https://pkg.go.dev/github.com/hashicorp/vault/audit), it looks like there are some missing fields.
- `audit.auth.request.replication_cluster`: `keyword`
- `audit.auth.request.client_certification_serial_number`: `keyword`
- `audit.auth.entity_created`: `boolean`

`audit.response.auth.policies` is missing a type in the existing file, it looks like it should be `keyword`.

**Comment by andrewkroh** [comment]
@efd6 Thank you for spotting those fields. I was mostly programming to the errors (and checking the Go types to make sure I had the type correct), but the generated logs in the system tests didn't have all the fields.

**Review by efd6 — APPROVED** [review]

**Comment by jamiehynds** [comment]
@andrewkroh am I ok to communicate to Hashicorp that we can support v1.11 (when the package is promoted)? 

Can we also update on integration docs to reflect support for v1.11?

**Comment by andrewkroh** [comment]
> am I ok to communicate to Hashicorp that we can support v1.11 (when the package is promoted)?

Yes. 👍 

> Can we also update on integration docs to reflect support for v1.11?

This change did update docs contained in the package to mention 1.11.

**Pull request merged**
