### PR TITLE
[O11y][Oracle] Migrate `Tablespace` dashboard visualizations to lens in kibana 8.6.0

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

- Migrate visualizations to lens for Oracle integration package

- Statistics for **Oracle** Lens migration:

<html>
<body>
<google-sheets-html-origin>

Oracle Dashboards | Before Migration |   | After Migration |   |
-- | -- | -- | -- | -- |
  | Lens | Visualization | Lens | Visualization
[Metrics Oracle] Tablespace | 0 | 4 | 4 | 0

</body>
</html>

## Checklist

- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that panels are populated with data.
- [x] I have verified that panels are not distorted after being migrated to lens.
- [x] I have updated screenshots of dashboard.
- [x] I have verified that data count are matching and panel aggregations are same as before.

## Author's checklist

- [x] Migrated panels should be removed from visualization folder.
- [x] Migrated visualizations are populating in Kibana version `8.6.0`. 

## Related issues

- Relates 
  - #5221 
  - #5753

## Issues Identified
- Convert data format for Tablespace and Overview dashboard visualizations from number to bytes
   https://github.com/elastic/integrations/issues/5761
  - **Impact** : [ Severity : Enhancement ]

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM, Approved!

**Review by agithomas — COMMENTED** [review]
1.  I think there exist some difference in the stacked bar chart. Please re-check.
2 I understand that in the old view, the Y-axis is not converting the bytes to MB / GB. Please see if you can change this .

**Comment by harnish-elastic** [comment]
> 1. I think there exist some difference in the stacked bar chart. Please re-check.

I have re-checked the bar chart with populating the data in both dashboards (Before migrated and after migrated), and both after migrated bar stacked charts are behaving same with before migrated bar stacked chart. Let me know if you have find any difference.

>    2 I understand that in the old view, the Y-axis is not converting the bytes to MB / GB. Please see if you can change this .

Sure, @agithomas, we will enhance this change in this PR itself. Also we have created one enhancement [issue](https://github.com/elastic/integrations/issues/5761) for the same to keep track of this thing.

**Review by agithomas — COMMENTED** [review]
New representation

image

The view presents, the avg data file size. The representation shows, the file size suddenly is 800MB approx around 3:15pm and becomes  zero at 9:15pm. Compare with the image below, it shows a consistent size usage through out.

Not sure , the problem is with graph or with the data ingestion. 

image

**Comment by agithomas** [comment]
> New representation
> 
> image
> 
> The view presents, the avg data file size. The representation shows, the file size suddenly is 800MB approx around 3:15pm and becomes zero at 9:15pm. Compare with the image below, it shows a consistent size usage through out.
> 
> Not sure , the problem is with graph or with the data ingestion.
> 
> image

Same problem for Tablespace Total size vis panel

**Comment by harnish-elastic** [comment]
> New representation
> 
> image
> 
> The view presents, the avg data file size. The representation shows, the file size suddenly is 800MB approx around 3:15pm and becomes zero at 9:15pm. Compare with the image below, it shows a consistent size usage through out.
> 
> Not sure , the problem is with graph or with the data ingestion.
> 
> image



> > New representation
> > image
> > The view presents, the avg data file size. The representation shows, the file size suddenly is 800MB approx around 3:15pm and becomes zero at 9:15pm. Compare with the image below, it shows a consistent size usage through out.
> > Not sure , the problem is with graph or with the data ingestion.
> > image
> 
> Same problem for Tablespace Total size vis panel

@agithomas, I think the issue is not related to chart and data ingestions as well. The data values are same for all the breakdown fields hence it looked like that. I have changed the mocked data values. Please refer the below screenshot.

image

**Comment by agithomas** [comment]
> > New representation
> > image
> > The view presents, the avg data file size. The representation shows, the file size suddenly is 800MB approx around 3:15pm and becomes zero at 9:15pm. Compare with the image below, it shows a consistent size usage through out.
> > Not sure , the problem is with graph or with the data ingestion.
> > image
> 
> > > New representation
> > > image
> > > The view presents, the avg data file size. The representation shows, the file size suddenly is 800MB approx around 3:15pm and becomes zero at 9:15pm. Compare with the image below, it shows a consistent size usage through out.
> > > Not sure , the problem is with graph or with the data ingestion.
> > > image
> > 
> > 
> > Same problem for Tablespace Total size vis panel
> 
> @agithomas, I think the issue is not related to chart and data ingestions as well. The data values are same for all the breakdown fields hence it looked like that. I have changed the mocked data values. Please refer the below screenshot.
> 
> image

Looks good, please update the screenshot file in the PR

**Comment by harnish-elastic** [comment]
@agithomas Updated the PR with requested changes. Thanks!

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
