### PR TITLE
[GCP] Add various dashboards

### PR DESCRIPTION
**Pull request by endorama**
## What does this PR do?

Some dashboards have not been migrated during the migration from `gcp` beat module to the integration package.

This PR adds the missing ones, updating them to the latest dashboard development guidelines.

Updates:
- GKE overview dashboard
- PubSub metrics overview dashboard
- Audit events overview dashboard
- Storage metrics overview dashboard

GCP package is bumped to 2.17.0.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

- Start Elastic cluster with `elastic-package stack up --version 8.6.1`
- Collect data for GKE, PubSub and Storage metrics by adding a policy with appropriate credentials
- Collect data for Audit Logs; default policy information should be enough, as the required collection infrastructure is already in place
- verify dashboard show data and filters work as expected

## Related issues

-

### GCP Audit logs
Screenshot 2023-02-13 at 17-59-59 Elastic

### GCP GKE
Screenshot 2023-02-13 at 18-04-30 Elastic

### GCP Storage
Screenshot 2023-02-13 at 18-04-35 Dashboards - Elastic

### GCP PubSub
Screenshot 2023-02-13 at 18-04-39 Elastic

### CODE REVIEW

**Comment by endorama** [comment]
Moving this back to draft as I exported some dashboard using the next development version.

**Comment by andrewkroh** [comment]
Please attach some screenshots when these are ready.

**Comment by endorama** [comment]
@andrewkroh I tried to update visualisations in the Audit dashboard to use Lens, but I've not been able to reproduce the same dashboard.

Before:
gcp audit before

After:
gcp audit after

In particular "Audit Events Outcome over time" panel does not show "unknown" documents (not sure why, I selected the "display docs without value"). Is this a blocker?

**Comment by andrewkroh** [comment]
I think this is fine. It used to show `[unknown]` when the field was missing. And now it's just showing "(missing value)". So I think that is fine.

Old settings:

Screen Shot 2023-01-23 at 14 41 34

**Comment by endorama** [comment]
@andrewkroh I've been able to reproduce the behaviour.

Also I updated the description with screenshots and updated the PR remove coflicts. Moveing to Ready for review

**Review by andrewkroh — APPROVED** [review]

**Review by dmathieu — APPROVED** [review]
I've been able to review all dashboards, except the audit log one (we don't know why yet, but I'm not getting data).
That dashboard has already been approved by security though. So stamping this PR.

**Pull request merged**
