### PR TITLE
[Elastic Agent] Set dimension fields for metrics data streams

### PR DESCRIPTION
**Pull request by constanca-m**
## What does this PR do?

Set dimension fields for TSDB migration. All metrics data streams have `agent.id` as dimension. Most of them have `service.address` set as dimension as well, except for `elastic_agent` and `filebeat`. See more details on the next section.

## Details

To enable TSDB we need some fields set as dimension. The combination of the dimension fields + the timestamp must be unique. Otherwise, documents will be overwritten. Check [this](https://github.com/elastic/elasticsearch-adrs/blob/master/analytics/tsdb/tsdb-design.md) for more information.

All data streams affected by this PR were tested using https://github.com/elastic/TSDB-migration-test-kit.

Metrics data streams:
- [x] APM server metrics
  - An elastic agent can only have one policy, and a policy can only have one APM Server integration. Because of this, `agent.id` needs to be set as dimension. Additionally, one agent can send more than one document per timestamp, with the difference being `service.address`. This field is also set as dimension.
  - Tested with:
    - Two elastic agents using the same policy with APM Server integration.

- [x] Auditbeat metrics
  - The agent policy can have more than 1 Auditd Manager integration, but that does not cause any difference in the number of documents. `agent.id` is set as dimension, as well as `service.address`, since each agent can be associated with more than one for the same timestamp.
  - Tested with:
    - Two elastic agents using the same policy with two Auditd Manager integrations.

- [x] Cloudbeat metrics
  - A policy can only have one Security Posture Management integration. `agent.id` is set as dimension. Each agent can send more than one document per timestamp with the difference being `service.address`. Because of that, this field is also set as dimension.
  - Tested with:
    - Two elastic agents using a policy with one Security Posture Management integration. 

- [x] Elastic agent metrics
  - `agent.id` is set as dimension to distinguish between agents. Additionally, each agent can send more than one document per timestamp. The differences are `elastic_agent.process`. Example: `(kind-control-plane, filebeat)` and `(kind-control-plane, metricbeat)` for the same timestamp.
    - `elastic_agent.process` no longer has the option `ignore_above: 1024` since that is not compatible with dimension fields.
  - Tested with:
    - 2 elastic agents.

- [ ] ~Endpoint security metrics~: not possible, see https://github.com/elastic/elastic-agent/issues/1944.

- [x] Filebeat input metrics:
  - `agent.id` is enough as a dimension.

- [x] Filebeat metrics
  - Each agent only sends one document per timestamp. `agent.id` is the only field set as dimension.
  - Tested with:
    - 3 agents on local deployment, 2 of them using the same policy.

- [x] Fleet server metrics:
  - An agent is only connected to one fleet server. Because of this, `agent.id` needs to be set as dimension. Since an `agent.id` can be connected to multiple `service.address` (for example, `http://unix/state` and `http://unix/stats`), that field is set as dimension as well.
  - Tested with:
    1. One elastic agent with two fleet server integrations on its policy;
    2. At the same time, two more elastic agent connected to a different fleet server.

- [x] Heartbeat metrics
    - `agent.id` is needed to differentiate between the agents. Additionally, `service.address` is added as dimension since one agent can send more than one document for each address at the same time.
    - Tested with:
      - 2 agents on local deployment and 4 monitors.

- [x] Metricbeat metrics
  - Each agent only sends one document per timestamp for each `service.address`. So both fields are set as dimension.
  - Tested with:
    - 2 agents on local deployment.

- [x] Osquerybeat metrics
  - A policy can only have one Osquery Manager integration. `agent.id` is set as dimension. Each agent can send more than one document at the same time, with the difference being `service.address`. For that reason, this field is also set as dimension.
  - Tested with:
    - 2 elastic agents using the same policy with Osquery Manager integration.

- [x] Packetbeat metrics
  - A policy can only have one Network Packet Capture integration. `agent.id` is set as dimension. Since one agent can send documents at the same time for difference `service.address`, that field is also set as dimension.
  - Tested with:
    - 2 elastic agents using the same policy with Network Packet Capture integration.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

Relates to https://github.com/elastic/integrations/issues/6938.

### CODE REVIEW

**Comment by cmacknz** [comment]
> Endpoint security metrics: to do.

You won't get endpoint security metrics, endpoint runs as a protected process and the way we collect metrics today doesn't work in this situation. https://github.com/elastic/elastic-agent/issues/1944

**Comment by cmacknz** [comment]
>  Filebeat input metrics: to do.

What input are you trying to test? The security external integrations team implemented most of these, @taylor-swanson might be able to help you get this figured out.

**Comment by cmacknz** [comment]
The plan is to fix it eventually, which is why we haven't removed it.

**Comment by joshdover** [comment]
What's the reason that we need/want `service.address` to be a dimensions if `agent.id` is already known to be unique?

**Comment by constanca-m** [comment]
> What's the reason that we need/want `service.address` to be a dimension if `agent.id` is already known to be unique?

Sometimes we receive documents at the same timestamp for the same agent id, but the address is different. If that happens, then we will loose data, that is why `service.address` needs to be set as dimension. @joshdover

**Review by pierrehilbert — APPROVED** [review]
LGTM

**Pull request merged**
