### PR TITLE
Use report command from elastic-package

### PR DESCRIPTION
**Pull request by marc-gr**
Uses the command from elastic-package to generate the benchmark reports

### CODE REVIEW

**Review by jsoriano — COMMENTED** [review]
Nice, thanks!

**Review by jsoriano — APPROVED** [review]

**Comment by jsoriano** [comment]
Some failures in CI are probably caused by https://github.com/elastic/elastic-package/pull/1042.

**Review by v1v — APPROVED** [review]
LGTM, knowing that my knowledge about Golang is not that much 🙏

**Pull request merged**
