### PR TITLE
[O11y][Oracle WebLogic] Lens migration for visualizations to kibana version 8.4.0

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

- Migrate visualizations to lens for Oracle WebLogic integration package

- Statistics for **Oracle WebLogic** Lens migration:

<html>
<body>
<google-sheets-html-origin>

Oracle WebLogic dashboards  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics Oracle WebLogic] Deployed Application | 5 | 2 | 7 | 0
[Logs Oracle WebLogic] Logs Overview | 3 | 8 | 7 | 4
[Metrics Oracle WebLogic] ThreadPool | 8 | 1 | 9 | 0
  | 16 | 11 | 23 | 4

</body>
</html>

- 4 visualizations are `markdown` visualizations which won't be converted to lens.

- Updated `TagCloud` visualizations to the `horizontal bar` chart. For that, changed the visualization name from `Request Endpoint [Logs Oracle WebLogic]` to `Top values of Request Endpoint [Logs Oracle WebLogic]`

## Checklist

- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that panels are populated with data.
- [x] I have verified that panels are not distorted after being migrated to lens.
- [x] I have updated screenshots of dashboard.
- [x] I have verified that data count are matching and panel aggregations are same as before.

## Author's checklist

- [x] Migrated panels should be removed from visualization folder.
- [x] Migrated visualizations are populating in current Kibana version 8.4.0 itself. 

## Related issues

- Relates #5221

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Review by agithomas — DISMISSED** [review]
LGTM1

**Comment by harnish-elastic** [comment]
> Any reason why `coreMigrationVersion` and `migrationVersion.lens `are different?. Are export dashboard method consistently used and no manual overriding done?

We are using `elastic-package export dashboards` command while exporting the dashboards. We are not manually overriding it. We are not sure of above two fields difference.

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
