### PR TITLE
[Apache Tomcat] Add integration package with localhost data stream 

### PR DESCRIPTION
**Pull request by niraj-elastic**
- Enhancement

## What does this PR do?

- Added 1 data stream (Localhost Logs).
- Added data collection logic for the data streams.
- Added the ingest pipeline for the data streams.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yaml files.
- Added dashboards and visualizations.
- Added system test cases for the data stream.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/apache_tomcat) directory.
- Run the following command to run tests. elastic-package test

## Meta issue
- #5200

## Related PRs
- #5424
- #6003
- #5926
- #5883

### CODE REVIEW

**Review by harnish-elastic — APPROVED** [review]
LGTM!

**Comment by muthu-mps** [comment]
@SubhrataK - Please take a look at the dashboard.

**Comment by niraj-elastic** [comment]
@ishleenk17 currently we are facing one issue with timestamp in which we see logs in incorrect time window in kibana discover page. We are looking in to it and fix it soon.

**Review by muthu-mps — APPROVED** [review]
looks good!

**Review by harnish-elastic — APPROVED** [review]

**Pull request merged**
