### PR TITLE
Enhancement: Add visualizations for data tier capacity

### PR DESCRIPTION
**Pull request by cp-elastic**
## Proposed commit message
Add visualizations for data tier capacity

## Why
Based on feedback from my customers, these visualizations have been incredibly helpful for capacity planning and adjusting ILM policies. 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Screenshots

capacity overview

### CODE REVIEW

**Comment by consulthys** [comment]
@cp-elastic thank you for this contribution!
Can you please enumerate the required steps to test this PR?

**Comment by cp-elastic** [comment]
@consulthys 
I'm not sure what the process is to build this integration locally for development. I exported the dashboard as .ndjson for testing on a ESS deployment.

**Comment by cp-elastic** [comment]
Updated the dashboards by exporting them [properly](https://www.elastic.co/guide/en/integrations-developer/current/create-dashboards.html). Tested against a fresh deployment, and is working as expected out of the box.

**Review by consulthys — APPROVED** [review]
LGT Stack Monitoring
PS: sorry for the delay

**Pull request merged**
