### PR TITLE
[AWS] [Fargate] Migrate to GA

### PR DESCRIPTION
**Pull request by lucian-ioan**
### Urgency
- Normal

### Activity Type
- Enhancement

## What does this PR do?

Migrates AWS Fargate to GA.

Set up multiple clusters using both 8.8 and 8.9 stack versions.

While setting up the integration, everything works as expected besides the first visualization in the dashboard:
awsfargate_720

`awsfargate.task_stats.cpu.total.norm.pct` is being fetched and even used in another visualization which leads me to believe the issue is the visualization type used. 

Other metrics used in the same visualization under `Metrics` also have the same behaviour.

The issue is from an ES bug: https://github.com/elastic/elasticsearch/issues/97394.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [x]  Automated Tests / Manual Tests guidelines
- [x]  Timeduration guidelines
- [x]  Field mapping guidelines
- [x]  Kibana dashboard guidelines
- [x]  TSDB enablementt
- [x]  SDHs check
- [x]  Enhacement Requests check
- [x]  Publish GA checklist summary
- [x]  Document quality check

- [x] Documented the findings [here](https://docs.google.com/document/d/11zl6KYsobwsPEGlbTQZWGlN9cznqAHe4eDi1UgiaDzI/edit).

## How to test this PR locally

[Blog post](https://www.elastic.co/blog/elastic-agent-monitor-ecs-aws-fargate-elastic-observability?utm_source=GaggleAMP-Elastic&utm_medium=LinkedIn%20(GaggleAMP)&utm_campaign=none%20(GaggleAMP)&utm_content=in-this-step-by-step-guide-youll-learn-how-to-install-the-elas-4077423) about setting up the integration.

## Related issues

- Closes https://github.com/elastic/obs-infraobs-team/issues/1104

### CODE REVIEW

**Comment by lucian-ioan** [comment]
Currently tied to an [ES bug](https://github.com/elastic/elasticsearch/issues/97394), waiting for the fix before moving it to GA.

**Comment by lalit-satapathy** [comment]
>The issue is from an ES bug: https://github.com/elastic/elasticsearch/issues/97394.

Can we target 8.10 validation that the [issue](https://github.com/elastic/elasticsearch/issues/97394#issuecomment-1685766058) is fixed?

**Review by zmoog — CHANGES_REQUESTED** [review]
We need to bump the Kibana requirements to 8.10 to get the fix, right @lalit-satapathy?

**Comment by lalit-satapathy** [comment]
> We need to bump the Kibana requirements to 8.10 to get the fix, right @lalit-satapathy?

Once verified, for GA release, we can choose to update to stack version 8.10. That will ensure, the GA release of this package, does not have a broken dashboard.

**Comment by agithomas** [comment]
Please hold this PR from proceeding as certain critical bugs are recently discovered.

**Comment by agithomas** [comment]
The issue mentioned in the description of this issue regarding the broken dashboard is no longer present. Tested using 8.10.1.

Newly discovered issues will be shortly tagged to this issue. 

image

**Comment by lucian-ioan** [comment]
Fix for the additional issue is being resolved in: https://github.com/elastic/integrations/pull/8254.

Once that is merged, AWS Fargate can be migrated to GA.

**Comment by mrodm** [comment]
Hi @lucian-ioan, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

**Comment by agithomas** [comment]
@lucian-ioan , with all the blocked issues resolved, can we have this change merged - to make  Fargate GA ?

**Comment by lucian-ioan** [comment]
@agithomas there was a new minor version (8.11.4) which contains beats changes instead of 8.12.0. 

It was released late last week, testing the changes now. Expecting to be done later today or tomorrow.

**Comment by lucian-ioan** [comment]
Final code changes are ready for review in: https://github.com/elastic/integrations/pull/8254.

**Comment by lucian-ioan** [comment]
Code PR is merged. Just need [docs update](https://github.com/elastic/integrations/pull/9130) merged before promoting to GA.

**Comment by muthu-mps** [comment]
@lucian-ioan - Can we update the Author checklist for GA migration? Reference can be found https://github.com/elastic/integrations/pull/8955.

**Comment by lucian-ioan** [comment]
@muthu-mps , I checked everything from the checklist mentioned.
awsfargate-integration-overview

**Review by muthu-mps — APPROVED** [review]

**Review by zmoog — APPROVED** [review]
LGTM!

**Pull request merged**
