### PR TITLE
[AWS] [API Gateway] Split metrics dashboard by API type and filter documents visualized

### LINKED ISSUE #7837: Metrics dashboard approach for AWS API Gateway when Detailed Metrics is enabled
Ingesting data for AWS API Gateway while making requests to a REST API, the following behavior can be observed:
4_documents

We get 4 documents, each with varying dimensions. This is similar to the `ApiGateway` CloudWatch metric groupings for REST APIs:
- Across All APIs (no dimensions, only Count and Data Processed metrics)
- By Api Name (ApiName dimension)
- By Stage (ApiName, Stage dimensions)
- By Method (ApiName, Stage, Resource, Method dimensions)

If the `Detailed metrics` option is set to Inactive in the Logs and tracing settings for the API Stage, then only 3 documents will be present (as that option enables metrics tracing for each specific method):
3_documents

Since we can't guarantee the end user will enable `Detailed metrics`, we can't just consider only the documents will all dimensions. 

With Detailed Metrics being an an opt-in feature rather than the default setting, one approach to ensure consistent data on the dashboard, whether Detailed Metrics is on or off, is to exclude these additional documents using dimension filters.

### PR DESCRIPTION
**Pull request by lucian-ioan**
### Urgency
- High

### Activity Type
- Bugfix

## What does this PR do?

1. Split the existing API Gateway metrics dashboard into 3 dashboards by API type.
2. Add additional metric counters and navigation panels.
3. Change visualization types to enhance clarity.
4. Filter data so only documents with `API Identifier` and `Stage` dimensions are considered. This is necessary due to additional documents being fetched based on API settings (ex. Detailed Metrics) which will result in inaccurate metrics (ex. `Count`).
5. Additional metric filters within the HTTP/WebSocket dashboards to prevent the redundant display of API IDs in both dashboards. (`ApiId` dimension is shared between HTTP and WebSocket)

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [x] Remove [Metrics AWS] API Gateway Overview dashboard.
- [x] Export all dashboards to 8.9
- [x] Check all data is 1:1 with CloudWatch metric groupings (`By Stage` - REST and `ApiId, Stage` - HTTP/WebSocket).

## Related issues

- Closes #7837

## Screenshots

REST:
REST_dashboard_8 9 0

HTTP:
HTTP_dashboard_8 9 0

WebSocket:
WebSocket_dashboard_8 9 0

Example CloudWatch:
CloudWatch_REST_count

Example REST:
Dashboard_REST_screenshot

### CODE REVIEW

**Review by kaiyan-sheng — APPROVED** [review]
Overall it looks good to me. Not sure if users will like the separated dashboards for different kinds of API gateway. But we can always adjust later if we get feedback. 
Can we add a screenshot (not sure if multiple screenshots is allowed) into documentation please? Thanks!

**Review by zmoog — APPROVED** [review]
LGTM.

I believe separating the single dashboard into multiple ones per type is fair. I don't have data to back this up, but in my experience as an application developer, I usually check one API at a time;.

**Review by drewdaemon — APPROVED** [review]
This better follows dashboard best practices. And, when the [links panel arrives](https://github.com/elastic/kibana/pull/166896), this will be an excellent use case for it.

With the new links panel, navigation between the views is much more performant. The dashboard app itself doesn't have to reload, minimizing the work it takes to show another API type.

**Comment by zmoog** [comment]
> This better follows dashboard best practices.

@drewdaemon, what's your recommended reading list to know more about dashboard best practices?

**Comment by drewdaemon** [comment]
@zmoog unfortunately fragmentation is a problem right now. My team created a document. Some designers created a document. Someone from Security solution created a document. Looks like someone from your team tried to collect ideas into a [markdown file](https://github.com/elastic/integrations/blob/main/docs/dashboard_guidelines.md).

I agree with everything I saw in the markdown file, so you could start there. I can send you our team's document as well. But, basically, we probably need to do some unification.

**Pull request merged**
