### PR TITLE
[O11y][Redis] Migrate `Logs Overview` dashboard visualizations to lens in kibana 8.3.0

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

- Migrate visualizations to lens for Redis integration package

- Statistics for **Redis** Lens migration:

<html>
<body>
<google-sheets-html-origin>

Redis dashboard | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Logs Redis] Overview | 0 | 3 | 3 | 0

</body>
</html>

## Checklist

- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that panels are populated with data.
- [x] I have verified that panels are not distorted after being migrated to lens.
- [x] I have updated screenshots of dashboard.
- [x] I have verified that data count are matching and panel aggregations are same as before.

## Author's checklist

- [x] Migrated panels should be removed from visualization folder.
- [x] Migrated visualizations are populating in Kibana version 8.3.0. 

## Related issues

- Relates #5221
## Issues identified
- Need to increase the size of the pie chart https://github.com/elastic/integrations/issues/5773
- Need to swap the X-axis and Y-axis label for `Top slowest commands` https://github.com/elastic/integrations/issues/5792
**Note** :- Please refer below before migrated screenshot. Seems like the previous screenshot is too old.

image

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Review by agithomas — COMMENTED** [review]
Not particularly happy with the pie chart colours, readability is very poor

Suggestions
1. Increase the size of the chart
2. Change the colour scheme so that the partitions can be distinctly seen.

**Comment by harnish-elastic** [comment]
> Not particularly happy with the pie chart colours, readability is very poor
> 
> Suggestions
> 
> 1. Increase the size of the chart
> 2. Change the colour scheme so that the partitions can be distinctly seen.

Understood your concern. But we haven't changed the size of the pie chart and also the colors for the same.

We will update it for you in this PR and let you know.

**Comment by harnish-elastic** [comment]
> The X and Y axis labels got interchanged.

I see the issue is regarding previous visualization. Sure we have created a [bug](https://github.com/elastic/integrations/issues/5792) for this change for tracking and will update the change in this PR. Thanks!

> Also, Does't the duration value auto-adjust? If so, you can remove the `(microsecond)` from the axis label
> 
> image

Kibana hasn't any functionality to convert `microsecond` to sec / min / hour or any human readable state. Also we have already raised an issue for the same. https://github.com/elastic/kibana/issues/153378

**Pull request merged**
