### PR TITLE
[O11y][Cassandra] Migrate `Overview` dashboard visualizations to lens in kibana 8.3.0 

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for Cassandra integration package

- Statistics for Cassandra Lens migration:

<html>
<body>

  | Before Migration |   | After Migration |    |  
-- | -- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization | New Control Panel
[Metrics Cassandra] Overview | 0 | 19 | 17 | 1 (Markdown) | 1
  | 0 | 19 | 17 | 1 (Markdown) | 1

</body>
</html>

Note: 
- 1 visualization is migrated to new control panels.
- 1 visualization is markdown which can not be migrated to the lens.

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.3.0 itself.

## Related issues

- Relates #5221 

Notes: As per the [discussion](https://github.com/elastic/integrations/issues/5672#issuecomment-1484873518), the  **Cluster Info [Metrics Cassandra]** donut chart is converted to table due to limitation of split size in lens.

### CODE REVIEW

**Comment by agithomas** [comment]
@rajvi-elastic , please complete peer review

@SubhrataK , JFYI, i noticed the change from Donut Chart to Table representation for representing the cluster information and i agree with the change. Hope you are good too.

**Comment by muthu-mps** [comment]
@rajvi-elastic,

- Please change the description of the issue which represents Redis Enterprise
- When replacing the control filter the current integration enables the `Database` selection based on the `host` selection. Are we having the same functionality in the control panel migration. If not is this captured somewhere ?

@SubhrataK - Please let me know your thought process on the mentions below.
- Can we make Node and Cluster Info tables to the fit in the entire screen ? 
- The Read Latency, Write Latency and Range Slice Latency all together looks cluttered. Can we realign ?
- Similarly for Storage Exception and Unavailable Requests.

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic,
> 
> * Please change the description of the issue which represents Redis Enterprise
> * When replacing the control filter the current integration enables the `Database` selection based on the `host` selection. Are we having the same functionality in the control panel migration. If not is this captured somewhere ?

@muthu-mps, 

1. Updated the description. 
2. No in the new control panels dependency filtering is not possible. We have mentioned this issue in the meta in below format. 

In input control visualization, we can make dependency filters that strictly depend on each other but in new controls, dependency filtering is possible but filters are not required to be strict. As per the https://github.com/elastic/integrations/issues/4768#issuecomment-1429952042, this is the expected behavior of new controls.
Impact : [ Severity : Low, Workaround : No (Expected Behaviour) ]

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Comment by rajvi-elastic** [comment]
> @SubhrataK - Please let me know your thought process on the mentions below.
> 
> * Can we make Node and Cluster Info tables to the fit in the entire screen ?
> * The Read Latency, Write Latency and Range Slice Latency all together looks cluttered. Can we realign ?
> * Similarly for Storage Exception and Unavailable Requests.

As discussed with @SubhrataK, created issue to update `service.address` field: https://github.com/elastic/integrations/issues/5766

**Review by muthu-mps — APPROVED** [review]
Looks good !

**Pull request merged**
