### PR TITLE
Rename datasources to config_templates

### PR DESCRIPTION
**Pull request by ruflin**
This renames the `datasources:` part in the dataset manifest to `config_tempaltes:`.

### CODE REVIEW

**Comment by ruflin** [comment]
This requires https://github.com/elastic/package-registry/pull/570 to be merged first and then the dependency is updated to update the last two usages of DataSources.

**Comment by ruflin** [comment]
@mtojek good catch, fixed.

**Comment by ruflin** [comment]
@mtojek Updated again with quite a few more changes I found.

Is CI validating of the imports-beat code is valid?

**Comment by mtojek** [comment]
>Is CI validating of the imports-beat code is valid?

Nope, unfortunately it doesn't. It wasn't urgent so far (also the future of this script is blurry).

Side note: there was Kubernetes integration pushed to master. I think you need to rebase your PR.

**Comment by ruflin** [comment]
@mtojek Rebased and updated with most recent packages.

**Pull request merged**
