### PR TITLE
cisco_asa: add handling of AAA operations

### LINKED ISSUE #3852: cisco_asa: vpn authentication rejected messages
Adding a processor on the default Cisco ASA ingest pipeline that parses the [113005 message](https://www.cisco.com/c/en/us/td/docs/security/asa/syslog/b_syslog/syslog-messages-101001-to-199021.html#con_8293726), which provides information when authentication on a connection has failed.

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

This adds handling of authentication fields for Cisco ASA AAA message types.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Updates elastic/beats#32257
- Closes #3852

### CODE REVIEW

**Comment by leweafan** [comment]
@efd6 seems like even.outcome always "success" but for failed authentications it should be "failure".

**Comment by efd6** [comment]
@leweafan Yeah, this can be confusing. Success is always a contextual thing; from the perspective of the attempting authenticator, a failure to auth is a failure, but if this entity is malicious it is a success for the people who matter. So in the [ECS definition](https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-outcome) you can see 
> `event.outcome` simply denotes whether the event represents a success or a failure **from the perspective of the entity that produced the event**.
The entity that produced the event is the device and it must have confidence in its decisions, so all authentications that have a definitive answer are successful. If there were a failure due to a network or identity store problem, those would be failures.

**Comment by leweafan** [comment]
@efd6 event.outcome is very important for SIEM cause if we go to Sercurity -> Hosts -> Authentications there is a graph for successful and failed attempts and a table representation with users their 'Successes'/'Failures'/'Last failure'/'Last failed source'/'Last failed' destination that depend on event.outcome = "failure". Please find screenshots in attachments.
Also according to ECS documentation https://www.elastic.co/guide/en/security/current/siem-field-reference.html
Screenshot 2022-07-20 at 12 08 05

Screenshot 2022-07-20 at 12 00 11
Screenshot 2022-07-20 at 11 57 10

**Comment by efd6** [comment]
Yes, having had a look at the background discussion, this appears to be the original intention. I will make this change.

**Comment by efd6** [comment]
@leweafan Please also take a look at #3750.

**Comment by efd6** [comment]
@leweafan Thanks for that, I was also thinking you might like to confirm the orientation of success/failure in that PR.

**Comment by leweafan** [comment]
@efd6 looks good

**Review by andrewkroh — APPROVED** [review]

**Pull request merged**
