### PR TITLE
Fix bugs in Cisco IOS and FTD ingest pipelines

### PR DESCRIPTION
**Pull request by C0FFEEC0FFEE**
[Fix: Dissect cisco iOS logs with prefix fman_fp_image](https://github.com/elastic/integrations/commit/6f33845cc16741cca519741892e46f25a9532305)

[Fix: Change data type to long for source.bytes and destination.bytes](https://github.com/elastic/integrations/commit/56fd384c1743f200794174f7f854be669a14b818)

### CODE REVIEW

**Comment by LaZyDK** [comment]
@C0FFEEC0FFEE can you provide us with anonymized test logs including `fman_fp_image`?

**Comment by C0FFEEC0FFEE** [comment]
> @C0FFEEC0FFEE can you provide us with anonymized test logs including `fman_fp_image`?

Here are some logs. I replaced the ip-adresses and the hostname of the router.
```
Jul 11 09:30:59 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(59144) -> 1.2.3.4(1103), 1 packet
Jul 11 09:31:03 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(59120) -> 1.2.3.4(7774), 1 packet
Jul 11 09:31:05 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied udp 1.2.3.4(43526) -> 1.2.3.4(5353), 1 packet
Jul 11 09:31:51 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(44678) -> 1.2.3.4(60023), 1 packet
Jul 11 09:32:04 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied udp 1.2.3.4(5292) -> 1.2.3.4(7060), 1 packet
Jul 11 09:32:07 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(42432) -> 1.2.3.4(2379), 1 packet
Jul 11 09:32:13 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(53733) -> 1.2.3.4(60383), 1 packet
Jul 11 09:32:24 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(46707) -> 1.2.3.4(3474), 1 packet
Jul 11 09:32:25 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(54804) -> 1.2.3.4(7001), 1 packet
Jul 11 09:33:49 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(52062) -> 1.2.3.4(23), 1 packet
Jul 11 09:33:55 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(38535) -> 1.2.3.4(9999), 1 packet
Jul 11 09:34:00 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied udp 1.2.3.4(1985) -> 1.2.3.4(1985), 327 packets
Jul 11 09:34:00 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied udp 1.2.3.4(1985) -> 1.2.3.4(1985), 342 packets
Jul 11 09:34:06 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(55527) -> 1.2.3.4(1311), 1 packet
Jul 11 09:34:06 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(25147) -> 1.2.3.4(443), 1 packet
Jul 11 09:34:08 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied udp 1.2.3.4(33351) -> 1.2.3.4(41079), 1 packet
Jul 11 09:34:23 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(17869) -> 1.2.3.4(8686), 1 packet
Jul 11 09:34:32 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(30974) -> 1.2.3.4(12257), 1 packet
Jul 11 09:34:33 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(50463) -> 1.2.3.4(25789), 1 packet
Jul 11 09:34:41 my-router-hostname %FMANFP-6-IPACCESSLOGP: R0/0: fman_fp_image: list internet_in_gig0 denied tcp 1.2.3.4(40563) -> 1.2.3.4(8081), 1 packet

```

**Comment by LaZyDK** [comment]
@C0FFEEC0FFEE Now this PR can be closed. Both fixes has been merged. 
#6929 
#6930

**Pull request closed without merging**
