### PR TITLE
Update Cisco integration manifest for consistency

### PR DESCRIPTION
**Pull request by LaZyDK**
## What does this PR do?

Fixes wording for consistency of integration module.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

### CODE REVIEW

**Comment by LaZyDK** [comment]
@P1llus This is a simple wording issue.

**Comment by P1llus** [comment]
run tests

**Review by P1llus — APPROVED** [review]

**Comment by P1llus** [comment]
@LaZyDK Can you bump the version in changelog.yml, and add the same new version in manifest.yml? We need to bump versions on packages so that people get the updates.

**Comment by LaZyDK** [comment]
Bump completed :)

**Pull request merged**
