### PR TITLE
Remove event.original removal processors (integrations AWS & Azure)

### PR DESCRIPTION
**Pull request by Alphayeeeet**
Please label as enhancement

## Proposed commit message 
Remove event.original removal processors

- [x] AWS *
- [x] Azure * 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues
Review #10072 for additional info

### CODE REVIEW

**Comment by Alphayeeeet** [comment]
Please run CI tests

**Review by andrewkroh — APPROVED** [review]
LGTM. Did you confirm that the minimum version is at least 8.11.0 (similar to https://github.com/elastic/integrations/pull/10417#issuecomment-2248603381)?

**Comment by Alphayeeeet** [comment]
> LGTM. Did you confirm that the minimum version is at least 8.11.0 (similar to https://github.com/elastic/integrations/pull/10417#issuecomment-2248603381)?

@andrewkroh I checked minimum Kibana constraints. However I saw that CI is failing on Azure integration due to permission denied on filesystem. Did I miss anything?

**Comment by andrewkroh** [comment]
I think azure needs an `elastic-package test pipeline -g` to re-build the files with `event.original`.

**Comment by muthu-mps** [comment]
@Alphayeeeet - The changelog entry for the `azure_openai` integration is missing. Can we add an entry for the missing one?

**Comment by Alphayeeeet** [comment]
@muthu-mps Thanks for mentioned. It seems that I forgot about that one. I will add it.

**Review by muthu-mps — APPROVED** [review]

**Comment by muthu-mps** [comment]
> I think azure needs an `elastic-package test pipeline -g` to re-build the files with `event.original`.

You need to address this comment to fix the build failure.

**Comment by andrewkroh** [comment]
@elastic/obs-ds-hosted-services, can you please have look at the changes. This gives `@custom` pipelines access to event.original.

**Review by kaiyan-sheng — COMMENTED** [review]
Should we remove the tag `preserve_original_event` then since `event.original` will always be there?

**Comment by andrewkroh** [comment]
No, this tag is still used by Fleet's built-in final_pipeline to determine if it should remove `event.original`.

**Review by kaiyan-sheng — APPROVED** [review]

**Comment by Alphayeeeet** [comment]
@andrewkroh Could you run CI again?

**Pull request merged**
