### PR TITLE
[elasticsearch] fix pending_tasks mappings

### PR DESCRIPTION
**Pull request by klacabane**
### Summary
Closes https://github.com/elastic/kibana/issues/138865

This change contains multiple small fixes:
- I generated new [pending tasks](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-pending.html) documents and realized the mappings were wrong. Note that the [.monitoring-es-mb mappings](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/resources/monitoring-es-mb.json#L220) are also incorrect and should be updated - https://github.com/elastic/integrations/commit/789ead052609b27e07bf8f768b96ccafea1e28c4
- Updated the readme to use template shortcuts. Note that the output readme is extremely noisy and we should improve the readability, for example by wrapping the fields and sample events in a details block
- Updated the logo

### CODE REVIEW

**Review by crespocarlos — APPROVED** [review]
LGTM!

**Comment by klacabane** [comment]
There's probably a better approach but I went the brute force way:
- create indexes in a while loop, you can have multiple in parallel to increase probability of queuing
- update metricbeat/agent configuration to collect metrics as often as possible, for example 1s, because tasks won't spent to much time in the queue

**Comment by matschaffer** [comment]
If I grep kibana source for `cluster.pending_task` I see number of test mapping references. Are they wrong or does this change only happen after a certain version?

**Comment by crespocarlos** [comment]
Thanks @klacabane. I managed to have some pending tasks here. 

@matschaffer, indeed there is a number of `cluster.pending_task` in the Kibana repo. I've run some tests reverting the changes present here.

Currently, without Kevin's change, `pending_task` is an object within `cluster` object

`GET metrics-elasticsearch.stack_monitoring.pending_tasks-default/_mapping`
```json

"elasticsearch": {
  "properties": {
    "cluster": {
      "properties": {
        "id": {
          "type": "keyword",
          "ignore_above": 1024
        },
        "name": {
          "type": "keyword",
          "ignore_above": 1024
        },
        "pending_task": { <--- current mapping
          "properties": {
            "insert_order": {
              "type": "long"
            },
            "priority": {
              "type": "keyword",
              "ignore_above": 1024
            },
            "source": {
              "type": "keyword",
              "ignore_above": 1024
            },
            "time_in_queue": {
              "properties": {
                "ms": {
                  "type": "long"
                }
              }
            }
          }
        },
        "state": {
          "properties": {
            "id": {
              "type": "keyword",
              "ignore_above": 1024
            }
          }
        }
      }
    },
    "node": {
      "properties": {
        "id": {
          "type": "keyword",
          "ignore_above": 1024
        },
        "master": {
          "type": "boolean"
        },
        "mlockall": {
          "type": "boolean"
        },
        "name": {
          "type": "keyword",
          "ignore_above": 1024
        }
      }
    }
  }
}
```

And this is what is actually in the doc. Looks like the mapping is wrong.

`GET metrics-elasticsearch.stack_monitoring.pending_tasks-default/_search`
```json
"elasticsearch": {
  "cluster": {
    "name": "elasticsearch",
    "id": "CvwadJe-QPyh9S7YKTNLAQ"
  },
  "pending_tasks": {
    "time_in_queue.ms": 150,
    "source": "create-index [test_e+cu4r+1], cause [api]",
    "priority": "URGENT",
    "insert_order": 1336
  }
}
```

**Comment by klacabane** [comment]
Looks like the mappings are correct for version up to 6.4 (see https://github.com/elastic/beats/blob/6.4/metricbeat/module/elasticsearch/pending_tasks/pending_tasks.go#L90), starting 6.5 we write to `elasticsearch.pending_tasks`

**Comment by matschaffer** [comment]
Gotcha. Let's at least get an issue open to fix the other mappings (internal/mb, maybe fixture data?).

**Pull request merged**
