### PR TITLE
[o365] O365 Title/Description changes

### LINKED ISSUE #10178: [o365] Integration Title/Short Description Change [Microsoft 365 --> Microsoft Office 365]
Today the Office 365 Integration is called Microsoft 365 which is confusing with Microsoft Defender 365. I suggest that the title simply add Office in it so that end users can distinguish this integration between other Microsoft integrations.

image

Even the short title does not tell me this has anything to do with Office 365.
Recommended new text: `Collect logs from Microsoft Office 365 with Elastic Agent.`

image

It may also be useful to move the underlying codebase to microsoft_o365 so it lives close to the other microsoft integrations.
image 
`o365` --> `microsoft_o365`

Also you cannot search Office for integrations to find the integration to ingest these logs.
image

Changing these names and descriptions will make it easier to find and deploy this integration.

### PR DESCRIPTION
**Pull request by nicpenning**
- Bug

## Proposed commit message
See title / linked issue: https://github.com/elastic/integrations/issues/10178

- WHAT: Clarify this integration as Microsoft Office 365
- WHY:  Improve user experience for finding integration 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues
- Closes #10178

### CODE REVIEW

**Review by efd6 — COMMENTED** [review]
The issue's change proposal doesn't require that we change the path of the code. Let's keep that the same and just make the cosmetic changes that are required.

**Comment by nicpenning** [comment]
> The issue's change proposal doesn't require that we change the path of the code. Let's keep that the same and just make the cosmetic changes that are required.

Understood, I can do that. And hello again, 👋.

**Comment by nicpenning** [comment]
This was a doozy, but I think it will do. Let me know if you need me to blow this away and start over, thanks!

**Comment by efd6** [comment]
`git rebase` is your friend.

**Review by efd6 — APPROVED** [review]
Thanks

**Pull request merged**
