### PR TITLE
[O11y][Hadoop] Migrate `application` dashboard visualizations to lens in kibana 8.3.0

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?

- Migrate visualizations to lens for Hadoop integration package

- Statistics for **Hadoop** Lens migration:

<html>
<body>
<google-sheets-html-origin>

Hadoop dashboards | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics Hadoop] Applications | 0 | 7 | 7 | 0
  | 0 | 7 | 7 | 0

</body>
</html>

## Checklist

- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that panels are populated with data.
- [x] I have verified that panels are not distorted after being migrated to lens.
- [x] I have updated screenshots of dashboard.
- [x] I have verified that data count are matching and panel aggregations are same as before.

## Author's checklist

- [x] Migrated panels should be removed from visualization folder.
- [x] Migrated visualizations are populating in Kibana version 8.3.0. 

## Related issues

- Relates #5221

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
Curious - why the amount of memory is in (s)? Can you look and make essential adjustments?

**Comment by agithomas** [comment]
> Curious - why the amount of memory is in (s)? Can you look and make essential adjustments?

Similar for the virtual cores as well.

**Comment by agithomas** [comment]
Why the elapsed time, being a large value, not converted to minutes / hours ? Doesn't lens viz does it automatically?

**Comment by harnish-elastic** [comment]
> Why the elapsed time, being a large value, not converted to minutes / hours ? Doesn't lens viz does it automatically?

Yes @agithomas, Lens doesn't have the functionality to convert the value into seconds / minutes / hours / human-readable-format. Please refer the issue: https://github.com/elastic/kibana/issues/153378

Also while migrating the visualization to lens, we kept the same behavior in the lens.

**Comment by harnish-elastic** [comment]
> Curious - why the amount of memory is in (s)? Can you look and make essential adjustments?
> Similar for the virtual cores as well.

Sure @agithomas, we have raised separate issue for this. https://github.com/elastic/integrations/issues/5628
Once these PRs are approved and merged we will raise the PR for this fix as well.

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
