### PR TITLE
[System] Add global filter in dashboard for System

### PR DESCRIPTION
**Pull request by milan-elastic**
## Proposed commit message
Add a global filter to the dashboard and remove the subfilters on the dataset and a global filter on the dataset is introduced. Filters on data_stream.dataset are applied with a phrase type filter on the dataset that is being used in that particular dashboard.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates https://github.com/elastic/integrations/issues/9323

## Screenshots
<details>
  <summary>System Windows Security  User Logons </summary>

Before:

System Windows Security  User Logons - Before

After:
System Windows Security  User Logons - After

</summary>
</details>

<details>
  <summary>System Windows Security  Group Management Events </summary>
Before:

System Windows Security  Group Management Events - Before

After:

System Windows Security  Group Management Events - After

</summary>
</details>

<details>
  <summary>System Windows Security  Failed and Blocked Accounts </summary>
Before:

System Windows Security  Failed and Blocked Accounts - Before

After:

System Windows Security  Failed and Blocked Accounts - After

</summary>
</details>

<details>
  <summary>Metrics System  Overview </summary>
Before:

Metrics System  Overview - Before

After:

Metrics System  Overview -  After

</summary>
</details>

<details>
  <summary>Metrics System  Host overview </summary>
Before:

Metrics System  Host overview - Before

After:

Metrics System  Host overview -  After

</summary>
</details>

<details>
  <summary>User Management Events  </summary>
Before:

User Management Events - Before

After:

User Management Events - after

</summary>
</details>

<details>
  <summary>Syslog dashboard</summary>
Before:

Syslog dashboard - Before

After:

Syslog dashboard -  After

</summary>
</details>

### CODE REVIEW

**Review by harnish-elastic — APPROVED** [review]
LGTM! 🚀

**Comment by tommyers-elastic** [comment]
thanks for this! these diffs are impossible to read - would it be possible to show before/after screenshots in the PR description so a reviewer can visually confirm the changes look good? thanks !

**Comment by lalit-satapathy** [comment]
> thanks for this! these diffs are impossible to read - would it be possible to show before/after screenshots in the PR description so a reviewer can visually confirm the changes look good? thanks !

Agree, all visualisation changes can have a before vs. after.

**Comment by milan-elastic** [comment]
> thanks for this! these diffs are impossible to read - would it be possible to show before/after screenshots in the PR description so a reviewer can visually confirm the changes look good? thanks !

@tommyers-elastic  I have populated the screenshots and updated them in description.

**Review by shmsr — APPROVED** [review]

**Comment by ishleenk17** [comment]
@milan-elastic : Before and after of the Windows dashboards look the same?
What's the change there?
Also, why are we also filtering by provider name in Windows dashboards?

**Comment by milan-elastic** [comment]
> @milan-elastic : Before and after of the Windows dashboards look the same? What's the change there? Also, why are we also filtering by provider name in Windows dashboards?

For the windows dashboards, we have removed the panel level filters as those are not needed anymore because there is already global level filter on dashboard level.  
Regarding the provider name filter in windows dashboard, it was already there since beginning!

**Comment by milan-elastic** [comment]
Can someone help me with a code owner review from @elastic/elastic-agent-data-plane , @elastic/kibana-visualizations team for this PR?

**Comment by pierrehilbert** [comment]
@andresrc I don't think Data Plane team review should be necessary as this is now owned by your team directly.
I can give my +1 but I think we should change the codeowner for the kibana dashboard in addition. WDYT?

**Comment by lalit-satapathy** [comment]
> @andresrc I don't think Data Plane team review should be necessary as this is now owned by your team directly. I can give my +1 but I think we should change the codeowner for the kibana dashboard in addition. WDYT?

I agree, historically the system package kibana folder changes went to both data plane and Kibana team. That can be updated in the codeowner.

**Comment by pierrehilbert** [comment]
I'm approving to unblock you.
@lalit-satapathy could you please open a PR (that I will approve) to update the codeowners?

**Review by pierrehilbert — APPROVED** [review]

**Review by tommyers-elastic — APPROVED** [review]
everything LGTM - except for one thing, the table at the bottom of the 'User Management Events' dashboard seems to have lost its column headings.

**Comment by milan-elastic** [comment]
> everything LGTM - except for one thing, the table at the bottom of the 'User Management Events' dashboard seems to have lost its column headings.

I see, it was just a scrolling issue in the screenshot, I have updated the screenshot with column header now!

**Pull request merged**
