### PR TITLE
[trendmicro] Add new trendmicro integration

### PR DESCRIPTION
**Pull request by emnp**
## What does this PR do?
Add integration for TrendMicro deep security logs.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [x] Deep Security
- [ ]  Apex Central
- [ ] Kibana Visualizations & Dahsboards

## How to test this PR locally
```
# cd integrations/packages/trendmicro
# elastic-package build
# elastic-package stack up -d -v
# eval "$(elastic-package stack shellinit)"
# elastic-package test  -v
```

## Related issues

-

### CODE REVIEW

**Comment by emnp** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [45619ce](https://github.com/elastic/integrations/commit/45619ce67435c6e1974398165932d73f77f04a6d), [2ccb811](https://github.com/elastic/integrations/commit/2ccb81124b166b32ab2ce7bc206e05ca593b54b7)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Agreement has been signed.

**Comment by emnp** [comment]
> > ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [45619ce](https://github.com/elastic/integrations/commit/45619ce67435c6e1974398165932d73f77f04a6d), [2ccb811](https://github.com/elastic/integrations/commit/2ccb81124b166b32ab2ce7bc206e05ca593b54b7)
> > Please, read and sign the above mentioned agreement if you want to contribute to this project
> 
> Agreement has been signed.

Sorry. I did commit with two different users, one with the unset user (root) and the other with my user mail.

**Comment by P1llus** [comment]
Hello @emnp,

Really sorry for the delayed response!

Are you still up for finalizing this package? It would need some tweaks and changes that I can handle in a review if you want.

**Comment by P1llus** [comment]
It might be worthwhile to recommit under the same username, or if you are having difficulties, we could create a new PR, as we cannot add the "root" user as a certified user

**Comment by emnp** [comment]
> It might be worthwhile to recommit under the same username, or if you are having difficulties, we could create a new PR, as we cannot add the "root" user as a certified user

Hello @P1llus,  new pr will be fine. BTW, I tested again this integration with the new snapshot version 8.4.0 and log doesn't parse.

**Comment by emnp** [comment]
> 
Hello @P1llus , new pr will be fine.

**Comment by emnp** [comment]
Can I create a new pr for this integration by myself, @P1llus?

**Comment by P1llus** [comment]
@emnp yes feel free! Then lets see how the review goes and then we can merge :)

**Comment by emnp** [comment]
Hello @P1llus , not a new PR :D but recommit under the same username. Can you please help to check?

**Comment by P1llus** [comment]
@emnp your old commits are still there unfortunately, you would need to either change those commits or recommit them under a new PR.
You also seem to have closed this PR

Ref for changing author: https://www.deployhq.com/git/faqs/update-author-committer-multiple-git-commits

**Comment by emnp** [comment]
> @emnp your old commits are still there unfortunately, you would need to either change those commits or recommit them under a new PR. You also seem to have closed this PR
> 
> Ref for changing author: https://www.deployhq.com/git/faqs/update-author-committer-multiple-git-commits

Hi @P1llus, yes I closed this one. Sorry for any inconvenience. 
I set a new pr here https://github.com/elastic/integrations/pull/4471.
Can you please take a look?

**Pull request closed without merging**
