### PR TITLE
[O11y][Cassandra] Migrate `System Log` dashboard visualizations to lens in kibana 8.3.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for Cassandra integration package

- Statistics for Cassandra Lens migration:

<html>
<body>

  | Before Migration |   | After Migration |   |  
-- | -- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization | New Control Panel
[Logs Cassandra] System Logs | 0 | 3 | 1 | 1 (Markdown) | 1
  | 0 | 3 | 1 | 1 (Markdown) | 1

</body>
</html>

Note: 
- 1 visualization is migrated to new control panels.
- 1 visualization is markdown which can not be migrated to the lens.

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.3.0 itself.

## Related issues

- Relates #5221

### CODE REVIEW

**Comment by agithomas** [comment]
@rajvi-elastic , can you please re-visit the table summary at the beginning of the PR. 
The counts before and after migration are not matching. Also, the linked issue is tagged as having a workaround.

**Comment by muthu-mps** [comment]
Please update the PR description which is currently mentioning Redis Enterprise.

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Comment by rajvi-elastic** [comment]
> Please update the PR description which is currently mentioning Redis Enterprise.

@muthu-mps, I have update the description. Can you please review it?

**Review by muthu-mps — APPROVED** [review]
LGTM!

**Pull request merged**
