### PR TITLE
[O11y][ZooKeeper] Lens migration for visualizations to Kibana version 8.2.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for ZooKeeper integration package

- Statistics for ZooKeeper Lens migration:

<html>
<body>

Zookeeper dashboard | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics Zookeeper] Overview | 0 | 5 | 5 | 0
  | 0 | 5 | 5 | 0

</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.2.0 itself.

## Related issues

- Relates #5221 

## Issues Identified
- TSVB visualization doesn’t show negative values in UI. But the lens shows both negative and positive values. (This will be fixed in 8.8)
https://github.com/elastic/elastic-charts/issues/135
Impact : [ Severity : Low, Workaround : This will be fixed in 8.8 ]

### CODE REVIEW

**Review by agithomas — APPROVED** [review]
LGTM. It may be best to add the unit of latency in the Y-axis for the latency panel.

If you can add the unit in the Y-axis for the latency, it will be good. If it is a time taking thing, please create a backlog ticket

**Comment by rajvi-elastic** [comment]
> If you can add the unit in the Y-axis for the latency, it will be good. If it is a time taking thing, please create a backlog ticket

Yes @agithomas. We can add the unit in Y-axis label. As per the [readme](https://github.com/elastic/integrations/tree/main/packages/zookeeper#:~:text=zookeeper.mntr.latency.avg) file the latency is measured in milliseconds. So we will add `ms` suffix to the Y-axis.

**Review by agithomas — APPROVED** [review]
LGTM!

Please complete the peer review

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Pull request merged**
