### PR TITLE
[Elasticsearch][Ingest Pipeline] Add elasticsearch.node.name as TSDS dimension

### LINKED ISSUE #11522: [Elasticsearch Ingest Pipeline]: Missing TSDS Dimension on Elasticsearch Node Id field
### Integration Name

Elasticsearch [elasticsearch]

### Dataset Name

elasticsearch.ingest_pipeline

### Integration Version

1.15.2

### Agent Version

8.14.3

### Agent Output Type

logstash

### Elasticsearch Version

8.15.3

### OS Version and Architecture

Container

### Software/API Version

Elasticsearch 8.15.3

### Error Message

_No response_

### Event Original

_No response_

### What did you do?

Ingest Elasticsearch ingest pipeline metrics

### What did you see?

High rates of document conflicts from TSDS dimension issue

### What did you expect to see?

Documents not having conflicts

### Anything else?

It appears that the issue here is the field mappings don't account for the pipeline running on multiple nodes.

These 2 events conflict with each other:

```json
"_source": {
    "@timestamp": "2024-10-25T12:20:26.205Z",
    "@version": "1",
    "agent": {
      "ephemeral_id": "c5450b38-f662-4c4d-955e-83d01818023e",
      "id": "f366e829-b281-4f51-b953-0b6421de91f0",
      "name": "elasticsearch-metrics-85cd87dc6f-6lnfb",
      "type": "metricbeat",
      "version": "8.14.3"
    },
    "data_stream": {
      "dataset": "elasticsearch.ingest_pipeline",
      "namespace": "private.default.production",
      "type": "metrics"
    },
    "ecs": {
      "version": "8.0.0"
    },
    "elastic_agent": {
      "id": "f366e829-b281-4f51-b953-0b6421de91f0",
      "version": "8.14.3",
      "snapshot": false
    },
    "elasticsearch": {
      "cluster": {
        "id": "ePTYK8hFSfaIBMtzUMQBCg",
        "name": "es-prod"
      },
      "ingest_pipeline": {
        "name": "metrics-aws.elb_metrics-2.25.1",
        "name_fingerprint": "O6mt5Ue7KRq7w2VCr9xN5azayhI=",
        "total": {
          "count": 10374,
          "failed": 0,
          "time": {
            "self": {
              "ms": 6
            },
            "total": {
              "ms": 7
            }
          }
        }
      },
      "node": {
        "id": "M0NpvuRXRZaMqGElEP-i6w",
        "name": "es-prod-es-rack5-ingest-0",
        "roles": "ingest"
      }
    },
    "event": {
      "agent_id_status": "auth_metadata_missing",
      "dataset": "elasticsearch.ingest_pipeline",
      "duration": 1792410281,
      "ingested": "2024-10-25T12:20:28Z",
      "module": "elasticsearch"
    },
    "host": {
      "architecture": "x86_64",
      "containerized": true,
      "hostname": "elasticsearch-metrics-85cd87dc6f-6lnfb",
      "name": "elasticsearch-metrics-85cd87dc6f-6lnfb",
      "os": {
        "kernel": "5.4.0-137-generic",
        "codename": "focal",
        "name": "Ubuntu",
        "type": "linux",
        "family": "debian",
        "version": "20.04.6 LTS (Focal Fossa)",
        "platform": "ubuntu"
      }
    },
    "metricset": {
      "period": 10000,
      "name": "ingest_pipeline"
    },
    "service": {
      "address": "https://elastic.domain.com:9200",
      "type": "elasticsearch"
    },
    "tags": [
      "beats_input_raw_event"
    ]
  }
```

```
[2024-10-25T12:20:29,516][WARN ][logstash.outputs.elasticsearch][elastic-agent][elastic_agent_elasticsearch_output] Failed action {:status=>409, :action=>["create", {:_id=>nil, :_index=>"metrics-elasticsearch.ingest_pipeline-private.default.production", :routing=>nil}, {"elasticsearch"=>{"node"=>{"roles"=>["ingest"], "id"=>"vkeapie2Tc-eyM0Q7Sj09w", "name"=>"es-prod-es-rack1-ingest-0"}, "cluster"=>{"id"=>"ePTYK8hFSfaIBMtzUMQBCg", "name"=>"es-prod"}, "ingest_pipeline"=>{"total"=>{"count"=>10957, "time"=>{"self"=>{"ms"=>7}, "total"=>{"ms"=>7}}, "failed"=>0}, "name"=>"metrics-aws.elb_metrics-2.25.1"}}, "event"=>{"module"=>"elasticsearch", "dataset"=>"elasticsearch.ingest_pipeline", "duration"=>1810724549}, "tags"=>["beats_input_raw_event"], "@timestamp"=>2024-10-25T12:20:26.205Z, "ecs"=>{"version"=>"8.0.0"}, "@version"=>"1", "service"=>{"type"=>"elasticsearch", "address"=>"https://elastic.domain.com:9200"}, "metricset"=>{"name"=>"ingest_pipeline", "period"=>10000}, "data_stream"=>{"namespace"=>"private.default.production", "dataset"=>"elasticsearch.ingest_pipeline", "type"=>"metrics"}, "agent"=>{"ephemeral_id"=>"c5450b38-f662-4c4d-955e-83d01818023e", "version"=>"8.14.3", "id"=>"f366e829-b281-4f51-b953-0b6421de91f0", "name"=>"elasticsearch-metrics-85cd87dc6f-6lnfb", "type"=>"metricbeat"}, "host"=>{"hostname"=>"elasticsearch-metrics-85cd87dc6f-6lnfb", "containerized"=>true, "architecture"=>"x86_64", "name"=>"elasticsearch-metrics-85cd87dc6f-6lnfb", "os"=>{"version"=>"20.04.6 LTS (Focal Fossa)", "name"=>"Ubuntu", "codename"=>"focal", "type"=>"linux", "platform"=>"ubuntu", "family"=>"debian", "kernel"=>"5.4.0-137-generic"}}, "elastic_agent"=>{"version"=>"8.14.3", "id"=>"f366e829-b281-4f51-b953-0b6421de91f0", "snapshot"=>false}}], :response=>{"create"=>{"status"=>409, "error"=>{"type"=>"version_conflict_engine_exception", "reason"=>"[7xkIUdwpnxJxkWqWAAABksOe790][MHOHhEEpUrLnRMji5dJi7mVwz8kKajARUioII8f23K_z8UOrIKJ5s-h5qHmvAmV9Vw@2024-10-25T12:20:26.205Z]: version conflict, document already exists (current version [1])", "index_uuid"=>"77_pKmQLQAC9LjcbxxDv6g", "shard"=>"0", "index"=>".ds-metrics-elasticsearch.ingest_pipeline-private.default.production-2024.10.19-000171"}}}}
```

They have different `ingest_pipeline` stat values, but the issue is, they came from 2 different Elasticsearch nodes, which isn't accounted for:

`"id": "M0NpvuRXRZaMqGElEP-i6w"` & `"id"=>"vkeapie2Tc-eyM0Q7Sj09w"`

Adding `elasticsearch.node.id` as a dimension field resolves this issue.

### PR DESCRIPTION
**Pull request by BenB196**
Bug

## Proposed commit message

Adds `elasticsearch.node.name` as a TSDS dimension to prevent document collisions.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [x] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## Author's Checklist

- [ ] 

## How to test this PR locally

Install assets for the Elasticsearch integration and validate that the `metrics-elasticsearch.ingest_pipeline@package` component template properly sets `elasticsearch.node.name` as `"time_series_dimension": true`

## Related issues

- Closes #11522

## Screenshots

image

### CODE REVIEW

**Review by consulthys — DISMISSED** [review]
Well spotted!
Thanks for the contribution

**Comment by consulthys** [comment]
Interestingly for the `node_stats` metric set, the `elasticsearch.node.name` was added as a dimension
https://github.com/elastic/integrations/blob/b7bb08ac2afd5e3f5e769d6aa35f7e1c1c9c6f28/packages/elasticsearch/data_stream/node_stats/fields/package-fields.yml#L319

Can you check this [commit](https://github.com/elastic/integrations/commit/b7bb08ac2afd5e3f5e769d6aa35f7e1c1c9c6f28#diff-2470cff76de92a3c48fa16914273838ad35d8d897c9681bb03ec597e4cd4a8b8) to see what would make the most sense regarding other metric sets?

**Comment by BenB196** [comment]
> Interestingly for the `node_stats` metric set, the `elasticsearch.node.name` was added as a dimension
> 
> https://github.com/elastic/integrations/blob/b7bb08ac2afd5e3f5e769d6aa35f7e1c1c9c6f28/packages/elasticsearch/data_stream/node_stats/fields/package-fields.yml#L319
> 
> Can you check this [commit](https://github.com/elastic/integrations/commit/b7bb08ac2afd5e3f5e769d6aa35f7e1c1c9c6f28#diff-2470cff76de92a3c48fa16914273838ad35d8d897c9681bb03ec597e4cd4a8b8) to see what would make the most sense regarding other metric sets?

Taking a look at the example provided, I think either would work, `service.address` being a dimension should prevent collisions between clusters if 2 clusters have the same `elasticsearch.node.name` value and are collected by the same centralized agent.

I've pushed a commit to use node.name here as with the other one.

**Comment by consulthys** [comment]
Agreed, because `elasticsearch.node.id` is also not guaranteed to be unique across clusters, so either would be fine, but since other metric sets use `elasticsearch.node.name` it'd make sense to be consistent in this one also.

**Review by consulthys — APPROVED** [review]
LGTM

**Comment by consulthys** [comment]
@BenB196 quick question, but did you sign the [CLA](https://www.elastic.co/contributor-agreement)?

**Pull request merged**
