### PR TITLE
[O11y][K8s] Update size of the metric visualizations

### LINKED ISSUE #8308: [O11y][K8s] Update size of the metric visualizations
## Description
As per the [comment](https://github.com/elastic/integrations/pull/8265#pullrequestreview-1692527050) received from Kibana team member, need to update the size of metric visualizations for the following dashboards.
 Dashboard Name | Count of visualizations to be resized
-- | --
[Metrics Kubernetes] Cronjobs | 1
[Metrics Kubernetes] StatefulSets | 5
[Metrics Kubernetes] DaemonSets | 4
[Metrics Kubernetes] Deployments | 4
[Metrics Kubernetes] Jobs | 3

### PR DESCRIPTION
**Pull request by kush-elastic**
## What does this PR do?
- Resize `K8s` Integration Dashboard's visualizations in the current Kibana version `8.10.2` itself.

  | Count of visualizations resized
-- | --
[Metrics Kubernetes] Cronjobs | 1
[Metrics Kubernetes] StatefulSets | 5
[Metrics Kubernetes] DaemonSets | 4
[Metrics Kubernetes] Deployments | 4
[Metrics Kubernetes] Jobs | 3

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #8308

## Screenshots

Before (Sample for one dashboard):-
image

After
image

### CODE REVIEW

**Review by drewdaemon — APPROVED** [review]
Thank you!

**Comment by drewdaemon** [comment]
Actually, you could also probably hide those panel titles. The metric visualization labels itself.

**Review by mbondyra — APPROVED** [review]

**Review by gizas — APPROVED** [review]

**Comment by kush-elastic** [comment]
> Actually, you could also probably hide those panel titles. The metric visualization labels itself. (not a blocker, though!)

Thanks for the review,
It's done.
Check out the below sample:

image

**Comment by kush-elastic** [comment]
@drewdaemon,
What do you think about the below dashboard?
If we resize the lower left panel(which is also metric type) of the dashboard it might look a bit weird based on the next panel to it.
image

**Review by rajvi-elastic — APPROVED** [review]
LGTM!

**Comment by drewdaemon** [comment]
To me, this is still preferable to having the metric number so far from the label. Readability > style.

But, cc @gvnmagni for a second opinion.

**Comment by gvnmagni** [comment]
Agreed! If we are concerned about the metric panel size, it could also be placed next to the markdown panel (which would need to get smaller, just a little)

**Comment by kush-elastic** [comment]
> Agreed! If we are concerned about the metric panel size, it could also be placed next to the markdown panel (which would need to get smaller, just a little)

Nice idea, let me try it.

**Comment by kush-elastic** [comment]
@drewdaemon @gvnmagni ,
What do you think about below?
image

**Comment by kush-elastic** [comment]
> @drewdaemon @gvnmagni , What do you think about this? image

@drewdaemon @gvnmagni, any suggestions?

**Comment by gvnmagni** [comment]
Apologies for not answering earlier @kush-elastic, I just got back from PTO. I feel like ti works! You saved a lot of space and it seems very elegant to me 👍

**Comment by kush-elastic** [comment]
> Apologies for not answering earlier @kush-elastic, I just got back from PTO. I feel like ti works! You saved a lot of space and it seems very elegant to me 👍

No worries, i will update the PR with updated dashboard and proceed with merging this.
Thanks

**Comment by kush-elastic** [comment]
@drewdaemon @gvnmagni,
I am merging this as discussed [before](https://github.com/elastic/integrations/pull/8337#issuecomment-1794315980).

**Pull request merged**
