### PR TITLE
[O11y][IIS] Migrate `Access and error logs` dashboard visualizations to lens in kibana 8.5.0 

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for IIS integration package

- Statistics for IIS Lens migration:

<html>
<body>

IIS dashboard | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Logs IIS] Access and error logs | 0 | 5 | 5 | 0
  | 0 | 5 | 5 | 0

</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.5.0 itself.

## Related issues

- Relates #5221 

Note: Below panel which contains split chart functionality has been migrated to table visualization.
Before Migration:
screencapture-storage-0-kb-us-central1-gcp-cloud-es-io-9243-app-dashboards-2023-03-24-12_29_30

After Migration:
kibana-iis

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Comment by rajvi-elastic** [comment]
@agithomas, As per the discussion, the below panel with split chart functionality  will be migrated to horizontal bar chart.
Please find below screenshots:

Before Migration
image (17)

After Migration
image (18)

CC: @SubhrataK

**Comment by rajvi-elastic** [comment]
> @agithomas, As per the discussion, the below panel with split chart functionality will be migrated to horizontal bar chart. Please find below screenshots:
> 
> Before Migration image (17)
> 
> After Migration image (18)
> 
> CC: @SubhrataK

@agithomas, I have updated the PR with mentioned changes.

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
