### PR TITLE
Add synthetics estimator dashboard based on adhoc data view

### PR DESCRIPTION
**Pull request by emilioalvap**
## What does this PR do?

Adds synthetics estimator dashboard.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

1. Build package locally:
````
// from integrations/packages/synthetics
❯ elastic-package build
2023/06/29 15:33:23  WARN CommitHash is undefined, in both //.elastic-package/version and the compiled binary, config may be out of date.
Build the package
2023/06/29 15:33:23  INFO License text found in "/repos/integrations/LICENSE.txt" will be included in package
Package built: <pwd>/integrations/build/packages/synthetics-1.0.2.zip
Done
````

2. Set up environment variables to install the package remotely into an existing cluster:
````
integrations/packages/synthetics (225af28) [!?]
❯ export ELASTIC_PACKAGE_ELASTICSEARCH_USERNAME="elastic"

integrations/packages/synthetics (225af28) [!?]
❯ export ELASTIC_PACKAGE_ELASTICSEARCH_PASSWORD="<password>"

integrations/packages/synthetics (225af28) [!?]
❯ export ELASTIC_PACKAGE_KIBANA_HOST="<url>"
````
3. Install the package:
````
❯ elastic-package install --zip ./integrations/build/packages/synthetics-1.0.2.zip -v
2023/06/29 15:18:28  WARN CommitHash is undefined, in both /.elastic-package/version and the compiled binary, config may be out of date.
2023/06/29 15:18:28 DEBUG Enable verbose logging
2023/06/29 15:18:29 DEBUG GET <url>.io:9243/api/status
2023/06/29 15:18:29 DEBUG Validating built .zip package (path: /repos/integrations/build/packages/synthetics-1.0.2.zip)
2023/06/29 15:18:29 DEBUG Skip validation of the built .zip package
2023/06/29 15:18:29 DEBUG POST <url>.io:9243/api/fleet/epm/packages
```` 
4. Log into Kibana and check installed version matches:
image

5. Open synthetics dashboard and check data is displayed:
image

### CODE REVIEW

**Comment by andrewvc** [comment]
@emilioalvap I've pushed an update here that:

1. Fixes the billing estimate field's incorrect calculation that caused some monitors to return 0 billing units due to faulty math and conversion from long -> float -> long.
1. Incorporate's @drewpost 's suggestions
  - Updated copy in help along his guidelines
  - filters results to only include the service by using `NOT exists monitor.fleet_managed` as a filter
1. Adds the overview dashboard

**Comment by drewpost** [comment]
This dashboard can be used to approximate your current cost of _**using the managed Elastic Synthetics service to execute your synthetic monitors.**_ This dashboard does not include data transfer and data storage costs, but can be used to estimate execution costs based on your real world usage of Elastic Synthetics. Data storage utilization can be explored on the [Synthetics Settings Data Retention page](https://metlifedemo.kb.us-central1.gcp.cloud.es.io:9243/app/synthetics/settings/data-retention).

I'd like to tweak the first paragraph to bring the work managed and execution forward a bit more. Other than that, it looks great @andrewvc

**Comment by andrewvc** [comment]
Running against 8.9.1 on ESS I get

```
Error: can't install the package: can't install the package: could not zip-install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"Migration function for version 7.13.1 threw an error"}
```

Any ideas @emilioalvap ?

**Comment by andrewvc** [comment]
Nevermind, I was checking the commit before your last change

**Review by andrewvc — APPROVED** [review]
LGTM

**Pull request merged**
