### PR TITLE
[O11y][AWS] Migrate AWS Security Hub dashboards to lens

### PR DESCRIPTION
**Pull request by kush-elastic**
- Enhancement

## What does this PR do?
- Manually migrate `AWS Security Hub dashboard` visualizations to the lens in the current Kibana version `8.8.1` itself. 

- Statistics for `AWS Security Hub dashboard` Lens migration:

<html>
<body>
<google-sheets-html-origin>

AWS Security Hub Dashboards | Before Migration |   |   |   | After Migration |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
  | Map | Search | Lens | Visualization | Map | Search | Lens | Visualization
[Logs AWS] Security Hub Summary Dashboard | 0 | 0 | 5 | 5 | 0 | 0 | 10 | 0

</body>
</html>

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to the lens.
- [X] I have updated screenshots of the dashboard.
- [X] I have verified that the data counts are matching and panel aggregations are the same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.8.1 itself.

## Related issues

- Closes https://github.com/elastic/integrations/issues/6863

### CODE REVIEW

**Review by mbondyra — APPROVED** [review]
This looks good to me! 

A small nit to consider: in general pie/donut charts are not recommended for visualizing any data, but I get they add some 'attractiveness' to the dashboard. Other options would be to use treemap instead where it's much easier to notice the real proportions of data. Or even instead of donut, pie looks a bit better because there's more space for labels. 

image

Screenshot 2023-07-11 at 15 49 47

**Comment by kush-elastic** [comment]
> This looks good to me!
> 
> A small nit to consider: in general pie/donut charts are not recommended 

@mbondyra, I agree with your suggestion. I have created backlog issue (https://github.com/elastic/integrations/issues/6927) to track this and will raise separate PR for converting these donut charts to pie/treemap.

**Review by kcreddy — APPROVED** [review]
LGTM 👍🏼 Please fix the conflicts and merge.
Also we could alternately bump the minor version for enhancements, but it has not been the case with this package.

**Comment by kush-elastic** [comment]
The dashboards are exported from 8.7.0 due to export issue from 8.8.x (https://github.com/elastic/elastic-package/issues/1354)

**Pull request merged**
