### PR TITLE
[azure] Ensure event.kind is correctly set for pipeline errors

### PR DESCRIPTION
**Pull request by MakoWish**
## What does this PR do?

Modify azure integration to correctly set `event.kind` for pipeline errors and ensure `error.message` is an array.

## Checklist

- [X] I have reviewed tips for building integrations and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's changelog.yml file.
- [x] I have verified that Kibana version constraints are current according to guidelines.
 
## Author's Checklist

- [x]  

## Related issues

* For #6582

## Screenshots

### CODE REVIEW

**Comment by zmoog** [comment]
Hey @MakoWish, thank you for taking the time to work on this PR and #7043!

After a quick look, I can see setting `event.kind` with the `pipeline_error` value as a net improvement with the proper semantics since this an [allowed value](https://github.com/elastic/ecs/blob/2fb814f063746a1fac3ff1390d2e9387bdd47a2f/schemas/event.yml#L146-L150) in ECS.

I am unsure about setting `error.message` as an array. Many integrations (for example, the generic Event Hub integration) set this field as a `keyword`, and changing it into an array could be a breaking change.

Please let me know what you think.

**Comment by MakoWish** [comment]
Hi @zmoog, 

I had worked with @efd6 on #6582, and that is what he had set for all the pipelines he worked on. I just followed suit, but I do lean more toward having an array, because it is possible to have multiple pipeline errors if multiple pipelines are in use. 

Eric

**Comment by zmoog** [comment]
@MakoWish got it. I'm not questioning the usefulness of having an array of errors vs. a single one.

I think we are good if there are no backward compatibility issues in switching from `keyword` to array of strings for existing data streams. @efd6 I guess we can switch from keyword to array of string without problems, right?

**Comment by MakoWish** [comment]
As the CI currently functions, events cannot set a value to `error.message`. Any attempt to do so will cause the CI to fail (the reason for #6582 and all these PR's). Since events cannot currently utilize `error.message`, I don't believe this would be a breaking change, but yeah... let's see what @efd6 says.

**Comment by efd6** [comment]
@zmoog SEI is making all `error.message` fields arrays. It's not a breaking change since arrays of scalar fields are treated the same as scalar fields for search. So long as the pipeline is handling the field consistently, there should be no problem.

**Comment by zmoog** [comment]
Thank you, @efd6!

@MakoWish I asked the other cloud monitoring team members to provide their feedback before moving forward.

**Review by zmoog — APPROVED** [review]

**Pull request closed without merging**
