### PR TITLE
[AWS] Moving edge processors to ingest pipelines, adding ECS version mapping and updating field definitions.

### LINKED ISSUE #655: Convert AWS's edge processing to Ingest Node pipeline
# Convert edge processing to Ingest Node pipeline

This package uses Beats processors for some of its data processing. We want to
move that processing into the ingest node pipeline that is part of the package
to make reuse easier (e.g. data from Kafka could be routed through the pipeline).

### Data Streams
- vpcflow (inputs: log, s3)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added

### PR DESCRIPTION
**Pull request by P1llus**
## What does this PR do?

This PR moves edge processing to ingest pipelines for AWS vpcflow and updates field definitions + ecs version mapping for the rest of the filesets.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.

## Related issues

- Closes #655

### CODE REVIEW

**Review by kaiyan-sheng — APPROVED** [review]
LGTM, thanks for adding the missing error.message fields.

**Comment by mtojek** [comment]
> Currently the CI will fail on one of the logfiles used for pipeline testing because we use drop processors, I can either remove the loglines that matches the drop processors or we would need to add support for it in elastic-package check + the pipeline tests, ref: elastic/elastic-package#284

As commented in the other issue, we'll add support for this, but please temporarily disable/remove these lines to make the CI happy.

**Comment by mtojek** [comment]
jenkins run the tests please

**Comment by P1llus** [comment]
> jenkins run the tests please

I saw the error, I can add a fix for that right now, its the event.ingested is not set to dynamic for a specific logfile @mtojek . Its pretty hard to catch all log files, I ended up filing this: https://github.com/elastic/elastic-package/issues/289

**Review by andrewkroh — APPROVED** [review]

**Pull request merged**
