### PR TITLE
[azure_billing] Add resource_manager_audience config option

### PR DESCRIPTION
**Pull request by zmoog**
## Proposed commit message

Add the `resource_manager_audience` config option in the "Advance options" section. 

The `resource_manager_audience` was already available in Metricbeat, but we never exposed it in the integration settings before today.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] ~~I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices)~~

## Related issues

- n/a

## Screenshots

CleanShot 2024-10-29 at 23 02 14@2x

CleanShot 2024-10-29 at 23 02 55@2x

### CODE REVIEW

**Comment by muthu-mps** [comment]
The [documentation](https://www.elastic.co/docs/current/integrations/azure_billing#:~:text=Directory%27s%20Tenant%20ID.-,Advanced%20options,-There%20are%20two) has a mention on two advanced configuration options. Can we include the `resource manager audience` config to the documentation?

**Comment by zmoog** [comment]
> The [documentation](https://www.elastic.co/docs/current/integrations/azure_billing#:~:text=Directory%27s%20Tenant%20ID.-,Advanced%20options,-There%20are%20two) has a mention on two advanced configuration options. Can we include the `resource manager audience` config to the documentation?

Oh, I missed this part, thank you.

On it.

**Comment by muthu-mps** [comment]
nit: `There are two additional advanced options:` The number of advanced config can be removed from the document.

**Review by gpop63 — APPROVED** [review]

**Review by muthu-mps — APPROVED** [review]
LGTM!

**Pull request merged**
