### PR TITLE
Document pipeline tests coverage reports

### PR DESCRIPTION
**Pull request by adriansr**
## What does this PR do?

Updates the _Testing and Validation_ docs to reflect changes to coverage reports introduced by https://github.com/elastic/elastic-package/pull/585

### CODE REVIEW

**Comment by efd6** [comment]
Is this still active with 585 closed unmerged?

**Review by andrewkroh — APPROVED** [review]

**Review by mtojek — COMMENTED** [review]
@adriansr Do you think we can convert this PR into a draft as we wait until all changes around ingest pipelines get into elastic-package?

**Comment by andrewkroh** [comment]
I addressed the merge conflicts and this is ready for review / merge.

**Review by mtojek — APPROVED** [review]

**Pull request merged**
