### PR TITLE
[O11y][WebSphere Application Server] Release Session Manager, Servlet, Threadpool lens migration work

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?

Bump up the package version and release Session Manager, Servlet, Threadpool lens migration work

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- https://github.com/elastic/integrations/issues/5575
- https://github.com/elastic/integrations/issues/5221

### CODE REVIEW

**Comment by agithomas** [comment]
Can you update the link to the actual PR link of Lens migration ?

**Comment by rajvi-elastic** [comment]
> Can you update the link to the actual PR link of Lens migration ?

@agithomas, Are you suggesting to update changelog like this? 

```
- version: "0.6.0"
  changes:
    - description: Migrate 'Session Manager' and 'Servlet' data-streams visualizations to lens.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5633
- version: "0.5.0"
  changes:
    - description: Migrate threadpool data-stream visualizations to lens.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5632
- version: "0.4.0"
  changes:
    - description: Migrate jdbc data-stream visualizations to lens.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5631
```

**Comment by agithomas** [comment]
Atleast the one below
```
- version: "0.5.0"
  changes:
    - description: Release Session Manager, Servlet, Threadpool lens migration work.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5870
```
 should be updated. If there are no issues, go with the format suggested above.

**Comment by rajvi-elastic** [comment]
> Atleast the one below
> 
> ```
> - version: "0.5.0"
>   changes:
>     - description: Release Session Manager, Servlet, Threadpool lens migration work.
>       type: enhancement
>       link: https://github.com/elastic/integrations/pull/5870
> ```
> 
> should be updated. If there are no issues, go with the format suggested above.

@agithomas, I will update changelog a s per your suggestion.

```
- version: "0.5.0"
  changes:
    - description: Release Session Manager, Servlet, Threadpool lens migration work.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5870
   - description: Migrate 'Session Manager' and 'Servlet' data-streams visualizations to lens.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5633
   - description: Migrate threadpool data-stream visualizations to lens.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/5632
```

**Comment by rajvi-elastic** [comment]
> > Atleast the one below
> > ```
> > - version: "0.5.0"
> >   changes:
> >     - description: Release Session Manager, Servlet, Threadpool lens migration work.
> >       type: enhancement
> >       link: https://github.com/elastic/integrations/pull/5870
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > should be updated. If there are no issues, go with the format suggested above.
> 
> @agithomas, I will update changelog as per your suggestion.
> 
> ```
> - version: "0.5.0"
>   changes:
>     - description: Release Session Manager, Servlet, Threadpool lens migration work.
>       type: enhancement
>       link: https://github.com/elastic/integrations/pull/5870
>    - description: Migrate 'Session Manager' and 'Servlet' data-streams visualizations to lens.
>       type: enhancement
>       link: https://github.com/elastic/integrations/pull/5633
>    - description: Migrate threadpool data-stream visualizations to lens.
>       type: enhancement
>       link: https://github.com/elastic/integrations/pull/5632
> ```

@agithomas, PR has been updated.

**Review by milan-elastic — APPROVED** [review]

**Comment by agithomas** [comment]
@rajvi-elastic , when i look at the other Lens migration projects, i see that we increase the minor version for every dashboards. It may be best to avoid exception as with this case. Please follow as you mentioned [here](https://github.com/elastic/integrations/pull/5870#issuecomment-1506439636). Please ensure that the PR links are pointing to the original PR links not to this [PR](https://github.com/elastic/integrations/pull/5870)

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
