### PR TITLE
[Zeek] Moving edge processing to ingest pipelines

### LINKED ISSUE #664: Convert Zeek's edge processing to Ingest Node pipeline
# Convert edge processing to Ingest Node pipeline

This package uses Beats processors for some of its data processing. We want to
move that processing into the ingest node pipeline that is part of the package
to make reuse easier (e.g. data from Kafka could be routed through the pipeline).

### Data Streams
- connection (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- dce_rpc (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- dhcp (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- dnp3 (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- dns (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- dpd (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- files (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- ftp (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- http (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- intel (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- irc (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- kerberos (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- modbus (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- mysql (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- notice (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- ntlm (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- ocsp (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- pe (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- radius (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- rdp (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- rfb (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- sip (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- smb_cmd (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- smb_files (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- smb_mapping (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- smtp (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- snmp (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- socks (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- ssh (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- ssl (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- stats (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- syslog (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- traceroute (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- tunnel (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- weird (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added
- x509 (inputs: log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added

### PR DESCRIPTION
**Pull request by P1llus**
## What does this PR do?

This PR moves all edge processing for the zeek filesets to ES ingest pipelines, adds pipeline tests to each fileset, and adds splunk data to each fileset golden files to test.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.

## Related issues

- Closes #664

### CODE REVIEW

**Comment by P1llus** [comment]
This still requires a bit of polish, but almost there!

**Comment by P1llus** [comment]
Except the DNS fileset, they are all ready for review

**Comment by P1llus** [comment]
CI errors will fail until DNS fileset is finalized, please disregard those.

**Comment by leehinman** [comment]
I noticed that the Splunk & "normal" processing are all in the same pipeline.  What do you think about splitting the pipelines?  Something like this for the first "pipeline-entry.yml"

```
processors:
  - json:
      field: message
      target_field: json
      ignore_failure: true
      if: ctx?.message != null
  - drop:
      if: 'ctx?.json?.result == null && ctx?.json?.ts == null' 
  - pipeline:
      if: ctx.json.result != null
      name: '{< IngestPipeline "pipeline-splunk" >}'
  - pipeline:
      name: '{< IngestPipeline "pipeline-zeek" >}'
on_failure:
  - set:
      field: error.message
      value: 'pipeline-entry: {{ _ingest.on_failure_message }}'    
```

That would be the same for all zeek datasets, and then in "pipeline-splunk" it does the moving around to get things in the right place and at the end calls "pipeline-zeek".

"pipeline-entry.yml" and "pipeline-splunk.yml" would be the same for all datasets, only pipeline-zeek would be specific to each dataset.

**Comment by P1llus** [comment]
> I noticed that the Splunk & "normal" processing are all in the same pipeline. What do you think about splitting the pipelines? Something like this for the first "pipeline-entry.yml"
> 
> ```
> processors:
>   - json:
>       field: message
>       target_field: json
>       ignore_failure: true
>       if: ctx?.message != null
>   - drop:
>       if: 'ctx?.json?.result == null && ctx?.json?.ts == null' 
>   - pipeline:
>       if: ctx.json.result != null
>       name: '{< IngestPipeline "pipeline-splunk" >}'
>   - pipeline:
>       name: '{< IngestPipeline "pipeline-zeek" >}'
> on_failure:
>   - set:
>       field: error.message
>       value: 'pipeline-entry: {{ _ingest.on_failure_message }}'    
> ```
> 
> That would be the same for all zeek datasets, and then in "pipeline-splunk" it does the moving around to get things in the right place and at the end calls "pipeline-zeek".
> 
> "pipeline-entry.yml" and "pipeline-splunk.yml" would be the same for all datasets, only pipeline-zeek would be specific to each dataset.

@leehinman Sure I wouldn't mind, but there is only about 4-5 processors that is splunk specific, then the rest is for both the "normal" and for splunk, and they are already exactly the same for all filesets, isn't it going to be messier to have 3 pipelines, and 2 which is almost empty?

**Comment by P1llus** [comment]
@leehinman mentioned that we should compare with golden files from the Zeek module, which will most likely uncover some misses, planning to do this next Monday.

**Comment by P1llus** [comment]
On the topic of splitting out the splunk specific parts into a specific pipeline, we decided to move that to a separate PR, once we have the possibility to store a single pipeline that can be shared between filesets.

**Comment by leehinman** [comment]
I tried a diff noticed a couple of things ( [diff src](https://gist.github.com/leehinman/154d02b8b72506f1b418d62631eeda54) )
`zeek.irc.command` is missing
`zeek.irc.user` is difference
`zeek.notice.actions` is new
`zeek.notice.suppress_for` now has decimal point
in http `url.port` removed
in http `url.path` added
in dhcp `destination.port` changed to 68
`zeek.dhcp.domain` missing
`zeek.dhcp.lease_time` now has decimal point
`zeek.files.duration` now has decimal point
`zeek.files.md5` missing
`zeek.files.mime_type` missing
`zeek.files.sha1` missing
and dns is different but I think that is expected.

**Comment by P1llus** [comment]
> I tried a diff noticed a couple of things ( [diff src](https://gist.github.com/leehinman/154d02b8b72506f1b418d62631eeda54) )
> `zeek.irc.command` is missing
> `zeek.irc.user` is difference
> `zeek.notice.actions` is new
> `zeek.notice.suppress_for` now has decimal point
> in http `url.port` removed
> in http `url.path` added
> in dhcp `destination.port` changed to 68
> `zeek.dhcp.domain` missing
> `zeek.dhcp.lease_time` now has decimal point
> `zeek.files.duration` now has decimal point
> `zeek.files.md5` missing
> `zeek.files.mime_type` missing
> `zeek.files.sha1` missing
> and dns is different but I think that is expected.

Thanks for taking the time @leehinman . I think what happen here is that I renamed a few that was originally "converted". I was a bit unsure why we store the same data in both zeek fields and ECS fields. I am going through all the logs now and fixing up the small bits and pieces.

**Comment by P1llus** [comment]
Manually went through all the golden files and applied some small fixes. The DNS fileset can still be ignored for now.

The only issue left is a few float values that does not want to convert, so I removed the convert processors for now, maybe someone else has an idea, the issues are in:

```
zeek.dhcp.duration
zeek.dhcp.lease_time
zeek.notice.suppress_for
zeek.files.duration

```

```
Running a convert processor with type long on these would return errors like:
zeek/files test-files.log:
[0] unexpected pipeline error: For input string: \"0.0\"
[1] unexpected pipeline error: For input string: \"5.316734313964844E-5\"
zeek/notice test-notice.log:
[0] unexpected pipeline error: For input string: \"3600.0\"
zeek/files test-files.log:
[0] unexpected pipeline error: For input string: \"0.0\"
[1] unexpected pipeline error: For input string: \"5.316734313964844E-5\"
zeek/notice test-notice.log:
[0] unexpected pipeline error: For input string: \"3600.0\"
```

**Comment by P1llus** [comment]
Any handling of event.original, duplicate fields etc discussed earlier will be handled in a separate PR to this.

**Comment by andrewkroh** [comment]
> The only issue left is a few float values that does not want to convert, so I removed the convert processors for now, maybe someone else has an idea, the issues are in:

I did a quick test with `convert` and had no issues with those float values as inputs. Are the quotes part of the input value?

```
{
  "docs": [
    {
      "doc": {
        "_index": "_index",
        "_id": "_id",
        "_source": {
          "float_output": 0.000053167343,
          "float_in": "5.316734313964844E-5"
        },
        "_ingest": {
          "timestamp": "2021-04-13T14:06:12.744211906Z"
        }
      }
    },
    {
      "doc": {
        "_index": "_index",
        "_id": "_id",
        "_source": {
          "float_output": 0,
          "float_in": "0.0"
        },
        "_ingest": {
          "timestamp": "2021-04-13T14:06:12.744218811Z"
        }
      }
    },
    {
      "doc": {
        "_index": "_index",
        "_id": "_id",
        "_source": {
          "float_output": 3600,
          "float_in": "3600.0"
        },
        "_ingest": {
          "timestamp": "2021-04-13T14:06:12.744221446Z"
        }
      }
    }
  ]
}
```

**Review by andrewkroh — COMMENTED** [review]
Nice work, this is a big undertaking. Apart from DNS changes that are pending, LGTM.

**Comment by leehinman** [comment]
LGTM.  awesome work.

**Review by andrewkroh — APPROVED** [review]

**Comment by P1llus** [comment]
jenkins run tests

**Pull request merged**
