### PR TITLE
Update link to inliner script

### PR DESCRIPTION
**Pull request by drewdaemon**
We should be using the supported fork instead of the original repository which is owned by a former Elastic employee.

### CODE REVIEW

**Review by jsoriano — APPROVED** [review]
Thanks!

**Comment by drewdaemon** [comment]
@elasticmachine merge upstream

**Comment by mrodm** [comment]
Hi @drewdaemon, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

**Comment by drewdaemon** [comment]
Really not sure why this PR is failing so consistently.... it's a one-line doc change 😆

**Pull request merged**
