### PR TITLE
wiz: fix result.evaluation to be lowercased in cloud_configuration_finding

### PR DESCRIPTION
**Pull request by maxcold**
## Proposed commit message

Cloud Security features in Kibana rely on the lowercase value of `result.evaluation`. Fixing `cloud_configuration_finding` ingest pipeline to provide the lowercased values

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

see https://github.com/elastic/integrations/pull/10790

## Related issues

- relates https://github.com/elastic/security-team/issues/9662

### CODE REVIEW

**Comment by JordanSh** [comment]
what do you think about changing our code to turn upper case to lower case where needed? just so 3Ps can have easier time integrating

**Comment by maxcold** [comment]
@JordanSh I considered it, we can maybe add it as a safety net, but my concern is that this duality will cause more headaches to the users. While we can update our code everywhere where we rely on the `result.evaluation` to lowercase the value, the Wiz data stream can be used not only from our flows. Eg. users can create dashboards, detection rules manually, etc. And they will need to remember that the value can be both lowercase and uppercase and fix it in each artifact they create. Eg. all detection rules will need to check for both values.  This is not a good UX in my opinion. So I prefer to be more strict with the data schema.

**Review by opauloh — APPROVED** [review]
lgtm, cc @animehart

**Review by efd6 — COMMENTED** [review]
I see that the relevant field here existed prior to this change, but is not an ECS field. I do not see any discussion about introduction on a non-ECS field in the original change. Is there background for that?

**Comment by maxcold** [comment]
@efd6 the field `result.evaluation` is used by `cloud_security_posture` integration (the integration Cloud Security team owns) and Cloud Security UX in Kibana rely on this field heavily. You can find more context in this document https://docs.google.com/document/d/1govaQj_8LwUOLtk3zrcjCEvRgyKWRuC-TUihCrk04ao/edit

**Review by efd6 — APPROVED** [review]

**Pull request merged**
