### PR TITLE
Update dependency on elastic-package

### PR DESCRIPTION
**Pull request by mtojek**
## What does this PR do?

This PR updates dependency on elastic-package, so this fix is included: https://github.com/elastic/elastic-package/pull/290

## Related issues

- Fixes https://github.com/elastic/elastic-package/issues/281

### CODE REVIEW

**Review by ycombinator — APPROVED** [review]
LGTM.

**Comment by ycombinator** [comment]
@mtojek I think we may have already discussed this before so I apologize if I'm repeating the discussion here:

For dependency update PRs like this one or https://github.com/elastic/integrations/pull/780 or https://github.com/elastic/integrations/pull/679 where the only files being touched are `go.mod` and `go.sum`, WDYT about not needing review from others, i.e. self-merging such PRs when CI is green? 

Sometimes there are dependency update PRs that also require additional changes beyond `go.mod` and `go.sum` (e.g. https://github.com/elastic/integrations/pull/395). For these we would still require review from others. WDYT?

**Comment by ycombinator** [comment]
> I admit I forgot about this rule and simply assigned as a reviewer. I apologize for the inconvenience.

Ha, it's not an inconvenience at all to review such PRs 🙂. I was more wondering if we had even come up with such a rule in the past 🤔. I can't remember any such conversation but my memory is also terrible.

**Comment by mtojek** [comment]
jenkins run the tests please

**Comment by mtojek** [comment]
The CI job has done its job correctly, but it can't report it status correctly due to an infrastructure outage.

**Pull request merged**
