### PR TITLE
[AWS API Gateway] Dashboard for metrics datastream

### LINKED ISSUE #6315: [AWS API Gateway] Dashboard for metrics datastream
Figure out which metrics make sense for customers and create API Gateway dashboard for Kibana.

### PR DESCRIPTION
**Pull request by lucian-ioan**
## What does this PR do?

Adds a dashboard for API Gateway metrics data stream. WIP.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Closes #6315

## Screenshots
aws_apigateway_metrics_dashboard

### CODE REVIEW

**Review by zmoog — COMMENTED** [review]
The data types on the dashboard look good: request count, bytes, latency, 4xx, and 5xx errors.

I have a few general questions:

- Labels: should we add a space between the words? For example, "IntegrationErrors" vs. "Integration Error".
- Unit of measure: some visualization may benefit from adding a UOM, like the "ms" on latency values.
- Field name differences: I know that different API Gateway types use distinct field names (`4xx` vs. `4XXError`), but should we make this visible or use the same name on the dashboard for consistency since the semantics is the same?
- The dashboard is very tall: should we consider splitting somehow?

I am looking forward to hearing from Drew o other Visualization team members!

**Comment by stratoula** [comment]
@zmoog thanx a lot. I agree that the dashboard looks good and also on:
- labels, yes let's add some space between the words. Panel title has space in general so we can safely do it and will be more readable
- Units, absolutely yes, it helps a lot for readability

> Field name differences: I know that different API Gateway types use distinct field names (4xx vs. 4XXError), but should we make this visible or use the same name on the dashboard for consistency since the semantics is the same?

I agree, let's use the same name on dashboard for consistency

Now about the height, in general we encourage small dashboards. I don't know if it makes sense to make 2 or 3 dashboards semantically but if yes I agree. Otherwise we could possibly have more panels per row.

**Comment by lucian-ioan** [comment]
@zmoog @stratoula This is how the updated dashboard looks:

screencapture-localhost-5601-app-dashboards-2023-06-19-15_11_27


WDYT? For now I would just bundle all API types in a single dashboard since they all use API Gateway. Suggestions are welcome, first dashboard ever 😁

**Review by zmoog — APPROVED** [review]
LGTM as 1.0 🚢

**Pull request merged**
