### PR TITLE
Use "elastic-package publish" to copy built integrations

### PR DESCRIPTION
**Pull request by mtojek**
## What does this PR do?

This PR uses the `elastic-package publish` to copy integrations to package-storage. It will replace the legacy code (`mage UpdatePackageStorage`).

## Related issues

- Fixes https://github.com/elastic/integrations/issues/730

### CODE REVIEW

**Comment by mtojek** [comment]
It seems that something is missing here:

```
[2021-03-30T13:28:41.537Z] panic: runtime error: invalid memory address or nil pointer dereference
[2021-03-30T13:28:41.537Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xae7b97]
[2021-03-30T13:28:41.537Z] 
[2021-03-30T13:28:41.537Z] goroutine 1 [running]:
[2021-03-30T13:28:41.537Z] github.com/go-git/go-git/v5.(*Repository).Worktree(...)
[2021-03-30T13:28:41.537Z] 	/var/lib/jenkins/workspace/gest-manager_integrations_PR-815/pkg/mod/github.com/go-git/go-git/v5@v5.1.0/repository.go:1371
[2021-03-30T13:28:41.537Z] github.com/elastic/elastic-package/internal/storage.ChangeStage(0x0, 0x1201012, 0xa, 0x12, 0xc000161680)
[2021-03-30T13:28:41.537Z] 	/var/lib/jenkins/workspace/gest-manager_integrations_PR-815/pkg/mod/github.com/elastic/elastic-package@v0.0.0-20210326093931-4b7e330c7a7c/internal/storage/storage.go:207 +0x37
[2021-03-30T13:28:41.537Z] github.com/elastic/elastic-package/internal/publish.findLatestPackageRevision(0x0, 0xc0002aa790, 0x5, 0x38, 0xc000161b00, 0x1, 0x1, 0x3b)
[2021-03-30T13:28:41.537Z] 	/var/lib/jenkins/workspace/gest-manager_integrations_PR-815/pkg/mod/github.com/elastic/elastic-package@v0.0.0-20210326093931-4b7e330c7a7c/internal/publish/publish.go:125 +0x51b
[2021-03-30T13:28:41.537Z] github.com/elastic/elastic-package/internal/publish.Package(0xc0002aa060, 0xe, 0xc00016cc60, 0xc000161d00, 0x1, 0x1)
[2021-03-30T13:28:41.537Z] 	/var/lib/jenkins/workspace/gest-manager_integrations_PR-815/pkg/mod/github.com/elastic/elastic-package@v0.0.0-20210326093931-4b7e330c7a7c/internal/publish/publish.go:64 +0x3d9
[2021-03-30T13:28:41.537Z] github.com/elastic/elastic-package/cmd.publishCommandAction(0xc0003ba840, 0xc0003a6820, 0x0, 0x1, 0x0, 0x0)
[2021-03-30T13:28:41.537Z] 	/var/lib/jenkins/workspace/gest-manager_integrations_PR-815/pkg/mod/github.com/elastic/elastic-package@v0.0.0-20210326093931-4b7e330c7a7c/cmd/publish.go:61 +0x198
[2021-03-30T13:28:41.537Z] github.com/spf13/cobra.(*Command).execute(0xc0003ba840, 0xc0003a6810, 0x1, 0x1, 0xc0003ba840, 0xc0003a6810)
[2021-03-30T13:28:41.537Z] 	/var/lib/jenkins/workspace/gest-manager_integrations_PR-815/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
[2021-03-30T13:28:41.538Z] github.com/spf13/cobra.(*Command).ExecuteC(0xc00017b8c0, 0x0, 0x1a9b7e0, 0xc0000a6058)
[2021-03-30T13:28:41.538Z] 	/var/lib/jenkins/workspace/gest-manager_integrations_PR-815/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
[2021-03-30T13:28:41.538Z] github.com/spf13/cobra.(*Command).Execute(...)
[2021-03-30T13:28:41.538Z] 	/var/lib/jenkins/workspace/gest-manager_integrations_PR-815/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
[2021-03-30T13:28:41.538Z] main.main()
[2021-03-30T13:28:41.538Z] 	/var/lib/jenkins/workspace/gest-manager_integrations_PR-815/pkg/mod/github.com/elastic/elastic-package@v0.0.0-20210326093931-4b7e330c7a7c/main.go:29 +0xb1
script returned exit code 2
```

**Comment by mtojek** [comment]
The problem lies in the way how elasticmachine builds a changeset. It clones the source repository (doesn't contain the local fork), branches out local changes and pushes to the source repository (again, not fork).

**Comment by mtojek** [comment]
jenkins run the tests please

**Comment by mtojek** [comment]
The CI build partially worked: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-815/9/pipeline/371

Actually I found another two problems:

1. Missing author field:

```
[2021-03-31T16:55:37.480Z] Error: can't publish the package: can't copy sources of latest package revision: can't copy latest revision: committing files failed (stage: update-snapshot-1617209734886886364): author field is required
```

2. Wrong revision considered as latest:

```
[2021-03-31T16:55:21.274Z] Use build directory: /var/lib/jenkins/workspace/gest-manager_integrations_PR-815/src/github.com/elastic/integrations/build/integrations/linux/0.3.8
[2021-03-31T16:55:21.274Z] Clone package-storage repository
[2021-03-31T16:55:21.274Z] 2021/03/31 16:55:21 DEBUG No-fork mode selected. The user's remote upstream won't be created.
[2021-03-31T16:55:21.275Z] Using GitHub token from environment variable.
[2021-03-31T16:55:21.275Z] 2021/03/31 16:55:21 DEBUG No-fork mode selected. he user's remote upstream won't be listed.
[2021-03-31T16:55:31.311Z] Find latest package revision of "linux" in package-storage
[2021-03-31T16:55:31.311Z] 2021/03/31 16:55:29 DEBUG Change stage to production
[2021-03-31T16:55:32.698Z] 2021/03/31 16:55:32 DEBUG Find revisions of the "linux" package
[2021-03-31T16:55:32.698Z] 2021/03/31 16:55:32 DEBUG Found package revision: linux-0.3.1
[2021-03-31T16:55:32.698Z] 2021/03/31 16:55:32 DEBUG Found package revision: linux-0.3.3
[2021-03-31T16:55:32.698Z] 2021/03/31 16:55:32 DEBUG Found package revision: linux-0.3.8
[2021-03-31T16:55:32.698Z] 2021/03/31 16:55:32 DEBUG Change stage to staging
[2021-03-31T16:55:34.610Z] 2021/03/31 16:55:34 DEBUG Find revisions of the "linux" package
[2021-03-31T16:55:34.612Z] 2021/03/31 16:55:34 DEBUG Found package revision: linux-0.3.5
[2021-03-31T16:55:34.612Z] 2021/03/31 16:55:34 DEBUG Found package revision: linux-0.3.7
[2021-03-31T16:55:34.612Z] 2021/03/31 16:55:34 DEBUG Change stage to snapshot
[2021-03-31T16:55:35.182Z] 2021/03/31 16:55:34 DEBUG Find revisions of the "linux" package
[2021-03-31T16:55:35.182Z] 2021/03/31 16:55:34 DEBUG Found package revision: linux-0.3.4
[2021-03-31T16:55:35.182Z] 2021/03/31 16:55:34 DEBUG Found package revision: linux-0.3.6
[2021-03-31T16:55:35.182Z] 2021/03/31 16:55:34 DEBUG Latest package revision: linux-0.3.6 (stage: snapshot)
```

**Comment by mtojek** [comment]
Found another one

3. PR is already present, but another one has been opened.

```
[2021-04-01T13:00:49.773Z] 2021/04/01 13:00:49 DEBUG Use Search API to find an open pull request (query: 'repo:elastic/package-storage base:snapshot is:pr is:open in:title "[snapshot] Update "panw" package to version 0.7.0"')
[2021-04-01T13:00:50.033Z] Open new pull request
[2021-04-01T13:00:50.033Z] 2021/04/01 13:00:49 DEBUG Current user: elastic
[2021-04-01T13:00:50.033Z] 2021/04/01 13:00:49 DEBUG Create new pull request (head: elastic:update-snapshot-1617282043226266618, base: snapshot)
[2021-04-01T13:00:51.418Z] 2021/04/01 13:00:51 DEBUG Pull request URL: https://github.com/elastic/package-storage/pull/1084
[2021-04-01T13:00:51.418Z] 2021/04/01 13:00:51 DEBUG Update reviewers (pull request ID: 1084)
[2021-04-01T13:00:51.989Z] 2021/04/01 13:00:51 DEBUG Reviewers requested successfully (teams: 1, reviewers: 0)
[2021-04-01T13:00:51.990Z] Done
```

**Review by ycombinator — APPROVED** [review]
LGTM.

Nice to see so much code being removed!

**Comment by mtojek** [comment]
Errors are unrelated (unavailable shard exception)

**Comment by mtojek** [comment]
jenkins run the tests please

**Pull request merged**
