### PR TITLE
tychon arp demonstration

### PR DESCRIPTION
**Pull request by efd6**
DISCUSSION ONLY DO NOT MERGE

There are still issues with this:

1. `destination`, `host`, `id` and `network` are either non-ECS compliant or have child fields that are not ECS-compliant. Ideally, these would all be put under tychon and then have ECS fields populated from the relevant information there. **As is, this cannot be merged.**
2. There is no way to currently retain the `event.original` despite the option in the agent config template. To do this the JSON parsing should be move to ingest so that the unparsed JSON text can be retained. I imagine, but don't know for sure if this is true, that the original data is single line JSON since it's coming from a log file.
3. There is no system test (this would confirm/refute the assumption above and so is helpful even only in that way). **This is also a blocker since as a log file input there is no reason not to have this present in the package.**
4. I think the data streams in general (and demonstrated here) stutter; it would be better if the datastream were arp instead of tychon_arp since that will show up to the user as tychon.tychon_arp in the datastream.dataset field in their index.

### CODE REVIEW

**Comment by joeperuzzi** [comment]
@efd6 Three of these items are somewhat straight forward

_#2 There is no way to currently retain the event.original despite the option in the agent config template. To do this the JSON parsing should be move to ingest so that the unparsed JSON text can be retained. I imagine, but don't know for sure if this is true, that the original data is single line JSON since it's coming from a log file._
TYCHON ANSWER: **- This item will be fixed across all data streams and tested.**

_#3 There is no system test (this would confirm/refute the assumption above and so is help even only in that way). This is also a blocker since as a log file input there is no reason not to have this present in the package._
TYCHON ANSWER: **We are unaware of a "system test", we'll try to find it in the docs but if you could give us an example that would help us fix this.**

_#4 I think the data streams in general (and demonstrated here) stutter; it would be better if the datastream were arp instead of tychon_arp since that will show up to the user as tychon.tychon_arp in the datastream.dataset field in their index._
TYCHON ANSWER: **We can update the folder names, however, this may run into issues with the transform and the index stream as they both create component templates and as of right now they are different, however, if we change the name of the datastream both the transform and the stream will have the same component pattern.  Is this ok, or should we change the transform too?**

_#1 destination, host, id and network are either non-ECS compliant or have child fields that are not ECS-compliant. Ideally, these would all be put under tychon and then have ECS fields populated from the relevant information there. As is, this cannot be merged._
TYCHON ANSWER: **This is going to be a huge issue across all of the data-streams as ECS is not very well covered in its dataset  (its missing hundreds of data points) and I think forcing a user to have pre-defined knowledge when filtering which "destination" fields are ECS and which fall under "tychon.destiantion" would be extremely confusing.  If there is no way around this we will need to update all of our rules, dashboards, and transforms as well as update third-party integrations.  Extrernal integrations is the real issue here as we all have data that falls well outside ECS (it being so limited) and the only way to join our data together is with common field names.  Third parties that send similar data in production environments won't be changing to use a "tychon." and therefore if we changed fields that aren't pre-defined in ECS then how do we advise customers to view our joint data in Elastic?**

**Comment by efd6** [comment]
1. The approach that I have used here would allow the non-ECS fields to be present. See [here](https://github.com/elastic/integrations/pull/8222/files#diff-7d2cfb440814590d467b7c87179d83dc48813cfde01ac257f407b026b775e3f6) under the `tychon.arp` field. The parts that _can_ be mapped to ECS can be copied/moved there and tychon-specific fields remain visible.
2. You can see how this is done here as well.

**Comment by efd6** [comment]
@joeperuzzi I have the system tests functioning now and have added back the `preserve_original_event` functionality and added the `preserve_duplicate_custom_fields` logic that can be added to when the ECS mapping is done.

**Comment by joeperuzzi** [comment]
@efd6  Thanks! 

These are the universal changes I caught that we'll apply across the rest of the project streams from your code push:

**Items we can easily take care of:**
1. Use single quotes vice double quotes in our yml 
2. Update our ECS schema version from 8 to 10
3. Add tags to our pipeline items that support this field
4. Update our pipeline error to show more data
5. Add the docker test file (this was already underway but a good example, thanks)
6. Add preserve_duplicate_custom_fields (we already added the preserve_original_event) and add to the test config file
7. Add "remove" items to our pipelines for the preserve tag items
8. Add beats.yml file to our fields folder
9. Add prospector.scanner.exclude_files: [".gz$"] to stream file

**Items that are easy changes but need more testing from our QA team:**
1, Add start and date_detection: true to all transforms (Just want to confirm this doesn't affect dashboards)
2. Add publisher_pipeline.disable_host: true (I think this is going to wreak havoc on our dashboards as we're using elastic-provided host info)
3. Change our streams to filestream from log in our manifest files (the way our data writes to the ndjson files could have an impact on the parser so this will trigger regression testing)

**These items need more in-depth discussion as these types of changes will have drastic effects to the integration for our own items, the integration with Elastic Defend, and other third-party integrations using this data**
1. Having all of our data starting with "tychon." really doesn't seem to be aligned to the spirit of ECS: _"ECS tries to model information by using the name of concepts, and avoids proper names such as tool names, project names or company names"_.  I think if we go down this route for all our streams it's going to be extremely difficult to join our data together, filter between views and properly perform triggers/alerts.  If you were unaware TYCHON is an OEM partner and we have a larger integration with Elastic that's currently deployed to millions of systems.  This is a subset of that larger integration that uses these same fields, having these fields changed here will impact downstream to the rest.

**Pull request closed without merging**
