### PR TITLE
[elastic_agent] Agent Metrics Dashboard improvements

### LINKED ISSUE #9724: Agents Metrics dashboards / visualizations are incorrect since the tsds was introduced with the new counter type
**Summary:** Agents Metrics Dashboards / Visualizations are incorrect since the tsds were introduced with the new `counter` type. 

**Why:**  This is important because more and more users are onboarding with Elastic Agent and are relying heavily on these metrics to understand the health of agents and overall Ingest. 

**Versions:** 8.12 + (not sure 8.11) When `tsds` was introduced

**Note:** When Fixing, please add the `output.event.dropped` rate as well; this is badly needed since this is what is captured when there is a mapping failure. 

**Details:** 
Many of the Agent Metrics Visualizations are incorrect since the introduction of `tsds` with the new `counter` type.

The metric graphs that use tsds `counter` type data are incorrect because they do not aggregate on the correct dimension.
`counter_rate` needs to be aggregated by their respective series (dimension) that created them, not a common or arbitrary dimension

In this case counter rate of any of the metrics n aggregated by `agent.name` which produced them .. not `beat.type` which is just an arbitrary dimension that works for aggregations like `count` or `sum` but not `counter_rate`

The following are incorrect: There may be more.

**Dashboard:** 
- [Elastic Agent] Agent metrics

**Visualizations:** 

- [Elastic Agent] Total events rate /s
- [Elastic Agent] Output write throughput
- [Elastic Agent] Output write errors
- [Elastic Agent] Output write batches
- [Elastic Agent] Dropped Events **(Please Add!)**
- [Elastic Agent] Events acknowledged rate /s

**Notes on Visualizations:** 
- I think these are all rates going forward so I should include units
- Also, since these are rates in the lens and the data is collected at 1m intervals, the min interval in the horizontal axis / (date histogram) needs to be set to 1m min interval, or the graph will not render correctly. 

**Screenshots:**
Screenshot 2024-03-27 at 9 19 04 AM
Screenshot 2024-03-25 at 10 05 48 PM
Screenshot 2024-03-25 at 10 04 55 PM
Screenshot 2024-03-25 at 10 13 21 PM (1)

### PR DESCRIPTION
**Pull request by leehinman**
## Proposed commit message

The visualizations in the "[Elastic Agent] Agent Metrics" Dashboard have been improved.  Specifically:

For the following visualizations the breakdown was changed from `beat.type` to `agent.name`+`component.id`.  This was necessary because it was grouping data together from different sources which was reporting incorrect values.  `agent.name`+`component.id` is correct because this maps the data to the unique process id that generated the data.

Also, the interval was changed from auto to minute.  This is necessary because the data only comes in at 1 minute intervals.  By default the visualization was grabbing smaller intervals which was breaking the visualization.

- [Elastic Agent] Total events rate /s
- [Elastic Agent] Output write throughput
- [Elastic Agent] Output write errors
- [Elastic Agent] Events acknowledged rate /s
- [Elastic Agent] Output write batches
- [Elastic Agent] Output batch size

The following visualizations were added.

- [Elastic Agent] Events dropped rate /s
- [Elastic Agent] Events duplicate rate /s
- [Elastic Agent] Events failed rate /s
- [Elastic Agent] Events TooMany rate /s

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- I used https://github.com/elastic/mock-es to generate erros that would show up in dropped, duplicate, failed and TooMany visualization
- I used https://github.com/leehinman/spigot to generate events at predictable rates and verified those rates were reported by the visualizations

## How to test this PR locally

1. Install elastic-agent
2. Look at [Elastic Agent] Agent Metrics Dashboard

## Related issues

- Closes #9724

### Before
Screenshot 2024-05-30 at 13 59 16

### After
Screenshot 2024-05-30 at 14 04 35

### All Visualization

Screenshot 2024-05-22 at 19 17 50

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
@leehinman do you want to merge from upstream? The conflicts are probably me. Hoping I'll actually have time to get to this tomorrow.

**Comment by fearful-symmetry** [comment]
So, this is probably a _me_ problem, but I can't get the CPU usage dashboard to show anything? This is just the "default" elastic-package deployment (`elastic-package stack up`) with a system integration installed and agent metrics enabled to get more data. Can you verify this is working?

It looks like the visualization is aggregating from `system.process.cpu.total.value` and `elastic-agent.process`, and there are documents matching with those fields.

The query response shows that we have matching documents, but the aggregation isn't there.
```
{
  "rawResponse": {
    "took": 7,
    "timed_out": false,
    "_shards": {
      "total": 15,
      "successful": 15,
      "skipped": 14,
      "failed": 0
    },
    "hits": {
      "total": 75,
      "max_score": null,
      "hits": []
    }
  }
}
```

Again, might just me being dumb, but it seems odd, since the Memory Usage and Open Handles metrics are working fine?
 
Screenshot 2024-06-05 at 1 49 14 PM

**Comment by leehinman** [comment]
> Can you verify this is working?

I didn't touch the "CPU Usage" chart, but I figured out what is wrong.  It is the fact that the data view is set to "auto" and we only get events every minute.  So if auto picks buckets that are smaller than one minute (which is what happens with default 15 min time picker) Some of the buckets have no data, and things like derivations don't work.   :-( 

fix coming soon.

**Comment by leehinman** [comment]
@fearful-symmetry try it now

**Review by fearful-symmetry — APPROVED** [review]

**Comment by jlind23** [comment]
@leehinman @pierrehilbert is this good to be merged?

**Comment by leehinman** [comment]
> @leehinman @pierrehilbert is this good to be merged?

Marius is out on paternity leave, I added Joe Reuter as reviewer, I'd like someone with a bit more Dashboard experience to review just to make sure I'm not missing something.

**Review by flash1293 — COMMENTED** [review]
Thanks for this. Some comments.

I ran this on some sample data and the first chart errors out for me:

Screenshot 2024-06-13 at 15 01 10

Didn't dig deeper on why that's happening, but it seems to be a TSVB vis, is there a reason for this? By my understanding we shouldn't use TSVB unless absolutely required.

In terms of the charts - all the time series charts are pretty dense and the y axis label doesn't really add much as the title is explaining it quite well already - I think we can omit them:
Screenshot 2024-06-13 at 15 03 45

For the x axis, it's pretty much the same - IMHO we can just remove the label here, the "per minute" is more confusing than helpful as we normalize the value per second anyway:
Screenshot 2024-06-13 at 15 04 07

**Comment by leehinman** [comment]
> Thanks for this. Some comments.
> 
> I ran this on some sample data and the first chart errors out for me:
> Screenshot 2024-06-13 at 15 01 10
> 
> Didn't dig deeper on why that's happening, but it seems to be a TSVB vis, is there a reason for this? By my understanding we shouldn't use TSVB unless absolutely required.


Looks like this was done when Dashboards were first made.  I'm going to leave it as TSVB until Marius bets back and we can ask him about it, since he did the original work.

I think the error is "too much data", and I'm guessing that is because I set the interval to "1m", I switched it to ">=1m", lets see if that fixes it.  If we go less than 1m, we have a different problem.

> 
> In terms of the charts - all the time series charts are pretty dense and the y axis label doesn't really add much as the title is explaining it quite well already - I think we can omit them: Screenshot 2024-06-13 at 15 03 45
> 

I didn't find a way to "remove" the text, I can change it to " ", so nothing shows up, but I can't seem to remove it totally and reclaim the space.  Do you know of a better way?

> For the x axis, it's pretty much the same - IMHO we can just remove the label here, the "per minute" is more confusing than helpful as we normalize the value per second anyway: Screenshot 2024-06-13 at 15 04 07

These are automatically added, so I could remove the "@timestamp" part of "@timestamp per minute", but I didn't find a way to remove the "per minute" part.  Any ideas?

**Comment by leehinman** [comment]
Updated dashboards look like:

Screenshot 2024-06-13 at 15 15 08

**Comment by flash1293** [comment]
> I think the error is "too much data", and I'm guessing that is because I set the interval to "1m", I switched it to ">=1m", lets see if that fixes it. If we go less than 1m, we have a different problem.

That should work 👍 

> I didn't find a way to "remove" the text, I can change it to " ", so nothing shows up, but I can't seem to remove it totally and reclaim the space. Do you know of a better way?

You can remove the axis titles in the axis menu like this:

Screenshot 2024-06-17 at 08 54 43

**Comment by leehinman** [comment]
@flash1293 Thanks for the help on the axis titles.  2 of the the panels are different and don't have those options, but I got it fixed on the rest.  screenshot below.

Screenshot 2024-06-18 at 08 47 38

**Comment by flash1293** [comment]
yeah, for tsvb you can't remove it I think - LGTM from the dashboard side based on the screenshots

**Pull request merged**
