### PR TITLE
[fortinet_fortimanager] Add more ECS fields mappings

### PR DESCRIPTION
**Pull request by aleksmaus**
## Proposed commit message

Add more ECS fields mappings.

The following mappings were requested to be added in the original issue

```
srcip --> source.ip
srcname --> source.domain
srcport --> source.port
dstip --> destination.ip
dstname --> destination.domain
dstcountry --> destination.geo.country_name
unauthuser --> user.name
sentbyte --> source.bytes
rcvdbyte --> destination.bytes
osname --> os.name
direction --> network.direction
crlevel --> risk.static_level
crscore --> risk.static_score_norm
apprisk --> event.risk_score
appcat --> event.category
```

The following fields mapping changed during this PR review:
```
appcat --> rule.category
srcname --> source.address
dstname --> destination.address
```

The following fields are not mapped with this PR still, because it is unclear how to map them yet, based on the examples of logs that we received. For example: 

It's not clear at the moment how to map `apprisk` to `event.risk_score` values.
[3] parsing field value failed: field "event.risk_score"'s Go type, string, does not match the expected field type: float (field value: elevated)

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by taylor-swanson** [comment]
> The appcat value from the actual logs doesn't quite match the expectations for ECS event.category

Even if you normalized those values into an array, the bigger issue is that `event.category` only has a [limited set of allowed values](https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-category.html). In this case, `event.category` nor `event.risk_score` are not good fits here. For reference, `fortinet_fortigate` moves `appcat` into `rule.category`.

**Comment by aleksmaus** [comment]
> or reference, `fortinet_fortigate` moves `appcat` into `rule.category`.

we could do the same for this integration

**Comment by aleksmaus** [comment]
> > or reference, `fortinet_fortigate` moves `appcat` into `rule.category`.
> 
> we could do the same for this integration

or leave as is.

please cast your ballots

**Comment by taylor-swanson** [comment]
I would say align with fortigate ([as seen here](https://github.com/elastic/integrations/blob/main/packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/utm.yml#L150)).

**Comment by aleksmaus** [comment]
> I would say align with fortigate ([as seen here](https://github.com/elastic/integrations/blob/main/packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/utm.yml#L150)).

image

**Review by taylor-swanson — COMMENTED** [review]
I think `srcname` and `dstname` should move to `source.address`/`destination.address`, since looking at the example logs, we see instances of both an IP address and a hostname in there.

The *.address fields say this in ECS:
> Some event source addresses are defined ambiguously. The event will sometimes list an IP, a domain or a unix socket. You should always store the raw address in the .address field.
Then it should be duplicated to .ip or .domain, depending on which one it is.

I've used the convert processor (with type `ip`) to figure out if the value should end up in `.ip` or `.domain`.

I really wish a processor could this automatically for us...

Other changes LGTM.

**Review by taylor-swanson — APPROVED** [review]

**Pull request merged**
