### PR TITLE
[AWS Fargate] Remove memory.usage.pct field

### PR DESCRIPTION
**Pull request by lucian-ioan**
## Proposed commit message
Remove `memory.usage.pct` field and use `memory.usage.total` instead for plain memory usage.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally
[Blog post](https://www.elastic.co/blog/elastic-agent-monitor-ecs-aws-fargate-elastic-observability?utm_source=GaggleAMP-Elastic&utm_medium=LinkedIn%20(GaggleAMP)&utm_campaign=none%20(GaggleAMP)&utm_content=in-this-step-by-step-guide-youll-learn-how-to-install-the-elas-4077423) for setting up the integration with Elastic container sidecar.

## Related issues

- #8129 

## Screenshots

Before:
before

After:
aws

### CODE REVIEW

**Review by zmoog — CHANGES_REQUESTED** [review]
I suggest to align the PR title and description, stating that it removes the `memory.usage.pct` field.

**Review by zmoog — APPROVED** [review]
LGTM.

Since this is a beta data stream, it seems okay to remove a field. WDYT @lalit-satapathy?

**Comment by agithomas** [comment]
@lucian-ioan , as per the inputs mentioned in the SDH, it is best to have the below information represented as Metrics panel

- Soft limit
- Hard limit
- Hierarchical limit 

This is good considering we are removing the memory utilisation percentage information from the dashboard.

**Comment by lucian-ioan** [comment]
@agithomas Currently, we are not collecting some limits at input level which is why I chose not to include them.

Should I look into it and open a PR in beats?

**Comment by agithomas** [comment]
> Should I look into it and open a PR in beats? The issue is this will delay this PR and the AWS Fargate to GA quite a bit.

From the SDH it is clear that the customers are looking for the memory utilisation information. So, it is highly recommend to have the limits collected and shown in the dashboard . This can be taken up after making GA as well,  but must be taken up at the earliest. 

Is there any immediate requirement to make AWS Fargate GA? 

cc @tommyers-elastic , @lalit-satapathy

**Comment by lucian-ioan** [comment]
> @lucian-ioan , as per the inputs mentioned in the SDH, it is best to have the below information represented as Metrics panel
> 
> * Soft limit
> * Hard limit
> * Hierarchical limit
> 
> This is good considering we are removing the memory utilisation percentage information from the dashboard.


Retrieved task metadata using AWS CLI and the instructions in the official [Amazon ECS documentation](https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-metadata-endpoint-v4-fargate.html).

1. Soft Limit - not reported by AWS
2. Hard Limit is available via `${ECS_CONTAINER_METADATA_URI_V4}/task`
> ```
>     Limits": {
>         "CPU": 1024,
>         "Memory": 3840
>       }
> ```
3. Hierarchical Memory Limit is available via `${ECS_CONTAINER_METADATA_URI_V4}/task/stats`

Since Soft Limit is not as important, I will proceed with the appropriate changes in beats shortly.

**Comment by mrodm** [comment]
Hi @lucian-ioan, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

**Comment by lucian-ioan** [comment]
Tested this with 8.12.0 and it will be ready for review as soon as 8.12.0 releases on the 9th of Jan.

**Review by agithomas — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
@lucian-ioan , can we have this merged, based on your [comment](https://github.com/elastic/integrations/pull/8254#issuecomment-1874109149) ?

**Comment by lucian-ioan** [comment]
@agithomas, beats release schedule changed, testing now with the new 8.11.4 minor version which was released late last week.

Expecting to be done later today or tomorrow.

**Comment by lucian-ioan** [comment]
I think the memory limit makes the most sense in the table, WDYT @agithomas ?

screencapture-elastic-package-test-serverless-c10976-kb-us-east-1-aws-elastic-cloud-app-dashboards-2024-01-24-03_44_35

Opted for using `container_id` instead of the ECS name due to scenarios where the name could be the same for different containers.

**Comment by agithomas** [comment]
> I think the memory limit makes the most sense in the table, WDYT @agithomas ?

Please see my comment [here](https://github.com/elastic/integrations/pull/8254#issuecomment-1791893305)

**Comment by lucian-ioan** [comment]
Since the solution proposed in the [SDH](https://github.com/elastic/sdh-beats/issues/3817#issuecomment-1725757661), several observations:
- Soft Limit Memory is not reported by the AWS API
- Heirarchical Memory Limit is not container dependent and can be reported as a very high value
- Hard Memory Limit is always reported correctly per container

Since there can be many different hard limits, a plain counter wouldn't work in this case.

I think either a table or plotting them in the `Container Memory Usage` line chart to be able to compare them with the containers is suitable.

**Comment by agithomas** [comment]
> 2\. Plotting the limits in the `Container Memory Usage` line chart to be able to compare them

This may not be needed. I am afraid, this would lead to the  confusions that led to the original SDH.

**Comment by agithomas** [comment]
> 1. Table with columns for Max Container Memory Used and Container Memory Hard Limit

It it the one that is mentioned [here](https://github.com/elastic/integrations/pull/8254#issuecomment-1907276367) in the screenshot ?

**Comment by lucian-ioan** [comment]
yes @agithomas, it could also be Latest Memory Usage, Max Memory Usage and Hard Memory Limit as columns.

**Comment by lucian-ioan** [comment]
Made the changes discussed to the dashboard @agithomas, please let me know if they are ok:

awsfargate-integration-overview png

**Comment by agithomas** [comment]
LGTM!

**Pull request merged**
