### PR TITLE
[Cloud Security][Vulnerability Management] Add CloudFormation template link

### PR DESCRIPTION
**Pull request by amirbenun**
## What does this PR do?

Resolves https://github.com/elastic/integrations/issues/5434
## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by eyalkraft** [comment]
@amirbenun are we not getting an official s3 bucket from the infra team?

**Comment by amirbenun** [comment]
This is an intermediate solution just for the sake of having a working E2E flow.
Once we will have the production bucket there are 2 tasks that we have to accomplish:
1. Configure cloudbeat's CI to upload the template into the new bucket
2. Update the integration to the new URL

@oren-zohar should I open tasks for these 2?

**Review by opauloh — APPROVED** [review]
LGTM 🚀

**Comment by tehilashn** [comment]
@amirbenun - can this be merged?

**Pull request merged**
