### PR TITLE
[O11y][IIS] Migrate `Website Overview` dashboard visualizations to lens in kibana 8.5.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for IIS integration package

- Statistics for IIS Lens migration:

<html>
<body>

IIS dashboard | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics IIS] Website Overview | 0 | 15 | 14 | 1
  | 0 | 15 | 14 | 1

</body>
</html>

Note: 1 markdown panel has not been migrated because we don't have any alternatives in lens for markdown.
1-metricbeat-iis-application-pool-overview

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.5.0 itself.

## Related issues

- Relates #5221

### CODE REVIEW

**Comment by milan-elastic** [comment]
Thanks, @rajvi-elastic ! Approved!

**Review by milan-elastic — APPROVED** [review]

**Comment by agithomas** [comment]
@SubhrataK , i am really not sure if Red colour is a good colour to choose service uptime, especially when service uptime value is really a high value. Can you suggest an appropriate theme or colour here?

**Comment by rajvi-elastic** [comment]
> I think there is something fundamentally wrong with Total Get Request , Total Post Request, Total Put Request, Total Delete Request title and the visualisation values shown in the graph.
> 
> If the field is capturing the Total value, the graph is expected to show an increasing trend.
> 
> If the field is capturing the value at a given time, then the title is wrong, it should not be Total. It must be Get Request / Sec. I do not think it is the case as there exist a dashboard already.
> 
> So, you may want to see the value that you are populating to generate the graph.

@agithomas, Updated the screenshot.

**Review by agithomas — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
Please complete the peer review

**Review by milan-elastic — APPROVED** [review]

**Pull request merged**
