### PR TITLE
[Jolokia Input] Add HTTP Options

### LINKED ISSUE #11627: [Jolokia Input] Add HTTP Options
# Add HTTP Options

Currently this integration does not support configuring credentials to access the Jolokia endpoint.

Assuming that the security layer implemented via basic authentication, even if minimal, is extremely suitable for cases of production environments, the improvement request here is to make this configuration option available in this integration.

[Jolokia Security doc](https://jolokia.org/reference/html/manual/security.html)

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists, [useful guidelines](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md) to follow
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

### PR DESCRIPTION
**Pull request by MatheusGelinskiPires**
- Enhancement

## Proposed commit message

Added HTTP Options [...]

The jolokia unsecured agent might be useful for a quick evaluation. It should not be used for production environments.
This PR enabled the use of a Jolokia secured agent by implementing the same HTTP options from the [Prometheus Integration](https://github.com/elastic/integrations/blob/main/packages/prometheus/data_stream/collector/agent/stream/stream.yml.hbs#L41)

[...]  and http_method parameter (default to GET).

The http_method parameter was hardcoded (as GET).
Here is the [doc ](https://jolokia.org/reference/html/manual/jolokia_protocol.html) suggesting the use of POST method for more complex ObjectNames.
Having a configurable option could add more capabilities for this integration as well.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [x] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## Author's Checklist

- [x] Ensure Jolokia best practices for production as the insecured agent should be used just for testing purposes as described [here](https://jolokia.org/reference/html/manual/agents.html#agent-war-security)

## How to test this PR locally

1. Setup a Jolokia Agent (secured) endpoint
2. Install Elastic Agent on some host
3. Create a Fleet Policy
4. Add the Jolokia Input Integration to the Fleet Policy
5. Configure the integration with the endpoint, http_method (to POST), username and password (advanced settings)
6. Check the metrics being collected by Elastic Agent.

## Related issues

- Closes #11627

## Screenshots

Jolokia Agent (secured) endpoint

image

Jolokia Input integration page

image

Jolokia Input integration config (endpoint and method)

image

Jolokia Input integration config (username and password)

image

Jolokia Input Integration status (Elastic Agent)

image

Metrics being collected

image

### CODE REVIEW

**Comment by ishleenk17** [comment]
@MatheusGelinskiPires : Thanks for the enhancement. 
So basically we are adding the HTTP config options as per [this](https://www.elastic.co/guide/en/beats/metricbeat/master/configuration-metricbeat.html#module-http-config-options). Have we tested out with these new config parameters other than username/password ?

Also for the HTTP_Method, IIRC there were some issues with the POST http_method hence it was defaulted to GET for Tech Preview release. 
Is the POST method working fine for you ?

**Comment by MatheusGelinskiPires** [comment]
> @MatheusGelinskiPires : Thanks for the enhancement. So basically we are adding the HTTP config options as per [this](https://www.elastic.co/guide/en/beats/metricbeat/master/configuration-metricbeat.html#module-http-config-options). Have we tested out with these new config parameters other than username/password ?
> 
> Also for the HTTP_Method, IIRC there were some issues with the POST http_method hence it was defaulted to GET for Tech Preview release. Is the POST method working fine for you ?

Not yet but I can test the other options by the end of this week.

The POST method is working fine so far (I am doing some tests with Oracle WebLogic mbeans).

**Comment by MatheusGelinskiPires** [comment]
> > > @MatheusGelinskiPires : Thanks for the enhancement. So basically we are adding the HTTP config options as per [this](https://www.elastic.co/guide/en/beats/metricbeat/master/configuration-metricbeat.html#module-http-config-options). Have we tested out with these new config parameters other than username/password ?
> > > Also for the HTTP_Method, IIRC there were some issues with the POST http_method hence it was defaulted to GET for Tech Preview release. Is the POST method working fine for you ?
> > 
> > Not yet but I can test the other options by the end of this week.
> > 
> > The POST method is working fine so far (I am doing some tests with Oracle WebLogic mbeans).
> 
> Changes look good. 
> Thanks, please keep this thread posted once the other options are tested. I'll aprove it thereafter. 

Hello, I will be testing the other options this week and keep this thread updated.

Thx

**Comment by MatheusGelinskiPires** [comment]
Tests with an SSL endpoint (certificate globally valid) and ssl verification mode set to 'full' -> success!

endpoint with certificate

Captura de tela 2024-12-16 173422

jolokia endpoint

Captura de tela 2024-12-16 173446

jolokia integration config

Captura de tela 2024-12-16 173626

jolokia integration config (ssl verification mode)

Captura de tela 2024-12-16 173637

validation

Captura de tela 2024-12-16 173736

I will try to test it using a self signed certificate as well to validate the other related configuration

**Comment by MatheusGelinskiPires** [comment]
Tests with an SSL endpoint (self signed certificate) and ssl verification mode set to 'full' -> success!

endpoint with certificate (notice that I didn't imported the CA to my browser)

Captura de tela 2024-12-16 182446

jolokia endpoint

Captura de tela 2024-12-16 182501

jolokia integration config

Captura de tela 2024-12-16 183419

jolokia integration config (ssl verification mode)

Captura de tela 2024-12-16 183451

validation

Captura de tela 2024-12-16 183517

Captura de tela 2024-12-16 183547

@ishleenk17 , let me know if any other validation should be done in this PR

thanks!

**Review by ishleenk17 — APPROVED** [review]

**Pull request merged**
