### PR TITLE
[O11y][Stan] Migrate Channel Overview Metrics Dashboard Visualizations to Lens

### PR DESCRIPTION
**Pull request by milan-elastic**
### Urgency
- High

### Activity Type
- Enhancement

## What does this PR do?
- Manually migrate `Stan` visualizations to the lens in the current Kibana version `8.10.2` itself. 

- Statistics for `Stan` Lens migration:
## Migration stats
  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Vizualization | Lens | Vizualization
[Metrics Stan] Channel Overview Metrics | 0 | 2 | 2 | 0

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to the lens.
- [x] I have updated screenshots of the dashboard.
- [X] I have verified that the data counts are matching and panel aggregations are the same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.10.2 itself.

## Related issues

- Relates #7778 

## Screenshots

Before Migration:
metrics-stan-overview

After Migration:
metrics-stan-overview

### CODE REVIEW

**Review by rajvi-elastic — APPROVED** [review]
LGTM!

**Comment by tommyers-elastic** [comment]
would it be possible to see before/after images over the same time period to directly compare the charts?

**Comment by milan-elastic** [comment]
> would it be possible to see before/after images over the same time period to directly compare the charts?

Done @tommyers-elastic I have updated the before/after screenshot in description now!

**Review by tommyers-elastic — APPROVED** [review]
LGTM

**Review by MichaelKatsoulis — APPROVED** [review]
LGTM

**Pull request merged**
