### PR TITLE
cisco_{asa,ftd}: harmonise pipelines

### LINKED ISSUE #2116: Cisco package Needs sync with Beats module
There's a bunch of fixes to the Cisco module in Filebeat (esp. ASA and FTD) that haven't made their way into the cisco package:

- [ ] https://github.com/elastic/beats/pull/28325
- [ ] https://github.com/elastic/beats/pull/26879
- [ ] https://github.com/elastic/beats/pull/24744

Possibly more.

We should review the differences with the Filebeat module and update accordingly.

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

This brings the cisco_asa and cisco_ftd ingest pipelines more into agreement though parts dealing with ECS categorisation remain distinct.

The changes in cisco_asa do not affect test outcomes and are for the most part cosmetic to reduce diff noise in future changes. It does add the malware event kind classification that exists in cisco_ftd.

The changes in cisco_ftd fix incorrect handling of:
- network.inner/cisco.ftd.tunnel_type fields
- 305012 events.

And add the network.community_id field to events.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Close #2116

### CODE REVIEW

**Review by taylor-swanson — APPROVED** [review]
LGTM, only minor complaint is that the test file name `test-ftd-fix.log` is a little vague, but it's easy enough to look up the git commit to see what the fix is.

**Comment by efd6** [comment]
@taylor-swanson Yeah, I was following the existing naming convention. I'm happy to change it if you would like.

**Comment by taylor-swanson** [comment]
If you think of a good, short descriptive file name, go for it, otherwise I'm fine with it as-is.

**Comment by efd6** [comment]
I'll leave it as is.

**Pull request merged**
