### PR TITLE
Quality of life updates to ProblemChild and DGA packages

### PR DESCRIPTION
**Pull request by susan-shu-c**
## What does this PR do?

* #4820
* In this PR, we are not shipping dashboards

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by alvarezmelissa87 — APPROVED** [review]
Code LGTM ⚡

**Review by szeitlin — APPROVED** [review]

**Comment by ajosh0504** [comment]
I want to clean up some tags, and add an `ML` tag to rules while we're at it. I'll get to this tomorrow.

**Comment by ajosh0504** [comment]
Screenshots from testing:
- Changed package title `LotL Attack Detection` to `Living off the Land Attack Detection`
Screen Shot 2023-01-11 at 3 09 28 PM

- Changed package title `DGA Detection` to `Domain Generation Algorithm Detection`
Screen Shot 2023-01-11 at 3 09 40 PM

- ML job card title appears as `Living off the Land Detection` instead of `ProblemChild`
Screen Shot 2023-01-11 at 3 14 54 PM

- Changed ML job group for ProblemChild from `problem_child` to `living_off_the_land`
Screen Shot 2023-01-11 at 3 15 07 PM

- Updated/cleaned up tags for Living off the Land Attack Detection package. Also added the `ML` tag
Screen Shot 2023-01-11 at 3 20 28 PM

- Updated/cleaned up tags for Domain Generation Algorithm Detection package. Also added the `ML` tag
Screen Shot 2023-01-11 at 3 20 44 PM

**Comment by ajosh0504** [comment]
@SourinPaul Can you please review the above screenshots and make sure these changes are ok?

**Comment by ajosh0504** [comment]
@susan-shu-c I changed the `Domain Generation Algorithm` rule tags back to DGA for consistency, and since DGA is a relatively well-known term. Plus we are defining it in the package description. You good with that?

**Comment by susan-shu-c** [comment]
> 

I'm good that you changed it back, and agree that since it's in the package description, it'll be clear enough!

**Comment by SourinPaul** [comment]
> Can you please review the above screenshots and give a 👍 on the changes?

@ajosh0504 @susan-shu-c, the changes look great. Thanks for the ping.

**Pull request merged**
