### PR TITLE
[winlog] Preserve original event when toggled on

### PR DESCRIPTION
**Pull request by nicpenning**
- Bug

## Proposed commit message
See title.

This should resolve the winlog issue here: https://github.com/elastic/integrations/issues/9425

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues
- Relates https://github.com/elastic/integrations/issues/9425

## Screenshots
image

### CODE REVIEW

**Comment by nicpenning** [comment]
Need to split this PR for only winlog.

**Comment by nicpenning** [comment]
Clean up commits and added screenshot. Ready for tests!

**Review by marc-gr — APPROVED** [review]

**Comment by nicpenning** [comment]
Thank you!

**Comment by nicpenning** [comment]
Looks like we all missed the PR number in the changelog. Should that just get changed on the next update or should I do a quick PR with updating that changelog and not increment the changelog version number? (10198)

**Pull request merged**
