### PR TITLE
[Enhancement] Add ".caseless" fields to process events

### PR DESCRIPTION
**Pull request by w0rk3r**
## Proposed commit message

This PR adds `.caseless` fields for the process name and executable to improve compatibility with our Elastic Defend integration. This enables us to handle language limitations in KQL more effectively.

I'm also specifying the `.text` field as it was being removed from the markdown file otherwise.

Elastic Defend Mapping:

image

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

Build the integration, ingest sysmon or windows security logs.
## Related issues

- Resolves https://github.com/elastic/integrations/issues/9234
- Resolves https://github.com/elastic/integrations/issues/8913

## Screenshots

image
image

### CODE REVIEW

**Review by belimawr — APPROVED** [review]

**Comment by ishleenk17** [comment]
@w0rk3r : Can we get the CI green here ?

**Review by andrewkroh — CHANGES_REQUESTED** [review]
This introduces a new field into an ECS controlled namespace that is not defined in ECS. We need to commit this to the schema first so that it becomes standardized. This will allow us to use a uniform definition everywhere and it's easily importable. 

```
# fields.yml
- name: process.executable
  external: ecs
```

This additional multi-field will end up in the Elasticsearch [ecs@mappings](https://github.com/elastic/elasticsearch/blob/b4938e16457dc69d392235eaf404a6dad9ddb717/x-pack/plugin/core/template-resources/src/main/resources/ecs%40mappings.json) template meaning that all users of data streams can have a consistent mapping for these fields (even if they aren't using an integration).

Probably one reason that we have incompatibility with detection rules (https://github.com/elastic/integrations/issues/9234) is that the rule(s) are using fields which have not been defined in ECS. So if we can align ECS then any future integrations will just work.

---------


I also think we should debate alternative naming. My initial reaction was that calling this "lowercase" would be more clear because it conveys the fact that the value is being converted to lowercase.

**Comment by w0rk3r** [comment]
@andrewkroh @efd6, should I close this PR? From what I understand, changes made in https://github.com/elastic/ecs/pull/2341 will auto-add these fields. Is that right?

**Comment by andrewkroh** [comment]
The change to ECS won't make it into the ecs@mappings component template that's part of ES until probably 8.16.0. 

So if you don't want to wait we can proceed with this now that the fields are agree to in the schema.

**Pull request closed without merging**
