### PR TITLE
Add field definitions for default processors

### PR DESCRIPTION
**Pull request by mtojek**
## What does this PR do?

This PR adds field definitions for Beats processors enabled by default. Added as separate files for ease of further refactoring (temporary workaround).

I confirmed that duplicated field entries are fine for Kibana and Integrations.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [x] I have verified that all datasets collect metrics or logs.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by ruflin** [comment]
Did you add these with a script? If yes, should it be also checked in so in case we need to update the files, we can just run the script again?

**Comment by mtojek** [comment]
I hope this is a temporary workaround and we can come up with a more sophisticated solution next :)

I didn't use a script but a bash one-liner: `find . -name fields -exec cp ~/processors.yml {} \;`

**Comment by exekias** [comment]
Thank you @mtojek! Should we add this to the beats import script for now? While I agree we need a more definitive solution this is the only one for now. We plan to migrate many integrations during the 7.11 cycle, they would suffer from the same issues if we don't add it.


nit: Should we call this "agent.yml"? Not sure all fields are added by processors, some come from dynamic templates or the agent itself

**Comment by mtojek** [comment]
> Should we add this to the beats import script for now? 

Good idea, but I will add them in a follow-up PR. Let's first focus on existing integrations.

> nit: Should we call this "agent.yml"?

SGTM, will adjust it.

> Not sure all fields are added by processors, some come from dynamic templates or the agent itself

I would appreciate if you can help marking these fields.

**Comment by exekias** [comment]
> I would appreciate if you can help marking these fields.

My point was more about using agent instead of processors. I don't see any outstanding field so they are good to go from my POV.

Agree with @ruflin that we may want to update this after a change in the Agent, I'm wondering if a symlink would work here? Not sure if that may be a problem in Windows systems

**Comment by mtojek** [comment]
Let me give you an update on the iteration. I stripped some fields and now we went down from 71 to 35.

In details:

1. I renamed `processors.yml` to `agent.yml`.
2. Reviewed files for `host` family:
https://github.com/elastic/beats/blob/master/libbeat/metric/system/host/host.go
https://github.com/elastic/beats/blob/master/libbeat/processors/add_host_metadata/add_host_metadata.go
3. Reviewed files for `container` family:
https://github.com/elastic/beats/blob/master/libbeat/processors/add_docker_metadata/add_docker_metadata_test.go
4. Reviewed files for `cloud` family:
https://github.com/elastic/beats/tree/master/libbeat/processors/add_cloud_metadata (test files)

**Review by ruflin — APPROVED** [review]
LGTM. The only ones I spotted where I was not sure we need them are all of the `os.*` related. We probably only need a subset?

**Comment by mtojek** [comment]
Rechecked.

We can strip the `os.full` :)

**Pull request merged**
