### PR TITLE
Update owner of Kibana and Elasticsearch

### PR DESCRIPTION
**Pull request by ruflin**
In the past the owner of the elasticsearch and kibana package has been the integrations team. But the infra-monitoring-ui should be the owner of these packages.

### CODE REVIEW

**Comment by ruflin** [comment]
@jsoriano I assume I need to update the CODEOWNERS file manually?

**Review by mtojek — COMMENTED** [review]
> @jsoriano I assume I need to update the CODEOWNERS file manually?

Yes

If you want to release a new package with updated owners, you have to bump up the version for every package.

**Comment by ruflin** [comment]
Good to see CI failed because codeowners was not in sync. Updated it now.

No need to release a new package version for this.

**Comment by ruflin** [comment]
Seems like a I pushed a commit the source branch but the PR does not show it?!? https://github.com/ruflin/integrations/commit/c8e4b6ebb1baec9cf57277e0e5fc5ee406482e40

**Review by mtojek — APPROVED** [review]

**Comment by andrewkroh** [comment]
Should there be a "Team:" label in this repo for infra-monitoring-ui?

**Comment by jlind23** [comment]
@andrewkroh their label does not exist here: https://github.com/elastic/observability-dev/blob/main/.github/labels/github-labels.yml as soon as they add it it's gonna be available there.

**Comment by ruflin** [comment]
@matschaffer @smith @klacabane Could one of you also approve this change?

**Review by klacabane — APPROVED** [review]
Ownership accepted :)

**Pull request merged**
