### PR TITLE
[Okta] Removes edge processing

### LINKED ISSUE #660: Convert Okta's edge processing to Ingest Node pipeline
# Convert edge processing to Ingest Node pipeline

This package uses Beats processors for some of its data processing. We want to
move that processing into the ingest node pipeline that is part of the package
to make reuse easier (e.g. data from Kafka could be routed through the pipeline).

### Data Streams
- system (inputs: httpjson, log)
  - [x] All beats processors are removed
  - [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) added

### PR DESCRIPTION
**Pull request by P1llus**
## What does this PR do?

Removes the last bit of edge processing for the Okta package

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.

## Related issues

- Closes #660

### CODE REVIEW

**Comment by P1llus** [comment]
Need to resolve the event.original, as it should be passed, then it can be reviewed

**Comment by P1llus** [comment]
Seems like the current ES version set for the package is `^7.10` which means it does not support `copy_from` argument on `set` processors, as seen from the CI failure. So I can either set it differently, or I would need to bump the minimum version.

**Comment by andrewkroh** [comment]
Bump the version.

**Comment by P1llus** [comment]
jenkins test please

**Comment by P1llus** [comment]
jenkins run tests please

**Review by marc-gr — APPROVED** [review]

**Comment by P1llus** [comment]
Waiting for this to be resolved so that CI can be green: https://github.com/elastic/beats/issues/24310

**Review by andrewkroh — APPROVED** [review]
LGTM

**Pull request merged**
