### PR TITLE
Update package-registry to 1.0.0

### PR DESCRIPTION
**Pull request by jsoriano**

### CODE REVIEW

**Review by mtojek — APPROVED** [review]
Approved.

BTW I think that such simple PRs can be also left for dependabot to handle.

**Comment by jsoriano** [comment]
> Approved.
> 
> BTW I think that such simple PRs can be also left for dependabot to handle.

Oh good point, I just followed the script :slightly_smiling_face:

**Comment by mtojek** [comment]
Known flaky errors, have to ignore them until https://github.com/elastic/kibana/issues/107514 is solved.

**Comment by mtojek** [comment]
Known issues unfortunately.

**Pull request merged**
