### PR TITLE
[Apache] Add `condition` support to logs and metrics

### PR DESCRIPTION
**Pull request by BenB196**
## What does this PR do?

Enhancement - Adds support for setting [`condition`](https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html) to both Log file collection and metrics. This allows for defining this integration in a policy, but only having it run on during specific conditions.

Note: Log file (access/error) share a top-level `condition` value, and metrics is an independent value.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

Install new version, confirm that `condition` fields are available and can be set.

## Related issues

-

## Screenshots

image

image

### CODE REVIEW

**Comment by ishleenk17** [comment]
@BenB196 : Could you please specify a usecase for which you think this will be helpful in Apache Tomcat ?

**Comment by BenB196** [comment]
Hi @ishleenk17 this would be helpful for Apache as it would allow for having a single Elastic Agent policy that is applied to both hosts which have an Apache process running and hosts that do not. By leveraging the [`condition`](https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html) value, it can be specified which hosts this integration should be run on.

**Comment by ishleenk17** [comment]
> Hi @ishleenk17 this would be helpful for Apache as it would allow for having a single Elastic Agent policy that is applied to both hosts which have an Apache process running and hosts that do not. By leveraging the [`condition`](https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html) value, it can be specified which hosts this integration should be run on.

Any specific reason why we are focusing on single policy when the same can be attained by having 2 different policies?

**Comment by BenB196** [comment]
Hi @ishleenk17, while technically possible to do this via 2 policies this method will devolve into exponential (matrix multiplication) operational complexity.

One of the main reasons for the [`condition`](https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html) setting to exist in the first place is to avoid this problem of needing to use multiple different policies.

FWIW, this isn't a "new" concept, there are already a number of integrations which support this field: https://github.com/search?q=repo%3Aelastic%2Fintegrations+%22title%3A+Condition%22&type=code

**Comment by ishleenk17** [comment]
> Hi @ishleenk17, while technically possible to do this via 2 policies this method will devolve into exponential (matrix multiplication) operational complexity.
> 
> One of the main reasons for the [`condition`](https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html) setting to exist in the first place is to avoid this problem of needing to use multiple different policies.
> 
> FWIW, this isn't a "new" concept, there are already a number of integrations which support this field: https://github.com/search?q=repo%3Aelastic%2Fintegrations+%22title%3A+Condition%22&type=code

Sounds good. Thanks for your contribution @BenB196

**Review by ishleenk17 — APPROVED** [review]
Looks good!

**Pull request merged**
