### PR TITLE
[cisa_kev] Update logo to align w/ Elastic Integrations page

### PR DESCRIPTION
**Pull request by nicpenning**
- Bug
Simply updating logo so that the integration matches the logo here: https://www.elastic.co/integrations/data-integrations?search=cisa

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by nicpenning** [comment]
I have no clue why there are 180 build kite files in my PR 😖 ideas?

**Comment by efd6** [comment]
I think this touches too much for what the PR is trying to do. Can you retry?

**Comment by efd6** [comment]
You've dropped x on all the scripts. This is not what we want.

**Comment by nicpenning** [comment]
Strange. All I did was clone my repo and switch to a new branch, then added / updated my files. I will see how I can correct this.

Perhaps my Linux OS / visual studio code did somethingin between those steps. I may have to recreate this PR.

**Pull request closed without merging**
