### PR TITLE
Add syslog source - macos system.log

### PR DESCRIPTION
**Pull request by defensivedepth**
## What does this PR do?

Adds `/var/log/system.log` to default syslog input datastream for macOS.

Have been running this for quite some time:

image

image

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by defensivedepth** [comment]
FYI, just signed the agreement.

**Comment by belimawr** [comment]
@nimarezainia adding `/var/log/system.log` by default looks fine to me, do you see any reasons not to add it?

**Comment by defensivedepth** [comment]
Anything I can do to help move this forward?

**Comment by defensivedepth** [comment]
Yep this is still valid. Let me know what I can do to help move it along!

**Comment by belimawr** [comment]
I'll look into that again, sorry for the delay @defensivedepth !

**Comment by defensivedepth** [comment]
Anything I can do to help move this along?

**Comment by nimarezainia** [comment]
> @nimarezainia adding `/var/log/system.log` by default looks fine to me, do you see any reasons not to add it?

sorry for the extremely late response. I don;t see any issues here.

**Comment by cmacknz** [comment]
Adding `/var/log/system*` is correct on newer versions of MacOS.

To move this forward we just need the changelog updated in `packages/system/changelog.yml` to create a new version of the integration. You can see an example of how to do this in https://github.com/elastic/integrations/pull/5160/files. You need something like this:

```yaml
- version: "1.24.0"
  changes:
    - description: Add basic dimension fields for cpu, load and memory
      type: enhancement
      link: https://github.com/elastic/integrations/pull/1234
```

This change could be considered either a bug fix or new functionality, probably the latter makes more sense here so updating the version to `1.25.0` works.

**Comment by defensivedepth** [comment]
@cmacknz This PR currently uses `/var/log/system.log` - are you suggesting I change it to `/var/log/system*` ?

**Comment by cmacknz** [comment]
`/var/log/system.log` by itself seems correct. I am just used to writing wildcard paths so I did that automatically. `/var/log/system*` is probably safer if Apple ever changes the log rotation strategy.

On my MacOS Monterey system I see the following, where every time it rotates the previous file is compressed with the .gz extension which the integration ignores. 

```
system.log
system.log.0.gz
system.log.1.gz
system.log.2.gz
system.log.3.gz
system.log.4.gz
system.log.5.gz
system.log.6.gz
```

**Comment by defensivedepth** [comment]
Ok, I have updated the PR based on feedback from @cmacknz

**Review by cmacknz — APPROVED** [review]

**Comment by cmacknz** [comment]
You need to increase the package version in the manifest.yml file to match what is in the changelog:

https://github.com/elastic/integrations/blob/a7a076dbb2c61d6392a09f3d37bc72f6c32816fe/packages/system/manifest.yml#L4

```diff
diff --git a/packages/system/manifest.yml b/packages/system/manifest.yml
index b20180a28..43f732a0a 100644
--- a/packages/system/manifest.yml
+++ b/packages/system/manifest.yml
@@ -1,7 +1,7 @@
 format_version: 1.0.0
 name: system
 title: System
-version: 1.24.2
+version: 1.25.0
 license: basic
 description: Collect system logs and metrics from your servers with Elastic Agent.
 type: integration
```

**Comment by andrewkroh** [comment]
I fixed the manifest version and merged it with main. It should be good to merge assuming it goes green.

**Comment by defensivedepth** [comment]
Thanks @andrewkroh, I missed the notification that there was still a change needed!

**Pull request merged**
