### PR TITLE
[O11y][Nagios XI] Lens migration for visualizations to Kibana version 8.3.0

### PR DESCRIPTION
**Pull request by rajvi-elastic**
- Enhancement

## What does this PR do?
- Migrate visualizations to lens for Nagios XI integration package

- Statistics for Nagios XI Lens migration:

<html>
<body>

Nagios XI dashboard | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Metrics Nagios XI] Hosts Dashboard | 6 | 1 | 6 | 1
[Metrics Nagios XI] Overview | 5 | 1 | 5 | 1
[Metrics Nagios XI] Events Dashboard | 0 | 1 | 0 | 1
[Metrics Nagios XI] Services Dashboard | 10 | 2 | 10 | 1
  | 21 | 5 | 21 | 4

</body>
</html>

Note: One visualization is migrated to the new control panels. Count of visualization is 4 after migration because all the dashboards have 1 markdown visualization whose alternative is not available in Lens hence we have not migrated those.

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to lens.
- [X] I have updated screenshots of dashboard.
- [X] I have verified that data count are matching and panel aggregations are same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.3.0 itself.

## Related issues

- Relates #5221 

## Issues Identified
- In input control visualization, we can make dependency filters that strictly depend on each other but in new controls, dependency filtering is possible but filters are not required to be strict.  As per the [discussion](https://github.com/elastic/integrations/issues/4768#issuecomment-1429952042), this is the expected behavior of new controls.

### CODE REVIEW

**Review by kush-elastic — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
Please revisit the color usage for the below viz

image

**Comment by agithomas** [comment]
Encourage you to create Smaller PRs going forward - One PR for either one dashboard / datastream. 

There are two visualisation files but only one screenshot image updated. Please confirm on the number of modified dashboards

**Comment by rajvi-elastic** [comment]
> Please revisit the color usage for the below viz
> 
> image

@agithomas, In this integration we have only migrated one visualization to new control panels. Apart from that we haven't touched any panels. The functionality/color palette of those panels are same as before. This is just the lens migration PR so we won't be changing any behavior/files as a part of this PR otherwise it will mess it up. However, If you strongly feel that this change needs to be done then we can raise a separate issue for that and track them separately.

**Comment by rajvi-elastic** [comment]
> Encourage you to create Smaller PRs going forward - One PR for either one dashboard / datastream.
> 
> There are two visualisation files but only one screenshot image updated. Please confirm on the number of modified dashboards

@agithomas, I understand the number of changed files is quite big but only one visualization is migrated. This integration is not yet converted to by reference and because of that there is a separate file for each panel. When we are migrating dashboards to the newer versions, the new properties are being added and the version related properties (e.g., `coreMigrationVersion` and `migrationVersion`) are also getting updated. This is the reason behind increased number of file changes.  Hence, creating different PR for one visualization seems irrational. 

Yes, there are two visualization files but that doesn't mean it has two dashboards. The number of dashboards can be determined by the number of files falls under `packages/nagios_xi/kibana/dashboard` folder. This integration contains four dashbaords but we just updated the screenshot of one dashboard from which the panel was migrated.

**Comment by agithomas** [comment]
> The functionality/color palette of those panels are same as before.

Can you elaborate the colour scheme used in the old dashboard ? Please refer and compare the two panels (circled in blue) in old and new dashboard. 

Screenshot 2023-03-20 at 1 19 17 PM

**Comment by rajvi-elastic** [comment]
> Can you elaborate the colour scheme used in the old dashboard ?  Please refer and compare the two panels (circled in blue) in old and new dashboard.
> 
> Screenshot 2023-03-20 at 1 19 17 PM

@agithomas, the screenshot of the **[Metrics Nagios XI] Services Dashboard** ([uploaded with the integration package](https://github.com/elastic/integrations/blob/main/packages/nagios_xi/img/nagios_xi-service-dashboard-screenshot.png)) does not sync with the Kibana files. Can you please refer to the below screenshot to compare the migrated visualization:


**[Metrics Nagios XI] Services Dashboard before migration:** 
screencapture-storage-0-kb-us-central1-gcp-cloud-es-io-9243-app-dashboards-2023-03-20-14_35_33


**[Metrics Nagios XI] Services Dashboard After migration:** 
nagios_xi-service-dashboard-screenshot


As mentioned in description, only control panels are migrated. Apart from that everything is in lens.
**Old Control panels:**
image
**New control panels:**
image

**Comment by rajvi-elastic** [comment]
> Can you elaborate the colour scheme used in the old dashboard ? 

Regarding colors in mentioned panels, 

The custom colors are used in **Swap Usage [Metrics Nagios XI]** and **Root Partition [Metrics Nagios XI]**.
image

The default color is used in **Swap Usage Gauge [Metrics Nagios XI]** and **Root Partition Gauge [Metrics Nagios XI]**.
image

**Comment by agithomas** [comment]
Thanks for sharing the details.

**Comment by agithomas** [comment]
@rajvi-elastic , any progress on this PR?

**Comment by rajvi-elastic** [comment]
> @rajvi-elastic , any progress on this PR?

@agithomas, In this integration, only one old control panel has been migrated to the new controls. And splitting this PR into multiple ones (either based on data-stream or dashboard) would be difficult because one file could belong to the both PRs. So we are waiting for your review only.

**Review by agithomas — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
I see that the screenshot that is deleted and the screenshot that is added are totally different. Please explain why?

**Comment by rajvi-elastic** [comment]
> I see that the screenshot that is deleted and the screenshot that is added are totally different. Please explain why?

Can you please refer to this [comment](https://github.com/elastic/integrations/pull/5573#issuecomment-1475894746). I have mentioned over there. Please let me know if you need more information for the same.

**Review by agithomas — APPROVED** [review]
LGTM

**Pull request merged**
