### PR TITLE
Add additional checks for event.original already existing into Azure firewall logs integration ingest pipeline

### PR DESCRIPTION
**Pull request by tommyers-elastic**
## What does this PR do?

Add additional checks for event.original already existing into Azure firewall logs integration ingest pipeline

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by philippkahr** [comment]
Can we make sure that this processor is the same in all integrations?

**Comment by philippkahr** [comment]
>i think it's kinda crazy each integration repeats these processors anyway. is there any reason not to move this into a higher level final pipeline?

I see a few problems:
* In the Azure integration I want to preserve `event.original`
* In the AWS Integration I don't want to preserve `event.original`

Some sort of tag must be send to the final pipeline, so it actually knows when to set it and when not.

Problem: Custom ingest pipelines. what if those heavily modify the message field, or even drop it? Then the final pipeline won't be able to create the event.original, since message is missing, or something else happened.

**Comment by zmoog** [comment]
@philippkahr, the `event.original` field is [preserved or removed](https://github.com/elastic/integrations/blob/f68d2b96cbd3c8ed988fc745fcaf20bb0165ec9e/packages/azure/data_stream/firewall_logs/elasticsearch/ingest_pipeline/default.yml#L237-L241) from the document according to the presence of the `preserve_original_event` tag. This tag is a data stream-level option.

The change in this PR handles an edge case that can happen the pipeline receives an event with both `message` and `event.original` fields.

(IIRC) This change was first introduced when Logstash changed its default behavior a few months ago and added `event.original`.

**Comment by mbudge** [comment]
Also seeing error.message: field [event.original] already exists rename in the azure application gateway logs with preserve original log disabled.

**Comment by zmoog** [comment]
> Also seeing error.message: field [event.original] already exists rename in the azure application gateway logs with preserve original log disabled.

Yep, this can happen at the beginning of the ingest pipeline execution if the document has both `message` and `event.original`.

@mbudge, is it still happening with integration version 1.5.9? Can you provide a sample log causing the error if it does happen?

**Comment by mbudge** [comment]
We've upgraded to 8.6.2 but the latest azure firewall/application gateway integration is 1.5.8.

As soon as 1.5.9 is available for upgrade we'll test it.

**Comment by mbudge** [comment]
Just upgraded to 1.5.9 and the original event issue is fixed in data_stream.dataset: azure.firewall_logs

The firewall integration has a grok parsing error, I'll share with support.

We're still getting the error "field [event.original] already exists rename" this dataset in v1.5.9

data_stream.dataset: azure.application_gateway

**Comment by zmoog** [comment]
> The firewall integration has a grok parsing error, I'll share with support.

Feel free to also open a public GitHub issue with the failing log event. Please redact any PII or account-identifiable information before sharing it.

> We're still getting the error "field [event.original] already exists rename" in data_stream.dataset: azure.application_gateway

You're right! 

Fixing this with https://github.com/elastic/integrations/pull/5361

**Comment by zmoog** [comment]
> The firewall integration has a grok parsing error, I'll share with support.

We added unsupported message patterns with https://github.com/elastic/integrations/pull/5382. Thank you for sharing a sample log.

Integration version 1.5.11 should be available for an upgrade shortly after the automation bot says it is ready with a comment in the PR.

**Pull request merged**
