### PR TITLE
[system] Windows Security dashboard fix (adds windows.forwarded)

### LINKED ISSUE #10431: [system] Windows Security - Use Managment Events dashboard missing forwarded events
It seems that the windows.forwarded is missing from some visualizations resulting in missing data:

image

Exploring these visuals in discover look something like this:

image

Note that the dataset is set twice. Likely the solution is to remove the search query in the bar with the dataset since it is redundant.

Removing that part of the search filter provides results like so:
image

### PR DESCRIPTION
**Pull request by nicpenning**
- Bug

## Proposed commit message

See title and Issue -> This fixes some discrepancies with some searches and visuals that did not include windows.forward. This adds that as an OR to make sure those events are included in all of the Windws Security dashboards.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues
- Closes #10431

### CODE REVIEW

**Review by marc-gr — APPROVED** [review]

**Comment by nicpenning** [comment]
Not sure what to do with this 75% code coverage. Is this stalled on my behalf? Please let me know how to proceed on this 😀 itching for these fixes.

**Comment by nicpenning** [comment]
Looks like conflicts are starting to set in could someone please review soon?

**Comment by nicpenning** [comment]
Resolved conflicts.

**Comment by nicpenning** [comment]
👋 just checking in. Please let me know how to proceed.

**Comment by andrewkroh** [comment]
I believe this requires the review of @elastic/obs-infraobs-integrations because of how CODEOWNERS is configured relating to the dashboards directory.

**Comment by nicpenning** [comment]
Yet another PR approved and now I have more conflicts to resolve. Am I missing something here?

**Comment by nicpenning** [comment]
Conflict resolved. I know that it is assigned to elastic/obs-infraobs-integrations and elastic/sec-linux-platform but it has little to do with either of those teams, especially Linux since this is a Windows Security dashboard. Please advise!

**Review by nfritts — APPROVED** [review]

**Comment by nicpenning** [comment]
Resolved conflicts, again.

**Review by muthu-mps — APPROVED** [review]
Code owner approval.

**Pull request merged**
