### PR TITLE
[TSDB] [Postgres] TSDB Enablement of Datastream - Activity

### PR DESCRIPTION
**Pull request by agithomas**
Type of change

- Enhancement

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by ritalwar — APPROVED** [review]
LGTM!

**Comment by agithomas** [comment]
PR blocked on https://github.com/elastic/kibana/issues/153220

**Comment by lalit-satapathy** [comment]
> PR blocked on [elastic/kibana#153220](https://github.com/elastic/kibana/issues/153220)

Need to decide whether its fine to upgrade the package version to 8.8, since the dimension fix above is available in 8.8

**Comment by lalit-satapathy** [comment]
@agithomas, Anything pending on this? Can we merge the dimension PRs? 8.8.0 can be added in future PR.

**Review by ritalwar — APPROVED** [review]
LGTM!

Please take care of dimension field limits in TSDB default enablement PR.

**Pull request merged**
