### PR TITLE
[O11y][AWS] Add global filter for dashboards to improve performance of AWS Integration package

### PR DESCRIPTION
**Pull request by milan-elastic**
- Enhancement

## Proposed commit message

Added global filter for below dashboards to improve performance,

- [Logs AWS] API Gateway Overview  (Unlinked saved search hence screenshot is not required)
- [Logs AWS] CloudTrail (Unlinked saved search hence screenshot is not required)
- [Logs AWS] ELB Access Log Overview 
- [Logs AWS] EMR Overview  (Unlinked saved search hence screenshot is not required)
- [Metrics AWS] EMR Overview
- [Metrics AWS] S3 Overview
- [Metrics AWS] Overview

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates #10200 

## Screenshots

<details>
  <summary>[Logs AWS] ELB Access Log Overview</summary>

| Before| After|
|:-:|:-:|
| Logs AWS  ELB Access Log Overview - Before | Logs AWS  ELB Access Log Overview - After |
</details>

<details>
  <summary>[Metrics AWS] EMR Overview</summary>

| Before| After|
|:-:|:-:|
| Metrics AWS  EMR Overview - Before | Metrics AWS  EMR Overview - after |
</details>

<details>
  <summary>[Metrics AWS] S3 Overview</summary>

| Before| After|
|:-:|:-:|
| metrics aws  s3 overview - before | metrics aws  s3 overview - after |
</details>

<details>
  <summary>[Metrics AWS] Overview</summary>

| Before| After|
|:-:|:-:|
| aws  metrics overview - before | aws  metrics overview - after |
</details>

### CODE REVIEW

**Review by harnish-elastic — APPROVED** [review]

**Review by mbondyra — APPROVED** [review]
LGTM 👌🏼

**Comment by agithomas** [comment]
As you have already taken the screenshot, are you planning to update the package screenshot images (with the dataset filter)

**Comment by agithomas** [comment]
Curious, why the error count, total count, and throttled count appear with decimal places.

Are there issues with the formula? If there is a problem, kindly create a backlog issue for further analysis. 


image

**Comment by harnish-elastic** [comment]
> Curious, why the error count, total count, and throttled count appear with decimal places.
> 
> Are there issues with the formula? If there is a problem, kindly create a backlog issue for further analysis.
> 
> image

Created backlog issue https://github.com/elastic/integrations/issues/10695

**Comment by harnish-elastic** [comment]
> As you have already taken the screenshot, are you planning to update the package screenshot images (with the dataset filter)

No, the dashboards having only change of filter. Also we have used mock data as well to populate some panels to cross check there are no issues after adding the filter.

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
