### PR TITLE
Backport fixes from 7.8

### PR DESCRIPTION
**Pull request by fearful-symmetry**
This is the culmination of a number of fixes we deployed yesterday as part of 7.8. That development happened against the `package-storage` repo, so this picks out the changes and puts them back where they belong.

Note that I haven't gotten around to testing this yet, as I'm running into some issues with ES on master.

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
Alright, testing now. No mapping conflicts, but still seeing unknown mapping errors from..something.

**Comment by mtojek** [comment]
> Alright, testing now. No mapping conflicts, but still seeing unknown mapping errors from..something.

If this is still relevant, could you please post more details?

**Comment by fearful-symmetry** [comment]
@mtojek Tried this again with the current 8.0.0 snapshot containers and what's in master. This is an event from the `socket_summary` metricset. All Those "no cached mapping" fields are present in the `fields.yml` doc for that metricset. This only started happening after I added `ecs.yml` docs to the fields.
Screen Shot 2020-06-24 at 1 59 53 PM

**Comment by mtojek** [comment]
@kaiyan-sheng wasn't a similar problem for the aws package?

**Comment by fearful-symmetry** [comment]
@mtojek She had an issue related to the `package-fields.yml` files. I had that same issue. I don't think @kaiyan-sheng had the `ecs` issue I'm running into?

**Comment by mtojek** [comment]
I thought about a different issue, one with refreshing fields.

**Comment by fearful-symmetry** [comment]
Yah, this issue can be fixed by refreshing the fields. We just shouldn't have to.

**Pull request merged**
