### PR TITLE
Box Consolidate Shield Events (#4464) Rebased (#4562) squashed

### PR DESCRIPTION
**Pull request by djptek**
This PR squashes changes from the rebase (#4562) of the Box Consolidate Shield Events (#4464)

- [x] check changes limited to scope of box_events package
- [x] re-run test suite
- [x] connect to target data source and ingest data
- [x] validate dashboards

### CODE REVIEW

**Comment by djptek** [comment]
## check changes limited to scope of box_events package

Screenshot 2022-11-07 at 17 40 39

OK

**Comment by djptek** [comment]
## re-run test suite

```
% elastic-package test                                                              (box_consolidate_shield_events_pick)integrations
Run test suite for the package
Run system tests for the package
2022/11/07 17:40:33  INFO Write container logs to file: /Users/djptek/github/integrations/build/container-logs/box-http-1667839233088260000.log
--- Test results for package: box_events - START ---
╭────────────┬─────────────┬───────────┬───────────┬────────┬───────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME │ RESULT │  TIME ELAPSED │
├────────────┼─────────────┼───────────┼───────────┼────────┼───────────────┤
│ box_events │ events      │ system    │ httpjson  │ PASS   │ 30.013960742s │
╰────────────┴─────────────┴───────────┴───────────┴────────┴───────────────╯
--- Test results for package: box_events - END   ---
Done
Run asset tests for the package
--- Test results for package: box_events - START ---
╭────────────┬─────────────┬───────────┬─────────────────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME                                                           │ RESULT │ TIME ELAPSED │
├────────────┼─────────────┼───────────┼─────────────────────────────────────────────────────────────────────┼────────┼──────────────┤
│ box_events │             │ asset     │ dashboard box_events-ce6fbf50-2df9-11ed-8003-6d5721603181 is loaded │ PASS   │        823ns │
│ box_events │             │ asset     │ dashboard box_events-ff3d9940-2e03-11ed-8003-6d5721603181 is loaded │ PASS   │        119ns │
│ box_events │ events      │ asset     │ index_template logs-box_events.events is loaded                     │ PASS   │        194ns │
│ box_events │ events      │ asset     │ ingest_pipeline logs-box_events.events-0.3.0 is loaded              │ PASS   │        173ns │
╰────────────┴─────────────┴───────────┴─────────────────────────────────────────────────────────────────────┴────────┴──────────────╯
--- Test results for package: box_events - END   ---
Done
Run pipeline tests for the package
--- Test results for package: box_events - START ---
╭────────────┬─────────────┬───────────┬───────────────────────────────┬────────┬──────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME                     │ RESULT │ TIME ELAPSED │
├────────────┼─────────────┼───────────┼───────────────────────────────┼────────┼──────────────┤
│ box_events │ events      │ pipeline  │ test-anomalous-download.log   │ PASS   │  14.811003ms │
│ box_events │ events      │ pipeline  │ test-copy.log                 │ PASS   │   7.655861ms │
│ box_events │ events      │ pipeline  │ test-create.log               │ PASS   │    5.00129ms │
│ box_events │ events      │ pipeline  │ test-download.log             │ PASS   │   5.663527ms │
│ box_events │ events      │ pipeline  │ test-event-types.log          │ PASS   │  78.028062ms │
│ box_events │ events      │ pipeline  │ test-malicious-content.log    │ PASS   │  22.709285ms │
│ box_events │ events      │ pipeline  │ test-preview.log              │ PASS   │   5.726704ms │
│ box_events │ events      │ pipeline  │ test-rename.log               │ PASS   │   7.466513ms │
│ box_events │ events      │ pipeline  │ test-suspicious-locations.log │ PASS   │  16.128386ms │
│ box_events │ events      │ pipeline  │ test-suspicious-sessions.log  │ PASS   │   8.627854ms │
│ box_events │ events      │ pipeline  │ test-trash.log                │ PASS   │   5.983108ms │
│ box_events │ events      │ pipeline  │ test-upload.log               │ PASS   │    6.16515ms │
╰────────────┴─────────────┴───────────┴───────────────────────────────┴────────┴──────────────╯
--- Test results for package: box_events - END   ---
Done
Run static tests for the package
--- Test results for package: box_events - START ---
╭────────────┬─────────────┬───────────┬──────────────────────────┬────────┬──────────────╮
│ PACKAGE    │ DATA STREAM │ TEST TYPE │ TEST NAME                │ RESULT │ TIME ELAPSED │
├────────────┼─────────────┼───────────┼──────────────────────────┼────────┼──────────────┤
│ box_events │ events      │ static    │ Verify sample_event.json │ PASS   │  53.495691ms │
╰────────────┴─────────────┴───────────┴──────────────────────────┴────────┴──────────────╯
--- Test results for package: box_events - END   ---
Done

```

OK

**Comment by djptek** [comment]
##  connect to target data source and ingest data

Screenshot 2022-11-07 at 17 56 20

OK

**Comment by djptek** [comment]
## validate dashboards

### Events (non-shield)

Screenshot 2022-11-07 at 17 49 28

### Shield events

Screenshot 2022-11-07 at 17 58 54

Events OK; Saw non-alert events showing up on Shield Dashboard (BUG) so added a filter

```
{
  "query": {
    "match_phrase": {
      "event.kind": "alert"
    }
  }
}
```

**Review by efd6 — APPROVED** [review]
Thanks

**Pull request merged**
