### PR TITLE
Add missing daemonset.name field

### PR DESCRIPTION
**Pull request by ChrsMark**
## What does this PR do?

Adds missing daemonset.name field to tune according to https://github.com/elastic/beats/pull/26808.

### CODE REVIEW

**Review by mtojek — COMMENTED** [review]
Many doc files are deleted. Is it on purpose?

**Comment by ChrsMark** [comment]
> Many doc files are deleted. Is it on purpose?

It is on purpose yes. Those files are redundant and should be moved after we moved to input_groups.

**Review by mtojek — APPROVED** [review]

**Review by MichaelKatsoulis — APPROVED** [review]

**Comment by ChrsMark** [comment]
@mtojek shouldn't this be automatically moved to snapshot? I don't see any linked PRs 🤔

**Comment by mtojek** [comment]
It will happen if the CI run for master succeeds: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/master/563/

**Pull request merged**
