### PR TITLE
Remove unused visualizations

### PR DESCRIPTION
**Pull request by flash1293**
## What does this PR do?

I noticed there were a bunch of trailing visualizations not used on dashboards - I removed them. The owner teams should make sure this makes sense or whether these visualizations were relied on in some way other than adding them to a dashboard.

### CODE REVIEW

**Comment by gizas** [comment]
From @elastic/obs-cloudnative-monitoring side are you referring to traefik and nginx-ingress-controller ones. Seem good and you can remove those visulaisations. Although not sure 100% if we are the owners of those I approved for those the PR

**Review by gizas — APPROVED** [review]

**Comment by flash1293** [comment]
@elastic/security-external-integrations and @elastic/obs-service-integrations could I please get a review on this?

**Review by andrewkroh — APPROVED** [review]
I don't know of any direct usages of visualizations outside of dashboards so LGTM.

**Comment by andrewkroh** [comment]
💡 I think it would be nice to have a warning in the elastic-package tool for unused visualizations.

**Comment by ruflin** [comment]
++ on having a potential warning for viz without reference @elastic/ecosystem team. In theory, someone could build a package with just a visualisations inside but I'm not aware of any package that has this today.

I really appreciate that @flash1293 opened this PR. But at the same time it would be nice if each time could take the diff out of this PR and open a PR for each package that needs it. This will make sure each team can check the package with the removed visualisations to be valid.

**Comment by flash1293** [comment]
It should be fairly simple to do this check - for each package, see whether the ids of visualizations/searches/lenses/maps show up in the `references` array of another saved object.

**Comment by ruflin** [comment]
To make sure this doesn't get stuck and caught up in conflicts, @andrewkroh @gizas @lalit-satapathy should this PR be merged as is and your team will publish the new versions of the packages or do you pick the changes and open your own PRs.

One thought: Do we really need to increase the version of the packages. I think this is one of the changes where we actually don't need a new release yet of the packages but can wait until a next change happens. Changelog entry is of course still needed.

**Comment by flash1293** [comment]
> One thought: Do we really need to increase the version of the packages. I think this is one of the changes where we actually don't need a new release yet of the packages but can wait until a next change happens. Changelog entry is of course still needed.

In that case the next author needs to remember to adjust the version in the changelog, I don't think this is something that has been done before. Also this cleans up the library, so you could argue it's an improvement for the user (albeit a small one).

**Comment by ruflin** [comment]
@andrewkroh Also fine by me. Can you resolve conflicts and get it in?

**Comment by flash1293** [comment]
Resolved conflicts, @andrewkroh do you know who from @elastic/obs-service-integrations could take a look?

**Comment by ruflin** [comment]
@lalit-satapathy @tommyers-elastic @gizas Could you take a look?

**Comment by gizas** [comment]
Did another round and all seem good! Double checked and there are no references for the above visualisations. Approved

**Comment by ManojS-shetty** [comment]
Hi @flash1293 ,

Just a quick question, Just observed in apache package as we removed the unused visualisation and i saw in the /img directory for a screenshot image for the dashboard contains  the removed visualisation snap. Is that ok here? or we just need to have a dashboard screenshot image which does not show the removed visualisation on the screenshot image.

**Comment by flash1293** [comment]
@ManojS-shetty i guess the screenshots should be updated but it’s unrelated to this pr as the visualization wasn’t part of the dashboard even without my changes.

**Review by ManojS-shetty — APPROVED** [review]
LGTM!

**Pull request merged**
