### PR TITLE
[OSQuery] Fix Field Mapping Conflicts

### LINKED ISSUE #3724: [OSQuery] Non-compliant ECS field mappings causing conflicts
I am seeing that OSQuery has a handful of conflicting fields for logs-*.

1 example: file.elf.sections is type object for .ds-logs-osquery_manager.result-default-2022.07.13-000001 and for .ds-logs-cassandra.log-default-2022.07.05-000003 that type is nested. Looks at ECS, or appears this should be nested not an object.  https://www.elastic.co/guide/en/ecs/current/ecs-elf.html#field-elf-sections

It appears that the .alerts-ecs-mappings component template is the source for the Cassandra logs which again is nested. whereas logs-osquery_manager.result@package mapping is an object.

Wherever .alerts-ecs-mappings are, it will conflict with OSQuery data and it's mappings.

All of the ones in the image are also in scope, where OSQuery templates/mappings are breaking data views. Version 8.3.2 on the stack and latest integrations as of this day of writing. 

Screenshot_20220716-225652_Slack

I am not sure where all of these needed to be updated to the correct ECS mappings so I figured I would start here. 😀

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Fix Field conflicts

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Closes #3724

### CODE REVIEW

**Review by aleksmaus — APPROVED** [review]
Thank you! 👍

**Comment by aleksmaus** [comment]
@legoguy1000 let me know when you are going to merge this. I will have another update to this integration for our upgrade to osquery 5.4.0 which might conflict with some of the files you touched.

**Comment by legoguy1000** [comment]
I can't merge :(.  I'm an outside contributor. But i'll take the access :).

**Comment by aleksmaus** [comment]
Ahh, ok. I'll merge.

**Pull request merged**
