### PR TITLE
[Ceph] Add Integration Package with dashboard

### PR DESCRIPTION
**Pull request by harnish-elastic**
- Enhancement

## What does this PR do?
- Added dashboard and visualizations.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's changelog.yml file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/ceph directory.
- Run the following command to run tests.
elastic-package test

## Related issues

- Relates #4871
- Relates #4930 
- Relates #4963
- Relates #5011
- Relates #5070 
- Relates #5128 
- Relates #5174 
- Relates #5216 

## Screenshots
ceph-overview-dashboard

### CODE REVIEW

**Review by agithomas — COMMENTED** [review]
1. Please change from `Average Client I/O rates operations over time` to  `Client I/O rates over time`. Similarly change to `Client I/O memory utilisation over time`

2. Most active pools : The horizontal axis title to be checked. Should it be Operations / Sec ? Or is it total number of operations ? Since it is a fraction, it should not be Operations. Please remove the word Average from the horizontal axis

3. Used storage over time : I see the graph dropping. Should it be then storage usage rate over time ? Chance of storage value dropping is a real thing? 

4. Please change the title to Pool Disk Overview Pool Disk usage. What is the sort order ? By Usage storage? Can we add a new column : Used percentage ?

5. Please change from Overview of Client I/O rate to Client I/O statistics

**Comment by harnish-elastic** [comment]
> 1. Please change from `Average Client I/O rates operations over time` to  `Client I/O rates over time`. Similarly change to `Client I/O memory utilisation over time`
> 2. Most active pools : The horizontal axis title to be checked. Should it be Operations / Sec ? Or is it total number of operations ? Since it is a fraction, it should not be Operations. Please remove the word Average from the horizontal axis
> 3. Used storage over time : I see the graph dropping. Should it be then storage usage rate over time ? Chance of storage value dropping is a real thing?
> 4. Please change the title to Pool Disk Overview Pool Disk usage. What is the sort order ? By Usage storage? Can we add a new column : Used percentage ?
> 5. Please change from Overview of Client I/O rate to Client I/O statistics

1. Sure, we can change it.
2. Currently the chart is showing the average operations is performed in the pool. The logic is (sum of operations received in pool / number of received doc). As per the logic it should be `Average operations` in X axis. Let me know if you want to remove the `Average` word then let me know you want to change the logic as well.
3. Used storage over time : In pool if the user override/delete the data, the value can be fluctuate. We have performed the same scenario. For the naming convention we are not calculating rate for the Used storage, So not sure why should we change it to rate over time. Let me know what is your thought process, so we can accommodate your suggestions.
4. Sure we can change the title from Pool Disk Overview to Pool Disk usage. Yes, the sort order is by used storage. Also we will add new column as used percentage.
5. Sure we can change it.

**Comment by agithomas** [comment]
> 2\. Currently the chart is showing the average operations is performed in the pool. The logic is (sum of operations received in pool / number of received doc). As per the logic it should be `Average operations` in X axis. Let me know if you want to remove the `Average` word then let me know you want to change the logic as well.

Just need to change the title. No change in the logic required

**Review by kush-elastic — APPROVED** [review]
LGTM

**Comment by agithomas** [comment]
Please refer here :

Kindly change the title to PGs. I assume PGs stand for Placement Groups. Could you consider replacing `PGs` as `Placement Groups`?

image

**Comment by agithomas** [comment]
Suggest to change from `Latency Over Time` to `OSD Performance Latency Over Time`

**Comment by harnish-elastic** [comment]
> Please refer here :
> 
> Kindly change the title to PGs. I assume PGs stand for Placement Groups. Could you consider replacing `PGs` as `Placement Groups`?
> 
> image

Yes, the PGs stand for Placement Groups. Sure we will update the title from `PGs` to `placement groups` across the dashboard.

**Comment by agithomas** [comment]
Can we have Panel having name `storage over time` renamed `Pool Disk Storage Over Time. ` Also, please have it kept near to the panel `Used Storage over time` under `Pool Metrics` section.

**Comment by harnish-elastic** [comment]
> Can we have Panel having name `storage over time` renamed `Pool Disk Storage Over Time. ` Also, please have it kept near to the panel `Used Storage over time` under `Pool Metrics` section.

`storage over time` is related to `cluster storage`. Hence we have kept it in cluster metrics section.

**Review by agithomas — APPROVED** [review]
LGTM!

**Pull request merged**
