### PR TITLE
[Osquery] Osquery Drivers Saved Queries

### PR DESCRIPTION
**Pull request by w0rk3r**
## What does this PR do?

Adds drivers-related saved queries to the OSQuery manager integration to aid investigation

### Screenshots

image

image

### CODE REVIEW

**Comment by tomsonpl** [comment]
@w0rk3r hey! Sorry I've totally missed this PR. Should we reopen and still merge this?

**Comment by w0rk3r** [comment]
@tomsonpl yup!

**Comment by w0rk3r** [comment]
cc @tomsonpl

**Comment by tomsonpl** [comment]
Hey, I've been trying resolve the conflicts, but don't know why I can't get the current version on main... So I just resolved the changelog in github. Hope this helps

**Review by tomsonpl — APPROVED** [review]

**Pull request closed without merging**
