### PR TITLE
Enhance AWS Kinesis Integration Dashboard

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
## What does this PR do?

This PR is to focus on enhancing AWS kinesis integration data collection and dashboard.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Screenshots
Screen Shot 2022-11-07 at 2 27 07 PM

### CODE REVIEW

**Comment by andrewctate** [comment]
Hi @kaiyan-sheng ! This is looking nice.

Could it make sense to replace the existing legacy input controls with dashboard native controls? (documentation: https://www.elastic.co/guide/en/kibana/current/add-controls.html)

**Comment by kaiyan-sheng** [comment]
@andrewctate Thanks for the review! Are you talking about the `Filters` part? I just changed it to use controls like this: 
Screen Shot 2022-11-03 at 11 21 50 AM

**Comment by andrewctate** [comment]
@kaiyan-sheng exactly! Sorry, if you'd already done that... I was just going of the screenshot... haven't yet spun up your changes locally.

**Comment by kaiyan-sheng** [comment]
@andrewctate Oh no I was just testing the new Controls after you pointed it out :) Thank you again!

**Comment by ravikesarwani** [comment]
Kaiyan and I talked about the dashboard and other than a few minor things she will look quickly its a go from my side.

**Review by ravikesarwani — APPROVED** [review]

**Pull request merged**
