### PR TITLE
tenable_sc: add tenable_sc.vulnerability.age field

### LINKED ISSUE #7198: Tenable SC (vulnerability) pipeline feature request: tenable_sc.vulnerability.age
Please add `tenable_sc.vulnerability.age` or `vulnerability.age` derived from (tenable_sc.vulnerability.last_seen - tenable_sc.vulnerability.first_seen) to the `logs-tenable_sc.vulnerability-<version>` pipeline, formatted as days.

possible approach:
```
if(ctx?.tenable_sc.vulnerability.first_seen != null && ctx?.tenable_sc.vulnerability.last_seen !=null ) {ctx.tenable_sc.vulnerability.age = ChronoUnit.DAYS.between(ZonedDateTime.parse(ctx?.tenable_sc.vulnerability.last_seen), ZonedDateTime.parse(ctx?.tenable_sc.vulnerability.first_seen)); }
``` 

Justification: Many audits require the tracking and remediation of vulnerabilities discovered and have Vulnerability Remediation SLAs. Having this value calculated  by the pipeline supports enriched reporting and alerting.

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

Retains a calculated vulnerability age in days from the first and last seen dates.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## Related issues

- Closes #7198

### CODE REVIEW

**Review by chrisberkhout — APPROVED** [review]
Looks good!

For me it seems counterintuitive that a vulnerability doesn't "age" unless it continues to be seen. I might have called it "exposure_duration" or "days_observed" or something. However, "age" was requested by someone who knows Tenable SC and the domain better than I do so I assume it'll be fine. Also the field description is clear.

**Comment by chemamartinez** [comment]
> For me it is counterintuitive that a vulnerability doesn't "age" unless it continues to be seen. I might have called it "exposure_duration" or "days_observed" or something. However, "age" was requested by someone who knows Tenable SC and the domain better than I do so I assume it'll be fine. Also the field description is clear.

Probably when this event arises it is because the vulnerability was detected in the last scan performed, so in theory it would still exist.

**Comment by efd6** [comment]
@jgreene-TrappTech Are you able to comment on the concerns above?

**Comment by efd6** [comment]
Thanks, the second part of the concern is whether events ever come through without a last seen, but with a first seen. Is this ever the case?

For the language and unit choice, I think days is the best given that it matches other fields in the tenable documents.

**Comment by efd6** [comment]
Thanks

**Pull request merged**
