### PR TITLE
Fix skipping Authentication Pipeline in panw panos Integration

### PR DESCRIPTION
**Pull request by mick-lue**
PA Firewalls can use type `AUTH` aswell as `AUTHENTICATION` for AUTH events. Previously, the pipeline for authentication events was only triggered for `AUTHENTICATION`

## Proposed commit message

Fix skipping authentication pipeline for authentication events with type AUTH

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

### CODE REVIEW

**Comment by mick-lue** [comment]
Signed the CLA - not sure where to go from here...

**Review by aleksmaus — CHANGES_REQUESTED** [review]
Seems outdated, version needs to be updated, manifest version change is not included. 
Please update this PR.

**Comment by mick-lue** [comment]
I am on it since today. Got the environment up finally (did the first change via GitHub editor...)

**Comment by mick-lue** [comment]
PR is up to date. Thanks for your patience! Can be tested now I hope

**Review by aleksmaus — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
