### PR TITLE
[O11y][K8] Migrate Deployments dashboard visualizations to lens

### PR DESCRIPTION
**Pull request by kush-elastic**
### Urgency
- High

### Activity Type
- Enhancement

## What does this PR do?
- Manually migrate `K8s Deployments` visualizations to the lens in the current Kibana version `8.10.1` itself. 

- Statistics for `K8s Deployments` Lens migration:
## Migration stats

  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Vizualization | Lens | Vizualization
[Metrics Kubernetes] Deployments | 1 | 4 | 5 | 0

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to the lens.
- [x] I have updated screenshots of the dashboard.
- [X] I have verified that the data counts are matching and panel aggregations are the same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.10.1 itself.

## Related issues

- Relates #7774

Before Migration:
image

After Migration:
image

### CODE REVIEW

**Review by drewdaemon — COMMENTED** [review]
Thanks for doing this. Could we decrease the height of the metric row by about half? That way the numbers will be much closer to the labels.

**Comment by kush-elastic** [comment]
@drewdaemon, according to your comment I have raised a separate issue for tracking the changes related to size of metric visualizations. As already 3 dashboard PRs are merged for Kubernetes, they also require this change.
Link to new issue: https://github.com/elastic/integrations/issues/8308

**Review by rajvi-elastic — APPROVED** [review]
LGTM!

**Comment by kush-elastic** [comment]
@drewdaemon , can you help me review this PR?
I will need to merge this first to proceed with resizing issue.

**Review by drewdaemon — APPROVED** [review]
Thanks!

**Review by gizas — APPROVED** [review]

**Pull request merged**
