### PR TITLE
Allow Rerouting for Windows Integration Package

### PR DESCRIPTION
**Pull request by ChriZzn**
Allow Routing to `logs-*-*` for the Windows Integration Package, otherwise it's not possible to use the Reroute Processor in a Ingest Pipeline to ship Windows logs to a different Dataset/Namespace.

Referring to this Guide:
[https://www.elastic.co/blog/simplifying-log-data-management-flexible-routing-elastic](https://www.elastic.co/blog/simplifying-log-data-management-flexible-routing-elastic
)

### CODE REVIEW

**Comment by marc-gr** [comment]
Hello! The version in manifest.yml and a new changelog.yml entry are required, could you please add these? A minor bump should work for this change.

**Comment by ChriZzn** [comment]
Hi @marc-gr, i updated the changelog and manifest file.

Regards Christoph

**Comment by ChriZzn** [comment]
Any Updates on this?

**Review by marc-gr — DISMISSED** [review]

**Review by leehinman — APPROVED** [review]

**Comment by ChriZzn** [comment]
Hello,
any updates on this? we would already need the change so a timely approval would be very helpful...

Thanks Christoph

**Comment by pierrehilbert** [comment]
@marc-gr could you please review (and approve) again?

**Comment by pierrehilbert** [comment]
@marc-gr any news here?

**Pull request closed without merging**
