### PR TITLE
[Stack Monitoring] update packages dataset

### LINKED ISSUE #3929: [Stack Monitoring] update data streams dataset section
### Summary

Related https://github.com/elastic/kibana/issues/135382

Today the stack monitoring's package writes data to `metrics-{product}.{metricset}-{namespace}` but should write to `metrics-{product}.stack_monitoring.{metricset}-{namespace}` to be more explicit about their purpose. This will help segregate data when PO packages will deliver differently shaped documents for these products.

We can use the [dataset property](https://github.com/elastic/package-spec/blob/10b32dff0212c3c09970171f7702a77d4c3fd55c/versions/1/integration/data_stream/manifest.spec.yml#L108) to specify the new one at the data stream level

- [ ] update elasticsearch metrics data streams
- [ ] update kibana metrics data streams
- [ ] update logstash metrics data streams

### AC
Metrics written by stack monitoring packages are sent to `metrics-{product}.stack_monitoring.{metricset}-{namespace}`

### PR DESCRIPTION
**Pull request by klacabane**
### Summary

Closes #3929

This change updates the datasets of the Stack Monitoring packages to include a stack_monitoring part (ie `elasticsearch.stack_monitoring.node`. The identifier has two purposes: 1) clarify the intent of these datastreams 2) free the stack products namespaces for the upcoming PO initiative. Only the metrics are impacted because logs will be collected similarly in both SM and PO.

The change also bumps elasticsearch, kibana and logstash package to their next major version while keeping their release to experimental until https://github.com/elastic/kibana/issues/120415 is completed. This will allow the packages to be built into the registry so that we don't have to manually build them locally when testing. I thought that metrics mappings being aligned was a relevant milestone for the bump.

### Testing
- Start an elastic-package stack with elasticsearch, kibana and logstash packages installed:
  - We can automate the package installation by providing the right fleet configuration to kibana, and we can use [elastic-package profiles](https://github.com/elastic/elastic-package#elastic-package-profiles) to do that. Let's download a profile that specifically does that. You can skip this step if you want to install the packages manually
  ```
  curl https://drive.google.com/uc\?export\=download\&id\=1aqdqNb9JaYXL-C3WjiT2t58Q65Cl4NIV -L -o /tmp/stack_monitoring-profile.zip && \
  unzip -o /tmp/stack_monitoring-profile.zip -d ~/.elastic-package/profiles && \
  rm /tmp/stack_monitoring-profile.zip
  ```
  - Now cd at the root of the integrations repository and let's build the packages, start the stack with the downloaded profile and also start a logstash service with some predefined pipelines. The command may take a moment to complete and will be done once the logstash service is started, this log message should appear: `Service is up, please use ctrl+c to take it down`
  ```
  (cd packages/elasticsearch && elastic-package build) && \
  (cd packages/kibana && elastic-package build) && \
  (
    cd packages/logstash && elastic-package build && \
    elastic-package stack up -v -d --profile stack_monitoring --version 8.5.0-SNAPSHOT && \
    elastic-package service up -v
  )
  ```
- Start a local Kibana with this change https://github.com/elastic/kibana/pull/137904. See [how to connect a local kibana](https://github.com/elastic/observability-dev/blob/548dfc0c5fe2776af40c1e85adc515c38139b4e5/docs/infra-obs-ui/stack-monitoring_integration-packages.md#connecting-a-local-kibana)
- Open kibana at `http://localhost:5602` and navigate to Stack Monitoring app. Elasticsearch, Kibana and Logstash section should be showing up with all their views populated. Inspect all the views and report anything bizarre
- Verify every stack monitoring `metrics-*` data streams is formatted as `metrics-{product}.stack_monitoring.{metricset}`

### CODE REVIEW

**Comment by crespocarlos** [comment]
For Logstash internal monitoring I had to add the lines below to `packages/logstash/_dev/deploy/docker/config/logstash.yml`

```
monitoring.enabled: true
monitoring.elasticsearch.hosts: https://elasticsearch:9200
monitoring.elasticsearch.username: elastic
monitoring.elasticsearch.password: changeme
```

And for some reason the docker container name is `elastic-package-service-logstash-1`, without `_`.

I've tested this branch using local kibana with changes from https://github.com/elastic/kibana/pull/137904 and everything looks ok, except for this standalone cluster. I'm trying to understand why this is there.
image

I don't see some datastreams like `ml_job` but that's probably because I don't have any ml jobs running

**Comment by crespocarlos** [comment]
Not related to this change but `enrich` consistently fails due to lack of permission. I think the agent user lacks some permissions

image

**Comment by klacabane** [comment]
> For Logstash internal monitoring I had to add the lines below

Are these settings allowing the Agent to collect data or is it publishing data in `.monitoring-logstash` ?

> And for some reason the docker container name is elastic-package-service-logstash-1, without _.

It seems dependent on the docker version you're running which makes the profiles difficult to share and probably not the best approach when it comes to installing packages. @matschaffer has similar issue when testing the elasticsearch package

> except for this standalone cluster

The logstash service defined in _dev [contains a standalone pipeline](https://github.com/elastic/integrations/blob/main/packages/logstash/_dev/deploy/docker/config/pipelines.yml#L6) so that is expected, unless the Standalone Cluster view breaks

**Comment by crespocarlos** [comment]
> Are these settings allowing the Agent to collect data or is it publishing data in .monitoring-logstash ?
I removed those config lines. The problem was actually the wrong logstash host I used. Even with those lines on the config file, `.monitoring-logstash` remains empty.

**Comment by matschaffer** [comment]
Glad to hear it wasn't the settings from https://github.com/elastic/integrations/pull/4018#issuecomment-1237071379 - those would be for internal collection which wouldn't exercise the agent at all.

Also the hyphen and dash is a difference between docker-compose 1 & 2. I was running 1 awhile ago, then switched to 2 to see if it would help at all with `stack up` slowness. You can run `docker-compose version` to check.

This is part of why I'm a little skeptical of the "canned profile" approach and would like to work on better elastic-package level support for additional services used in testing. There's already code in there that deals with docker-compose differences so I think we can probably deal with it at the golang layer more easily.

**Comment by matschaffer** [comment]
Wondering we might have a new issue with the saved profile now. When I try to connect a `main` kibana it seems to fail at this stage:

```
[2022-09-06T13:12:35.789+09:00][INFO ][savedobjects-service] [.kibana] OUTDATED_DOCUMENTS_REFRESH -> UPDATE_TARGET_MAPPINGS. took: 34ms.
[2022-09-06T13:12:35.889+09:00][INFO ][savedobjects-service] [.kibana] UPDATE_TARGET_MAPPINGS -> UPDATE_TARGET_MAPPINGS_WAIT_FOR_TASK. took: 100ms.
{"log.level":"error","@timestamp":"2022-09-06T04:12:44.321Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"APM Server transport error: intake response timeout: APM server did not respond within 10s of gzip stream finish"}
{"log.level":"error","@timestamp":"2022-09-06T04:13:34.146Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"APM Server transport error: error fetching APM Server version: timeout (30000ms) fetching APM Server version"}
[2022-09-06T13:13:35.492+09:00][ERROR][savedobjects-service] [.kibana_task_manager] Action failed with '[timeout_exception] Timed out waiting for completion of [Task{id=19169, type='transport', action='indices:data/write/update/byquery', description='update-by-query [.kibana_task_manager_8.5.0_001]', parentTask=unset, startTime=1662437555506, startTimeNanos=1380955459148883}]'. Retrying attempt 1 in 2 seconds.
[2022-09-06T13:13:35.493+09:00][INFO ][savedobjects-service] [.kibana_task_manager] UPDATE_TARGET_MAPPINGS_WAIT_FOR_TASK -> UPDATE_TARGET_MAPPINGS_WAIT_FOR_TASK. took: 59993ms.
```

**Review by matschaffer — APPROVED** [review]
This seems good to merge. The data stream names are as-expected. I wish we had a more complete stack to test with (ccr, logstash, beats, monitoring), but not sure how easy/hard that'd be with the current setup.

I'm catching some logstash docs that are showing up as "standalone" but they cause the UI just look "blank"

Screen Shot 2022-09-06 at 15 23 18

Screen Shot 2022-09-06 at 15 23 46

But I'm fairly certain that's up to https://github.com/elastic/kibana/pull/137904 to fix.

One thing on my mind for this PR is the logs. I guess they don't really need a `.stack_monitoring` datastream though since the shape won't be changing between now and platform observability.

**Comment by matschaffer** [comment]
Yeah, looks like those are connection errors.

Screen Shot 2022-09-06 at 15 25 55

So we can fix that part up in kibana.

**Comment by matschaffer** [comment]
Ah, and the connection failures are due to `elastic-package-service_logstash_1` (docker compose v1 style) :)

So many little things to iron out here but I think this PR is fine.

**Comment by klacabane** [comment]
Merging - the ghost standalone cluster will be fixed with https://github.com/elastic/kibana/pull/140102

**Pull request merged**
