### PR TITLE
aws.securityhub_findings: Add fields to `_source` as needed by CDR workflows.

### PR DESCRIPTION
**Pull request by kcreddy**
## Proposed commit message
Add `cloud.provider`, `event.kind`, and `observer.vendor` fields to 
`_source` as needed by CDR workflows.

The commit [here](https://github.com/elastic/integrations/commit/0e4409161a73e99763b266042288416edace0599#diff-c17e1251c36fc92221e2d3db57cc560bd80a4cf5d345fd18c6b646af6a458866L39) removed the fields from `_source`. But the fields are required to be 
present in `_source` for Cloud Detection and Response (CDR) workflows. This PR reverts 
the changes made in that commit and re-adds the fields into the ingest pipeline.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## How to test this PR locally

`cd packages/aws && elastic-package stack down && elastic-package build && elastic-package stack up --version=8.16.0-SNAPSHOT -d -v && eval "$(elastic-package stack shellinit)" && elastic-package test pipeline --generate -v --data-streams=securityhub_findings`
```
--- Test results for package: aws - START ---
╭─────────┬──────────────────────┬───────────┬──────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE │ DATA STREAM          │ TEST TYPE │ TEST NAME                                                │ RESULT │ TIME ELAPSED │
├─────────┼──────────────────────┼───────────┼──────────────────────────────────────────────────────────┼────────┼──────────────┤
│ aws     │ securityhub_findings │ pipeline  │ (ingest pipeline warnings test-securityhub-findings.log) │ PASS   │ 322.486291ms │
│ aws     │ securityhub_findings │ pipeline  │ test-securityhub-findings.log                            │ PASS   │ 274.104459ms │
╰─────────┴──────────────────────┴───────────┴──────────────────────────────────────────────────────────┴────────┴──────────────╯
--- Test results for package: aws - END   ---
Done
```

## Related issues

- Relates https://github.com/elastic/security-team/issues/11020

Sample documents after the change:
1. Source index: [_source-updated-document-destination-index.json](https://github.com/user-attachments/files/17590629/_source-updated-document-destination-index.json)
2. Destination index: [_source-updated-document-source-index.json](https://github.com/user-attachments/files/17590630/_source-updated-document-source-index.json)

### CODE REVIEW

**Comment by andrewkroh** [comment]
@maxcold What is the reason that the CDR workflows depend on `_source` instead of [fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html#search-fields-param)? We should not need to sacrifice on storage efficiency.

**Comment by andrewkroh** [comment]
> I can bring it up with the team and have a github issue to track the effort of not relying directly on the _source

I think would be the prudent course of action. We can add these fields into _source as a temporary workaround.

Another important reason to avoid `_source` is [synthetic source](https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-source-field.html#synthetic-source), which is now enabled by default in Serverless as part of LogsDB and will be the default in Elasticsearch in the next major. Every access to `_source` incurs the penalty of synthesizing the _source value from the doc values.

**Comment by efd6** [comment]
To provide context, the relevant PR and comment are [here](https://github.com/elastic/integrations/pull/11158#discussion_r1774354556).

**Review by efd6 — APPROVED** [review]
Approving as a work-around while the world is brought into order.

**Comment by maxcold** [comment]
@andrewkroh here is the issue to track getting rid of `_source` in our queries:
- https://github.com/elastic/kibana/issues/198642

**Pull request merged**
